Limit vertical domain used by COSP
ESCOMP/CAM pull request #1010
Opened 2024-04-17 18:25 UTC by brian-eaton

The COSP simulator was not working with "FMT" compsets.  This compset has a model top of about 1 Pa which is above where the cloud parameterizations operate.  The COSP interface routine was modified so that COSP operates on the same vertical domain as the cloud parameterizations which is set the the namelist variable `trop_cloud_top_press` (1 mb by default).  In addition a lot of code cleanup was done, and a bug fix was made for the layer interface values of height and pressure passed from CAM to COSP.

resolves #967- COSP prevents running "FMT" compsets.

Removed old tools for topo file generation.

resolves #1005 - Remove old topo generation software from CAM

2024-05-06 20:10 UTC, cacraigucar requested changes

2024-05-06 20:10 UTC, cacraigucar commented on src/physics/cam/cospsimulator_intr.F90
> +       cldtot_cal(1:ncol)                = cospOUT%calipso_cldlayer(:,4)
Just curious on why you removed the comments which indicated what CALIPSO variables the CAM variables represent.

2024-05-06 20:10 UTC, cacraigucar commented on src/physics/cam/cospsimulator_intr.F90
> +       y%sunlit(npoints), &
Another allocate which might benefit from error checking

2024-05-06 20:10 UTC, cacraigucar commented on src/utils/hycoef.F90
> +!
Thanks for the clarifying comment!

2024-05-07 21:24 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +       htmlscol_cosp(nlay*nscol_cosp) )
I have added an allocate status check to all allocate calls in this module.

2024-05-07 21:24 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +       )
Done.

2024-05-07 21:28 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +             rain_ls_interp(i,k) = 0._r8
Done.

2024-05-07 21:38 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +
I think I've added the comment you suggested.  Let me know if I missed something.

2024-05-07 22:10 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    call subsample_and_optics( &
I added a hopefully clarifying comment.  Let me know if it could be improved.

2024-05-07 22:51 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +       cldtot_cal(1:ncol)                = cospOUT%calipso_cldlayer(:,4)
This module was full of comments that were either wrong or unhelpful.  A lot of the comments were relevant for the old cosp v1.4 code which we are not using.  Since I couldn't find the arrays referred to in these comments when I searched the cosp code I couldn't see how they were useful.

2024-05-07 22:52 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +       y%sunlit(npoints), &
Done.

2024-05-07 22:58 UTC, brian-eaton commented on src/utils/hycoef.F90
> +!
CAM's grid utility code is not consistent in terms of who is responsible for maintaining the data in the grid and coordinate objects.  Sometimes the object copies the data, and sometimes it just points to it and expects the caller to be sure the data is persistent.  I've shot myself in the foot with this "feature" more than once, including during this refactoring exercise, hence the comment.

2024-05-08 05:56 UTC, gold2718 commented on src/utils/hycoef.F90
> +!
>  I've shot myself in the foot with this "feature" more than once

I would not call it a feature, more of a compromise. I was not smart enough to figure out a consistent way to handle grid memory that always worked.

2024-05-20 22:48 UTC, cacraigucar approved these changes
One minor typo, otherwise my review is complete

2024-05-20 22:48 UTC, cacraigucar commented on src/physics/cam/cospsimulator_intr.F90
> +       y%sunlit(npoints), &
Nice creative way that you presented fieldnames in handle_allocate_error

2024-05-20 22:48 UTC, cacraigucar commented on src/physics/cam/cospsimulator_intr.F90
> +    call subsample_and_optics( &
That sounds great and hopefully will help folks in the future.  "alread" needs the "y" added to it.

2024-06-10 21:47 UTC, nusbaume approved these changes
Great cleanup!  I do have some questions and suggestions, but none of them are really required for this particular PR, so will go ahead and approve it now.

2024-06-12 19:20 UTC, brianpm commented on src/physics/cam/cospsimulator_intr.F90
> +            'NOT SURE WHAT THIS IS Cloud Fraction', flag_xyfill=.true., fill_value=R_UNDEF)
These are temperatures ("TMP").

CLD_CAL_TMP = Calipso Cloud Temperature
CLD_CAL_TMPLIQ = Calipso Liquid Cloud temperature
CLD_CAL_TMPICE = Calipso Ice Cloud temperature
CLD_CAL_TMPUN = Calipso Undefined-Phase Cloud Temperature

2024-06-12 19:25 UTC, brianpm commented on src/physics/cam/cospsimulator_intr.F90
> +            'MODIS Cloud Area Fraction', flag_xyfill=.true., fill_value=R_UNDEF)
Hmm. These are all cloud area fraction. The difference is that they are in different parameter space:
CLMODIS is cloud optical thickness vs cloud-top pressure
CLRIMODIS is cloud optical thickness vs _ice_ effective radius
CLRLMIDOS is cloud optical thickness vs _liquid_ effective radius

Maybe they should be named
MODIS Cloud tau-pressure histogram
MODIS Cloud tau-reffice histogram
MODIS Cloud tau-reffliq histogram
??

2024-06-12 19:36 UTC, brianpm commented on src/physics/cam/cospsimulator_intr.F90
> +          'RH_COSP', flag_xyfill=.true., fill_value=R_UNDEF)
I think these are the state inputs that COSP uses:

PS_COSP = "COSP Surface Pressure"
TS_COSP = "COSP Skin Temperature"
P_COSP = "COSP Pressure (Full)"
PH_COSP = "COSP Pressure (Half)"
ZLEV_COSP = "COSP Height (Full)"
ZLEV_HALF_COSP = "COSP Height (Half)"
T_COSP = "COSP Temperature"
**RH_COSP = "COSP Specific Humidity"** -- @brian-eaton -- The name would hint at relative humidity, but it looks like this is just set to specific humidity. Can you confirm?

2024-06-12 19:38 UTC, brianpm commented on src/physics/cam/cospsimulator_intr.F90
> +    grpl_ls_interp = 0._r8
I don't know. This is a good question, but I would need to look into whether the satellite products think they see graupel.

2024-06-12 19:38 UTC, brianpm commented on src/physics/cam/cospsimulator_intr.F90
> -       call outfld('Q_COSP',         q(1:ncol,1:pver),             ncol,lchnk)
I didn't see the conversion, but maybe it happens somewhere. I asked the same in my response about the names above.

2024-07-01 13:26 UTC, brian-eaton commented on doc/ChangeLog
> +the namelist variable trop_cloud_top_press (1 mb by default).  Changing to
Done.

2024-07-01 13:28 UTC, brian-eaton commented on src/physics/cam/ref_pres.F90
> +   call alloc_err(istat, sub, 'trop_prefi', nlev)
Yes.  Fixed.

2024-07-01 13:31 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    ! The COSP init method was run from cospsimulator_intr_register in order to add
Done.

2024-07-01 13:43 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +       call addfld('MOL532_CAL', (/'trop_pref'/), 'A', 'm-1sr-1', &
Done.

2024-07-01 13:57 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +            'NOT SURE WHAT THIS IS Cloud Fraction', flag_xyfill=.true., fill_value=R_UNDEF)
Updated field long names and units.

2024-07-01 14:05 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    call handle_allocate_error(istat, sub, 'sd_cs,rcfg_cs')
This was to work around a user interface inconsistency which I didn't try to fix in this work.  If the user asked, for example, to just run the lidar and isccp simulators, the run failed because sd_cs and rcfg_cs would not be allocated, but they were still referenced as actual arguments in the call to subsample_and_optics.

2024-07-01 14:45 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +          'RH_COSP', flag_xyfill=.true., fill_value=R_UNDEF)
Updated the long names.  And yes @brianpm, `RH_COSP` is set to specific humidity.  I changed the name to `Q_COSP`.

2024-07-01 14:47 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    !         now donein cosp_init, but these fields are stored in cosp_config.F90.
Fixed.

2024-07-01 14:50 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    ! actual output is specified in cospsimulator1_intr.F90
Done.

2024-07-01 14:59 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    surf_hgt = state%phis(:ncol)/gravit
Done.  No concerns about roundoff changes here since there is already a bug fix related to the height fields input to COSP.

2024-07-01 15:09 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
>      use_precipitation_fluxes = .true.      !!! consistent with cam4 implementation.
`use_precipitation_fluxes` removed.

2024-07-01 15:11 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
>      use_reff = .true.
`use_reff` removed.

2024-07-01 15:21 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> +    cospstateIN%lon             = state%lon(:ncol)*180._r8/pi
Done.  Defined parameter `rad2deg`.

2024-07-01 15:32 UTC, brian-eaton commented on src/physics/cam/cospsimulator_intr.F90
> -       call outfld('Q_COSP',         q(1:ncol,1:pver),             ncol,lchnk)
COSP takes specific humidity as an input.  I replaced `RH_COSP` (which was set to specific humidity) by `Q_COSP` in the history output.

2024-07-01 21:53 UTC, merged