CCPP'ize dadadj
ESCOMP/CAM pull request #1026
Opened 2024-05-06 16:10 UTC by jtruesdal

Refactor dadadj parameterization for inclusion in the CCPP framework.  On the CAM side this entails moving the core parameterization over to atmos_phys and updating the dadadj_cam interface file to call the new library routine.  There are additional mods to cime and ccs_config that are needed for the CAM-SIMA dadadj CCPP validation.

2024-06-01 19:59 UTC, nusbaume requested changes
Looks good!  Just had a couple of concerns related to the new error message generation.

2024-06-01 19:59 UTC, nusbaume commented on Externals_CAM.cfg
> +branch = dadadj
Just adding the usual reminder to point to a tag once ESCOMP/atmospheric_physics#91 has been approved and merged.

2024-06-01 19:59 UTC, nusbaume commented on src/physics/cam/dadadj_cam.F90
> +           state%lat(errflg)*180._r8/pi, state%lon(errflg)*180._r8/pi
I believe this error message could fail if the `errflg` is being returned via a bad `allocate` call in `dadadj_run`.  Maybe it would be worth checking the `errmsg` string (say via the ["index" function](https://gcc.gnu.org/onlinedocs/gfortran/INDEX-intrinsic.html)) for the word "Allocate", and then only if that word is absent use the `errflg` as the physics column index?

2024-06-01 19:59 UTC, nusbaume commented on src/physics/cam/dadadj_cam.F90
> +      write(errstring, *) errmsg,' at lat,lon:', &
Should `errmsg` be trimmed here?  Otherwise I think it is technically the same length as `errstring`, and so it could cause problems when the additional text is being added to `errstring` via this write statement.

2024-06-04 17:49 UTC, jtruesdal commented on src/physics/cam/dadadj_cam.F90
> +           state%lat(errflg)*180._r8/pi, state%lon(errflg)*180._r8/pi
I'll change the dadadj error to read  'Convergence failure at column i, zeps > 1.e-4 (errflg set to failing column index)'.  Any other users of this scheme could then use that value to back out location info.  I will also add a check for the word 'Convergence' and appended the additional error info on lat/lon if found.

2024-06-04 18:46 UTC, cacraigucar reviewed
I found it easier to review this along with the atmospheric_physics PR.

2024-06-04 18:46 UTC, cacraigucar commented on src/physics/cam/dadadj_cam.F90
> +   ptend%s(:ncol,:) = ptend%s(:ncol,:) * cpairv(:ncol,:,lchnk)
@nusbaume - Just wanting to confirm our definition of `tendency_of_air_temperature`?  Is it without out the cpairv adjustment?  If so, we may want to augment the conversion document to indicate the ptend%s special adjustment?

2024-06-21 15:50 UTC, jtruesdal commented on src/physics/cam/dadadj_cam.F90
> +      write(errstring, *) errmsg,' at lat,lon:', &
Trimmed.

2024-06-21 15:50 UTC, jtruesdal commented on src/physics/cam/dadadj_cam.F90
> +           state%lat(errflg)*180._r8/pi, state%lon(errflg)*180._r8/pi
Changed.

2024-06-21 16:07 UTC, nusbaume commented on src/physics/cam/dadadj_cam.F90
> +   ptend%s(:ncol,:) = ptend%s(:ncol,:) * cpairv(:ncol,:,lchnk)
Yes, `tendency_of_air_temperature` is basically the change in `state%t` (or air temperature), while `ptend%s` is technically the `tendency_of_dry_air_enthalpy_at_constant_pressure`, which in CAM we use to calculate the change `state%t` in `physics_update` by dividing by `cpairv`.  So in other words:

`ptend%t = ptend%s / cpairv`

or in standard name lingo:

```
tendency_of_air_temperature = tendency_of_dry_air_enthalpy_at_constant_pressure / composition_dependent_specific_heat_of_dry_air_at_constant_pressure
```

Hopefully that makes sense?  If not just let me know.  Regardless I can say that I am pretty sure this new CAM code is correct as-is.

2024-07-08 23:49 UTC, cacraigucar requested changes

2024-07-08 23:49 UTC, cacraigucar commented on .gitmodules
> +        fxtag = dadadj
Once this is updated, then we can schedule this to go into CAM

2024-07-30 00:37 UTC, cacraigucar approved these changes

2024-08-17 03:30 UTC, merged