Change name of physics package 'cam_dev' to 'cam7'
ESCOMP/CAM pull request #1028
Opened 2024-05-07 12:54 UTC by brian-eaton

#813 - Introduce "-phys cam7" and remove "-phys cam_dev".  
Related changes:
- The compset tokens CAM%DEV are replaced by CAM70
- The src/physics/cam_dev/ directory is renamed src/physics/cam7
- No compset names were changed.

N.B.: This PR depends on a CMEPS tag to make the corresponding change of CAM%DEV to CAM70 in buildnml

. resolves #813

2024-05-21 17:36 UTC, cacraigucar requested changes

2024-05-21 17:36 UTC, cacraigucar commented on bld/configure
> +}
Should there be a check that a user is using cam7 if they specify model_top?  I could see a naïve user wanting to use 'lt' or 'mt' with cam5 or cam6, especially for comparison purposes.  Do we want to prohibit this or would things work okay?

2024-05-21 17:36 UTC, cacraigucar commented on doc/ChangeLog
> +Tag name:
This will be cam6_4_001 whenever it comes in

2024-05-21 18:17 UTC, gold2718 commented on doc/ChangeLog
> +Tag name:
Out of curiosity, if you are introducing CAM7 to the world, why isn't this cam7_0_001?

2024-05-21 18:33 UTC, cacraigucar commented on doc/ChangeLog
> +Tag name:
I am reserving cam7_0_000 for when we make our release branch, which is still quite a ways off.  I found it useful with the last release that cam6_0_001 was the first tag which wasn't in the release.

2024-05-22 16:03 UTC, brian-eaton commented on bld/build-namelist
> -
The variable `do_clubb_sgs` is not meant to be user settable since turning on clubb is a build-time decision.  This variable is similar to, for example, `cam_physpkg` which is communicating build-time information to the run-time environment.  `build-namelist` has checks that the user doesn't try to set
`cam_physpkg` and similar variables.  I will add a similar check for `do_clubb_sgs` and update the documentation in the definition file.

2024-05-22 16:11 UTC, brian-eaton commented on bld/configure
> +}
I agree that we should restrict this option to cam7.  Currently the only use of the `lt`/`mt` `model_top` settings are as attributes in the `namelist_defaults_cam.xml file`.  They are being used to distinguish cam7 settings from previous cam versions.  For example, cam6 is a low top model, but `model_top='lt'` is used to distinguish cam6 from cam7 settings for some GWD variables and an SE variable.

I will add the check in `configure` that you suggested.  I will also modify the compset matching in `config_component.xml` by changing `_CAM.*%LT` to `_CAM70%LT` and similarly for `%MT`.

2024-05-24 22:51 UTC, cacraigucar approved these changes

2024-05-31 03:32 UTC, nusbaume approved these changes

2024-06-07 18:14 UTC, cacraigucar commented
Please update the CICE external to be cesm_cice6_5_0_10.  This will eliminate you from seeing components/cice being "modified".  This tag was made after I started up my regression runs for cam6_3_162.

2024-06-20 15:24 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> -      <machine name="derecho" compiler="intel" category="prealpha"/>
@PeterHjortLauritzen and @adamrher  - I don't believe we are dropping support for running CAM7 with the FV dycore, correct?  Since I also believe we are not supporting 32 levels in CAM7, do we need to create initial condition files for at least the LT case for the various grids?  The reason I am asking is that it appears that with Brian's changes to move to CAM7, we no longer have any FV tests with CAM7.

2024-06-20 15:33 UTC, PeterHjortLauritzen commented on cime_config/testdefs/testlist_cam.xml
> -      <machine name="derecho" compiler="intel" category="prealpha"/>
No we are not supporting FV with CAM7. FV should only be supported for CAM4,5,6 configurations.

2024-06-22 04:18 UTC, nusbaume approved these changes
Looks good!  I did want to note though that the `resolves #XXX` text should be added to the main PR  description box on Github for all of the additional issues that were fixed so that they can be closed automatically once the PR has been merged.  Thanks!

2024-06-26 12:09 UTC, merged