Add updated ncdata and bnd_topo files for MPASv8
ESCOMP/CAM pull request #1029
Opened 2024-05-13 15:17 UTC by gdicker1

The new initial condition files contain fields that are expected by routines in cam_dev (cam7) physics. The new topo files were regenerated due to changes in the NCAR/Topo software. These files are only used when `phys="cam_dev"` to ensure previous compsets and/or tests aren't affected.

These files were checked for NaNs and runs were attempted for the `F2000dev` compset before making this PR.

Fixes #995

2024-07-25 22:08 UTC, cacraigucar requested changes

2024-07-25 22:08 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa30"  nlev="32" analytic_ic="1" phys="cam_dev" >atm/cam/inic/mpas/mpasa30_L32_notopo_coords_c240507.nc</ncdata>
The newly added files in this files are not in the derecho inputdata nor in the svn repository.  Please make sure they have the mandatory metadata described here: https://www.cesm.ucar.edu/models/cam/metadata

2024-07-25 23:31 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa30"  nlev="32" analytic_ic="1" phys="cam_dev" >atm/cam/inic/mpas/mpasa30_L32_notopo_coords_c240507.nc</ncdata>
Thanks for the reminder, I'll double-check. I'll work with Chris Fischer to get this data added and will update here when it's done.

2024-07-26 17:54 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa30"  nlev="32" analytic_ic="1" phys="cam_dev" >atm/cam/inic/mpas/mpasa30_L32_notopo_coords_c240507.nc</ncdata>
@cacraigucar, the files have been put in the correct location on Derecho and the SVN repo. Thanks to @fischer-ncar for the assist.

2024-07-26 17:56 UTC, gdicker1 commented
> 3. * [ ]  Update branch w/ `cam_development` work
>    1. * [x]  (If not already) update references of `cam_dev` to `cam7` when [cam6_4_001: Change name of physics package 'cam_dev' to 'cam7' #1028](https://github.com/ESCOMP/CAM/pull/1028) is merged
> 4. * [ ]  Run test suite and record results

At this point 3.1 has been addressed by [b608af1](https://github.com/ESCOMP/CAM/pull/1029/commits/b608af1db20f1cfcdb70112ba0fa21223f4b8549). I plan to proceed with step 3 and 4 once I have a tag number or directed otherwise.

2024-07-30 14:57 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
Hi @gdicker1 as you are only adding analytic_ic entries, I think you can just replace the existing L32 notopo files with the new cam7 files. If you ran cam6 with analytic_ic's, I think the solutions would be bfb to running with the new cam7 files.

2024-07-30 21:29 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
Thanks @adamrher, I'll make that adjustment. That tracks with the (lack of) difference I remember between the files.

I think it would be good to still have the real-data files only apply for `cam7` physics. What do you think?

2024-08-12 23:09 UTC, cacraigucar approved these changes

2024-08-13 16:07 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
Sorry for the late reply. Yes, I agree with providing real-world files for ```cam7``` to resolve this issue, but it should be for the L58 and L93 grids (not L32). One way to do this is to generate an L58/L93 analytic_ic topo_coords file, run for a year and dump out a new cam.i.* file by setting ```inithist = 'YEARLY'```. The year long run will remove most of the memory from the analytic_ic so it should be "real world" at that point. Happy to help, just let me know.

2024-08-13 18:30 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
I'm wondering about the need for L58 and L93 grids in this PR?

As near as I can tell, using cam7 physics still defaults to 32L and these coarse resolutions would help get some of those cases running. These resolutions can also help with transitioning the tests that use MPAS dycore to cam7 physics.

(However, I will generate files at other vertical levels as soon as possible. And thanks for the tip about long runs to create ICs!)

2024-08-13 20:04 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
cam7 physics is not intended to be run with L32, that's a cam6 grid (physics versions are tied to a specific set of vertical grids). cam7 is intended to be run with 58/93 levels. When I first introduced cam_dev (now cam7) I made a F2000dev compset that used 32 levels because we didn't have any 58/93 level support in CAM. But now that we do (e.g., FLTHIST and FMTHIST compsets), the F2000dev compset will be deprecated in the near future (we almost got rid of it a couple weeks ago, but decided to keep it for the time being).

I think sticking with L32/cam7 is just creating an extra step down the road to move to L58 real data inic. I don't find L58 prohibitive for getting cases running but perhaps you are running against some other issues I'm unaware of (like EarthWorks wanting to use L32?).

2024-08-13 20:24 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
Gotcha, thanks for the extra context! I was getting the idea that cam7 allowed 32L from the files in this PR as well as [these lines in the bld/configure script](https://github.com/ESCOMP/CAM/blob/eb275095c52e54b00c55191b6ab7bca614004a57/bld/configure#L1349-L1350).

I see your point and agree that putting off these files just creates another bit of work. There's no other issues I know of that makes L32 more attractive than L58.

2024-08-13 20:42 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
Ah, thanks for pointing me to that setting in configure. That will get updated when we remove the F2000dev compset.

2024-08-15 20:29 UTC, gdicker1 commented
@adamrher could you take a look at this and see if it matches the files you expect? I want to make sure before I try to get these added to the CESM data repo.

This PR now:
- Replaces the L32 analytic_ic files with updated versions
    - the "*_topo_*" file here uses the new bnd_topo
- Adds notopo files for product {mpasa480, 120, 60, 30} x {58L, 93L}
- Adds new real-data IC files for the product {mpasa480, 120} x {58L, 93L}
   - these use the new bnd_topo below
   - generated using the MPAS init_atmosphere core to add CSFR initial conditions from 2000-01-01T00:00:00Z[^1]
- Adds 2 new bnd_topo files for mpasa480 and mpasa120

[^1]: I couldn't get ctsm to use the correct files for mpasa480 and generate from analytic_ic.

2024-08-16 14:42 UTC, adamrher reviewed
@gdicker1 I have some comments to be addressed. 

I have a more general concern. I don't know why we would need analytic_ic topo_coords ncdata files if we are supporting the real world ncdata files. There is no need to ever run with analytic_ic, which is not realistic (the winds are 0), if we support the real world data files. It's just clogging up the xml file, IMO. Pinging @jtruesdal for his feedback.

2024-08-16 14:42 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" analytic_ic="1" phys="cam7" >atm/cam/inic/mpas/mpasa120_L32_topo_coords_c240508.nc</ncdata>
I don't think you need separate entries for cam6 and cam7 for mpasa120 L32 topo_coords? Wouldn't it be cleaner to just have one entry with no physics specifier?

2024-08-16 14:42 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" phys="cam7" >atm/cam/inic/mpas/cami_01-01-2000_00Z_mpasa120_L32_CFSR_c240508.nc</ncdata>
Can you verify that this mpasa120 L32 cam7 file works for cam6? If so, then can we remove the cam7 entry entirely, and just use this cam7 file for the previous entry w/o any physics specifier?

2024-08-16 14:42 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
I don't like having multiple topos file for the same mpasa120 grid. I presume you are keeping this because there is still an nlev=70 ncdata entry for mpas120 that is based on this old topo file? I gotta say, I don't know who is running that configuration, but I'd vote for removing that nlev=70 ncdata entry above (atm/waccm/ic/mpasa120km.waccm_fulltopo_c220818.nc) and this bnd_topo entry.

@jtruesdal do you have any intel on this file or why would need it?

2024-08-16 14:42 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" phys="cam7" >atm/cam/topo/mpas/mpasa120_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_20240507.nc</bnd_topo>
Once we deal with the nlev=70 file and corresponding bnd_topo file, remove all physics and analytic_ic modifiers and collapse this to one single entry.

2024-08-16 15:24 UTC, gdicker1 commented
@adamrher

> I don't know why we would need analytic_ic topo_coords ncdata files if we are supporting the real world ncdata files.

I'm unsure why too. This 32L topo_coords file was added here because my original motivation was to just replace/update the existing files. It can be removed easily.

2024-08-16 15:24 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" phys="cam7" >atm/cam/topo/mpas/mpasa120_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_20240507.nc</bnd_topo>
Agreed.

2024-08-16 15:24 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
Yep, that is why. I didn't want to break something for someone else's project or needs. If it's not needed, I can definitely remove the files.

2024-08-16 15:24 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" phys="cam7" >atm/cam/inic/mpas/cami_01-01-2000_00Z_mpasa120_L32_CFSR_c240508.nc</ncdata>
Yep, let me check!

2024-08-16 15:24 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" analytic_ic="1" phys="cam7" >atm/cam/inic/mpas/mpasa120_L32_topo_coords_c240508.nc</ncdata>
I think when the previous topo_coords file was added the physics specifier was used since `use_topo` isn't known before processing the namelist_defaults_cam.xml either. If the specifier is removed, there would be no difference between the notopo_coords and topo_coords files so the earlier file would always be chosen automatically.

2024-08-16 15:34 UTC, gdicker1 commented
@adamrher

I also wanted to see what you thought of this point:

> [the real data ICs were] generated using the MPAS init_atmosphere core to add CSFR initial conditions from 2000-01-01T00:00:00Z

I've been told that some tracers and other fields would be missing if I didn't create the file from a year-long run (as you suggested before).

If this is a problem, I think it would be easier to drop mpasa480 cami\*.nc and bnd_topo files from this PR than for me to figure out the CLM files needed for mpasa480. Then I could do what's needed to generate the correct mpasa120 ncdata.

2024-08-16 15:35 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" analytic_ic="1" phys="cam7" >atm/cam/inic/mpas/mpasa120_L32_topo_coords_c240508.nc</ncdata>
Good point. What about heeding my suggestion to remove analytic_ic support for topo_coords files that also have real world ncdata files? The only time you should run L32 mpasa120 with analytic_ic would be for aqua-planets or simple physics cases (i.e., no topo). If running real world cases, always use the real world ncdata file. Would that resolve the conflict?

2024-08-16 15:41 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" analytic_ic="1" phys="cam7" >atm/cam/inic/mpas/mpasa120_L32_topo_coords_c240508.nc</ncdata>
Agreed and agreed, I'll remove the file.

An average user should only get analytic_ic for aqua-planet or simple physics, and a dev or "power user" could find their own topo_coords file or just use one of the real world ncdata with analytic_ic.

2024-08-16 15:41 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
OK, as I wait for some intel on the mpasa120 nlev=70 case, can we remove the old mpas480 bnd_topo, and the corresponding old mpasa480 L32 real world ncdata file (and remove the cam7 specifier for the new mpasa480 L32 real world ncdata file and from the new mpasa480 bnd_topo entry)?

In short, I want to remove all the old ncdata files based on the old topography, so that we're not supporting multiple bnd_topo files for each grid.

2024-08-16 15:47 UTC, adamrher commented
As long as the CFSR ncdata files work for a real world case, then I say move forward with the CFSR file. If the model doesn't complain, and some tracers are missing, then the model will probably initialize them to zero which is fine by me.

What's the issue with mpasa480? It looks there is CTSM support for F2000climo/dev, but not FHIST.

2024-08-16 15:58 UTC, gdicker1 commented
Moving forward sounds good, these files can always be replaced if they cause a problem.

> CTSM support for F2000climo/dev, but not FHIST

This was my problem, I was trying to use FLTHIST and didn't consider the F2000 compsets.

2024-08-16 16:07 UTC, jtruesdal commented
I do not know what the analytic ic topo cases are for and would agree that they seem to be unneeded.  The analytic no topo (just vertical coordinates) are used and they also provide a way to run a new grid or start the model using a standard atmosphere initial condition.

2024-08-16 16:22 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
At one time we were coordinating with the land group (I think Erik put the initial list together) to define supported resolutions.  If we are thinking of pruning that set then we should coordinate with the other groups on that list. 
As for the 120 resolution, I think when we put together the initial set of resolutions for the MPAS port we chose to support resolutions that other dycores routinely ran (.25, .5, 1, 2 degree).  Other than the choice for the initial resolution set I don't have any more intel about this file.

2024-08-16 16:35 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
Thanks for the history on this John. Let's not prune anything, just replace and enhance. [My grids document](https://docs.google.com/spreadsheets/d/1Osq56e423CF107zhoNQ0VS7-iH_JXLF9AtCvBdXyfJ4/edit?usp=sharing) is consistent with the plans that you recall, and Erik populated the CLM column more recently.

Dylan what would you need to make a L70 ncdata file based on CFSR and the new mpasa120 bnd_topo? The zeta level file (e.g., levels_70.txt)? I could then test it in a WACCM compset to make sure it runs.

2024-08-16 16:38 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
Adam, if a file with the levels is handy that would help but not needed. If not, I can take the vertical levels from a column above the sea in the existing file.

2024-08-16 16:46 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" >atm/cam/topo/mpas/mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc</bnd_topo>
I cc'd you on the email but got an auto response that Bill's out until Aug 26. So I'd proceed without the zeta file. I did find a L70 file in his directory but I'm not sure it's the correct one (/glade/u/home/skamaroc/MPAS_vertical_grids/standard_levels_70.3.txt).

2024-08-16 16:55 UTC, gdicker1 commented
> the vertical coordinate is a function of ncol and therefore must be consistent with the horizontal grid you're running

This is my understanding with MPAS. We get horizontal grid info from meshes generated by code not in the main MPAS-Model repo. It's easy to add vertical levels to that. I don't think that it would be efficient to do the Voronoi tessellation online (especially for high resolution) to run MPAS from only a set of vertical levels.

2024-08-16 17:12 UTC, adamrher commented
Dylan I think what @jtruesdal is referring to is that, for example with the se dycore, when you want to run a new grid and you don't have an inic file, you can add a new grid entry in ccs_config/ pointing to a new ESMF mesh file (meaning you're supplying the new grid, not generating it in a run), and then run with analytic_ic. For the se dycore (and all but mpasa, maybe), the ncdata file only needs to have vertical level information, and the analytic_ic's are generated in the horizontal using the supplied mesh file and analytic_ic code in src/dynamics/. That's why there are only three coordinate files in the analytic_ic section (L26, L30, L32); they work for any arbitrary horizontal grid/dycore.

For no_topo mpasa, I think the zgrid is identical for every grid column. But I wouldn't be surprised if mpasa requires analytic_ic to have a ncdata file on the horizontal grid, which is indicated by the comments in the mpasa analytic_ic section of namelists_defaults.xml.

2024-08-16 17:20 UTC, jtruesdal commented
> Is this true for mpasa coords files? I had thought that the vertical coordinate is a function of ncol and therefore must be consistent with the horizontal grid you're running? If this is not the case, than we only need one analytic_ic ncdata file for each vertical grid, as they would work for any arbitrary mpasaXXX grid.

The MPAS vertical coordinate is height based so does have a dependence on the height of each ncol.  The mpass coords files are very useful for aquaplanet cases where there is no topo.  As you mentioned then we only need one coord file for each supported vertical resolution.  I've also generated quick initial condition files from the aquaplanet runs that I've also used for non-aquaplanet cases.

2024-08-16 17:42 UTC, gdicker1 commented
Thanks for explaining, my understanding of CAM/CESM was off. It seems to me the reason is:
1. MPAS separates the logic for vertical levels into the init_atmosphere core (may be easy to adapt in the CAM interface)
2. As they are created by `mpas2esmf` now, ESMF and SCRIP files in CESM don't have the horizontal grid info MPAS-A would need. (I think non-trivial amount of work, bigger discussion needed here)

2024-08-19 22:38 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" analytic_ic="1" phys="cam7" >atm/cam/inic/mpas/mpasa120_L32_topo_coords_c240508.nc</ncdata>
Removed in https://github.com/ESCOMP/CAM/pull/1029/commits/939a92d7615b4d1954be230f25f71bdd8c298293

2024-08-19 22:46 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="mpasa120" phys="cam7" >atm/cam/topo/mpas/mpasa120_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_20240507.nc</bnd_topo>
These have been collapsed and specifiers removed in [9afb3cd](https://github.com/ESCOMP/CAM/pull/1029/commits/9afb3cdf7eb8e125fd9e70541338bb458fb96d26)

One entry with the old mpas120 bnd_topo is kept since the mpas120km.waccm_fulltopo_c220818.nc file still uses it (confirmed with a FWsc2000climo case). The same specifiers are now used to match this ncdata and bnd_topo.

2024-08-19 22:52 UTC, gdicker1 commented
After pushing [939a92d](https://github.com/ESCOMP/CAM/pull/1029/commits/939a92d7615b4d1954be230f25f71bdd8c298293), [9afb3cd](https://github.com/ESCOMP/CAM/pull/1029/commits/9afb3cdf7eb8e125fd9e70541338bb458fb96d26), and [24012df](https://github.com/ESCOMP/CAM/pull/1029/commits/24012df14922fcf45dc1ab9e78f57f43c1e6c21d). The remaining work seems to be:

- [ ] Generate an entry to replace mpas120km.waccm_fulltopo_c220818.nc
- [ ] Replace mpasa120 waccm ncdata with new file, remove mpas_120_nc3000_Co060_Fi001_MulG_PF_Nsw042_c200921.nc bnd_topo entry
- [ ] Push approved files to CESM data repository
- [ ] Prepare to test, merge in cam_development
- [ ] Do `aux_cam` testing

2024-09-05 23:19 UTC, gdicker1 commented
@adamrher @jtruesdal @cacraigucar, I'm looking for another round of reviews or comments on this. Once any changes are made and this PR approved, I will ask for help getting the files below added to CESM data.

Files to add to atm/cam/inic/mpas (12):
-  mpasa120_L58_notopo_coords_c240814.nc
-  mpasa120_L93_notopo_coords_c240814.nc
-  mpasa30_L58_notopo_coords_c240814.nc
-  mpasa30_L93_notopo_coords_c240814.nc
-  mpasa480_L58_notopo_coords_c240814.nc
-  mpasa480_L93_notopo_coords_c240814.nc
-  mpasa60_L58_notopo_coords_c240814.nc
-  mpasa60_L93_notopo_coords_c240814.nc
-  cami_01-01-2000_00Z_mpasa120_L93_CFSR_c240814.nc
-  cami_01-01-2000_00Z_mpasa120_L58_CFSR_c240814.nc
-  cami_01-01-2000_00Z_mpasa480_L58_CFSR_c240814.nc
-  cami_01-01-2000_00Z_mpasa480_L93_CFSR_c240814.nc

Files to add to atm/waccm/ic (1):
-  mpasa120_L70.waccm_topography_SC_c240904.nc

Accessible on Derecho, within sub-dirs of: "/glade/derecho/scratch/gdicker/2024Jun04_CAMMPASv8Grids_2/files_for_cesmdata3"

2024-09-10 15:04 UTC, adamrher approved these changes
Looks great Dylan, thanks for doing this!

2024-09-11 00:16 UTC, gdicker1 commented
Commit https://github.com/ESCOMP/CAM/pull/1029/commits/a0db53f82ce7646608b278661cfcde5ae2de1d73 is a convenience for me as I bring in these changes to EarthWorksOrg/CAM as well. EarthWorksOrg/CAM is currently based on cam6_4_030.

2024-09-13 19:33 UTC, merged