replace L93 ncdata files w/ corrected versions
ESCOMP/CAM pull request #1040
Opened 2024-05-23 17:58 UTC by adamrher

Fixes #1034 

@jtruesdal I'm requesting your review because you had introduced these files in https://github.com/ESCOMP/CAM/pull/815, and I would like your advice on how to rename these files.

2024-06-17 19:39 UTC, cacraigucar requested changes
Just a reminder, that the mandatory metadata needs to be added to these files.  See: https://www.cesm.ucar.edu/models/cam/metadata

2024-06-20 16:19 UTC, jtruesdal requested changes
@adamrher I've added the metadata and renamed the files.  Here are the recommended changes.  I'll push these to the data repo once the PR is approved.

2024-06-20 16:19 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne3np4"   nlev="93"  aquaplanet="1" ic_ymd="101" >/glade/derecho/scratch/aherring/restart/L93v2/cam6_3_153_QPC6_ne3pg3_ne3pg3_mg37_36pes_240518_L93v2.001.cam.i.0001-02-01-0000
```suggestion
<ncdata dyn="se" hgrid="ne3np4"   nlev="93"  aquaplanet="1" ic_ymd="101" >atm/cam/inic/se/cam6_QPC6_aqua_ne3pg3_mg37_L93_01_02_01_c240518.nc</ncdata>
```

2024-06-20 16:19 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne3np4"   nlev="93"             ic_ymd="101" >/glade/derecho/scratch/aherring/restart/L93v2/cam6_3_153_FMTHIST_ne3pg3_ne3pg3_mg37_36pes_240517_L93v2.001.cam.i.1979-02-01-00000
```suggestion
<ncdata dyn="se" hgrid="ne3np4"   nlev="93"             ic_ymd="101" >atm/cam/inic/se/cam6_FMTHIST_ne3pg3_mg37_L93_79-02-01_c240517.nc</ncdata>
```

2024-06-20 16:19 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne30np4" npg="3" nlev="93">/glade/derecho/scratch/aherring/restart/L93v2/c153_ne30pg3_FMTHIST_x02.cam.i.1990-01-01-00000.nc</ncdata>
```suggestion
<ncdata dyn="se" hgrid="ne30np4" npg="3" nlev="93">atm/cam/inic/se/c153_ne30pg3_FMTHIST_x02.cam.i.1990-01-01-00000_c240618.nc</ncdata>
```

2024-06-20 16:19 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne30np4" nlev="93" chem="trop_strat_mam5_vbs">/glade/derecho/scratch/aherring/restart/L93v2/f.cam6_3_160.FCMT_ne30.moving_mtn.001.cam.i.1996-01-01-00000.nc</ncdata>
```suggestion
<ncdata dyn="se" hgrid="ne30np4" nlev="93" chem="trop_strat_mam5_vbs">atm/cam/inic/se/f.cam6_3_160.FCMT_ne30.moving_mtn.001.cam.i.1996-01-01-00000_c240618.nc</ncdata>
```

2024-06-20 19:08 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne30np4" nlev="93" chem="trop_strat_mam5_vbs">/glade/derecho/scratch/aherring/restart/L93v2/f.cam6_3_160.FCMT_ne30.moving_mtn.001.cam.i.1996-01-01-00000.nc</ncdata>
Thanks John.

2024-06-24 15:51 UTC, cacraigucar commented
Just checking to see which of you is going to make the changes the @jtruesdal provided.  Once that is done, I can complete my review and schedule this for CAM tagging.

2024-06-24 16:27 UTC, jtruesdal commented
@adamrher @cacraigucar I'll make the changes.  Just checking with Adam to see if I have the correct permissions to merge.

2024-06-24 18:08 UTC, cacraigucar approved these changes

2024-06-28 17:22 UTC, jtruesdal approved these changes

2024-06-28 17:47 UTC, merged