Remove manage externals
ESCOMP/CAM pull request #1052
Opened 2024-06-01 21:01 UTC by jedwards4b

Superceeds #989 
Replace manage externals with git-fleximod.

2024-06-04 17:19 UTC, cacraigucar requested changes

2024-06-04 17:33 UTC, jedwards4b commented on .gitignore
> -components
These are removed because I believe you want to see the changes in submodules.  Why are cice and chem_proc modified?

2024-06-04 17:40 UTC, cacraigucar commented on .gitignore
> -components
A `git status` in cice yields:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cime_config/__pycache__/
```

Inside chem_proc:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        campp
```

2024-06-04 18:58 UTC, jedwards4b commented on .gitignore
> -components
I think that if you want to change .gitignore to handle these you should do that explicitly:
__pycache__
campp

2024-06-06 19:49 UTC, cacraigucar approved these changes

2024-06-07 18:08 UTC, merged