fix CLUBB interface bug
ESCOMP/CAM pull request #1054
Opened 2024-06-04 22:56 UTC by PeterHjortLauritzen

fixes https://github.com/ESCOMP/CAM/issues/1053

2024-06-06 11:22 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
I'm curious why make this fix in place here instead of fixing `set_wet_to_dry` in physics_types.F90?
The "broken" `set_wet_to_dry` is still called in `vertical_diffusion_tend` which is called in `tphysac`.

2024-06-06 23:41 UTC, PeterHjortLauritzen commented on src/physics/cam/clubb_intr.F90
What the subroutine `set_wet_to_dry` does would be clearer if it was named `undo_set_dry_to_wet` or `revert_set_dry_to_wet`

Explanation:

subroutine `set_dry_to_wet` does as the subroutine name suggests: it converts mixing ratios that are dry (```(cnst_type(m).eq.'dry')```) to wet. 

subroutine `set_wet_to_dry` undoes this operation by converting the tracers that are supposed to be dry back to dry (from wet).

set_wet_to_dry does NOT convert wet tracers to dry as the name seems to imply: here is the code from set_wet_to_dry

```
  do m = 1,pcnst
     if (cnst_type(m).eq.'dry') then
        state%q(:ncol,:,m) = state%q(:ncol,:,m)*state%pdel(:ncol,:)/state%pdeldry(:ncol,:)
     endif
  end do
```

Hence the operation in `vertical_diffusion_tend` is correct as it converts dry tracers to wet and reverts the operation at the end.

Converting all of CAM physics to a dry basis would highly likely make sure these kinds of bugs are avoided ...

2024-06-07 07:07 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
Ah, thanks. I keep forgetting about that subtlety (probably because of the broken name and also getting rusty in that part of the code). Also, there is no tag on a constituent's current state which has caused plenty of other problems in the past. I'm still hoping this can get fixed in CAM-SIMA but I don't know if that has been fully fleshed out yet.

2024-06-07 13:38 UTC, sjsprecious commented on src/physics/cam/clubb_intr.F90
@PeterHjortLauritzen @gold2718 I have wondered this question for a while: why do we need to use dry basis and wet basis in different CAM parts?

2024-06-07 13:50 UTC, PeterHjortLauritzen commented on src/physics/cam/clubb_intr.F90
Traditionally, moist physics developers have always used moist mixing ratios for water species. For example, specific humidity (which equals the moist mixing ratio of water vapor) is a directly measurable and observable quantity, making it a logical choice for moist physics. However, chemists usually use dry mixing ratios; for them, a moist basis is problematic because it includes a water vapor signal embedded in the mixing ratio. Numerical schemes are generally designed to conserve a constant mixing ratio. Specifically, some chemical species remain constant (on a dry basis) in most of the atmosphere. If one uses a moist basis, the numerical schemes will likely introduce a water vapor signal into the mixing ratio that was supposed to remain constant.

We wrote a detailed argument for using a dry basis, which you can find here:

https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2017MS001257

(see Introduction)

2024-06-07 17:12 UTC, sjsprecious commented on src/physics/cam/clubb_intr.F90
Thanks @PeterHjortLauritzen so much for your detailed explanation and sharing of your paper. That is very helpful.

2024-06-10 16:06 UTC, brian-eaton requested changes
I agree with Steve's initial reaction: why don't we fix the utility code in physics_types.F90?  By doing so we have the opportunity to add some clarity the complexity of having different types of constituents and different parameterizations that expect wet or dry mixing ratios based on the type of the constituent (water specie or not).  I have made an attempt at this below and invite comments for further clarification.  I left the subroutine names the same since the functionality of converting between wet and dry mixing ratios is fairly clear in those names.  What's not clear is what constituent types the conversion is applied to.  Adding an argument will make that clearer.  I considered making the argument optional with the default to convert the dry species as it currently does.  But there aren't many calls to these subroutines so updating them all is easy, and will make existing code more clear.
```
subroutine set_wet_to_dry(state, convert_cnst_type)

  ! Convert mixing ratios from a wet to dry basis for constituents of type
  ! convert_cnst_type.  Constituents are given a type when they are added
  ! to the constituent array by a call to cnst_add during the register
  ! phase of initialization.  There are two constituent types: 'wet' for
  ! water species and 'dry' for non-water species.

  use constituents,  only: pcnst, cnst_type

  type(physics_state),  intent(inout) :: state
  character(len=*),     intent(in)    :: convert_cnst_type
  
  ! local variables
  integer :: m, ncol
  character(len=*), parameter :: sub = 'set_wet_to_dry'
  !-----------------------------------------------------------------------------

  ! check input
  if (.not.(convert_cnst_type == 'wet' .or. convert_cnst_type == 'dry')) then
    write(iulog,*) sub//': FATAL: convert_cnst_type not recognozed: '//convert_cnst_type
    call endrun(sub//': FATAL: convert_cnst_type not recognozed: '//convert_cnst_type)
  end if

  ncol = state%ncol

  do m = 1,pcnst
     if (cnst_type(m) .eq. convert_cnst_type) then
        state%q(:ncol,:,m) = state%q(:ncol,:,m)*state%pdel(:ncol,:)/state%pdeldry(:ncol,:)
     endif
  end do

end subroutine set_wet_to_dry
```
Similar changes can be made to `set_dry_to_wet`

2024-06-10 17:09 UTC, PeterHjortLauritzen commented
Thanks for looking into this. I am fine with the proposed change.

2024-06-24 18:32 UTC, brian-eaton approved these changes
I have implemented the suggested changes.

2024-06-26 14:59 UTC, nusbaume approved these changes
Looks good to me!  Only issue I found was few minor typos (so I don't feel the need to re-review).  Thanks!

2024-06-26 14:59 UTC, nusbaume commented on src/physics/cam/physics_types.F90
> +    call endrun(sub//': FATAL: convert_cnst_type not recognozed: '//convert_cnst_type)
Couple minor typos:

```suggestion
    write(iulog,*) sub//': FATAL: convert_cnst_type not recognized: '//convert_cnst_type
    call endrun(sub//': FATAL: convert_cnst_type not recognized: '//convert_cnst_type)
```

2024-06-26 14:59 UTC, nusbaume commented on src/physics/cam/physics_types.F90
> +  end if
Typos:

```suggestion
  if (.not.(convert_cnst_type == 'wet' .or. convert_cnst_type == 'dry')) then
    write(iulog,*) sub//': FATAL: convert_cnst_type not recognized: '//convert_cnst_type
    call endrun(sub//': FATAL: convert_cnst_type not recognized: '//convert_cnst_type)
  end if
```

2024-06-26 19:37 UTC, brian-eaton commented on src/physics/cam/physics_types.F90
> +  end if
Thanks for catching that.  Fixed.

2024-07-03 19:56 UTC, merged