Remove WACCMX gridded component layer
ESCOMP/CAM pull request #1069
Opened 2024-06-27 19:28 UTC by fvitt

This removes the ESMF gridded component layer in waccmx coupling.

Closes #1055

2024-07-10 10:42 UTC, gold2718 approved these changes
Nice cleanup!

2024-07-12 15:30 UTC, cacraigucar requested changes

2024-07-12 15:30 UTC, cacraigucar commented on src/ionosphere/waccmx/edyn_phys_grid.F90
> +    allocate(lonMesh(total_cols), latMesh(total_cols))
Need to put checks on all the allocations in this subroutine

2024-07-12 18:25 UTC, fvitt commented on src/ionosphere/waccmx/edyn_phys_grid.F90
> +    allocate(lonMesh(total_cols), latMesh(total_cols))
done

2024-07-19 15:59 UTC, cacraigucar requested changes

2024-07-19 15:59 UTC, cacraigucar commented on src/ionosphere/waccmx/edyn_phys_grid.F90
> +    call edyn_esmf_chkerr(subname, 'ESMF_DistGridCreate phys decomp', rc)
I realize that this code is most likely a rename of previous code, but I'm seeing a number of return codes which are not being checked here, and below.  Should they be?

2024-07-19 18:00 UTC, fvitt commented on src/ionosphere/waccmx/edyn_phys_grid.F90
> +    call edyn_esmf_chkerr(subname, 'ESMF_DistGridCreate phys decomp', rc)
The return codes from the ESMF routines are checked by `edyn_esmf_chkerr`.  I believe they are all checked.  Am I missing something?

2024-07-19 18:24 UTC, cacraigucar commented on src/ionosphere/waccmx/edyn_phys_grid.F90
> +    call edyn_esmf_chkerr(subname, 'ESMF_DistGridCreate phys decomp', rc)
No - I'm the one missing things (i.e. that edyn_esmf_checkerr is actually doing the checking!)  Sorry about that!

2024-07-19 18:24 UTC, cacraigucar approved these changes

2024-07-22 23:29 UTC, merged