New CLUBB External to fix GPU problem
ESCOMP/CAM pull request #1086
Opened 2024-07-09 23:17 UTC by Katetc

Small answer changes, but no new CLUBB science. Diagnostics can be found here:
https://webext.cgd.ucar.edu/F2000climo/newCLUBBtesting/larson_tag_20240605.katemerge.062724-0201.F2000dev.f09_f09_mg17_1_2_vs_larson_tag_control.cam6_3_162.062724-1359.F2000dev.f09_f09_mg17_1_2/website/index.html

Fixes #1036

2024-07-19 15:54 UTC, cacraigucar requested changes

2024-07-23 15:27 UTC, sjsprecious approved these changes
The current CLUBB GPU tag runs successfully on Derecho's GPU but fails the ensemble consistency test. The UWM group is debugging the GPU code now but we (CISL group) are fine with moving on with this PR and including the new CLUBB GPU tag in the CAM regression test.

2024-07-23 16:56 UTC, adamrher commented
@Katetc I'm under the impression that these new clubb externals remove the ghost point from the thermodynamic 'zt' grid. But I'm not seeing a reduction in the size of the zt arrays in clubb_intr in this PR. What am I missing?

2024-07-24 06:20 UTC, sjsprecious requested changes

2024-07-24 06:20 UTC, sjsprecious commented on .gitmodules
The `ccs_config` tag needs to be updated to `ccs_config_cesm1.0.0` so that the CLUBB GPU code can be compiled correctly on the GPU.

2024-07-26 15:33 UTC, cacraigucar requested changes

2024-07-26 15:33 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +#ifndef SILHS
Couldn't this be wrapped in a `    if ( trim(subcol_scheme) == 'SILHS' ) then`?  The only reason to put code like this inside a #ifndef directive is to hide it completely from the compiler.  I believe that hm_metadata and the two fields always are declared.

2024-07-26 15:33 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +    allocate( hm_metadata%l_mix_rat_hm(1) )
Need to return and check an error code for the allocations.

2024-07-26 15:35 UTC, cacraigucar commented
@adamrher and @bstephens82 - @Katetc requested reviews from both of you.  Please either remove yourself as a reviewer or do a review when you can.

2024-07-26 15:44 UTC, adamrher approved these changes
I'm approving this PR, but would like to understand why all the arrays on the thermodynamic grid in clubb_intr.F90 are still retaining their ghost points. It was my understanding that this PR is removing the ghost point? Is the plan to just do that in the clubb externals, not the CAM interface?

For example, ```rho_zt``` is still of size ```dimension(state%ncol,pverp+1-top_lev)``` in clubb_intr.F90; it has the ghost point.

2024-07-26 16:57 UTC, vlarson commented
> I'm approving this PR, but would like to understand why all the arrays on the thermodynamic grid in clubb_intr.F90 are still retaining their ghost points. It was my understanding that this PR is removing the ghost point? Is the plan to just do that in the clubb externals, not the CAM interface?
> 
> For example, `rho_zt` is still of size `dimension(state%ncol,pverp+1-top_lev)` in clubb_intr.F90; it has the ghost point.

This code merely changes some lower BCs to one-sided derivatives within CLUBB core (and fixes some minor bugs involving full-level variables being placed on the wrong (half-level) grid levels).  This PR doesn't change the clubb_intr, but UWM hopes to do that at some point.

2024-07-26 16:59 UTC, vlarson commented
@adamrher, do you think that the changes in the solution look "large", or do they look like what you'd expect from truncation error (numerics)?

2024-07-26 17:05 UTC, adamrher commented
Thanks for getting back to me on the ghost point. All is good then.

> @adamrher, do you think that the changes in the solution look "large", or do they look like what you'd expect from truncation error (numerics)?

The global mean turbulent fluxes and radiative fluxes look ~identical, so that suggests round-off level changes. There's some differences in the lat-lon map plots but those are what you would expect from comparing to two, 2 year long runs.

2024-07-26 19:55 UTC, bstephens82 approved these changes

2024-07-29 18:38 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(sclr_idx)
Removed all three

2024-07-29 18:39 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +      allocate(corr_array_n_below(pdf_dim,pdf_dim))
Fixed

2024-07-29 18:53 UTC, Katetc commented on .gitmodules
The current head of cam_development points to ccs_config_cesm1.0.0 so when this branch is merged up, the external will be correctly versioned.

2024-07-29 19:49 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +#ifndef SILHS
Seems like it should be fine. I'm updating to just a straight "if" here.

2024-07-29 19:49 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    allocate( hm_metadata%l_mix_rat_hm(1) )
Fixed.

2024-07-29 20:31 UTC, sjsprecious commented on .gitmodules
Thanks Kate. That is great!

2024-07-29 20:31 UTC, sjsprecious approved these changes

2024-07-29 20:44 UTC, cacraigucar approved these changes
One minor tweak requested, but I am approving

2024-07-29 20:44 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +#ifndef SILHS
Should probably use `/=` instead of `.ne.` to adhere to the CAM coding standards (it is a should and not a must)

2024-07-29 22:16 UTC, Katetc commented
> One minor tweak requested, but I am approving

I had a minor bug fix too, so I fixed this "if" statement as well.

2024-08-12 23:37 UTC, merged