Wrap MPAS longitude values to [0,2pi) range
ESCOMP/CAM pull request #1095
Opened 2024-07-18 18:10 UTC by gdicker1

This PR addresses issues that were seen when using ncdata with longitudes in the $[-pi, pi]$ range in cases with full physics.  This would cause the atmosphere to become unphysical and runs to fail. This change is made just after the longitude values are read to ensure they are correct for the remainder of execution.

Fixes #1094

2024-07-18 18:16 UTC, gdicker1 commented
NOTE: This PR branch is based on cam6_3_148 for compatibility with EarthWorks. This can be updated at any time, in whatever way reviewers would prefer.

Changes in this PR should also allow #1029 to proceed.

2024-07-19 21:57 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       call mpas_pool_get_dimension(meshPool, 'nCells', nCells)
Is `nCells` actually needed?

2024-07-19 22:30 UTC, gdicker1 commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       call mpas_pool_get_dimension(meshPool, 'nCells', nCells)
Thanks for the catch, it's not needed now. It was a leftover from when I was iterating on this. Addressed by https://github.com/ESCOMP/CAM/pull/1095/commits/f3dfa5173aea7d1c4a90dafd53f3e3fe2e0660a9

2024-07-23 23:14 UTC, jtruesdal approved these changes
Looks Good!  I have one small request.  Append the kind to the number literal.  After that it should be good to go.

2024-07-23 23:14 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       lonCell_arr(:) = lonCell_arr(:) - (2.*pii) * floor(lonCell_arr(:) / (2.*pii))
```suggestion
       lonCell_arr(:) = lonCell_arr(:) - (2._RKIND*pii) * floor(lonCell_arr(:) / (2._RKIND*pii))
```

2024-07-24 00:16 UTC, gdicker1 commented
@jtruesdal before I push to address your comment, I just noticed that I didn't wrap the commit message for f3dfa5173aea7d1c4a90dafd53f3e3fe2e0660a9 appropriately. In other repos, I would fix the message and force-push the branch.

How should I proceed here? Just ignore it?

2024-07-24 20:34 UTC, jtruesdal commented
I'm not sure what you mean by "wrap the commit message".  Everything looks Ok to me when I look at the 3 commits and their associated messages.  We mostly go by the Changelog and the commit messages are useful but not critical.

2024-07-24 20:47 UTC, gdicker1 commented
Fair enough, I won't worry about it.

> I'm not sure what you mean by "wrap the commit message".
Most resources on git commit messages suggest to break body text at 72 characters and continue on the next line.

2024-07-24 20:48 UTC, gdicker1 commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       lonCell_arr(:) = lonCell_arr(:) - (2.*pii) * floor(lonCell_arr(:) / (2.*pii))
Thanks for the reminder! Addressed by [288f3ed](https://github.com/ESCOMP/CAM/pull/1095/commits/288f3ed05d3e3e8d475bc39f967ab420f87bb937)

2024-07-25 22:31 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       lonCell_arr(:) = lonCell_arr(:) - (2._RKIND*pii) * floor(lonCell_arr(:) / (2._RKIND*pii))
It might have been me who initially suggested adding this code in `cam_mpas_read_static`, but after a second look, I'm wondering whether this code would better belong in the `setup_time_invariant` routine? We do other checks and processing of fields there after the call to `cam_mpas_read_static`, and moving the modification of the longitude range there would let the focus of `cam_mpas_read_static` be purely on reading fields.

2024-07-25 22:33 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       ! Ensure longitudes w/i [0, 2*pi) range
It took me a second to realize that `w/i` probably means "within". It probably wouldn't hurt readability to just write this all out, and to also note that this doesn't really matter for the MPAS-A dycore, but it does matter for other parts of CAM that inherit the longitude field from the dycore.

2024-07-25 22:36 UTC, mgduda requested changes
Besides giving some consideration to the two comments I've left, I think it would be worth using a loop with a conditional to only modify longitudes that aren't already in the interval [0, 2*Pi). It's ultimately likely to be slower, but this only happens once when the model starts up, and the cost is almost certainly negligible when compared with the cost of filesystem accesses. The benefit would be that, for meshes that provide longitudes in CAM's required range, those values would remain bitwise identical to their values in the input file.

2024-07-26 17:32 UTC, gdicker1 commented
@mgduda I implemented your suggestions in [fabe37a](https://github.com/ESCOMP/CAM/pull/1095/commits/fabe37a9910838690e43b4a6695079971156e5aa). Thanks for the explanation you gave on the "loop with a conditional".

2024-07-26 21:45 UTC, mgduda requested changes

2024-07-26 21:45 UTC, mgduda commented on src/dynamics/mpas/dyn_grid.F90
> +      if (lonCell(k) < 0._r8 .or. lonCell(k) .ge. (2._r8 * pi)) then
For consistency (and perhaps even CAM coding standards), I think `.ge.` should be changed to `>=`.

2024-07-26 21:45 UTC, mgduda commented on src/dynamics/mpas/dyn_grid.F90
> +   ! longitude range, MPAS may have any (radian) value in lonCell
The phrasing of this last part doesn't quite give the right sense to me. Perhaps rather than saying "MPAS may have any (radian) value in lonCell" we could say something like "the MPAS-A dycore does not require any specific range for lonCell".

2024-07-26 22:15 UTC, gdicker1 commented on src/dynamics/mpas/dyn_grid.F90
> +      if (lonCell(k) < 0._r8 .or. lonCell(k) .ge. (2._r8 * pi)) then
Thank you this does correspond to one of the [SHOULD](https://github.com/ESCOMP/CAM/wiki/CAM-Coding-Standards#should-1) standards. Addressed in [005e7f4](https://github.com/ESCOMP/CAM/pull/1095/commits/005e7f45cdb8ec604dd707fc2af56f9351f7d25f)

2024-07-26 22:15 UTC, gdicker1 commented on src/dynamics/mpas/dyn_grid.F90
> +   ! longitude range, MPAS may have any (radian) value in lonCell
Addressed in [1325911](https://github.com/ESCOMP/CAM/pull/1095/commits/13259119275a64900e771931df912c5a4ea01982)

2024-07-26 22:26 UTC, mgduda approved these changes
Approved by inspection.

2024-08-05 16:48 UTC, jtruesdal approved these changes

2024-09-13 19:33 UTC, merged