Aerosol deposition fluxes
ESCOMP/CAM pull request #1096
Opened 2024-07-19 14:08 UTC by fvitt

This repartitions the modal dust deposition fluxes into 4 bulk bins for passing to the surface models.  The aerosol fluxes code was refactored in a generalized way which can easily be expanded for other aerosol representations, such as CARMA.

Closes #1060

2024-07-19 14:09 UTC, fvitt commented
This has yet to be tested and evaluated.

2024-08-27 21:22 UTC, cacraigucar requested changes

2024-08-27 21:22 UTC, cacraigucar commented on src/chemistry/aerosol/aero_deposition_cam.F90
> +      if (cam_out%dstdry4(i)  .lt. 0._r8) cam_out%dstdry4(i)  = 0._r8
CAM guidelines say "should" use `<` instead of `.lt.` .  This is at your discretion since it is a "should" and not a "must"

2024-08-27 21:22 UTC, cacraigucar commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +          if (spectype==bulk_type) then
I'm not sure if it is doable (an error or not) to capture if no matches occur with `spectype==bulk_type`.  I'm thinking of whether it is worth trying to capture a typo or completely incorrect name for `bulk_type`

2024-08-28 14:48 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +          if (spectype==bulk_type) then
I could probably implement an error code and error string that get returned by the subroutine if you think it is worth while.  As it is now, if the specified `bulk_type` is not valid then the fluxes returned are zeros.

2024-08-28 14:52 UTC, cacraigucar commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +          if (spectype==bulk_type) then
I agree that the fluxes will be zero, but I'm not sure if it would be readily apparent to a user that they had a typo or invalid name as zero fluxes might be pretty subtle in a run.  It really is your call - I am just pointing this out for your consideration.

2024-08-28 14:54 UTC, cacraigucar approved these changes

2024-08-28 15:20 UTC, fvitt commented on src/chemistry/aerosol/aero_deposition_cam.F90
> +      enddo
Added comments

2024-08-28 15:20 UTC, fvitt commented on src/chemistry/aerosol/aero_deposition_cam.F90
> +      if (cam_out%dstdry4(i)  .lt. 0._r8) cam_out%dstdry4(i)  = 0._r8
Done

2024-08-28 15:21 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +          if (spectype==bulk_type) then
Added error checking

2024-08-28 22:41 UTC, merged