Dust emissions
ESCOMP/CAM pull request #1104
Opened 2024-07-24 22:43 UTC by fvitt

Mods needed for the new dust scheme 

closes https://github.com/ESCOMP/CAM/issues/651
closes https://github.com/ESCOMP/CAM/issues/141

2024-07-24 22:47 UTC, fvitt commented
@ekluzek This is the new CAM PR for the new dust emission scheme coming into CTSM.  

We need to think about how to coordinate namelist settings when the new scheme is turned on...

2024-07-25 07:08 UTC, ekluzek requested changes
@fvitt thanks for working on this. I suppose this was just back porting the previous PR that was done before the dust emission namelist was worked out in CMEPS.

The namelist read needs to be redone so that it uses the dust emission settings in the drv_flds_in namelist file and uses the components/cmeps/cesm/nuopc_cap_share/shr_dust_emis_mod.F90 module to determine if CAM needs to modify dust emissions from CLM with the soil erodibility file.

What needs to happen in CAM will be similar to what happens in the CTSM branch being pointed to.

2024-07-25 18:05 UTC, ekluzek requested changes
@fvitt thanks for the updates. I ask for a couple changes.

I think you also need to add the new fields to the namelist_defintion file for drv_flds, unless I'm missing something. And you need to add a call for the shr_dust_emis_readnl() (CTSM has this in lnd_import_export.F90).

2024-07-30 14:55 UTC, ekluzek commented
@fvitt note, the CTSM tag that allows CAM and CTSM to work together on dust emission settings is complete and it's ctsm5.2.017. 

It doesn't yet allow turning on Leung_2023, but it uses the new XML variable LND_SETS_DUST_EMIS_DRV_FLDS to determine if CTSM or CAM are doing the dust settings and uses the dust_emis_inparm namelist in drv_flds_in to determine the dust settings and when Zender_2003 is on, to determine if CAM or CTSM will be setting the Zender soil erodibility file.

2024-08-06 16:52 UTC, fvitt commented
@ekluzek Is there a CTSM tag for the Leung_2023 scheme, or is this still in progress?

2024-08-09 21:03 UTC, ekluzek commented
@fvitt the CTSM tag with Leung is still in process, but it's

https://github.com/ESCOMP/CTSM/pull/1897

and will be ctsm5.2.019. It is almost completed. I plan to have it completed over the weekend before Derecho goes down on Monday.

2024-08-11 20:35 UTC, ekluzek commented
Ok the needed CTSM tag is done ctsm5.2.019

2024-08-12 16:44 UTC, ekluzek commented
@fvitt the thing that is missing here is that when you are running CAM you need CAM to specify the namelist settings and NOT have CLM modify any of them. The problem seems to be having them both trying to mess with them at the same time.

So you need to set the XML variable LND_SETS_DUST_EMIS_DRV_FLDS to false

```
./xmlchange LND_SETS_DUST_EMIS_DRV_FLDS=FALSE
```

I'm not sure where that should go in CAM, but for now it should always be done for CAM compsets that use CLM.

2024-08-12 16:46 UTC, fvitt commented
@ekluzek 
These problems occur with `LND_SETS_DUST_EMIS_DRV_FLDS=FALSE`.

2024-08-12 20:53 UTC, ekluzek commented
@fvitt thanks for pointing that out. I'll try checking out this branch and reproduce it to figure out what's wrong.

2024-08-12 21:17 UTC, fvitt commented
@ekluzek I just pushed up my latest changes.  Try to build namelists for FHIST and FLTHIST compsets.  Thanks.

2024-08-13 19:28 UTC, ekluzek commented
@fvitt thanks for pointing this out. I've replicated the problem with your branch. 

I also see what's going on, and why I didn't think of this issue before. I'll have to think about how to fix it though. I'll add an issue on the CTSM side regarding this. We'll include it in an upcoming CTSM tag and I'll update this when we have that.

A workaround that I verified is you can add this to your user_nl_clm for CAM:

``` fortran
use_prigent_roughness = .false.
```

You could add that temporarily while we get a CTSM tag with a fix and then remove it when we get the CTSM in place for CAM to use.

2024-08-13 22:20 UTC, fvitt commented
> @fvitt thanks for pointing this out. I've replicated the problem with your branch.
> 
> I also see what's going on, and why I didn't think of this issue before. I'll have to think about how to fix it though. I'll add an issue on the CTSM side regarding this. We'll include it in an upcoming CTSM tag and I'll update this when we have that.
> 
> A workaround that I verified is you can add this to your user_nl_clm for CAM:
> 
> ```fortran
> use_prigent_roughness = .false.
> ```
> 
> You could add that temporarily while we get a CTSM tag with a fix and then remove it when we get the CTSM in place for CAM to use.

The problem with this is I don't see a way to set this namelist in `user_nl_clm` out-of-the-box for all the CAM compsets, which what is needed for the regression tests.

2024-08-13 23:21 UTC, ekluzek commented
@fvitt yes it looks like CAM is using test mod directories as completely independent of each other and NOT using the include_user_mods feature to pull in something from a parent test-mod. Maybe that's done on purpose? Or CAM just wasn't aware of this ability?

Using the include ability you could add for example a 

cime_config/testdefs/testmods_dirs/cam/default

directory with the user_nl_clm file with the one modification needed. And then add
include_user_mods
file to each test mod directory that has...

../default

as it's contents. Which is relatively contained and doable, and it would allow you to test before a tag is in place.

That might be more than you want to do here, and you'd definitely want to check in with CAM folks to see if it's even desired to do this. But, it's an option...

2024-08-14 17:55 UTC, ekluzek commented
@fvitt I thought of one other workaround that might be easier to try. You could add

"-ignore_warnings"

to the XML variable CLM_BLDNML_OPTS (you'd probably want to do it using the --append option). That should work, but I haven't tried it.

2024-08-15 21:54 UTC, ekluzek commented
@fvitt try hash 3f3541b37b7ff9abe37050c98575b61b3702e688 in the CTSM PR https://github.com/ESCOMP/CTSM/pull/2699

on a few of your cases and make sure it's working for you. I successfully ran:

SMS_Ln9.f19_f19_mg17.FHIST.derecho_intel.cam-outfrq9s_nochem.

and think that means it should work for everything. But, of course in practice there might be a compset with unexpected problems.

2024-08-15 23:13 UTC, fvitt commented
@ekluzek 
With that hash, I am getting this error:
```
 err=ERROR : CLM build-namelist::CLMBuildNamelist::setup_logic_megan() : megan_specifier or megan_factors_file defined, but megan option NOT set
```

The `outfrq9s_nochem` user_mod is not a good choice for testing.  
Try these tests
```
 SMS_Ln9.f19_f19_mg17.FHIST.derecho_intel.cam-outfrq9s
 SMS_Ln9.ne30pg3_ne30pg3_mg17.FLTHIST.derecho_intel.cam-outfrq9s
```

2024-08-15 23:24 UTC, ekluzek commented
@fvitt thanks for trying that out and giving me some new tests to try. I see the next thing that needs to be done now.

This also shows that the current path here is fragile, but I think it's necessary for now. I think right now it means that we'll have this  LND_SETS_DUST_EMIS_DRV_FLDS  variable and logic around for a while, but we'll want to get it to always FALSE as quickly as we can. And then we'll be able to remove it. The fragility goes away once we can get it to FALSE for coupled to CAM.

2024-08-19 20:45 UTC, ekluzek commented on bld/build-namelist
> +if ($nl->get_value('dust_emis_method') eq 'atm') {$soil_erod_atm = $TRUE;}
This should check zender_soil_erod_source rather than dust_emis_method. And since it's not always set should likely be restructured so that it's set appropriately even if zender_soil_erod_source wasn't being set (because it's Leung_2024 and not Zender_2003).

I'll suggest a potential restructuring...

2024-08-19 20:49 UTC, ekluzek commented on bld/build-namelist
> +if ($nl->get_value('dust_emis_method') eq 'atm') {$soil_erod_atm = $TRUE;}
```suggestion
add_default($nl, 'dust_emis_method');
my $soil_erod_atm = $FALSE;
if ( $nl->get_value('dust_emis_method') =~ /Zender/ ) {
    add_default($nl, 'zender_soil_erod_source');
    if ($nl->get_value('zender_soil_erod_source') eq 'atm') {$soil_erod_atm = $TRUE;}
}
```

2024-08-22 17:30 UTC, ekluzek commented
@fvitt I have another updated CTSM version for you to try out:

786252bb012172e53ced93b40b9730d11f8d6efe

I ran

SMS_Ln9.f19_f19_mg17.FHIST.derecho_intel.cam-outfrq9s_nochem

with it and it passed. Note that Danny noticed a problem with your sandbox that gave problems for him that you likely need to handle before this works here (it's all given in comments above).

2024-08-23 14:13 UTC, fvitt commented
> @fvitt I have another updated CTSM version for you to try out:
> 
> 786252bb012172e53ced93b40b9730d11f8d6efe
> 
> I ran
> 
> SMS_Ln9.f19_f19_mg17.FHIST.derecho_intel.cam-outfrq9s_nochem
> 
> with it and it passed. Note that Danny noticed a problem with your sandbox that gave problems for him that you likely need to handle before this works here (it's all given in comments above).

I tried this version of CTSM.  This allows CAM to set the namelist settings.  However, with `dust_emis_method = 'Leung_2023'`, the dust emission fluxes seem to be all zeros.

2024-08-23 16:49 UTC, ekluzek commented
> > @fvitt I have another updated CTSM version for you to try out:
> > 786252bb012172e53ced93b40b9730d11f8d6efe
> > I ran
> > SMS_Ln9.f19_f19_mg17.FHIST.derecho_intel.cam-outfrq9s_nochem
> > with it and it passed. Note that Danny noticed a problem with your sandbox that gave problems for him that you likely need to handle before this works here (it's all given in comments above).
> 
> I tried this version of CTSM. This allows CAM to set the namelist settings. However, with `dust_emis_method = 'Leung_2023'`, the dust emission fluxes seem to be all zeros.

Hmmm. That's not something I can explain by any of the code changes that have happened. Danny has also been doing his own F cases while we've gone along.

Before diving into this -- can you let me know about what period it's all zeros? Is that the first time-step for example? If you run longer does it become non-zero after awhile? Zero is valid, it would just be unusual over the entire globe, but maybe possible, but over time it obviously needs to be non-zero.

2024-08-23 17:02 UTC, fvitt commented
> > > @fvitt I have another updated CTSM version for you to try out:
> > > 786252bb012172e53ced93b40b9730d11f8d6efe
> > > I ran
> > > SMS_Ln9.f19_f19_mg17.FHIST.derecho_intel.cam-outfrq9s_nochem
> > > with it and it passed. Note that Danny noticed a problem with your sandbox that gave problems for him that you likely need to handle before this works here (it's all given in comments above).
> > 
> > 
> > I tried this version of CTSM. This allows CAM to set the namelist settings. However, with `dust_emis_method = 'Leung_2023'`, the dust emission fluxes seem to be all zeros.
> 
> Hmmm. That's not something I can explain by any of the code changes that have happened. Danny has also been doing his own F cases while we've gone along.
> 
> Before diving into this -- can you let me know about what period it's all zeros? Is that the first time-step for example? If you run longer does it become non-zero after awhile? Zero is valid, it would just be unusual over the entire globe, but maybe possible, but over time it obviously needs to be non-zero.

I ran for a day and output fluxes each time step.  Fluxes seem to zeros all time steps everywhere.

2024-08-23 20:03 UTC, fvitt commented
@ekluzek I fixed a bug on the CAM side.  The Leung dust emissions schemes seems to be working now.

2024-08-27 22:02 UTC, cacraigucar requested changes

2024-08-27 22:02 UTC, cacraigucar commented on .gitmodules
> +fxtag = 786252bb0
Just a reminder (more for me than you) to update this to the official CTSM tag when it is ready

2024-08-29 03:29 UTC, ekluzek commented on .gitmodules
> +fxtag = 786252bb0
This can now be replaced with ctsm5.2.027

2024-08-29 03:31 UTC, ekluzek commented on bld/namelist_files/namelist_definition.xml
> +Default: set by build-namelist.
@cacraigucar this will be a transition thing that we need to do. Once, the older CAM physics versions that use Zender are vetted for lnd to work correctly for them -- we can change it to lnd. We need to make sure that the difference between lnd and atm is small. It's likely greater than roundoff, but shouldn't be much, unless there's a bug in CTSM.

2024-08-29 16:34 UTC, fvitt commented on .gitmodules
> +fxtag = 786252bb0
Thanks @ekluzek 
Updating to from ctsm5.2.009 to ctsm5.2.027 changes answers for the F compsets, even when Zender scheme is used.  Is this expected?  I see several namelist changes in lnd_in.

2024-08-29 16:55 UTC, ekluzek commented on .gitmodules
> +fxtag = 786252bb0
Yes, this is expected. There's several rounds of answer changes between 009 and 027. I can map out what they are if you like and that would help.

Is it OK for your CAM tag to have CLM answer changes in it?

2024-08-29 22:15 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<zender_soil_erod_source>atm</zender_soil_erod_source>
Default is now `Zender_2003` for all configurations.

2024-08-29 22:29 UTC, ekluzek commented on bld/namelist_files/namelist_defaults_cam.xml
> +<zender_soil_erod_source>atm</zender_soil_erod_source>
@cacraigucar I assume that means there will be a follow on CAM tag where Leung is turned on for CAM7? Or will we just be in experimental mode for awhile and then change the default much later? Just curious how this is going to go...

2024-08-30 15:05 UTC, cacraigucar commented on .gitmodules
> +fxtag = 786252bb0
We typically update answer changing externals for CAM runs in their own tag, so I'd like to pull it in separate.  @fvitt - would you be willing to do this, or do we need to do this on the AMP side?

2024-08-30 15:17 UTC, cacraigucar commented on .gitmodules
> +fxtag = 786252bb0
The exception to this is if @fvitt has independently already run the regression tests with his changes and they are BFB except for the test(s) which use the dust.  If this has been done, he can document in the ChangeLog that he has independently tested that "the code changes were independently tested and were non-answer changing for all but the dust configurations.  All answer changes to non-dust runs are due to updating CLM".  If these tests haven't been run, then it probably makes sense to just split it into two CAM tags.

2024-08-30 15:51 UTC, cacraigucar approved these changes

2024-08-30 15:51 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<zender_soil_erod_source>atm</zender_soil_erod_source>
@ekluzek - When(if) the scientists tell us that they want to change the default setting, we will do so.  This will be part of the tunings that will be happening and I suspect that we'll be adjusting quite a few settings/defaults, not just this one.

2024-08-30 16:39 UTC, ekluzek commented on .gitmodules
> +fxtag = 786252bb0
Here's the list of things I expected to affect CAM F compsets in a substantial way:

- ctsm5.2.016 -- changes answers for clm6_0 for crop grid cells
- ctsm5.2.020 -- changes answers for all physics options for MEGAN BGVOC's which will affect CAM-Chem simulations
- ctsm5.2.026 -- change answers for clm6_0 over urban grid cells

There's a few others that still might affect CAM F compsets, but I expect them to be much smaller. Go to the bottom of this wiki page to see a full description of CTSM answer changing tags:

https://github.com/ESCOMP/CTSM/wiki/Answer-changing-tags

2024-08-30 16:42 UTC, ekluzek commented on bld/build-namelist
> +if ($nl->get_value('dust_emis_method') eq 'atm') {$soil_erod_atm = $TRUE;}
This was done.

2024-08-30 16:44 UTC, ekluzek commented on bld/build-namelist
> +if ($nl->get_value('dust_emis_method') eq 'atm') {$soil_erod_atm = $TRUE;}
Handled.

2024-08-30 16:47 UTC, ekluzek commented on src/chemistry/bulk_aero/dust_model.F90
> +       write(iulog,*) subname,': soil_erod_file = ',trim(soil_erod_file)
Handled.

2024-08-30 16:48 UTC, ekluzek commented on src/chemistry/bulk_aero/dust_model.F90
> +       write(iulog,*) subname,': is_dust_emis_zender : ',is_dust_emis_zender()
Nicely handled.

2024-08-30 16:50 UTC, ekluzek commented on src/chemistry/bulk_aero/dust_model.F90
> +    call mpi_bcast(soil_erod_file, len(soil_erod_file), mpi_character, masterprocid, mpicom, ierr)
Handled.

2024-08-30 16:51 UTC, ekluzek commented on src/chemistry/modal_aero/dust_model.F90
> +    call mpi_bcast(soil_erod_file, len(soil_erod_file), mpi_character, masterprocid, mpicom, ierr)
Handled.

2024-08-30 16:53 UTC, ekluzek approved these changes
All of my suggestions were appropriately handled. So this is good to go from my perspective. Thanks for working on this and getting it done @fvitt!

2024-09-04 19:01 UTC, ekluzek commented on cime_config/config_compsets.xml
> +	<value compset="_CAM7.*_CLM6">FALSE</value>
@fvitt I was concerned about this at first in case it meant that the CAM Zender soil erodibility files were NOT being used. But, it looks like that is NOT the case. So this should be fine. I'm looking at it more closely. I'm glad you figured this workaround out.

2024-09-04 19:03 UTC, ekluzek commented on cime_config/config_compsets.xml
> +	<value compset="_CAM7.*_CLM6">FALSE</value>
This is also probably fine since longer term we want to always make this TRUE and even remove it entirely. So that just brings us closer to the long term solution.

2024-09-04 19:10 UTC, ekluzek commented on cime_config/config_compsets.xml
> +	<value compset="_CAM7.*_CLM6">FALSE</value>
The only bad thing here is that it means that the way you change dust emission settings will be different for the CAM7 with CAM6 than for anything else. But, it's unlikely that people will be messing with the dust settings for previous CAM physics.

2024-09-04 19:11 UTC, ekluzek commented on bld/namelist_files/use_cases/sd_waccm_ma_cam4.xml
> +<megan_specifier>
I'm surprised you had to do this. But, of course it's a change that's perfectly fine to do. I'll see if I can look into why you had to change it...

2024-09-04 22:47 UTC, merged