Implementation of CCPP-ized tropopause_find with compatibility with current CAM
ESCOMP/CAM pull request #1135
Opened 2024-08-26 04:20 UTC by jimmielin

**Please place on hold until bit-for-bit issues in CAM-SIMA are confirmed so a final `atmospheric_physics` tag can be made first**

Closes #1121.

Companion PRs:
* https://github.com/ESCOMP/atmospheric_physics/pull/112
* https://github.com/ESCOMP/CAM-SIMA/pull/293

This brings in `atmospheric_physics` with CCPP-ized `tropopause_find` and a compatibility wrapper in the place of old `tropopause.F90` preserving old behavior and bit-for-bit reproducibility.

Minor edits to certain subroutine calls to remove redundant specification of `primary=TROP_ALG_TWMO, backup=TROP_ALG_CLIMATE`, as that is the default configuration and such specification is unnecessary.

2024-09-12 21:35 UTC, nusbaume requested changes
Great work @jimmielin!  I have some suggestions to hopefully cleanup the top-level interfaces in CAM and add some extra sanity checks, but otherwise everything looks good.

2024-09-12 21:35 UTC, nusbaume commented on src/physics/cam7/micro_pumas_cam.F90
> +      call tropopause_find_cam(state_loc, troplev, primary=TROP_ALG_CPP, backup=TROP_ALG_NONE, &
I think you'll need to initialize `troplev`, `cp_z`, and `cp_t` here (assuming they aren't initialized above):

```suggestion
      !REMOVECAM - no longer need this when CAM is retired and pcols no longer exists
      troplev(:) = 0
      cp_z(:) = 0._r8
      cp_t(:) = 0._r8
      !REMOVECAM_END
      call tropopause_find_cam(state_loc, troplev, primary=TROP_ALG_CPP, backup=TROP_ALG_NONE, &
```

2024-09-12 21:35 UTC, nusbaume commented on src/physics/cam/tropopause.F90
> +         tropp_p_loc    = tropp_p_loc(:,pstate%lchnk,:), &  ! Subset into chunk as the underlying routines are no longer chunkized.
Does `tropp_p_loc` need to subsetted by `ncol` as well?  I have the same question for `tropopause_findChemTrop` below too.

2024-09-12 21:35 UTC, nusbaume commented on src/physics/cam/tropopause.F90
> +         hstobie_tropop = hstobie_tropop, &  ! Only used if TROP_ALG_HYBSTOB
Do these need to be subset as well?  For example:

```suggestion
         hstobie_trop   = hstobie_trop(1:ncol,:), &    ! Only used if TROP_ALG_HYBSTOB
         hstobie_linoz  = hstobie_linoz(1:ncol,:), &   ! Only used if TROP_ALG_HYBSTOB
         hstobie_tropop = hstobie_tropop(1:ncol,:), &  ! Only used if TROP_ALG_HYBSTOB
```

2024-09-12 21:35 UTC, nusbaume commented on src/physics/cam/tropopause.F90
> +         tropLev        = tropLev, &
If you subset the `tropLev` variable here then you won't need to subset int in the `tropopause_findChemTrop` call itself:

```suggestion
         tropLev        = tropLev(1:ncol), &
```

2024-09-12 21:35 UTC, nusbaume commented on src/physics/cam/tropopause.F90
> +         tropLev        = tropLev, &
If you subset the `tropLev` variable here then you won't need to subset int in the `tropopause_find_cam` call itself:

```suggestion
         tropLev        = tropLev(1:ncol), &
```

2024-09-13 17:10 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +         hstobie_tropop = hstobie_tropop, &  ! Only used if TROP_ALG_HYBSTOB
Fixed, thank you!

2024-09-13 17:10 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +         tropLev        = tropLev, &
Updated, thank you!

2024-09-13 17:11 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +         tropLev        = tropLev, &
Updated, thank you! Also changed the logic for `tropP`, `tropT`, and `tropZ` similarly.

2024-09-13 17:12 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +         tropp_p_loc    = tropp_p_loc(:,pstate%lchnk,:), &  ! Subset into chunk as the underlying routines are no longer chunkized.
Updated, thank you!

2024-09-13 17:12 UTC, jimmielin commented on src/physics/cam/tropopause.F90
>      return
Thanks, updated to remove throughout.

2024-09-13 17:13 UTC, jimmielin commented on src/physics/cam7/physpkg.F90
> +                                  karman, cappa
Thanks for noticing, not sure why it got added. Removed.

2024-09-13 17:13 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +    use physconst,          only: rair, cpair, gravit, zvir, karman, cappa
Thanks for noticing, not sure why it got added. Removed.

2024-09-13 17:22 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +    !REMOVECAM
Thanks, added throughout.

2024-09-13 17:22 UTC, jimmielin commented on src/chemistry/geoschem/chemistry.F90
> +    CALL Tropopause_FindChemTrop(state, Trop_Lev(1:nY))
Thanks, updated throughout.

2024-09-13 17:22 UTC, jimmielin commented on src/physics/rrtmgp/radiation.F90
> +      call tropopause_find_cam(state, troplev(1:ncol), tropP=p_trop(1:ncol), primary=TROP_ALG_HYBSTOB, &
Thanks, updated!

2024-09-13 17:22 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +       call tropopause_find_cam(state,tropLev(1:ncol))
Thanks, updated throughout.

2024-09-13 17:23 UTC, jimmielin commented on src/physics/cam7/micro_pumas_cam.F90
> +      call tropopause_find_cam(state_loc, troplev, primary=TROP_ALG_CPP, backup=TROP_ALG_NONE, &
Thanks, updated!

2024-09-16 17:10 UTC, nusbaume approved these changes
Everything looks great to me now.  Thanks!

2024-09-18 21:57 UTC, cacraigucar requested changes
Mainly comment changes to make them more "long-term".  The comments were appropriate during your development (especially to yourself as you are making the mods).   Now that we are getting ready to commit, the comments should be less about what "used to be" and more general comments about what the code is doing.

2024-09-18 21:57 UTC, cacraigucar commented on src/physics/cam/tropopause.F90
> +    ! are using the new CAM-SIMA History infrastructure.
I don't think we need this comment.  Keeping the CAM addfld/outfld calls will be what all interface routines in ESCOMP/CAM will maintain.

2024-09-18 21:57 UTC, cacraigucar commented on src/physics/cam/tropopause.F90
> +    ! then replicate those outfld calls here.
Comments like "used to do X, now do Y" are great during development, but when we are ready commit, a long-term comment describing what is being done is more appropriate.  Something like `! Output hybridstobie specific fields`

2024-09-18 21:57 UTC, cacraigucar commented on src/physics/cam/tropopause.F90
> +    ! no longer accepts optional arguments during the CCPP-ization process.
Another comment which should now be replaced with a long-term comment (or in this case maybe no comment at all)

2024-09-18 21:57 UTC, cacraigucar commented on src/physics/cam/tropopause.F90
> +    ! This does not call the CCPP-ized "run" routine directly, because the CCPP-ized "run"
I would replace `CCPP-ized "run"` with `tropopause_find_run `in both places

2024-09-18 21:57 UTC, cacraigucar commented on src/physics/cam/tropopause.F90
> +    ! routine computes multiple needed tropopauses simultaneously. For non-SIMA CAM,
I would replace `For non-SIMA CAM` with `Instead`

2024-09-18 21:57 UTC, cacraigucar commented on src/physics/cam/tropopause.F90
> +    ! active columns is needed here.
Probably remove this comment as all CAM routines which are using routines which are CCPP'ized will have this feature and we don't need to spell it out.

2024-09-18 23:13 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! no longer accepts optional arguments during the CCPP-ization process.
Thanks, replaced with
```
    ! Dummy out arguments from tropopause_findWithBackup as it does not accept optional arguments.
```

To make it clear why these variables are present even unused.

2024-09-18 23:13 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! then replicate those outfld calls here.
Thanks, updated!

2024-09-18 23:13 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! are using the new CAM-SIMA History infrastructure.
Thank you for your suggestions, I will be sure to make comments in the future relevant to what is happening now vs. in-development comments. I've removed this comment.

2024-09-18 23:15 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! active columns is needed here.
Thank you, removed!

2024-09-18 23:15 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! routine computes multiple needed tropopauses simultaneously. For non-SIMA CAM,
Thank you, updated comment wording. For this particular case I believe this will be clearer and more relevant:
```
    ! Now call the unified routine with the CHEMTROP option, which has automatic
    ! backup fall to climatology.
```

2024-09-18 23:16 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! This does not call the CCPP-ized "run" routine directly, because the CCPP-ized "run"
Thank you, updated wording to
```
    ! This does not call the tropopause_find_run routine directly, because it
    ! computes multiple needed tropopauses simultaneously. Instead, here we
    ! specify the algorithm needed directly to the algorithm driver routine.
```
for this generic case, and a different comment for the `findChemTrop` call.

2024-09-19 17:27 UTC, jimmielin commented on src/physics/cam/tropopause.F90
> +    ! no longer accepts optional arguments during the CCPP-ization process.
Thank you, updated here and in another instance as well.

2024-09-19 17:27 UTC, jimmielin commented
> As a side note - I typically use a known string "CACNOTE" for things I need to address before my final commit. That way I can leave notes to myself during development, but can remove them before they become permanent.

Thank you, this is good to know. I leave `TODO`s here and there but had not thought of flagging comments that could be removed in the final commit as well.

2024-09-30 15:48 UTC, cacraigucar approved these changes

2024-10-01 01:28 UTC, jimmielin commented
All tests passed matching expected pre-existing failures.

The Derecho Intel test for SMS FCSD_HCO did not match baseline at initial attempt and was resubmitted and passed w/o any changes. The test is suspect due to reproducibility issues in HEMCO and may be solved by future GEOS-Chem updates...

```
➜  aux_run_failing_intel_20240930183121 ./cs.status.aux_run_failing_intel_20240930183121
aux_run_failing_intel_20240930183121: 1 test
  SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h (Overall: PASS) details:
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h CREATE_NEWCASE
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h XML
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h SETUP
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h SHAREDLIB_BUILD time=329
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h NLCOMP
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h MODEL_BUILD time=334
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h SUBMIT
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h RUN time=464
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h GENERATE /glade/derecho/scratch/hplin/aux_run_failing_intel_20240930183121/baselines
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h BASELINE /glade/campaign/cesm/community/amwg/cam_baselines/cam6_4_036_intel:
    FAIL SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h MEMCOMP [Errno 2] No such file or directory: '/glade/campaign/cesm/community/amwg/cam_baselines/cam6_4_036_intel/SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h/cpl-mem.log'
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h TPUTCOMP
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h MEMLEAK insufficient data for memleak test
    PASS SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h SHORT_TERM_ARCHIVER
```

2024-10-01 01:34 UTC, merged

2024-10-01 01:58 UTC, jimmielin commented
Baselines (including failed rerun for `SMS_Lh12.f09_f09_mg17.FCSD_HCO.derecho_intel.cam-outfrq3h`) archived on Izumi and Derecho