Timestamp in rpointer name
ESCOMP/CAM pull request #1147
Opened 2024-09-10 21:27 UTC by jedwards4b

Add a timestamp in the rpointer name.
This is a backward compatible change in that rpointer.cam will still work
but new files will include a timestamp.
Fixes #1146

2024-10-03 17:32 UTC, brian-eaton requested changes
minor comments and a question

2024-10-03 17:50 UTC, jedwards4b commented on src/control/cam_initfiles.F90
> +            inquire(file=trim(rest_pfile),exist=found)
done

2024-10-03 17:50 UTC, jedwards4b commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +            yr_spec=yr_spec, mon_spec=mon_spec, day_spec=day_spec, sec_spec= sec_spec )
Thanks for pointing out this bug, it should replace 'rpointer.cpl' below

2024-10-03 18:04 UTC, brian-eaton approved these changes
looks good now

2024-10-17 18:57 UTC, jedwards4b commented on src/control/runtime_opts.F90
> -
done

2024-10-29 13:59 UTC, jedwards4b commented
I'm not sure what happened to the history here.  I rebased to cam_development tag: cam6_4_043 and pushed back.  Now this PR shows my changes applied twice, but git log in my sandbox does not show the original commits.

2024-12-17 17:51 UTC, ekluzek commented
This is dependent on the CTSM tag, and updates to: cime, share, cmeps and cdeps.

@peverwhee on Izumi you'll need to update cdeps to cdeps1.0.61, otherwise you'll find problems with the CDEPS tests.

2024-12-20 23:21 UTC, merged