History bugfixes
ESCOMP/CAM pull request #1163
Opened 2024-10-03 22:34 UTC by peverwhee

## Summary
1. No longer override averaging flag to "I" if nhtfrq = 1 (every timestep). This reenables subcycling averages.
2. Check for incompatible duplicates
    - compatible duplicates (flags match) are ok - just take the first one (to keep existing CAM behavior)
    - incompatible duplicates (flags differ) - endrun
4. Update git-fleximod to 0.9.2

## Mods
*src/control/cam_history.F90*
- Remove nhtfrq=1 override
- modify `list_index` to optionally check for duplicates/compatibility
- endrun with message including all duplicates found (if necessary)
    - Sample error message: `ERROR:  FLDLST: Found duplicate field(s) with different averaging flags. Place in separate fincl lists: "Q:A", "Q:I" (fincl3). "T:A", "T:I" (fincl3). "U:A", "U:I" (fincl4).`

*bld/namelist_files/use_cases/sd_waccm_sulfur.xml*
- remove bad XML comment line

*.lib/git-fleximod/*
- update to 0.9.2

closes #1149 
closes #1150

2024-10-09 00:05 UTC, brian-eaton commented
I'll just point out that the reason for setting the averaging flag to `I` when `nhtfrq=1` is to get the correct timestamps.  If the flag is `A` then the timestamps are set to midpoint values which is not correct for a single timestep.

2024-10-29 19:17 UTC, peverwhee commented
@adamrher could you confirm that the addfld calls I've amended represent the full set of fields that are sampled on the subcycle?

2024-10-29 21:40 UTC, adamrher requested changes
Hi @peverwhee, I found some missing addfld calls. 

micro_pumas_cam.F90, marcop_driver.F90, microp_aero.F90 all look good. There are a 5 addflds you missed, in stats_init_clubb in clubb_intr.F90. I couldn't figure out how to add a review comment that deep into clubb_intr, but they start at line 5116.

microp_aero.F90 has some dependencies that have addfld calls. These are: ndrop.F90, ndrop_bam.F90, nucleate_ice_cam.F90, hetfrz_classnuc_cam.F90. All addflds in those modules need the sample_on_subcycle flag.

Lastly, the drivers in subcol_SILHS.F90 are called inside the macmic loop if use_subcol_microp=.true. Support for subcolumns is a grey area but it shouldn't be too much work (?) to add sample_on_subcycle to all the addflds in subcol_SILHS.F90.

2024-10-29 21:40 UTC, adamrher commented on src/physics/cam/check_energy.F90
> +    call addfld('DQCORE', (/ 'lev' /), 'A', 'kg/kg/s' , 'Water vapor tendency due to dynamical core', sampled_on_subcycle=.true.)
I would nix the ```sampled_on_subcycle``` for all these addflds in check_energy.F90 -- their outfld calls are in phypkg.F90, and outside the subcycles.

2024-10-29 23:03 UTC, peverwhee commented
@adamrher thanks for taking the time to check these! I've added/removed the `sampled_on_subcycle` arguments as you described.

- [x] stats_init_clubb in clubb_intr.F90 (5 fields)
- [x] ndrop.F90 (all addflds)
- [x] ndrop_bam.F90 (all addflds)
- [x] nucleate_ice_cam.F90 (all addflds)
- [x] hetfrz_classnuc_cam.F90 (all addflds)
- [x] subcol_SILHS.F90 (all addflds)
- [x] **REMOVE FROM** check_energy.F90 (all addflds)

2024-11-04 20:11 UTC, brian-eaton commented on src/control/cam_history.F90
>                   prev=prev, flag_spec='i' )
A 1 month test reveals that the filename of an instantaneous monthly file still does not match the time data in the file.  The problem is that monthly output files have `prev=.true.`, so the timestamp in the filename is 1 timestep earlier than the time data in the file.  Note that the `prev` option was implemented as a hack to get the expected month into the filename for monthly output files.  The time at the end of a monthly period is at 0Z of day 1 of the following month.  By backing up a timestep you get the date to contain the month that corresponds to the time period.  This option should not be on for instantaneous data, but the logic that sets `prev` only takes into account the output frequency and not whether it's an instantaneous or accumulated file.  I think the best solution here is to simply remove the `prev=prev` optional argument from this call to `interpret_filename_spec` since you never want to use a previous timestep for instantaneous data.

2024-11-04 22:32 UTC, peverwhee commented on src/control/cam_history.F90
>                   prev=prev, flag_spec='i' )
good catch, @brian-eaton !

I've removed the `prev` argument from `interpret_filename_spec` for the instantaneous file

2024-11-05 19:51 UTC, brian-eaton approved these changes
Looks good.

2024-11-19 23:50 UTC, cacraigucar reviewed
Curiosity led me to looking into this PR.  This is not intended to be a full review, but rather documents a couple of things that I saw.

2024-11-19 23:50 UTC, cacraigucar commented on .lib/git-fleximod/git_fleximod/cli.py
> +__version__ = "0.9.2"
I see that CESM is at 0.9.3 - should we be updating to that while we are at it?

2024-11-19 23:50 UTC, cacraigucar commented on test/system/archive_baseline.sh
> +    chmod_cmd="chmod -R a+r ${baselinedir}"
Just curious what this change is doing and why it is needed

2024-11-20 00:04 UTC, peverwhee commented on .lib/git-fleximod/git_fleximod/cli.py
> +__version__ = "0.9.2"
yep! i will do this tomorrow!

2024-11-20 00:05 UTC, peverwhee commented on test/system/archive_baseline.sh
> +    chmod_cmd="chmod -R a+r ${baselinedir}"
some cime changes recently resulted in the baselines on izumi having the wrong permissions. this updates the baselines to be globally readable.

per jesse's suggestion, I will be updating this to also run on derecho since it can't hurt to be globally readable!

2024-12-31 00:29 UTC, merged