CAM-Chem compset names
ESCOMP/CAM pull request #1164
Opened 2024-10-07 16:50 UTC by fvitt

Closes #1158

2024-10-09 20:19 UTC, cacraigucar requested changes

2024-10-09 20:19 UTC, cacraigucar commented on cime_config/config_compsets.xml
> +	<value  compset="HIST.*_CAM">1979-01-01</value>
Suggestion we came up with HIST(C_|E_|_)CAM

2024-10-09 20:19 UTC, cacraigucar commented on cime_config/config_component.xml
> +      <value compset="HIST.*%CT1S"       >hist_trop_strat_vbs_cam6</value>
Another location to be more explicit

2024-10-10 15:12 UTC, fvitt commented on cime_config/config_component.xml
> +      <value compset="HIST.*%CT1S"       >hist_trop_strat_vbs_cam6</value>
changed

2024-10-14 22:36 UTC, cacraigucar approved these changes

2024-10-16 14:05 UTC, merged