Vertical diffusion refactor
ESCOMP/CAM pull request #1176
Opened 2024-10-21 14:04 UTC by mwaxmonsky

Outsources solve phase of non-graft decomp solves to atmospheric physics solver.

2024-10-25 18:18 UTC, peverwhee commented on .gitmodules
> +        fxtag = c6ed2caae61dee8ba798011fa3eace583f3db917
going to be obnoxious here and request an official tag instead of a hash - it's a rule in CAM. 

e.g. time to open a PR to main in atmospheric_physics and make a tag.

2024-10-25 21:48 UTC, mwaxmonsky commented on .gitmodules
> +        fxtag = c6ed2caae61dee8ba798011fa3eace583f3db917
Updated!

2024-10-28 15:48 UTC, peverwhee requested changes
one question

2024-10-28 15:48 UTC, peverwhee commented on cime_config/config_pes.xml
> +	  <nthrds_cpl>1</nthrds_cpl>
Your description says this "fixes runtime error" - do we know why threading no longer works on izumi? If so, can we make sure to document this change and why in the changelog?

2024-10-30 14:44 UTC, mwaxmonsky commented on cime_config/config_pes.xml
> +	  <nthrds_cpl>1</nthrds_cpl>
Updated!

2024-10-31 03:49 UTC, nusbaume approved these changes
Looks good to me!  Just had one comment about the current test failures listed in the ChangeLog.

2024-10-31 03:49 UTC, nusbaume commented on doc/ChangeLog
> +SMS_D_Ln9_P1280x1.ne30pg3_ne30pg3_mg17.FHISTC_MTt1s.derecho_intel.cam-outfrq9s_Leung_dust (Overall: DIFF)
I assume these and the other "expected diff" test failures will go away once we do regression tests against `cam6_4_043`?  If not please let me know (as it could indicate something is wrong).

2024-10-31 04:07 UTC, mwaxmonsky commented on doc/ChangeLog
> +SMS_D_Ln9_P1280x1.ne30pg3_ne30pg3_mg17.FHISTC_MTt1s.derecho_intel.cam-outfrq9s_Leung_dust (Overall: DIFF)
Good catch!  I just copied these over from the latest tag changelog and was waiting to update it with the info from my runs but it looks like there were errors relating to my build so I'll clean check these out and re-run on Derecho and these should go away and I'll remove these from the log.

2024-11-01 14:28 UTC, peverwhee approved these changes

2024-11-07 17:46 UTC, merged