Implement CCPPized check_energy_chng and check_energy_fix
ESCOMP/CAM pull request #1180
Opened 2024-10-25 20:35 UTC by jimmielin

Closes #1138

## Purpose of changes
- CCPPize check_energy_chng and check_energy_fix
  CAM interfaces have been kept in check_energy.F90 instead of a new module because check_tracers is not yet CCPPized, there are other non-CCPPized routines in module, and for compatibility with FV3 external calls
- Save air_composition cp_or_cv_dycore into state snapshot
- Separate out "energy_formula_physics"/"energy_formula_dycore" definitions used in get_hydrostatic_energy from dyn_tests_utils "vcoord" for an eventual change in SIMA.

## Related issues
- Companion PR in atmos_phys: https://github.com/ESCOMP/atmospheric_physics/pull/145
- Companion PR in CAM-SIMA: https://github.com/ESCOMP/CAM-SIMA/pull/316

Files changed:
```
List all files eliminated: N/A

List all files added and what they do:
- separate out energy formula definitions used in get_hydrostatic_energy from dyn_tests_utils "vcoord"
A       src/utils/cam_thermo_formula.F90

List all existing files that have been modified, and describe the changes:

Update atmos_phys external with CCPPized check_energy
M       .gitmodules
M       bld/configure
M       src/atmos_phys

Save cp_or_cv_dycore in state snapshot
M       src/control/cam_snapshot_common.F90

New CAM interfaces to CCPPized routines, when avaialble
M       src/physics/cam/check_energy.F90

Update calls to CCPPized routines, when available
M       src/physics/cam/physpkg.F90
M       src/physics/cam/zm_conv_intr.F90
M       src/physics/cam7/physpkg.F90
M       src/physics/simple/physpkg.F90
M       src/physics/spcam/crm_physics.F90
M       src/physics/spcam/spcam_drivers.F90
```

2024-11-18 23:31 UTC, cacraigucar requested changes

2024-11-19 18:25 UTC, jimmielin commented on .gitmodules
> +        fxtag = b1e2c2a9
Thanks, updated to `atmos_phys0_07_000`!

2024-11-20 21:39 UTC, nusbaume requested changes
Looks good!  Just had a few requests, almost entirely related to comments.

2024-11-20 21:39 UTC, nusbaume commented on src/physics/cam/check_energy.F90
> +    real(r8), intent(in) :: ztodt                  ! 2 delta t (model time increment)
I would change this variable comment to the following:

```suggestion
    real(r8), intent(in) :: ztodt                  ! physics timestep (s)
```

2024-11-20 21:39 UTC, nusbaume commented on src/physics/cam/check_energy.F90
> +    real(r8), intent(in) :: flx_ice(:)             ! (pcols) -boundary flux of ice           (m/s) (snow?)
I might change these variable comments to the following:

```suggestion
    real(r8), intent(in) :: flx_cnd(:)             ! (pcols) -boundary flux of lwe liquid+ice  (m/s)
    real(r8), intent(in) :: flx_ice(:)             ! (pcols) -boundary flux of lwe ice         (m/s) 
```

2024-11-20 21:39 UTC, nusbaume commented on src/physics/cam/check_energy.F90
> +    elseif(state%psetcols > pcols) then
Total nit-pick, but I would add a space here:

```suggestion
    else if(state%psetcols > pcols) then
```

2024-11-21 02:37 UTC, jimmielin commented on src/physics/simple/physpkg.F90
>        call outfld( 'EFIX', flx_heat    , pcols, lchnk   )
Thanks, made an issue https://github.com/ESCOMP/atmospheric_physics/issues/161

One needs to be renamed and some need to be added/computed in a separate diagnostic scheme.

2024-11-21 02:39 UTC, jimmielin commented on src/control/cam_snapshot_common.F90
> +
Thanks, added!

2024-11-21 02:40 UTC, jimmielin commented on src/physics/cam/check_energy.F90
> +    real(r8), intent(in) :: ztodt                  ! 2 delta t (model time increment)
Thanks, updated!

2024-11-21 02:41 UTC, jimmielin commented on src/physics/cam/check_energy.F90
> +    real(r8), intent(in) :: flx_ice(:)             ! (pcols) -boundary flux of ice           (m/s) (snow?)
Thanks, updated!

2024-11-21 02:41 UTC, jimmielin commented on src/physics/cam/check_energy.F90
> +    elseif(state%psetcols > pcols) then
Thanks, updated!

2024-11-21 13:51 UTC, jimmielin commented on src/physics/cam/check_energy.F90
> +      if (vc_loc == ENERGY_FORMULA_DYCORE_MPAS .or. vc_loc == ENERGY_FORMULA_DYCORE_SE) then
Thanks, added above where `vc_loc` is first set!

2024-11-21 15:48 UTC, nusbaume approved these changes
Looks great to me now.  Thanks @jimmielin!

2024-11-21 18:56 UTC, cacraigucar approved these changes

2024-11-22 05:52 UTC, jimmielin commented
Thanks @nusbaume and @cacraigucar for the code reviews! I will wait for my turn to make a tag and run the test suite again.

If before my turn to make a tag, https://github.com/ESCOMP/atmospheric_physics/pull/160 is incorporated in a atmos_phys tag, I will use that tag and update the subroutine call for `check_energy_fix_run` to include dummy arguments for `errmsg` and `errflg`. Otherwise I will keep this on `atmos_phys0_07_000`.

2024-12-31 19:10 UTC, merged