Update CARMA external base
ESCOMP/CAM pull request #1201
Opened 2024-12-05 16:16 UTC by fvitt

Update CARMA base code to the latest tag (carma4_09) and updates existing CARMA models accordingly.

Closes #1181

2025-01-02 21:29 UTC, cacraigucar requested changes
This review was limited - I did not go into each CARMA model and look at the differences.

2025-01-02 21:29 UTC, cacraigucar commented on src/physics/carma/cam/carma_intr.F90
>    use carma_model_mod
The rest of these should probably have the "only" added to them as well

2025-01-02 22:07 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +     Zhao and Turco, JAS, V.26, No.5, 1995.
@tilmes and @cbardeen
Is this the Zhao and Turco paper referenced here?
https://doi.org/10.1016/0021-8502(95)00010-A

2025-01-02 22:13 UTC, tilmes commented on bld/namelist_files/namelist_definition.xml
> +     Zhao and Turco, JAS, V.26, No.5, 1995.
Zhao, J. and Turco, R.: Nucleation simulations in the wake of a jet aircraft in stratospheric flight, J. Aerosol Sci., 26, 779–795, https://doi.org/10.1016/0021-8502(95)00010-A, 1995.

2025-01-02 23:49 UTC, fvitt commented on src/physics/carma/cam/carma_intr.F90
>      call CARMA_Create(carma, NBIN, NELEM, NGROUP, NSOLUTE, NGAS, NWAVE, rc, &
@tilmes,
Do you know how NWAVE is defined here?

2025-01-03 00:20 UTC, tilmes commented on src/physics/carma/cam/carma_intr.F90
>      call CARMA_Create(carma, NBIN, NELEM, NGROUP, NSOLUTE, NGAS, NWAVE, rc, &
see: cam/carma_constants_mod.F90:  integer, public, parameter      :: NWAVE           = nlwbands+nswbands ! Number of wavelength bands

2025-01-03 14:54 UTC, fvitt commented on src/physics/cam/carma_flags_mod.F90
> +    call mpi_bcast (carma_do_coremasscheck,1 ,mpi_logical, masterprocid, mpicom, ierr)
checks added

2025-01-03 14:55 UTC, fvitt commented on src/physics/carma/cam/carma_intr.F90
>    use carma_model_mod
done

2025-01-03 16:09 UTC, cacraigucar approved these changes
Thanks for making the nitpicky changes

2025-01-07 16:10 UTC, merged