Add QPLT and QPMT compsets, plus misc.
ESCOMP/CAM pull request #1203
Opened 2024-12-06 19:40 UTC by brian-eaton

Resolve #814 - Introduce QPC7 and possibly QPS7 aquaplanet compsets
  - Analogous to FLT and FMT compset names, create QPLT and QPMT for the LT and MT versions of cam7.
  - Open new issue to address QPS7.
  - The new aquaplanet configurations use '-chem none' to eliminate the aerosols.  This is much faster and requires much less memory than a configuration that leaves the default chemistry in place and removes aerosols by zeroing the initial concentrations and emission sources.

Resolve #1159 - Prealpha tests exceeding wallclock
  - increased time limit to 20 minutes for these prealpha tests:
    ERP_Ln9.f09_f09_mg17.FHIST_BGC.derecho_intel.cam-outfrq9s
    ERP_Ln9.f09_f09_mg17.FHIST.derecho_intel.cam-outfrq9s

Resolve #670 - DAE test broken
  - The ChangeLog indicates that this test has never worked since it was added in cam6_2_046 (2020-09-01).  Test removed.

Resolve #807 - add UT and UQ to cam_diagnostics
  - Add UT and UQ diagnostics.  Note that other possible fields mentioned in the issue, i.e., OMEGA2, OMEGAQ, OMEGAU, and OMEGAV, are already implemented.  OMEGA2 is called OMGAOMGA.

```NOTE: this PR is in draft status pending finalizing some details of the QPMT configuration```

2024-12-17 21:22 UTC, brian-eaton commented
@brianpm  is waiting on me to provide some test runs of QPMT.  Almost there.

2025-01-09 21:01 UTC, cacraigucar requested changes

2025-01-10 16:53 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="QPLT" grid="ne3pg3_ne3pg3_mg37" name="ERP_D_Ln9" testmods="cam/outfrq9s">
Yes, good catch.  I added a QPLT and a QPMT test to prealpha on derecho/intel.

2025-01-10 17:30 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="derecho" compiler="intel" category="prealpha"/>
I think we want the aux_cam ones because they are run as often as cam tags are made, which is not true for prealpha.  Currently for each of QPLT and QPMT there is an ne30pg3 test on derecho/intel, and an ne3pg3 test on izumi/gnu.  As I add tests to aux_cam I have been looking for old tests to remove to keep the test time from growing.  I will be doing more of that in the PR to evaluate replacing cam5/cam6 tests by cam7.

2025-01-10 17:38 UTC, cacraigucar approved these changes

2025-01-13 15:34 UTC, merged