New CARMA trop_strat aerosol model
ESCOMP/CAM pull request #1210
Opened 2024-12-18 16:18 UTC by fvitt

Introduce CARMA trop_strat sectional aerosol model which can be as an alternative to the modal aerosol aerosol representation in CAM physics.

closes #495

2024-12-18 16:20 UTC, fvitt commented
Draft PR for now.  Needs to follow PR #1201.

2025-01-17 23:39 UTC, cacraigucar requested changes
I still have quite a ways to go, but I am submitting my current review comments so they don't get lost.

2025-02-12 16:02 UTC, fvitt commented on bld/build-namelist
>                  # Look for values that begin with 'X:name:name2' where X is one of [AMN]
'B' has been added in the comment

2025-02-12 16:03 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +Default: 0
The description has been update.

2025-02-20 22:22 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="fv"  hgrid="1.9x2.5"   nlev="32"  aquaplanet="1" carma="trop_strat_soa5">atm/cam/inic/fv/QPCARMATS_f19_carmats4038_spinup01_0002-01-01_c241029.nc</ncdata>
done

2025-02-20 22:22 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="fv"  hgrid="1.9x2.5"   nlev="70"                 carma="trop_strat_soa1">atm/waccm/ic/FWmaCARMAHIST_f19_carmats038_spinupl03.cam.i.1980-01-01_c241025.nc</ncdata>
done

2025-02-20 22:22 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="fv"  hgrid="1.9x2.5"   nlev="70"  aquaplanet="1" carma="trop_strat_soa1">atm/cam/inic/fv/aqua_carma_waccm_0002-01-01_1.9x2.5_L70_c220809.nc</ncdata>
done

2025-02-20 22:22 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<OC_GFEDv3_filename>atm/cam/chem/carma/data/GFEDv3_OC_2010.nc</OC_GFEDv3_filename>
done

2025-02-20 22:35 UTC, cacraigucar requested changes

2025-02-20 22:35 UTC, cacraigucar commented on src/chemistry/aerosol/carma_aerosol_properties_mod.F90
> +    allocate(imx_bl(nbins))
Probably should have check on these allocates

2025-02-20 22:35 UTC, cacraigucar commented on src/chemistry/aerosol/carma_aerosol_properties_mod.F90
> +             ! assuming  PRSULF and  MXSULF have the same number of bins
Should there be an actual check that these have the same number of bins?

2025-02-25 17:36 UTC, fvitt commented on src/chemistry/aerosol/carma_aerosol_properties_mod.F90
> +    allocate(imx_bl(nbins))
added checks

2025-02-25 17:37 UTC, fvitt commented on src/chemistry/aerosol/carma_aerosol_properties_mod.F90
> +             ! assuming  PRSULF and  MXSULF have the same number of bins
I don't think the same number of bins is required here.  I changed the comment.

2025-02-25 22:42 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> + Specified -- {{ hilight }}emissions_specifier{{ closehilight }} method which places emissons in physcis buffer
Oh I see you are pointing out a typo

2025-02-26 17:29 UTC, fvitt commented on src/chemistry/carma_aero/aero_model.F90
> +    if (.not. is_spcam_m2005) then  ! regular CAM
Cleaned out the spcam logic

2025-02-26 17:29 UTC, fvitt commented on src/chemistry/carma_aero/aero_model.F90
> +    !endif
removed

2025-02-26 17:29 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> + Specified -- {{ hilight }}emissions_specifier{{ closehilight }} method which places emissons in physcis buffer
fixed

2025-02-26 17:29 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> + Specified -- {{ hilight }}elev_emis_specifier{{ closehilight }} method which places emissons in physcis buffer
fixed

2025-02-26 17:29 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +namelist variable {{ hilight }}elve_emis_specifier{{ closehilight }}.  The
fixed

2025-02-26 17:29 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +That is, the {{ hilight }}elve_emis_specifier{{ closehilight }} variable is
fixed

2025-02-26 17:30 UTC, fvitt commented on src/chemistry/carma_aero/aero_model.F90
> +    allocate( &
added checks for the allocates

2025-02-26 17:31 UTC, fvitt commented on src/chemistry/carma_aero/aero_model.F90
> +    end do
needed for the outfld calls

2025-02-26 17:31 UTC, fvitt commented on src/chemistry/carma_aero/aero_model.F90
> +             vmr_total(:ncol,:) = vmr_total(:ncol,:) +  vmr(:ncol,:,mm)
removed the unused vmr_total

2025-02-26 17:32 UTC, fvitt commented on src/chemistry/carma_aero/sox_cldaero_mod.F90
> +                !qin(i,k,id_h2so4) =  MAX( qin(i,k,id_h2so4),  small_value )
Needs to be kept -- removed the "TEST" comments

2025-02-26 17:33 UTC, fvitt commented on src/chemistry/carma_aero/sox_cldaero_mod.F90
> +                !st endif
removed

2025-02-26 17:33 UTC, fvitt commented on src/chemistry/aerosol/hygrocoreshell_aerosol_optics_mod.F90
> +       palb(icol) = 1._r8-pabs(icol)/max(pext(icol),1.e-40_r8)
removed duplicate line

2025-02-26 17:33 UTC, fvitt commented on src/chemistry/aerosol/hygrowghtpct_aerosol_optics_mod.F90
> +       palb(icol) = 1._r8-pabs(icol)/max(pext(icol),1.e-40_r8)
removed duplicate line

2025-02-26 17:33 UTC, fvitt commented on src/chemistry/aerosol/hygrocoreshell_aerosol_optics_mod.F90
> +    real(r8),intent(out) :: pasm(ncol) ! parameterized single scattering albedo
Good catch.  Fixed.

2025-02-27 22:16 UTC, fvitt commented on src/chemistry/carma_aero/sox_cldaero_mod.F90
> +                dqdt = dqdt_aq
fixed

2025-02-27 22:16 UTC, fvitt commented on src/chemistry/carma_aero/sox_cldaero_mod.F90
> +                dqdt = dqdt_aq
fixed

2025-02-27 22:19 UTC, fvitt commented on src/chemistry/carma_aero/aero_model.F90
> +    ! add plus one to include number, total mmr and nspec
removed comment

2025-02-28 17:29 UTC, fvitt commented on src/chemistry/aerosol/carma_aerosol_state_mod.F90
> +          diamdry = rdry(i,k) * 2.e4_r8 * 1.e6_r8 ! diameter in microns (from radius in m)
@tilmes See the error here

2025-02-28 18:36 UTC, fvitt commented on src/chemistry/aerosol/carma_aerosol_state_mod.F90
> +          diamdry = rdry(i,k) * 2.e4_r8 * 1.e6_r8 ! diameter in microns (from radius in m)
fixed

2025-02-28 19:34 UTC, cacraigucar approved these changes

2025-03-05 22:32 UTC, merged