Nitrogen deposition fluxes
ESCOMP/CAM pull request #1216
Opened 2024-12-30 17:26 UTC by fvitt

Addresses #1196

2025-01-06 15:54 UTC, brian-eaton requested changes

2025-01-06 15:54 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +
By making use of the `sim_year` attribute we could define all the options for the `stream_ndep_*` variables right here rather than modifying a bunch of use case files for the non-`2000_` cases.

2025-01-06 15:54 UTC, brian-eaton commented on bld/namelist_files/use_cases/1850_cam_lt.xml
> +<stream_ndep_data_filename>lnd/clm2/ndepdata/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc</stream_ndep_data_filename>
This value of filename doesn't match what `config_component.xml` set for the `1850_` case.  Another good reason to set all these defaults in one place in `namelist_defaults_cam.xml`.

2025-01-06 15:54 UTC, brian-eaton commented on bld/namelist_files/use_cases/1850_cam_mt.xml
> +<stream_ndep_data_filename>lnd/clm2/ndepdata/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc</stream_ndep_data_filename>
Wrong filename.

2025-01-07 18:55 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +
@brian-eaton 
I like your suggestion here. However this approach does not work for me.  See mods to my sandbox on derecho here:
```
 /glade/work/fvitt/camdev/nitro_dep_fluxes
```

It seems that the first entries in namelist_defaults_cam.xml are used, regardless of the `sim_year` setting...

2025-01-07 19:35 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +
@fvitt, I have just looked at `build-namelist` in the  sandbox you pointed to.  It doesn't contain the mods needed to make this work.  Take a look at how it sets the default for `co2_readflux_fuel` for an example.  Also, since the `add_default` call needs to pass the `sim_year` attribute, you'll need to move the `add_default` calls for the `stream_ndep_*` variables to below where `$sim_year` is set (or move the setting of `$sim_year` up higher).

2025-01-09 15:46 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +
@brian-eaton This has been updated us you suggested.  I think it is working correctly now.
Thank you for the tips.

2025-01-09 18:02 UTC, brian-eaton reviewed
The definition of `sim_year` in `namelist_definition.xml` needs to have `2010` and `1850-2015` added to the list of valid values.

I wasn't sure whether the `sim_year` attribute needed to be added to any of the use case files that don't currently set it.  It depends on whether the use case is for a configuration that prognoses the ndep fluxes or not.  I don't know how to figure that out without running the model.

2025-01-10 20:43 UTC, cacraigucar requested changes
Minor comment requests

2025-01-10 20:43 UTC, cacraigucar commented on doc/ChangeLog
> + of providing the fluxes.  Deprecated ndep_list option in drv_flds_in has beed removed.
`beed` should be `been`

2025-01-10 20:43 UTC, cacraigucar commented on doc/ChangeLog
> +Purpose of changes (include the issue number and title text for each relevant GitHub issue):
I looked for a mention of the removal of the SSP's in config_component and I did not see a mention about it in the ChangeLog.  Or are the SSP's still handled, but not in CAM code anymore?  Regardless, I believe a brief comment might be appropriate.

2025-01-15 16:09 UTC, fvitt commented on doc/ChangeLog
> + of providing the fluxes.  Deprecated ndep_list option in drv_flds_in has beed removed.
fixed

2025-01-15 16:09 UTC, fvitt commented on doc/ChangeLog
> +Purpose of changes (include the issue number and title text for each relevant GitHub issue):
I added a blurb about SSP compsets

2025-01-15 16:10 UTC, fvitt commented on bld/namelist_files/use_cases/2010_geoschem.xml
Good catch.  I added sim_year to geoschem use case files.

2025-01-15 16:13 UTC, brian-eaton approved these changes

2025-01-15 22:27 UTC, cacraigucar approved these changes

2025-01-17 02:25 UTC, merged