initial implementation of CLUBB+MF
ESCOMP/CAM pull request #221
Opened 2020-09-17 22:41 UTC by adamrher

Code mods are limited to CAM. No externals needed to be modified, contrary to the description in the original issue. I've populated the ChangeLog with all the relevant information that I could think of. 

The mods do not impact the answers because the mass fluxes default to off. I would like to develop a test to protect this functionality with the mass fluxes on, and suggest the following configuration

--comp FSCAM
--res T42_T42
--user-mods-dir $src/cime_config/usermods_dirs/scam_bomex
do_clubb_mf = .true.
deep_scheme='off'

Fixes https://github.com/ESCOMP/CAM/issues/213
Fixes https://github.com/ESCOMP/CAM/issues/181

@JulioTBacmeister @mikaelwitte

2020-09-28 17:57 UTC, mikaelwitte commented on src/physics/cam/edmf_module.F90
> +       ! get entrainent, ent=ent0/dz*P(dz/L0)
Should be "entrain**m**ent"

2020-09-28 17:57 UTC, mikaelwitte commented on src/physics/cam/edmf_module.F90
>         wstar  = max( wstarmin, (gravit/thv(1)*wthv*pblh)**(1./3.) ) ! MKW NOTE: is it better to use kts instead of index 1 for surface?
Can remove comment since kts no longer used

2020-09-28 17:59 UTC, mikaelwitte commented on src/physics/cam/edmf_module.F90
> +           !if (i.eq.1) then
Maybe a larger comment, but perhaps worth adding a debug flag for prints - this will be really useful when we start working on the plume microphysics because all kinds of weird stuff is bound to pop up, and print statements will be helpful.

2020-09-28 18:05 UTC, mikaelwitte reviewed
Pardon the piecemeal nature of my comments, still figuring out the workflow. Almost all of my comments address comment typos I let slide when I inherited this code, but now that others are using this I'd like to see them corrected.

2020-09-28 18:05 UTC, mikaelwitte commented on src/physics/cam/edmf_module.F90
> +           ! get wn^2, to avoid singularities w equation has to be computed diferently if wp==0
Should be "dif**f**erently"

2020-09-28 20:48 UTC, mikaelwitte commented on src/physics/cam/edmf_module.F90
> +  ! The Art of Computer Programming, v3, 137-138
Reference is to volume 2 instead of 3.

2020-09-28 20:52 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +           !if (i.eq.1) then
Agreed. I will add debug flag to dump out buoyancy ... which is an arbitrary choice but at least provides a template to replicate debug statements.

2020-09-29 00:12 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +  ! The Art of Computer Programming, v3, 137-138
done

2020-09-29 00:12 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +           ! get wn^2, to avoid singularities w equation has to be computed diferently if wp==0
done

2020-09-29 00:12 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +           !if (i.eq.1) then
done

2020-09-29 00:12 UTC, adamrher commented on src/physics/cam/edmf_module.F90
>         wstar  = max( wstarmin, (gravit/thv(1)*wthv*pblh)**(1./3.) ) ! MKW NOTE: is it better to use kts instead of index 1 for surface?
done

2020-09-29 00:12 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +       ! get entrainent, ent=ent0/dz*P(dz/L0)
done

2020-10-05 20:39 UTC, cacraigucar requested changes
Once these changes have been made and pushed back to your PR, please ask for a re-review (hit the two circular arrows by my reviewer name).   At that point, I will add the other CAM-SE reviewers to the list for their review.

2020-10-05 20:39 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +If TRUE run CLUBB-MF
Comments here are what are displayed in CAM's namelist web page.  Please give a little more explanation for this and the subsequent namelist parameters.  (i.e. for this variable what is CLUBB-MF?)

2020-10-05 20:39 UTC, cacraigucar commented on doc/ChangeLog
> +Github PR URL: NA
This can be changed now that there is a github PR URL.

2020-10-05 20:39 UTC, cacraigucar commented on doc/ChangeLog
> + - src/physics/cam/clubb_intr.F90
Typically we list each file individually.  Then we comment on what is modified in each file or group of files.  You can look at past ChangeLog entries for examples.

2020-10-05 20:39 UTC, cacraigucar commented on doc/ChangeLog
> + - since mass fluxes are off by default, there are bit-for-bit no changes.
Not sure I understand this sentence

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +    call mpi_bcast(do_clubb_mf, 1, mpi_logical,   mstrid, mpicom, ierr)
These two lines are backwards.  You check the error status and report it if needed after the mpi_bcast call for that variable.

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +       call add_default('THETAL',           1, ' ')
Confirming that adding this to all  runs when history_clubb is turned on was intended.

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +           ep2 = 1.0/ep
All real numbers in code need to have "_r8" attached to the end to make sure they match the r8 type.

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +         ! MKW convert edmf flx variables to W/m2
When code is ready for a PR, please remove developer initials as they should not be committed.

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +           mf_qtflx(:)     = 0._r8
These shouldn't need to be initialized to zero for when do_clubb_mf is false.  We never want to output a field full of known zeroes.  See the suggestion below about putting an if statement around the outfld calls instead.

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'edmf_qtflx'    , mf_qtflx_output,           pcols, lchnk )
Put these outfld calls within an "if (do_clubb_mf) then" section

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/edmf_module.F90
> +       sigmath = 2.890_r8 * abs(thstar)/ 1._r8
We like to document constants.  What are 0.572_r8 and 2.890_r8?  Are these from a paper or do they have a definition?

2020-10-05 20:39 UTC, cacraigucar commented on src/physics/cam/edmf_module.F90
> +         upthv(1,i) = thv(1) + 0.58_r8 * upw(1,i) * sigmath/sigmaw
More constants to possibly define

2020-10-06 23:02 UTC, mikaelwitte commented on src/physics/cam/clubb_intr.F90
> +                               do_clubb_mf
One other MF parameter that would be very convenient to set from namelist is nup (number of updrafts)

2020-10-06 23:05 UTC, mikaelwitte commented on src/physics/cam/clubb_intr.F90
> +                               do_clubb_mf
Further suggestion: move nup to edmf_module so it doesn't have to be an input to integrate_mf. That way we can keep it in clubb_mf_nl instead of putting another MF parameter in clubb_params_nl.

2020-10-07 00:47 UTC, adamrher commented on doc/ChangeLog
> + - since mass fluxes are off by default, there are bit-for-bit no changes.
I'm trying to say the do_clubb_mf logical is set to false in namelist_defaults, so that an out-of-box run should not change answers. Answers will change if user decides to turn mass fluxes on.

2020-10-07 00:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'edmf_qtflx'    , mf_qtflx_output,           pcols, lchnk )
how about the equivalent addfld calls? Should I put a do_clubb_mf logical around those as well?

2020-10-07 01:34 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +If TRUE run CLUBB-MF
done

2020-10-07 01:34 UTC, adamrher commented on doc/ChangeLog
> +Github PR URL: NA
done

2020-10-07 01:35 UTC, adamrher commented on doc/ChangeLog
> + - src/physics/cam/clubb_intr.F90
I added text for each file. I didn't so every single scam file though...

2020-10-07 01:35 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    call mpi_bcast(do_clubb_mf, 1, mpi_logical,   mstrid, mpicom, ierr)
yes they are. fixed.

2020-10-07 01:35 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +         ! MKW convert edmf flx variables to W/m2
done

2020-10-07 01:36 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +           mf_qtflx(:)     = 0._r8
removed these and added do_clubb_mf logical around the outfld calls, as suggested below.

2020-10-07 01:36 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +       sigmath = 2.890_r8 * abs(thstar)/ 1._r8
made these constants and added descr. + reference.

2020-10-07 01:37 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +         upthv(1,i) = thv(1) + 0.58_r8 * upw(1,i) * sigmath/sigmaw
made these constants and added descr. + reference.

2020-10-07 01:37 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +                               do_clubb_mf
added clubb_mf_nup to clubb_mf namelist group

2020-10-07 02:38 UTC, adamrher commented
Hi Cheryl, I've made most of the changes you had asked for, but I need a morning and some fresh coffee to make sure I'm ready to push my changes.

2020-10-07 04:25 UTC, mikaelwitte commented on src/physics/cam/edmf_module.F90
> +                                    pwmax = 3._r8,            &
Remove trailing comma and ampersand

2020-10-07 16:11 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +                                    pwmax = 3._r8,            &
i guess i fixed this b/c its not in my sandbox anymore.

2020-10-07 16:12 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'edmf_qtflx'    , mf_qtflx_output,           pcols, lchnk )
ok, I condtioned addfld calls on do_clubb_mf, as well as the block setting the xxx_output vars

2020-10-07 16:15 UTC, adamrher commented on doc/ChangeLog
> + - since mass fluxes are off by default, there are bit-for-bit no changes.
example: here is my clubbmf branch with do_clubb_mf = .false. compared to cam6_3_000 unmodified. No answer changes.

![temp_scam](https://user-images.githubusercontent.com/29961476/95358172-fcce8e80-0885-11eb-9f8a-ea2643fdd0fa.png)

2020-10-07 16:21 UTC, adamrher commented
@cacraigucar it is saying I have a conflict with my new ChangeLog, but I can't see anything wrong. Any idea what's going on here?

2020-10-07 19:30 UTC, cacraigucar commented
> @cacraigucar it is saying I have a conflict with my new ChangeLog, but I can't see anything wrong. Any idea what's going on here?
> 
> EDIT: ohh. I presume it's because the head of CAM is cam6_3_001 and I'm branching off of cam6_3_000. Seems like an easy fix, but I can't hit the resolve conflicts button. Should I add in the cam6_3_001 ChangLog entry in my branch and commit?

We'll worry about the ChangeLog when we get ready to commit.  For now, don't worry about it.

2020-10-07 19:33 UTC, cacraigucar commented on doc/ChangeLog
> + - since mass fluxes are off by default, there are bit-for-bit no changes.
I would suggest that it be reworded:
since mass fluxes are off by default, there are no answer changes and the results are bit-for-bit

2020-10-07 19:35 UTC, cacraigucar commented
@adamrher   Thanks for the edits - it looks good.  I have requested the other CAM SEs to review this now.

2020-10-09 16:51 UTC, cacraigucar commented
@adamrher   We will need to introduce a CAM regression test for this configuration (when do_clubb_mf is set to true).  Would a 9 time step test be sufficient to uncover any changes which might creep in?   What grids are you going to want to support with this? 
We'll routinely test one or more of them.

2020-10-09 17:00 UTC, nusbaume requested changes
Looks good! Just some (hopefully) minor clean-up requests, and a few questions.

2020-10-12 19:43 UTC, brian-eaton requested changes

2020-10-12 19:43 UTC, brian-eaton commented on src/control/runtime_opts.F90
> +   use edmf_module,         only: clubb_mf_readnl
Since edmf is only used with clubb I'd be inclined to just call clubb_mf_readnl from clubb_readnl and remove the call from runtime_opts.  It's good to minimize the footprint in CAM's infrastructure.

2020-10-12 19:43 UTC, brian-eaton commented on src/physics/cam/clubb_intr.F90
> +       end if
It's probably a good idea to add another logical variable, say do_clubb_mf_diag, so that these fields which are most likely only of interest to EDMF developers aren't automatically added to the default output.  That's a lot of history file bloat for production runs.

2020-10-12 19:43 UTC, brian-eaton commented on src/physics/cam/edmf_module.F90
> +    use units,           only: getunit, freeunit
We updating our namelist reading code to no longer use getunit/freeunit by making use of the newunit option in the open call.  See for example the dyn_readnl routine in src/dynamics/fv3/dyn_comp.F90.

2020-10-13 17:56 UTC, mikaelwitte commented on src/physics/cam/clubb_intr.F90
> +      call addfld ( 'edmf_S_AE'     , (/ 'ilev' /), 'A', 'fraction', 'a_e (EDMF)' )
There is a sum wrapped up in this but it's not sum(a_e). Rather, the environment area fraction a_e=1-sum(a_i) where  a_i is the area fraction of each plume.

2020-10-13 18:41 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +      call addfld ( 'edmf_S_AE'     , (/ 'ilev' /), 'A', 'fraction', 'a_e (EDMF)' )
@mikaelwitte Thanks for the clarification!  In that case does it make sense to include something like `1 - sum of ai` in the variable long name, so future users don't get confused like I just did?

2020-10-15 21:18 UTC, fvitt commented on src/physics/cam/clubb_intr.F90
> +           ep2 = 1.0/ep
1.0 should be 1.0_r8 ?

2020-10-20 21:42 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
hi Jesse, I think for background, know that this PR is for a bare bones version that I suspect will end up looking quite a bit different after further development/PRs. I will probably introduce more params and eliminate some params down the road as well. So I'm hesitant to start making all these params namelists. Also Brian wants me to readnl from the clubb_intr, which means I have to pass all nl vars into a subroutine in this module. So at this stage, I'd like to keep nl to only the most important params. Is that OK?

2020-10-20 22:31 UTC, brian-eaton commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
My suggestion was to call clubb_mf_readnl from clubb_readnl.  The data would be stored in the same location as before.

2020-10-20 22:44 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
ok, I misunderstood. I had thought all calls to xxx_readnl are done in runtime_opts.F90. You're saying call clubb_mf_readnl in clubb_readnl. Would you mind telling me how I can grab the input argument to clubb_mf_readnl, i.e., the filepath+filename for namelist inputs?

2020-10-20 22:51 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
err, nrmind brian. I think I got it.

2020-10-21 01:18 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Real: Entrainment length scale for individual plumes
done

2020-10-21 01:18 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      call addfld ( 'edmf_S_AE'     , (/ 'ilev' /), 'A', 'fraction', 'a_e (EDMF)' )
changed def. to 1 - sum(ai) for clarity

2020-10-21 01:19 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      call addfld ( 'edmf_qtflx'    , (/ 'ilev' /), 'A', 'W/m2'    , 'qt flux by edmf (EDMF)' )
removed the redundant edmf

2020-10-21 01:19 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +       call add_default('THETAL',           1, ' ')
removed redundant thetal call

2020-10-21 01:19 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +                              !um_in,     vm_in,       thlm_in,    rtm_in,     thvm_in,        & ! input
removed commented out line.

2020-10-21 01:22 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
reduced nl vars to only those necessary (do_clubb_mf, do_clubb_mf_diag, clubb_mf_L0, clubb_mf_ent0). If it has been decided that I need to move all params to nl pls let me know.

2020-10-21 01:23 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +           !!upthv(1,i) = thv(1) + 0.58_r8 * upw(1,i) * sigmathl/sigmaw
removed this line ... resorted to computing it that the way JPL does it.

2020-10-21 01:23 UTC, adamrher commented on src/control/runtime_opts.F90
> +   use edmf_module,         only: clubb_mf_readnl
done

2020-10-21 01:24 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +       end if
made/implemented nl do_clubb_mf_diag as suggested.

2020-10-21 01:24 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +    use units,           only: getunit, freeunit
done

2020-10-21 01:25 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +           ep2 = 1.0/ep
removed these lines as I have decided against using the calculation that uses these ep vars

2020-10-28 21:25 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +      call addfld ( 'edmf_S_AE'     , (/ 'ilev' /), 'A', 'fraction', 'a_e (EDMF)' )
Thanks!

2020-10-29 00:05 UTC, nusbaume commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
I would personally lean towards more namelist parameters rather then less.  The reason is because I feel that parameters that exist solely in the source code tend to get "buried" over time, which can result in users not realizing of their existence when doing experiments related to parameter sensitivity, objective tuning, etc.  

That being said, given that it sounds like this is the initial commit of a parameterization that will need additional developments over time, I agree that it is probably not a major concern for this PR.

2020-10-29 00:06 UTC, nusbaume approved these changes
Thanks for taking care of my requests Adam!  Everything looks good to me now.

2020-10-29 17:14 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
it's my preference to provide exhaustive namelists in another PR. My development branch has already diverged quite a bit from this commit.

2020-10-29 17:55 UTC, cacraigucar commented
@adamrher and @cacraigucar have been having offline discussions on a proposed test for this new feature.  We have concluded we would like to add this test to an existing test.  There have been discussions on whether an aquaplanet or SCAM test would be preferable.  Thoughts from others?

2020-11-02 16:52 UTC, cacraigucar commented
> @adamrher and @cacraigucar have been having offline discussions on a proposed test for this new feature. We have concluded we would like to add this test to an existing test. There have been discussions on whether an aquaplanet or SCAM test would be preferable. Thoughts from others?

@fischer-ncar might actually have some insights as well as @brian-eaton and @gold2718

2020-11-04 20:13 UTC, cacraigucar commented
@adamrher - After speaking with @gold2718 about the proposed test for this modification, we agreed that SCAM is not an adequate test.  We also discussed the difference between aquaplanet and F compset tests, and it really comes down to your thoughts on whether topography is important for your test or  not.  @brianpm might also have some thoughts on whether aquaplanet would be appropriate to test CLUBB+MF.  Aquaplanet has the benefit of being a fast test, but only for those instances where feature is adequately tested (to make sure future CAM commits do not break the feature.  Please let us know your thoughts and I can help you find a test we can repurpose for this feature.

2020-11-04 20:37 UTC, adamrher commented
Aqua-planet test if fine by me. I can't think of any good reason that topo is req'd for a CLUBB+MF test. When you have time, it would be great if you could suggest a test that I can repurpose for CLUBB+MF.

2020-11-04 22:28 UTC, cacraigucar commented
@brianpm and @adamrher - Do either of you have a feel for whether a QSC6 or QPC6 aquaplanet test is better for testing CLUBB+MF?  Also is there a preferred dycore, or does any dycore work equally well?

2020-11-04 22:54 UTC, adamrher commented
QSC6, is that slab ocean? If it is I don't see the advantage of that extra level of complexity. The equatorial convection on QPC6 is pretty good test, id say.

I don't have a preference on dycores, but I was looking through the test list and I don't think I saw any tests for CAM-SE-CSLAM (?). Maybe this is a convenient opportunity so we can also start officially supporting that dycore? Just a thought.

2020-11-04 22:56 UTC, mikaelwitte commented
@adamrher conservative EDMF team thought: use a well-vetted dycore so it's easier to determine whether "weird stuff" is caused by EDMF vs. other model components.

2020-11-04 23:13 UTC, cacraigucar commented
@mikaelwitte Thanks for your comment.  The test we are talking about is one that will be run every time a new CAM tag is made, to make sure that new code changes do not accidentally break the CLUBB+MF capability.  This test is usually only 9 time steps in length and "passes" if the code is bit-for-bit with the previous version (unless code changes are known to change the answers).   With this is mind, do you still suggest not using the CAM-SE-CSLAM or will it exercise the CLUBB+MF code sufficiently to make sure that no inadvertent changes creep in?

2020-11-04 23:17 UTC, mikaelwitte commented
@cacraigucar thanks for the added context. You correctly assumed that I was thinking of longer simulations from which we're trying to make physical inferences. No further objection from me.

2020-11-05 00:18 UTC, cacraigucar commented
@adamrher It sounds like we will be creating a new test.  I believe that it will be a QPC6.  I need to get from you the a CAM-SE-CSLAM grid (the coarser the better from a testing standpoint) and a user_nl_cam that you would use to setup the CLUBB+MF test.  I can then setup the new test, run it to make sure it works and then push it back to your fork for the upcoming commit.

2020-11-05 00:48 UTC, adamrher commented
Do you just need the grid alias? There is a low-res grid ne5pg3_ne5pg3_mg37 which is about 666km grid spacing. Is that coarse enough?

2020-11-05 02:38 UTC, brianpm commented
I agree that QPC6 seems like an appropriate test. No reason to ask for trouble by introducing the slab-ocean.

2020-11-05 15:07 UTC, adamrher commented
@cacraigucar I do see that ne5pg3 has the right ncdata file for QPC6, but I dont think it has a drydep_srf_file. I can create one. But my bigger question concerns whether or not this decision to use ne5pg3 will lengthen the time to complete this PR. If you think it might (set the drydep srf file aside, I can do that in a matter of minutes), I would advocate for modifying an existing test. I don't want to hold up the CPT folks who are waiting on this PR.

The lack of tests for neXXpg3 and other new grids is a bigger issue that will prob require a separate PR.

2020-11-05 15:08 UTC, adamrher commented
Also the namelist mods to run the test should be:

do_clubb_mf = .true.
do_clubb_mf_diag = .true.
deep_scheme='off'

2020-11-05 16:55 UTC, cacraigucar commented
@adamrher I will set up a new QPC6 test using the f10_f10_mg37 compset and using your namelist mods.  I will also indicate that this test will be replaced with a CAM-SE-CSLAM grid when the pieces are ready.  This gives us a "fallback" test if you are not able to get the files ready in time for the PR going in.  That said, PR #246 is ahead of this one.  While it is nearing completion, it isn't done yet, so there is a bit of time for you to get the CAM-SE-CSLAM files ready for a ne5pg3_ne5pg3_mg37 grid.  If you make it in time, we can replace the f10_f10_mg37 with the ne5pg3_ne5pg3_mg37 grid.

2020-11-05 17:41 UTC, adamrher commented
OK. Thanks Cheryl. I presume add the ne5pg3 drydep_srf_file to the namelist_defaults on my branch when I create it?

2020-11-05 17:50 UTC, cacraigucar commented
> OK. Thanks Cheryl. I presume add the ne5pg3 drydep_srf_file to the namelist_defaults on my branch when I create it?

Yes, and we'll need to change the f10_f10_mg37 grid in the testlist_cam.xml to use this new grid.

2020-11-05 18:17 UTC, gold2718 commented
> @adamrher It sounds like we will be creating a new test. I believe that it will be a QPC6

Is the new test so we can switch to ne5pg3 when all the input files are ready?

2020-11-05 19:04 UTC, cacraigucar commented
> > @adamrher It sounds like we will be creating a new test. I believe that it will be a QPC6
> 
> Is the new test so we can switch to ne5pg3 when all the input files are ready?

Yes, changing the test should be as simple as switching the grid.  I just pushed back the "fallback" test in case the ne5pg3 grid isn't ready when CLUBB+MF is in line for making its PR commit.

2020-11-05 21:07 UTC, adamrher commented
I've added the drydep_srf_file for ne5pg3 and that QPC6 runs. Can someone put the new file in the atm/cam/chem/trop_mam/ repo: /glade/work/aherring/grids/uniform-res/ne5np4.pg3/atmsrf/atmsrf_ne5pg3_201105.nc ?

Swapped out the edmf test with ne5pg3_ne5pg3_mg37.

2020-11-05 21:10 UTC, adamrher commented
Can we also put /glade/work/aherring/grids/uniform-res/ne5np4.pg3/grids/ne5pg3_scrip_201105.nc in the atm/cam/coords/ directory for future reference?

2020-11-05 21:17 UTC, cacraigucar commented
@adamrher There are mandatory metadata standards for AMWG files which go into the repository.  Please add the missing information to your files.  The standards are at: https://www.cesm.ucar.edu/working_groups/Atmosphere/required-meta-data-amwgcam-datasets.html.  Let me know when the files are ready, and I will import them into the appropriate locations in the repo.

2020-11-07 00:09 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">/glade/work/aherring/grids/uniform-res/ne5np4.pg3/atmsrf/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
I will update this entry (removing the hardcoded path) once the file has the required metadata added to it and it resides in inputdata.

2020-11-10 05:25 UTC, gold2718 requested changes
Mostly okay -- I do have some change requests.

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +         wtv = wmin + (wmax-wmin) / (real(clubb_mf_nup)) * real(i)
Since the variables are all `r8`, these integers should be explicitly cast that way:
```suggestion
         wlv = wmin + (wmax-wmin) / (real(clubb_mf_nup, r8)) * (real(i-1, r8))
         wtv = wmin + (wmax-wmin) / (real(clubb_mf_nup, r8)) * real(i, r8)
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +           if (qcn.gt.0._r8) zcb(i) = zm(1)
Please use modern notation:
```suggestion
           if (qcn > 0._r8) zcb(i) = zm(1)
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +           if (do_precip .and. upqc(k,i).gt.0._r8) then
Please use modern notation:
```suggestion
           if (do_precip .and. upqc(k,i) > 0._r8) then
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +             if (zcb(i).eq.zcb_unset .and. qcn.gt.0._r8) zcb(i) = zm(k+1)
Please use modern notation:
```suggestion
             if (zcb(i) == zcb_unset .and. qcn > 0._r8) zcb(i) = zm(k+1)
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +       if (qt.gt.qstar) then
Please use modern notation:
```suggestion
       if (qt > qstar) then
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +       do while (puni.gt.explam)
Please use modern notation:
```suggestion
       do while (puni > explam)
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +         wlv = wmin + (wmax-wmin) / (real(clubb_mf_nup)) * (real(i)-1.)
You need a kind:
```suggestion
         wlv = wmin + (wmax-wmin) / (real(clubb_mf_nup)) * (real(i)-1._r8)
```

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +       tc=t-273.16_r8
Please use `h2otrip` from physconst here.

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/edmf_module.F90
> +                   qcmin = 0.00125_r8   ! supersat threshold
I think that these should be parameters.

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +      enddo
Does this section need to be executed if `do_clubb_mf == .false.`? If not, please add the appropriate logic.

2020-11-10 05:25 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +           mf_dry_a_output(i,pverp-k+1)     = mf_dry_a(k)
What happens here if `nz >= pverp`? Is there any check for that?
I think it would require `top_lev == 0` which does not seem likely (maybe a *really* low-top model :)

2020-11-16 19:55 UTC, brian-eaton approved these changes

2020-11-17 23:44 UTC, adamrher commented on doc/ChangeLog
> + - /glade/scratch/aherring/cam6_3_000_FSCAM_bomex_T42_T42_pe36_201007_nlev128_mfoff/run/
I assume just get rid of it, and that the explanation that this does not change answers is enough (since the do_clubb_mf is false by default)

2020-11-18 00:18 UTC, adamrher commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_clubbmf"/>
I wouldn't think we would need to add a separate testlist for what amounts to just adding another parameterization to CAM. @cacraigucar?

2020-11-18 00:26 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Real: Entrainment length scale in meters for individual plumes
done.

2020-11-18 00:26 UTC, adamrher commented on doc/ChangeLog
> +Originator(s): herrington, bacmeister, goldy, cacraig
removed ur name (and julio's since this has really been just me and cheryl)

2020-11-18 00:27 UTC, adamrher commented on src/control/runtime_opts.F90
> +   !use edmf_module,         only: clubb_mf_readnl
removed

2020-11-18 00:27 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +         wlv = wmin + (wmax-wmin) / (real(clubb_mf_nup)) * (real(i)-1.)
added a kind in my branch.

2020-11-18 00:27 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +       tc=t-273.16_r8
using h2otrip now

2020-11-18 00:27 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +                   qcmin = 0.00125_r8   ! supersat threshold
changed to parameters

2020-11-18 00:27 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      enddo
No, these are all unique to clubb_mf. Added conditional.

2020-11-18 00:27 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +           mf_dry_a_output(i,pverp-k+1)     = mf_dry_a(k)
I eliminated the nz and replaced with pverp. They should be the same so it was redundant. Tendencies are subsequently zeroed out above the tropopause in clubb_intr.

2020-11-18 16:52 UTC, cacraigucar commented
@adamrher I don't see your latest changes.  Did you "commit" and "push" them?  

Are you done with the changes you will be making and should I go ahead and make the rest?

2020-11-18 17:02 UTC, adamrher commented
You don't see the "1st attempt at addressing goldys review 5fe837b" just above your comment?

2020-11-18 17:35 UTC, cacraigucar commented
@adamrher I see them now.  I don't know what went wrong on my end - sorry!  Is it my turn now to address the remaining issues?

2020-11-18 17:43 UTC, adamrher commented
I think so cheryl. What comes to mind is steve's ? about incl an extra test list for clubbmf.

I still have to add metadata to the drydep ands scrip file for ne5pg3.

2020-11-18 18:24 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">/glade/work/aherring/grids/uniform-res/ne5np4.pg3/atmsrf/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
I've added the metadata to this drydep_srf_file. If it looks good to you, go ahead and copy to inputdata and change path

2020-11-18 18:27 UTC, adamrher commented
@cacraigucar I've added metadata to the drydep_srf_file and SCRIP file. Could you move the SCRIP file into atm/cam/coords/?

/glade/work/aherring/grids/uniform-res/ne5np4.pg3/grids/ne5pg3_scrip_201105.nc

2020-11-18 22:13 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_clubbmf"/>
@adamrher  Let's remove the aux_clubbmf test category (remove that whole line).  There is no need for a separate test category for it.

2020-11-20 21:03 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="test_cac"/>
I changed the name on this test, so I have a convenient way to test.  I will be removing this before the final commit

2020-11-23 21:50 UTC, cacraigucar commented
@adamrher - The problem with restart and differing answers appears to be related to the random number generator.  When I hardwire the poisson output to 1, I get identical answers.  Without it, even two runs using the same executable does not give reproducible results.  CAM has always had the ability to have reproducible results, so the way you are using the random number generator will need to be changed.  I believe @gold2718 and @brian-eaton have dived into CAM's random number generator in the past.  If one of them can advise on what needs to be done, that would be great.  In the meantime, I will explore what may need to be changed.

2020-11-23 21:54 UTC, gold2718 commented
Could someone point me to the code location of the problematic use of the RNG?
The usual secret is to key off global column numbers as things like chunk and column number are subject to change from run to run.

2020-11-23 21:57 UTC, cacraigucar commented
> Could someone point me to the code location of the problematic use of the RNG?
> The usual secret is to key off global column numbers as things like chunk and column number are subject to change from run to run.

It is at the bottom of the clubb_mf.F90 module.  I believe the seed is coming from the variable "thl" in clubb_intr.F90

2020-11-23 21:58 UTC, adamrher commented
Cheryl, For the same executable, the results should be bit for bit. I could be mistaken, but I've tested this before and I am double checking now. I implemented the RNG after how its done in the radiation code, setting the seed equal to the state.

2020-11-23 22:00 UTC, adamrher commented
The seed is set here:

https://github.com/adamrher/CAM/blob/80c4c0f7f45029382c1394a7d15b9d73be1bea90/src/physics/cam/clubb_mf.F90#L630

I think that its not reproduce-able if the chunks change, as steve indicated. but for the same layout, i don't see why the answers should change.

2020-11-23 22:20 UTC, gold2718 commented
> but for the same layout, i don't see why the answers should change.

For some restart tests, the layout _does_ change between runs. This is to explicitly test the ability of the model to reproduce results regardless of layout. Many, many, many bugs have been found by changing task and thread numbers.

2020-11-23 22:28 UTC, cacraigucar commented
> > but for the same layout, i don't see why the answers should change.
> 
> For some restart tests, the layout _does_ change between runs. This is to explicitly test the ability of the model to reproduce results regardless of layout. Many, many, many bugs have been found by changing task and thread numbers.

But my tests do indicate that the exact same layout and same executable is giving different answers.  I move the cam h0 file to a new name, reissue the ./case.submit and then do a cprnc comparing the old and new cam h0 files.    I would have expected that the files would be identical, but they are not.  Also I can see difference in the second timestep comparing the two atm.log files.

2020-11-23 22:50 UTC, gold2718 commented
At first glance, I do not see anything wrong with the way the random number code is called (i.e., nothing using layout information).
However, I do not believe that random_number is thread safe unless used within OMP directives.
Currently, I do not see anywhere in CAM where random_number is called from a threaded region.
One idea is to create the distribution in `phys_timestep_init`, possibly by stuffing it in a `pbuf` field (the code to do this would still be in clubb_mf.F90). This is a technique used by the prescribed_aero code.

2020-11-23 23:13 UTC, adamrher commented
I'm having trouble reproducing the problem. For two separate runs, one with 36 processors, one with 72 processors, the h0 files are identical.

SUMMARY of cprnc:
 A total number of 128534 fields were compared
          of which      0 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of    722 fields could not be analyzed
 A total number of      0 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files seem to be IDENTICAL

I'm running on cheyenne with the intel compiler. Maybe I should try with the nag compiler on izumi?

2020-11-23 23:16 UTC, gold2718 commented
How many time frames are in the h0 file?

2020-11-23 23:17 UTC, adamrher commented
> How many time frames are in the h0 file?

360

2020-11-23 23:17 UTC, cacraigucar commented
My latest tests (and the ones which indicated different results for identical executables) were using PGI on izumi.  I would expect that FSCAM might be identical because the test I ran with ATM_NCPL =1 was reproducible

> How many time frames are in the h0 file?
10 time steps and it differs on time step 2

2020-11-23 23:24 UTC, gold2718 commented
If my theory is correct, you need to run with multiple threads to see the problem.

2020-11-24 00:01 UTC, adamrher commented
I ran two separate QPC6 runs for 30 time-steps and the i/o is identical. So I haven't reproduced Cheryl's issue, but will try using pgi on izumi.

But with difference processor counts (72pes v. 108pes), the i/o is different,

SUMMARY of cprnc:
 A total number of  10694 fields were compared
          of which   8135 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of     60 fields could not be analyzed
 A total number of      0 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files seem to be DIFFERENT

2020-11-24 03:19 UTC, gold2718 commented
Thread collisions are flighty beasts. Sometimes they occur on only a few machine / compiler combinations and even so, they do not always occur because you can get the same collision twice in a row and you will get the same answer.

2020-11-24 03:40 UTC, adamrher commented
I can't comment on collisions (i'm wearing pads dude) but I can confirm Cheryl's results ... re-running the executable yields different i/o using the pgi compiler.

SUMMARY of cprnc:
 A total number of   3930 fields were compared
          of which   2835 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of     22 fields could not be analyzed
 A total number of      0 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files seem to be DIFFERENT

I will note that running with nag gives identical results.

2020-11-24 05:15 UTC, gold2718 commented
Interesting. Unfortunately for my theory, all of your recent runs seem to be with a single thread (just looking at recent runs in /scratch/cluster/aherring).
Still worth fixing because Cheryl said that by overriding the RNG, results were reproducible.

2020-11-24 16:24 UTC, cacraigucar commented
Unfortunately, I see a difference when I rerun a 48 task single thread case using the PGI compiler on izumi (job ending with "hthoko" if @gold2718 would like to inspect it).   This appears to shoot down the threading being the issue.  The baseline test is failing as well.

2020-11-24 17:15 UTC, adamrher commented
I tried setting the seed using a prognostic variable (u) instead of a prognostic variable (thl) and that did nothing.

I modeled my setting the seed after subroutine generate_stochastic_clouds in
/home/aherring/src/cam6_3_000.clubbmf/src/physics/rrtmg/aer_src/mcica_subcol_gen_lw.f90

But there, they don't call the intrinsic fortran routine directly, but rather through these utils:

   use shr_RandNum_mod, only: ShrIntrinsicRandGen, ShrKissRandGen, &
                              ShrF95MtRandGen, ShrDsfmtRandGen

Maybe I should experiment with using ShrIntrinsicRandGen, which is the "! Fortran 90 "random_number" intrinsic"?

2020-11-24 17:43 UTC, gold2718 commented
Is there any reason you cannot do this at timestep init time?

2020-11-24 18:01 UTC, adamrher commented
> Is there any reason you cannot do this at timestep init time?

You're asking if we can just set the seed at every grid point only one time per run, at initialization?

2020-11-24 18:02 UTC, mikaelwitte commented
> > Is there any reason you cannot do this at timestep init time?
> 
> You're asking if we can just set the seed at every grid point only one time per run, at initialization?

This should be fine. It seems like a very high bar to require that the seed be reset every timestep.

2020-11-24 18:07 UTC, gold2718 commented
> >     Is there any reason you cannot do this at timestep init time?
> 
> You're asking if we can just set the seed at every grid point only one time per run, at initialization?

No, once per timestep.

However, I just looked through the KISS code (all the way down to the C99 kernel) and I think that this version should be thread safe because it keeps the seed value all the way down. The Fortran intrinsic stores a single seed for the entire task.

I think you should be able to replace your use of the Fortran intrinsic with the shr_RandNum_mod version without moving where you do the work. The major difference is that you call the random number generator once to grab an array of random numbers, then apply them from that array.

2020-11-24 18:12 UTC, gold2718 commented
> This should be fine. It seems like a very high bar to require that the seed be reset every timestep.

@mikaelwitte, the issue is not setting the seed, it is how that seed is stored and accessed during the timestep. Accessing it from a threaded region (apparently even with only a single thread) is not guaranteed to be reproducible in Fortran.

I'm leaning towards just replacing the current use of the Fortran intrinsic with the thread-safe share version which @adamrher identified.

2020-11-24 18:17 UTC, adamrher commented
I've had problems plugging the kiss uniform distribution into my poisson algorithm. See attached PDF of the resulting poisson dist, with kiss in red and instrinsic in blue,

[temp_dist_intrincsic-v-kiss.pdf](https://github.com/ESCOMP/CAM/files/5591890/temp_dist_intrincsic-v-kiss.pdf)

(fun fact, kiss stands for keep it simple stupid).

Steve, do you think ShrIntrinsicRandGen is thread safe?

2020-11-24 18:28 UTC, adamrher commented
update. So i did a run where I by-passed my uniform->poisson conversion, and just used the uniform from the intrinsic routine:

       call random_number(tmpuni)
       kout = int(10._r8*tmpuni) + 1

And ran the pgi compiled executable twice and the results were identical. So the problem that @cacraigucar discovered is originating in my poisson alg. @mikaelwitte do you have convenient alternative I can quickly plug in? Can you also summarize any previous problem you've had with my poisson alg (i think u mentioned you had).

The threadsafe issue still might be a problem but it has not been properly diagnosed yet. And just to be clear, all new code mods to CAM need to be thread safe? I ask b/c I know with cam-se we only run with nthrds=1 b/c =2 slows down performance on cheyenne. but obv this PR is independent of dcyore, so i can imagine that we do want thread safety.

2020-11-24 18:37 UTC, gold2718 commented
> And just to be clear, all new code mods to CAM need to be thread safe? 

Nothing new here. The issue is that CAM physics tendency code (the code called from tphysac or tphysbc) is inside a threaded region of the code so it has always had to be thread safe. The timestep init code is not called from a threaded region.

Dycores each have their own rules regarding threading since they are in control of which regions are threaded.

2020-11-24 18:39 UTC, mikaelwitte commented
@adamrher my previous issue with changing clubb_mf_nup was resolved when you finished all the namelist stuff (I think). I hadn't encountered the same problems with output POI<=0 in CESM as in E3SM so I won't get into that.

An F90 Poisson generator from Numerical Recipes that I got from Kay Suselj is attached. This is what I'm using in E3SM, but I have not done anything on the software engineering side to ensure BFB reproducibility, thread safe implementation, etc. Hope it helps.
[poisson_fromkay.F90.txt](https://github.com/ESCOMP/CAM/files/5591990/poisson_fromkay.F90.txt)

2020-11-24 18:41 UTC, adamrher commented
@gold2718 OK, maybe with my a new poisson alg the kiss algorithm will play well with it.

@mikaelwitte thx. Ill give it a whirl.

2020-11-24 18:43 UTC, gold2718 commented
> Steve, do you think ShrIntrinsicRandGen is thread safe?

Probably not because while it stores its seed, the three Fortran intrinsic calls that do this are not protected. There is no inexpensive way to do this in Fortran because we do not have access to the intrinsic seed once it is set so we cannot use the `ATOMIC` directive.

2020-11-24 18:44 UTC, gold2718 commented
> OK, maybe with a new poisson alg the kiss algorithm will play well with it.

Did you graph KISS to see if it was flat? I had no idea Poisson had such an unusual tail :)

2020-11-24 18:51 UTC, brian-eaton commented
> I ask b/c I know with cam-se we only run with nthrds=1 b/c =2 slows down performance on cheyenne. but obv this PR is independent of dcyore, so i can imagine that we do want thread safety.

The SE code is thread safe as far as I know.  John Dennis did that work and there are several namelist options to control exactly how the threads are used.  But on cheyenne the performance with threads stinks which is why we don't run with them on that platform.

2020-11-24 20:44 UTC, mikaelwitte commented
@adamrher the JPL group has also done some experimentation with different distributions (Poisson, uniform, constant; see sections 3b-c of attached paper). We are going to run further sensitivity tests in the JPL SCM to see whether we can get away with ditching Poisson, since it's causing problems in other GCM implementations as well. I'll comment here with any relevant results.
[Suselj et al 2019 JAS.pdf](https://github.com/ESCOMP/CAM/files/5592611/Suselj.et.al.2019.JAS.pdf)

2020-11-24 21:07 UTC, cacraigucar commented
@mikaelwitte and @adamrher  Since the problems with Poisson sound like they might take a bit of time to sort out, we have two choices.  We have the potential for being able to make a commit early next week, but additional slots will continue to open up if we miss this one.

1. Commit a version of CLUBB_MF which bypasses Poisson and make a bug fix commit at a later date.   This has the benefit of getting most of the code committed and onto the CAM trunk, but also has the drawback of not being fully usable.
2. Wait for the dust to settle on the distribution method, implement the changes and make the commit at a future date.  This would be a good way to go if you think it will happen in the next month or so as it is only one commit and it will work as soon as it is in the repo.

I am looking for suggestions from you both on this.

2020-11-24 21:18 UTC, adamrher commented
@mikaelwitte While I haven't looked carefully at the paper you reference, my fixed entrainment rate runs give unrealistic results when coupled to Key's microphysics, in particular the GATE case. So for that reason I'm opposed to removing the RNG.

@cacraigucar I would like to spend the next day or two trying to fix the problem with the poisson alg. Can we punt to make a determination on the path forward until then? I think we've made some headway on this issue.

2020-11-24 21:28 UTC, cacraigucar commented
> @mikaelwitte While I haven't looked carefully at the paper you reference, my fixed entrainment rate runs give unrealistic results when coupled to Kay's microphysics, in particular the GATE case. So for that reason I'm opposed to removing the RNG. [edit - I did a pretty exhaustive test of sensitivity to various entrainment rates, which I can provide to you offline]
> 
> @cacraigucar I would like to spend the next day or two trying to fix the problem with the poisson alg. Can we punt to make a determination on the path forward until then? I think we've made some headway on this issue.

@adamrher - Yes, certainly.  I was suggesting that early next week we'll need to make the decision on whether to give up our slot to another tag or not.  (There is actually a small code change going in today or tomorrow because I knew we weren't going to be ready).  The next tags will most likely be major ones and could potentially delay this tag again.  I'll check with you early next week.  BTW, if the weak scaling PR comes in in the meantime, that will bump us based on the decisions at last week's planning meeting.  In that case we will be postponed.

2020-11-25 03:06 UTC, adamrher commented
@gold2718 my prior implementation of kiss was probably wrong. It looks like it needs 4 seeds. So I set the seed to be an array of size(1,4), which I get from the lowest 4 levels of the zonal wind. See line 612 of:

/scratch/cluster/aherring/cam6_3_000.clubbmf_QPC6_ne5pg3_ne5pg3_mg37_96pe_201124_nag-kiss-4seed/SourceMods/src.cam/clubb_mf.F90

(note the arrays are flipped due to the clubb convention). When i run the nag executable 2X I get different answers so I feel like I'm not setting the seed in kiss properly.

2020-11-25 04:12 UTC, gold2718 commented
I cannot see what you might be doing wrong. Does it still work with `debug = .true.`?

2020-11-25 04:47 UTC, cacraigucar commented
> I cannot see what you might be doing wrong. Does it still work with `debug = .true.`?

Another experiment that I was going to try, but didn't have time to try, was to set the seed to a constant and make sure that there wasn't a different issue going on.  Since I am not familiar with the random number generator routines, I was wondering if there might be race condition going on with them.  Since I could get different results with anything running more than one task, threaded or unthreaded, it has the feel of a race condition.

2020-11-25 17:53 UTC, adamrher commented
OK, after looking over the code clear eyed this morning, I was able to make some progress. I am now able to run the pgi executable and get identical results (hooray!). The successful configuration uses the kiss RNG *but* I also fixed an apparent bug (two loops weren't spanning the entire array that, subsequently, is fed into the RNG ... of which does span the entire array). I'm figuring out which (or both) of these changes are responsible for the pgi reproduce-ability.

I think at this point my to do list is: (1) reproduce-ability when changing core counts (2) thread protection. For the latter, my understanding from brian's post is that the cam-se QPCX test can be used to check thread protection.

2020-11-26 21:52 UTC, adamrher commented
I'm going to summarize my results so far while its fresh on my mind. The pgi compiler reproducibility issue was related to the loop bug, and so not (directly) related to the poisson alg or RNG.

I've verified that the code is reproduce-able using different counts. I ran with the pgi compiler on izumi, and I used the intrinsic RNG.

w.r.t thread safety. I first ran a f19 QPC6 out of the box with nthrds=1 & 2, to confirm the is identical i/o. I then turned on clubbmf, but in debug mode where I don't invoke the RNG. The i/o for nthds=1 & 2 is identical. 

Then I tested threading with the intrinsic RNG. The i/o is different,
/scratch/cluster/aherring/cam6_3_000.clubbmf_QPC6_f19_f19_mg17_96pe_201126_pgi-intrinsic-1nthrds
/scratch/cluster/aherring/cam6_3_000.clubbmf_QPC6_f19_f19_mg17_96pe_201126_pgi-intrinsic-2nthrds

Lastly I tested threading with the kiss RNG ... The i/o is identical!
/scratch/cluster/aherring/cam6_3_000.clubbmf_QPC6_f19_f19_mg17_96pe_201126_pgi-kiss-1nthrds
/scratch/cluster/aherring/cam6_3_000.clubbmf_QPC6_f19_f19_mg17_96pe_201126_pgi-kiss-2nthrds

These results are consistent with steve's theory. So I think kiss is the way to go. I had also checked to make sure the pdf's look similar for the different RNGs, and they do,
[temp_dist.pdf](https://github.com/ESCOMP/CAM/files/5605099/temp_dist.pdf)

Note this is a pdf of 10 steps in f19 ... So it's the superposition of a ton of poisson dist's with different mean values.

Is there anything else I should check or should I go ahead and commit the code changes with kiss? 

I'm going to relax and watch football. Happy Thanksgiving!

2020-11-30 16:52 UTC, cacraigucar commented
@adamrher - If you push your changes back to your branch, I can continue with my testing as well (if you are still happy with the current results).  Also, let us know if you believe this is ready for the official CAM trunk, or what your plans are to validate, modify it to get it ready.

2020-11-30 17:56 UTC, adamrher commented
I did some eyeball verification for the BOMEX case and the results look similar to prior commits. So I'm happy with the change to the kiss RNG plus some other bug fixes. @cacraigucar you can proceed with testing. I hope this fixes the issue with the restarts as well as I didn't test this.

2020-11-30 17:59 UTC, cacraigucar commented
@adamrher - I will test the restart (along with a bunch of other things).  I'll also merge in the most recent CAM.  It sounds like if my testing proceeds okay, then we are ready for this to go into the CAM repo?  If so, I'll assign us the next CAM tag.

2020-11-30 18:09 UTC, adamrher commented
`It sounds like if my testing proceeds okay, then we are ready for this to go into the CAM repo?`

yep!

2020-11-30 18:37 UTC, cacraigucar commented
@fvitt and @gold2718 - Could you please complete your final review as this is slotted for the next CAM tag.  The restart test is now passing.

2020-11-30 18:53 UTC, cacraigucar commented
FYI - the merge broke the regression test, due to changes with PUMAS.  Fix will be coming after lunch.

2020-11-30 20:08 UTC, cacraigucar commented
The issue was that I forgot to rerun checkout_externals.  The restart test now runs fine.  @adamrher - The answers do change due to the PUMAS update (and maybe other updates as well).  Please rerun and make sure you are happy with the results.  I will continue with my testing.

2020-11-30 21:16 UTC, adamrher commented
@cacraigucar what source code do I test? I don't see any more commits in my branch.

2020-11-30 21:21 UTC, cacraigucar commented
@adamher - I committed it to ESCOMP/CAM (upstream) instead of your branch!  I'll be backing it out of ESCOMP/CAM and committing it to your branch.  New workflow for me and I blew it!  Look for the commit message shortly (first undoing ESCOMP/CAM commits)

2020-11-30 22:53 UTC, cacraigucar commented
After further investigation, it was concluded that the commit was actually done correctly.  There will be another minor commit coming soon.

2020-11-30 23:08 UTC, adamrher commented
@cacraigucar results of SCAM runs look good to me with the cam6_3_005 merge onto my branch

2020-12-01 19:36 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
@adamher  This file is changing answers for all of our CAM regression tests which use the ne5_pg3_mg37 grid.  Is this expected?  Does this have any implications for current users of the CAM code?

2020-12-01 19:51 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
Yes, it's expected. This dataset is hacky in that as long as ncols of the dataset is >= than the grid you are running, than the model will run. So prior to creating this ne5pg3 dataset, it would just pull the ne5np4 dataset for ne5pg3 runs. Now it will pull this ne5pg3 dataset proper. It doesn't really matter to me whether we use the old or the new dataset, but at the time I forgot about the hacky-ness of this dataset and thought I needed to create it.

Only developers and se's use ne5pg3, so this shouldn't be a big deal to switch over.

2020-12-01 20:17 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
@adamrher If I'm interpreting your comments correctly, it sounds like this new dataset isn't any better or worse than the old dataset - they are both "hacky".  If there is no benefit for using this new data file, I would suggest that there isn't any reason to change answers and use the new one.  Unless I am misreading your comments, I would suggest that we delete this line and continue using the older dataset.

2020-12-01 20:27 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
I agree that its no better than the old file and that we should just delete this line from the PR.

2020-12-01 22:01 UTC, gold2718 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
Why is reading the correct data 'no better' than reading incorrect data? While reading the old dataset does not crash the model, all the data is incorrect. While this may not matter for a baseline test, developers use this resolution for more than just baseline tests.

2020-12-01 22:25 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
Point taken. I suppose it would be the correct file. But ... I'm skeptical this file is used for anything, and should probably be opened as a separate issue. I think it is supposed to be used in one of the aerosol routines, but when Peter and I looked, and checked with @brian-eaton, we came out thinking this file isn't being used. Worryingly, It contains bogus values in one of its only two fields, soil moisture fraction. And I mean ALL the drydep_surf files have these bogus values.

2020-12-01 22:30 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
I assumed that this file change was the reason that 4 of the izumi PGI regression tests had answer changes.  I have a job in right now rerunning those tests without this file modification and confirm if that is the reason for the answer changes or not.  Regardless of the results, I will then need you and Steve to agree on whether the file should be there or not.  The latest commit I made has it removed.

2020-12-02 00:29 UTC, cacraigucar commented on test/system/test_driver.sh
> +    ${CAM_ROOT}/test/system/TGIT.sh
The results are written to the screen only and run for both PGI and NAG izumi runs.  The r8 tests take less than a minute and TGIT is instantaneous.  In the commit that I made an hour or so ago, there are now lines around the runs to help the user to see the results.

2020-12-02 03:31 UTC, gold2718 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
My preference is to leave it in as a marker for what files we need to keep track of. I believe the reason the file is not currently used is because the drydep code could not handle unstructured grids so Brian created a workaround. This will hopefully get addressed and we need to make sure we know what we need to catch up on. 
On the other hand, @cacraigucar, let us know if that is somehow the source of the answer changes.

2020-12-02 03:33 UTC, gold2718 approved these changes
I would like some commented debug code removed but no need to re-review after that.
Note that there are unresolved conversations started by @nusbaume  and @cacraigucar, please check that your concern has been addressed and resolve each conversation (or let us know if there is still an issue).

2020-12-02 16:48 UTC, cacraigucar commented
@gold2718 and @adamrher The added file in namelist_defaults.xml appears to be the reason for the answer change.  By removing it, the baseline tests pass.  Since it was thought this file was not being used, I will run some additional tests to confirm this, but I wanted to post this information as soon as I could (after izumi hiccuped on building this test overnight!)

2020-12-02 16:59 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
OK. Makes sense to keep in the ne5pg3 file as a marker. Hoping we can address this in the near future, as we are generating a new drydep file with each new grid we create ... incl the var-res toolkit for user defined grids.

2020-12-02 17:02 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +           !end if
@mikaelwitte do you think we should uncomment this for this PR? It makes the log files massive, but other than that, I think we agreed earlier it we good to have at least one debug print statement.

2020-12-02 18:29 UTC, gold2718 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
After discussion, we decided to handle this as a separate issue because otherwise, this PR does not change answers and it is important enough to make sure it gets proper attention.

2020-12-02 18:59 UTC, mikaelwitte commented on src/physics/cam/clubb_mf.F90
> +           !end if
I think it's worth leaving it in as a sanity check during plume microphysics development.

2020-12-02 19:58 UTC, cacraigucar approved these changes

2020-12-02 19:59 UTC, cacraigucar commented
@fvitt  Have you completed your review or are you still working on it?

2020-12-02 20:17 UTC, fvitt approved these changes

2020-12-02 20:50 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne5np4"   npg="3">atm/cam/chem/trop_mam/atmsrf_ne5pg3_201105.nc</drydep_srf_file>
Opened issue #284 to allow discussion on how best to handle this file

2020-12-03 22:28 UTC, merged

2020-12-08 18:23 UTC, nusbaume commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
Hey @adamrher just letting you know that we have created an issue and assigned it to you that states the desire to provide the more extensive namelist in a future PR.  No rush on this, however, as it is just to help us keep track of stuff.  Thanks!

2020-12-10 00:50 UTC, adamrher commented on src/physics/cam/edmf_module.F90
> +     logical                              :: debug = .false.
no problem. Many enhancements are in the pipeline, so Ill make sure to include this issue.