Chemistry code changes for 'weak scaling' issues
ESCOMP/CAM pull request #222
Opened 2020-09-18 17:13 UTC by fvitt

This removes this use of phys_grid interfaces in chemistry code that will become obsolete in the near future.  The phys_grid interfaces that will go away are:
 scatter_field_to_chunk
 get_lat_all_p
 get_lon_all_p
 get_lat_p
 get_lon_p

These phys_grid routines will be removed in an effort to allow CAM to scale better to high-resolution grids

This PR also removes chemistry code that is no longer used.

closes #219

2020-09-21 20:33 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +Full pathname of dataset which contains land vegitation information used in modal aerosol deposition.
Typo here (`vegetation`).

2020-09-22 04:13 UTC, nusbaume requested changes
Generally looks fine to me, but I do have some (hopefully minor) requests and questions.

2020-09-22 04:13 UTC, nusbaume commented on src/chemistry/mozart/mo_drydep.F90
> +          call get_rlon_all_p(lchnk, ncol, rlons(:ncol))
Should these two calls be outside the `icol` loop?

2020-09-22 17:36 UTC, gold2718 commented
@fvitt, can you merge this up to cam6_3_000 to remove conflicts and make it easier to compare?

2020-09-22 22:36 UTC, brian-eaton approved these changes

2020-09-23 15:02 UTC, gold2718 approved these changes
Wow, lots of cleanup.
Looks okay o me.

2020-09-23 17:00 UTC, nusbaume approved these changes
Thanks for taking care of my requests!  Everything looks good to me now.

2020-10-01 21:37 UTC, cacraigucar approved these changes

2020-10-01 21:37 UTC, cacraigucar commented on src/chemistry/mozart/mo_drydep.F90
> +    ! put this kludge in for now ...
Is this still a kludge?  What will it take to make it correct?  Does this need an issue opened for it or should the comment be modified?

2020-10-05 17:37 UTC, fvitt commented on src/chemistry/mozart/mo_drydep.F90
> +    ! put this kludge in for now ...
> Is this still a kludge? What will it take to make it correct? Does this need an issue opened for it or should the comment be modified?

Yes this is still a kludge.  There will be a larger effort to refactor how dry deposition implemented in the not too distant future.  Hopefully we will remove these kludges then.  I propose we leave the comment as it is for this merge.

2020-10-07 22:08 UTC, merged