Misc bugs #1: rrtmg_state pointer, SCAM namelist, izumi compiler and TGIT test
ESCOMP/CAM pull request #227
Opened 2020-09-23 21:19 UTC by cacraigucar

Fix rrtmg_state pointer bug, correct SCAM6 namelist inconsistencies and update izumi compilers and TGIT test

Closes #86 
Closes #130 
Closes #146 

Also updates TGIT regression test

2020-09-23 21:35 UTC, fvitt approved these changes

2020-09-23 21:46 UTC, brian-eaton approved these changes

2020-09-23 22:15 UTC, nusbaume approved these changes
Looks good, and thanks for fixing the TGIT error codes!  Just one question regarding a print statement.

2020-09-23 22:19 UTC, cacraigucar commented on src/control/scamMod.F90
> +        print *
Exactly - I saw that too!   I decided that because I am applying the exact changes from cam_development, I would leave it in.  We all missed it the first time around, but not now!

2020-09-23 23:01 UTC, jtruesdal approved these changes

2020-09-24 14:13 UTC, gold2718 requested changes
Mostly documentation issues but I think that stray print statement should go away.

2020-09-24 14:13 UTC, gold2718 commented on doc/ChangeLog
> +    Workaround rrtmg_state pointer issue on cheyenne (issue #86)
The new ChangeLog template says to include the issue text, but that is not what is written here. In fact, this text should be down in the modified section where an explanation of the changes should be.
Speaking of the new ChangeLog template, it would not hurt to update that in this branch for future maintenance tags.

2020-09-24 14:13 UTC, gold2718 commented on doc/ChangeLog
> +    Updates for using latest izumi compilers (issue #146)
This is a PR, not an issue. There should be an issue for these changes.

2020-09-24 14:13 UTC, gold2718 commented on doc/ChangeLog
> +          - Mods for issue #86
A summary of the change would be much better here.

2020-09-24 14:13 UTC, gold2718 commented on doc/ChangeLog
> +          - Mods for issue #130
A summary of the change would be much better here.

2020-09-24 14:13 UTC, gold2718 commented on doc/ChangeLog
> +          - Mods for issue #146
A summary of the change would be much better here.

2020-09-24 14:13 UTC, gold2718 commented on doc/ChangeLog
> +          - Update the TGIT CAM regression test
Why did it need an update? Is there an issue on that?

2020-09-24 14:13 UTC, gold2718 commented on src/control/scamMod.F90
> +        print *
So is it going away? I think it should.

2020-09-24 14:13 UTC, gold2718 commented on test/system/TGIT.sh
> +        rc=5
Note for the future. This seems like a losing game. Perhaps a better approach would be to take a peek in Externals.cfg and maybe also Externals_CAM.cfg and check that those directories, and only those directories contain .git files.
Another check could be to use `manage_externals/checkout_externals --status` to make sure that all the .git files that are supposed to be there are actually working clones in a clean state.

2020-09-24 15:59 UTC, cacraigucar commented on doc/ChangeLog
> +    Workaround rrtmg_state pointer issue on cheyenne (issue #86)
I am only addressing the open issues on the CESM2.1 branch.  Since there was no issue to update the ChangeLog_template, I did not bring it in.   I will make an issue to bring it in with my next tag in this branch.

2020-09-24 16:00 UTC, cacraigucar commented on doc/ChangeLog
> +          - Mods for issue #86
I will copy the issue text here and for the following.

2020-09-24 16:01 UTC, cacraigucar commented on doc/ChangeLog
> +          - Mods for issue #130
I will copy the issue text here

2020-09-24 16:01 UTC, cacraigucar commented on doc/ChangeLog
> +          - Mods for issue #146
I will copy the issue text here

2020-09-24 16:02 UTC, cacraigucar commented on doc/ChangeLog
> +          - Update the TGIT CAM regression test
The test failed when I ran it.  I had looked for an issue that I could reference, but it was buried in issue #82.  I decided to not reference that issue as the thrust of the issue was not this modification.  I also thought since I was fixing the test, I wouldn't bother with making an issue for it.

In hindsight, since issue #82 included a change to the CAM source tree, it should not have been committed without making a tag and an updated ChangeLog.  I was unable to find this change via the ChangeLog, but rather had to use the github log.  I believe all CAM source changes should be documented in the ChangeLog.

2020-09-24 16:03 UTC, cacraigucar commented on test/system/TGIT.sh
> +        rc=5
This is what is currently on cam_development.   If a change is needed then an issue needs to be opened.   I will not be making any changes now, as the test is passing.

2020-09-24 16:07 UTC, cacraigucar commented on src/control/scamMod.F90
> +        print *
I will remove the print statement.  If someone wants it removed from cam_development, then an issue needs to be opened for it.

2020-09-24 18:25 UTC, nusbaume commented on doc/ChangeLog
> +    Updates for using latest izumi compilers (issue #146)
@cacraigucar if you can also change the PR number to the correct issue number in the keyword text above that would be great, as it will help us avoid having to close the issue manually later.  Thanks!

2020-09-24 20:22 UTC, nusbaume commented on test/system/TGIT.sh
> +        rc=5
@gold2718 I might disagree with that assessment.  Right now this test only examines the `.git*` files and directories in the top-level CAM directory, which should be quite limited (right now it is only `.git`, `.gitignore`, and `.github`.  I know there are a few other `.git*` file types out there, but I can't imagine there are too many more that we would add to the repo?  

Also, I can of course modify the script to examine the externals as well, but I wasn't sure if this test should cover them, or if they should be the responsibility of their own repo's tests?  Either way is fine with me.

2020-09-26 00:36 UTC, gold2718 approved these changes
Either the ChangeLog template is wrong or you need to include a GitHub PR URL near the top.

2020-09-26 00:36 UTC, gold2718 commented on doc/ChangeLog
> +Github PR URL:
Where is the URL?

2020-09-26 00:37 UTC, gold2718 commented on doc/ChangeLog
> +
Do you need to include #228 here?

2020-09-26 01:43 UTC, nusbaume approved these changes
Should we create an issue to remind us to remove the erroneous `print` statement from the other branches as well?

2020-09-28 15:36 UTC, cacraigucar commented on doc/ChangeLog
> +Github PR URL:
Sorry - first time filling out the template and didn't register the "URL".  Added

2020-09-28 15:36 UTC, cacraigucar commented on doc/ChangeLog
> +
Forgot to add that documentation.  Added both here and to the PR text.

2020-09-28 15:53 UTC, merged