Fix modal_aero_rename opens too many files, FCHIST test failure, CAM_diagnostics memory leak, update config_pes.xml
ESCOMP/CAM pull request #234
Opened 2020-10-01 20:04 UTC by cacraigucar

Misc bug fixes 2 for CESM2_1 branch

Closes #131 
Closes #214 
Closes #185 
Closes #126

2020-10-01 20:28 UTC, fvitt commented on bld/build-namelist
> +                  rad_diag_10 srf_emis_specifier mode_defs);
I don't believe csw_specifier (for ocean exchange of chemicals) is in cesm2.1

2020-10-01 20:42 UTC, nusbaume approved these changes

2020-10-01 21:36 UTC, brian-eaton approved these changes

2020-10-05 18:40 UTC, gold2718 requested changes
One minor change.

2020-10-05 18:40 UTC, gold2718 commented on bld/build-namelist
> +                  rad_diag_10 srf_emis_specifier mode_defs);
I agree, please remove this item.

2020-10-05 22:11 UTC, gold2718 approved these changes

2020-10-05 22:24 UTC, fvitt approved these changes

2020-10-06 19:23 UTC, merged