Replace serial reads with infld calls.
ESCOMP/CAM pull request #241
Opened 2020-10-06 06:33 UTC by patcal

This is an incremental revision to the nudging.F90 module which replaces serial reads with infld() calls so that PIO is used to read values on known model grids from an open netcdf file. This update does not address the need for in-line horizontal/vertical interpolations.

2020-10-06 20:51 UTC, brian-eaton commented on src/physics/cam/nudging.F90
> +   call pio_seterrorhandling(fileID,PIO_INTERNAL_ERROR)
Why are the error handling calls back to back?  Internal error is the default, and normally you'd change that to broadcast error while you do checks that may fail, and later switch back to the default.  This code doesn't seem to be doing anything.

2020-10-06 21:14 UTC, patcal commented on src/physics/cam/nudging.F90
> +   call pio_seterrorhandling(fileID,PIO_INTERNAL_ERROR)
I used the code in metdata.F90 as a guide for my modifications. There were originally a couple of pio_inq_var() calls between them in the section of code I was referencing. The pio_inq calls were not relevant for my usage, but because I am not familiar with the PIO error handling functionality, I thought it best to include both of the pio_seterrorhandling() calls. Since they do nothing, they can certainly be removed.

2020-10-06 21:33 UTC, gold2718 commented
Murphy ensures that whenever you select some code as a guide, you will select the worst possible example :-)
Also, the interface has changed so the best approach is to include these at the beginning of your routine:
```
   integer err_handling
...
       call pio_seterrorhandling(File, PIO_BCAST_ERROR, oldmethod=err_handling)
```
and this at the end of your routine.
```
    ! Back to old error handling
    call pio_seterrorhandling(File, err_handling)
```
This will reset the error handling back to whatever it was which is important if your routine is called from a region that has already changed the default PIO error handling method.

2020-10-07 22:36 UTC, nusbaume requested changes
Mostly looks good to me, beyond the `seterrorhandling` issue found previously.  However, I do have a few concerns which I would like to see addressed, if possible.  Thanks!

2020-10-07 22:36 UTC, nusbaume commented on src/physics/cam/nudging.F90
> +   call infld('U',fileID,dim1name,'lev',dim2name,     &
It looks like there are no checks here for whether or not these variables are actually present on the file.  I believe you need to add something like this after the `infld` call:

```
if (VARflag) then 
   Nobs_U(:,:,begchunk:endchunk,Nudge_ObsInd(1)) = Tmp3D(:,:,begchunk:endchunk)
else
   call endrun('Variable "U" is missing from '//trim(anal_file))
end if
```
Something similar should be added to the rest of the `infld` calls as well (I think).

2020-11-09 20:09 UTC, gold2718 requested changes
Mostly supporting previous change requests (just added a suggestion).

2020-11-09 20:09 UTC, gold2718 commented on src/physics/cam/nudging.F90
> +!   if(masterproc) write(iulog,*)'PIO: DIM1NAME=',dim1name,' DIM2NAME=',dim2name
Another technique is to define a `debug` private logical symbol at module scope which you can set to `.true.` when you want these messages.
```suggestion
   if(masterproc .and. debug) then
      write(iulog,*)'PIO: DIM1NAME=',dim1name,' DIM2NAME=',dim2name
   end if
```

2021-01-05 20:11 UTC, fvitt commented
What issue does this PR fix?  Does this address scalability issues?

2021-01-05 20:18 UTC, fvitt commented on src/physics/cam/nudging.F90
>     call mpibcast(Nudge_ObsInd      , Nudge_NumObs, mpiint, 0, mpicom)
Should mpi_bcast (without ifdef SPMD) be used rather than mpibcast?

2021-01-05 20:31 UTC, gold2718 commented
> What issue does this PR fix? Does this address scalability issues?

#237, thanks for noticing, I updated the description.

2021-01-05 20:43 UTC, fvitt commented
Are we expecting this regression test to be restored.   I am hoping someone checks that it is bit-for-bit compared to cam6_3_006.  

FAIL ERP_Ln9.ne30_ne30_mg17.FCnudged.cheyenne_intel.cam-outfrq9s RUN time=39
Nudging code is using global interfaces not supported for weak scaling.
This error should be fixed with PR #241

2021-01-05 20:48 UTC, gold2718 commented
> Are we expecting this regression test to be restored

Yes, I will make sure of that.

2021-01-05 22:06 UTC, nusbaume approved these changes
Looks good to me!  Just one typo in all the new `endrun` calls.

2021-01-07 04:07 UTC, gold2718 commented
From around line 772:

> `       call endrun('NUDGING IS CURRENTLY ONLY CONFIGURED FOR CAM-SE, FV, or EUL')`

Is this still true? Should it work with MPAS and/or FV3?

2021-01-07 15:38 UTC, patcal commented
The module originally needed different interfaces to read in  the data for 
each dycore. FV3 and MPAS are new so there is no interface set up for them, 
but if you notice, with the change to infield calls all of the nudging_update_analyses_*()
subroutines are now identical. So I think that adding dycore_is() cases for the 2 
new dycores to the if-elseif block and hang them call nudging_update_analyses_se() 
will allow for FV3 and MPAS.  I left the degeneracy for the time being in case any
dycore-dependent differences showed up during testing and needed to be added 
back in. An alternative would be to remove the if-block and the redundant routines.

2021-01-07 20:54 UTC, nusbaume approved these changes

2021-01-10 22:28 UTC, gold2718 commented
The changes from this PR were merged to cam_development as part of cam6_3_008 (#310).

2021-01-10 22:28 UTC, closed without merging