Add MPAS-A dycore
ESCOMP/CAM pull request #246
Opened 2020-10-09 21:42 UTC by brian-eaton

Fixes #220 Add MPAS-A dycore

2020-10-09 22:31 UTC, cacraigucar commented on Externals.cfg
> +repo_url = https://github.com/brian-eaton/cime
A quick comment - should issue a PR to cime to get whatever mods are made in this branch put into the main cime repo

2020-10-09 22:37 UTC, brian-eaton commented on Externals.cfg
> +repo_url = https://github.com/brian-eaton/cime
The commit to cime has already been done by Chris.  Not sure whether there's a tag yet, but I told him there was no particular rush for one.

2020-10-09 22:37 UTC, fischer-ncar commented on Externals.cfg
> +repo_url = https://github.com/brian-eaton/cime
I believe that the changes are already in cime master.  I would just need to make a cime tag.

2020-10-12 20:07 UTC, gold2718 commented on Externals_CAM.cfg
> +required = True
These need to be re-homed to MPAS-Dev/MPAS-Model, what is the ETA on that?

2020-10-12 20:22 UTC, brian-eaton commented on Externals_CAM.cfg
> +required = True
I have made the request to Michael that the CAM mods in MPAS be merged to v7 (from the current v6), and that we have a "standard" repo location.  I've also asked him to try and get mods that allow MPAS to be built with GNU/debug into the main development code.  This request has been outstanding for a month now.  I have no ETA.  My feeling is that we shouldn't let that hold up this commit since it's an orthogonal issue to review of the CAM interfaces.

2020-10-13 22:24 UTC, cacraigucar commented
@MiCurry here is the PR for the MPAS mods which will be going into CAM.  You will see all the discussions which occur as we perform our reviews.  You can also review the code mods as much or as little as you want as we are not making you an official reviewer.

2020-10-14 21:31 UTC, mgduda commented on Externals_CAM.cfg
> +required = True
The code should compile and run with GNU/debug. Do you mean NAG?

2020-10-14 21:33 UTC, brian-eaton commented on Externals_CAM.cfg
> +required = True
Yes.  NAG/debug.

2020-10-15 15:00 UTC, fvitt reviewed
This is only the begging of my review.

2020-10-15 16:44 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +<entry id="mpas_time_integration" type="char*512" category="mpas" group="nhyd_model" valid_values="">
I agree that it seems like a bit of overkill.  But the declaration of that variable in cam_mpas_namelist_read is character(len=StrKIND), and StrKIND is set to 512 in mpas_kind_types.F which is part of the mpas external code.  That variable is then used as an input to mpas_pool_add_config which is how the value is stored in an internal mpas data structure.  Perhaps it could be shorter.  @mgduda?

2020-10-15 17:06 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +Time integration scheme
I personally feel that the 'mpas_' prefix is sufficient.  Could others please weigh in on this.

The thing to note is that these definitions are auto-generated making use of the MPAS Registry.xml file.  So the descriptions are identical to what's there.  The python script which is responsible for this is in dynamics/mpas/scripts/build_cam_namelists.py.

2020-10-15 17:29 UTC, brian-eaton commented on src/control/cam_history_support.F90
> +
This is used in the mpas dyn_readnl routine (in dyn_comp.F90).  The reason the function is here is because it's similar to two other routines found in this module, date2yyyymmdd and sec2hms.  All three of these functions are used in dyn_readnl.

I agree it makes more sense for these functions to be in a string utility module.  I will move all 3 routines to src/utils/string_utils.F90.

2020-10-15 18:08 UTC, MiCurry commented on doc/ChangeLog
> +    of atmosphere rather than the top to botton order used by CAM.
'botton` should be `bottom` here.

2020-10-15 18:27 UTC, brian-eaton commented on doc/ChangeLog
> +    of atmosphere rather than the top to botton order used by CAM.
Fixed.

2020-10-15 20:07 UTC, brian-eaton commented on src/control/cam_history_support.F90
> +
When moving this function to string_utils I realized that the code is not specific to 'number of days'.  The integer being converted to a string could represent anything.  So I renamed the function to 'int2str'.

2020-10-15 20:34 UTC, fvitt reviewed
I did not notice any new regression tests for MPAS.  Did I just overlook them?

2020-10-15 20:34 UTC, fvitt commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                                                    +  edgeNormalVectors(3,iEdge) * north(3,cell2))
Does the 0.5 constant need a kind specifier (0.5_RKIND)?

2020-10-15 20:34 UTC, fvitt commented on src/dynamics/mpas/dyn_comp.F90
> +   real(r8), parameter :: t0b = 250.0      ! Temperature [K]
_r8 ?

2020-10-15 20:34 UTC, fvitt commented on src/dynamics/mpas/dyn_comp.F90
> +   use shr_kind_mod, only : shr_kind_r8
Don't we already have r8=>shr_kind_r8 at the module level?

2020-10-15 20:34 UTC, fvitt commented on src/dynamics/mpas/dyn_comp.F90
> +      open(unit=unitNumber, file=trim(namelistFilename), status='old', form='formatted')
Should we use open( newunit=unitn ..., rather than getunit()?

2020-10-15 21:30 UTC, nusbaume requested changes
My first set of code questions and requests (as I still need to go through all of the `src/dynamics` code additions).  Hopefully they are all easy fixes!

2020-10-15 21:30 UTC, nusbaume commented on src/utils/time_manager.F90
> +   call chkrc(rc, sub//': error return from ESMF_ClockGet')
Can't you get both `start_time` and `stop_time` from the same `ESMF_ClockGet` call?

2020-10-15 22:01 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                                                    +  edgeNormalVectors(3,iEdge) * north(3,cell2))
Fixed.

2020-10-15 22:12 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   real(r8), parameter :: t0b = 250.0      ! Temperature [K]
Fixed.

2020-10-15 22:21 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   use shr_kind_mod, only : shr_kind_r8
This function is using shr_kind_r8 in it's declarations.  I think this is OK as is.

2020-10-15 22:51 UTC, cacraigucar reviewed
My first installment

2020-10-15 22:51 UTC, cacraigucar commented on doc/ChangeLog
> +    utility to do this.
How would a user find this utility if they want it?  (name, website, etc?)

2020-10-15 22:51 UTC, cacraigucar commented on doc/ChangeLog
> +    additionally contain a complete atmospheric state.
How would a user find this utility as well?

2020-10-15 22:51 UTC, cacraigucar commented on doc/ChangeLog
> +    grid.  There is an MPAS utility used to generate the partition files.
Again, a name/location for this utility as well?

2020-10-15 22:51 UTC, cacraigucar commented on src/dynamics/mpas/Makefile
> +#
This feels fragile to me -- having dependencies spelled out in a Makefile.  The rest of CAM depends on the dependencies being determined on-the-fly.  Will future developers remember to update this file when they add a new use statement or a new file?

2020-10-16 19:27 UTC, brian-eaton commented
We need a bigger discussion about how the MPAS namelist has been implemented.  A lot of the comments so far concern namelist issues that should be easy to fix.  But they're not and the reason is that all the code for handling the mpas namelist has been auto-generated. The reason for this was to have consistency with the information in the MPAS Registry.xml file.  That means that many of the suggested changes would need to be made there, but that file is part of the MPAS external code, so it's not a matter of just making changes in files that are part of CAM.

When I started looking into modifying the script that generates all the namelist code the first thing I did was to run it and check it's output against what's currently in CAM.  I found that there are already substantial differences, some which are easy to fix, and some which are not. A good example is related to Jesse's comment on mpas_block_decomp_file_prefix.  That variable needs to be an absolute pathname and build-namelist creates that pathname by prepending the inputdata root directory to the relative pathnames found in the namelist defaults file.  But it only knows to do that if the definition contains the attribute input_pathname="abs".  Not only is that attribute missing from the auto-generated namelist definitions, but it has been compensated for by modifying the build-namelist code to do the right thing, and this modified code is not what the build_cam_namelists.py script generates.  It's also the case that what the namelist_defaults_cam.xml file contains for mpas_block_decomp_file_prefix is not what was auto-generated.  That's because we've already modified this code, utilizing CAM's flexibility to have defaults that depend on attributes, to specify a bunch of default partition file prefixes which depend on the horizontal grid.

The comments requesting clarifications to the definitions also point out a problem with generating those definitions from the mpas registry.  Beside the issue of having to make the changes in external MPAS code, there is the fact that CAM is sometimes using these variables in a slightly different way from MPAS standalone.  Back to the example of mpas_block_decomp_file_prefix, in MPAS standalone that is a prefix, not an absolute pathname.  So changing the definition to make it more clear for CAM users would make it wrong for MPAS users.

2020-10-16 19:30 UTC, brian-eaton commented
Oooops.  Hit the comment button before I was finished.  One more thing.

I've come to the conclusion that we will be better off managing the mpas namelist in the same way as CAM's other namelists are managed, i.e., by directly editing namelist_definition.xml, namelist_defaults_cam.xml, build-namelist, and the code in dyn_comp.F90.  Comments?

2020-10-16 20:19 UTC, cacraigucar commented
> Oooops. Hit the comment button before I was finished. One more thing.
> 
> I've come to the conclusion that we will be better off managing the mpas namelist in the same way as CAM's other namelists are managed, i.e., by directly editing namelist_definition.xml, namelist_defaults_cam.xml, build-namelist, and the code in dyn_comp.F90. Comments?

A question back to you -- How stable have the MPAS namelist definitions been?  i.e.  with each MPAS update, how much work do you envision maintaining the namelist if they are done by hand?

2020-10-16 21:28 UTC, brian-eaton commented
We've been working with an old version, v6.1, since the start of this project.  The plan is to update to v7 soon so we'll see how much change that entails.  There are only 44 variables currently, so this would not have been a big job even if we took a more CAM like approach from the start.

2020-10-16 22:06 UTC, gold2718 commented
I vote for manual maintenance, especially because we need to carefully document how we use the variables (which as you mentioned, is not exactly the same as in MPAS).

2020-10-16 22:22 UTC, brian-eaton commented on doc/ChangeLog
> +    constituents), cell edges (used the the normal velocity component), and
Fixed.

2020-10-16 22:22 UTC, brian-eaton commented on doc/ChangeLog
> +    which is accessed via pointers in the dynamics import/export objecets,
Fixed.

2020-10-16 22:28 UTC, brian-eaton commented on src/dynamics/mpas/Makefile
> +UTIL_OBJS = \
How about when the next UTIL_OBJS is added?  Current code seems like a reasonable general approach.

2020-10-16 22:30 UTC, brian-eaton commented on src/dynamics/mpas/Makefile
> +dycore: $(DYN_OBJS) $(DIGNOSTICS) $(DIAG_OBJS) $(INTERFACE_OBJS)
Fixed.

2020-10-16 22:43 UTC, brian-eaton commented on src/utils/time_manager.F90
> +   call chkrc(rc, sub//': error return from ESMF_ClockGet')
Suggestion adopted.

2020-10-16 22:44 UTC, cacraigucar commented
> I vote for manual maintenance, especially because we need to carefully document how we use the variables (which as you mentioned, is not exactly the same as in MPAS).

I add a second vote for manual maintenance for the MPAS namelists in CAM.

2020-10-16 22:45 UTC, brian-eaton commented on doc/ChangeLog
> +    utility to do this.
We are developing the workflow for dealing with these new tools and datasets.  There is no standard place for them yet.  That won't be part of this PR.

2020-10-16 22:48 UTC, brian-eaton commented on doc/ChangeLog
> +    additionally contain a complete atmospheric state.
The current MPAS code to generate grid files doesn't work with our topo files.  This is in development.  To date we've only run simple models with no topography.

2020-10-16 22:48 UTC, brian-eaton commented on doc/ChangeLog
> +    grid.  There is an MPAS utility used to generate the partition files.
This code does exist, but isn't yet in a standard place.  Workflow details not part of this PR.

2020-10-16 22:53 UTC, brian-eaton commented on src/dynamics/mpas/Makefile
> +#
This is standard Makefile practice.  Both the other libraries that may be built during the CAM build, i.e., COSP and FV3, have dependencies like this in their Makefiles.

2020-10-19 18:20 UTC, MiCurry commented on doc/ChangeLog
> +    grid.  There is an MPAS utility used to generate the partition files.
I had the same question as well. Is the referenced utility the [gpmetis](http://glaros.dtc.umn.edu/gkhome/metis/metis/overview) command for creating paritionings of the mesh (e.g., `garph.info.part.32`) or the code for creating the mesh connectivity file for a mesh (e.g. `graph.info`)?

2020-10-20 17:46 UTC, nusbaume commented on src/dynamics/mpas/Makefile
> +UTIL_OBJS = \
Fair point, especially if additional utilities will be used in the future.

2020-10-20 17:57 UTC, cacraigucar commented on doc/ChangeLog
> +    utility to do this.
Could you please put the name of the utility in here?

2020-10-20 17:58 UTC, cacraigucar commented on doc/ChangeLog
> +    additionally contain a complete atmospheric state.
Could you please put the name of the utility here?

2020-10-20 17:58 UTC, cacraigucar commented on doc/ChangeLog
> +    grid.  There is an MPAS utility used to generate the partition files.
Could you please put the name of the utility here?

2020-10-20 18:02 UTC, cacraigucar commented on src/dynamics/mpas/Makefile
> +#
I made the same comment in FV3 when it was coming in, but due to time constraints let it slide.  This may be the way we bring in external libraries, but I wanted to discuss this.  Are the makefiles maintained in the libraries themselves (which would be okay) or are they maintained on the CAM side by CAM developers (error prone)?

2020-10-20 19:12 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +Time integration scheme
I have redone all the definitions and made MPAS dycore explicit in each one.

2020-10-20 19:14 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   use shr_kind_mod, only : shr_kind_r8
I have replaced the use of shr_kind_r8 by the module variable r8 so the code is more CAM-like.

2020-10-20 21:19 UTC, cacraigucar reviewed
My second review installment

2020-10-20 21:19 UTC, cacraigucar commented on src/utils/string_utils.F90
> +   end if
Are these unnecessary checks?  Since we have already checked that seconds < 0 and > 86400, then the hours/minutes/secs will always be correct, once they have been verified once.    This function might be great for an offline unit test, so production code doesn't need to test for a condition we know will never be reached.

2020-10-20 22:44 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +      open(unit=unitNumber, file=trim(namelistFilename), status='old', form='formatted')
I've done this along with further refactoring in cam_mpas_namelist_read to make it more readable.  That includes not checking mpi bcast status after every call following Steve's previous argument that doing so is not really useful.

2020-10-20 22:45 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +Prefix of graph decomposition file, to be suffixed with the MPI task count
Done.

2020-10-20 23:01 UTC, brian-eaton commented on bld/build-namelist
> +    }
I have fixed this by putting the actual file needed for the run into the cam.input_data_lists file.  This wasn't being done previously because the auto-generated definition was missing the attribute input_pathname.  Once I fixed that the prefix was added to cam.input_data_lists, but the script that checks for input datasets was failing because the prefix needs the number of tasks to be appended before it corresponds with an actual filename.  I made that adjustment in check_input_files routine.  Now the actual file that is needed by the run is checked for.

2020-10-20 23:02 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +When config\_split\_dynamics\_transport = T, the number of RK steps per transport step
Fixed.

2020-10-20 23:04 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +Height MSL to begin w-damping profile
I assume the same as you, that this should be 'Height above MSL ...'.  Change made.

2020-10-21 18:15 UTC, brian-eaton commented on doc/ChangeLog
> +    utility to do this.
Done.

2020-10-21 18:21 UTC, brian-eaton commented on doc/ChangeLog
> +    grid.  There is an MPAS utility used to generate the partition files.
Done.

2020-10-21 19:01 UTC, brian-eaton commented on src/dynamics/tests/initial_conditions/ic_us_standard_atm.F90
> +      if (present(PHIS_IN)) then
If the requested output requires information about the vertical coordinate, that information comes from PHIS_IN if the dycore uses a hybrid sigma pressure coordinate, or from zint if the dycore uses a height coordinate.  So these args should never both be specified.  I've added a check for this at the top of the subroutine.

2020-10-21 19:03 UTC, brian-eaton commented on src/dynamics/tests/initial_conditions/ic_us_standard_atm.F90
> +            end if
This code is inside a conditional that ensures T is present.

2020-10-21 19:05 UTC, brian-eaton commented on src/dynamics/tests/initial_conditions/ic_us_standard_atm.F90
> +            end if
This code is inside a conditional that ensures PS is present.

2020-10-21 19:14 UTC, brian-eaton commented on src/dynamics/tests/initial_conditions/ic_us_standard_atm.F90
> +      if (present(PHIS_IN)) then
I added this check to the top of the subroutine.

2020-10-21 19:15 UTC, brian-eaton commented on src/dynamics/tests/initial_conditions/ic_us_standard_atm.F90
> +            end if
This code is inside a conditional that ensures PS is present.

2020-10-21 20:58 UTC, brian-eaton commented on src/utils/cam_map_utils.F90
> +        ndest = size(dest_in)
The original code didn't check whether d and dest_in where the same size.  The mod was to address an error I encountered when the size of dest_in was smaller than d which is dimensioned to max_dests which is a parameter set to 2.  I ran into the problem when I was trying to get the mpas grid objects defined correctly.  I don't recall the details of this unpleasant debugging experience.  Since this code was written by @gold2718 I'm happy to let him make the call on whether a check should be included.  If there were need for a check it would be that ndest needs to be <= max_dests.

2020-10-22 17:00 UTC, jtruesdal commented on bld/build-namelist
> +# MPAS-Atmosphere dycore
https://github.com/ESCOMP/CAM/blob/70ca71281e12d2e34e2735a58532b3e784fbd1c1/bld/build-namelist#L592-L598

mpas needs to be added to the list to create a default for a dry deposition file.  I've  added a few mpas deposition files (120 and 480) to inputdata/atm/cam/chem/trop_mam. The defaults need to be added to namelist_defaults_cam.xml as well.

2020-10-22 17:28 UTC, jtruesdal commented on bld/configure
>  elsif ($dyn_pkg eq 'se') {
https://github.com/ESCOMP/CAM/blob/70ca71281e12d2e34e2735a58532b3e784fbd1c1/bld/configure#L698-L703

I think MPAS should be added to the list to allow use with WACCM physics.

2020-10-22 18:04 UTC, fvitt commented on bld/configure
>  elsif ($dyn_pkg eq 'se') {
> https://github.com/ESCOMP/CAM/blob/70ca71281e12d2e34e2735a58532b3e784fbd1c1/bld/configure#L698-L703
> 
> I think MPAS should be added to the list to allow use with WACCM physics.

Do we need this check?  In principle, waccm physics should be run with any dycore.

2020-10-22 20:39 UTC, nusbaume reviewed
My second round of reviews.  Hopefully they are all easy and/or straight-forward.

2020-10-22 20:44 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +Height MSL to begin w-damping profile
Thanks for fixing this!  I also realized that it might be good to specify that the height must also be in meters (m).

2020-10-22 21:20 UTC, nusbaume commented on src/dynamics/mpas/dyn_grid.F90
> +                             pio_seterrorhandling, PIO_BCAST_ERROR, PIO_NOERR
It seems like most of these `pio` entries aren't actually used anywhere in the module.  Might be worth cleaning up?

(Not sure how this one wasn't included in my official review request above, but I wanted to add it now before I forgot.  Whoops!)

2020-10-23 18:56 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +Height MSL to begin w-damping profile
Done.

2020-10-23 19:03 UTC, brian-eaton commented on src/utils/string_utils.F90
> +   end if
I agree these checks are redundant.  Removed.

2020-10-23 19:09 UTC, brian-eaton commented on bld/build-namelist
> +# MPAS-Atmosphere dycore
Done.

2020-10-23 19:18 UTC, brian-eaton commented on bld/configure
>  elsif ($dyn_pkg eq 'se') {
I don't recall that waccm physics has ever run with the Eulerian spectral dycore, so I changed this check to just fail in that case. @fvitt does that sound OK?  I can just remove the check if you think that the waccm/eul config should be allowed.

2020-10-23 19:22 UTC, brian-eaton commented on src/dynamics/mpas/scripts/build_cam_namelists.py
> +build_cam_namelists.py
I just hadn't gotten around to removing it.  Will be gone in next commit.

2020-10-23 19:39 UTC, fvitt commented on bld/configure
>  elsif ($dyn_pkg eq 'se') {
Sounds okay.  I don't think anyone has ever tried to run waccm with eul dycore (or wants to).

2020-10-23 20:10 UTC, brian-eaton commented on src/dynamics/mpas/stepon.F90
> +   ! This call writes the inputs to the physics package on the dynamics
I did mean "physics package".  The point is subtle and has to do with details of CAM's initialization, i.e., the dycore doesn't run during the initialization, only part of the physics package does.  I took another stab at trying to make the comment clear.  Let me know if it helps.

2020-10-23 20:47 UTC, cacraigucar reviewed
I've completed my review and did not find any other issues.  Please request rereview when everyone's comments have been addressed.

2020-10-24 00:42 UTC, brian-eaton commented on Externals_CAM.cfg
> +required = True
I just pushed the commit that merges Michael's mods to checkout the MPAS external from the MPAS-Dev/MPAS-Model repo.

2020-10-24 00:49 UTC, brian-eaton commented on src/dynamics/mpas/dp_coupling.F90
> +         ! include water vapor in in moist pdel.
Fixed.

2020-10-24 00:55 UTC, brian-eaton commented on src/dynamics/mpas/dp_coupling.F90
> +#else
This is the result of starting from the SE version of dp_coupling where this cpp conditional also appears.  I'm going to remove it here since it's not clear whether the same "fix" would apply to mpas.

2020-10-24 00:56 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +                                          ! independent way to to identify the physics grid on the dynamics
Fixed.

2020-10-24 00:59 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +9840 format(1x, 3x, 12x, f15.4, 9x, f15.4)
Done.

2020-10-24 01:06 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +   character(len=*), parameter :: subname = 'dyn_grid::get_block_bounds_d'
All gone.

2020-10-24 01:16 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +   do icol = 1, num_col_per_block(blockid)
Done.

2020-10-24 01:21 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +      call endrun( subname // ':: arrays not large enough' )
Added value of cnt to error output.

2020-10-24 01:36 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +      area_d_out(:) = areaCell_g(:) / (6371229.0_r8**2.0_r8)
Replaced denominator by rearth**2 in two places.

2020-10-24 01:38 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +      call endrun('get_dyn_grid_parm_real1d: w not defined')
Done.

2020-10-24 01:39 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +   call endrun('dyn_grid_get_elem_coords: not implemented for the MPAS grids')
Done.

2020-10-24 01:41 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +      call endrun(routine//': ERROR: number levels in IC file does not match plev.')
Fixed.

2020-10-24 01:43 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +                             pio_seterrorhandling, PIO_BCAST_ERROR, PIO_NOERR
file_desc_t is the only one being used.  I removed the others.

2020-10-26 02:11 UTC, gold2718 requested changes
I have a few change requests and questions.
Code reviewed up through 1aeb92eb.

2020-10-26 02:11 UTC, gold2718 commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
Why not just replace this entire section with a single `write` statement?
```suggestion
       write(histAtt, '(A,I0,A,A,A)') 'mpirun -n ', domain % dminfo % nProcs, ' ./', trim(domain % core % coreName), '_model'
```

2020-10-26 02:11 UTC, gold2718 commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!      call MPAS_stream_mgr_add_att(domain % streamManager, 'history', domain % history)
Do we really need commented out code from over 6 years ago? Please remove.

2020-10-26 02:11 UTC, gold2718 commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                end if
Is there really no need for an error-checking `else` here?

2020-10-26 17:12 UTC, brian-eaton commented on src/utils/cam_map_utils.F90
> +        ndest = size(dest_in)
This was a fix along a path which I eventually abandoned, which is why it's no longer clear why it might be needed.  The map code currently assumes that the internal dycore data structures have a "block" dimension.  This isn't needed for mpas since it assigns one block per task.  I was trying to dimension arrays for reading the mpas initial file without using a dimension of size 1 for the blocks, and that's where I was running into trouble.  When you're reading data, the "dest" arrays are the local storage and my "dest_in" only needed 1 dimension.  I believe it was GNU/debug that complained about the size of dest_in not being the same as the size of d, and that's where this particular fix came from.  But I ran into other problems that weren't so easy to resolve and eventually I decided to back off to using the extra size 1 block dimension since this code seems to only be working when a block dimension is used.

2020-10-26 17:15 UTC, brian-eaton commented on src/dynamics/mpas/dp_coupling.F90
> +#else
Peter has let me know that we don't need this conditional in the SE code either, so I removed it from that version of dp_coupling as well.

2020-10-26 17:16 UTC, brian-eaton commented on src/dynamics/mpas/dyn_grid.F90
> +      call endrun( subname // ':: incorrect number of cells' )
Done.

2020-10-26 17:55 UTC, brian-eaton commented on src/control/cam_history_support.F90
> +     nday2str = adjustl(str)
Done.  And while I was at it I removed the format statement and just included the format in the write statement.  This function is now in string_utils.F90.

2020-10-26 17:57 UTC, brian-eaton commented on bld/configure
> +     -mpas_libdir <dir> Directory containing MPAS library.
Done.

2020-10-26 18:35 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<mpas_del4u_div_factor>10.0</mpas_del4u_div_factor>
I don't know the answer.  Seems like no harm done to add the 'D' specifiers to the constants so I'll do that for the new mpas variables.

2020-10-26 18:49 UTC, brian-eaton commented on bld/build-namelist
> +    }
If I'm understanding the comment, the purpose of the conditional checking for the streams_gen executable is to allow build-namelist to be called before that executable exists.  If that's correct, then it wouldn't make sense to die if it's not found.  I'm guessing this is related to how the cesm scripts do things like call build-namelist for namelist previews before things are built?

2020-10-26 18:51 UTC, brian-eaton commented on doc/ChangeLog
> +  structures.  The dimension order for MPAS arrays is vertical levels, the
Fixed.

2020-10-26 18:56 UTC, brian-eaton commented on doc/ChangeLog
> +      depends on the pressure profile and the current code which got things
Correct.  This was explained in the ChangeLog dp_coupling notes.

2020-10-26 19:07 UTC, brian-eaton commented on doc/ChangeLog
> +    read PHIS from the topo file.
No.  These two grids both use the dynamics decomposition.  I needed to read the topo file data into dynamics data structures, so I need a grid object that uses the dynamics decomp.  But it also needs to use the CAM dimension and coordinate names.  For SE this is the only cell centered dynamics grid needed because all input data is read from files that use CAM conventions.  For MPAS we are reading an MPAS initial file which does not follow CAM conventions, and a topo file that does follow CAM conventions.  The other cell centered dynamics grid uses the MPAS convention for dimension and coordinate names.

2020-10-26 19:08 UTC, brian-eaton commented on doc/ChangeLog
> +  updates in the MPAS registry.
I removed the script and forgot to remove the ChangeLog entry, now done.  We decided to go manual with the namelist.

2020-10-26 19:12 UTC, brian-eaton commented on doc/ChangeLog
> +. Temporary pointer to cime branch for MPAS build and grids
The cime commit has been made.  I'll update CAM's cime tag before the commit.  I removed this entry from the ChangeLog since it won't be relevant once I update to a tag of cime master.

2020-10-26 19:16 UTC, brian-eaton commented on src/utils/string_utils.F90
> +   int2str = adjustl(str)
This comment was also made in cam_history_support which is where this new function lived before I moved it to string_utils.  Fixed as noted above.

2020-10-26 19:22 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +       group="nhyd_model" valid_values="">
The reason why is because the auto-generate script wasn't smart enough to do that.  Now that we're operating in manual mode I've checked the mpas registry file and it appears that SRK3 is the only valid value, so I added that to the definition.  Will do the same for subsequent questions of this nature.

2020-10-26 19:25 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +       group="nhyd_model" valid_values="">
Fixed.

2020-10-26 19:26 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +       group="nhyd_model" valid_values="">
Fixed.

2020-10-26 19:29 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +</entry>
Fixed.

2020-10-26 20:34 UTC, gold2718 commented on src/utils/cam_map_utils.F90
> +        ndest = size(dest_in)
Thanks. I think all that is needed is to initialize `d` inside this conditional (`d = 0`) since the unused dimension just has to be zero. This is the default for unstructured grids so it should have worked for MPAS -- not sure what the code looked like at that point.

2020-10-26 21:45 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +! Note that the fields in the import and export states are pointers into the MPAS dycore internal
Done.

2020-10-26 21:58 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_run(integrationLength)
The integrationLength is the cam timestep (embedded in an MPAS_TimeInterval_type object) which cannot change during a run.  MPAS may use a shorter timestep than CAM's DP coupling interval (dtime), just like the other dycores.  Could you please clarify what you're asking for?

2020-10-26 22:06 UTC, gold2718 commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_run(integrationLength)
While the CAM time step cannot currently change during a run, that restriction is likely to be lifted in order to meet SIMA data assimilation goals. This indirect storage of the initial value of `dtime` will prevent MPAS from adjusting to a different time step.

2020-10-26 22:19 UTC, brian-eaton commented on src/utils/cam_map_utils.F90
> +        ndest = size(dest_in)
I added a statement to initialize d=0 inside this conditional as requested by Steve.  For some reason that request isn't here, and I'm not sure where it is.

2020-10-27 00:05 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_run(integrationLength)
Could you explain how data assimilation goals could affect the CAM timestep?  I don't recall this issue coming up in any previous discussions concerning data assimilation.

In order for CAM to change its timestep during a run, a call to the time manager module (something like timemgr_update_timestep) would be needed.  None of this infrastructure is in place.  I could set the MPAS integrationLength variable from dtime at every timestep, but since dtime can't change this seems more confusing than anything else.  It would give the appearance that dtime could change when it can't.  It seems premature to be trying to address this concern here.

2020-10-27 00:11 UTC, gold2718 commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_run(integrationLength)
While many discussions revolved around using DART for data assimilation, other systems, such as JEDI were discussed in SIMA meetings. I agree that resetting `integrationLength` is not necessary at time time which is why I simply asked for a check that `dtime` has not changed.

2020-10-27 00:39 UTC, brian-eaton commented on src/dynamics/mpas/dp_coupling.F90
> +   real(r8), parameter :: pref = 1.e5_r8 ! reference pressure (Pa)
pstd in physconst is set from the share constants module to be 101325.  The textbook (I checked three) convention for the reference pressure used to define potential temperature is 1.e5.  

This is not the reason we use the MPAS exner values when converting MPAS's prognosed potential temperature to temperature.  It's because the actual pressure MPAS uses in that calculation is from a non-hydrostatic pressure profile.  CAM's physics package operates with a hydrostatic pressure profile, so that profile is used to define the associated potential temperatures internal to the physics package.

2020-10-27 00:46 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_run(integrationLength)
I was hoping you would shed some light on how data assimilation might require a change to CAM's timestep, just out of curiosity.

A check that dtime has not changed implies that it might change.  But it can't.  So that's confusing, and doesn't make the system any more robust.  It's also inconsistent with the other dycores and the physics package which have no such checks.

2020-10-27 20:59 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       call mpas_log_write('Reading streams configuration from file '//trim(domain_ptr % streams_filename))
Calls to `mpas_log_write` are sent to CAM's logging unit (`iulog`) when MPAS is used as a CAM dycore. Is this consistent with CESM and CAM standard usage?

2020-10-27 21:08 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +          call mpas_timer_start('time integration')
I'd prefer the time measured by these timers to be written out to the log file along with other MPAS-specific timers ([example](https://github.com/MPAS-Dev/MPAS-Model/blob/atmosphere/cam/src/core_atmosphere/dynamics/mpas_atm_time_integration.F#L313)) at the end of a simulation.

2020-10-27 21:51 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +#ifdef MPAS_USE_STREAMS
At this point I don't think we'll use the `MPAS_USE_STREAMS` code in the near future, so I'll just remove it for now.

2020-10-27 21:56 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +    !>  ...
Since I'm removing the `MPAS_USE_STREAMS` code, I'll remove this subroutine, too.

2020-10-27 23:55 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end do
I think the proposed alternative is easier to read and correct. Some of the code in this routine predates the introduction of the `cnst_is_a_water_species` function, if I recall correctly, and that might explain the difficult loop structure. I'll update with the simpler loop (though I'll probably initialize `idx_passive` to `num_moist + 1` and post-increment it).

2020-10-28 04:49 UTC, mgduda commented on bld/namelist_files/namelist_definition.xml
> +<entry id="mpas_time_integration" type="char*512" category="mpas" group="nhyd_model" valid_values="">
While I don't think it should be a problem for the MPAS infrastructure to shorten this namelist option string, I'll first to some checking to verify this assumption.

2020-10-28 16:26 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
Looking through the code that defines `num_scalars`, there's no reason why `size(cnst_name)` should not be equal to `num_scalars`. I'll change this conditional.

2020-10-28 16:53 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +
If these are place holders and you are not planning on creating these for this PR can we remove the missing files from here and create a new issue for MPAS mods needed to fill out missing CESM functionality and common grids/resolutions?  Along with creating boundary data for .25/.5/1/2 degree resolutions, I would put items like providing for an automatic decomposition functionality which the other dycores have (mv gmetis functionality into cime scripts for building).  This comment applies to all other boundary data defaults that are placeholders.  If you create an issue can you put me on the list as I'll be maintaining fv3 after you.  Thanks.

2020-10-28 16:54 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +
that should be maintaining MPAS after you (not fv3)

2020-10-28 18:51 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +
These are files Michael used for his weak scaling testing, but we never added them to the standard location.  Since we now know that these files need to be remade to have something that works with the KESSLER compset I have removed them.  I kept the 480 km file because it's useful for testing, but renamed it to conform to our naming conventions.  I added the mpasa120z32 grid file with topography along with the corresponding mpasa120 topo file.  I have also added the initial file for mpasa120z32 created by Bill Skamarock.  This file can supply the "no topography" grid for analytic IC runs, and it can potentially be used as an initial file for aquaplanet runs.  I have copied the four files just mentioned to the svn data repo.

I haven't opened an issue for mpas workflow development as I don't plan to be involved in that task and feel it would better be done by someone who will be involved and has spent some time thinking about the issues that need to be addressed.

2020-10-28 19:02 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +
An FYI to whoever makes the next data files, there is mandatory metadata that is needed for the files.  Since there are a few new people working on this project, I figured it would be good to get this information posted here.  The link for the requirements is:  http://www.cesm.ucar.edu/working_groups/Atmosphere/required-meta-data-amwgcam-datasets.html

2020-10-28 20:49 UTC, nusbaume reviewed
Thanks for taking care of my requests!  This is my final review for this PR.  Once the concerns below have been addressed I will be happy to approve.

2020-10-28 23:06 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!
I've added a `README` file in the `src/dynamics/mpas/driver` directory.

2020-10-28 23:07 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +
I've updated the code to use to a module-level `implicit none` statement.

2020-10-28 23:08 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                              messageType=MPAS_LOG_ERR)
Done.

2020-10-28 23:08 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
Done.

2020-10-29 01:58 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
There is a general tendency in MPAS for routines to write an error message to a log file (which in the case of CAM-MPAS would be the `iulog` unit) before returning a non-zero error code. Applying this recursively, we should in principle get an error stack that points to the problem.

So, for example (not based on current code), we might hope for something like the following in a log file:
```
Error: No available Fortran units.
Error: Could not open file 'log.atmosphere.0000.out'.
Error: Log setup failed.
Error: Initialization of the 'atmosphere' core failed.
```
In an ideal world, we would get file names and line numbers for each of these log messages; but, we don't right now.

My preference would be to simply leave the error message as it is: `Log setup failed for MPAS-A dycore`. If the `setup_log` routine doesn't say anything useful before returning an error code, then I would suggest we should address that issue in the `setup_log` routine rather than in the `cam_mpas_init_phase1` routine.

2020-10-29 02:00 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +          owningBlock = indexToBlockID(iCell) + 0            ! 1-based block indices?
No, I'll remove ` + 0            ! 1-based block indices?`

2020-10-29 02:08 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       procedure(halt_model) :: endrun
Hopefully these routines wouldn't return status codes of 1, -1, 1, -1, ... or another sequence that sums to 0.

An alternative would be to turn the `cam_mpas_read_static`, `cam_mpas_setup_restart`, `cam_mpas_read_restart`, and `cam_mpas_write_restart` routines into functions that return integer status codes. We could then log an error message before returning an error code as an alternative to calling `endrun`.

I'll go with whatever you prefer, or whatever is the most CAM-like.

2020-10-29 02:10 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +
Yes, good catch.

2020-10-29 02:10 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +
Yes.

2020-10-29 02:15 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       type (MPAS_TimeInterval_type) :: integrationLength
Agreed.

2020-10-29 04:58 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       procedure(halt_model) :: endrun
Actually, I just noticed that the CAM coding standards requires that `Functions may not have side effects.`. I'll find a way to combine error codes and call `endrun` before returning from the subroutine if not all calls were successful.

I should also convert `cam_mpas_define_scalars` from a function to a subroutine.

2020-10-29 16:27 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!      call MPAS_stream_mgr_add_att(domain % streamManager, 'history', domain % history)
This code has been removed.

2020-10-29 16:27 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +    !>  ...
This code has been removed.

2020-10-29 16:27 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
This code has been removed.

2020-10-29 16:27 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                end if
This code has been removed.

2020-10-29 17:54 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end interface
This code has been removed.

2020-10-29 18:05 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       call mpas_bootstrap_framework_phase2(domain_ptr)
Removed.

2020-10-29 18:08 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +          call mpas_log_write('The ''state'' pool was not found by cam_mpas_define_scalars', &
Done.

2020-10-29 18:35 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       real (kind=RKIND), dimension(:), intent(out) :: areaCellGlobal
As per agreement from our Oct 26 AMP projects meeting I have added a check to cam_mpas_init_phase1 that the real kinds are equal.

2020-10-29 18:58 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +               ! Error...
Done.

2020-10-29 18:58 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +           ! Error...
Done.

2020-10-29 18:59 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +               ! Error...
Done.

2020-10-29 19:02 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +    subroutine cam_mpas_cell_to_edge_winds(nEdges, uZonal, uMerid, east, north, edgeNormalVectors, &
Check has been added that R8==RKIND.

2020-10-29 19:02 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                                                       + edgeNormalVectors(3,iEdge)*north(3,cell2))
Check has been added that R8==RKIND.

2020-10-29 19:14 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_init_phase1(mpicom, endrun, logUnits)
A description of each of MPAS initialization phases is included in the module containing those routines.  I could cut and paste those descriptions here, but duplicating information is not a good practice.  The user who is interested can easily look in the cam_mpas_subdriver module.

2020-10-29 19:20 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +   character(len=*), parameter :: subname = 'dyn_comp::dyn_run'
I removed all occurences of unused subname parameters.

2020-10-29 19:23 UTC, brian-eaton commented on src/dynamics/mpas/dyn_comp.F90
> +         call endrun(subname//': failed to read theta_base from initial file')
Fixed.

2020-10-29 19:25 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +
This code has been removed.

2020-10-29 19:30 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
We are also consistently adding the name of the routine where endrun was called from to the error message.  This is a big help in tracing back where endrun calls are made from.

2020-10-30 19:00 UTC, nusbaume commented on src/dynamics/mpas/dyn_comp.F90
> +   call cam_mpas_init_phase1(mpicom, endrun, logUnits)
Yeah, I probably should have looked at the actual subroutines first before making this request.  I am happy with the descriptions there, so feel free to ignore this particular request.

2020-10-30 19:19 UTC, nusbaume commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       end if
@mgduda I agree that the method you described would be ideal, and that it also sounds non-trivial to implement. I was more just asking if the value of `ierr` itself provided any additional info (e.g. if `-1` meant a missing file, `-2` meant an array-size issue, and so on).  If that's not the case then I perfectly happy with the error messages as is, so I will go ahead and mark this particular concern as resolved.

2020-10-30 20:53 UTC, cacraigucar requested changes

2020-10-30 20:53 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
Might want to make one of these prealpha to make sure that cime doesn't break the MPAS dycore.

2020-10-30 21:08 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +
I created the MPAS-A dycore workflow and additional compset support #260 issue. @cacraigucar Most likely I'll be the person responsible for the boundary data and will make sure to follow the metadata requirements.

2020-11-02 17:50 UTC, jtruesdal commented on src/dynamics/mpas/Makefile
> +CPPFLAGS := -D_MPI -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=unknown -DMPAS_NAMELIST_SUFFIX=atmosphere -DMPAS_CAM_DYCORE
Does -DMPAS_NATIVE_TIMERS cpp definition turn on timers? Looking to see if this is a possible performance hit.

2020-11-02 19:14 UTC, brian-eaton commented on src/utils/cam_map_utils.F90
> +        ndest = size(dest_in)
I just ran into a problem with the mods I made in cam_map_utils.F90 when running regression tests involving the SE dycore.  I don't think I ever tested SE when I was trying to get MPAS to work without declaring a block dimension for the dynamics decomp.  Since I had to back away from that approach anyway, I have decided to simply revert this file to the original.  I leave it as an exercise for some future masochist to find the mods needed to extend to code to work without a block dimension in the dynamics decomp.

2020-11-03 15:37 UTC, jtruesdal commented
@PeterHjortLauritzen I'm not sure where the energy budget validation effort is with MPAS but I was wondering if MPAS should be added to some of the checks for TFIX in cam_diagnostics.F90 (like SE,FV, FV3)?

2020-11-03 15:48 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                                                    +  edgeNormalVectors(3,iEdge) * north(3,cell2))
There should be an entry in test/system/TR8.sh for all the mpas interface files.

2020-11-03 15:59 UTC, jtruesdal reviewed
I've finished my review.

2020-11-04 21:23 UTC, PeterHjortLauritzen commented
> @PeterHjortLauritzen I'm not sure where the energy budget validation effort is with MPAS but I was wondering if MPAS should be added to some of the checks for TFIX in cam_diagnostics.F90 (like SE,FV, FV3)?

MPAS should be added to the conditional (or alternatively we could do " if (.not.dycore('EUL')"):

    if ( dycore_is('LR') .or. dycore_is('SE')  .or. dycore_is('FV3') ) then
      call addfld ('TFIX',    horiz_only,  'A', 'K/s',        'T fixer (T equivalent of Energy correction)')
    end if

FYI: We have not adapted the total energy fixer for MPAS yet.

2020-11-05 16:58 UTC, brian-eaton commented
I've run into some problems with trying to get the cime mods we need for MPAS directly from ESMCI/cime/master (currently the mpas_simple branch pulls them from a branch off of cime5.8.28 in my cime fork).  Chris merged the mods to cime master some time ago, but there was no tag made at the time.  I just asked Chris for a tag to start the regression testing and got one that he added to the head of cime/master.  That tag had two problems.  One was that a lot of tests were failing due to a cime testing bug (some executables were not being created) and the other was that all 3 WACCMX tests had baseline failures.  So I asked Chris if he could back off that tag to the commit where he merged the mods we needed for MPAS.  He did that and now the cime testing seems to be working again, but the WACCMX baseline failures are still present.  This cime tag is many commits past the cime5.8.32 tag currently being used by CESM.

If someone knows a cime change that is responsible for answer changes in WACCMX then I could go with this cime tag and just make a separate CAM tag with the cime update before making the CAM tag with the MPAS update.  But if this is an unknown then I'm wondering whether we could make a cime branch off of cime5.8.32 for use in this PR.  Comments?

2020-11-05 17:12 UTC, cacraigucar commented
@brian-eaton Have you verified that the WACCMX answer changes are not due to cime changes between cime5.8.28 (where CAM currently is) and cime5.8.32?

2020-11-05 18:23 UTC, brian-eaton commented
I have checked the cesm testing database and don't find any mention of WACCMX baseline failures due to changes between cime5.8.28 (cesm2_2_alpha06c) and cime5.8.32 (cesm2_2_alpha06f).  There is mention of diffs in FXHIST, but that seems to be due to a fix in cam.  I'm seeing diffs in FXHIST, FXSD, and FX2000.  @cacraigucar, do you think I should run the regression with the update just to cime5.8.32 just to be sure?

2020-11-05 19:06 UTC, cacraigucar commented
> I have checked the cesm testing database and don't find any mention of WACCMX baseline failures due to changes between cime5.8.28 (cesm2_2_alpha06c) and cime5.8.32 (cesm2_2_alpha06f). There is mention of diffs in FXHIST, but that seems to be due to a fix in cam. I'm seeing diffs in FXHIST, FXSD, and FX2000. @cacraigucar, do you think I should run the regression with the update just to cime5.8.32 just to be sure?

@brian-eaton   Yes, I would be running the tests to just confirm for myself that the baselines remain the same using cime5.8.32 for CAM regression testing.

2020-11-05 19:08 UTC, cacraigucar commented
@brian-eaton Also, if you do see answer changes, save that testing as we might want to squeeze in an intermediate CAM tag that just updates cime to cime5.8.32.  Of course we would still need to understand why WACCMX has answer changes before doing so.

2020-11-05 20:19 UTC, fvitt commented
I see the ESMF lib version has changed between cime5.8.28 and cime5.8.32 (esmf-8.1.0b17 --> esmf-8.1.0b23) for cheyenne.  This could conceivably explain the answers changes in WACCMX tests.   I believe cime5.8.32 is what we are using in the CESM2.2.0 release.

2020-11-05 20:32 UTC, cacraigucar commented
@brian-eaton This is sounding like the update of the CAM externals from cime5.8.28 to cime5.8.32 may be the culprit.  If that is confirmed by you, please open a PR for updating cime and you may go ahead with making cam6_3_003 with that one change.

2020-11-12 20:15 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +                                                    +  edgeNormalVectors(3,iEdge) * north(3,cell2))
Done.

2020-11-14 01:03 UTC, brian-eaton commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       procedure(halt_model) :: endrun
This has been done.

2020-11-14 01:06 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
I changed the FHS94 test to be prealpha.

2020-11-16 19:02 UTC, cacraigucar approved these changes

2020-11-16 20:20 UTC, fvitt approved these changes
I am curious to know if there is anything to prevent someone from trying to run cam physics with MPAS dycore.  The test cases you added seem to be only with simplified physics packages.

2020-11-16 20:26 UTC, jtruesdal commented on src/dynamics/mpas/Makefile
> +CPPFLAGS := -D_MPI -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=unknown -DMPAS_NAMELIST_SUFFIX=atmosphere -DMPAS_CAM_DYCORE
I've checked the performance with some tests and don't see any hit.

2020-11-16 21:17 UTC, mgduda commented on src/dynamics/mpas/Makefile
> +CPPFLAGS := -D_MPI -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=unknown -DMPAS_NAMELIST_SUFFIX=atmosphere -DMPAS_CAM_DYCORE
Sorry, I lost track of this. Essentially, adding `-DMPAS_NATIVE_TIMERS` tells the MPAS timer module to use `MPI_Wtime` with some internal data structures to track time information rather than another external library like TAU or PAPI. I suppose "native" isn't quite the right term, but it was probably meant to convey the fact that no external timing library is needed.

2020-11-16 21:49 UTC, nusbaume approved these changes
Thanks for the fixes!  It all looks good to me now.  I do have one last question, but whatever the answer is it shouldn't be important enough to hold-up this PR.

2020-11-16 21:49 UTC, nusbaume commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       startTime = mpas_get_clock_time(clock, MPAS_START_TIME, ierr)
Does this `ierr` value need checked here?

2020-11-16 23:46 UTC, jtruesdal approved these changes
Looks good.  Thanks for including the FV3 fix.

2020-11-17 00:55 UTC, brian-eaton commented
> I am curious to know if there is anything to prevent someone from trying to run cam physics with MPAS dycore. The test cases you added seem to be only with simplified physics packages.

No.  Nor do I think there should be.  That would just get in the way of the developers who are currently working on the full physics functionality.

2020-11-17 04:19 UTC, gold2718 commented on bld/build-namelist
> +    }
Ah, I did not realize that the executable was created during the build, perhaps a comment to that effect would help?

2020-11-18 00:47 UTC, gold2718 approved these changes
I have a question about `get_hdim_name` but if that works in all cases, everything else looks good. Thanks for all the fixes!

2020-11-18 00:47 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +
Does it always work to try `ncol` first? Can there be an initial data file with the dynamics state on the GLL grid but that also has physics fields (e.g., the ones read from `fh_ini` in `phys_inidat`?
Does this algorithm do the right thing in that case?

2020-11-18 23:02 UTC, brian-eaton commented on Externals.cfg
> +repo_url = https://github.com/brian-eaton/cime
Updated to cime5.8.34 from ESMCI/cime.

2020-11-18 23:08 UTC, brian-eaton commented on bld/build-namelist
> +    }
Added more detail to comment.

2020-11-18 23:43 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +
Good call.  Although the "optional" physics fields should no longer be written to the initial file, the code to do so is still in place and could be turned on.  Switching the order so that ncol_d is queried before ncol would correctly deal with that.  I'll make that change.

2020-11-19 19:49 UTC, fischer-ncar approved these changes

2020-11-19 20:35 UTC, merged