Refactor coupling with WACCMX ionosphere
ESCOMP/CAM pull request #264
Opened 2020-11-02 17:56 UTC by fvitt

This PR is a refactor of how WACCMX ionosphere is coupled to CAM to be independent of dynamical core.  

Previously, the FV dycore grid was used as the ion transport grid.  Thus, WACCMX could only be run with FV dycore.   

Here, ESMF regridding utilities are used to regrid fields between independent ion transport lat/lon grid, electro-dynamo geomagnetic lat/lon grid, and a generalized cam physics grid mesh.  The use of an ESMF gridded component to contain the ion transport and electro-dynamo ionosphere components allows the ionosphere to be executed on a subset of CAM's MPI tasks and for multi-instance WACCMX configurations (a requirement for WACCMX-DART).

closes #84 
closes #223
closes #151

2020-12-29 22:21 UTC, nusbaume requested changes
Mostly looks ok to me!  I just have some clean-up and clarification requests.

Also, one other  issue I have that is not listed below is that in some of the source files the `WACCMX_EDYN_ESMF` def is so prevalent that it impacts readability (at least for me).  I assume this pre-proc def is necessary in order to prevent users from having to build ESMF? 

 If so then it might be good to create a Github issue stating that this `WACCMX_EDYN_ESMF` def can be replaced with a fortran run-time option once NUOPC/ESMF becomes the default CAM configuration (which I can do, I just want to make sure I am understanding the purpose of `WACCMX_EDYN_ESMF` correctly).  Thus any info you can provide would certainly be appreciated.

2020-12-29 22:21 UTC, nusbaume commented on src/ionosphere/waccmx/edyn_esmf.F90
> +#endif
I would remove this always false `#if` statement.  I imagine you can just comment out the ESMF calls like what is done above if need be.

2020-12-30 16:12 UTC, fvitt commented
@nusbaume,
The WACCMX_EDYN_ESMF cpp variable is intended to allow ion transport without the need for the ESMF library and without an active electro-dynamo.  This was the "-ionosphere wxi" configure option which was unsupported and was removed in this PR.  We may be able to remove the WACCMX_EDYN_ESMF cpp defs from the code.  I will explore this possibility.

2020-12-30 16:14 UTC, fvitt commented on doc/ChangeLog
> +M	cime_config/testdefs/testmods_dirs/cam/waccmx_weimer/user_nl_cam
Thanks for pointing out the omission.

2020-12-30 16:16 UTC, fvitt commented on bld/configure
> +     -mgrid             Magnetic grid resolution for the ionosphere [ 97x80 | 193x160 ].
Yes

2020-12-30 16:20 UTC, fvitt commented on src/ionosphere/waccmx/edyn_init.F90
> +      call addfld ('MBAR_geo', (/ 'lev' /), 'I', ' ',' '   , gridname='geo_grid')
These diagnostics were added for my debugging purposes.  These should be removed.

2020-12-30 16:21 UTC, fvitt commented on src/ionosphere/waccmx/edyn_geogrid.F90
> +!  character(len=10) :: lev_sequence
These have been removed

2020-12-30 21:20 UTC, fvitt commented on src/ionosphere/waccmx/utils_mod.F90
> +    real(r8), intent(in)  :: dim(lg,*)
Appears to be dead code.  Will remove this subroutine.

2020-12-31 15:26 UTC, fvitt commented on src/ionosphere/waccmx/utils_mod.F90
> +    !
yes

2020-12-31 15:27 UTC, fvitt commented on src/ionosphere/waccmx/utils_mod.F90
> +    character(len=256) :: errmsg
yes

2020-12-31 15:27 UTC, fvitt commented on src/ionosphere/waccmx/utils_mod.F90
> +    character(len=256) :: errmsg
yes

2020-12-31 15:28 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +  character(len=256), allocatable :: ltr_files(:)
ok

2020-12-31 15:30 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +    !
removed the commented out writes

2020-12-31 15:30 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +    istat = pio_inquire_dimension(ncid, id_time, len=ntimes)
added check_ncerr

2020-12-31 15:31 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +    !if (denoma > 1._r8) then
yes

2020-12-31 15:31 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +       !     Allocate workspace for regrid routine rgrd2.f:
done

2020-12-31 15:32 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +  character(len=256), allocatable :: amiesh_files(:)
yes

2020-12-31 15:33 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +    !     write(iulog, "('lonp1=', i3, ' latp1=', i3)") lonp1, latp1
removed

2020-12-31 15:33 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       !     f2 = (model_ut - amie_sh_ut(iset))/denoma
yes

2020-12-31 15:34 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       !     f2 = (model_ut - amie_nh_ut(iset))/denoma
removed it

2020-12-31 15:34 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +    !     endif
yep

2020-12-31 15:34 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       !     Allocate workspace for regrid routine rgrd2.f:
made the change

2020-12-31 15:35 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       !
removed this dead code

2020-12-31 15:37 UTC, fvitt commented on src/ionosphere/waccmx/ionosphere_interface.F90
> +   character(len=256) :: ltr_files(max_num_files) = 'NONE'
ok

2020-12-31 15:49 UTC, fvitt commented on src/ionosphere/waccmx/ionosphere_interface.F90
> +      real(r8) :: re = 6.370e6_r8                      ! earth radius (m)
agree

2020-12-31 16:09 UTC, fvitt commented on src/ionosphere/waccmx/dpie_coupling.F90
> +     ! (omega (Pa/s), tn (K), and mbar (??) are inputs, grav is m/s^2)
I believe you are correct

2020-12-31 16:11 UTC, fvitt commented on src/ionosphere/waccmx/dpie_coupling.F90
> +     call outfld_phys('DPIE_MBAR',mbar)
don't know

2020-12-31 17:56 UTC, fvitt commented on src/ionosphere/waccmx/edyn_init.F90
> +      character(len=80) :: msg
I believe subroutine lonshift_global is dead code.  Will remove it.

2020-12-31 17:58 UTC, fvitt commented on src/ionosphere/waccmx/edyn_init.F90
> +         call endrun
removed dead code

2021-01-04 16:04 UTC, fvitt commented on src/ionosphere/waccmx/edyn_geogrid.F90
> +      endif
I don't believe so

2021-01-04 16:54 UTC, fvitt commented on src/ionosphere/waccmx/edyn_geogrid.F90
> +      dlong = 2._r8*pi / real(nlon,r8)
Yes. Thanks for pointing this out.

2021-01-04 17:26 UTC, fvitt commented on src/ionosphere/waccmx/wei05sc.F90
> +         write(iulog,"(/,a,i4,' na = ',i4)")                                  &
Yes that would be better.

2021-01-04 17:33 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +         call endrun('edyn_mpi mp_init')
ok

2021-01-04 17:33 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +      character(len=256)          :: errmsg
yes

2021-01-04 17:34 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +      rnlon = dble(nlon_geo)
yes

2021-01-04 17:34 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +            !if (debug.and.masterproc) write(iulog,"('setpoles: spole ave(k0:k1)=',/,(8es12.4))") fave
I removed the line

2021-01-04 17:45 UTC, fvitt commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +      character(len=80)       :: tempc1,tempc2
ok

2021-01-04 17:45 UTC, fvitt commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +               write(*,*) trim(errstr)
yes

2021-01-04 17:45 UTC, fvitt commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +               write(*,*) trim(errstr)
yes

2021-01-04 17:48 UTC, fvitt commented on src/ionosphere/waccmx/edynamo.F90
> +    zpotm3d = finit
I believe so

2021-01-04 17:59 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +      character(len=512)           :: errmsg
ok

2021-01-04 17:59 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +         call edyn_esmf_chkerr(subname, 'ESMF_FieldGet, mag_phi3d', rc)
yes

2021-01-04 17:59 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +         call edyn_esmf_chkerr(subname, 'ESMF_FieldGet, phys_phi3d', rc)
yes

2021-01-04 18:01 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +
removed them

2021-01-04 18:02 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +#endif
okay

2021-01-04 18:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccmx_ma_2000_cam4.xml
> +<qbo_use_forcing dyn="fv">.true.</qbo_use_forcing>
QBO settings will be addressed in another PR.  Can we leave this as it is for this PR?

2021-01-04 18:08 UTC, fvitt commented on src/ionosphere/waccmx/adotv_mod.F90
> +      bmod                 ! magnitude of magnetic field (gauss?)
agree

2021-01-04 18:08 UTC, fvitt commented on src/ionosphere/waccmx/adotv_mod.F90
> +          bmod,              & ! magnitude of magnetic field (gauss?)
right

2021-01-04 18:09 UTC, fvitt commented on src/physics/cam/phys_control.F90
> +character(len=256) :: cam_physics_mesh    = unset_str  ! SCRIP file for phys
okay

2021-01-04 18:10 UTC, fvitt commented on src/physics/cam/phys_control.F90
> +   character(len=256),intent(out), optional :: physics_grid_out
ok

2021-01-04 18:10 UTC, fvitt commented on src/physics/cam/cam_diagnostics.F90
> +    call addfld( 'RAIRV', (/ 'lev' /), 'I', 'J/K/kg', 'specific heat cap air' )
I corrected the description

2021-02-22 22:27 UTC, nusbaume commented on bld/namelist_files/use_cases/waccmx_ma_2000_cam4.xml
> +<qbo_use_forcing dyn="fv">.true.</qbo_use_forcing>
Right, I forgot that PR #305 is modifying all of this.  I'm fine to leave it as-is here.

2021-03-01 17:41 UTC, nusbaume reviewed
This looks a lot better, thanks!  I just have some final questions/concerns, but once they are addressed then it will be good to go on my end.

2021-03-01 17:41 UTC, nusbaume commented on src/ionosphere/waccmx/edyn_mudmod.F90
> +!     use cam_logfile  ,only: iulog
It looks like this concern was missed in the first go-around?

2021-03-01 17:41 UTC, nusbaume commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +      character(len=256)                    :: grid_file
Looks like this was missed on the first round of revisions.

2021-03-01 17:41 UTC, nusbaume commented on src/ionosphere/waccmx/edyn_esmf.F90
> +
It looks like they are still here?

2021-03-01 17:41 UTC, nusbaume commented on src/ionosphere/waccmx/edyn_esmf.F90
> +   use ESMF,           only: ESMF_FieldGet, ESMF_GridWriteVTK
I don't think you need the `ESMF_GridWriteVTK` entry, as it looks like the only uses have been commented out.

2021-03-02 15:50 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mudmod.F90
> +!     use cam_logfile  ,only: iulog
Removed the commented out code.

2021-03-02 18:41 UTC, gold2718 requested changes
@fvitt, we would like to move this forward to facilitate putting in WACCMX changes to the SE dycore. Could you merge this code up to cam_development and make sure that SE still works (or fix the issues that arise due to the weak scaling changes)? I am happy to work with you on any changes that are needed due to the weak scaling update.
When you are finished with this merge and the changes requested by @nusbaume, please select re-review for all AMP SEs.

2021-03-02 22:35 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       efx_nh_amie, efx_sh_amie
I rename the input arrays with suffix "_input".  I left the arrays which hold the time-interpolated data with the "_amie" suffix.

2021-03-02 22:36 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +    rtd = 180._r8 / pi          ! radians to degrees
We should use the edyn_params parameters.  I made the change.

2021-03-02 22:36 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       end do
I agree.

2021-03-02 22:37 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +       end if
I combined the if blocks.

2021-03-02 22:38 UTC, fvitt commented on src/ionosphere/waccmx/dpie_coupling.F90
> +    call addfld ('DPIE_MBAR' ,(/ 'lev' /), 'I', '        ','MBAR Mean Mass from dpie_coupling', gridname='physgrid')
Yes. Should be 'kg/kmole'.

2021-03-02 22:39 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +      ! Note: In the future, mag2geo might be added
I changed the comments to reflect this.

2021-03-02 22:40 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +  subroutine edyn_esmf_get_3dfield(field, data, i0,i1,j0,j1,k0,k1 )
I added checks for the ESMF field array bounds.

2021-03-02 22:41 UTC, fvitt commented on src/ionosphere/waccmx/edynamo.F90
> +    ped_meq, hal_meq, adotv1_meq, adotv2_meq !, zpot_meq
Removed it.

2021-03-02 22:41 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +              len_task_type,' npes=',npes
Yes I added the endrun call.

2021-03-02 22:41 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +              len_task_type,' npes=',npes
Yes I added the endrun call.

2021-03-02 22:43 UTC, fvitt commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +      character(len=256)                    :: grid_file
changed it to cl

2021-03-02 22:46 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +   use ESMF,           only: ESMF_FieldGet, ESMF_GridWriteVTK
Removed the unused VTK code.

2021-03-02 22:47 UTC, fvitt commented on src/ionosphere/waccmx/ionosphere_interface.F90
> +         allocate(opmmrtm1_blck(pver, blksize), stat=astat)
Added stat checks.

2021-03-02 22:48 UTC, fvitt commented on src/ionosphere/waccmx/ionosphere_interface.F90
> +         allocate(tempm(pcols, pver))
I put the allocate inside the if block as you suggest.

2021-03-02 22:49 UTC, fvitt commented on src/ionosphere/waccmx/ionosphere_interface.F90
> +                  tempm(i, k) = mbar_blck(k, j)
I removed the line.

2021-03-02 22:52 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +       pot_ltr, ekv_ltr, efx_ltr
I renamed the input data arrays with "_input" suffix.  I left names of the arrays which hold the time-interpolated data as they are with the "_ltr" suffix.

2021-03-02 22:52 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +       end do
Agree.

2021-03-02 22:53 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +       !     distored magnetic grids in radian - from consdyn.h
good catch

2021-03-02 22:53 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +       end if
I combined the if blocks.

2021-03-02 22:54 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +    rtd = 180._r8 / pi          ! radians to degrees
Should use the parameters in edyn_params.

2021-03-02 22:56 UTC, fvitt commented on src/ionosphere/waccmx/utils_mod.F90
> +       iset = iset1 - ibox
I added a call to endrun if ibox > mtime

2021-03-02 22:57 UTC, fvitt commented on src/ionosphere/waccmx/wei05sc.F90
> +     ! www.fizyka.umk.pl/nrbook/c6-1.pdf (numerical recipes gammln)
I changed the comments as you suggest.

2021-03-02 23:05 UTC, fvitt commented on src/ionosphere/waccmx/edyn_esmf.F90
> +
Removed the lines.

2021-03-03 18:18 UTC, nusbaume approved these changes
Looks great to me now.  Thanks for getting these major modifications ready!

2021-03-05 23:39 UTC, cacraigucar requested changes

2021-03-05 23:39 UTC, cacraigucar commented on bld/configure
> +        $cfg_cppdefs .= " -DEDYN_NLAT=$nmlat -DEDYN_NLON=$nmlon -DEDYN_NLEV=$nmlev -DEDYN_NGRID=$ngrid";
I know that we are trying to move away from cpp variables used in #ifdefs.  I don't know if that applies to constants as well.  EDYN_NLEV is used in 46 places in this code.  I did not see any place where these couldn't be namelist variables instead of configure variables, but I may have missed something.

2021-03-05 23:39 UTC, cacraigucar commented on src/ionosphere/waccmx/wei05sc.F90
> +         write(errmsg,"(a,i4,a,i4)") prefix//'rd_n_alschfits /= n_alschfits rd_n_alschfits = ', rd_n_alschfits,' n_alschfits = ', n_alschfits
This line is longer than 133 characters - please break into two lines

2021-03-10 00:08 UTC, fvitt commented on bld/configure
> +        $cfg_cppdefs .= " -DEDYN_NLAT=$nmlat -DEDYN_NLON=$nmlon -DEDYN_NLEV=$nmlev -DEDYN_NGRID=$ngrid";
@cacraigucar This is not straight forward.  Making the magnetic grid resolution run-time configurable is rather involved.  The tricky part is in `edyn_solve.F90`.  I may be able to make the changes if you really think this is necessary.

2021-03-10 00:11 UTC, fvitt commented on src/ionosphere/waccmx/edyn_geogrid.F90
> +  real(r8), public, allocatable            :: zp(:)   ! log pressure (as in tiegcm lev(nlev))
Yes this was clunky.  I moved this to oplus.F90

2021-03-10 00:12 UTC, cacraigucar commented on bld/configure
> +        $cfg_cppdefs .= " -DEDYN_NLAT=$nmlat -DEDYN_NLON=$nmlon -DEDYN_NLEV=$nmlev -DEDYN_NGRID=$ngrid";
Let's see what @gold2718 has to say on this.

2021-03-22 19:40 UTC, fvitt commented on bld/configure
> +        $cfg_cppdefs .= " -DEDYN_NLAT=$nmlat -DEDYN_NLON=$nmlon -DEDYN_NLEV=$nmlev -DEDYN_NGRID=$ngrid";
@gold2718, could you give your opinion on this matter?  Should I be spending some time to implement the change request by @cacraigucar to make the magnetic grid resolution run-time configurable?

2021-03-26 18:03 UTC, gold2718 commented on bld/configure
> +        $cfg_cppdefs .= " -DEDYN_NLAT=$nmlat -DEDYN_NLON=$nmlon -DEDYN_NLEV=$nmlev -DEDYN_NGRID=$ngrid";
@fvitt,
Sorry, I was buried in edyn_esmf and did not look at notifications or email. I was going to say that while this will be needed to work with the new infrastructure (where grids and levels are run-time quantities), it does not have to be fixed for this PR. However, it looks like you went ahead and did it anyway.
I'm really making an effort to get through this -- it is massive!

2021-03-27 05:18 UTC, gold2718 approved these changes
I have a couple of questions and a few suggestions but I think it is basically ready to go. It still needs some work to get up to standard but it is a whole lot better.

2021-03-27 05:18 UTC, gold2718 commented on doc/ChangeLog
> +
When you finish this file, please be sure to separate the 'A' (adds) and 'D' (deletes) into their correct locations.

2021-03-29 17:31 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se"  hgrid="ne16np4"   nlev="126" waccmx="1"               >atm/waccm/ic/waccmx_ne16np4_126L_c200108.nc</ncdata>
I believe the new files have been added to the inputdata repo.

2021-03-29 17:41 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq9s_576tsks/user_nl_clm
> +fsurdat = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/surfdata_0.47x0.63_78pfts_CMIP6_simyr2000_c180508.nc'
The file path is now relative to $DIN_LOC_ROOT

2021-03-29 17:43 UTC, fvitt commented on bld/configure
> +        $cfg_cppdefs .= " -DEDYN_NLAT=$nmlat -DEDYN_NLON=$nmlon -DEDYN_NLEV=$nmlev -DEDYN_NGRID=$ngrid";
The mag grid resolution is now run-time configurable.

2021-03-30 13:43 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +        nlat_geo,        & ! size of geo lat dimension
I removed the protected attribute from the private variables in this module.

2021-03-30 13:45 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mpi.F90
> +      !       mytid,mytidi,mytidj,lat0,lat1,nj,lon0,lon1,ni
I put the write statement inside a if debug block.

2021-03-30 13:46 UTC, fvitt commented on src/ionosphere/waccmx/edyn_solve.F90
> +    call mudmod(rim_glb,phisolv,jntl,isolve,res_nlev,ier)! solver in mudmod.F
Removed the comment.

2021-03-30 13:47 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mud.F90
> +      use edyn_solve,only: nc,cee
The subroutine mud was not used.  I removed it.  The remaining routines are inside a module.

2021-03-30 13:47 UTC, fvitt commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +   ! Private data and interfaces
Added a private statement.

2021-03-30 13:51 UTC, fvitt commented on src/ionosphere/waccmx/edyn_grid_comp.F90
> +      call ESMF_GridCompInitialize(phys_comp, rc=rc)
The import and export states are optional arguments.  It works as it is.  If you would like a better answer, I will need some time to study the code and think about it.

2021-03-30 14:40 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
This is different.  This does not have the ion transport in the ionosphere and  thus does not use ESMF regridding capabilities.  This exercises the SE dycore throughout the WACCMX vertical extent.  When we update the external cime tag I may change this to QPX2000 which exercises the ion transport and the ESMF regridding capabilities.

2021-03-30 14:40 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
I am changing this to prealpha.

2021-03-30 15:36 UTC, cacraigucar approved these changes

2021-04-01 01:44 UTC, merged