Initial implementation of weak scaling physics infrastructure
ESCOMP/CAM pull request #287
Opened 2020-12-06 21:14 UTC by gold2718

Initial implementation of weak scaling physics infrastructure
- Implement scalable physics grid with no load balancing
- Implement scalable gmean algorithm that does not need global data
- Modify SE/dyn_grid.F90 and related files for weak scaling interface
- Add repro sum variables if weak-scaling fix is on
- Added memory use for phys_grid_init and gmean timing
- Add cam_repro_sum to test namelists to ensure BFB compatibility
- Add checks to phys_debug_lat and phys_debug_lon
- **Note:** The repro_sum version of gmean is not scalable
- **Note:** create_native_mapping_files contains non-scalable memory use

fixes #127 
fixes #259

2020-12-07 18:48 UTC, cacraigucar requested changes
First round of reviews

2020-12-07 18:48 UTC, cacraigucar commented on bld/configure
> +            print $fh "$dir xx\n";
This looks like a typo.

2020-12-07 18:48 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +    for global calculations.
I didn't really understand this explanation until I read the following in the ChangeLog:
Maximum number of global fields to sum at one time

2020-12-07 18:48 UTC, cacraigucar commented on src/cpl/mct/atm_comp_mct.F90
> +       end if
Is this code to be committed?  If so, please change the comment.

2020-12-07 21:55 UTC, fvitt reviewed
What is the purpose of the "-weak_scaling_fix" configure

2020-12-07 21:55 UTC, fvitt commented on doc/ChangeLog
> +#127: Fix weak scaling issues in physics decomp
Can you elaborate on what purpose of these changes?  I gather infrastructure changes are to improve performance scaling of cam physics in terms of number of MPI tasks.

2020-12-07 21:55 UTC, fvitt commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
I find the directory name "weak_scaling" to be confusing.  Would something like "improved_scaling" be better?

2020-12-07 21:57 UTC, cacraigucar submitted a review, later dismissed
Round 2 comments

2020-12-07 22:00 UTC, gold2718 commented on src/cpl/mct/atm_comp_mct.F90
> +       end if
Change it to what? 'WS is complete' happens when all dycores can use the new physics infrastructure. Until then, this kludge needs to be here (or we need a copy of atm_comp_mct with just this change).

2020-12-07 22:02 UTC, gold2718 commented on doc/ChangeLog
> +#127: Fix weak scaling issues in physics decomp
The ChangeLog_template says to copy the issue number and title text. The explanation is in the issue: https://github.com/ESCOMP/CAM/issues/127

2020-12-07 22:03 UTC, gold2718 commented on src/dynamics/se/dyn_comp.F90
> +!                  call shr_sys_flush(6)
No idea. Brian left then in when he upgraded the implementation. @brian-eaton ? Any love left for these debug lines?

2020-12-07 22:03 UTC, cacraigucar commented on src/cpl/mct/atm_comp_mct.F90
> +       end if
My mistake - I thought weak scaling was complete with this PR.

2020-12-07 22:08 UTC, gold2718 commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
Well, the project was to solve the weak scaling issue but it does also address strong scaling issues.
@cacraigucar, any thoughts?

2020-12-07 22:50 UTC, cacraigucar commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
How ingrained is the name "weak scaling"?  I know it has been used for quite some time.  

On the other hand, now is the time to give it a name change, if it is appropriate.   Since it sounds like this is more than weak scaling,  I do like @fvitt suggestion of "improved_scaling" as it covers both the weak and strong scaling issues.

2020-12-08 00:49 UTC, brian-eaton commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
This project is replacing the dynamics-physics coupler with a new version that has better weak scaling properties.  The current coupler code lives in physics/cam/phys_grid.F90.  This would be a good time to move the new implementation into its own directory, say dyn_phys_coupling, at the same level as the dynamics and physics subdirectories under src/.  There doesn't seem to be any good logic behind having the coupling code in the directory meant for physics parameterizations.

2020-12-08 01:21 UTC, brian-eaton commented on src/dynamics/se/dyn_comp.F90
> +!                  call shr_sys_flush(6)
This output only occurs before endrun is called.  It is more sanity check than debug code.  So seems like good info to put in the log file.  Rather than commenting them out the hardcoded unit 6 should be changed to iulog, and the XXG changed to something like 'file lat not correct on task', and add text describing the other output data.

2020-12-08 05:09 UTC, gold2718 commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
@brian-eaton, phys_grid.F90 does a lot more than dynamics-physics coupling. It is also the home to defining the cam_grid information for history output from physics code. With the ionosphere PR, it also becomes the center for regridding from physics to the ionosphere and for other uses, such as inline regridding of emissions data onto the physics grid.
Also, while I agree that physics/cam is not a great place, that will be reformed as the physics becomes CCPP-ized and moves into its own repository.

Finally, only two of the files are about the new infrastructure, the others are temporary until all dycores use this interface.

How about `new_phys_grid` or `physics_infrastructure`? `improved_scaling` is okay as well. Consensus? Feedback on the suggestion to move it up a level (to `src` instead of in `src/physics`)?

2020-12-08 15:03 UTC, fvitt commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
I like "src/physics/infrastructure"  or "src/physics_infrastructure"

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
What is meant by "mixed layer"?  Is this exclusively for energy conservation checks?  Are other parts of the code using this utility to calculate global means?

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +            arr_gmean(fld_ind) = arr_gmean(fld_ind) / (4.0 * pi)
Any reason to not multiply by inv4pi rather than divide by (4.0*pi)?

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +         end do
Is this reproducible if PE layout does not change?

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +   subroutine test_gmean(max_diff)
Do you have a stand-alone unit test for gmean?

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +!!XXgoldyXX: v remove once new algorithm is in place
Is the new algorithm in place?  Is this stuff ready to remove?

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +   private :: test_gmean
How is this used if it is private?

2020-12-08 15:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +!!XXgoldyXX: ^ remove once new algorithm is in place
Ready to remove?

2020-12-08 15:59 UTC, brian-eaton commented on doc/ChangeLog
> + - Add weak scaling directory to override several files (see below)
Because it's coupling between dynamics and physics, or physics and ionosphere, I like having the directory at the same level as those 3 rather than inside physics.  Calling the directory "infrastructure" would be OK.  MPAS has a directory called "framework" which is similar.  We have a lot of infrastructure type stuff in control/ and utils/ as well which could eventually migrate.  Anything we do at this point will not be entirely consistent with the historical evolution of our directory structure, but that's OK.

2020-12-08 23:50 UTC, brian-eaton commented on src/cpl/mct/atm_comp_mct.F90
> +       end if
I don't see why any changes are needed in this module.  The number of global columns in the physics grid doesn't depend on the coupling algorithm.  Why can't this number come from both versions of phys_grid the same way, i.e., why can't phys_grid::ngcols always be used?

2020-12-09 00:21 UTC, brian-eaton commented on bld/configure
> +n     -fopt <string>     A string of user specified Fortran compiler optimization flags.
The 'n' in column 1 snuck in somehow.

2020-12-09 00:23 UTC, brian-eaton commented on bld/configure
> +    "weak_scale_fix"            => \$opts{'weak_scale_fix'},
Do we want to leave this as a user settable option?  We decided not to allow it for SE.  I think we should do the same for MPAS and FV3.

2020-12-09 01:51 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +            arr_gmean(fld_ind) = arr_gmean(fld_ind) / (4.0 * pi)
This is hopefully temporary. This code is BFB with the baselines, multiplying by `inv4pi` was not.
In order to get this code in, we decided to go with the BFB version and introduce the faster, scalable version in the future.

2020-12-09 01:54 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +         end do
It should be although the MPI standard does not guarantee that the `MPI_allreduce` call will always return the same sum (the network could end up doing the sum in a different order if you end up on different nodes).
All my tests have at most roundoff differences with a PE change -- I did not try repeatedly running one layout to see if it ever varies.

2020-12-09 01:56 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   subroutine test_gmean(max_diff)
Not currently. I tested it by inserting calls in the init code.
We will have an easier-to-use unit test system in the new infrastructure.

2020-12-09 01:57 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +!!XXgoldyXX: v remove once new algorithm is in place
No. See note above about getting this PR pushed out to allow MPAS-A to begin converting.
This will be done later (or maybe removed entirely if we decide to abandon the notion of BFB runs for high-resolution configurations).

2020-12-09 01:58 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   private :: test_gmean
With code insertion (see note above about how it was used).
I left the code in so that we can use it when we have easier-to setup unit tests.

2020-12-09 01:58 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +!!XXgoldyXX: ^ remove once new algorithm is in place
Nope.

2020-12-09 06:23 UTC, gold2718 commented on bld/configure
> +    "weak_scale_fix"            => \$opts{'weak_scale_fix'},
@PeterHjortLauritzen, what do you think? After this PR, the SE dycore will always use the new infrastructure.
Should we just do the same thing each time we convert a dycore?

2020-12-09 15:03 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +         end do
The potential for simulation results that are not reproducible does not seem right.

2020-12-09 16:02 UTC, PeterHjortLauritzen commented on bld/configure
> +    "weak_scale_fix"            => \$opts{'weak_scale_fix'},
Yes I think that is what we agreed on in the AMP projects meeting

2020-12-09 16:03 UTC, PeterHjortLauritzen commented on bld/configure
> +    "weak_scale_fix"            => \$opts{'weak_scale_fix'},
Yes I think that is what we agreed on in the AMP projects meeting.

2020-12-09 19:46 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
The comments in src/utils/gmean_mod.F90 indicate that the code originated from SOM, in which case the mixed layer refers to the ocean.  Just a case of old comments not being updated.

Doing a global search on 'call gmean' indicates that the primary purpose of the code is for diagnostics and the check_energy code.  There's also some use in chemistry.  The use of gmean in the check_energy code would cause answers to depend on task count if the means were not calculated in a task independent way.  Since CAM is currently giving task count independent answers I have to assume that src/utils/gmean_mod.F90 is working as designed.  But what's not clear is whether a call to gmean is relying on the non-scalable calculation to achieve this result.  The current implementation is that a scalable algorithm is used first (shr_reprosum_calc called from gmean_fixed_repro), and the scalable algorithm makes an error estimate which is subsequently used to decide whether the non-scalable (but always task count independent) calculation should be used.  However, as far as I can tell the check of the error estimate is not done because shr_reprosum_reldiffmax defaults to -1.0.  So it appears that the current scalable code is being used and is producing task count independent results.  @gold2718, did you come to a different conclusion after examining the current gmean_mod.F90?

2020-12-10 21:54 UTC, cacraigucar commented on src/physics/weak_scaling/cam_comp.F90
> +   call gmean_init(pcnst) !!XXgoldyXX: Is that a good value to use?
Right now, this is the only line that is different from the standard cam_comp.F90 routine.  Instead of copying this routine in its entirety to just add this one line, couldn't we hide if with #ifdef for weak_scaling.  I believe this is one of the limited times when a #ifdef is valid.  Alternatively, there could be an empty gmean_init routine for non-weak scaling cases.  Curious why you took the approach of copying the entire cam_comp.F90 to insert this one line.

2020-12-11 16:06 UTC, fvitt commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED
Will these be removed?

2020-12-11 16:07 UTC, fvitt commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ debug only
Should this be removed?

2020-12-11 17:52 UTC, cacraigucar commented
@gold2718 Have you found the updated file(s) that you thought was(were) committed?  It would be good to get them updated ASAP.

2020-12-11 18:45 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +         end do
After spending more time looking at both the gmean_mod.F90 in src/utils/ and the new one in weak_scaling/ I find that I don't understand what problem the new version is trying to solve.  The issue comments indicate that a scalable version is the goal, but the current code already provides both scalable and non-scalable versions.  CAM is currently set up to use the scalable version which is also reproducible.

If I'm missing what's going on and the new code is improving gmean_mod, then I think it should be implemented in shr_reprosum_mod.F90.  The code there originally came from CAM, but was moved so that all components had access to scalable reproducible sums.  I don't think we should be making improvements to those algorithms in a CAM specific location.

2020-12-11 19:38 UTC, brian-eaton commented on src/dynamics/se/interp_mod.F90
> +    deallocate(fld_dyn)
I agree.  This deallocate is misplaced.

2020-12-11 19:45 UTC, brian-eaton commented on src/dynamics/se/interp_mod.F90
> +    deallocate(fld_dyn)
Which makes me think this code isn't being tested by our regression tests.  I know people often use the interpolated output with SE rather than deal with native grid output, so interpolated output should be added to an SE test.

2020-12-11 20:32 UTC, brian-eaton commented on src/dynamics/se/interp_mod.F90
> +       end if
This code isn't needed.  local_dp_map is hardcoded to .true. in spmd_dyn.  Same comment for the version below at line 463.

2020-12-11 20:41 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED
Yeah, I could swear I did that but obviously, it did not make its way to the PR. I will clean up this file.

2020-12-11 21:45 UTC, nusbaume reviewed
My first round of reviews.  Hope they are helpful (and don't show too much of my own ignorance)!

2020-12-13 18:11 UTC, gold2718 commented on src/dynamics/se/interp_mod.F90
> +       end if
@brian-eaton , I do not consider a public module variable to be "hardcoded". Do you want me to change that to `protected` or `parameter`?

2020-12-13 18:20 UTC, gold2718 commented on src/physics/weak_scaling/cam_comp.F90
> +   call gmean_init(pcnst) !!XXgoldyXX: Is that a good value to use?
There is no `#ifdef` for weak scaling but an empty routine could be added to the non-weak-scaling gmean_mod.
As for reasons, I suppose at the time, I did not know what the full impact would be.

2020-12-13 18:27 UTC, gold2718 commented on src/physics/cam/phys_debug_util.F90
> +              dist = 0.0_r8
Done (but down below to avoid code duplication).

2020-12-14 02:30 UTC, gold2718 commented on test/system/test_driver.sh
> +    ## If this is a Nag test, run the r8 and git tests
[Done](https://github.com/NCAR/CAM/wiki/CAM-SE-Workflows#run-cam-tests)

2020-12-14 02:31 UTC, gold2718 commented on src/cpl/mct/atm_comp_mct.F90
> +  save
Nope (implied at module scope).

2020-12-14 02:55 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ debug only
Yes, thanks for noticing.

2020-12-14 02:56 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED
There is still a block of comments but hopefully it is a bit more clear as to how these interfaces need to be treated down the road.

2020-12-14 02:57 UTC, gold2718 commented on src/utils/cam_abortutils.F90
> +      character(len=256)           :: errmsg
Probably.

2020-12-14 02:57 UTC, gold2718 commented on src/utils/cam_abortutils.F90
> +      character(len=256)           :: errmsg
Probably.

2020-12-14 02:57 UTC, gold2718 commented on src/utils/cam_map_utils.F90
> +    character(len=256)            :: errmsg
Probably.

2020-12-14 02:58 UTC, gold2718 commented on src/physics/cam/phys_control.F90
> +   if ( present(cam_repro_sum_out       ) ) cam_repro_sum_out = cam_repro_sum
I'm not a big liner-upper but I will line up the right parentheses (which is what I think you meant).

2020-12-14 03:07 UTC, gold2718 commented on src/physics/cam/phys_debug_util.F90
> +   if ((abs(latmin) > maxlat) .or. (lat > maxlat)) then
`maxlat < pi / 2` so it is possible for `lat > maxlat`, just not very likely

2020-12-14 03:27 UTC, gold2718 commented on src/utils/spmd_utils.F90
> +   type(spmd_col_trans), public, protected :: spmd_col_trans_mpi_type
Or even better, use the correct data type (`spmd_col_trans_mpi_type` is a special handle to an MPI derived type which is not the same thing as a Fortran DDT).

2020-12-14 03:29 UTC, gold2718 commented on src/utils/spmd_utils.F90
> +     h1 = h1 + 1
Well sure but then, it is too easy to mess up the offsets when creating MPI derived types. I would prefer safety over looks here, especially since this is only done once at startup.

2020-12-14 03:37 UTC, gold2718 commented on src/utils/gmean_mod.F90
> +      character(len=256)          :: errmsg
Okay

2020-12-14 03:39 UTC, gold2718 commented on src/physics/weak_scaling/cam_comp.F90
> +! or atm_comp_esmf, which translates between CAM and either MCT or ESMF
I think it was the old ESMF interface (the one that pasted ESMF interfaces on top of the MCT code).
Fixed.

2020-12-14 03:47 UTC, gold2718 commented on src/physics/weak_scaling/cam_comp.F90
> +   end if
Hmm. According to `svn blame`, this was put in by Pat Worley in 2006.
@brian-eaton, any idea if these calls are needed?

2020-12-14 03:51 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED FOR WEAK SCALING
I can't take these out yet since there is code in src/physics/cam which will not compile without these interfaces.
They all call `endrun` but until we clean up those files or improve our directory structure, or just outgrow the problem, these will have to stay :-(

2020-12-14 03:52 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   !!
Nope.

2020-12-14 03:52 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +!      use mpi,              only: MPI_reduce ! XXgoldyXX: Should this work?
Or maybe someone tell me why this does not work in 2020?

2020-12-14 03:53 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED FOR WEAK SCALING
My momma always said don't assume because then you  . . . oh nevermind, I'll just take it out :-)

2020-12-14 03:57 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +            end if
You have greater confidence in your counting skills than I do in mine.
That being said, this might have been useful in an earlier version of this block.

2020-12-14 04:04 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +           unstructured) then
Sounds like a good idea.

2020-12-14 04:08 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +      nullify(grid_map)
Nope, the data lives on in the grid's map structure (which is what the comment above means). Nullifying the local pointers ensures that we do not mess that up.

2020-12-14 04:31 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   real(r8) function get_dlon_p(index)
I guess I thought I would need an `index` interface (which is what `get_dlat_p` and `get_dlon_p` are).
Turns out I do not need those but I went ahead and implemented all the degrees interfaces (will be used at some point).

2020-12-14 04:32 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +      ! getrlat_all_p: Return all latitudes (in radians) for chunk, <lcid>
Fixed

2020-12-14 04:33 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   subroutine get_rlat_all_p(lcid, rlatdim, rlats)
That check happens in the `chunk_info_to_index_p` call.

2020-12-14 04:35 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   integer function get_gcol_p(lcid, col)
Nope, probably just neglected to update it once I wrote `chunk_info_to_index_p` to encapsulate all those checks.

2020-12-14 04:39 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +      index = chunk_info_to_index_p(lcid, col)
Dunno, no one calls this interface yet. I added it as an optional argument.

2020-12-14 04:40 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   end subroutine dyn_decomp_to_phys
Done.

2020-12-14 05:19 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   real(r8) function get_dlon_p(index)
I thought I would need `index` interfaces (what `get_dlat_p` and `get_dlon_p` are) but I guess not so I've removed them.

There were never degree interfaces and the routines, I can add them if they are needed.

2020-12-14 05:39 UTC, gold2718 commented on src/physics/cam/phys_debug_util.F90
> +                dist = 2.0_r8 * asin((temp1*temp1) + (cos(latmin)*cos(lat)*temp2*temp2))
I'm sure I started with the correct formula on paper but now have no idea how I came up with this one so I set it back to the standard definition.

2020-12-14 16:40 UTC, brian-eaton commented on src/dynamics/se/interp_mod.F90
> +       end if
I meant "hardcoded" in the sense that local_dp_map=.true. is set in spmd_dyn, and not changed anywhere in the SE weak scaling code.  In the original code phys_grid is responsible for setting local_dp_map based on the phys_loadbalance setting.  The weak_scaling version of phys_grid ignores the phys_loadbalance setting, so the value is effectively hardcoded to true.  I find the code in question to be confusing because when I see a check I assume it's possible that the condition being checked can occur.  In this case it can't, but the code reader needs to spend time to verify that (at least I did).

2020-12-14 16:51 UTC, brian-eaton commented on src/cpl/mct/atm_comp_mct.F90
> +  save
Steve, I thought the save attribute was only implied for module variables that have an initializer.  No?

2020-12-14 18:48 UTC, brian-eaton commented on src/physics/cam/phys_grid.F90
> +    use shr_mem_mod,      only: shr_mem_getusage
I think the memory analysis code in this module should be removed since it's for development only.

2020-12-14 19:40 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED FOR WEAK SCALING
I don't understand why the get_*_p routines aren't compatible with weak scaling.  Their interface indicates they are meant to return values for the chunks in the local task, i.e., lcid is the local chunk id which ranges from begchunk to endchunk.  So global data isn't required to support this. True, the currently implementation makes use of the global chunks array since it is available.  But the lat/lon indicies could easily be put in the local lchunks array during phys_grid_init.

2020-12-15 19:19 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED
I see that there are still a few calls to get_horiz_grid_d in places where there is no conditional logic to restrict the calls to rectangular grids, i.e., in src/ionosphere/waccmx/ionosphere_interface.F90 and in src/physics/carma/models/meteor_impact/carma_model_mod.F90.  Are these physics configurations not supported for the SE dycore?

2020-12-15 19:28 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> -type(block_global_data), allocatable :: gblocks(:)
The definition of type(block_global_data) should also be removed.

2020-12-15 19:49 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +      call get_horiz_grid_int(ngcols_d, clat_d_out=clat, clon_d_out=clon, area_d_out=areaA)
Are the native mapping files still used?  It seems like this functionality has been superseded by the ESMF remapping tools.  Maybe this whole conditional can go away.  @PeterHjortLauritzen what do you think?

2020-12-15 21:40 UTC, gold2718 commented on src/cpl/mct/atm_comp_mct.F90
> +  save
That used to be true but no compiler ever implemented any module variable non-saving so they made it official in the 2008 standard that all data objects at module scope have the `save` attribute.

2020-12-15 22:40 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +      hdim1_d = nelem * fv_nphys * fv_nphys
Why duplicate this code rather than use a call to get_horiz_grid_dim_d?

2020-12-15 23:01 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +   call endrun('dyn_grid_get_colndx: not implemented for unstructured grids')
This routine is called by the sat_hist module.  It looks like the old code supported the GLL grid, but not the FVM grid.  Now the routine doesn't support either.  Does this mean that it's no longer possible to have sathist output with SE?

2020-12-15 23:53 UTC, brian-eaton commented on src/dynamics/se/dp_coupling.F90
> +   end if
The endrun call is not necessary since local_dp_map is always true in the weak scaling code.  I think it would be better to replace this by a comment to indicate that the current version of weak scaling does not support load balancing.

2020-12-17 23:35 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +!      use mpi,              only: MPI_reduce ! XXgoldyXX: Should this work?
It works on my home desktop using gnu.

I don't quite understand how it works without the 'use mpi' statement:)  This is also true for the mpi_bcast calls in phys_grid_readnl.

2020-12-18 00:43 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +type(physics_column_t), pointer :: local_dyn_columns(:) => NULL()
Is there a reason for this to be a pointer?  It seems that this is the persistent storage for the local column info, and that it would be better declared allocatable.

2020-12-18 02:31 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +type(physics_column_t), pointer :: local_dyn_columns(:) => NULL()
My thinking was that I do not want to restrict dycore writers to have their columns start at `1`. This is similar to physics with columns from `begchunk` to `endchunk`.
However, in this case, it could just as easily have been written:
```
   type(physics_column_t), allocatable, target :: local_dyn_columns(:) 
```
I'm happy to change that but would like to hear why you think this is "better".

2020-12-18 03:44 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +      hdim1_d = nelem * fv_nphys * fv_nphys
I would like to deprecate `get_horiz_grid_dim_d`, it should never be called outside of a dycore.
Even under the current regime, only `phys_grid_init` should have ever called it. All the other uses in the physics and chemistry code are incorrect and have caused a lot of problems.
That being said, I agree that this calculation should be done in one place. I will remove this function once the nudging and ionosphere PRs are in.

2020-12-18 04:33 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
@brian-eaton, I had not noticed the settings of `shr_reprosum_reldiffmax` and `shr_reprosum_recompute`.
Not only is `shr_reprosum_reldiffmax` set to `-1.0` (which means do not make an estimate) but `shr_reprosum_recompute` is set to `.false.` meaning that **even if the reprosum fails, CAM uses the answer anyway!**

It looks to me that while our global means are reproducible, we have no idea if they are correct. Ouch!

Unless you know this is not happening, I am going to throw in some tests to see how we are doing.

2020-12-18 18:39 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +type(physics_column_t), pointer :: local_dyn_columns(:) => NULL()
I don't see the need to allow the local_dyn_columns arrays to have start indices other than 1.  We currently support 5 dycores, and none of them will use that capability.  It adds complexity to the phys_grid_init code and doesn't seem to have an offsetting benefit.

Now I understand (I think) the motivation behind the use of the pointer attribute, i.e., so that the array bounds get passed along through interfaces.  I personally prefer the use of allocatable arrays because when I see one I know where the memory is being allocated. When I see a pointer, on the other hand, I'm never quite sure who's in charge of the memory management.  For example I have found that to be a confusing part of the grid and mapping object code which has tripped me up many times; i.e., should I deallocate this pointer or just nullify it?  The complexity of using pointers is also evident in the new phys_grid_init routine.  There is an explicit comment to explain that the dyn_columns pointer should be nullified and not deallocated.  The use of allocatable arrays that are just passed through argument lists as arrays avoids this confusion.

2020-12-18 19:04 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +      hdim1_d = nelem * fv_nphys * fv_nphys
If you deprecate get_horiz_grid_dim_d how do you plan to supply atm_nx and atm_ny to the seq_infodata_putdata call in atm_init_mct?  This info could be stored in phys_grid and accessed via an interface there.  But it doesn't bother me to have it come from a dyn_grid interface.  The dycore is the 'expert' here.  It determines the physics grid.  phys_grid is only responsible for the physics decomposition of that grid.

2020-12-18 19:16 UTC, brian-eaton commented on src/physics/weak_scaling/cam_comp.F90
> +   end if
Looks to me like old dead code that should be removed.

2020-12-18 19:18 UTC, brian-eaton commented on src/physics/weak_scaling/cam_comp.F90
> +   end if
More old dead code to remove.

2020-12-18 22:54 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
I believe the default settings in shr_reprosum_mod came from Pat Worley.  I assume that when Pat and other DOE folks implemented and tested this code they found that the algorithm in shr_reprosum_int worked well enough that there was no need to go to the expense of producing the error estimate in the default mode of running.  The error estimate is made by redoing the sum using mpi_allreduce (so not reproducible, but an independent estimate) and comparing that with the results from shr_reprosum_int.

The thing that makes shr_reprosum_int susceptible to error is that the reproducibility is obtained by converting the floating point values to integer representations, and doing the mpi_allreduce on the integers.  Then you convert back to floating point.  I'm not familiar with the algorithmic details, but depending on the properties of the floats I imagine there could be pathologies when converting to integers.  My guess as to why this scheme works well for this application is that the sums involve values that are all positive, e.g., energy of a column or the mass of a constituent in a column.

2020-12-21 06:12 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
The tests I have been running are telling me is that `shr_reprosum` is pretty good if given positive-definite fields, even with a fairly high dynamic range.
However, it is easy to mess with if you give it inputs that gyrate around zero and end up with a small result (compared to the size of the gyrations). In these situations, it computes incorrect answers and is not even reproducible.
Since we are currently using `gmean` on non-negative fields and are not checking whether or not `shr_reprosum` is working, I propose the following steps to resolve this issue:

- Replace the unused safety-net (the backup algorithm which is not used because we do not check) with a call to `endrun`
- Always use `shr_reprosum` (i.e., remove the new `cam_repro_sum` namelist variable I introduced).
- Turn on the `shr_reprosum` check for CAM regression tests. This is to prevent a future use of `gmean` on oscillating fields.

Thoughts? @brian-eaton? @fvitt?

2020-12-21 16:48 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
@gold2718, your proposal seems reasonable to me.

2020-12-21 17:32 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
The case of nearly equal numbers of opposite sign summing to a smaller result is how significant figures are lost.  This causes errors with floating point results as well as with the shr_reprosum_int scheme.  But I don't understand how that case causes reproducibility failures, since the reproducibility is a property of the integer sums.  Do you have any ideas why you get that result?

I think turning on the tolerance check for some regression tests is a good idea.  But rather than replace the call to gmean_float_repro with an endrun call, if that's what you're proposing, I would prefer to leave that call in place so we could then print the values from both summing methods before calling endrun.   It would be useful to have the relevent information for the field that's causing the failure.  It may be that that's the only info we'd need to possibly just adjust the test by loosening the reprosum_diffmax value just a bit.  Or perhaps we'd see a catastrophic failure which needed further investigation.  It could be an indicator that the field contains bad values.

2020-12-21 18:42 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
I have not been able to reproduce my not-reproduced runs so maybe I misread a run (one run had last three digits of 000 vs. most show last three digits of 009).

As for putting in the backup method for diagnostic purposes, the choices I have now are:

- Scalable but not reproducible version
- Reproducible but not scalable version

Which one do you prefer? BTW, the `shr_reprosum` check uses the scalable but not reproducible sum (`allreduce`) for its check value.

2020-12-21 19:33 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
My initial thought was to just use the gmean_float_repro call that's already in place.  But now that you mention it, it probably would be better to use a scalable but not reproducible calc which would be consistent with how the error estimate is made.

2020-12-23 03:35 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
Well, this is interesting. Adding that check causes several FV tests to fail to restart and to fail baselines. The main culprit seems to be calls to `par_xsum`. The errors are not huge but I wonder if we should look into them. For now, I am just going to remove the check for those tests (nothing to see here folks, move along) but for the record, they are:

- ERC_D_Ln9.f10_f10_mg37.QPC4.izumi_pgi.cam-outfrq3s_diags
- ERC_D_Ln9.f10_f10_mg37.QPC4X.izumi_nag.cam-outfrq3s_newyear
- ERC_D_Ln9.f10_f10_mg37.QPC6.izumi_nag.cam-outfrq3s_am
- ERC_D_Ln9.f10_f10_mg37.QPC6.izumi_nag.cam-outfrq3s_cospsathist
- ERC_D_Ln9.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s
- ERI_D_Ln18.ne5_ne5_mg37.FADIAB.izumi_nag.cam-outfrq3s_bwic

The good news is that `par_xsum` checks the result (if checks are on) and does have a backup algorithm. Other uses, such as `lightning_no_prod` in mo_lightning.F90 have no check.

Any thoughts on what we should do about these? @brian-eaton, @fvitt, @cacraigucar?

2020-12-23 03:38 UTC, gold2718 commented on src/dynamics/se/interp_mod.F90
> +    deallocate(fld_dyn)
I have added tests for interpolated output (from an SE run) and also zonal mean output (from an FV run). I did this by adding a new file to existing tests (see ChangeLog).

2020-12-23 03:44 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED
The ionosphere code currently only runs on FV. The call to `get_horiz_grid_d` is removed in #264 which also enables SE support by moving the coupling to the physics grid.

On the other hand, CARMA is a hot mess. I do not know if anyone has tried it with SE but I would be surprised if it ever ran on an unstructured dycore. There has been talk (from ACOM folks) of reimplementing CARMA but I have not heard from them for a few months.

2020-12-23 03:46 UTC, gold2718 commented on src/dynamics/se/interp_mod.F90
> +       end if
I like to put checks in if a situation can be caused without looking carefully. If anyone ever did try to set `local_dp_map` to `.false.` (which can be done from anywhere), this check will be triggered.

2020-12-23 03:53 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +!      use mpi,              only: MPI_reduce ! XXgoldyXX: Should this work?
What happens depends on the compiler. The Nag MPI library only supports the old F77 MPI interfaces so they don't have interfaces for the routines which is why we have `<cime_root>/config/cesm/machines/nag_mpi_argument.txt` to deal with the overloading error messages.

2020-12-23 03:58 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> -type(block_global_data), allocatable :: gblocks(:)
Yep, thanks for noticing.

2020-12-23 05:27 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +type(physics_column_t), pointer :: local_dyn_columns(:) => NULL()
What should the interface to `get_dyn_grid_info` be for the output array, `dyn_columns`? Ideally, if it is an `allocatable` array, what should its `intent` be?
`in` and `inout` do not make sense because the caller does not know what size the arrays should be.
For an `intent(out)` array, `get_dyn_grid_info` will have to allocate a copy to pass back meaning there is an extra copy. This will increase the memory used by `phys_grid_init`, unless it just uses that array or until it can `deallocate` it (currently where the `nullify` statement is).
How much memory? At the moment, it looks like about 10-11 2-D fields depending on the dycore (i.e., not a lot).
Is that the way to go?

- `get_dyn_grid_info` creates a copy of its columns in the output variable, `dyn_columns`.
- The caller (`phys_grid_init`) will copy this data into its internal data structures, then deallocate that array.

Is this a better approach?

2020-12-23 14:55 UTC, gold2718 commented on src/dynamics/se/dyn_grid.F90
> +type(physics_column_t), pointer :: local_dyn_columns(:) => NULL()
I think I know what is bugging me about this. Because the dycore is in charge of defining the physics grid, it should just call `phys_grid_init`. This would require all physics and chemistry code to use interfaces in phys_grid but that is a good thing as it simplifies the public interfaces that a dycore must support.

In this case, it would make the whole problem of this array go away and also allow us to drop the `physgrid_copy_attributes_d` callback function since the appropriate attributes would just be passed to `phys_grid_init`.

I think I will probably head in that direction (not for this PR obviously).

2020-12-23 17:39 UTC, fvitt commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
For the case of mo_lightning, shr_reprosum_calc is used to compute diagnostics only so there may not be too much concern on the accuracy.  The global sums are computed on non-negative quantities.  The diagnostics seem to be independent of number of MPI tasks.  So we may be getting the same wrong answers when changing PE layout.

2020-12-23 18:22 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
Steve, what value did you use for reprosum_diffmax?  And what were the means computed by the reprosum calc and allreduce code for, say, the worst case?

Francis, I wouldn't expect there to be any significant error for a non-negative fields.  But if you want to check you could add the optional arg rel_diff to the shr_reprosum_calc calls.  To get the rel_diff values you also need to set the reprosum_diffmax namelist variable to some positive value.

2020-12-23 18:36 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED
I'm aware of the CARMA resurrection efforts which is why I wanted to keep it on our radar.  The use of get_horiz_grid_d in the CARMA code is minimal, and could easily be updated to just use info in the local chunks and then shr_reprosum_calc to compute the area of interest.

2020-12-23 18:45 UTC, brian-eaton commented on src/dynamics/se/interp_mod.F90
> +       end if
It's not possible to bulletproof the code against user source mods.  When attempting to do so makes the code harder to read then to me the hypothetical benefit is outweighed by the real downside.

2020-12-23 20:54 UTC, brian-eaton commented on src/dynamics/se/dyn_grid.F90
> +type(physics_column_t), pointer :: local_dyn_columns(:) => NULL()
What I had in mind is basically what you propose above to have get_dyn_grid_info copy the module array local_dyn_columns to the output array dyn_columns.  But I view the get_dyn_* routines as accessor routines.  So I would compute the number of local columns and assign the local_dyn_columns during dyn_grid_init.  Then phys_grid_init can query the number of local columns and allocate the actual dyn_columns array before calling get_dyn_grid_info which then just does the access.

I think it makes sense to have dyn_grid_init call phys_grid_init directly.  That's the same order as things are done now with the call to phys_grid_init right after the call to dyn_grid_init in cam_init.

2020-12-24 00:40 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
First, some of the baseline diffs were as high as `5.E-01` although for not-so-small absolute values, it still got to `1.7E-01`.
I used `reprosum_diffmax=1.0e-14`

I do not see either the value computed or the backup value computed by `par_xsum`. The output looks something like:
```
 par_xsum: difference in fixed and floating point sums  exceeds tolerance in  71  fields.
   Maximum relative diff: (rel)   0.9694656488549618  (abs)    2.8876456781290472E-11
   Maximum absolute diff: (rel)   6.9519501266768202E-11  (abs)    6.9519501266768202E-11
```
`par_xsum` does not use allreduce, it has some other reproducible algorithm.

2020-12-24 00:55 UTC, brian-eaton reviewed
A few more nits.

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +
There should be a description here of what this module is responsible for.  It should include info about what the physics decomposition is. It would be helpful to point out that the physics grid is defined by the dycore, and the information about the physics grid on the dynamics decomposition is provided by the dyn_grid module.

This would also be a good place to note that the physics load balancing options in the original code have not yet been re-implemented in this weak scaling version.  

In this weak scaling version the physics chunks contain the same columns as the dynamics blocks in each task.  That implies there is no support for running with more tasks for the physics package than for the dycore.  That should also be noted here.

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +   character(len=8), protected, public :: dycore_name = ''
dycore_name is set but not used.  Isn't function dycore_is sufficient for conditionals needing to know the specific dycore or dycore grid type?

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +   integer,     protected, public :: phys_global_max_fields = -1
This variable isn't used in this module.  Why is it in the phys_grid_nl namelist group?

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +      integer, private :: chunk_index    = -1  ! Local index of this chunk
The chunk_index component doesn't seem to be used for anything.  Is it needed?

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +      integer, private, allocatable :: phys_cols(:) ! phys column indices
Should clarify that these indices are local to the columns in the task.

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +   integer,          protected, public :: index_bottom_interface = 0
These variables are set but not used.  What are they for?

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +      num_global_phys_cols = hdim1_d * hdim2_d
hdim1_d and hdim2_d are set by dyn_grid which is the 'expert' regarding size of the global physics grid.  Those values are passed to the coupler via a call to seq_infodata_putdata.  It makes sense to always use them to compute the number of columns in the global physics grid.

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +      unstructured = hdim2_d <= 1
The dycore_is function provides info about whether the grid is unstructured or not.

2020-12-24 00:55 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +         if (columns_on_task /= col_index) then
Reusing the variable col_index for the quantity last_dyn_column-first_dyn_column+1 makes the code hard to read.  That quantity is not an index.

since first_dyn_column and last_dyn_column are set to lbound and ubound of dyn_columns, how is it possible for col_index not to equal size(dyn_columns)?

2020-12-24 06:16 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +
Regarding nits, please let me know when you are done.

2020-12-24 06:21 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   character(len=8), protected, public :: dycore_name = ''
IMHO, `dycore_is` should go away and be replaced with properties. For instance, in the geopotential routines, the issue is not so much the type of dycore as the type of vertical coordinate (e.g., lagrangian vertical coordinate).
As for the name, I was planning on using it to log messages -- I'll think about whether or not that is still likely to be true.

2020-12-24 06:22 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   integer,     protected, public :: phys_global_max_fields = -1
Long story but not worth retelling because it is going away with the new plan.

2020-12-24 06:23 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +      integer, private :: chunk_index    = -1  ! Local index of this chunk
It will be when load balancing goes in.

2020-12-24 06:30 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +   integer,          protected, public :: index_bottom_interface = 0
That's CCPP stuff, will be used soon.

2020-12-24 06:36 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +      num_global_phys_cols = hdim1_d * hdim2_d
While it is true that the info comes from the dycore, I have two issues with code other than the dycore and phys_grid using it directly.

- Since the SE physgrid showed up, I have run into confused users (and even an SE or two) because the dycore interfaces are no longer reporting dycore quantities but are reporting physics quantities.
- In order to allow for increasing modularity of CAM, I want all physics, chemistry, and driver code to get information from phys_grid (see the new atm_comp_mct.F90 coming soon to this PR).

2020-12-24 06:36 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +      unstructured = hdim2_d <= 1
See note above about `dycore_is`.

2020-12-24 06:36 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +         if (columns_on_task /= col_index) then
It's actually a bit worse than that. Fixed in next push.

2020-12-24 17:00 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +   character(len=8), protected, public :: dycore_name = ''
I agree a more general properties module would be good.  That could include a function to provide the dycore name for log messages.  But not needed for this commit.

2020-12-24 17:23 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +      num_global_phys_cols = hdim1_d * hdim2_d
I'm not opposed to having phys_grid query dyn_grid for the size of the global physics grid, expressed as hdim1_d and hdim2_d, and to be responsible for providing that information to the coupling layer.  What I was responding to with my comment is that the code comment makes it sound like it was just a lucky coincidence that hdim1_d*hdim2_d was the number of global physics columns, even for SE/CSLAM. But this will always be true regardless of which module is made responsible for providing that info, at least as long as the driver code expects the grid to be characterized that way.

2020-12-24 17:25 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +      unstructured = hdim2_d <= 1
But, the new properties module is not yet implemented, so dycore_is should be used until that time.

2020-12-24 17:27 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +
I'm feeling pretty done:)

2020-12-24 17:44 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED FOR WEAK SCALING
The problem is that the current interfaces for those routines are *not* returning a latitude in degrees but rather an index which does not make sense in the new infrastructure. This is used by routines such as polar_avg.F90 which is stuck in the src/physics/cam junk drawer along with all the good knives and silverware.
If I implement the obvious meaning of, for example, `get_lat_p`, polar_avg will not compile. I can:
- Implement them and move polar_avg (and other offenders) to a new directory (e.g., src/physics/old)
- Hold off on implementing them until we need them and can cleanup all the old-style code.

What do you think? If you go for the rename, what is your naming choice?

2020-12-24 19:10 UTC, gold2718 commented on src/physics/weak_scaling/phys_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED FOR WEAK SCALING
Nevermind, there are still too many connections back to physpkg and I do not want to make another copy of physpkg. I need to fulfill those interfaces and an `endrun` call makes sure they are never called for SE.

2020-12-24 19:38 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
I'm not quite understanding the par_xsum output.  I think to pursue those errors you'd need to set up par_xsum the same way we discussed setting up gmean so that when the error tolerance is exceeded we print the means from both estimates and call endrun.

Did you see any failures related to gmean calls?  1.e-14 is a pretty tight tolerance.

2020-12-24 20:44 UTC, gold2718 commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
That output is from the `shr_reprosum_calc` calls made by `par_xsum`.  The `(abs)` numbers are just `abs(fast - allreduce)` while the `(rel)` numbers are `abs(fast - allreduce) / abs(allreduce)` (unless `abs(allreduce)` is too small in which case `(rel)` is just `(abs)`).
- "Maximum relative diff" is the case (out of the 71 listed above) which had the largest `(rel)` value.
- "Maximum absolute diff" is the case (out of the 71 listed above) which had the largest `(abs)` value.

To get an idea of the (absolute) value of the `allreduce` method, I would just look at `(abs) / (rel)` which gives `2.9786E-11` for the "Maximum relative diff" case (the absolute diff case did not compute a relative value since the absolute value was too small (abs(allreduce) <= abs(fast - allreduce)`).

I did not see any `gmean` errors which is expected because they are all summing non-negative values.

2020-12-24 23:09 UTC, brian-eaton commented on src/physics/weak_scaling/phys_grid.F90
> +!!XXgoldyXX: ^ MUST BE DELETED FOR WEAK SCALING
I'm not suggesting to address these issues now.  My comment is just to point out that the code comment, "MUST BE DELETED FOR WEAK SCALING" is incorrect with respect to the get_lat* and get_lon* routines.  I've looked at most of the places in the code where these routines are used and have only found one instance where the use was non-scalable, i.e., in some CARMA code that hasn't been updated for unstructured grids and is allocating a (plon,plat) array for holding boundary data.  But otherwise the use is in scalable code.  For example the polar_avg.F90 code which is only used for the FV dycore uses these global indices to identify the columns in a chunk which are on the latitude circles closest to the poles, i.e., indices 1 and plat.  The polar averages are computed using the scalable shr_reprosum_calc routine.

2020-12-25 00:04 UTC, brian-eaton commented on src/physics/weak_scaling/gmean_mod.F90
> +   !
It's hard to interpret relative errors when the values are so close to zero.  To be sure I'd still want to see the means computed by both methods.  But I think there's no need to pursue this.  When Pat Worley updated par_xsum to use the shr_reprosum_mod code he did plenty of testing.  Just for the record, here is part of the relevent ChangeLog history:

----------------------
Tag name: cam3_6_37
Originator(s): pworley
Date: Mon Apr 27 2009
One-line Summary: more accurate reproducible sum; additional OpenMP
parallelism.

Purpose of changes:

1) Modify repro_sum fixed-point algorithm to improve accuracy.
   In certain situations, numerical cancellation can degrade accuracy
   of original repro_sum algorithm as compared to floating-point-based
   algorithms. New algorithm is nearly exact, employing variable
   precision as needed. This results in roundoff level differences.
--------------------

The ChangeLog file contains a lot more details about the introduction of and improvements to the scalable reproducible sums code, going back to July 2008.

2020-12-28 17:19 UTC, fvitt commented on doc/ChangeLog
> + - Waxed poetic about modifying code
It this poetry?

2020-12-28 17:19 UTC, fvitt commented on bld/config_files/definition.xml
> +</entry>
It this configure option used?  It seems that the src/infrastructure code is always used when the dycore is SE.

2020-12-28 17:19 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_diags/user_nl_cam
> +fincl2='Uzm:I','Vzm:I','Wzm:I','THzm:I'
Is this only for a test that uses FV dycore?

2020-12-28 17:19 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_ttrac/user_nl_cam
> +fincl2='Q:I','T:I','U:I','V:I','Q_gll:I','T_gll:I','U_gll:I','V_gll:I'
Is this for an SE dycore test?

2020-12-28 17:30 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_ttrac/user_nl_cam
> +fincl2='Q:I','T:I','U:I','V:I','Q_gll:I','T_gll:I','U_gll:I','V_gll:I'
Yes, It turns out we had no regression tests for interpolated output. This just puts one in place. I just did a `cprnc` with the same mod to a cam6_3_006 run to decide it was okay.

2020-12-28 17:30 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_diags/user_nl_cam
> +fincl2='Uzm:I','Vzm:I','Wzm:I','THzm:I'
Yes, It turns out we had no regression tests for zonal mean output. This just puts one in place. I just did a `cprnc` with the same mod to a cam6_3_006 run to decide it was okay.

2020-12-28 17:31 UTC, gold2718 commented on bld/config_files/definition.xml
> +</entry>
Oops, I removed it in the last round and forgot to take it out here. Thanks for noticing.

2020-12-28 17:32 UTC, gold2718 commented on doc/ChangeLog
> + - Waxed poetic about modifying code
Everybody's a critic :-)

2020-12-28 17:33 UTC, gold2718 commented on src/utils/gmean_mod.F90
> +      test_mean(:) = -2.71828_r8 * pi
That's the idea, if some new version does not overwrite a value, I will be able to track down using a weird value. Not sure why I ended up with this one.

2020-12-28 17:35 UTC, gold2718 commented on src/utils/gmean_mod.F90
> +      ! Test 6: Large dynamic range (pattern 2)
One pattern is every other task while the other is top half vs. bottom half. The idea is that this is a way to make sure that load balancing does not affect the results by accidentally creating an easy case.

2020-12-28 17:58 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_diags/user_nl_cam
> +fincl2='Uzm:I','Vzm:I','Wzm:I','THzm:I'
There are waccm use case files that include these zonal mean history fields.  So these have been subject to regression tests.

2020-12-28 18:04 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_diags/user_nl_cam
> +fincl2='Uzm:I','Vzm:I','Wzm:I','THzm:I'
Okay, good to know (it's hard to search for that since there are many use case files that are not tested with regression tests). Do you think I should take out this new test?

2020-12-28 18:17 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_diags/user_nl_cam
> +fincl2='Uzm:I','Vzm:I','Wzm:I','THzm:I'
I guess it is okay to leave it as you have while keeping in mind that that outfrq3s_diags cannot be used with a different dycore.

2020-12-28 21:18 UTC, brian-eaton approved these changes

2020-12-29 20:47 UTC, gold2718 commented on doc/ChangeLog
> + - cam_repro_sum: Flag to enable reproducible sum
Thanks for that (and all your other comments -- even the nits :-)

2020-12-31 00:37 UTC, gold2718 commented on bld/configure
> +    "weak_scale_fix"            => \$opts{'weak_scale_fix'},
@PeterHjortLauritzen, @patcal, Just a reminder that because there is no option to turn off the new code, nudging will be broken in this tag. Perhaps we can prioritize #241?

2020-12-31 00:39 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_ttrac/user_nl_cam
> +fincl2='Q:I','T:I','U:I','V:I','Q_gll:I','T_gll:I','U_gll:I','V_gll:I'
@fvitt, Do you approve this PR with the changes we discussed in this latest round or are there other needed changes?

2020-12-31 01:48 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_ttrac/user_nl_cam
> +fincl2='Q:I','T:I','U:I','V:I','Q_gll:I','T_gll:I','U_gll:I','V_gll:I'
I don't have other changes.

2020-12-31 01:54 UTC, fvitt approved these changes
weak_scale_fix needs to be removed from config_files/definition.xml

2020-12-31 02:51 UTC, nusbaume approved these changes
Looks good to me now!  Just one grammar fix and a request for additional error checks.

2020-12-31 02:51 UTC, nusbaume commented on src/infrastructure/phys_grid.F90
> +   subroutine get_rlat_all_p(lcid, rlatdim, rlats)
I believe all of the `get_XXX_all_p` subroutines still need a `phys_grid_initialized()` check, as they do not call `chunk_info_to_index_p`.

2020-12-31 03:07 UTC, gold2718 commented on cime_config/SystemTests/plb.py
> +        comments = "Using phys_loadbalance to value that's set in the testmod."
No, I just want to express how much I 'value' the 'set' belonging to 'that' in the testmod :-)

2021-01-01 22:19 UTC, merged