MPAS bug fixes, performance enhancements, allow initial files writes, refactor/cleanup
ESCOMP/CAM pull request #303
Opened 2020-12-18 22:38 UTC by jtruesdal

PR mods:
- running on 1 task
- nag/debug
- Longer timestep 600s -> 900s for performance (requires MPAS coefficient change as well). Answer changing.
- replace existing analytic MPAS default ic with notopo grid file. Kessler blows up with nonzero topo initial condition.
- allow initial file writes
- dyn_in/dyn_out points to same MPAS memory location (refactor.

2020-12-19 03:34 UTC, cacraigucar approved these changes

2020-12-19 03:34 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa480" nlev="32" analytic_ic="1" >atm/cam/inic/mpas/mpasa480_L32_notopo_grid_c201125.nc</ncdata>
Just checking that these files have the mandatory AMWG metadata and are imported into the svn repository

2020-12-19 03:34 UTC, cacraigucar commented on src/dynamics/mpas/dyn_comp.F90
> +      allocate(tm(plev))
I believe we are trying to add error checking to all allocate calls now

2020-12-19 03:34 UTC, cacraigucar commented on src/dynamics/mpas/dyn_comp.F90
> +   logical, parameter :: discrete_hydrostatic_base = .true.
Should this be a namelist variable?

2021-01-11 16:08 UTC, cacraigucar reviewed
@jtruesdal Are these all the expected changes from the development side of things for this PR?  If so, I believe this is ready to be sent out for others to review.

2021-01-11 16:08 UTC, cacraigucar commented on src/dynamics/mpas/dp_coupling.F90
> +      tsize = 7 + pcnst
Since this number changed with this commit (and other values below are dependent on the value), should it be a parameter with appropriate offset values?  Or was this a one-time change which you don't expect to change again in the future?

2021-01-11 16:20 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +      tsize = 7 + pcnst
@cacraigucar It is now close.  I am updating the branch with the fixes for critical issues that have caused the delay.  There was a problem with the calculation of pressure levels in the interface that Peter has fixed, he is currently making the updates to make sure the energy is calculated correctly.  Michael Duda also updated the tag to the MPAS dycore with the addition of sponge layer diffusion which is required to allow MPAS to run stabily.  I am making runs now to get an initial default value.

2021-03-14 23:32 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +      tsize = 7 + pcnst
This part of the code was removed as part of the weak scaling fix.

2021-03-14 23:54 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa480" nlev="32" analytic_ic="1" >atm/cam/inic/mpas/mpasa480_L32_notopo_grid_c201125.nc</ncdata>
Making sure all new NetCDF files contained the core AMWG metadata.

2021-03-14 23:55 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +      allocate(tm(plev))
Put error checking for all allocates in dyn_comp.  I'll will check the other routines as well.

2021-03-15 20:15 UTC, cacraigucar approved these changes

2021-03-15 20:15 UTC, cacraigucar commented on src/dynamics/mpas/dp_coupling.F90
> +   ncols = columns_on_task! TODO: Correct way to get number of columns on task?
Should this TODO comment be removed?

2021-03-16 01:19 UTC, fvitt reviewed
a couple comments

2021-03-16 01:33 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   allocate(block_offset(0), stat=ierr)
It does seem odd.  Lets check with @MiCurry.

2021-03-16 21:48 UTC, MiCurry commented on src/dynamics/mpas/dp_coupling.F90
> +   allocate(block_offset(0), stat=ierr)
The allocation of size zero is to avoid the invalid memory access that would be caused in the subset call to `get_dyn_col_p` (`get_dyn_col_p_index` in `infrastructure/phys_grid()`), the code and link is bellow:

https://github.com/ESCOMP/CAM/blob/203925432967994400651a175eea1fddbe64a71f/src/infrastructure/phys_grid.F90#L921-L927

MPAS does not use a `block_offset`, but an unallocated block_offset would cause a seg fault in the above `phys_grid` code.

2021-03-16 21:54 UTC, MiCurry commented on src/dynamics/mpas/dp_coupling.F90
> +   ncols = columns_on_task! TODO: Correct way to get number of columns on task?
I suppose it could, as things seem to be working fine; however, I had it here to see if someone had a preference on using 'nCellsSolve' or `columns_on_task` here. Although I believe they are equivalent here, they might have slightly different meanings. Does `coloumns_on_task` represent the number of physics columns on a task? Or the number of dynamics columns on a task?

2021-03-16 22:07 UTC, MiCurry commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       use mpas_framework, only : mpas_framework_finalize
@fvitt I believe the comment on lines 2326-2328 contain the reason for this being commented out:

! Before we can make the call, below, changes are needed in the mpas_framework_finalize
! routine so that the call to mpas_timekeeping_finalize only finalizes the ESMF
! timekeeping library if ESMF was initialized by MPAS (and not, e.g., by CESM).
!       call mpas_framework_finalize(domain_ptr % dminfo, domain_ptr)

As of this comment, the change above has not been made into the atmosphere/cam branch of the MPAS repository.

2021-03-16 22:07 UTC, gold2718 commented on src/dynamics/mpas/dp_coupling.F90
> +   allocate(block_offset(0), stat=ierr)
@MiCurry, I agree with your solution.

2021-03-16 22:36 UTC, gold2718 commented on src/dynamics/mpas/dp_coupling.F90
> +   ncols = columns_on_task! TODO: Correct way to get number of columns on task?
The current correct answer is `columns_on_task`. The logic will change slightly when load balancing is (re)-introduced but for now, please use that.

2021-03-16 23:10 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       use mpas_framework, only : mpas_framework_finalize
@MiCurry, what are the next steps for finalizing MPAS in the CAM port.  I would be more comfortable finalizing MPAS properly at the end. Is this something that can be put into the atmosphere/cam branch of MPAS for now or do you also rely on that branch for running a non-CESM version of MPAS for comparison?

2021-03-16 23:27 UTC, fvitt commented on src/dynamics/mpas/dp_coupling.F90
> +   allocate(block_offset(0), stat=ierr)
Thanks for the explanation.

2021-03-17 15:04 UTC, MiCurry commented on src/dynamics/mpas/dp_coupling.F90
> +   ncols = columns_on_task! TODO: Correct way to get number of columns on task?
Thanks for the clarification @gold2718. Then yes, @cacraigucar we can delete this comment.

2021-03-17 15:13 UTC, MiCurry commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       use mpas_framework, only : mpas_framework_finalize
@jtruesdal I am not too familiar with the `mpas_framework_finalize` routine (and the comment above this call). Looking at the code I think we'll need to do something similar to whats being done for ESMF: 

https://github.com/MPAS-Dev/MPAS-Model/blob/f69242b68281ab3aff3d70044741901b56023afb/src/framework/mpas_timekeeping.F#L126-L128

@mgduda will have more insight on this.

2021-03-17 17:48 UTC, mgduda commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       use mpas_framework, only : mpas_framework_finalize
If we add `-DMPAS_NO_ESMF_INIT` to the definition of `CPPFLAGS` in the MPAS-A dycore [Makefile](https://github.com/ESCOMP/CAM/blob/cam_development/src/dynamics/mpas/Makefile), I think we could then safely uncomment the call to `mpas_framework_finalize`.

2021-03-23 15:37 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       use mpas_framework, only : mpas_framework_finalize
Thanks Michael.  I will test that and update the code as suggested.

2021-03-24 16:48 UTC, cacraigucar commented on Externals_CAM.cfg
> +hash = f69242b
Is it possible to get a tag associated with this hash?   If it is on a branch of the repo, it runs the risk of being removed and CAM tags will no longer be able to run checkout_externals properly.

2021-03-24 17:14 UTC, mgduda commented on Externals_CAM.cfg
> +hash = f69242b
The problem with tags and GitHub is that GitHub creates release points for each tag. We actually make use of [releases](https://github.com/MPAS-Dev/MPAS-Model/releases) in the MPAS-Model repository, and we'd like to avoid having the latest supported release (7.0 as of today) pushed off of the first page by newer tags.

Not creating releases from each tag is something that has been requested of GitHub various times over the years; see, e.g., [this discussion](https://github.community/t/tag-without-release/857). Nonetheless, GitHub never seems to act on these requests.

2021-03-24 20:37 UTC, gold2718 commented on Externals_CAM.cfg
> +hash = f69242b
Then a related question is: Is this hash on a mainline (long-lived) branch where it is _very_ unlikely that the hash would become an orphan (and therefore garbage collected) or deleted?

2021-03-24 22:10 UTC, mgduda commented on Externals_CAM.cfg
> +hash = f69242b
I think this commit is on the 'atmosphere/cam' branch, which we could in principle delete after we bring the MPAS-A dycore up to date with the current MPAS development branch.

2021-03-24 22:54 UTC, gold2718 commented on Externals_CAM.cfg
> +hash = f69242b
This GitHub issue (https://github.com/go-gitea/gitea/issues/378) seems to imply that you can delete the release without deleting the associated tag. Would that be okay?

2021-03-24 23:07 UTC, mgduda commented on Externals_CAM.cfg
> +hash = f69242b
If we could delete a release without deleting the tag, that would be great. However, I don't think this is actually possible. I may be mistaken, but the issue you referenced deals with something in Gitea, and not GitHub. And, I did try earlier this afternoon in a test repository to delete a release point without deleting the tag on GitHub, but with no success.

2021-03-29 20:37 UTC, MiCurry commented on src/dynamics/mpas/dyn_comp.F90
> +   if( ierr /= 0 ) call endrun(subname//': failed to allocate phis array')
`ierr` is declared but never initialized or set, which causes this this line to cause a run-time warning when debug is True:
```
 Run-Time Check Failure. The variable 'dyn_comp_mp_get_zsurf_from_topo_$IERR' is being used in '/glade/u/home/mcurry/cam-mpas/cam-mpas/src/dynamics/mpas/dyn_comp.F90(1067,13)' without being defined
```

2021-03-29 20:46 UTC, gold2718 commented on src/dynamics/mpas/dyn_comp.F90
> +   if( ierr /= 0 ) call endrun(subname//': failed to allocate phis array')
Looks like the `allocate` statement is missing a `stat=ierr` input.

2021-03-31 23:19 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +!       use mpas_framework, only : mpas_framework_finalize
Works correctly. Makefile and cam_mpas_subdriver updated.

2021-04-14 02:17 UTC, gold2718 commented
@jtruesdal,

Can you merge this branch up to the head of CAM? There are three tags (cam6_3_013, cam6_3_015, and cam6_3_016) which have NUOPC updates that are not in your PR.

2021-04-14 02:39 UTC, jtruesdal commented
Sure.  Just FYI the FV3 hash in this tag doesn't have Michael's NUOPC
changes needed for Mariana's proof of concept run.

jt
jt

On Tue, Apr 13, 2021 at 8:17 PM goldy ***@***.***> wrote:

> @jtruesdal <https://github.com/jtruesdal>,
>
> Can you merge this branch up to the head of CAM? There are three tags
> (cam6_3_013, cam6_3_015, and cam6_3_016) which have NUOPC updates that are
> not in your PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/303#issuecomment-819172153>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACG3NX7EJDLDLNUDMQQ7MBDTIT3MVANCNFSM4VBYOZ7A>
> .
>

2021-04-14 03:50 UTC, gold2718 commented
> Just FYI the FV3 hash in this tag doesn't have Michael's NUOPC

Just checking, did you mean MPAS hash?

2021-04-14 04:10 UTC, jtruesdal commented
Yes.

jt

On Tue, Apr 13, 2021 at 9:50 PM goldy ***@***.***> wrote:

> Just FYI the FV3 hash in this tag doesn't have Michael's NUOPC
>
> Just checking, did you mean MPAS hash?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/303#issuecomment-819208530>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACG3NX2OQFWNUZS2MG46AD3TIUGJZANCNFSM4VBYOZ7A>
> .
>

2021-04-14 04:14 UTC, jtruesdal commented
Updated the MPAS PR branch.

jt

On Tue, Apr 13, 2021 at 10:10 PM John Truesdale ***@***.***>
wrote:

> Yes.
>
> jt
>
> On Tue, Apr 13, 2021 at 9:50 PM goldy ***@***.***> wrote:
>
>> Just FYI the FV3 hash in this tag doesn't have Michael's NUOPC
>>
>> Just checking, did you mean MPAS hash?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ESCOMP/CAM/pull/303#issuecomment-819208530>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ACG3NX2OQFWNUZS2MG46AD3TIUGJZANCNFSM4VBYOZ7A>
>> .
>>
>

2021-04-23 20:07 UTC, jtruesdal commented
@cacraigucar This PR is ready for review again.  I've updated the cime external to a newer version to fix a bug we had with MPAS restart writes. The MPAS dycore external has been updated to allow it to use the CESM version of ESMF. The MPAS update was requested to allow NUOPC compatibility.  @gold2718 We still have the outstanding issue of having an MPAS hash from a branch that could be removed in the future.  I can open an issue on that if we don't have a fix right now but I don't think it should hold up the PR.  It's not an immediate problem and we have assurances from the MPAS team that they won't delete anything until this issue is resolved.

2021-04-23 21:38 UTC, cacraigucar commented
@jtruesdal - The problem with the hash and its possible removal occurs  if a user checks out the CAM tag and uses it as a base for their branch or long-term work.  Even if they are not using MPAS, a future run of manage_externals/checkout_externals could break their entire branch if the hash were removed.  The likelihood of this happening is small, but it is not zero.    As a result, I believe we (at least I) would be much more comfortable if the hash issue were resolved before this PR is put onto the CAM trunk.  If its not fixed now, it will continue to be a problem for all CAM tags until it is fixed.  If the CAM tag without the "forever hash" gets into a CESM tag, then the odds of it creating a problem goes up.

2021-04-23 22:24 UTC, jtruesdal commented on Externals_CAM.cfg
> +hash = f69242b
I don't know of a workaround and we seem to be at a bit of an impasse.  Not ideal but how about a fork of MPAS under ESCOMP its only reason for being is to contain tags for the MPAS hashes.

2021-04-23 22:45 UTC, cacraigucar commented on Externals_CAM.cfg
> +hash = f69242b
We do something very similar for the CLUBB library.  In the CLUBB case, we have a few edits we need to make with every tag.  Let's see if @gold2718 is happy with this option.  If we go that route, I would suggest that you add a very abbreviated ChangeLog and make a tag with each commit.  Again, you can see the ESCOMP/CLUBB_CESM repo for an example.

2021-05-18 18:34 UTC, jtruesdal commented
@cacraigucar This PR is ready for review again.  I pushed the change to make MPAS an optional component.

2021-05-18 19:11 UTC, fvitt approved these changes

2021-05-18 20:09 UTC, cacraigucar approved these changes

2021-05-18 20:09 UTC, cacraigucar commented on Externals.cfg
> +tag = cime5.8.42
If regression tests for non-MPAS tests have answer changes, you may need to update this cime tag in a separate CAM tag all by itself.

2021-05-18 20:09 UTC, cacraigucar commented on doc/ChangeLog
> +List all existing files that have been modified, and describe the changes:
Double check that all the modified files are accurately reflected here.  (Externals.cfg is not listed though it now has change)

2021-05-18 20:34 UTC, jtruesdal commented on Externals.cfg
> +tag = cime5.8.42
I will test that now.  Would the following failure against baseline be acceptable?

FAIL SMS_D_Ln9.ne0CONUSne30x8_ne0CONUSne30x8_mt12.FCHIST.cheyenne_intel.cam-outfrq9s_refined_camchem BASELINE /glade/p/cesm/amwg/cesm_baselines/cam6_3_017:  FIELDLIST field lists differ (otherwise bit-for-bit)

2021-05-19 06:09 UTC, peverwhee approved these changes

2021-05-19 15:35 UTC, jtruesdal commented on doc/ChangeLog
> +List all existing files that have been modified, and describe the changes:
I added documentation for Externals.cfg, diagnostics.F90 and listed subroutines that were removed when adopting weak scaling fixes.  I'll have one more update when I run the official regression tests and will push this file before tagging.

2021-05-20 16:04 UTC, nusbaume approved these changes
Looks good!  I do have one recommendation about wrapping an `endrun` call in an if-statement, but the rest are all just minor things like typos or error message text additions.

2021-05-31 03:55 UTC, gold2718 commented
I'm not sure where this should be documented, however, there is a bug in manage_externals. If the hash for MPAS is updated, you have to rerun `checkout_externals` with the `--optional` flag or the MPAS external will not be updated.
See https://github.com/ESMCI/manage_externals/issues/155

2021-05-31 05:41 UTC, gold2718 requested changes
A few change requests

2021-05-31 05:41 UTC, gold2718 commented on src/dynamics/mpas/dyn_grid.F90
> +      call endrun(subname//': ERROR: number of levels in IC file does not match plev.')
`use string_utils, only: int2str` is one way to get integer values into an `endrun` message.
Writing to a formatted character string is another way to do this.

2021-05-31 05:41 UTC, gold2718 commented on src/dynamics/mpas/dp_coupling.F90
> +   real(r8), allocatable, dimension(:) :: bbuffer, cbuffer ! transpose buffers
These are not used anymore, delete (same for `p_d_coupling`).

2021-05-31 05:41 UTC, gold2718 commented on src/dynamics/mpas/dp_coupling.F90
> +   kap2 = (1.0_r8/(1.0_r8-rgas/cp))! pre-compute constants
Could these be parameters?

2021-06-01 14:17 UTC, jtruesdal commented on doc/ChangeLog
> +. Correct interface error when calculation CAM pressures from MPAS height.
Fixed.

2021-06-01 14:27 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="mpasa480">atm/cam/chem/trop_mam/atmsrf_mpasa480_c090720.nc</drydep_srf_file>
I reported the addition of these 2 new defaults in ChangeLog also added reviewers.

2021-06-01 14:28 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   real(r8), allocatable:: pmid(:,:)   !mid-level pressure consisten with MPAS discrete state
Corrected.

2021-06-01 14:29 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +      ! is at heigh z(nVertLevels-1)+0.5*dz
Corrected

2021-06-01 14:39 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       character(len=*), parameter :: subname = 'cam_mpas_subdriver::cam_mpas_get_global_dims'
My thoughts exactly but I do see Jesse's point of not including extraneous lines of code and it's not currently best practice to markup every subroutine like this.  I removed it.

2021-06-01 14:49 UTC, jtruesdal commented on src/dynamics/mpas/driver/cam_mpas_subdriver.F90
> +       if( ierr /= 0 ) call endrun(subname//':failed to allocate temp1d array')
I like Steve's idea and implemented that to pinpoint the line.

2021-06-01 14:51 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +      if( ierr /= 0 ) call endrun(subname//': failed to allocate mpas3d array')
Added line number as above.

2021-06-01 14:55 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +      ! no else clause needed.  &decomposition is not present for single task runs.
I could see a developer/user hand-editing a namelist and making this mistake.  I will add your suggestion.

2021-06-01 14:56 UTC, jtruesdal commented on src/dynamics/mpas/stepon.F90
> +      if( ierr /= 0 ) call endrun(subname//':failed to allocate arr2d array')
Will add line number as above.

2021-06-01 15:00 UTC, jtruesdal commented on src/dynamics/mpas/stepon.F90
> +   ! of having an initial files written with a timestamp that is after the stop date.
Corrected.

2021-06-01 16:34 UTC, jtruesdal commented on src/dynamics/mpas/dyn_grid.F90
> +      call endrun(subname//': ERROR: number of levels in IC file does not match plev.')
Agreed, I'll add the level info.  Thanks for the heads up on int2str Steve, I'll use that more from now on.

2021-06-01 16:51 UTC, jtruesdal commented on src/dynamics/mpas/dyn_grid.F90
> +   if( ierr /= 0 ) call endrun(subname//':failed to allocate gidx array')
Added line number as before.

2021-06-01 18:18 UTC, jtruesdal commented on doc/ChangeLog
> +Github PR URL:
Done.

2021-06-01 19:17 UTC, jtruesdal commented on doc/ChangeLog
> +. Port weak scaling mods to MPAS
New issue: https://github.com/ESCOMP/CAM/issues/385
MPAS is currently under development so in this case, I've opened a general issue for all of these items. I will be better about opening issues in the future as we anticipate more updates as the dycore port matures. While MPAS is under heavy development and in the interest of making efficient use of the reviewers' time,  it is very likely that each of the next PR's will include several changes.  I will make sure to update the issue, in the case of last-minute additions to a PR that weren't documented in the original.

2021-06-01 19:55 UTC, jtruesdal commented on doc/ChangeLog
> +bld/namelist_files/namelist_definitions.xml
Fixed.

2021-06-01 20:09 UTC, jtruesdal commented on doc/ChangeLog
> +. fix calculation of CAM pressure from MPAS height coordinate.
This particular if statement is applicable to all the dycores.  MPAS is listed as a comment in the else part of the statement.  This is one of Peter's changes, I think he just wanted to make explicit the differences between the dycores in the setting of the hydrostatic elements.  If you would like more comments or something please 'at' PeterHjortLauritzen and I'll let him put the wording together.

2021-06-01 20:54 UTC, jtruesdal commented on doc/ChangeLog
> +  - mpas_cam_coef: A fixed, second-order horizontal diffusion in the top-most three layers on
@PeterHjortLauritzen below is the wording I currently have in namelist_definition.xml. I'm no longer sure which of the terminology is yours, mine or Michaels. Would you address Steve's concern (re mixing and diffusion) as well as any of your own and modify the following definition?  I will update the ChangeLog and namelist definition file to use your version.

================
<entry id="mpas_cam_coef" type="real" category="mpas"
       group="damping" valid_values="">
The coefficient for scaling the 2nd-order horizontal mixing in the mpas_cam absorbing layer.                                                                              
A value of 1.0 will result in layered diffusion similar to CAM-SE and gives damping coefficients of 0.2216E7, 0.6482E6, 0.1927E6 in the top-most three layers on the dynamics variables u, w, and theta. The top 3 damping coefficients scale linearly with mpas_cam_coef. A value of 0.0 disables SE like 2nd-order diffusion in the absorbing layer and is the current default.  In this case (no SE-like diffusion) we provide stability by activating Rayleigh damping on u in the absorbing layer with the namelist parameter mpas_rayleigh_damp_u.                                                               
Default: 0.0

2021-06-01 20:55 UTC, jtruesdal commented on doc/ChangeLog
> +	   linearly with mpas_cam_coef.
Done.

2021-06-01 21:11 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +            rho_base(klev,iCell) = pres / ( Rgas * t0b * zz(klev,iCell))
I would think this type of change has to be in the noise from one run to the next. It would also make the code less readable.  I'm not positive though so I'll run a few tests and make sure.

2021-06-01 21:14 UTC, jtruesdal commented on src/dynamics/mpas/stepon.F90
> +   call pio_closefile(fh)
Thanks for the suggestion, I changed it.

2021-06-01 21:16 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   real(r8), allocatable, dimension(:) :: bbuffer, cbuffer ! transpose buffers
Good catch.  Removed from both subroutines.

2021-06-02 18:04 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   kap2 = (1.0_r8/(1.0_r8-rgas/cp))! pre-compute constants
I did try this but cp is a modifiable variable for aquaplanet (derived from public protected) so no these can not be parameters.

2021-06-03 05:31 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +            rho_base(klev,iCell) = pres / ( Rgas * t0b * zz(klev,iCell))
Unfortunately, cp is modifiable (public protected) and can't be used for a parameter.  Same issue with making kap1 and kap2 below into parameters.

2021-06-03 15:38 UTC, gold2718 approved these changes
Looks good now (pending input from @PeterHjortLauritzen).

2021-06-03 15:38 UTC, gold2718 commented on doc/ChangeLog
> +. fix calculation of CAM pressure from MPAS height coordinate.
My point is that while the additional comments mention MPAS, there is a code change that affects FV3. @PeterHjortLauritzen, is the FV3 change appropriate? If so, there should be an issue discussing the change as I expect it would change answers for FV3 runs.

2021-06-03 15:38 UTC, gold2718 commented on src/dynamics/mpas/dp_coupling.F90
> +   kap2 = (1.0_r8/(1.0_r8-rgas/cp))! pre-compute constants
Oops, I keep forgetting that. Sorry for the distraction.

2021-06-03 15:38 UTC, gold2718 commented on src/dynamics/mpas/dyn_comp.F90
> +            rho_base(klev,iCell) = pres / ( Rgas * t0b * zz(klev,iCell))
More 'my bad', sorry.

2021-06-03 15:59 UTC, gold2718 commented on doc/ChangeLog
> +. Port weak scaling mods to MPAS
While this looks like efficiency on the surface, it costs us a lot of time on the back end. The issues are our record and database for discussions of what needed fixing and why. Please trim #385 to match what is fixed in this PR and add a line to that effect in the PR title (see [item 10 of the CAM SE PR procedures](https://github.com/NCAR/CAM/wiki/CAM-SE-Workflows#primary-assigned-ses-duties-for-when-code-from-scientists-are-being-brought-into-cam) or the [GitHub issue-closing syntax](https://help.github.com/en/articles/closing-issues-using-keywords).

2021-06-03 16:13 UTC, nusbaume requested changes
Looks like a couple of my requested edits were missed (?).  Once they are fixed (or you have a reason to not make those changes) then this PR should be good to go on my end.

2021-06-03 16:13 UTC, nusbaume commented on src/dynamics/mpas/dyn_comp.F90
> +      ! no else clause needed.  &decomposition is not present for single task runs.
It looks like this `endrun` change still needs to be made?

2021-06-03 16:13 UTC, nusbaume commented on src/dynamics/mpas/dyn_grid.F90
> +   if( ierr /= 0 ) call endrun(subname//':failed to allocate grid_map array')
I believe these `grid_map` endrun calls also would benefit from having the line number included, as there is more than one of them in this subroutine.

2021-06-03 16:29 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +      ! no else clause needed.  &decomposition is not present for single task runs.
Yes.  Will push this mod before updating and testing.

2021-06-03 16:37 UTC, jtruesdal commented on doc/ChangeLog
> +. fix calculation of CAM pressure from MPAS height coordinate.
The changelog comment for this mod is incorrect and I will replace that. The change is a no-op for FV3 and the rest of the dycores. Peter just removed a logical that obscured which dycores were involved and replaced it with the complete expression and comment explicitly listing them.

2021-06-03 16:38 UTC, jtruesdal commented on doc/ChangeLog
> +. Port weak scaling mods to MPAS
Will do.

2021-06-03 16:40 UTC, jtruesdal commented on src/dynamics/mpas/dyn_grid.F90
> +   if( ierr /= 0 ) call endrun(subname//':failed to allocate grid_map array')
I'll add this as well.  Thanks.

2021-06-03 16:45 UTC, gold2718 commented on doc/ChangeLog
> +. fix calculation of CAM pressure from MPAS height coordinate.
Ah, thanks for the explanation. I see now that the new version still has the `fvdyn` variable but is no longer using it. Please remove that variable from geopotential.F90.

2021-06-03 18:58 UTC, jtruesdal commented on src/dynamics/mpas/dyn_grid.F90
> +   if( ierr /= 0 ) call endrun(subname//':failed to allocate grid_map array')
Finished and tested.

2021-06-03 18:59 UTC, jtruesdal commented on doc/ChangeLog
> +. fix calculation of CAM pressure from MPAS height coordinate.
Removed variable and associated code.

2021-06-03 19:46 UTC, nusbaume approved these changes
Looks great now, thanks!

2021-06-05 00:03 UTC, merged