PUMAS Optimization PR pt2
ESCOMP/CAM pull request #324
Opened 2021-02-04 23:32 UTC by Katetc

This PR and another one titled "PUMAS Optimization PR pt1" should go into the same CAM tag for expediency. The changes were broken up to help with the review process.

The second part of the PR includes CAM source code changes as well as PUMAS source changes. However, these changes are all verified bit-for-bit against a full aux_cam Cheyenne suite generated by part 1 of the PR. To review the PUMAS changes look at:
https://github.com/ESCOMP/PUMAS/compare/pumas_cam-release_v1.9..pumas_cam-release_v1.11

Tagging @andrewgettelman so he can follow the discussion.

All changes suggested by review of both part 1 and part 2 PRs will be included in this PR.

2021-03-03 23:01 UTC, cacraigucar requested changes
When you address these minor issues from my preliminary review, I will then open this PR up for full review.

2021-03-03 23:26 UTC, andrewgettelman commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
Goff, J. A., and S. Gratch. “Low-Pressure Properties of Water from -160F to 212F.” Trans. Am. Soc. Heat. Vent. Eng. 52 (1946): 95–121.

2021-03-03 23:26 UTC, andrewgettelman commented on src/physics/cam/wv_sat_methods.F90
> +          0.014025_r8 * t(i))))
Murphy, D. M., and T. Koop. “Review of the Vapour Pressure of Ice and Supercooled Water for Atmospheric Applications.” Q. J. R. Meteorol. Soc. 131, no. 608 (2005): 1539–65.

2021-03-10 00:32 UTC, Katetc commented on src/physics/cam/macrop_driver.F90
> +     if (qv(i).gt.QSL(i)) then
Fixed

2021-03-10 00:33 UTC, Katetc commented on src/physics/cam/macrop_driver.F90
> +        if (nc(i)*p(i)/rair/t(i).lt.1e3_r8.and.(qc(i)+qctend(i)*deltat).gt.1e-18_r8) then
Fixed, I believe. I left the ".and." there because I don't think C-style Boolean operators are fully supported... but feel free to correct me if you prefer a "&&" here.

2021-03-10 00:34 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
Fixed

2021-03-10 00:34 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +          0.014025_r8 * t(i))))
Fixed

2021-03-10 17:43 UTC, cacraigucar commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
Is there a DOI for this paper (it is pretty old)?  If so, please add it.

2021-03-10 17:44 UTC, cacraigucar commented on src/physics/cam/wv_sat_methods.F90
> +          0.014025_r8 * t(i))))
Please add the DOI if there is one for this paper.

2021-03-10 17:53 UTC, andrewgettelman commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
No DOI. Too old.

2021-03-10 19:42 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +          0.014025_r8 * t(i))))
Addressed this

2021-03-10 22:04 UTC, fvitt commented
Is there a github issue this PR is addressing?

2021-03-11 13:57 UTC, fvitt reviewed
I am seeing copies of constants and complicated formulas throughout wv_sat_methods.  This will be difficult to maintain.

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/clubb_intr.F90
> +  real(r8), dimension(vlen), intent(in)  :: p      !pressure (pa0
Are the units (Pa)?

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/macrop_driver.F90
> +           nctend(i) = nctend(i) + 3._r8 * qctend(i)/(4._r8*3.14_r8*6.e-6_r8**3*rhow)
Is 3.14 pi?  To improve efficiency, could you let 3./(4*pi*6e-6**3*rhow) a parameter?

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/cldfrc2m.F90
> +
This loop does not seem to be indented.

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +function wv_sat_svp_water(t, idx) result(es)
Is there a need to do away with elemental functions?  I did not see discussion of this in the issues.  Is this done for efficiency reasons?  If so, much have you improved efficiency?

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
Log is an expensive operation.  Could you make `log10(1013.246_r8)` a parameter?  There is  no need to compute this more than once.

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +          log10(6.1071_r8))*100._r8
Could you make `log10(6.1071_r8)` a parameter?

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +      integer :: i
Please fix the indentation.

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +     f4(i) = 8.1328_r8*(10.0_r8**e2(i) - 1.0_r8)/1000.0_r8
Instead of dividing constants, could you multiply by inverses?

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +     f5(i) = log10(ps(i))
I seems that f5 could be a parameter (`log10(1013.256)`).

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
>  elemental function OldGoffGratch_svp_ice(t) result(es)
Is this elemental function remaining as elemental?

2021-03-11 13:57 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
>  elemental function MurphyKoop_svp_water(t) result(es)
Is this elemental function remaining as elemental?

2021-03-11 18:08 UTC, Katetc commented on src/physics/cam/cldfrc2m.F90
> +
I read this as "This loop does not seem to be intended" at first and spent some confused time staring at the code. Lol. Dyslexia.

2021-03-11 18:13 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +function wv_sat_svp_water(t, idx) result(es)
The purpose of these PRs is to prep the microphysics code in CAM for offloading onto GPUs once they become available. Elemental functions do not vectorize well, and aren't as efficient on GPUs. These changes should not improve efficiency on currently supported machines, so there isn't a good way to quantify improvements right now.

2021-03-11 22:10 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +     f5(i) = log10(ps(i))
I think keeping this as variable allows the function to be more flexible. For different sea levels (paleo runs, distant futures) or other reference surface pressures at other altitudes.

2021-03-11 22:22 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
>  elemental function OldGoffGratch_svp_ice(t) result(es)
For some reason, yes, Jian left these as elemental functions. I grepped through the CESM code, and I can't find anywhere that OldGoffGratch is used any more, so I'm not sure if it matters at this point if those are elemental functions or not. If those functions are never called, then changing them to support GPUs is not necessary.

2021-03-11 22:28 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
>  elemental function MurphyKoop_svp_water(t) result(es)
For some reason, John Dennis' postdoc Jian (who made these modifications for us) did leave some functions as elemental. Perhaps these are not called any more or will be updated in the future. It will remain elemental in this pull request.

2021-03-11 22:38 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +  real(r8), dimension(vlen), intent(in)  :: p      !pressure (pa0
Fixed the parenthesis

2021-03-11 22:38 UTC, Katetc commented on src/physics/cam/macrop_driver.F90
> +           nctend(i) = nctend(i) + 3._r8 * qctend(i)/(4._r8*3.14_r8*6.e-6_r8**3*rhow)
Changed

2021-03-11 22:38 UTC, Katetc commented on src/physics/cam/cldfrc2m.F90
> +
Fixed indentation

2021-03-11 22:39 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
Made this change

2021-03-11 22:39 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +          log10(6.1071_r8))*100._r8
Made this change

2021-03-11 22:39 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +      integer :: i
Fixed

2021-03-11 22:44 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +     f4(i) = 8.1328_r8*(10.0_r8**e2(i) - 1.0_r8)/1000.0_r8
Changed

2021-03-24 22:05 UTC, gold2718 approved these changes
A few suggestions (and notes for the future) but basically okay.

2021-03-25 03:37 UTC, nusbaume approved these changes
Looks good to me!  Just a few very minor edits.

2021-03-30 16:01 UTC, Katetc commented on src/physics/cam/cldfrc2m.F90
>           if( iceopt.eq.1 ) then
Sure, sounds good to me!

2021-03-31 16:51 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +           nitend(i) = nitend(i) + 3._r8 * qitend(i)/(4._r8*3.14_r8* 10.e-6_r8**3*997._r8)
Thanks, I agree!

2021-03-31 19:39 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +       log10(1013.246_r8))*100._r8
I have no idea what happened here. Apparently I was once sure I made this change, but it didn't stick. Maybe I can blame emacs or git or who knows. Thanks for catching that, Steve.

2021-03-31 19:40 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +     f5(i) = log10(ps(i))
Ahhh, I see what's up now. I made these requested changes.

2021-03-31 19:41 UTC, Katetc commented on src/physics/cam/cldwat.F90
> +
I have no opinion on extra lines. Removed.

2021-03-31 19:42 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        qitend(i) = (qv(i)-QSI(i))/deltat !* exp(-tau/deltat)
I have no idea, this comment is from before my time. Sure, removed.

2021-03-31 19:43 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +  log_param = log10(6.1071_r8)
Got it now, thanks!

2021-03-31 19:44 UTC, Katetc commented on src/physics/cam/aer_rad_props.F90
> +   integer :: i, k       ! index
That's weird. I removed it.

2021-03-31 19:44 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +!!  real(r8) :: tau
Sure

2021-03-31 19:45 UTC, Katetc commented on src/physics/cam/macrop_driver.F90
> +        ! size is create to remove the excess water. This could be enhanced to
Fixed

2021-04-01 19:34 UTC, cacraigucar approved these changes

2021-04-01 20:18 UTC, fvitt approved these changes

2021-04-01 20:18 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +  log_ps = log10(1013.246_r8)
Is there a reason this is not a parameter?
```
 real(r8), parameter :: log_ps = log10(1013.246_r8)
```

2021-04-01 20:18 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +  real(r8) :: f5 = log10(psp)
Should `f5` a parameter? `psp` is a parameter.
```
real(r8), parameter :: f5 = log10(psp)
```

2021-04-01 20:20 UTC, fvitt commented on src/physics/cam/wv_sat_methods.F90
> +  log_ps = log10(1013.246_r8)
Maybe the log_ps parameter be defined once at the module level?

2021-04-01 22:10 UTC, gold2718 commented on src/physics/cam/wv_sat_methods.F90
> +  real(r8) :: f5 = log10(psp)
I agree on the parameter issue. However, if there is a good reason to _not_ make it a parameter, please move the initialization (see comment on line 695).

2021-04-01 22:13 UTC, gold2718 commented on src/physics/cam/wv_sat_methods.F90
> +  real(r8) :: f = 0._r8
Do not set `f` here. If you initialize a variable in the declaration statement of a subroutine or function, it invokes the `save` attribute which can affect performance and possibly give you unexpected answers. I do not see a reason to set `f` at all given that it only possible use is after it is set in the code.

2021-04-02 21:30 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +  log_ps = log10(1013.246_r8)
Ok, moved the log_ps parameter to the module level. But I only updated the two functions that you guys have been looking at. The whole module needs a massive rewrite, and I don't have time to do that right now.

2021-04-02 21:31 UTC, Katetc commented on src/physics/cam/wv_sat_methods.F90
> +  real(r8) :: f5 = log10(psp)
As mentioned in the previous comment, I made log_ps a module level parameter and it is now used in these two functions. I'm not here to rewrite all of wv_sat_methods.F90 right now, though.

2021-04-07 15:27 UTC, cacraigucar commented
Does your latest commit (which you are sending back to CISL) mean that you will be delaying the CAM tag until they give you a solution?

2021-04-07 15:30 UTC, Katetc commented
> Does your latest commit (which you are sending back to CISL) mean that you will be delaying the CAM tag until they give you a solution?

No, I just won't include the water vapor optimized calls in ZM microphysics in this tag. Jian is working on a new set of changes right now, so I'll have him rework this bit of code with his current stuff and it can be included in his next PR.

2021-04-07 15:31 UTC, andrewgettelman commented
Agreed. zm convective microphysics is optional (not default) code, rarely used.

2021-04-13 22:23 UTC, merged