MPAS doesn't build under CESM checkout.
ESCOMP/CAM pull request #338
Opened 2021-02-26 19:08 UTC by jtruesdal

CAM's bld/configure routine needs to be updated for MPAS to allow it to build under CAM or CESM checkouts.  The namelist defaults also need to be updated to get a MPAS CESM regression test to pass.

2021-02-26 20:43 UTC, nusbaume commented
Looks good!  My only request would be to add the line:

`Fixes #337`

To the initial Github PR text above.  That way the associated issue will be closed after this PR has been merged.  Thanks!

2021-02-26 20:43 UTC, nusbaume approved these changes

2021-02-26 20:58 UTC, gold2718 requested changes
I need to understand what is going on with analytic initial conditions in MPAS.

2021-02-26 20:58 UTC, gold2718 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa480" nlev="32" analytic_ic="1" >atm/cam/inic/mpas/mpasa480_L32_notopo_grid_c201125.nc</ncdata>
I'm really confused, why are we passing an initial conditions file for an analytic IC case?

2021-02-26 21:18 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa480" nlev="32" analytic_ic="1" >atm/cam/inic/mpas/mpasa480_L32_notopo_grid_c201125.nc</ncdata>
Like the other dycores, MPAS requires some grid information to be passed via the initial condition file, whether for analytic or initialized runs. The other dycores pass vertical grid information specified in terms of cam_vcoords_LXX.nc files.  The files which only contain MPAS grid information have the word grid in them and don't contain any initial state.

2021-02-26 21:30 UTC, gold2718 approved these changes
Possibly rename the file for clarity.

2021-02-26 21:30 UTC, gold2718 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa480" nlev="32" analytic_ic="1" >atm/cam/inic/mpas/mpasa480_L32_notopo_grid_c201125.nc</ncdata>
Is this an MPAS naming convention? We have been using the `_vcoord_` convention (I originally even set them up in a separate, `vcoord` directory, not sure why they got moved to `inic`). If you do not mind renaming the file, please do so (i.e., if it is not an existing MPAS convention).

2021-02-26 21:37 UTC, cacraigucar approved these changes

2021-02-26 21:46 UTC, gold2718 commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
Since this change is to fix an issue not normally encountered in CAM regression tests, please document steps taken to ensure the issue is fixed.
- What tests were run from a CAM standalone sandbox?
- What tests were run from a CESM sandbox?

2021-02-26 21:56 UTC, jtruesdal commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
I ran the single CESM regression test that Cheryl asked me to look into and will put the passing status in the log as requested.
I'm running the aux_cam suite for the CAM sandbox but am running into failures on Izumi which I am working through with @cacraigucar.

2021-02-26 22:00 UTC, gold2718 commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
Great, please add the details of the CESM test to this section when you update it prior to the merge.

2021-02-27 00:58 UTC, jtruesdal commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
As for renaming the files.  MPAS reads its grid info (horizontal and vertical) from the initial file making those files resolution specific and different from the generic vcoord convention that can be used for the analytic cases by the other dycores.  I could rename the current files to make them more similar and differentiating from a standard initial condition by using the term grid_only. Something like

mpas120_L32_notopo_grid_only_c190924.nc 
mpas480_L32_notopo_grid_only_c201125.nc.

Peter has spoken about using analytic initial files containing topography so there may also be some _topo_ versions down the line.

2021-03-01 18:31 UTC, jtruesdal commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
@gold2718 I am happy to rename the files but they don't quite fit the existing _vcoord_ convention and I'm not sure what they should be called. The existing _vcoord_ files are somewhat generic and consist of vertical pressure coordinates and work with all resolutions of the non-MPAS dycores. The new grid only MPAS files are tied to the MPAS height grid, requiring a topo/notopo designation along with level # and a specific horizontal resolution.  Maybe cam_mpas480_L32_notopo_coords_cDATE.nc ?

2021-03-01 18:54 UTC, gold2718 commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
@jtruesdal, I like this naming (`_notopo_coords_`) better. Other thoughts? @cacraigucar? @nusbaume?

2021-03-01 19:19 UTC, cacraigucar commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
I'm fine with (`_notopo_coords_`)

2021-03-01 19:30 UTC, jtruesdal commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
@cacraigucar is it OK just to rerun the tests which are affected by the name change.  2 tests in cam testlist and the original CESM regression test that was failing.

2021-03-01 19:39 UTC, cacraigucar commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
Yes, that will be fine.

2021-03-01 19:58 UTC, nusbaume commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
I am also fine with `_notop_coords_`.  Thanks for asking!

2021-03-01 20:23 UTC, cacraigucar commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
@jtruesdal - Don't forget to verify it has the AMWG mandatory metadata and rimport it into the svn repo.

2021-03-01 20:35 UTC, jtruesdal commented on doc/ChangeLog
> +appropriate machine below.  All failed tests must be justified.
Will do.

2021-03-01 22:33 UTC, merged