Update CAM codes for Casper and the execution of qsat* subroutines on GPU
ESCOMP/CAM pull request #366
Opened 2021-04-21 05:24 UTC by sjsprecious

This PR mainly aims at accommodating the following two recent changes: 

- In the latest PUMAS tag `pumas_cam-release_v1.15`, the calculation of MG3 parameterization has been offloaded to GPU. This requires the GPU changes of qsat* subroutines in the CAM Repo.
- In the current master branch of CIME repo (https://github.com/ESMCI/cime/tree/master/config/cesm/machines), we have updated the configuration files for Casper machine at NCAR and added options to enable the execution of MG3 and qsat* subroutines on GPU. This also requires some changes in the CAM Repo.

The detailed changes in this PR include:

- Change the tag of stable PUMAS codes to `pumas_cam-release_v1.15`.
- Update configuration files `pgi` and `nvhpc` compilers to accommodate the changes in the CIME repo.
- Add some CPU and GPU tests for Casper to the test list, as well as their configurations.
- Add OpenACC directives to the qsat* subroutines to enable their execution on GPU.
- Change the `svp_water` and `svp_ice` subroutines to scalar functions in the `zm_microphysics.F90` subroutine, avoiding the non-stridded access to the `t` and `es` array in the previous version.

Test suite: [aux_cam]
Test machine: [Cheyenne]
Test baseline: generated on Cheyenne with (1) Intel compiler, (2) PUMAS tag `pumas_cam-release_v1.15` and (3) CAM codes from https://github.com/PUMASDevelopment/CAM/tree/sjsp_cam_gpus_p3.
Test results: [BFB]
Code review: @Katetc @andrewgettelman

2021-04-23 17:40 UTC, cacraigucar requested changes

2021-04-23 21:33 UTC, sjsprecious commented on src/physics/cam/wv_sat_methods.F90
> +
Thanks @cacraigucar, just delete it.

2021-04-23 21:43 UTC, sjsprecious commented on src/physics/cam/micro_mg_cam.F90
> +#if defined (__OPENACC__)
Thanks. I just revised the implementation without the `__OPENACC__` preprocessor directive.

2021-04-26 22:26 UTC, sjsprecious commented on src/physics/cam/wv_sat_methods.F90
> +#define VLEN 128
Hi @cacraigucar , the `VLEN` variable will replace the string in the OpenACC directives, not the Fortran code. Thus changing it to a Fortran parameter would not work here. I discussed with John and we would probably remove the `VLEN` variable and `vector_length` clause for simplicity.

2021-04-28 02:34 UTC, sjsprecious commented on src/physics/cam/wv_saturation.F90
> +#define VLEN 128
Thanks. We have made the suggested change.

2021-04-28 17:47 UTC, sjsprecious commented on src/physics/cam/wv_sat_methods.F90
> +
Thanks. This variable is deleted.

2021-04-28 17:49 UTC, sjsprecious commented on src/physics/cam/micro_mg_cam.F90
> +#if defined (__OPENACC__)
Thanks. This # variable is deleted.

2021-04-29 15:00 UTC, fvitt approved these changes
A couple curiosity questions.

2021-04-29 15:27 UTC, sjsprecious commented on cime_config/testdefs/testmods_dirs/cam/outfrq9s_mg3_casper/shell_commands
> +./xmlchange ROOTPE_CPL='0'
Thanks @fvitt . These settings are the same as those in the config_pes.xml as you point out. Originally I thought a user could change the PE layout for a particular type of simulation here, providing certain flexibility. But I could remove them if they look unnecessary.

2021-04-29 15:41 UTC, sjsprecious commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
Thanks @fvitt . Yes, this test runs on 1 Casper node. They could run on multiple Casper nodes as well but I choose one here because Casper has limited number of nodes with NVIDIA V100 GPU and asking for many nodes with GPU could lead to longer queue time. Currently this test uses one GPU per node. In order to use multiple GPUs per node, we could (1) always ask for a node with 8 GPUs or (2) provide a new configuration option like "num_gpu" to ask the user for input. I prefer the latter method personally but I think it will involve many changes in both CAM and CIME. I could do that in a separate PR and I really appreciate it if you could suggest what needs to be changed.

2021-05-05 17:58 UTC, Katetc approved these changes

2021-05-20 19:59 UTC, nusbaume approved these changes
Looks good to me!  I just had one question (which is mostly just out of curiosity).

2021-05-20 19:59 UTC, nusbaume commented on src/physics/cam/wv_sat_methods.F90
> +integer, parameter :: VLEN = 128 ! vector length for a GPU kernel
Can I ask how this number was chosen, and if it is always a reasonable choice, or is it GPU/system-dependent?  If it is system-dependent, are there any plans to make this configurable in the future (say via CIME and/or a namelist variable)?

2021-05-20 20:02 UTC, nusbaume commented on src/physics/cam/wv_sat_methods.F90
> +function OldGoffGratch_svp_water(t) result(es)
I am happy to remove it as well, but I would like to double-check with the scientists first in case there are situations where they would want to use it.  @andrewgettelman any opinion here?

2021-05-20 20:08 UTC, andrewgettelman commented on src/physics/cam/wv_sat_methods.F90
> +function OldGoffGratch_svp_water(t) result(es)
I'm fine with removing old goff gratch.

2021-05-20 20:24 UTC, sjsprecious commented on src/physics/cam/wv_sat_methods.F90
> +integer, parameter :: VLEN = 128 ! vector length for a GPU kernel
Hi @nusbaume , thanks for your question. We tested this VLEN number from 32 to 256 and found the test with VLEN = 128 ran slightly faster. In general we set VLEN as a multiple of 32 (the size of a warp) but the optimal number could be GPU/system-dependent and even GPU-kernel-dependent. I think it is good to make this parameter configurable and I would like to know which method generally works better for other users.

2021-05-20 21:11 UTC, nusbaume commented on src/physics/cam/wv_sat_methods.F90
> +integer, parameter :: VLEN = 128 ! vector length for a GPU kernel
Thanks @sjsprecious for the explanation!  I imagine that the best long-term solution would be to have CIME set it (especially if other components are GPU-enabled as well).  However, if the plan is to focus only on CAM for the foreseeable future then maybe just adding a namelist option would be the simplest and most user-friendly solution.

Of course this is just my own personal view.  Maybe the other CAM SEs have a different opinion (@Katetc @gold2718 @cacraigucar @peverwhee @fvitt)?

2021-05-20 21:28 UTC, johnmauff commented on src/physics/cam/wv_sat_methods.F90
> +integer, parameter :: VLEN = 128 ! vector length for a GPU kernel
I would prefer to keep the setting of the vector length simple for now.  I would suggest that we defer anything more complex then just a simplex parameter statement as future work.

2021-05-20 21:50 UTC, andrewgettelman commented on src/physics/cam/wv_sat_methods.F90
> +integer, parameter :: VLEN = 128 ! vector length for a GPU kernel
Simple is good. Definitely stay out of CIME for now. If this appears in more than one routine in the code however (and would have the same value in all routines), making it namelist might be wise, and easy to change. 

If this value is specific to wv_sat_methods, then the hard coding is fine.

2021-05-20 22:05 UTC, peverwhee approved these changes

2021-05-24 15:42 UTC, cacraigucar approved these changes

2021-05-24 15:42 UTC, cacraigucar commented on Externals.cfg
> +tag = cime5.8.44
@Katetc When you begin regression testing, if cime is answer changing, you should make a separate tag with just this change prior to bringing in this PR.  Note that #303 will be updating to cime5.8.42, so it may help in this regard.

2021-05-24 15:42 UTC, cacraigucar commented on src/physics/cam/wv_sat_methods.F90
> +function OldGoffGratch_svp_water(t) result(es)
@Katetc Please remove OldGoffGratch before you setup and run your testing.

2021-06-02 05:44 UTC, gold2718 approved these changes
I agree with the other requests for changes so I won't add a request here.
I do have one question int wv_sat_methods.F90 that could lead to a small change (or to an answer that would help me understand the code changes).

2021-06-02 15:58 UTC, sjsprecious commented on src/physics/cam/wv_sat_methods.F90
> +!$acc declare create (epsilo, tmelt, tboil, default_idx, omeps, h2otrip, ttrice)
Thanks @gold2718 for your comments. The subroutines in the `wv_sat_methods.F90` code will only use the value of `default_idx` from CPU. Thus you are right that the `acc declare create` for `default_idx` is not necessary here. I just removed it.

2021-06-21 19:35 UTC, merged