Bug fixes for WACCMX
ESCOMP/CAM pull request #382
Opened 2021-05-26 18:59 UTC by fvitt

Misc bug fixes for WACCMX:
  - array out of bounds issue in electric potential solver when compiled with some compilers (#363)
  - error writing physics buffer fields to restart file in large simulations (#376)
  - initialization of ion and electron temperatures when not read from IC file (#377)
  - do not attempt to advect N2 when SE CSLAM is used (#379)
  
fixes #363 
fixes #376
fixes #377 
fixes #379

2021-06-24 21:59 UTC, cacraigucar requested changes

2021-06-24 21:59 UTC, cacraigucar commented on Externals.cfg
> +tag = cime5.8.38
cime is now up to 44.  We need to make sure we don't digress.

2021-06-24 21:59 UTC, cacraigucar commented on src/ionosphere/waccmx/edyn_mudcom.F90
> +      real(r8) :: a(lda,*)
Why use "*" instead of ":" (assumed size vs assumed shape)?  This occurs in multiple places in this module.  I believe these should all be assumed shape.

2021-06-24 21:59 UTC, cacraigucar commented on src/physics/cam/waccmx_phys_intr.F90
> +#endif
Why are you using this #ifdef?  The routine which is encapsulated is compiled, so that is not the reason.  Perhaps this should be a namelist (but the one place I see the calling routine, it is already only calling this when it is ionosphere).  I'm wondering if there is any need at all for this "if".

2021-06-24 21:59 UTC, cacraigucar commented on src/utils/physconst.F90
> +    allocate(thermodynamic_active_species_kc(0:i))
I'd heard about something which is not supposed to be manipulated later (advected?) being put into index 0.  I assume this may be the mod which enables this.  I'm not real keen on having special indices that have special treatment.  I will leave this to others who understand the code more completely to weigh in on this.  I just wanted to express my discomfort.

2021-06-25 14:57 UTC, fvitt commented on src/physics/cam/waccmx_phys_intr.F90
> +#endif
The `ion_electron_temp_timestep_init` routine is available only if the code in `src/physics/waccmx` is compiled.

2021-06-25 15:58 UTC, fvitt commented on src/ionosphere/waccmx/edyn_mudcom.F90
> +      real(r8) :: a(lda,*)
The way the code is written (adopted F77 legacy code), assumed size is needed.  Actual arguments of different shapes are passed to the routines throughout the code.

2021-06-25 16:02 UTC, fvitt commented on src/utils/physconst.F90
> +    allocate(thermodynamic_active_species_kc(0:i))
Yes, the element 0 is for N2 which is not prognosed in the model and is not advected.

2021-07-07 01:49 UTC, nusbaume approved these changes
Looks good to me!  Just a couple optional requests to change the log output, and one question related to possibly skipping a file read.

2021-07-07 19:57 UTC, fvitt commented on src/physics/waccmx/ion_electron_temp.F90
> +                                       //' Set TElec to NaN'
That would make sense.

2021-07-07 19:57 UTC, fvitt commented on src/physics/waccmx/ion_electron_temp.F90
> +       if (found) then
Agree.

2021-07-07 19:58 UTC, fvitt commented on src/physics/waccmx/ion_electron_temp.F90
> +          if (masterproc) write(iulog,*) 'ion_electron_temp_inidat: Not able to read temperature from IC file.' &
Makes sense.

2021-07-08 17:58 UTC, gold2718 approved these changes
I have a couple of comments and questions but nothing that looks like it needs fixing (but please look at the question in election_ion_temp.F90).

2021-07-08 17:58 UTC, gold2718 commented on src/physics/waccmx/ion_electron_temp.F90
> +          call pbuf_set_field(phys_buffer_chunk,index_ti,phys_state(lchnk)%t(:ncol,:),start=(/1,1/), kount=(/ncol,pver/))
At line 278, the `pbuf_set_field` calls are within a `if (index_te>0) then` block. Why not here?

2021-07-08 19:29 UTC, peverwhee approved these changes

2021-07-09 20:16 UTC, fvitt commented on src/physics/waccmx/ion_electron_temp.F90
> +          call pbuf_set_field(phys_buffer_chunk,index_ti,phys_state(lchnk)%t(:ncol,:),start=(/1,1/), kount=(/ncol,pver/))
Good catch.

2021-07-13 15:56 UTC, cacraigucar reviewed
When cam6_3_026 is tagged, please merge your code forward.  At that point, I will verify that the cime version is okay and submit my approval. I've tentatively slated this PR for cam6_3_027.

2021-07-13 16:39 UTC, jtruesdal commented
Thanks Cheryl! Will merge as requested.

jt

On Tue, Jul 13, 2021 at 9:56 AM cacraigucar ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> When cam6_3_026 is tagged, please merge your code forward. At that point,
> I will verify that the cime version is okay and submit my approval. I've
> tentatively slated this PR for cam6_3_027.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/382#pullrequestreview-705372399>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACG3NXYASXYB2JHTJHDG7E3TXRO2BANCNFSM45SVREQA>
> .
>

2021-07-14 18:56 UTC, jtruesdal commented on src/utils/physconst.F90
> +      if ((.not. LEN(TRIM(dry_air_species(i)))==0).and.(TRIM(dry_air_species(i))/='N2')) then
@PeterHjortLauritzen just checking if you took a look at the fvitt changes to physconst and approve them (PR #382)?

2021-07-14 19:09 UTC, PeterHjortLauritzen approved these changes
@jtruesdal yes I approve. Just had some clarifying questions

2021-07-20 23:08 UTC, merged

2021-07-22 19:43 UTC, cacraigucar reviewed
Post merge approval of Externals.cfg not being changed.