Support for the CAM Perturbed Parameter Ensemble (PPE)
ESCOMP/CAM pull request #398
Opened 2021-07-07 02:36 UTC by Katetc

Code to bring many hardcoded parameters to namelist options so that we can experiment with model sensitivity to them. The tag including these code changes will be used in the CAM PPE. 

Note: There could be updates to the CLM tag (to conform to the CLM PPE) and to the PUMAS tag (only to improve comment documentation) before this PR goes in. These changes will likely be done Wednesday 7-7.

fixes #313

2021-07-07 04:50 UTC, gold2718 requested changes
The new namelist items really need some documentation (see notes). Otherwise, this looks okay.

2021-07-07 04:50 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +Radius of detrained liquid drops as they are used in the CLUBB parameterization.
Units?

2021-07-07 04:50 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +Radius of detrained ice drops as they are used in the CLUBB parameterization.
Units?

2021-07-07 04:50 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +in the CLUBB parameterization.
Units?

2021-07-07 05:02 UTC, andrewgettelman commented
Go ahead without me. Can’t see it for a week. 

Hopefully this also has Trude’s CLUBB additions.

Regards,

Andrew

Sent from my iPhone (sorry for typos)
Andrew Gettelman
National Center for Atmospheric Research
1850 Table Mesa Dr., Boulder, CO 80304
***@***.***
+1-303-497-1887

> On Jul 6, 2021, at 6:37 PM, Kate Thayer-Calder ***@***.***> wrote:
> 
> ﻿
> @Katetc requested your review on: #398 Support for the CAM Perturbed Parameter Ensemble (PPE) .
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-07 05:04 UTC, andrewgettelman commented
We do NOT need to document the sensitivities. We don’t know what they are: that’s why we are doing this.

Fine to document more specifically if you want.

Else check it in and I can add detail next week.

Thanks,

Andrew

Sent from my iPhone (sorry for typos)
Andrew Gettelman
National Center for Atmospheric Research
1850 Table Mesa Dr., Boulder, CO 80304
***@***.***
+1-303-497-1887

> On Jul 6, 2021, at 8:50 PM, goldy ***@***.***> wrote:
> 
> ﻿
> @gold2718 requested changes on this pull request.
> 
> The new namelist items really need some documentation (see notes). Otherwise, this looks okay.
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Maximum allowed ice number concentration
> +Default: 1000000.e3
> This is a weird way to write 10^9. Why not 1.0e9?
> Also, what are the units here?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Accretion enhancment factor
> +Default: 1
> This needs more documentation. What is enhanced if you change this value? By how much?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Autoconversion prefactor
> +Default: 0.001
> This needs more documentation. What changes if you change this value? By how much? What are the units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Autoconversion nd exponent
> +Default: -1.1
> This needs more documentation. What happens if you change this value? By how much?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Autoconversion lwp exponent
> +Default: 2.47
> This needs more documentation. What happens if you change this value?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Size of droplets feezing homogeneously 
> +Default: 1
> This needs more documentation. What are the units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Ice fall speed factor
> +Default: 1
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Ice effective radius factor
> +Default: 25.e-6
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +ccn activated number scale factor
> +Default: 1
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Scaling factor for subgrid vertical velocity (liquid)
> +Default: 1
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Scaling factor for subgrid vertical velocity (ice)
> +Default: 1
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Minimum subgrid vertical velocity (liquid) ms-1
> +Default: 0.2
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Minimum subgrid vertical velocity (ice) ms-1
> +Default: 0.001
> This needs more documentation. What happens if you change this value? By how much? Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Tunable entrainment rate in ZM deep convection scheme.                     
> +Default: set by build-namelist
> Any units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Tunable parcel temperature perturbation  in ZM deep convection scheme.
> +Default: set by build-namelist
> Units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Tunable triggering threshold for convection in ZM deep scheme.
> +Default: set by build-namelist
> Units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > @@ -3529,6 +3665,21 @@ clubb_up2_vp2_factor increases the values of up2 and vp2 at the surface.
>  Coefficient for gustiness near ground.
>  </entry>
>  
> +<entry id="clubb_detliq_rad" type="real" category="pblrad"
> +       group="clubb_params_nl" valid_values="" >
> +Radius of detrained liquid drops as they are used in the CLUBB parameterization.
> Units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > @@ -3529,6 +3665,21 @@ clubb_up2_vp2_factor increases the values of up2 and vp2 at the surface.
>  Coefficient for gustiness near ground.
>  </entry>
>  
> +<entry id="clubb_detliq_rad" type="real" category="pblrad"
> +       group="clubb_params_nl" valid_values="" >
> +Radius of detrained liquid drops as they are used in the CLUBB parameterization.
> +</entry>
> +
> +<entry id="clubb_detice_rad" type="real" category="pblrad"
> +       group="clubb_params_nl" valid_values="" >
> +Radius of detrained ice drops as they are used in the CLUBB parameterization.
> Units?
> 
> In bld/namelist_files/namelist_definition.xml:
> 
> > +Temperature at which detrained water is classified as entirely ice (no liquid) 
> +in the CLUBB parameterization.
> Units?
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-07 15:23 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Default: set by build-namelist
peanut gallery here. It's 1/m

2021-07-07 15:23 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Default: set by build-namelist
temperature, so K

2021-07-07 15:23 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Default: set by build-namelist
J/kg

2021-07-07 15:26 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Radius of detrained liquid drops as they are used in the CLUBB parameterization.
m

2021-07-07 15:26 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +Radius of detrained ice drops as they are used in the CLUBB parameterization.
m

2021-07-07 15:26 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +in the CLUBB parameterization.
K

2021-07-07 15:37 UTC, adamrher commented
Hopefully I'm being helpful --I added some the units for most of what steve flagged. Also, I sound like a broken record, but the namelists ```cldfrc_dp1``` and ```cldfrc_dp2``` are hard coded into clubb_intr, since those namelists are linked up with macropdriver (which we don't use in cam6 physics). So a change like this needs to be added to clubb_intr:

```
         (-) deepcu(i,k) = max(0.0_r8,min(0.1_r8*log(1.0_r8+500.0_r8*(cmfmc(i,k+1)-cmfmc_sh(i,k+1))),0.6_r8))
         (+) deepcu(i,k) = max(0.0_r8,min(dp1*log(1.0_r8+dp2*(cmfmc(i,k+1)-cmfmc_sh(i,k+1))),0.6_r8))
```

with ```dp1``` and ```dp2``` linked up to those namelists. I have made these changes in my pending PR: https://github.com/ESCOMP/CAM/pull/352

2021-07-07 15:49 UTC, gold2718 commented
> We do NOT need to document the sensitivities. We don’t know what they are: that’s why we are doing this.
> Fine to document more specifically if you want.

Right. I do not expect that we can document values (yet) but we should document what changing these values changes in the computation.

2021-07-07 15:58 UTC, cacraigucar requested changes

2021-07-07 15:58 UTC, cacraigucar commented on cime_config/usermods_dirs/scam_twp06/user_nl_cam
> +iradsw = 1
The comparison says there is no "newline at the end of the file".  I've never seen this before and just suggest you check the last line to make sure there isn't something funky at the end.

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +     call endrun(sub//": ERROR: clubb_detphase_lowtemp must be less than 268.15 K")
Should the error message say "less than or equal" or does the if statement need to revised?

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +            dum1 = ( 268.15_r8 - state1%t(i,k) ) / ( 268.15_r8 - dt_low )
I keep seeing `268.15_r8` throughout the code.  While you didn't introduce it, you did utilize it a couple of times.  I would suggest it would make sense to create a parameter with this value and use it throughout.

2021-07-07 15:58 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_c6rtc                                      > 1.0     </clubb_c6rtc>
Are all of these newly introduced default values the default that CLUBB is currently using (i.e. will this change answers for any existing CAM6 runs)?  I don't think this tag should be changing values for current code.

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/micro_mg_cam.F90
> +!++ trude for namelist
Remove this comment from here and all places below

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/micro_mg_cam.F90
> +!-- trude
Remove this comment here and all similar places below

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/micro_mg_cam.F90
> +real(r8)          :: micro_mg_max_nicons = 100000.e3_r8 ! max allowed ice number concentration
These should probably all be set to UNSET here and depend on the defaults being set in namelist_defaults.

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/micro_mg_cam.F90
> +           micro_mg_accre_enhan_fact , &  !++ trude
Remove the !++ trude comments here and below

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/micro_mg_cam.F90
> +              packed_melt, packed_meltstot, packed_meltgtot,            packed_homo,            &
This line lost some spaces and no longer lines up like it once did.

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/micro_mg_cam.F90
> +      call handle_errmsg(errstring, subname="micro_mg_  tend")
Spaces before `tend` need to be removed

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/microp_aero.F90
> +   real(r8) :: microp_aero_wsubi_min = 0.001_r8  ! subgrid vertical velocity (ice) minimum
These should be set to UNSET and use the namelist_default values

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/microp_aero.F90
> +   call mpibcast(microp_aero_wsubi_min, 1, mpir8, 0, mpicom)
We've been updating to the newer mpi_bcast calls as we encounter the old ones.  Please update them and add error handling.

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/microp_aero.F90
> +   wsubi(:ncol,:top_lev-1) = wsubi_min !0.001_r8
The comments should be removed as these are namelist values and are subject to changed values.

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/zm_conv.F90
> +   real(r8) :: capelmt = 70._r8  ! namelist configurable:
Remove the initialization value as it is set by the namelist or initlialize to UNSET

2021-07-07 15:58 UTC, cacraigucar commented on src/physics/cam/zm_conv.F90
> +   real(r8) :: dmpdz_param = -1.e-3_r8 ! New namelist configurable
Remove the initializations or initialize to UNSET for these two variables as well.

2021-07-07 15:58 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +Default: 1
@Katetc These requests are being made as this file autogenerates the namelist web page that users refer to when setting namelist values.  Because of this, this information is important to have accurate and complete.

2021-07-07 16:30 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +     call endrun(sub//": ERROR: clubb_detphase_lowtemp must be less than 268.15 K")
I think the `if` statement is correct. If they are equal, I think you might get a divide by zero issue down on line 3130.

@Katetc, what happens if `clubb_detphase_lowtemp` is very close to `265.15` (e.g., 265.1499999999)?

2021-07-07 21:39 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_c6rtc                                      > 1.0     </clubb_c6rtc>
These default values are the same ones currently used by clubb as of cam6_3_025. This tag does change answers slightly because of one microphysics parameter that went from a hard-coded volume to a volume calculated based on radius. It is non-climate changing.

2021-07-07 22:45 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +     call endrun(sub//": ERROR: clubb_detphase_lowtemp must be less than 268.15 K")
Later on, the equation is if the state temp is between 268.15 and low, then ( 268.15 - temp ) / (268.15 - low), which gives a fraction of the cloud water to be ice and the remainder is liquid. If the "low" value is very close to 268.15, and then the state temperature somehow manages to be between 268.15 and 268.1499, then the numerator and denominator would be equivalently sized. This math shouldn't blow up.

2021-07-07 23:01 UTC, Katetc commented
Hi all. I made a first pass at addressing these comments, but I know there are still some more to do (especially micro_mg_cam). @andrewgettelman, yes, this does include Trude's additions of c6thl and c6thlb in clubb. @adamrher Thank you! Those units were super helpful. And I totally stole your code for dp1 and dp2 wholesale from your PR. Please have a look and make sure I've got it in there correctly, but I think that is addressed now.

2021-07-13 15:31 UTC, cacraigucar requested changes

2021-07-13 15:31 UTC, cacraigucar commented on src/physics/cam/microp_aero.F90
> +
If Francis' proposed initlialization of tendnd in dropmixnuc resolves the NaN problem, please remove this section of code.

2021-07-13 21:52 UTC, gold2718 requested changes
I have some questions that *could* result in code changes but they are not required.
I _would_ like us to be using standard unit language so that we can use them with the CCPP. Since these changes are in XML comment blocks, it should not require re-running all the tests (just run one test or run xmllint).

2021-07-13 21:52 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +                                     / (4._r8*3.14_r8*50.e-6_r8**3*500._r8)     ! Shallow Convection
Is this version of `500._r8` also `dp2`?
Is `50.e-6_r8` something that should have a name?
Why is `3.14_r8` being used here instead of `pi`? Is it not supposed to be `pi`?

2021-07-13 23:19 UTC, cacraigucar approved these changes

2021-07-14 03:13 UTC, nusbaume requested changes
Looks good to me, although I do have some suggestions which will hopefully be easy to implement.

2021-07-14 18:01 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +                                     / (4._r8*3.14_r8*50.e-6_r8**3*500._r8)     ! Shallow Convection
I just added the _r8 here so that the check test would pass on Izumi. This code is in no way related to the changes for the PPE. I have no good answers to these questions, though I suspect they might be "no, probably, ask Pete, and it is probably Pi, but not scoped to rewrite clubb_inter in this PR."

2021-07-14 18:03 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_berg_eff_factor microphys="mg2"  >  1.D0    </micro_mg_berg_eff_factor>
Yes, we would like the ability to change these to tune MG2 and MG3 separately.

2021-07-14 18:15 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_max_nicons                  >  100000.D3    </micro_mg_max_nicons>
Counting zeros is hard! :) It's actually D8. I'll fix it.

2021-07-14 18:17 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +<entry id="clubb_c6rt" type="real" category="pblrad"
Yes, these get twiddled-with quite a lot. Adding in all of the defaults here would take a lot more time than I'm supposed to be using for this PR.

2021-07-14 18:23 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +<entry id="clubb_c6rt" type="real" category="pblrad"
I've always felt uncomfortable with labeling the defaults here and in the namelist_defaults file as it is too easy to get out-of-date and give the user misleading information.  I concur with Kate's decision to not add them, especially since they are in flux.

2021-07-14 18:24 UTC, Katetc commented on src/physics/cam/zm_conv_intr.F90
> +                  zmconv_microp, no_deep_pbl, zmconv_tiedke_add, &
I removed the optional logic so it will always be passed in now.

2021-07-14 18:52 UTC, nusbaume approved these changes
Thanks for answering my questions/concerns!  It looks great now, although I do have one last question.

2021-07-14 18:52 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +Default: 1.0e9
I guess as an example of "we shouldn't have defaults listed in two different places", should this say `1.0e8` instead?

2021-07-14 20:36 UTC, peverwhee approved these changes

2021-07-16 17:34 UTC, andrewgettelman commented on src/physics/cam/clubb_intr.F90
> +                                     / (4._r8*3.14_r8*50.e-6_r8**3*500._r8)     ! Shallow Convection
Agreed: we need to get this done, not fix clubb_intr issues. Can be done later in a different issue or PR.

2021-07-16 18:56 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +                                     / (4._r8*3.14_r8*50.e-6_r8**3*500._r8)     ! Shallow Convection
Agreed (which is why it is a question and not a request).
This is a good item to address during conversion to the CCPP.

2021-07-16 19:02 UTC, cacraigucar approved these changes

2021-07-16 19:15 UTC, gold2718 approved these changes
Tentatively approving. Please make the requested very minor changes before merging (and complete tests of course).

2021-07-16 19:15 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +Default: 1.0e9
This is inconsistent with what is in namelist_defaults.xml
Which is correct?

2021-07-16 19:15 UTC, gold2718 commented on doc/ChangeLog
> +- Adding in namelist parameters and supporting code to be used in the CAM PPE
Just needs issue number added:
```suggestion
- #313: Adding in namelist parameters and supporting code to be used in the CAM PPE
```

2021-07-16 19:15 UTC, gold2718 commented on doc/ChangeLog
> +izumi/pgi/aux_cam:
Please fill out this report (including the expected FAIL for the DAE test).

2021-07-17 00:13 UTC, merged