Science Updates for CESM2.2 release and cam_development
ESCOMP/CAM pull request #401
Opened 2021-07-13 15:24 UTC by jtruesdal

These mods are necessary to fix science bugs, improve algorithms and numerical stability of SE dycore. Namelist default changes to the gravity wave parameterization and updates to the Test Tracers will also affect the other dycores. This PR will close issue #392.

Improvements:
- alleviate noise over steep orography
- sponge layer changes for stability
- Changes to TT_CCOSB TT_COSB and TT_lCCOSB for idealized testing of dynamical cores (change to Lauritzen and Thuburn,2012, QJRMS, formulation).
- New parameterization defaults for improved stability and to provide better baseline defaults.

Bug fixes:
- species dependent thermodynamics in WACCM-X
- mods to physconst.F90 for WACCM-x and SE (mid pressure calculation consistency)
- initialization bug in angular momentum diagnostics 

Refactor:
- Remove Rayleigh Friction Parameterization from SE
- remove vertical diffusion code in SE dycore

2021-07-14 16:34 UTC, gold2718 commented
@jtruesdal, the title of this issue says it is for CESM2.2 but you did not select that as a Project. Are these changes for the CESM2.2 branch?
Are these changes also to be put in cam_development?

2021-07-19 22:26 UTC, jtruesdal commented on src/dynamics/se/dp_coupling.F90
> +   use physconst,         only: cpair, cpairv
Will do.

2021-07-19 22:31 UTC, jtruesdal commented on src/dynamics/se/dyn_comp.F90
> +   real(r8)            :: press(1), ptop, tref,z(1)
@PeterHjortLauritzen can correct me if I'm wrong but it looks like they are used in the call to std_atm_height which expects an array argument for press and z.

2021-07-19 22:36 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_comp.F90
> +   real(r8)            :: press(1), ptop, tref,z(1)
Correct

2021-07-20 06:45 UTC, peverwhee approved these changes

2021-07-20 18:03 UTC, PeterHjortLauritzen commented
Cecile brought to our attention that del4 sponge layer settings are hard coded. We have code to move those settings to namelist.

2021-07-20 18:18 UTC, jtruesdal commented
@PeterHjortLauritzen I have finished my testing of the refactored code that generalizes the sponge layer setup and removes the hard coded layer settings.  I will commit the fix for the rest of the reviewers to look at.

2021-07-20 22:32 UTC, nusbaume requested changes
Looks good to me, but I did have some questions and requests.

2021-07-20 22:32 UTC, nusbaume commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +!           dp3d_ref=dp3d_ref,T_ref=T_ref)
Remove commented-out call?

2021-07-21 00:25 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/dimensions_mod.F90
> +  real(r8), public :: nu_s_lev(PLEV)    ! level depedendet del4 T damping
This is following the convention grandfathered in from HOMME that used subscript "s". Sounds good to change. This comment made me realize that we still have nu_s in the code although it is not used. Will clean up!

2021-07-21 00:30 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +            write(iulog,*) 'WARNING: theoretically unstable in sponge; increase se_hypervis_subcycle_sponge'
We had several discussion with @adamrher about this. In high resolution simulations the sponge layer diffusion is quite expensive and we have found empirically that the model is stable with slight violations of the theoretical stability limits. Hence we chose to make it a warning rather than calling endrun ... that said, we get contacted frequently by users for whom them model is blowing up and they are not looking in the atm log file so they don't see the warning (and encouragement to change sub stepping for stability). Long story short ... we advocate to keep the code as is (at least for now)!

2021-07-21 00:33 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +      scale1        = 0.5_r8*(1.0_r8+tanh(2.0_r8*log(pmid(sponge_del4_lev)/press)))!
Actually the vertical profile is from FV and documented in https://journals.sagepub.com/doi/10.1177/1094342011410088 (Peter H. Lauritzen, Art Mirin, John Truesdale, Kevin Raeder, Jeffrey Anderson, Julio Bacmeister and Richard B. Neale, 2011: Implementation of new diffusion/filtering operators in the CAM-FV dynamical core Int. J. High. Perform. C., Vol. 26 (Issue 1), pp. 63–73. DOI:10.1177/1094342011410088 ). 

The details of the profile used for SE have not been published at this point in time. We can add reference.

2021-07-21 00:34 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +      press = pmid(k)
will fix

2021-07-21 00:35 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/control_mod.F90
> +  ! nu_div*sponge_del4_nu_fac following a hyperbolic tangent function
Good catch. Yes.

2021-07-21 00:35 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/control_mod.F90
> +  ! Similar for spnge_del4_nu_fac
thanks

2021-07-21 00:39 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/viscosity_mod.F90
> +  dp_thresh=.025_r8  ! tunable coefficient
Code from @mt5555 (Mark Taylor, DOE). We could make it namelist, however, we have not experimented with other values and we do not anticipate having to. If we do decide to do so we can make it namelist. OK with you @nusbaume?

2021-07-21 00:40 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +!           dp3d_ref=dp3d_ref,T_ref=T_ref)
sure

2021-07-21 14:47 UTC, jtruesdal commented on src/dynamics/se/dp_coupling.F90
> +            phys_state(lchnk)%exner (i,k) = (phys_state(lchnk)%pint(i,pver+1) &
Will do.

2021-07-22 17:26 UTC, nusbaume commented on src/dynamics/se/dycore/global_norms_mod.F90
> +            write(iulog,*) 'WARNING: theoretically unstable in sponge; increase se_hypervis_subcycle_sponge'
@PeterHjortLauritzen Thanks for the info!  Keeping it as warning sounds reasonable to me.

2021-07-22 17:37 UTC, cacraigucar approved these changes

2021-07-22 17:41 UTC, nusbaume commented on src/utils/physconst.F90
> +               ispecies = idx_local(icnst)
I don't believe you need `ispecies` here, as it is not being used.

2021-07-22 17:41 UTC, nusbaume commented on src/dynamics/se/dycore/viscosity_mod.F90
> +  dp_thresh=.025_r8  ! tunable coefficient
@PeterHjortLauritzen That sounds like a good plan to me, and I agree that if this value isn't expected to change, then there is no reason to make it a namelist variable.

2021-07-22 17:50 UTC, nusbaume approved these changes
Looks great to me now!  Just a few final (very minor) requests I missed the first go-around.

2021-07-22 18:00 UTC, jtruesdal commented on src/dynamics/se/dycore/dimensions_mod.F90
> +  real(r8), public :: nu_s_lev(PLEV)    ! level depedendet del4 T damping
I renamed nu_s and nu_s_lev to nu_t and nu_t_lev.

2021-07-22 18:02 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +      scale1        = 0.5_r8*(1.0_r8+tanh(2.0_r8*log(pmid(sponge_del4_lev)/press)))!
Added the reference and removed the !.

2021-07-22 18:05 UTC, jtruesdal commented on src/dynamics/se/dycore/control_mod.F90
> +  integer, public :: phys_dyn_cp = 1 !=0; no thermal energy scaling of T increment
Got it.  I'll look over the Fortran Coding Standards wiki before the next PR.

2021-07-22 18:36 UTC, jtruesdal commented on src/utils/physconst.F90
> +               ispecies = idx_local(icnst)
I'll get rid of ispecies here.

2021-07-22 21:26 UTC, PeterHjortLauritzen commented on src/utils/physconst.F90
> +    cappav(:ncol,:,lchnk) = rairv(:ncol,:,lchnk)/cpairv(:ncol,:,lchnk)
Yes this is a bug ("only" impacts WACCM-x applications) that needs to be fixed in the release branch and, as far as I understand, will be tackled in a separate pull request. We have not assessed impacts on simulation but the WACCM-x group did a sanity check with the buggy code and did not report issues.

2021-07-22 21:51 UTC, PeterHjortLauritzen commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_hypervis_subcycle_sponge hgrid="ne0np4CONUS.ne30x8" waccm_phys="1"> 4  </se_hypervis_subcycle_sponge>
I talked to Jim and Marianna and we propose to have the bug fixes and updates be part of the CESM2.3 release rather than updating the CESM2.2 release branch (which would be a lot of work). It will be important to point users to the CESM2.3 release for any spectral-element applications.

Apologies for my wording in the PR - we will update to avoid confusion.

2021-07-23 03:15 UTC, gold2718 requested changes
I think it is important to log namelist values, especially if they are set in the code (see my comment). Did I miss the print statements?

2021-07-23 03:15 UTC, gold2718 commented on doc/ChangeLog
> +	src/utils/physconst.F90
Odd choice here. In the past, we (including you) have listed the file first followed by the change. Why the switch?

2021-07-23 05:02 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> +se_nu_p*se_sponge_del4_nu_fac following a hyperbolic tangent function
corrected

2021-07-23 05:02 UTC, jtruesdal commented on doc/ChangeLog
> +           se_nu_p*se_sponge_del4_nu_fac following a hyperbolic tangent function
corrected

2021-07-23 06:18 UTC, jtruesdal commented on doc/ChangeLog
> +	src/utils/physconst.F90
Why did I do that?  Rewritten for consistency, file first followed by change.

2021-07-23 06:19 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    end if
Logged the sponge del4 configuration.  Noted whether the value was set by the namelist or a default based on the model top.

2021-07-23 06:22 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    nu_max = MAX(MAX(MAXVAL(nu_div_lev(:)),MAXVAL(nu_lev(:))),MAXVAL(nu_t_lev(:)))
Rewritten as suggested.

2021-07-23 15:34 UTC, cacraigucar approved these changes

2021-07-23 15:34 UTC, cacraigucar commented on doc/ChangeLog
> +	- Remove SE Rayleigh Friction Parameterization
Totally at your discretion (i.e. no need to change). I typically combine several files that have the exact same description together and then have the description follow. In this case, build-namelist, user_nl_cam, dyn_comp.F90 could all be grouped together with the "Remove SE Rayleigh Friction Parameterization" description.

2021-07-23 15:44 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    end if
Good point. Thanks!

2021-07-23 22:46 UTC, gold2718 approved these changes
Looking good now, thanks!

2021-07-23 22:46 UTC, gold2718 commented on src/dynamics/se/dycore/global_norms_mod.F90
> +         write(iulog, '(a,i3)')   '  sponge_del4_lev        = ',sponge_del4_lev
FYI, `i0` will use the exact needed number of characters to write out an integer value.

2021-07-24 02:00 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +         write(iulog, '(a,i3)')   '  sponge_del4_lev        = ',sponge_del4_lev
Thanks! It is new information to me and I will change to i0.

2021-07-25 21:07 UTC, fvitt approved these changes

2021-08-19 19:28 UTC, merged