PUMAS Updates
ESCOMP/CAM pull request #409
Opened 2021-08-02 21:03 UTC by andrewgettelman

This PR addresses a series of updates and bug fixes to the CAM microphysics and ice nucleation schemes. 

PR linked to CAM issue #408 

Note: this is ready for SE review, but it will need Science Review. I will advise Julio B. of this when the PR is started. Minor code changes. Major science changes. 

Repeating some of that information below. 

It addresses issues identified in PUMAS issue number 28: 
https://github.com/ESCOMP/PUMAS/issues/28

1, fixes issue Possible removal of ice number limiter....doesn't work with new ice nucleation. PUMAS issue number 20:
https://github.com/ESCOMP/PUMAS/issues/20
2. adds in vapor deposition onto snow as a process
3. Fall speed correction for rain/snow/graupel (namelist option turned on)
4. Option for implicit fall speed (namelist option, initially off)
5. Option for the accretion to see newly autoconverted rain (liquid only, namelist option, initially off).

For the moment, 1 and 2 do not have switches, 3-5 have switches (though 3 is a bug fix). They will need science testing, but I have checked the code is functional in SCAM and 3D CAM, and @Katetc has verified it passes all the standard CAM tests (with lots of answer changes).

2021-08-02 21:59 UTC, cacraigucar requested changes

2021-08-02 21:59 UTC, cacraigucar commented on src/physics/cam/nucleate_ice.F90
> +!            end if
@andrewgettelman This should either be deleted or encased in a new namelist

2021-08-09 19:31 UTC, andrewgettelman commented
Change requested by Cheryl made, and I think I updated the code (commit-add-push). Let me know if I did not do this right!

2021-08-10 21:49 UTC, cacraigucar requested changes

2021-08-10 21:49 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +Default: .true.
The code is initializing this to false.  Is the default really true (and I missed it) or does the code or documentation need to be changed?

2021-08-10 21:57 UTC, andrewgettelman commented on bld/namelist_files/namelist_definition.xml
> +Default: .true.
The default is set to false, so the documentation is wrong. I intend to test and switch it to true at some point, we might do that for the final tag (pending testing). Updating the default now anyway.....corrected

2021-08-16 19:59 UTC, gold2718 approved these changes
Fix typo (unless I misread it), otherwise okay.

2021-08-16 19:59 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +If true, then the autoconvered liquid is added to rain and removed from cloud before accretion is estimated.
autoconverted?
```suggestion
If true, then the autoconverted liquid is added to rain and removed from cloud before accretion is estimated.
```

2021-08-16 20:15 UTC, fvitt approved these changes

2021-08-16 20:37 UTC, peverwhee approved these changes

2021-08-16 22:37 UTC, nusbaume approved these changes
Looks good, although there might be some typos in some history variable descriptions (?).

2021-08-16 22:37 UTC, nusbaume commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld ('INondust',  (/ 'lev' /), 'A','1/m3/s','Number Concentation dust (out) from ice_nucleation')
Should all of these say `Concentration` (note missing "r")?  Also, should their descriptions include the word `tendency` somewhere, as they are now per second?

2021-08-16 22:37 UTC, nusbaume commented on src/physics/cam/nucleate_ice_cam.F90
> +   call addfld('NIMEY', (/ 'lev' /), 'A', '1/m3/s', 'Activated Ice Number Concentation tendency due to meyers deposition')
Should all of these say `Concentration` (note missing "r")?

2021-08-17 15:54 UTC, andrewgettelman commented on src/physics/cam/nucleate_ice_cam.F90
> +   call addfld('NIMEY', (/ 'lev' /), 'A', '1/m3/s', 'Activated Ice Number Concentation tendency due to meyers deposition')
Corrected

2021-08-17 15:54 UTC, andrewgettelman commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld ('INondust',  (/ 'lev' /), 'A','1/m3/s','Number Concentation dust (out) from ice_nucleation')
Corrected

2021-08-17 15:55 UTC, andrewgettelman commented on bld/namelist_files/namelist_definition.xml
> +If true, then the autoconvered liquid is added to rain and removed from cloud before accretion is estimated.
corrected

2021-09-21 02:50 UTC, JulioTBacmeister approved these changes
Like the science behind the changes 1-4.  Haven't quite understood 5 (ACCRE).   #6 in the document (IFS replication) seems like a good idea but don't know what it entails.  Approving PR.

2021-12-06 18:05 UTC, cacraigucar approved these changes

2022-01-19 20:34 UTC, adamrher commented
@Katetc just a heads up in case you hadn't seen it, but cam_dev turns on mg3 in bld/configure
```
elsif ($phys_pkg eq 'cam_dev') {
    $microphys_pkg = 'mg3';
}
```
Does that mess anything up?

2022-01-19 21:25 UTC, cacraigucar commented on src/physics/cam_dev/micro_mg_cam.F90
> +
Not crazy about having a shadow version of the interface code specific for cam_dev when it only has a few lines of changes.  I am okay with this if the version in src/physics/cam is expected to be more or less static.  

That does bring up though -- what about the pack/unpack removal?  Will it occur in both versions?  It would be good to do that as the pack/unpack is problematic at times.  If this doesn't preclude removing it from both the cam and cam_dev versions and that is expected to be the last modification to src/physics/cam version, then I am fine with this.

2022-01-19 21:55 UTC, Katetc commented
@adamrher That doesn't mess anything up. It really just turns on prognostic graupel, which we called "mg3". There's no specific configure flag for pumas as all of the updates are controlled by singular namelist options at this point.  Though, it really wouldn't be hard to add one if it makes people feel better...

2022-01-19 21:56 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Oops, yes, I changed it to true but forgot to update this. :)

2022-01-19 21:58 UTC, Katetc commented on src/physics/cam_dev/micro_mg_cam.F90
> +
My current pack/unpack branch is based off the older pumas micro_mg_cam file currently. My plan is to get that working and then "merge up" to the new version of micro_mg_cam. So, both versions will get the code change. And then, I hope to never touch the old micro_mg_cam again. I, also, do not want two copies of this file to maintain going forward.

2022-01-19 22:42 UTC, nusbaume approved these changes
Looks good to me, thanks!

2022-01-19 23:31 UTC, andrewgettelman commented
W.R.T 'mg3': we don't need this option  for pumas going into cam_dev. It was to select mg2 or mg3 being compiled so we could avoid changing answers with mg2. If you want mg2 (no graupel) functionality with PUMAS, there is namelist for that (do_graupel = .false.). For now that is the default (doesn't matter for 100km simulations), but we can change the namelist default at any time.

2022-01-19 23:43 UTC, cacraigucar commented
> W.R.T 'mg3': we don't need this option for pumas going into cam_dev. It was to select mg2 or mg3 being compiled so we could avoid changing answers with mg2. If you want mg2 (no graupel) functionality with PUMAS, there is namelist for that (do_graupel = .false.). For now that is the default (doesn't matter for 100km simulations), but we can change the namelist default at any time.

@andrewgettelman - Based on what you are saying, it sounds like selecting version numbers is now obsolete in the cam_dev version?  If so,  I believe that the cam_dev/micro_mg_cam.F90 needs a major overhaul to remove the version selection in it.  I am fine with this being a new issue and the code goes in with version selection in it, to not hold this tag up.

2022-01-19 23:47 UTC, andrewgettelman commented
@cacraigucar I guess I spoke too soon: I forgot about the configure call needed to add the extra constituents for MG3. So it's still needed I guess. At least until we get to the CCPP I think....

2022-01-20 20:41 UTC, gold2718 requested changes
I have some questions and one comment change request.

2022-01-20 20:41 UTC, gold2718 commented on src/physics/cam/macrop_driver.F90
> +  use micro_pumas_utils, only: rhow
I don't think we need to make any changes but isn't `micro_pumas` sort of redundant?

2022-01-20 20:41 UTC, gold2718 commented on src/physics/cam_dev/micro_mg_cam.F90
> +module micro_mg_cam
With all the renaming going on, is there a reason this module (and the one in physics/cam) is not getting the new name (e.g., `micro_pumas_cam`)?

2022-01-20 20:41 UTC, gold2718 commented on src/physics/cam_dev/micro_mg_cam.F90
> +   call addfld ('VAPDEPSO',   (/ 'lev' /), 'A', 'kg/kg/s',  'Vapor deposition onto snow'                            )
This seems to be a rate (as are many above). Should rate be in the name?

2022-01-21 17:56 UTC, fvitt approved these changes
Took a quick look -- seems okay to me.

2022-01-21 21:43 UTC, Katetc commented on src/physics/cam/macrop_driver.F90
> +  use micro_pumas_utils, only: rhow
I suppose so? I was originally thinking of it as "microphysics scheme: specifically PUMAS" but, I guess for these files there won't be any other scheme options. I don't think it's confusing or anything though.

2022-01-21 23:05 UTC, Katetc commented on src/physics/cam_dev/micro_mg_cam.F90
> +module micro_mg_cam
Well, was going to avoid that extra hour of work, but I went ahead and did it today.

2022-01-21 23:05 UTC, Katetc commented on src/physics/cam_dev/micro_mg_cam.F90
> +module micro_mg_cam
Namelist names still have micro_mg in them, though. And that's a bigger job for the future.

2022-01-21 23:10 UTC, Katetc commented on src/physics/cam_dev/micro_mg_cam.F90
> +   call addfld ('VAPDEPSO',   (/ 'lev' /), 'A', 'kg/kg/s',  'Vapor deposition onto snow'                            )
The variable name? Or the long name/comment? I'll leave it up to @andrewgettelman if he wants to change or update the descriptions for all of these variables.

2022-01-21 23:48 UTC, andrewgettelman commented on src/physics/cam_dev/micro_mg_cam.F90
> +   call addfld ('VAPDEPSO',   (/ 'lev' /), 'A', 'kg/kg/s',  'Vapor deposition onto snow'                            )
I think Steve was referring to the long name. We are definitely not changing the variable name. @Katetc if it's trivial to add 'Tendency' to the long name here, that would be fine. Otherwise we can do it later in a separate issue.

2022-01-24 16:25 UTC, Katetc commented on src/physics/cam_dev/micro_mg_cam.F90
> +   call addfld ('VAPDEPSO',   (/ 'lev' /), 'A', 'kg/kg/s',  'Vapor deposition onto snow'                            )
I started doing it on Friday and there are more than the above four variables with per-second units and no "tendency" or "rate of" in the long name. Many, many more. I would say it is not trivial to change all of them. I think this might be a good project for another Andrew PR.

2022-01-24 16:37 UTC, andrewgettelman commented on src/physics/cam_dev/micro_mg_cam.F90
> +   call addfld ('VAPDEPSO',   (/ 'lev' /), 'A', 'kg/kg/s',  'Vapor deposition onto snow'                            )
> I started doing it on Friday and there are more than the above four variables with per-second units and no "tendency" or "rate of" in the long name. Many, many more. I would say it is not trivial to change all of them. I think this might be a good project for another Andrew PR.

If it's difficult, let's skip it for this PR please. I'm happy to do it once this and the Pack/unpack are removed. We can open an issue and assign it to me.

2022-01-24 17:52 UTC, peverwhee approved these changes

2022-01-25 17:19 UTC, gold2718 approved these changes
The rest of the requests will be handled in #508.

2022-01-27 18:51 UTC, peverwhee approved these changes

2022-01-27 19:46 UTC, fvitt approved these changes

2022-01-27 19:50 UTC, cacraigucar commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
For some reason this did not go in the code when I entered it previously.  

I'm not crazy about keeping the name in the file the same, but repurposing it with different units and longname. I'm not sure if this will cause problems for users comparing CAM6 and cam_dev runs. Thoughts? @andrewgettelman @adamrher

2022-01-27 19:59 UTC, andrewgettelman commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
The issue is that the code itself changed. The old unit does not make sense in the new code. I don't think people are going to be comparing across versions, and I don't like the old method and unit anymore anyway. So I think we go with it: definitely do not want to make the new version backward compatible here.

2022-01-27 20:12 UTC, Katetc commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
I think Cheryl is suggesting here that we change the variable names also, in order to make this extra super evident that the code itself changed. She's advocating for even less backward compatibility here.

2022-01-27 20:13 UTC, Katetc commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
And I'm voting with her.

2022-01-27 20:18 UTC, cacraigucar commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
Yes, that is my request Kate - that the variable names be changed in the cam_dev version

2022-01-27 20:33 UTC, nusbaume approved these changes
Still looks good to me!  Just two not important nit-picks.

2022-01-27 20:33 UTC, nusbaume commented on src/physics/cam/nucleate_ice_cam.F90
> +                 INhet(i,k) = (niimm(i,k) + nidep(i,k))   ! #/m3, nimey not in cirrus
Should the comment here say `#/m3/s`?  Also not sure if the outer parentheses are needed.

2022-01-27 20:33 UTC, nusbaume commented on src/physics/cam/nucleate_ice_cam.F90
> +                 INhet(i,k) = (niimm(i,k) + nidep(i,k))   ! #/m3, nimey not in cirrus
Not sure if the outer parentheses are needed here?

2022-01-27 20:33 UTC, nusbaume commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
I also want to cast my vote in with Cheryl and Kate.  Otherwise I can already see a bunch of "These variables are way different!" forum posts that we all will have to deal with.

2022-01-27 21:13 UTC, Katetc commented on src/physics/cam/nucleate_ice_cam.F90
> +                 INhet(i,k) = (niimm(i,k) + nidep(i,k))   ! #/m3, nimey not in cirrus
I think they are not needed, but also outside of the modifications of this PR.

2022-01-27 21:31 UTC, gold2718 commented
@Katetc: The description block of this PR does not seem to be formatted in a way that allows GitHub to directly manage the linked issues. Please follow the syntax outlined in the PR instructions (section 4 of [submit section](https://github.com/ESCOMP/CAM/wiki/CAM-Development-Workflow-in-GitHub#how-to-submit-code-changes-to-be-included-in-escompcam), see note about [correct syntax](https://help.github.com/en/articles/closing-issues-using-keywords)).

2022-01-27 21:33 UTC, cacraigucar approved these changes

2022-01-27 21:33 UTC, cacraigucar commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
Thanks for the change

2022-01-27 21:36 UTC, gold2718 approved these changes
Approving, however, the ChangeLog does not look complete. Please address my comments / questions in there.

2022-01-27 21:36 UTC, gold2718 commented on doc/ChangeLog
> +- Change number conentrations to number concentration tendencies in history files
What about specific cam_dev changes?

2022-01-27 21:36 UTC, gold2718 commented on doc/ChangeLog
> +cheyenne/intel/aux_cam:
Why is the rest of the test section missing?

2022-01-27 21:52 UTC, Katetc commented on doc/ChangeLog
> +- Change number conentrations to number concentration tendencies in history files
I was working on the ChangeLog after running regression tests when I realized that there were too many baseline differences, and the changes I was documenting here were likely only meant for cam_dev. And then the emails started. I promise to revisit and complete the ChangeLog before the final merge.

2022-01-27 21:52 UTC, Katetc commented on doc/ChangeLog
> +cheyenne/intel/aux_cam:
I was working on the ChangeLog after running regression tests when I realized that there were too many baseline differences, and the changes I was documenting here were likely only meant for cam_dev. And then the emails started. I promise to revisit and complete the ChangeLog before the final merge.

2022-01-27 23:26 UTC, andrewgettelman commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
Is the intent to rename NIHF in the new cam_dev code? If this is homogeneous freezing it could be just NIHF-->NIHOM for the output, and remove NIHF for PUMAS. Is that the proposal here? Or other variables too?

2022-01-27 23:31 UTC, Katetc commented on src/physics/cam/nucleate_ice_cam.F90
> +      call addfld('NIHF',  (/ 'lev' /), 'A', '1/m3', 'Activated Ice Number Concentration due to homogenous freezing')
So, all of the variables with updated units of tendency in cam_dev only in nucleate_ice_cam.F90 now have "TEN" at the end of the history variable name. So NIHF is now NIHFTEN, and NIDEP is now NIDEPTEN, for all of these variables in a cam_dev configuration only (no changes otherwise).

2022-01-31 18:33 UTC, cacraigucar reviewed
The following three tests have an error as have the error:

[22] /home/katec/sandboxes/PUMASDevelopmentupdater/src/physics/pumas-frozen/micro_pumas_data.F90, line 395: Error occurred in MICRO_
PUMAS_DATA:MGFIELDPOSTPROC_ACCUMULATE

    FAIL PLB_D_Ln9_Vmct.ne5_ne5_mg37.QPC5.izumi_nag.cam-ttrac_loadbal0 RUN time=276
    FAIL PLB_D_Ln9_Vmct.ne5_ne5_mg37.QPC5.izumi_nag.cam-ttrac_loadbal1 RUN time=561
    FAIL PLB_D_Ln9_Vmct.ne5_ne5_mg37.QPC5.izumi_nag.cam-ttrac_loadbal3 RUN time=248

This error was also encountered during the making of #490 and went away when some additional code was added (not related to the MG routine at all). 

@katec said in email that:
" those three tests are failing. They passed before my last commit, which was adding some if-statements in the ice_nucleation code that in no way would change answers for these compsets."

Proposal is to allow this PR to go in with the ACCUMULATE failures as a known issue.  The pack/unpack issue #254 should resolve this problem and significant progress has been made on the way to opening a PR for this issue.

Re-review will be asked from the relevant reviewers.

2022-01-31 18:43 UTC, andrewgettelman commented
I'm fine with the proposal to move forward with the failing tests. It makes getting rid of the pack/unpack a high priority, but agreed this should not hold up this or other similar work.  Thanks!

2022-01-31 18:48 UTC, nusbaume approved these changes
Sounds like a reasonable plan to me!

2022-01-31 19:19 UTC, gold2718 commented
@Katetc, @cacraigucar, The request for a re-review seems premature as my previous comments have not been addressed. Please fix the ChangeLog (especially as we are being asked to review a variance in test procedure).

Pleas also fix the description block of this PR so that is formatted correctly for our CI tools.

2022-02-01 00:23 UTC, gold2718 approved these changes
Looking much better. ChangeLog still needs a couple of tweaks but that is all I see.

2022-02-01 00:23 UTC, gold2718 commented on doc/ChangeLog
> +Date: 26 Jan 2022
Don't forget to update.

2022-02-01 00:23 UTC, gold2718 commented on doc/ChangeLog
> +izumi/nag/aux_cam:
Please add in the failing `loadbal` tests to document that they are approved failures and what is going on. This document is the first place a lot of folks look to understand why a test is failing.

2022-02-01 19:57 UTC, peverwhee approved these changes

2022-02-01 20:38 UTC, Katetc approved these changes

2022-02-01 20:40 UTC, merged