CAM6 Zhang-McFarlane Option for Parcel Properties to be Based on PBL Depth
ESCOMP/CAM pull request #451
Opened 2021-10-18 14:13 UTC by swrneale

An update to the calculation of the initial parcel properties based on assumed mixing within the boundary layer. It is an alternative option to the maximum moist static energy approach.

closes #383

2021-11-02 01:05 UTC, gold2718 requested changes
A bit of minor cleanup.

2021-11-02 01:05 UTC, gold2718 commented on src/physics/cam/zm_conv.F90
>  #else
Just curious, does anyone still use `pergro`?

2021-11-02 01:05 UTC, gold2718 commented on src/physics/cam/zm_conv.F90
> +!      write(iulog,*) tl(i),hpar(i),rl,qpar(i),grav,parcel_ztop(i),cp
Remove unused code.

2021-11-02 01:05 UTC, gold2718 commented on src/physics/cam/zm_conv.F90
> +            qtp0(i) = q(i,k)    ! Parcel launch total water (assuming subsaturated) - OK????.
Is it time to update this comment?

2021-11-02 01:05 UTC, gold2718 commented on src/physics/cam/zm_conv_intr.F90
> +   call mpi_bcast(zmconv_parcel_pbl,        1, mpi_real8, masterprocid, mpicom, ierr)
Why is this being broadcast as a real, shouldn't it be a logical?
```suggestion
   call mpi_bcast(zmconv_parcel_pbl,        1, mpi_logical, masterprocid, mpicom, ierr)
```

2021-11-02 22:03 UTC, swrneale commented on src/physics/cam/zm_conv.F90
>  #else
I often wonder that. I had presumed it wasn't a useful test anymore given too many of the processes can be discontinuous (mostly microp) and so it's pointless editing them all out.

2021-11-03 21:43 UTC, nusbaume approved these changes
Looks good to me!   Just some random typos and possible comment clarifications.

2021-11-03 21:43 UTC, nusbaume commented on src/physics/cam/zm_conv.F90
> +else ! Default method finding level of MSE maximum (nlev senstitve though)
typo here (`senstitve` -> `sensitive`).

2021-11-03 21:43 UTC, nusbaume commented on src/physics/cam/zm_conv.F90
> +  if (lparcel_pbl) then
I think this if-statement does not need to be indented.

2021-11-03 21:43 UTC, nusbaume commented on src/physics/cam/zm_conv.F90
> +            qtp0(i) = ql(i)     ! Parcel launch q (could be environment (default] or a BL mixed value.
I would change this comment to:

`Parcel launch q (PBL mixed value).`

since if `lparcel_pbl` is true won't it always be the mixed value?  It might also be helpful to note that the parcel may be subsaturated (as I don't see any check that q must be greater or equal to the saturation value).

2021-11-03 21:43 UTC, nusbaume commented on src/physics/cam/zm_conv_intr.F90
> +   logical  :: zmconv_parcel_pbl = .false.             ! switch for parcl pbl calculation
typo here (`parcl` -> `parcel`)

2021-11-10 20:36 UTC, cacraigucar approved these changes
A few minor edits

2021-11-10 20:36 UTC, cacraigucar commented on src/physics/cam/zm_conv.F90
> +! RBN: Use z interface for parcel calculations.
Probably remove this comment as it appears to not pertain to the next line.

2021-11-10 20:36 UTC, cacraigucar commented on src/physics/cam/zm_conv.F90
> +! RBN parcel property variables
We typically no longer have user's initials attached to comments.  Please remove them from here and throughout the code.

2021-11-10 20:36 UTC, cacraigucar commented on src/physics/cam/zm_conv.F90
>  !!! tv=tv : tpv=tpv : qstp=q : buoy=0.
I know this isn't changed code, but the comment implies that qstp is set and it is not.  I suggest removing the entire comment as it doesn't add any knowledge that isn't in the code below.

2021-11-10 21:02 UTC, cacraigucar requested changes
I just realized that we will need a ChangeLog for this commit.  Please copy the ChangeLog_template to the top of the current ChangeLog and make the appropriate edits.

2021-11-15 19:55 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +
Removed

2021-11-15 20:01 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +! RBN: PBL parcel calculation
Removed

2021-11-15 21:42 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +!   write(iulog,*) 'START OF LPARCEL_PBL CODE'
Removed

2021-11-15 21:43 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +!   write(iulog,*) dp_lev
Removed

2021-11-15 21:43 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +! RBN XXX Still Needs to be fully tested XXXXX
Removed

2021-11-15 21:44 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +!            write(iulog,*) 'dp_zfrac',dp_zfrac
Removed

2021-11-15 21:44 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +!            write(iulog,*) k, parcel_hdp(i), parcel_dp(i), dp_zfrac
Removed

2021-11-15 21:45 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +!            write(iulog,*) k, parcel_hdp(i), parcel_dp(i), dp_zfrac
Removed

2021-11-15 21:45 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +!      write(iulog,*) tl(i),hpar(i),rl,qpar(i),grav,parcel_ztop(i),cp
Remove

2021-11-15 21:46 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +            qtp0(i) = q(i,k)    ! Parcel launch total water (assuming subsaturated) - OK????.
Removed. I think this is OK :)

2021-11-15 21:47 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +   logical :: lparcel_pbl     ! Switch to turn on mixing of parcel MSE air, and picking launh level to be the top of the PBL.
Fixed

2021-11-15 21:48 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +  integer            :: ipar ! Index for top of parcel mixing/laucnh level.
Fixed

2021-11-15 21:50 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +! Should be well mixed by other processes no in the very near PBL.
Clarified comment

2021-11-15 21:50 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +else ! Default method finding level of MSE maximum (nlev senstitve though)
Fixed

2021-11-15 21:53 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +            qtp0(i) = ql(i)     ! Parcel launch q (could be environment (default] or a BL mixed value.
Yep, you're right. Changed

2021-11-15 21:57 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +! RBN: Use z interface for parcel calculations.
It pertains to zf being pulled in which is only used for the parcel calculation I believe. I'll leave for now.

2021-11-15 21:57 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +! RBN parcel property variables
Removed. I shall remain anonymous :)

2021-11-15 22:01 UTC, swrneale commented on src/physics/cam/zm_conv_intr.F90
> +   logical  :: zmconv_parcel_pbl = .false.             ! switch for parcl pbl calculation
Fixed

2021-11-15 22:07 UTC, swrneale commented on src/physics/cam/zm_conv.F90
>  !!! tv=tv : tpv=tpv : qstp=q : buoy=0.
It is described above, so will just remove this comment.

2021-11-15 22:10 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +  if (lparcel_pbl) then
I agree. @nusbaume There is an odd suggestion to remove the line
"do i = 1,ncol ! Initialise LCL variables"
In your comment. I don't know why.
I don't think it's a problem in the code so I will ignore :)

2021-11-16 19:57 UTC, gold2718 reviewed
A seemingly missing change and a question.

2021-11-16 19:57 UTC, gold2718 commented on src/physics/cam/zm_conv.F90
> +
They are still there. Missing push?

2021-11-16 19:57 UTC, gold2718 commented on src/physics/cam/zm_conv.F90
>  #else
I'm confused. If the test is not useful, why not edit it out when working on a file?

2021-11-16 23:39 UTC, cacraigucar requested changes

2021-11-16 23:39 UTC, cacraigucar commented on src/physics/cam/zm_conv.F90
>  !!! tv=tv : tpv=tpv : qstp=q : buoy=0.
Were you going to remove this comment line?

2021-11-17 03:50 UTC, swrneale commented on src/physics/cam/zm_conv.F90
> +
Odd, Maybe, I'm just pushing commits to my branch in github itself so I am hoping that's ok.

2021-11-17 03:52 UTC, swrneale commented on src/physics/cam/zm_conv.F90
>  #else
Meant to say it's pointless using it or something like that. Should we remove all the PERGROs left in the code? Are there many left? I feel we should just make one PR to get rid of them all at the same time.

2021-11-17 21:41 UTC, cacraigucar approved these changes

2021-11-17 22:02 UTC, nusbaume commented on src/physics/cam/zm_conv.F90
> +  if (lparcel_pbl) then
@swrneale I think Github just shows the first few lines before any comment, as that line removal is a change that has already been implemented (I didn't suggest it).  Regardless, this all looks good to me now!

2021-11-17 22:09 UTC, nusbaume approved these changes
Everything looks great now, thanks!

2021-11-18 20:58 UTC, peverwhee approved these changes

2021-11-19 20:11 UTC, gold2718 approved these changes

2021-11-23 16:43 UTC, merged