cam6_3_042: mods for interactive fire emissions
ESCOMP/CAM pull request #452
Opened 2021-10-21 18:38 UTC by fvitt

Updates for compset FCfireHIST compset including an updated emissions factors input file for MAM species and corrections to units to history output for aerosol number concentrations.

fixes #405

2021-12-09 22:50 UTC, cacraigucar requested changes

2021-12-10 17:47 UTC, fvitt commented on bld/namelist_files/use_cases/hist_trop_strat_vbsfire_cam6.xml
> +<fire_emis_factors_file>lnd/clm2/firedata/fire_emission_factors_78PFTs_c20210803.nc</fire_emis_factors_file>
done

2021-12-10 20:35 UTC, fvitt commented on bld/namelist_files/use_cases/hist_trop_strat_vbsfire_cam6.xml
> +         'BENZENE -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_BENZENE_anthro_surface_1750-2015_0.9x1.25_c20170608.nc',
Fixed.  I verified all inputs are in the inputdata repo.

2021-12-13 23:07 UTC, cacraigucar approved these changes

2022-01-04 21:59 UTC, gold2718 approved these changes
Just needs a ChangeLog

2022-01-04 23:50 UTC, peverwhee approved these changes

2022-01-05 18:56 UTC, nusbaume approved these changes

2022-01-10 15:34 UTC, merged