Inline medium-energy electron ionization
ESCOMP/CAM pull request #478
Opened 2021-12-03 00:50 UTC by fvitt

Adds the capability to compute medium energy electron chemical forcings from Ap geo-magnetic activity index or observed radiation belt electron fluxes.

closes #425

2022-01-27 20:20 UTC, cacraigucar requested changes

2022-02-07 15:49 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +  function mee_ap_iprs( ncols, nlyrs, airden, scaleh, Ap, status, maglat, lshell) result(ionpairs )
The common exception to this coding practice is an error code or a status indicator, such as in pbuf_get_index or many functions in the PIO lib.  If you insist, I can easily convert this to a subroutine.

2022-02-07 16:40 UTC, gold2718 commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +  function mee_ap_iprs( ncols, nlyrs, airden, scaleh, Ap, status, maglat, lshell) result(ionpairs )
My feeling is that while we are trying to improve CAM coding standards, we also plan on separating chemistry to be a CAM external so I'm fine not insisting here.

2022-02-07 19:54 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +          sec_str = time_units(seci:seci+1)
Corrected.

2022-02-07 19:54 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    flux(:) = en(:)**k*c
Tried to improve readability here and other places in the module.

2022-02-07 19:55 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    real(r8), intent(in) :: Ap
Added descriptors.

2022-02-07 19:55 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    ! Table 1.
done

2022-02-11 22:24 UTC, peverwhee requested changes
A couple memory cleanup suggestions.

2022-02-13 02:05 UTC, gold2718 commented on src/chemistry/mozart/mee_fluxes.F90
> +    endif
Isn't this whole thing the same as:
```suggestion
    valid(:) = .not. mee_fluxes_fillin
```

2022-02-13 02:12 UTC, gold2718 commented on src/chemistry/mozart/mee_fluxes.F90
> +    ierr = pio_get_var( file_id, flux_var_id, start, cnt, indata )
Is this file ever closed? If not, can you add a routine called from chem_final?
Alternatively, you could add logic here to determine if this is the last read for the run and then close it but it is bad form to leave open files (even read only) around.

2022-02-14 15:00 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    lshell = 1.01_r8/(cos(rmaglat)**2)
@dan800 Is this the L-Shell value of a dipole at 1.01 Earth radius?

2022-02-14 15:03 UTC, fvitt commented on src/chemistry/mozart/mee_fluxes.F90
> +    if ( mee_fluxes_active .and. masterproc ) then
Do we really need to write a statement to the log file when the prescribed fluxes are not active?

2022-02-14 16:59 UTC, dan800 commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    lshell = 1.01_r8/(cos(rmaglat)**2)
In a centered dipole magnetic field model, the path along a given L shell can be described as[[5]](https://en.wikipedia.org/wiki/L-shell#cite_note-walt-5)

{\displaystyle r=L\cos ^{2}\lambda }{\displaystyle r=L\cos ^{2}\lambda }
where {\displaystyle r}r is the radial distance (in planetary radii) to a point on the line, {\displaystyle \lambda }\lambda  is its [geomagnetic latitude](https://en.wikipedia.org/wiki/Geomagnetic_latitude), and {\displaystyle L}L is the L-shell of interest.
So this corresponds to an altitude in the lower mesosphere where these energetic particles deposit their energy.

2022-02-14 17:31 UTC, gold2718 commented on src/chemistry/mozart/mee_fluxes.F90
> +    if ( mee_fluxes_active .and. masterproc ) then
I find it helps when someone complains that their simulation isn't working and I can just point them to the log file. However, support for this is likely to fall in your lap so I'm happy to have you log as you see fit.

2022-02-14 19:38 UTC, cacraigucar approved these changes

2022-02-14 21:09 UTC, fvitt commented on bld/build-namelist
> +  add_default($nl, 'mee_ion_blc', 'val'=>'80.D0');
There are many defaults set this way in build-namelist.  By setting it here I don't need to modify another file (namelist_defaults_cam.xml).  If you feel strongly that the default value should be specified in namelist_defaults_cam then I will set it there.

2022-02-14 21:14 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_cam"/>
I thought NAG was a more robust compiler.  I don't have a strong opinion for this particular test.  It should be OK to move it to pgi.
Are there plans to start using gnu for our regression tests? I have been using gnu for my development work and have been liking it.

2022-02-14 21:45 UTC, gold2718 commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_cam"/>
I agree with your points but we can't keep heaping stuff on nag. I would love to drop pgi and use gnu instead. Still waiting for some guidance on that from CSEG et.al. who seem to be betting on the new NVIDIA replacement for pgi (NVHPC?). If it will run on pgi, please move it.

2022-02-14 21:46 UTC, gold2718 commented on bld/build-namelist
> +  add_default($nl, 'mee_ion_blc', 'val'=>'80.D0');
It's pay now or pay later. build-namelist will be going away, hopefully in the next 6 - 9 months. Stuff in namelist_defaults will be kept but stuff in build-namelist will have to be recovered by the developers.

2022-02-14 21:47 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +  function mee_ap_iprs( ncols, nlyrs, airden, scaleh, Ap, status, maglat, lshell) result(ionpairs )
I changed this to a subroutine

2022-02-14 21:48 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +
A added final a routine to this module to clean up memory.

2022-02-14 21:49 UTC, fvitt commented on src/chemistry/mozart/mee_fluxes.F90
> +
Added a final routine to clean up mem and close the input file

2022-02-14 21:50 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_cam"/>
I moved it to PGI.  I will see if it runs.  It should.

2022-02-14 21:51 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    ! The area of the BLC in sr is 2pi(1-cosd(BLC))
I think it was a typo.  Changed it to "cos(BLC)"

2022-02-14 21:52 UTC, fvitt commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    lshell = 1.01_r8/(cos(rmaglat)**2)
Added Dan's comments to the code.

2022-02-14 21:52 UTC, fvitt commented on src/chemistry/mozart/mee_fluxes.F90
> +  real(r8),protected, pointer :: mee_fluxes_energy(:)
made this change

2022-02-14 21:52 UTC, fvitt commented on src/chemistry/mozart/mee_fluxes.F90
> +    endif
Changed, as suggested

2022-02-14 21:53 UTC, fvitt commented on src/chemistry/mozart/mee_fluxes.F90
> +    ierr = pio_get_var( file_id, flux_var_id, start, cnt, indata )
It is now closed in a final routine.

2022-02-14 21:53 UTC, dan800 commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    ! The area of the BLC in sr is 2pi(1-cosd(BLC))
It's a comment but AFAIK
COSD(X) computes the cosine of X in degrees.
And the BLC was written in the comments as 66.7 degrees.

2022-02-14 22:03 UTC, gold2718 commented on src/chemistry/mozart/mee_ap_util_mod.F90
> +    ! The area of the BLC in sr is 2pi(1-cosd(BLC))
> COSD(X) computes the cosine of X in degrees

Maybe in Fortran 77, it does not exist in modern Fortran.

2022-02-14 22:43 UTC, fvitt commented on bld/build-namelist
> +  add_default($nl, 'mee_ion_blc', 'val'=>'80.D0');
The default is now set in namelist_defaults_cam.xml.

2022-02-23 20:45 UTC, gold2718 approved these changes
Looks good to me now, thanks!

2022-02-23 20:57 UTC, peverwhee approved these changes
Looks good to me! Thanks!

2022-02-24 18:19 UTC, nusbaume approved these changes
Looks good to me!  Just some minor requests.

2022-02-24 18:19 UTC, nusbaume commented on src/chemistry/mozart/mee_ionization.F90
> +    if (mee_ion_inline) then
Should this if-statement include a `mee_ion_diagonly` check as well?  My understanding is that the fluxes from a file can only be used if `diagonly` is true, so it seems like there would be no reason to even try and read the namelist if that wasn't the case?

2022-02-24 21:43 UTC, fvitt commented on src/chemistry/mozart/mee_ionization.F90
> +    if (mee_ion_inline) then
The line is correct as it is.  Prescribed electron fluxes can be used regardless of how diagonly is set.

2022-02-24 21:50 UTC, nusbaume commented on src/chemistry/mozart/mee_ionization.F90
> +    if (mee_ion_inline) then
Whoops, my mistake, I confused `epp_mee_filepath` with  `mee_fluxes_filepath`.  You're totally correct.

2022-02-24 22:04 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq9s_mee_fluxes/shell_commands
> +./xmlchange GLC_NCPL=\$ATM_NCPL
Should someone clean out all of the GLC_NCPL settings in the test shell_commands files now that all F compsets should be using stub glacier component?

2022-02-24 22:05 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/outfrq9s_apmee/shell_commands
> +./xmlchange ROF_NCPL=\$ATM_NCPL
Now sure. I can remove it for now.

2022-02-25 20:17 UTC, merged