cam6_3_040: MPAS pressure fix
ESCOMP/CAM pull request #481
Opened 2021-12-09 19:12 UTC by jtruesdal

MPAS uses hydrostatic interface pressures and non-hydrostatic mid level pressures when passing state to CAM physics (this ensures that geopotential_t will exactly recover MPAS z levels from CAM physics state); unfortunately, the hydrostatic interface pressures did not bound the non-hydrostatic mid level pressure at high resolution leading to a physically inconsistent pressure field. Mid-level pressure computation changed to the arithmetic mean of hydrostatic interface pressures. This makes sure that the mid level pressure is bounded (but violates the geopotentian_t consistency for mid level height). 
This PR also addresses an error in the calculation of some MPAS energy diagnostics due to swapped array dimensions in the rhod and dz arrays.
closes #442
closes #487

2021-12-13 23:38 UTC, cacraigucar requested changes

2021-12-13 23:38 UTC, cacraigucar commented on src/dynamics/mpas/dp_coupling.F90
> +        !hydrostatic dry mid-level dry pressure - MPAS non-hydrostatic dry pressure is pmiddry(k,iCell) = (rhodryk*rgas*theta*kap1)**kap2
I believe this comment might be longer than 132 characters.  If so, please break it into two lines

2021-12-14 15:56 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +        !hydrostatic dry mid-level dry pressure - MPAS non-hydrostatic dry pressure is pmiddry(k,iCell) = (rhodryk*rgas*theta*kap1)**kap2
Good eye 137.  Split.

2021-12-14 22:42 UTC, cacraigucar approved these changes

2021-12-14 23:15 UTC, fvitt approved these changes

2021-12-14 23:15 UTC, fvitt commented on doc/ChangeLog
> +Date: 10 Dec 2021
Should this date be the date the new cam tag is created?

2021-12-14 23:18 UTC, jtruesdal commented on doc/ChangeLog
> +Date: 10 Dec 2021
I believe so.  Now just a placeholder till I get a tag. Thanks for noting it though I will make sure its corrected.

2021-12-21 16:58 UTC, peverwhee approved these changes

2021-12-21 17:36 UTC, gold2718 approved these changes
Code looks okay, however, there is missing issue for the bug fix. Please find the issue or create one and add it to this PR's description section.

2021-12-21 17:36 UTC, gold2718 commented on src/dynamics/mpas/dp_coupling.F90
> +        rho_dz        = (1.0_r8+q(index_qv,k,iCell))*rhod(k,iCell)*dz(k,iCell)
I see this bug fix explained in the ChangeLog, however, there should be an open issue that this should address (unless there is no effect from these changes). Can you add that to this PR?

2021-12-21 18:02 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +        rho_dz        = (1.0_r8+q(index_qv,k,iCell))*rhod(k,iCell)*dz(k,iCell)
I added issue #487 that describes the bug in these energy diagnostics and referenced it as being closed in this PR description.  These variables are not output by default and don't affect the model run.  The error was caught while I was putting this PR together.

2021-12-21 18:22 UTC, nusbaume approved these changes

2021-12-23 05:32 UTC, merged