[WIP] Integrating GEOS-Chem chemistry in CESM2.3
ESCOMP/CAM pull request #484
Opened 2021-12-15 16:35 UTC by lizziel

This draft PR (work-in-progress) contains CESM-GC changes to merge into the main CAM development branch. It will serve as a starting point for discussion of modifications needed for inclusion of GEOS-Chem in CESM 2.3. 

The goal of implementing GEOS-Chem chemistry inside CESM is to provide an additional chemistry option alongside CAM-Chem. Thibaud Fritz (@fritzt) has done the bulk of the work for implementing the GEOS-Chem 13 chemistry module into CESM2.1.1, and the new option is designated CESM2-GC. That work was built on the tag for CESM2.1 release 29 of the now stale branch for CESM 2.1, and was previously submitted in the now closed PR https://github.com/ESCOMP/CAM/pull/378. This new PR features CESM2-GC CAM changes after a rebase onto CAM 6.0.034. The cam_development branch as of early December has been merged in with all conflicts resolved.

CESM2-GC relies heavily on the implementation of HEMCO in CESM2 (https://github.com/ESCOMP/HEMCO_CESM) developed by @jimmielin, and we do not expect the GEOS-Chem option to run until HEMCO is integrated into CESM as well. HEMCO is an ESMF-compatible interface to perform I/O (e.g. loading emission inventories) in atmospheric models. Note that HEMCO has been implemented in CAM for CESM2-GC development and lives at a higher level than GEOS-Chem. This allows HEMCO to feed data (e.g. emission fluxes) to either GEOS-Chem or CAM-Chem. Compiling CESM2-GC with HEMCO requires the use of ESMF libraries (USE_ESMF_LIB).

The CESM2-GC implementation originally came with a few modifications in CIME and CLM and changes were submitted previously with these updates (see https://github.com/ESCOMP/CTSM/pull/1475, https://github.com/ESCOMP/CTSM/pull/1377, and https://github.com/ESMCI/cime/pull/3974). Due to a combination of incompatibility with the new CESM version and change of design those PRs were not merged and are now closed. Here I will go over a brief history and current status of those updates.

First, we wanted to have the option to let GEOS-Chem compute its own dry deposition velocities. This required the coupler to pass land types from CLM to CAM and CLM, CIME, and CAM were modified accordingly. After discussion with NCAR we decided to use dry deposition velocities calculated in CLM for gas phase species instead, and import via HEMCO for aerosol species. GEOS-Chem will not compute its own dry deposition velocity. CAM changes for that are not yet incorporated in this PR and doing so is on the to do list.

Second, we needed coefficients such as Henry's Law for added GEOS-Chem species.  Due to changes in how CESM handles these coefficients the previous work for including them is no longer applicable. With guidance from @fvitt I instead created a NetCDF file containing molecular weights, Henry's Law coefficients, and reactivities for all GEOS-Chem dry-deposited gases that should be readable via the work Francis is doing. The file is located on Cheyenne at `/glade/u/home/elundgren/cesm_2.3/henrys_coeffs/geoschem_drydep_tables.nc`.

Third, not all files in the GEOS-Chem subdirectories should be compiled. To deal with this we introduced a feature that can exclude files from the compilation process (ESMCI/CIME#3366). This feature needs to be revisited for applicability and compatibility with CESM 2.3.

I am now working on seeing if CESM will compile using the CAM branch that I would like to merge. I anticipate several changes will need to be made before the merge, either for compilation or design reasons. Any and all feedback is welcome!

~Lizzie (GEOS-Chem Support Team)

2022-02-10 19:56 UTC, lizziel commented
I am currently testing this PR branch within CESM master branch commit a2434e82 ("Merge pull request #201" on 1/27/22). It successfully builds and runs with case `FCnudged` with minor edits (now pushed).

I am now testing the five GEOS-Chem test cases: `FCSD_GC`, `FCHIST_GC`, `FC2000climo_GC`, `FC2010climo_GC`, and `FSPCAMM_GC`.  Since HEMCO is turned off by default in this PR I must make a manual change [here](https://github.com/CESM-GC/CAM/blob/71fb83adfdb9be465f84a3b9661281a2f2e015c7/bld/config_files/definition.xml#L55) to turn on HEMCO to build these cases.

Current status is the GEOS-Chem builds are failing because all GEOS-Chem files are being compiled. This is expected since previously @fritzt implemented in CIME the ability to skip GEOS-Chem files that are not used in CESM-GC, and I have not brought that work in yet. That update is discussed in issue https://github.com/ESMCI/cime/issues/3366, and  submitted as part of PR https://github.com/ESMCI/cime/pull/3974. I am now working on bringing that functionality to the recent version.

Pinging @gold2718 and @lkemmons on this update.

2022-02-11 19:50 UTC, lizziel commented
I opened draft PR https://github.com/ESMCI/cime/pull/4180 to submit CIME updates to use an `.exclude` file to exclude certain files from compiling. This update will be necessary for building GEOS-Chem within CESM.

2022-02-24 21:27 UTC, lizziel commented
Four of the five GEOS-Chem compsets in this PR now build successfully with HEMCO enabled and dry deposition code disabled.

- FCSD_GC
- FCHIST_GC
- FC2000climo_GC
- FC2010climo_GC

The fifth one, `FSPCAMM_GC`, relies on option `geoschem_mam3` which is not fully implemented. We may not support this compset.

The next step for me is to tackle dry deposition. I will turn off dry deposition for aerosols and try to use dry deposition velocities for gas phase species from the land module.

2022-04-29 18:29 UTC, lizziel commented
**April 29 UPDATE:** GEOS-Chem in the cam_development branch now runs successfully to completion with dry deposition off and a kludge for setting Henry's law coefficients for some of the wet deposited species. My next steps are (1) getting the Henry's Law coeffs into the model for species in GEOS-Chem but not yet in CESM, and (2) turn on using land module dry deposition velocities in GEOS-Chem dry deposition for gases (will turn off aerosol dry deposition for now).

2022-04-29 18:33 UTC, lizziel commented
This branch currently contains GEOS-Chem 13.3.4. Note that this is ahead of the version used in https://github.com/CESM-GC/CAM which is 13.1. I added one additional advected gas species to GEOS-Chem (HMS) in the upgrade.

2022-11-17 18:01 UTC, lizziel commented
This PR is now ready for review. I updated the initial post at the top of this thread to give a basic overview of the update and the history that went into it. Please let me know what the next steps are.

@fvitt, @gold2718

2022-11-21 22:47 UTC, jimmielin commented
Hi @peverwhee, yes, #560 is the corresponding HEMCO PR. The PR is currently under review and I'm working on some final updates for optimizing memory usage, but the code in the PR is near ready.

Thanks!
Haipeng

2022-12-02 21:40 UTC, fvitt reviewed
Please explain the rational for copying many of the source modules from the `chemistry/mozart` directory to `chemistry/geoschem`.  As far as I can see, geoschem does not use these modules.

2022-12-05 15:41 UTC, lizziel commented
Hi @fvitt. Originally the `chemistry/mozart` files were copied to `chemistry/geoschem` to use as templates for the GEOS-Chem implementation in CAM. Over time these were slimmed down to only what is needed to build and run when `chemistry/mozart` is excluded from the build. The current files that retain the Mozart filenames can be broken down into a few categories of why they are still present.

1. Several files contain content that is used in physics or `runtime_opts` and so must be built. As part of the original implementation @fritzt commented out the body of most of the subroutines so that nothing is actually done with them apart from making them available in the modules. I am looking into these dependencies and whether we can do something about them. These files include:

- mo_apex.F90
- mo_gas_phase_chmdr.F90
- charge_neutrality.F90
- epp_ionization.F90
- clybry_fam.F90
- rate_diags.F90
- upper_bc.F90

2. Several files contain content that is used in the GEOS-Chem implementation. Ideally the content used by both Mozart and GEOS-Chem would be abstracted to a shared folder within `src/chemistry` so that both GEOS-Chem and Mozart could use them. This would avoid having duplicates in `chemistry/geoschem` and `chemistry/mozart`. For files that are best kept within GEOS-Chem rather than put in shared we should rename them so that they do not include the `mo_` prefix. The current Mozart files that have content used in GEOS-Chem, along with a note on why, are listed below:

- file_emissions.F90: subroutine fire_emissions_srf
- mo_chem_utls.F90: chemistry utilities
- mo_drydep.F90: subroutine drydep_inti
- mo_mean_mass.F90: subroutines init_mean_mass and set_mean_mass
- mo_neu_wetdep.F90: GEOS-Chem uses the Neu wetdep scheme
- mo_setinv.F90: used to set invariant densities
- mo_tracname.F90: declares solsym array
- gas_wetdep_opts.F90: reads gas-phase wet deposition namelist
- short_lived_species.F90: manages storage of non-transported short-lived chemical species in the physics buffer
- tracer_cnst.F90: general utility file
- tracer_srcs.F90: general utility file

3. Two GEOS-Chem files share the same name as Mozart files because the build system uses those names:

- mo_sim_dat.F90
- chemistry.F90

4. There are two files that I think might be able to be removed, and I am testing this.

- chem_prod_loss_diags.F90
- mo_ghg_chem.F90

@fritzt and @sdeastham, please chime in if you have anything to add to this.

2022-12-14 23:12 UTC, fvitt commented
@lizziel 
Having duplicates of the mozart files will be difficult to maintain.  Would it be possible to have in the `chemistry/geochem` only `chemistry.F90` and `mo_sim_dat.F90`? Then compile the code in both `chemistry/geochem` followed by `chemstry/mozart`.  The version in of `chemistry.F90` and `mo_sim_dat.F90` in `chemistry/geochem` will supersede the versions in `chemstry/mozart`.

2022-12-14 23:32 UTC, fvitt commented
@lizziel Would you be able add regression tests (under `cime_config/testdefs/`) for the geoschem configurations you would like to maintain?

2022-12-14 23:36 UTC, fvitt commented on Externals.cfg
> +repo_url = https://github.com/fvitt/CESM_CPL7andDataComps
I think you can just use the ESCOMP versions of CMEPS and CPL7 rather than the fvitt forks.  I don't think you need these changes `Externals.cfg`.

2022-12-15 00:13 UTC, fvitt commented
I tried to build the `FC2000climo_GC` compset.  I get the following errors:

```
/data/terminator-data1/home/fvitt/camdev/CESM-GC_rebased_on_cam6_0_034/src/chemistry/geoschem/geoschem_src/GeosUtil/error_mod.F90:250:21:

  250 |     FPC            = FP_CLASS( VALUE )
      |                     1
Error: Function ‘fp_class’ at (1) has no IMPLICIT type
/data/terminator-data1/home/fvitt/camdev/CESM-GC_rebased_on_cam6_0_034/src/chemistry/geoschem/geoschem_src/GeosUtil/error_mod.F90:197:21:

  197 |     FPC            = FP_CLASS( VALUE )
      |                     1
Error: Function ‘fp_class’ at (1) has no IMPLICIT type
```

2022-12-15 17:16 UTC, lizziel commented on Externals.cfg
> +repo_url = https://github.com/fvitt/CESM_CPL7andDataComps
Done. I had been using your branches for the Henry's Law coeffs netcdf file capability.

2022-12-15 17:24 UTC, lizziel commented
Thanks @fvitt for your responses.

> Having duplicates of the mozart files will be difficult to maintain. Would it be possible to have in the chemistry/geochem only chemistry.F90 and mo_sim_dat.F90? Then compile the code in both chemistry/geochem followed by chemstry/mozart. The version in of chemistry.F90 and mo_sim_dat.F90 in chemistry/geochem will supersede the versions in chemstry/mozart.

It may be confusing to build `chemistry.F90` and `mo_sim_dat.F90` in both directories even if it works. Would you be open to using a `shared` directory and having the CAM-Chem specific files in `Mozart`? I could do that work.

Regarding building all of `chemistry/mozart`, I am concerned that @fritzt commented out the bodies of the subroutines in the copied files. I assume this was just so that it would build, but I want to verify that having the bodies in them will not inadvertently mess things up for GEOS-Chem. One solution is to have a global variable indicating what chemistry scheme is being used. This may already exist but I am unaware. Do you know of one? Then we could bracket code by chemistry scheme. Not ideal, but it may come in handy.

> Would you be able add regression tests (under cime_config/testdefs/) for the geoschem configurations you would like to maintain?

Yes, at least I think so. I'll let you know if I have questions as I do it.

2022-12-15 17:34 UTC, gold2718 commented
> It may be confusing to build `chemistry.F90` and `mo_sim_dat.F90` in both directories and also have GEOS-Chem use files in the Mozart directory.

That would not happen. The way the CAM build system works, it finds and builds only the first instance of a module in the Filepath (currently constructed by the configure script). In this case, the GEOS-Chem path shows up before the Mozart path so it will "shadow" the modules in that directory.

2022-12-15 18:12 UTC, lizziel commented
@fvitt, I merged in the latest cam_development today and am testing all compsets again. I have not run into the build error you have for FC2000climo_GC, but am getting a different one.

> /glade/u/home/elundgren/cesm_gc_2.3_alpha10a/components/cam/src/chemistry/geoschem/epp_ionization.F90(253): error #6580: Name in only-list does not exist or is not accessible.   [RAIRV]

Interestingly, this issue is a case of exactly what we are talking about with regards to copies of Mozart files in GEOS-Chem. I compared `epp_ionization.F90` in GEOS-Chem versus Mozart and see we have divergence in subroutine use statements after merging in the latest CAM updates.

This file is an example where main bodies of the subroutines are commented out for GEOS-Chem. I assumed we had files like this because we do not build Mozart in GEOS-Chem, however I see in the build log that Mozart did build.

> mosart built in 31.400082 seconds

@fritzt, could you comment on why you copied files from Mozart to GEOS-Chem and then commented out the bodies?

2022-12-15 18:18 UTC, lizziel commented
Hi @gold2718, thanks for clarifying. According to my build log Mozart built before GEOS-Chem. However, the build then fails on a module in GEOS-Chem that is also in Mozart. Is this expected?

2022-12-15 18:23 UTC, lizziel commented
Nevermind. I checked the full build log and none of the Mozart files appear in the file. So it seems I was correct that `geoschem/mosart` is not actually built despite the message in the main log that is was. Apologies for the confusion. I'll check the files in `bld` to see where it is actually skipped.

2022-12-15 18:30 UTC, lkemmons commented
Lizzie - note that 'mosart' is the river scheme -- something very different
from 'mozart'.


On Thu, Dec 15, 2022 at 11:23 AM Lizzie Lundgren ***@***.***>
wrote:

> Nevermind. I checked the full build log and none of the Mozart files
> appear in the file. So it seems I was correct that geoschem/mosart is not
> actually built despite the message in the main log that is was. Apologies
> for the confusion. I'll check the files in bld to see where it is
> actually skipped.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/484#issuecomment-1353525414>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH5BH7NO7ACRU6TSB6FAJHLWNNO3JANCNFSM5KECZK5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-15 18:30 UTC, lizziel commented
Ah, thanks you @lkemmons!

2023-01-10 22:10 UTC, lizziel commented
@fvitt, I have pushed updates that remove all of the adapted or copied Mozart files from `src/chemistry/geoschem` except the following which are required either per mechanism or per chemistry (Mozart vs GEOS-Chem):

- chem_mods.F90
- chemistry.F90
- mo_sim_dat.F90
- m_spc_id.F90

In order to do this I had to make a few modifications to code in the `src/chemistry/mozart` and `src/chemistry/pp_*` folders. Please review and let me know if those changes are acceptable.

I did not move anything into a shared folder for use by both Mozart and GEOS-Chem so there are dependencies in GEOS-Chem's chemistry.F90 on Mozart. I wonder if you are open to having a `chem_shared` folder (or some other name) to store some of the common code used for chemistry, if not now then in the future. This would make it easier to spot changes to subroutines currently in Mozart that might affect GEOS-Chem.

I am currently putting GEOS-Chem compset tests into `cime_config/testdefs` and have a few questions.

1. What are the `name` keywords, e.g. `ERP_Ln9_Vnuopc`, and how do I pick which to use for GEOS-Chem tests?
2. I think I can use files in one of the pre-existing testmods folders for the `testmods` keyword, e.g. `cam/outfrq9s`, but I am not sure which to pick. Do you have a standard one that would be appropriate?
3. There are several options for machine `category`, e.g. `aux_cam` and `prealpha`. Which should I choose for GEOS-Chem?
4. Is one test sufficient per compset?
5. How do I run the tests?

Other things left on the to do list are (1) bringing in the latest `cam_development` updates and resolving conflicts (I noticed there are now a few that crept in), and (2) updating the default diagnostics lists per GEOS-Chem compset.

Let me know your thoughts. Thanks!

2023-02-23 16:46 UTC, lizziel commented
@fvitt, I noticed a lot of conflicts have snuck in with recent cam development. I will update this PR to resolve those. I also still need to add GEOS-Chem compsets to the test suite and am looking for guidance on that (see my above questions). Could you give me an update on your timeline?

2023-02-24 16:31 UTC, fvitt requested changes
Sorry, I thought I had requested these changes some time ago.  I am not sure what happened.

2023-02-24 16:31 UTC, fvitt commented on src/chemistry/pp_terminator/chem_mods.F90
> +      real(r8), allocatable :: slvd_ref_mmr(max(1,nslvd))
Can the `slvd_ref_mmr` be removed from the chemistry preprocessor generated `chem_mods.F90` files?  This would require changes to chemistry preprocessor and I would like to avoid this.  For an alternative, see my comments on `short_lived_species.F90`.

2023-02-24 16:31 UTC, fvitt commented on src/chemistry/mozart/short_lived_species.F90
> +    use chem_mods,        only : slvd_ref_mmr
Rather than use `slvd_ref_mmr` from `chem_mods`, can this array simply be a member of the `short_lived_species` module that can be set by GEOSchem before `initialize_short_lived_species` called?  Another alternative is to add an optional argument to `initialize_short_lived_species` pass in the initial MMRs.

BTW, I am not seeing where the `slvd_ref_mmr` is being set.

2023-02-24 16:48 UTC, fvitt commented
> @fvitt, I noticed a lot of conflicts have snuck in with recent cam development. I will update this PR to resolve those. I also still need to add GEOS-Chem compsets to the test suite and am looking for guidance on that (see my above questions). Could you give me an update on your timeline?

For adding tests to the test suite, take a look at `cime_config/testdefs/testlist_cam.xml`.  See the test entries for the CAMChem `FC2000climo` compset.    Tests for the GC compsets will need to be added to `testlist_cam.xml`, similar to `FC2000climo`.

I don't really have a timeline.  HEMCO needs to be merged into `cam_development` before GEOSchem since it seems to be dependent on HEMCO.  (There is a separate PR for HEMCO)

2023-03-07 15:43 UTC, lizziel commented on src/chemistry/pp_terminator/chem_mods.F90
> +      real(r8), allocatable :: slvd_ref_mmr(max(1,nslvd))
I removed it from chem_mods.F90 and it is now a module variable in short_lived_species.F90.

2023-03-07 15:45 UTC, lizziel commented on src/chemistry/mozart/short_lived_species.F90
> +    use chem_mods,        only : slvd_ref_mmr
Thanks for the recommendation since I think this way is much cleaner than having it in chem_mods. The short_lived_species module variable is now set by passing an optional argument to register_short_lived_species. It is then used in initialize_short_lived_species only if the array is allocated. I added deallocation to chem_final in chemistry.F90 for both GEOS-Chem and Mozart.

2023-03-07 18:39 UTC, fvitt reviewed
I took a quick look. I have a couple more questions.

2023-03-07 18:39 UTC, fvitt commented on src/cpl/mct/cam_cpl_indices.F90
> +       index_x2a_Sl_ddvel    = 0
This whitespace change is not needed

2023-03-07 18:39 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +    logical :: debug                   ! enable status prints
Do you still need debug statements in `physpkg.F90`

2023-03-07 18:39 UTC, fvitt commented on src/chemistry/aerosol/aer_drydep_mod.F90
> +module aer_drydep_mod
Curious why the name of this module needed to change.  Was there a naming conflict somewhere?

2023-03-07 18:39 UTC, fvitt commented on src/chemistry/pp_waccm_ma/chem_mods.F90
> +      real(r8), allocatable :: slvd_ref_mmr(max(1,nslvd))
This needs to be reverted.

2023-03-07 18:39 UTC, fvitt commented on src/cpl/nuopc/atm_import_export.F90
> +    call fldlist_add(fldsToAtm_num, fldsToAtm, 'So_ustar'  )
Does this additional field require an update to CMEPS external?

2023-03-07 19:11 UTC, lizziel commented on src/chemistry/aerosol/aer_drydep_mod.F90
> +module aer_drydep_mod
Yes, GEOS-Chem contains module drydep_mod.

2023-03-07 19:11 UTC, lizziel commented on src/physics/cam/physpkg.F90
> +    logical :: debug                   ! enable status prints
Not needed anymore. now removed.

2023-03-07 19:11 UTC, lizziel commented on src/cpl/mct/cam_cpl_indices.F90
> +       index_x2a_Sl_ddvel    = 0
Removed.

2023-03-07 19:17 UTC, lizziel commented on src/cpl/nuopc/atm_import_export.F90
> +    call fldlist_add(fldsToAtm_num, fldsToAtm, 'So_ustar'  )
No, So_ustar is already in the mediator.

2023-04-19 17:59 UTC, lizziel commented
Hi @fvitt, I added 5 GEOS-Chem tests to the test suite and all tests passed. However, I just merged in the latest cam_development and the tests no longer pass. Have you see this error before when creating a test? I am using cime 6.0.94.

```
Finished CREATE_NEWCASE for test SMS_Ld1_Vnuopc.f09_f09_mg17.FCHIST_GC.cheyenne_intel.cam-outfrq1d in 0.670619 seconds (FAIL). [COMPLETED 5 of 5]
    Case dir: /glade/scratch/elundgren/SMS_Ld1_Vnuopc.f09_f09_mg17.FCHIST_GC.cheyenne_intel.cam-outfrq1d.20230419_115751_j5qozk
    Errors were:
        Traceback (most recent call last):
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/scripts/create_newcase.py", line 459, in <module>
            _main_func(__doc__)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/scripts/create_newcase.py", line 449, in _main_func
            ngpus_per_node=ngpus_per_node,
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/case/case.py", line 2398, in create
            ngpus_per_node=ngpus_per_node,
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/case/case.py", line 1303, in configure
            self._get_component_config_data(files)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/case/case.py", line 1087, in _get_component_config_data
            compobj = Component(comp_config_file, comp_class)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/XML/component.py", line 25, in __init__
            EntryID.__init__(self, infile)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/XML/entry_id.py", line 15, in __init__
            GenericXML.__init__(self, infile, schema, read_only=read_only)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/XML/generic_xml.py", line 78, in __init__
            self.read(infile, schema)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/XML/generic_xml.py", line 128, in read
            self.read_fd(fd)
          File "/glade/u/home/elundgren/cesm_master_Apr19/cime/CIME/XML/generic_xml.py", line 156, in read_fd
            self.tree = ET.parse(fd)
          File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
            tree.parse(source, parser)
          File "/glade/u/apps/ch/opt/python/3.6.8/gnu/8.3.0/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
            self._root = parser._parse_whole(source)
        xml.etree.ElementTree.ParseError: mismatched tag: line 390, column 14
```

2023-04-19 18:20 UTC, gold2718 commented
> Have you see this error before when creating a test?

It looks like a merge error in the cime_config/config_component.xml file.
I'm not sure what happened but look at line 390.

2023-04-19 18:50 UTC, lizziel commented
Ah! Thank you. There was a typo introduced on a random line during the interactive conflict resolution on GitHub.

2023-05-01 14:56 UTC, lizziel commented
I am still working on getting CAM tests (category geoschem) to pass since my latest `cam_development` merge. It is failing without traceback or error messages in any of the logs. It seemingly is unrelated to GEOS-Chem since CAM initialize succeeds and it never reaches `Model_Advance`. The commit I merged is this:

> [Merge pull request](https://github.com/CESM-GC/CAM/commit/fc3cc80d285d8517ba54854db04f312271d653cb) https://github.com/ESCOMP/CAM/pull/788 [from brian-eaton/lapack_invert](https://github.com/CESM-GC/CAM/commit/fc3cc80d285d8517ba54854db04f312271d653cb) 
> 
> cam6_3_107: Reimplement zonal_mean_mod::Invert_Matrix using LAPACK DGESV
> @[brian-eaton](https://github.com/CESM-GC/CAM/commits?author=brian-eaton)
> brian-eaton committed 2 weeks ago

Are they any known issues with this version that would cause the run to crash without error?

2023-05-01 15:17 UTC, gold2718 commented
> It is failing without traceback or error messages in any of the logs. It seemingly is unrelated to GEOS-Chem since CAM initialize succeeds and it never reaches `Model_Advance`.

Any chance you are just running out of memory? I'm not sure if 107 upped the memory the model is using but that is pretty common (has anyone looked at the test logs to see if the new version uses much more memory?). You are running a bunch of one-degree tests.  I think you can easily try just using more tasks (can you xmlchange of NTASKS in shell_commands?). I would report this if that helps. Also, there might be a memory highwater log message at the end of CAM init in which case you could compare your premerged and merged cases to see if there is a big difference.

2023-05-02 14:50 UTC, lizziel commented
Thanks for the suggestion @gold2718. I created a case using 1.9x1.9 and upped the tasks by a factor of 4. It still fails without traceback or error. My plan now is to go back to the pre-merge commit which used cam_3_095 and verify it still works. Then I'll merge in the latest cam_development, test, and if it still fails go back and merge in more incrementally to find out where the problem came in.

2023-05-02 16:32 UTC, gold2718 commented
I know there is a lag in writing but what is the last bit of the relevant log files (e.g., atm, cesm)?

2023-05-02 16:57 UTC, fvitt commented
Can you point us to one of your failing cases?  I assume you are testing with DEBUG=TRUE.   In some cases I have found that setting NTHRDS=1 helps with generating a traceback.

2023-05-19 14:56 UTC, lizziel commented
The issue is now fixed. I did a new merge with the latest CAM (cam3_6_111) and created a fresh CESM clone.

2023-07-18 20:34 UTC, lizziel commented
I will merge in the latest cam_development this week and resolve conflicts. Now that HEMCO has been merged do you have an idea of when the official review of this PR will start?

2023-08-29 18:36 UTC, lizziel commented
@fvitt, @lkemmons Do you have update on when this PR will start the official review?

2023-08-29 19:25 UTC, fvitt commented
> @fvitt, @lkemmons Do you have update on when this PR will start the official review?

I hope to start my review later this week.

2023-08-29 20:52 UTC, lizziel commented
@fvitt, that's great news! I submitted a test suite today (GEOS-Chem tests only) but it is pending.

2023-09-01 20:41 UTC, fvitt commented on src/chemistry/geoschem/chemistry.F90
> +#endif
use spmd_utils

2023-09-01 20:42 UTC, fvitt commented on src/chemistry/geoschem/chemistry.F90
> +       CALL MPIBCAST( linozData, nLinoz, MPIR8, 0, MPICOM )
Remove the `SPMD` cpp defs and use `mpi_bcast`

2023-09-01 20:45 UTC, fvitt commented on src/chemistry/geoschem/geoschem_diagnostics_mod.F90
> +  USE ErrCode_Mod                               ! Error codes for success or failure
Should use `only` keyword so that we can see what is actually used from these modules.

2023-09-01 21:20 UTC, lizziel commented on src/chemistry/geoschem/geoschem_diagnostics_mod.F90
> +  USE ErrCode_Mod                               ! Error codes for success or failure
Is this a requirement for all USE cases throughout all of GEOS-Chem?

2023-09-01 21:23 UTC, lizziel commented
Thanks @fvitt. I will address these next week. Today I switched from cheyenne to derecho and you probably saw that I brought in the latest cam_development updates. I am getting this error in my FCSD_GC case and I wonder if you know what this is given other changes in CAM over the last month or so.
```
 (GETFIL): using 
 /glade/p/cesmdata/inputdata/atm/cam/topo/fv_1.9x2.5_nc3000_Nsw084_Nrs016_Co120_
 Fi001_ZR_GRNL_c190405.nc
 hycoef_read: ERROR: file lev does not match model. lev (file, model):
          32          56
 ERROR: hycoef_read: ERROR: file lev does not match model.
```

2023-09-01 23:21 UTC, fvitt commented
> Thanks @fvitt. I will address these next week. Today I switched from cheyenne to derecho and you probably saw that I brought in the latest cam_development updates. I am getting this error in my FCSD_GC case and I wonder if you know what this is given other changes in CAM over the last month or so.
> 
> ```
>  (GETFIL): using 
>  /glade/p/cesmdata/inputdata/atm/cam/topo/fv_1.9x2.5_nc3000_Nsw084_Nrs016_Co120_
>  Fi001_ZR_GRNL_c190405.nc
>  hycoef_read: ERROR: file lev does not match model. lev (file, model):
>           32          56
>  ERROR: hycoef_read: ERROR: file lev does not match model.
> ```

The number of levels in the IC dose not match the number of levels the model is configured for.

2023-09-05 17:53 UTC, lizziel commented on bld/build-namelist
> +    #           'exo_coldens_file', 'sulf_file' );
Will delete.

2023-09-05 17:53 UTC, lizziel commented on bld/configure
> +     -hemco             Switch enables the use of the Harmonized Emissions Component.
Will delete.

2023-09-05 17:57 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
These changes add a new option for creating deposition lists. CESM deposition lists (`wetdep_list`, `drydep_list`, `aer_wetdep_list`, and `aer_drydep_list`) are constructed by retrieving species from master list files in `bld/namelist_files/` and then removing species that are not advected. This is done within `set_dep_lists` with routines `get_(aer/gas)_(wet/dry)dep_lists`. For GEOS-Chem we do not want to rely on the master list files. Instead, the namelist variables are initialized in the compset files (`bld/namelist_files/use_cases/*_geoschem.xml`) and then updated using new subroutine `filter_dep_list` to remove non-advected species. The routine is essentially the same as `get_(aer/gas)_(wet/dry)dep_lists` except that it uses the pre-defined list rather than initialize them with entries in the text files.

2023-09-05 17:57 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +{
filter_dep_list is used in bld/perl5lib/Build/ChemNamelist.pm when setting the deposition lists. It is only used if the \
deposition list namelist variables are not yet set prior to calling set_dep_lists. This	currently only occurs if using G\
EOS-Chem chemistry.

2023-09-05 17:57 UTC, lizziel commented on cime_config/config_compsets.xml
> +        <value compset="GC">1</value>
I am not sure. Is there a reason it is set to 1 for `SPCAM[SM]` in both `cime_config/config_compsets.xml` and `config_pes.xml`. I think it is set in both places for GEOS-Chem because it used SPCAM as an example of how to do it.

2023-09-05 17:59 UTC, lizziel commented on src/chemistry/geoschem/chem_mods.F90
> +      CHARACTER(LEN=255)   :: slsLongnames(nSlsMax)
I will replace the LEN=255 character declarations to use `SHR_KIND_CL` for all files in `src/chemistry/geoschem/`. I will exclude geoschem_history_mod since that module may move to the CESM interface folder in the GEOS-Chem repository.

2023-09-05 18:00 UTC, lizziel commented on src/chemistry/geoschem/geoschem_diagnostics_mod.F90
> +  USE ErrCode_Mod                               ! Error codes for success or failure
I'll fill in the missing only keywords for all files in src/chemistry/geoschem/.

2023-09-05 18:02 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +       CALL MPIBCAST( linozData, nLinoz, MPIR8, 0, MPICOM )
I'm not sure why the SPMD cpp defs are there. Did it used to be the case that they were needed for MPIBCAST? I'll make the changes, although I wonder why Mozart still has a lot of `MPIBCAST` calls. Is removing them in the pipeline for CAM updates?

2023-09-05 18:02 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +#endif
Will do

2023-09-05 18:04 UTC, lizziel commented
Hi @fvitt, I replied to all your comments but will wait to push and confirm changes since derecho is down today. Regarding the mismatch of levels, what is IC? Did something change in the model to make levels change?

2023-09-05 21:14 UTC, jimmielin commented on cime_config/config_compsets.xml
> +        <value compset="GC">1</value>
I think it used to be the case that GEOS-Chem within CESM would crash with NTHRDS > 1, but I am not sure if it is fully fixed now. There was a lingering issue where some code in the interface is not OpenMP-safe.

2023-09-05 21:46 UTC, fvitt commented on src/chemistry/geoschem/chemistry.F90
> +       CALL MPIBCAST( linozData, nLinoz, MPIR8, 0, MPICOM )
@lizziel, The use of `MPIBCAST` predates `mpi_bcast`.  The use of `MPIBCAST` in the chemistry/mozart code should be updated to use `mpi_bcast` and the cpp checks for `SMPD` should be removed.

2023-09-05 21:47 UTC, fvitt commented
> Hi @fvitt, I replied to all your comments but will wait to push and confirm changes since derecho is down today. Regarding the mismatch of levels, what is IC? Did something change in the model to make levels change?

ncdata in the namelist is the initial conditions file (or IC file)

2023-09-05 23:09 UTC, fvitt reviewed
A few more comments/questions

2023-09-05 23:09 UTC, fvitt commented on src/control/cam_comp.F90
> +
No need to add a blank line here.

2023-09-05 23:09 UTC, fvitt commented on src/control/runtime_opts.F90
> +
Should not need to add code for HEMCO.

2023-09-06 21:08 UTC, lizziel commented on bld/build-namelist
> +    #           'exo_coldens_file', 'sulf_file' );
Done

2023-09-06 21:08 UTC, lizziel commented on bld/configure
> +     -hemco             Switch enables the use of the Harmonized Emissions Component.
Done.

2023-09-06 21:12 UTC, lizziel commented on src/chemistry/geoschem/chem_mods.F90
> +      CHARACTER(LEN=255)   :: slsLongnames(nSlsMax)
Done, at least for all character arrays with len 255. There are a few that are small and a few that are larger which I left as is.

2023-09-06 21:13 UTC, lizziel commented on src/chemistry/geoschem/geoschem_diagnostics_mod.F90
> +  USE ErrCode_Mod                               ! Error codes for success or failure
Done.

2023-09-06 21:22 UTC, lizziel commented on src/chemistry/mozart/mo_chem_utls.F90
> +    logical,          intent(in), optional :: compare_uppercase
Do you mean change the default to always convert names to uppercase for the comparison? I would want confirmation from someone at NCAR that Mozart would be okay ignoring case before making that change.

2023-09-06 21:29 UTC, lizziel commented on src/control/cam_comp.F90
> +
Done.

2023-09-06 21:29 UTC, lizziel commented on src/control/runtime_opts.F90
> +
Removed.

2023-09-06 21:31 UTC, fvitt commented on src/chemistry/mozart/mo_chem_utls.F90
> +    logical,          intent(in), optional :: compare_uppercase
No, that is not what I meant.  My suggestion was on the variable name.  Not change the default behavior.  It looks like you want to ignore case when looking up species indices in geos-chem.   That is what converting to upper case before comparing does.  If you want to leave it as it is, that is fine too.

2023-09-07 15:11 UTC, lizziel commented on src/chemistry/mozart/mo_chem_utls.F90
> +    logical,          intent(in), optional :: compare_uppercase
I see now what you are saying. I agree on the name change.

2023-09-07 16:42 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +       CALL MPIBCAST( linozData, nLinoz, MPIR8, 0, MPICOM )
Done.

2023-09-07 16:43 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +#endif
Done.

2023-09-07 16:47 UTC, jimmielin commented
Hi @lizziel, as you're replacing `MPISHORTHAND` etc. in the code, there are some instances in the GEOS-Chem sources that these are used as well that aren't covered in this PR since the GC sources are an external. If they're being phased out we should probably replace these as well at some point. Here's what I've found. Thanks!

```
gc/GeosCore/fast_jx_mod.F90:
   20    USE PRECISION_MOD    ! For GEOS-Chem Precision (fp)
   21  #if defined( MODEL_CESM ) && defined( SPMD )
   22:       USE MPISHORTHAND
   23        USE SPMD_UTILS
   24  #endif

gc/GeosCore/ucx_mod.F90:
 3903      USE UNITS,              ONLY : freeUnit
 3904  #if defined( SPMD )
 3905:     USE MPISHORTHAND
 3906  #endif
 3907  #endif
```

for `SPMD` related to CESM:
```
gc/GeosCore/fast_jx_mod.F90:
   19    USE CMN_FJX_MOD
   20    USE PRECISION_MOD    ! For GEOS-Chem Precision (fp)
   21: #if defined( MODEL_CESM ) && defined( SPMD )
   22        USE MPISHORTHAND
   23:       USE SPMD_UTILS
   24  #endif
   25  
   ..
 2238      ENDIF
 2239  
 2240: #if defined( SPMD )
 2241      CALL MPIBCAST( NJX,       1,             MPIR8,   0, MPICOM )
 2242      CALL MPIBCAST( NW1,       1,             MPIR8,   0, MPICOM )
 ....
 2417      ENDIF
 2418  
 2419: #if defined( SPMD )
 2420      CALL MPIBCAST( QAA,       Size(QAA),     MPIR8,   0, MPICOM )
 2421      CALL MPIBCAST( WAA,       Size(WAA),     MPIR8,   0, MPICOM )
 ....
 2633      ENDDO
 2634  
 2635: #if defined( MODEL_CESM ) && defined( SPMD )
 2636      CALL MPIBCAST( WVAA,      Size(WVAA),     MPIR8,   0, MPICOM )
 2637      CALL MPIBCAST( RHAA,      Size(RHAA),     MPIR8,   0, MPICOM )
 ....
 3074  #if defined( MODEL_CESM )
 3075      ENDIF
 3076: #if defined( SPMD )
 3077  
 3078      CALL MPIBCAST( JLABEL,    JVN_*50,       MPICHAR, 0, MPICOM )

gc/GeosCore/ucx_mod.F90:
 3902  #if defined( MODEL_CESM )
 3903      USE UNITS,              ONLY : freeUnit
 3904: #if defined( SPMD )
 3905      USE MPISHORTHAND
 3906  #endif
 ....
 3930      INTEGER            :: IMON, ITRAC, ILEV
 3931      INTEGER            :: IU_FILE
 3932: #if defined( MODEL_CESM ) && defined( SPMD )
 3933      INTEGER            :: nSize ! Number of elements in State_Chm%NOXCOEFF
 3934  #endif
 ....
 4137  #if defined( MODEL_CESM )
 4138      ENDIF
 4139: #if defined( SPMD )
 4140      CALL MPIBCAST( State_Chm%NOXCOEFF, nSize, MPIR8, 0, MPICOM )
 4141  #endif
```

2023-09-07 19:32 UTC, lizziel commented
@jimmielin, thanks for the heads up on that!

2023-09-08 01:41 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +       CALL MPIBCAST( linozData, nLinoz, MPIR8, 0, MPICOM )
As @jimmielin pointed out, we use this old code in the GEOS-Chem repository too. Unless there are other changes needed in the GEOS-Chem repository I propose I make those changes in the next GEOS-Chem release, to be brought into CESM at a later time when the version gets updated. I would like to keep the official GEOS-Chem in CESM tied to an official version release rather than a dev branch or tag. I could also put the changes in a Z-version off of the current release, specifically a 14.1.2, and make that release specifically to include for this PR. My preference is to bring the changes instead into our current GEOS-Chem development branch for a future version.

2023-09-08 01:49 UTC, lizziel commented on bld/namelist_files/namelist_defaults_cam.xml
> +<dep_data_file chem="geoschem_mam4">/glade/u/home/elundgren/drydep_henrys_law_nc/dep_data_file_geoschem.nc</dep_data_file>
I do not have permission to create a directory in `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem`. I renamed my file to `dep_data_file_geoschem_2022Sep21.nc` but will need getting it somewhere on the `inputdata` path.

2023-09-08 02:02 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +          SELECT CASE ( to_upper(xname_massptr(L,M)(:3)) )
Done.

2023-09-08 02:05 UTC, lizziel commented on src/chemistry/modal_aero/modal_aero_data.F90
> +      character(len=16), public, protected, allocatable :: xname_massptr(:,:)     ! names of species in each mode
Done. The update to make xname_massptr public and protected is now removed.

2023-09-14 20:32 UTC, lizziel commented on bld/namelist_files/namelist_defaults_cam.xml
> +<dep_data_file chem="geoschem_mam4">/glade/u/home/elundgren/drydep_henrys_law_nc/dep_data_file_geoschem.nc</dep_data_file>
@fvitt, I am looking the inputdata paths and see the geoschem folder is in `atm/cam` rather than `atm/cam/chem`. I think it would make more sense to move that to `atm/cam/chem`, and then make new directory `atm/cam/chem/geoschem/dvel` to store the deposition data file for GEOS-Chem. The one for CAM-chem is stored in `atm/cam/chem/trop_mozart/dvel`.  Let me know when you make changes so I can update CAM and test.

2023-09-14 20:34 UTC, lizziel commented on src/chemistry/geoschem/chemistry.F90
> +       CALL MPIBCAST( linozData, nLinoz, MPIR8, 0, MPICOM )
The associated updates to GEOS-Chem repo will be included in 14.2.1 (https://github.com/geoschem/geos-chem/pull/1951).

2023-09-29 13:52 UTC, lizziel commented
HI @fvitt, do you have an idea of when you will get back to this PR? We are hoping to get it merged soon and I am free to work on whatever needs to be done.

2023-09-29 16:35 UTC, fvitt requested changes
I few more comments / questions.

2023-09-29 16:35 UTC, fvitt commented on src/control/runtime_opts.F90
> +#endif
Remove these lines.  Line 209 calls `hemco_readnl`.

2023-09-29 19:44 UTC, lizziel commented on src/chemistry/mozart/mo_chem_utls.F90
> +  public :: utls_chem_is
No, looks like this function is old and no longer used. Deletion done.

2023-09-29 19:44 UTC, lizziel commented on src/chemistry/mozart/mo_chem_utls.F90
> +  end function utls_chem_is
It turns out this function is not used. Now deleted.

2023-09-29 19:45 UTC, lizziel commented on src/chemistry/mozart/short_lived_species.F90
> +          write(fieldname,'(a,a)') trim(slvd_lst(m))
This way of doing it was legacy from Thibaud's original code. I pushed an update to use the more straightforward assignment you suggest.

2023-09-29 19:46 UTC, lizziel commented on src/control/runtime_opts.F90
> +#endif
Done. I also checked that there are no more instances of HEMCO_CESM ifdefs. This was the final one.

2023-09-29 19:48 UTC, lizziel commented on cime_config/buildnml
> +
This gets tricky and I am curious what your thoughts are. The run directory configuration files are stored in the GEOS-Chem source code. However, the content of the files should be edited by the user in the run directory. Otherwise it would get very weird if you try to have multiple runs with different run settings using the same code. The solution here is to copy the files to the run directory where they can be edited. Do you have a better solution?

2023-09-29 19:53 UTC, lizziel commented on cime_config/buildnml
> +
I should add that the reason they are in the run directory is because the format and content can change version to version in GEOS-Chem. It works best to keep it under version control along with the rest of the code so you know you are using the correct configuration file for the version you are running.

2023-10-01 19:21 UTC, gold2718 commented on cime_config/buildnml
> +
> I should add that the reason they are in the run directory is because the format and content can change version to version in GEOS-Chem. It works best to keep it under version control along with the rest of the code so you know you are using the correct configuration file for the version you are running.

@lizziel, While I agree that the template or default configuration files should be kept in and copied from the source, I think the run directory is the wrong place and the current method will likely not work with multi-instance runs. Ideally, these would be copied into the case directory during [`./case.setup`](https://esmci.github.io/cime/versions/master/html/users_guide/setting-up-a-case.html). This is not trivial, however, there is some precedent in that the ice sheet model (CISM) does have a special script to do something similar during `./case.setup` (see [lines 419-423](https://github.com/ESMCI/cime/blob/b8d6d2bc3b0ab44af4de3dc338a45ecf686bb409/CIME/case/case_setup.py#L419) in case_setup.py).
After this, the (possibly modified) configuration files should be copied to the run directory by buildnml.
Of course, this would be a CIME modification so I know it complicates things a bit.

Finally, the config files should be copied from the run directory to the CaseDocs directory. To do this, regex patterns for the files should be added to `cpglob` in [CIME/case/preview_namelists.py](https://github.com/ESMCI/cime/blob/b8d6d2bc3b0ab44af4de3dc338a45ecf686bb409/CIME/case/preview_namelists.py#L117). This could be added to the CIME modification.

I hope this helps and is not a repeat but I did not see similar notes anywhere.

2023-10-01 19:22 UTC, gold2718 commented on cime_config/buildnml
> +
Also, the PR description above is not listed as closing any issues. Should a "closes #424" or something similar be added there?

2023-10-02 16:27 UTC, gold2718 commented on cime_config/buildnml
> +
I think we are basically on the same page. First, I have a few picky Python comments:

1. This looks like a Python script, why the `#! /usr/bin/env bash` at the top?

2. Technically, I believe paths are supposed to be built one directory at a time to allow the OS to control path format.  E.g.,
```
      geoschem_config_src = os.path.join(cam_root, 'src', 'chemistry', 'geoschem', 'geoschem_src', 'run', 'CESM')
```

3. We have been converting to f strings. So for instance, you could have:
```
      raise SystemExit(f"ERROR: Did not find path to GEOS-Chem source code at {geoschem_src}")
```

4. Perhaps add a check for the existence of `source_file` before doing the `shutil.copy`.

2023-10-03 23:02 UTC, fvitt requested changes
A few more comments.

2023-10-03 23:02 UTC, fvitt commented on src/physics/cam/physpkg.F90
> -
Is this change really needed?

2023-10-05 16:40 UTC, lizziel commented on src/physics/cam/physpkg.F90
> -
It is not, but I figured the second blank line was not needed. I can put it back if you would like.

2023-10-05 18:29 UTC, lizziel commented on cime_config/buildnml
> +
The python script is now the equivalent in bash (cime_config/cam.case_setup). Rather than copy the files to the run directory during build I would like to copy them during case submit. I am thinking another cime update similar to what I did for case setup, but this time in case_submit.py, with corresponding file cime_config/cam.case_submit. The config files are not used for build and should be able to be modified between runs. Do you approve that idea?

2023-10-05 18:31 UTC, lizziel commented on cime_config/config_compsets.xml
> +        <value compset="GC">1</value>
Okay, I'll wait for the final go-ahead before deleting.

2023-10-05 18:32 UTC, lizziel commented on bld/namelist_files/namelist_defaults_cam.xml
> +<dep_data_file chem="geoschem_mam4">/glade/u/home/elundgren/drydep_henrys_law_nc/dep_data_file_geoschem.nc</dep_data_file>
Done.

2023-10-06 12:23 UTC, gold2718 commented on cime_config/buildnml
> +
> submit

Why at submit time?
Why not just copy all the files to the run directory in cime_config/buildnml, say right after the `atm_in` files are copied. That way, it happens every time `preview_namelists` is called (including before submit).

2023-10-10 14:55 UTC, lizziel commented on cime_config/buildnml
> +
Ah, okay, I understand now buildnml is a different kind of building than compiling. If it is called every time there is a submit then that works great for what we need. Thanks for the clarification!

2023-10-13 17:44 UTC, lizziel commented on src/physics/cam/physpkg.F90
> -
Removed.

2023-10-13 17:44 UTC, lizziel commented on cime_config/buildnml
> +
CIME PR for this is here: https://github.com/ESCOMP/CAM/pull/484

2023-10-13 17:51 UTC, lizziel commented on cime_config/buildnml
> +
See CAM updates in `cime_config/buildnml` and `cime_config/cam.case_setup`. It tested this with the CIME updates and it works.

2023-10-13 17:54 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@fvitt, do you have any thoughts on my comment above?

2023-10-13 18:21 UTC, jedwards4b commented on cime_config/cam.case_setup
This file should be rewritten in python for consistency with cime.

2023-10-13 18:21 UTC, jedwards4b commented on cime_config/config_compsets.xml
> +        <value compset="GC">1</value>
I think that compset="GC" is too general and may over match - can this be changed to be more specific? Perhaps "GEOSChem" would be better.

2023-10-13 18:21 UTC, jedwards4b commented on cime_config/config_pes.xml
> +        <pes pesize="any" compset="GC">
Why would cam presume to change the threading of any other component?

2023-10-13 18:21 UTC, jedwards4b commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="geoschem"/>
Why add a test for a machine about to be retired - can this be redone for derecho?

2023-10-13 18:21 UTC, jedwards4b commented on src/physics/cam/constituents.F90
> +      write(errmsg, *) sub//': FATAL: advected tracer (', trim(name), ') index for greater than pcnst=', pcnst
index for greater?   Please improve this message.

2023-10-13 18:48 UTC, lizziel commented on cime_config/cam.case_setup
I'll switch to python. I used bash since that was done for cism.

2023-10-13 18:49 UTC, lizziel commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="geoschem"/>
Yes, that should be changed. Thanks for catching that.

2023-10-13 19:26 UTC, lizziel commented on cime_config/cam.case_setup
Would you like to keep it as a script called via `run_cmd_no_fail`, or import a python package from cam?

2023-10-13 19:28 UTC, jedwards4b commented on cime_config/cam.case_setup
keep it as a script - thanks

2023-10-13 20:31 UTC, lizziel commented on cime_config/cam.case_setup
I pushed an update and tested that it works. See new file `cime_config/cam.case_setup.py` and cime update at https://github.com/ESMCI/cime/pull/4497.

2023-10-13 20:31 UTC, jedwards4b commented on cime_config/cam.case_setup
thanks

2023-10-13 20:35 UTC, lizziel commented on src/physics/cam/constituents.F90
> +      write(errmsg, *) sub//': FATAL: advected tracer (', trim(name), ') index for greater than pcnst=', pcnst
Done.

2023-10-13 20:36 UTC, lizziel commented on cime_config/config_pes.xml
> +        <pes pesize="any" compset="GC">
I'm not sure the details of why this was needed and it is unclear if it is still an issue. I will remove setting nthrds to 1 for all components and see if it causes any problems.

2023-10-13 20:37 UTC, lizziel commented on cime_config/buildnml
> +
cam.case_setup is now cam.case_setup.py. Back to python :)

2023-10-13 20:38 UTC, jedwards4b commented on src/physics/cam/constituents.F90
> +      write(errmsg, *) sub//': FATAL: advected tracer (', trim(name), ') index for greater than pcnst=', pcnst
I think that it may be important to include the tracer name, why did you remove that part?
': FATAL: advected tracer (', trim(name), ') index greater than pcnst=', pcnst

2023-10-13 20:45 UTC, lizziel commented
**TODO based on comments to date:**

- [ ] Change tests to use derecho rather than cheyenne
- [ ] Remove forcing nthrds=1 for all components if using GEOS-Chem and test to see if it is really needed
- [ ] Figure out why the FCSD_GC tests fail due to wrong number of vertical levels in initial conditions. Did something change in the model for the base compset FCSD? Our initial conditions is a slightly modified copy of it. Maybe there is a new restart file.
- [ ] I just merged in the latest cam_development so need to do a new externals checkout for further testing. case setup and build work fine but the runs are now failing.
- [ ] Further discuss using "GC" versus "GEOSCHEM". The downside to using GEOSCHEM is that we still using "_GC" in the compset names. Should we use GEOSCHEM there too, e.g. FCHIST_GEOSCHEM and FCnudged_GEOSCHEM?

2023-10-13 20:58 UTC, jedwards4b commented
FCnudged_GC is fine and that is the compset alias - the compset name is 
2010_CAM60%GC%HEMCO_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_CISM2%NOEVOLVE_SWAV.    And I think that in the longname you should use GEOSCHEM.

2023-10-13 21:27 UTC, jedwards4b commented on cime_config/config_component.xml
> +    <desc option="GC"           >GEOS-Chem troposphere/stratosphere chemistry :</desc>
Now that the longname has been changed from GC to GEOSCHEM the option will need to be changed to match.

2023-10-16 20:09 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="geoschem"/>
No, please go ahead and add the test as cheyenne, though it would be good for you to hand test it on derecho.  We are going to make a wholesale change of all cheyenne tests to derecho at a future date.   Right now we are trying to get all regression tests to work on derecho before we make that switchover.  We are not currently routinely running derecho tests yet.

2023-10-17 17:15 UTC, lizziel commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="geoschem"/>
Okay, thanks for the heads up!

2023-10-17 18:02 UTC, lizziel commented on cime_config/config_component.xml
> +    <desc option="GC"           >GEOS-Chem troposphere/stratosphere chemistry :</desc>
Done.

2023-10-19 20:51 UTC, lizziel commented
@fvitt, @jedwards4b, I am considering whether to delete the FCSD_GC compset since the equivalent compset using CAM-chem (FCSD) at 0.9x1.25 is also not working. The dvel file is not found and the initial conditions file is no longer there ([this file](https://github.com/ESCOMP/CAM/blob/559fdb7814d27b3da4483029870473aa035e8bb1/bld/namelist_files/use_cases/sd_trop_strat_vbs_cam6.xml#L7)). I would need a new IC file for FCSD_GC. I could add in an FCSD_GC compset later if FCSD becomes functional again and having a GEOS-Chem version would be useful. But my understanding is FCnudged is used more now.

2023-10-19 21:06 UTC, lizziel commented
@fvitt, @jedwards4b: NTHRDS is 1 by default without the GEOS-Chem-specific setting to 1 in `config_pes.xml` and `config_compsets.xml`. I can remove those if you would like. We do need to make sure `NTHRDS` is 1 when using GEOS-Chem, although in my tests the model hangs before it even gets to GEOS-Chem. I did not try setting NTHRDS for atm only to >1 since that seems like not something that would appear in the defaults.

2023-10-20 16:25 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
The filtering out of short-lived species sounds like a good feature to add.  Why don't you add to the master field lists additional species needed for GEOSChem and remove the duplicate lists in the goeschem use case files?

2023-11-03 15:21 UTC, lizziel commented
Following up on this, @jimmielin and I both did tests with NTHRDS other than 1 for GEOS-Chem and other compsets. There is   varying behavior for all. The default right now is NTHRDS=1 for GEOS-Chem without the overrides so I went ahead and deleted those. If we need to add them back later we can.

Regarding FCSD_GC, I deleted that compset. We can add it in later if there is demand. Currently it does not work so deleting is simplest way forward. Users should use FCnudged_GC instead.

@fvitt, are there any other updates needed prior to merge?

2023-11-03 15:22 UTC, lizziel commented on cime_config/config_pes.xml
> +        <pes pesize="any" compset="GC">
I deleted the overrides since the defaults are sufficient.

2023-11-03 17:30 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@lizziel You have not responded to my latest comments on this (2 weeks ago).

2023-11-06 14:48 UTC, lizziel commented
The CIME PR that goes with this PR (https://github.com/ESMCI/cime/pull/4497) is now ready for merge when this PR goes in.

2023-11-07 17:55 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
Ah, I missed seeing the new comment. We do not add the GEOS-Chem species to the master deposition lists to avoid confusion in the overlap of species between CAM-Chem and GEOS-Chem. Would you prefer adding GEOS-Chem species that are not CAM-Chem species to the master lists?

2023-11-08 14:09 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@lizziel 
I prefer adding GEOS-Chem species to the master deposition lists, as long as we are not conflicting with CAM-Chem/WACCM lists.  You can list the GEOS-Chem species in separate lists, like this:
```
<list id="GOES-Chem">
 ...
</list>
```

2023-11-08 14:14 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@lizziel If the GEOS-Chem species are added to the master deposition lists and the lists removed from the use case files, then I think the changes here can be like:
```suggestion
    $gas_wetdep_list = $nl->get_value('gas_wetdep_list');
    $gas_wetdep_list = filter_dep_list( $gas_wetdep_list, $print_lvl, \@species_list, \@nottransported_list );
    if ($print_lvl>=2) {print " gas wet dep list : $gas_wetdep_list  \n" ;}
```

2023-11-08 15:16 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@fvitt, I will add the species to the master lists and test that out.

2023-11-13 16:50 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
Hi @fvitt, I want t make sure you are aware that adding the GEOS-Chem deposition species to the master deposited lists will mean Mozart and GEOS-Chem must both deposit common advected species that are also in the deposition lists. This may be fine, but could potentially cause a problem in the future if Mozart or GEOS-Chem deposits something that is not set up to be deposited in the other model. For example, possibly NH4 and down the road SO4. I wonder if we should discuss this with a wider group before making this structural change?

2023-11-13 21:43 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
Hmm, this is already an issue since GEOS-Chem does not dry deposit C2H2, but CAM-Chem does. Is there any chance we could put off removal of the current deposition list implementation until later? There is a student at MIT waiting for this merge to continue his research.

2023-11-13 21:58 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@lizziel 
The simple thing to do for this merge is revert the changes to ChemNamelist.pm and explicitly list the deposited species the use case files for GEOSChem's needs.  Otherwise, your changes rather convoluted and difficult to understand.

2023-11-14 13:31 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@fvitt, the depositions lists are explicitly defined in the GEOS-Chem use case files. The changes in ChemNamelist.pm are needed to filter those lists, unlike CAM-Chem which takes the list from the master deposition files. Maybe the master deposition list files should be expanded with a special list for GEOS-chem species to be separate from CAM-Chem species list?

2023-11-14 15:06 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
@lizziel  Can you provide lists that do not need filtering?

2023-11-14 18:05 UTC, lizziel commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
We would prefer to have a master list of deposited species used in GEOS-Chem with flexibility to make them either advected or non-advected. This is best done through filtering. What do you think about passing a new argument to `set_dep_lists` (called from `build-namelist`) that specifies if using GEOS-Chem or Mozart. That could pass through the functions in `ChemNamelist.pm` to ultimately choose the master deposition list files. There could be separate master deposition files in `cam/bld/namelist_files` for GEOS-Chem and Mozart. This would be easier to maintain and would allow `set_dep_lists` to be used the same way for both mechanisms.

2023-11-14 18:34 UTC, fvitt commented on bld/perl5lib/Build/ChemNamelist.pm
> +    }
> We would prefer to have a master list of deposited species used in GEOS-Chem with flexibility to make them either advected or non-advected. This is best done through filtering. What do you think about passing a new argument to `set_dep_lists` (called from `build-namelist`) that specifies if using GEOS-Chem or Mozart. That could pass through the functions in `ChemNamelist.pm` to ultimately choose the master deposition list files. There could be separate master deposition files in `cam/bld/namelist_files` for GEOS-Chem and Mozart. This would be easier to maintain and would allow `set_dep_lists` to be used the same way for both mechanisms.

I like this suggestion.  I look forward to seeing the implementation.

2023-11-16 22:01 UTC, lizziel commented
@fvitt, could you move file `/glade/p/univ/umit0034/Shared/dep_data_file_geoschem_c230417.nc` to `/glade/campaign/cesm/cesmdata/cseg/inputdata/atm/cam/chem/geoschem/dvel`. I need to make this file the default for use with GEOS-Chem rather than the other one that you moved. You can remove the file already there (dep_data_file_geoschem_2022Sep21.nc). We will not use it for this version and I have a back-up copy.

2023-11-16 22:09 UTC, fvitt commented
> @fvitt, could you move file `/glade/p/univ/umit0034/Shared/dep_data_file_geoschem_c230417.nc` to `/glade/campaign/cesm/cesmdata/cseg/inputdata/atm/cam/chem/geoschem/dvel`. I need to make this file the default for use with GEOS-Chem rather than the other one that you moved. You can remove the file already there (dep_data_file_geoschem_2022Sep21.nc). We will not use it for this version and I have a back-up copy.

I have copied the file over.

2023-11-17 19:09 UTC, lizziel commented
Thanks @fvitt. I did manual tests this morning and all GEOS-Chem compsets work, as well as the equivalent ones that use CAM-Chem.

2023-11-28 21:57 UTC, fvitt approved these changes
I trust that you have done some regression tests and verified that our CAMChem and WACCM compsets do not change answers.
Thanks.

2023-11-28 21:58 UTC, fvitt commented
@cacraigucar 
Please invite other SEs to review this PR.

2023-11-28 22:28 UTC, jedwards4b approved these changes
One more suggested change...

2023-11-28 22:28 UTC, jedwards4b commented on cime_config/buildnml
> +        if os.path.isdir(rundir) and '-chem geoschem' in CAM_CONFIG_OPTS:
This requires an exact match to '-chem geoschem'. I wonder if a regular expression would be better so that 
the match is to '-chem\s+geoschem'

2023-11-28 22:28 UTC, jedwards4b commented on cime_config/cam.case_setup.py
> +if '-chem geoschem' in cam_config:
same concern here.

2024-01-16 18:27 UTC, brian-eaton commented on cime_config/buildnml
> +                shutil.copy(file1,file2)
Is there a reason not to copy these configuration files directly from the source directory to the run directory?  Why copy to the case directory first?  Copying from the source to the run directory right here would eliminate the need for `cam.case_setup.py` and ESMCI/cime#4497.

2024-01-16 19:40 UTC, lizziel commented
Hi @brian-eaton, thanks for the comment. This design is different from my original PR. I was asked to change it to this by NCAR developers.

2024-01-16 20:15 UTC, jedwards4b commented
@lizziel Can you please be more specific in your last comment - quoting the request for change might help - I agree with @brian-eaton that we don't want to copy files twice if we can avoid it.

2024-01-16 21:34 UTC, lizziel commented
@jedwards4b The current method using cam.case_setup.py came out of discussion in late Sept 2023 on this thread. To be more clear, there always was an initial copy to the case directory upon case setup, followed by a copy to the run directory upon each submit. What changed is how it is done.

Ideally there would be one copy, with configuration files in the case directory created from xml files and then copied to the run directory. This is what is done for `atm_in` et al. However, GEOS-Chem configuration files are not created from namelists and are stored in the source code. They are therefore copied to the case directory where they can be edited prior to submit, or in between multiple submits.

2024-01-16 22:26 UTC, brian-eaton commented
Thanks @lizziel for pointing out the previous discussion in this thread.  That makes sense now.  I was running into a problem with the copy in `buildnml` failing when I tried to test with `FC2000climo_GC`.  I'll just work around that for now with a file copy from my run script.

2024-01-16 23:44 UTC, cacraigucar requested changes

2024-01-16 23:44 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="geoschem"/>
@lizziel - Since this PR did not come in before cheyenne was retired, we have made the changeover to using derecho now in our testlist.  Please change these all to derecho.

2024-01-16 23:44 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="geoschem"/>
One of these test should be duplicated in "aux_cam" and another test should be "pre-alpha".  If they are not routinely tested in CAM, the ability to run GEOS-Chem could be accidentally broken and we not know it.

2024-01-18 18:08 UTC, brian-eaton requested changes

2024-01-22 23:18 UTC, brian-eaton requested changes
I think this is looking good.  Just a few more minor comments.

2024-01-22 23:18 UTC, brian-eaton commented on bld/build-namelist
> +    $nl->set_variable_value('wetdep_inparm', 'gas_wetdep_list', $gas_wetdep_list);
These statements are not needed.  The wetdep and drydep list variables are all set in `add_default` calls above.

2024-01-30 22:36 UTC, lizziel commented
@brian-eaton, @cacraigucar - All updates are pushed now. I updated the test suite to use derecho for GEOS-Chem compsets and also added aux_cam and prealpha as categories. I am able to manually create GEOS-Chem compset cases and successfully run.

2024-01-30 22:44 UTC, brian-eaton commented on bld/build-namelist
> +    $nl->set_variable_value('wetdep_inparm', 'gas_wetdep_list', $gas_wetdep_list);
@lizziel, this comment hasn't been addressed yet.

2024-01-30 22:58 UTC, cacraigucar commented
@lizziel - Please just have one GEOS-Chem aux_chem test and a different one for pre_alpha - your choice on which ones to test.  I don't think we need to test all four compsets, but should catch any errors with a couple of tests.  Also, except for a couple of important main CAM compsets, we don't run the same tests in aux_cam and pre-alpha (aux_cam are run when we make CAM tags and pre-alpha are run when CESM tags are made).  Let me know if you have questions about this.

Also, could you merge to the head of cam_development?  Your PR may be the next one and then it will be ready.

2024-01-31 16:28 UTC, brian-eaton approved these changes
Looks good.  Nice work.

2024-01-31 19:43 UTC, fvitt commented
@lizziel Can you document the changes in the `doc/ChangeLog` file?

2024-01-31 21:40 UTC, lizziel commented
@fvitt, yes, I will add documentation to Changelog. Do you use a git diff command to generate the list of files with prefix D, M, etc, or put it in manually?

2024-01-31 22:14 UTC, lizziel commented
All four geoschem compset tests passed. I will push the Changelog updates tomorrow.

2024-01-31 22:25 UTC, fvitt commented
> @fvitt, yes, I will add documentation to Changelog. Do you use a git diff command to generate the list of files with prefix D, M, etc, or put it in manually?

Yes:
```
   git diff --name-status ...
```

2024-02-01 15:04 UTC, lizziel commented
@fvitt

Yes, you may push directly to the branch. I checked that you are added as a collaborator with write permissions. Could you explain what the real kind script is testing? Is this something I should fix at some point?

2024-02-01 17:02 UTC, cacraigucar reviewed
I just realized that none of the GEOS-Chem tests use the SE dycore (which is one of the main dycores for CAM7).  Has GEOS-Chem been tested with the SE dycore?  This should not hold up this PR, but should be considered in the follow-on PR for GEOS-Chem.

2024-02-01 17:20 UTC, jimmielin commented
> I just realized that none of the GEOS-Chem tests use the SE dycore (which is one of the main dycores for CAM7). Has GEOS-Chem been tested with the SE dycore? This should not hold up this PR, but should be considered in the follow-on PR for GEOS-Chem.

Hi @cacraigucar, yes I have ran with the SE dycore using the ne30 grid with the FCnudged_GC compset. It should work out of the box.

2024-02-01 17:21 UTC, cacraigucar commented
> > I just realized that none of the GEOS-Chem tests use the SE dycore (which is one of the main dycores for CAM7). Has GEOS-Chem been tested with the SE dycore? This should not hold up this PR, but should be considered in the follow-on PR for GEOS-Chem.
> 
> Hi @cacraigucar, yes I have ran with the SE dycore using the ne30 grid with the FCnudged_GC compset. It should work out of the box.
That is good to know!  Thanks

2024-02-02 13:09 UTC, fvitt commented
@lizziel 
The GEOS-Chem test fails to build with this error:
```
[Errno 2] No such file or directory: '/glade/derecho/scratch/fvitt/aux_cam_20240201095805/SMS_Ld1_Vnuopc.f09_f09_mg17.FCHIST_GC.derecho_intel.cam-outfrq1d.GC.aux_cam_20240201095805/species_database.yml'
```
See test dir:
```
/glade/derecho/scratch/fvitt/aux_cam_20240201095805/SMS_Ld1_Vnuopc.f09_f09_mg17.FCHIST_GC.derecho_intel.cam-outfrq1d.GC.aux_cam_20240201095805
```

2024-02-02 15:16 UTC, lizziel commented
@fvitt, did you pull in my CIME PR https://github.com/ESMCI/cime/pull/4497? This is needed so that the GEOS-Chem configuration files are copied to the run directory.

2024-02-02 15:25 UTC, fvitt commented
> @fvitt, did you pull in my CIME PR [ESMCI/cime#4497](https://github.com/ESMCI/cime/pull/4497)? This is needed so that the GEOS-Chem configuration files are copied to the run directory.

Is there a tag that includes this?

2024-02-02 15:26 UTC, lizziel commented
There is not. The PR is on hold to be brought in along with the GEOS-Chem PR. This is because it updates case setup to expect a new python file in CAM to be run during case setup. To test GEOS-Chem I brought in the change to cime before submitting tests. This makes sure the GEOS-Chem config files are copied to the case directory.

2024-02-02 15:30 UTC, lizziel commented
I just realized that technically I do not know if there a tag with the PR merged. There is a commit that reverts it so perhaps the prior commit does have a tag. @jedwards4b, could you advise?

2024-02-02 15:32 UTC, fvitt commented
@cacraigucar 
Is it okay to let the goeschem tests fail until a new cime tag is brought in to fix the issue with geoschem config file?

2024-02-02 15:39 UTC, cacraigucar commented
> @cacraigucar Is it okay to let the goeschem tests fail until a new cime tag is brought in to fix the issue with geoschem config file?

@fvitt - Yes, let's go ahead and allow this to go in with the failing geoschem tests.  Make sure you mark it in the plans page, so Chris knows to expect it with the prealpha tag, unless cime is updated by then for it.

2024-02-02 17:23 UTC, merged

2024-02-02 17:24 UTC, jedwards4b commented
So this is going to require another cime branch - right?

2024-02-02 17:34 UTC, cacraigucar commented
> So this is going to require another cime branch - right?

That is correct.  @lizziel can let us know whether they need this immediately or if we can wait for the next cime branch that you'll inevitably be making for Chris.

2024-02-02 17:36 UTC, cacraigucar commented
> > So this is going to require another cime branch - right?
> 
> That is correct. @lizziel can let us know whether they need this immediately or if we can wait for the next cime branch that you'll inevitably be making for Chris.

I should mention that this change also needs to go into the main cime branch as well, but we won't be able to use it there until we no longer need the branches.

2024-02-02 17:47 UTC, jedwards4b commented
It will go into cime master first, then I create a branch.

2024-02-02 17:49 UTC, cacraigucar commented
> It will go into cime master first, then I create a branch.

That is perfect.  Let see when @lizziel thinks this needs to be made for their work.  They may be able to use their personal branch until you make the next cime branch for other reasons.

2024-02-02 18:00 UTC, cacraigucar commented
@jedwards4b - This was the response from @lizziel via email:

`We would prefer there to be a CIME tag compatible with GEOS-Chem as soon as possible so that we can tell people it is functional. Let me know if this will be an issue.`

Let us know when you make the cime branch tag and we will probably update all the CAM externals at that point.

2024-02-02 18:10 UTC, cacraigucar commented
@jedwards4b - This may be in the branch tag you just made for Chris.  The required changes were in:  https://github.com/ESMCI/cime/pull/4497 which said it was merged into cime in November.  Could you confirm whether this is in the branch tag and what that tag is?

2024-02-02 18:14 UTC, fischer-ncar commented
@cacraigucar The changes in https://github.com/ESMCI/cime/pull/4497 were removed because they were causing all of my testing to fail.  So the changes are not in the existing branch tag.

2024-02-02 18:41 UTC, cacraigucar commented
@fischer-ncar Is there an open issue in cime to bring them back in, in a way that doesn't cause your tests to fail?

2024-02-02 18:45 UTC, fischer-ncar commented
@cacraigucar there's a cime PR that's about to be merged when the tests for it finish.  My tests will pass with this new cam tag.  ESMCI/cime#4540

2024-02-02 20:09 UTC, jedwards4b commented
cime6.0.209_httpsbranch01 is the cime tag you want here.