mods to pass cam_dev ERP tests, misc cam_dev bug fixes
ESCOMP/CAM pull request #493
Opened 2022-01-03 18:00 UTC by adamrher

Fixes https://github.com/ESCOMP/CAM/issues/491

2022-01-03 21:23 UTC, cacraigucar approved these changes
Preliminary testing indicates this solves the restart issues.

2022-01-04 04:14 UTC, nusbaume approved these changes

2022-01-04 06:06 UTC, gold2718 reviewed
Question about the logic.

2022-01-04 06:06 UTC, gold2718 commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
This new logic seems fragile. Is it true that a better check would be testing _when_ radiation is called relative to the CAM time step? Sure, at the moment, `cam_dev` is the only package that is different but I would like the logic and documentation to be clear on this point.

2022-01-04 13:37 UTC, fvitt approved these changes

2022-01-04 19:54 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
as we discussed, let's put ```nextwsw_cday``` in the restarts. Should we then take it from the restarts for plain ol' cam physics as well, to make this logic independent of physics package?

w.r.t to the plain ol' cam physics package ... the restarts probably contains the state from dp_coupling or some state after CAM_run4, but before the final CAM_run1 call, right? But what about the radiation in the restarts, is it from the prior CAM_run1 call, or that final CAM_run1 call? I'm trying to understand if the radiation on restarts is the same as that produced during the CAM_run1 call during restart initialization.

2022-01-04 21:34 UTC, gold2718 commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
Yes, this should happen all the time.
Do you need any coding help?

2022-01-04 22:17 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
Yes. It would be helpful to know (1) what module has the appropriate list of vars where ```nextsw_cday``` should go to be written to restart, and (2) an example of reading a variable from restarts in the atm_comp_xxx module.

2022-01-04 22:38 UTC, gold2718 commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
I think all of this can (and should) go into radiation.F90 (rrtmg for sure and maybe also camrt).
At the module level (just above the `contains` statement):
```
type(var_desc_t) :: nextsw_cday_desc
```
In `radiation_define_restart`:
```
ierr = pio_def_var(File, 'nextsw_cday', pio_int, nextsw_cday_desc)
ierr = pio_put_att(File, nextsw_cday_desc, 'long_name', 'future radiation calday for surface models')
```
In `radiation_write_restart`:
```
ierr = pio_put_var(File, nextsw_cday_desc, (/ nextsw_cday /))
```
In `radiation_read_restart`:
```
ierr = pio_inq_varid(File, 'nextsw_cday', vardesc)
ierr = pio_get_var(File, vardesc, nextsw_cday)
```
Note: Add the `radiation_read_restart` code at the end of the routine. This will force a crash if `nextsw_cday` is not on the restart file.

2022-01-05 21:32 UTC, peverwhee approved these changes

2022-01-06 02:46 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
Or do I need to add ```nextsw_cday``` to ```read_restart_physics``` in read_restart_physics.F90?

2022-01-06 03:40 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
part 3 of Adam talks to himself. Steve's mods seem to have worked; I've past ERP tests for both F2000dev and F2000climo. I suspect Steve's mods work b/c for ```is_first_restart_step()``` the ```read_restart_physics``` subroutine is called, and this sets the module level value of ```nextsw_cday``` in radiation.F90.

Since I've not done my usual diligence of printing out nextsw_cday, I will wait to push these mods until I get verification from @gold2718 that my understanding is what he intended these mods to do.

2022-01-06 03:43 UTC, gold2718 commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
Great self-talk! Yes, the `pio_get_var` call in `radiation_read_restart` sets the module variable to the value it had when the restart file was written. I think that should set you back on track so that you do not need the other mods. That's the magic of restarts!

2022-01-06 17:20 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
having slept on this ... I think I can actually get rid of calling ```radiation_nextsw_cday``` in the init phase of mct/nuopc caps, and replace it with a ```use radiation        , only: nextsw_cday```. This will work because for startups, radiation_tend is called in initialization for all phys packages, which sets ```nextsw_cday``` correctly, and then for restart runs ```nextsw_cday``` will be made available by the ```radiation_read_restart``` call. 

I'm not so sure about simple models. I think it will work as long as simple models always calls its simplified radiation_tend in CAM_run1, which will set it to -1.

2022-01-06 18:21 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   if (doinit .and. is_first_restart_step() .and. cam_physpkg_is("cam_dev")) then
This seems to have worked as it's passing a bunch of ERP tests (nuopc, mct, F2000climo, F2000dev, QPC4). There is an inefficiency in this approach for standard cam physics; the ```nextsw_cday``` read in from restarts will be overwritten by the value computed in CAM_run1 in the initialization phase. But since they are identical, it doesn't break anything.

2022-01-06 19:10 UTC, gold2718 requested changes
Not strictly necessary but I think a bit more cleanup and we have radiation always in charge of `nextsw_cday`.

2022-01-06 19:10 UTC, gold2718 commented on src/cpl/mct/atm_comp_mct.F90
> +          call seq_infodata_PutData( infodata, nextsw_cday=get_curr_calday() )
How about initializing `nextsw_cday` in `radiation_init` so that you can use that here? That keeps radiation in charge of this quantity. In `radiation_init`, you would have something like:
```
if (.not. is_first_restart_step()) then
   nextsw_cday = get_curr_calday()
end if
```
Thoughts?

2022-01-06 21:13 UTC, adamrher commented on src/physics/rrtmg/radiation.F90
> +   use phys_control,   only: cam_physpkg_is
done

2022-01-06 21:58 UTC, adamrher commented on src/cpl/mct/atm_comp_mct.F90
> +          call seq_infodata_PutData( infodata, nextsw_cday=get_curr_calday() )
I'm on board. As you say, it's the last mod needed to make radiation entirely in charge of ```nextsw_cday```. I did this in camrt as well. I don't think it will be necessary after we fully transition to nuopc, but it nonetheless makes this variable explicitly defined for all time after init.

2022-01-06 22:20 UTC, gold2718 approved these changes
By George*, I think we've got it!

*No, I don't know who George is. George V maybe?

2022-01-06 22:37 UTC, peverwhee approved these changes

2022-01-06 23:29 UTC, nusbaume approved these changes

2022-01-07 00:14 UTC, cacraigucar approved these changes

2022-01-07 22:03 UTC, merged