New CAM CARMA tests
ESCOMP/CAM pull request #505
Opened 2022-01-14 17:56 UTC by manderberg

Adding new CARMA tests to CAM regression testing.
Adding a new CARMA testing category.
Issue not closing; more tests coming in another PR.

Addresses #420

2022-01-14 22:37 UTC, fvitt approved these changes
Looks OK to me.  Thanks for the work on this.

2022-01-17 16:31 UTC, gold2718 requested changes
I think there are a few files that are not being used and should be removed.
Otherwise, it looks okay.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam
> +
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_clm
> +
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cpl
> +reprosum_recompute=.true.
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/user_nl_cam
> +carma_reftfile="camrun.cam.r.carma_reft.nc"
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/user_nl_cpl
> +reprosum_recompute=.true.
I do not see a test using this file, please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_test_radiative/user_nl_clm
> +
This test is for an aquaplanet compset so this file is not used. Please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_test_tracers2/user_nl_clm
> +
This test is for an aquaplanet compset so this file is not used. Please remove.

2022-01-17 16:31 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_carma/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
It looks like this file is no longer used. Please remove.

2022-01-18 17:41 UTC, fvitt commented
Should we remove the carma models that do not have regression tests?  
These models do not have tests:
```
 bc_strat
 cirrus
 cirrus_dust
 pmc_sulfate
 tholin
```
@cbardeen , @tilmes thoughts?

2022-01-18 18:24 UTC, cbardeen commented
I don’t particularly care about bcstrat or tholin, but do want the other ones retained. Brian Toon’s group is working on enhancing the cirrus model. Mike did publish some papers with bcstrat, but I think we have better soot models now.

> On Jan 18, 2022, at 10:41 AM, fvitt ***@***.***> wrote:
> 
> ﻿
> Should we remove the carma models that do not have regression tests?
> These models do not have tests:
> 
>  bc_strat
>  cirrus
>  cirrus_dust
>  pmc_sulfate
>  tholin
> @cbardeen , @tilmes thoughts?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-01-18 19:44 UTC, tilmes commented
I think, we agreed to remove tholin, pmc_sulfate,  bc_strat, and cirrus_dust (if I recall). I think, cirrus  is a model we did not get to run, but want to leave in, is that correct?

2022-01-19 17:17 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
This is a test we would like to keep.  Currently it fails.  We will try to fix this test.

2022-01-19 17:19 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
We would like to keep this test.  Currently fails with DEBUG=TRUE.

2022-01-19 20:42 UTC, fvitt requested changes

2022-01-19 20:42 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/shell_commands
> +./xmlchange CAM_CONFIG_OPTS=" -phys cam4 -chem waccm_ma_sulfur -carma mixed_sulfate"
```suggestion
./xmlchange CAM_CONFIG_OPTS=" -phys cam4 -rad rrtmg -chem waccm_ma_sulfur -carma mixed_sulfate"
```
@manderberg : Try this change for mixed_sulfate.  Add this back to the the test list if this works.

2022-01-19 21:21 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
What is the test that is failing? It might be related to a known bug.

2022-01-19 21:31 UTC, fvitt commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
@gold2718 This is the failing test:
`ERC_D_Ln9_Vmct.f10_f10_mg37.QPC5.cheyenne_intel.cam-carma_test_detrain`
I think it is an issue with test_detrain CARMA model.

2022-01-19 23:54 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_meteor_impact/user_nl_clm
> +
Done.

2022-01-19 23:54 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_meteor_smoke/user_nl_clm
> +
Done.

2022-01-19 23:55 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_test_radiative/user_nl_clm
> +
Done.

2022-01-19 23:55 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_test_tracers2/user_nl_clm
> +
Done.

2022-01-19 23:57 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/outfrq3s_carma/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
Directory cime_config/testdefs/testmods_dirs/cam/outfrq3s_carma is no longer needed so it has been removed.

2022-01-20 00:19 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/shell_commands
> +./xmlchange CAM_CONFIG_OPTS=" -phys cam4 -chem waccm_ma_sulfur -carma mixed_sulfate"
tholin, pmc_sulfate and bc_strat were not included in any of my testing , and aren't in testlist_cam.xml. 
I was never able to get cirrus or cirrus_dust to run; neither it nor cirrus are in testlist_cam.xml.
With the addition of "-rad rrtmg" to CAM_CONFIG_OPTS mixed_sulfate passes the SMS test on cheyenne and on izumi. Adding mixed_sulfate back in to testing.

2022-01-24 19:58 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
From cesm.log.2015979.chadmin1.ib0.cheyenne.ucar.edu.211215-144033 (case ERC_D_Ln9_Vmct.f10_f10_mg37.QPC5.cheyenne_intel.cam-carma_test_detrain.20121215-03):

"ERROR: Attempt to find undefined name in pbuf TND_QSNOW
16:Image              PC                Routine            Line        Source             
16:cesm.exe           000000000558A646  Unknown               Unknown  Unknown
16:cesm.exe           0000000004987062  shr_abort_mod_mp_         114  shr_abort_mod.F90
16:cesm.exe           0000000004986EC8  shr_abort_mod_mp_          61  shr_abort_mod.F90
16:cesm.exe           00000000010377B8  physics_buffer_mp         807  physics_buffer.F90.in
16:cesm.exe           000000000288BFB1  carma_intr_mp_car        1083  carma_intr.F90
16:cesm.exe           00000000011F3419  physpkg_mp_tphysb        2382  physpkg.F90
16:cesm.exe           00000000011CE1D3  physpkg_mp_phys_r        1155  physpkg.F90
16:cesm.exe           0000000000888688  cam_comp_mp_cam_r         258  cam_comp.F90
16:cesm.exe           0000000000846150  atm_comp_mct_mp_a         355  atm_comp_mct.F90
16:cesm.exe           00000000004761F3  component_mod_mp_         257  component_mod.F90
16:cesm.exe           000000000042E947  cime_comp_mod_mp_        2281  cime_comp_mod.F90
16:cesm.exe           000000000046CD0D  MAIN__                    122  cime_driver.F90"

Doing "grep -Hnr TND_QSNOW" from <CAM root>/src produces:
"physics/carma/cam/carma_intr.F90:1083:      call pbuf_get_field(pbuf, pbuf_get_index("TND_QSNOW"), tnd_qsnow)
physics/cam/micro_mg_cam.F90:796:      call pbuf_add_field('TND_QSNOW',  'physpkg',dtype_r8,(/pcols,pver/), tnd_qsnow_idx)
control/cam_snapshot.F90:1716:          'TND_QSNOW              ','unset                  ',&"

2022-02-02 15:17 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam
> +
Problems with mixed_sulfate have been resolved; it now passed the ERS test on both cheyenne and izumi. The file testlist_cam.xml has been updated to reflect this.

2022-02-02 15:18 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cpl
> +reprosum_recompute=.true.
Problems resolved, mixed_sulfate passes ERS test on cheyenne and izumi.

2022-02-02 15:20 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
I have removed the test_detrain sub-directory from <root>/cime_config/testdefs/testmods_dirs/cam.

2022-02-02 15:21 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_test_detrain/user_nl_cam
> +carma_reftfile="camrun.cam.r.carma_reft.nc"
Done.

2022-02-02 15:22 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/shell_commands
> +./xmlchange RUN_STARTDATE="0001-01-01"
Problem is resolved, mixed_sulfate passed the ERS test on cheyenne and izumi.

2022-02-02 18:12 UTC, fvitt approved these changes

2022-02-03 17:55 UTC, gold2718 approved these changes
Okay, looks good now, thanks!
I will get this in the PR pipeline.

2022-02-03 18:16 UTC, cacraigucar approved these changes

2022-02-03 18:16 UTC, cacraigucar commented on cime_config/config_compsets.xml
> +    <lname>2000_CAM40%WCCM_CLM50%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV</lname>
Just an observation - I find it interesting that we are introducing a CAM4 compset as there have been rumblings about trying to phase out older versions of CAM

2022-02-03 18:16 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="carma"/>
As CARMA becomes more mainstream, you might want to consider adding a prealpha or prebeta CARMA test.  This doesn't need to happen now, but is something to keep in mind.  Checking in prealpha or prebeta has the advantage of testing in the CESM checkout while aux_cam tests a CAM checkout.  A single test (probably at prebeta) should be sufficient to make sure that CARMA is functioning in a CESM checkout.

2022-02-03 18:32 UTC, peverwhee approved these changes

2022-02-03 19:46 UTC, nusbaume approved these changes
Looks good to me!  Just one possible clean-up related question.

2022-02-03 19:46 UTC, nusbaume commented on cime_config/testdefs/testmods_dirs/cam/carma_meteor_impact/shell_commands
> +./xmlchange GLC_NCPL=\$ATM_NCPL
Do these `xmlchange` commands need to be here?  It looks like this is an aquaplanet simulation (i.e. ROF and GLC are just stubs).

I have the same question for the "carma_meteor_smoke" and "test_tracers2" `shell_commands` files as well.

2022-02-03 23:27 UTC, manderberg commented on cime_config/testdefs/testmods_dirs/cam/carma_meteor_impact/shell_commands
> +./xmlchange GLC_NCPL=\$ATM_NCPL
I have removed these two lines from the shell_commands file for the carma_meteor_impact, carma_meteor_smoke and carma_test_tracers2 models. The changes have been committed and pushed up to my fork.

2022-02-07 16:44 UTC, gold2718 commented on cime_config/config_compsets.xml
> +    <lname>2000_CAM40%WCCM_CLM50%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV</lname>
Maybe so but both the simpler modeling community and the paleo community view CAM4 as the only stable physics system that is affordable for longer (e.g., millennium) simulations. WACCM can also be expensive so I feel we will be supporting CAM4 longer than CAM3 or CAM5.

2022-02-07 17:53 UTC, fvitt commented on cime_config/config_compsets.xml
> +    <lname>2000_CAM40%WCCM_CLM50%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV</lname>
At least one of the CARMA models needs CAM4 physics which is why we added it.

2022-02-11 03:18 UTC, merged