adding compset for CAM extending 2100-2500 for LE2
ESCOMP/CAM pull request #514
Opened 2022-01-27 16:16 UTC by nanr

LE2-2100extension:  This compset cycles most CAM forcing over year 2100. GHG evolves to 2500. Solar forcing has been extended by MikeMills from 2300 to 2500.  co2flux_fuel_file and aircraft_co2_file files were extended by KLindsay.

2022-02-01 18:41 UTC, cacraigucar requested changes

2022-02-01 18:41 UTC, cacraigucar commented on bld/namelist_files/use_cases/ssp370BBext_cam6.xml
> +	 'H2O    -> $INPUTDATA_ROOT/atm/cam/chem/emis/elev/H2OemissionCH4oxidationx2_3D_L70_1849-2101_CMIP6_HistEnsAvg_SSP3-7.0.002_c20220120.nc',
This data file does not reside in the svn repo, so users will be unable to be run on any machine other than where it currently resides (presumably cheyenne).  I don't know whether this file should be imported into the svn repo or not, but am pointing this out in case it is an issue.  I assume the other data files will also have this same issue

2022-02-02 17:15 UTC, cacraigucar commented on bld/namelist_files/use_cases/ssp370BBext_cam6.xml
> +	 'H2O    -> $INPUTDATA_ROOT/atm/cam/chem/emis/elev/H2OemissionCH4oxidationx2_3D_L70_1849-2101_CMIP6_HistEnsAvg_SSP3-7.0.002_c20220120.nc',
@nanr - Can you please respond back on whether these data files should reside in the svn inputdata repository or not

2022-02-02 18:17 UTC, nanr commented on bld/namelist_files/use_cases/ssp370BBext_cam6.xml
> +	 'H2O    -> $INPUTDATA_ROOT/atm/cam/chem/emis/elev/H2OemissionCH4oxidationx2_3D_L70_1849-2101_CMIP6_HistEnsAvg_SSP3-7.0.002_c20220120.nc',
Hi Cheryl - I have added these data to the SVN repo.  Thank you for pointing this out.  Nan

2022-02-02 20:53 UTC, merged