Bring in Frierson Simple Model
ESCOMP/CAM pull request #537
Opened 2022-03-04 18:21 UTC by cacraigucar

Closes #8

2022-03-04 18:33 UTC, cacraigucar reviewed
I've highlighted the areas which I believe still need to be addressed by @patcal

2022-03-04 18:33 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +  subroutine frierson_convection(ncol,pver,dtime,pmid,pdel,T,qv,relhum,precc)
Question for @patcal

2022-03-04 18:33 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    !--------------------------------
Question for @patcal

2022-03-04 18:33 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +!x        dqsat(i,k) = epsilo*latvap*qsat(i,k)/(rair*T(i,k)**2)  !PFC - check this before deletinig it.
@patcal -  comment to yourself

2022-03-04 18:33 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  !   PFC todo: Eventually change these to namelist options??
@patcal - Should these be namelists options?  I can change them if needed

2022-03-04 18:33 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    ! Set Tsfc() PFC?? Get rid of this!!!
@patcal - comment to yourself

2022-03-04 18:33 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  integer,parameter:: CONVECTION_FRIERSON   = 1  ! PFC todo: **Betts-Miller convection here..
@patcal - comment to yourself

2022-03-04 19:21 UTC, islasimpson commented
Here is a description for the PR.  

"This gray radiation aquaplanet is based on the widely used configuration of Frierson et al (2006) https://doi.org/10.1175/JAS3753.1.  It is a simplified physics configuration in which the radiation scheme is "gray" i.e., radiation is represented by a two-stream approximation with a representation of incoming solar radiation at the surface, which is not attenuated by the atmosphere, and upward and downward radiative fluxes in a single thermal radiation band.  The thermal radiation is only affected by a single longwave absorber, the concentration of which is specified by the user.  The surface is a slab mixed layer and water is prognostic in that it is evaporated from the surface and advected around.  Water condenses and leads to diabatic heating, but it does not affect the radiation scheme and there are no clouds.  This configuration is a step up in complexity from the "dry dynamical core" and the "moist Held-Suarez" configurations which already exist in CESM, with the major difference being the inclusion of a simplified representation of radiation, which allows users to investigate the influence of changes in the radiative properties of the atmosphere on circulation and moisture in a simplified manner."

@patcal - please feel free to modify if you feel that anything is inaccurate or missing.

2022-04-05 02:26 UTC, patcal commented on src/physics/simple/frierson.F90
> +  subroutine frierson_convection(ncol,pver,dtime,pmid,pdel,T,qv,relhum,precc)
No. The plan - long ago - was for this routine was to provide a betts-miller convection option that was going to be added after the initial pull-request. This should stay to maintain the possibility for that to still be done.

2022-04-05 02:32 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +  integer,parameter:: CONVECTION_FRIERSON   = 1  ! PFC todo: **Betts-Miller convection here..
This is related to the duplicate 'convection_NONE' routine above. It should stay in preparation for adding the Betts-Miller convection option after this initial PR.

2022-04-05 02:35 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +  !   PFC todo: Eventually change these to namelist options??
Probably best to wait until alternative schemes have been added before adding namelist options.

2022-04-05 02:36 UTC, patcal commented on src/physics/simple/frierson.F90
> +!x        dqsat(i,k) = epsilo*latvap*qsat(i,k)/(rair*T(i,k)**2)  !PFC - check this before deletinig it.
The commented line can go.

2022-04-05 02:36 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +    !--------------------------------
The comment can go away.

2022-05-09 19:12 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    !--------------------------------
removed

2022-05-09 19:25 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +!x        dqsat(i,k) = epsilo*latvap*qsat(i,k)/(rair*T(i,k)**2)  !PFC - check this before deletinig it.
removed

2022-05-09 19:25 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +  subroutine frierson_convection(ncol,pver,dtime,pmid,pdel,T,qv,relhum,precc)
I believe that we may want to only commit those items which are currently implemented.  @islasimpson and @gold2718 - do you have thoughts on this?

2022-05-09 19:25 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  integer,parameter:: CONVECTION_FRIERSON   = 1  ! PFC todo: **Betts-Miller convection here..
Again a question for @islasimpson and @gold2718 on whether we should just commit what is currently implemented and allow the Betts-Miller code to be brought in at a future date

2022-05-09 19:25 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  !   PFC todo: Eventually change these to namelist options??
removed comment

2022-05-09 19:25 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    ! Set Tsfc() PFC?? Get rid of this!!!
@patcal - What should we do with this comment?  Obviously we don't want to commit code with this comment, so I believe the problem needs to be fixed.  Let me know what you suggest

2022-05-10 01:27 UTC, islasimpson commented on src/physics/simple/frierson.F90
> +  subroutine frierson_convection(ncol,pver,dtime,pmid,pdel,T,qv,relhum,precc)
I'll defer to @gold27118 a I don't know what is appropriate from a software engineering standpoint, but I do think it would be good to have something in there that points to where the appropriate place to put the convection scheme in the future.  Do I understand correctly that this call to the frierson_convection scheme is not actually doing anything?  If so, maybe it can just be commented out with a comment that says something like, "This is how and where a convection scheme can be implemented in the future".  Let me know if I'm totally misunderstanding what the issue is.

2022-06-21 16:43 UTC, gold2718 commented on src/physics/simple/frierson.F90
> +  subroutine frierson_convection(ncol,pver,dtime,pmid,pdel,T,qv,relhum,precc)
@islasimpson, Does Betts-Miller convection need to buried in the Frierson code? I was hoping that Betts-Miller would be a separate scheme that would be generally available. Is that off the mark?

2022-06-21 16:50 UTC, swrneale commented on src/physics/simple/frierson.F90
> +  subroutine frierson_convection(ncol,pver,dtime,pmid,pdel,T,qv,relhum,precc)
@gold2718 I would second this. Betts-Miller is about the simplest scheme that is useful/skillful and yet easy to understand.

2022-07-11 19:27 UTC, nusbaume commented
@cacraigucar Just checking if this PR should still be a draft?

2022-09-16 02:22 UTC, nusbaume requested changes
Looks good, but I do have a bunch of (hopefully) small change requests and a few questions.

2022-09-16 02:22 UTC, nusbaume commented on src/physics/simple/frierson.F90
> +    ! Return Upwad/Downward long wave ratiation at Surface
Typo here (`Upwad` -> `Upward`).

2022-09-16 02:22 UTC, nusbaume commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: Fdown_s (ncol)        !
I might set these `intent(out)` variables to zero in this stub, just to be safe.

2022-09-19 19:36 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The ocean surface is a slab mixed layer with a specified heat capacity.
@patcal - This question is for you

2022-09-19 19:38 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: SST Width of Latitudinal variation.
@patcal - is this degrees North?

2022-09-19 20:05 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +       The ocean surface is a slab mixed layer with a specified heat capacity.
Can we please start using standard units notation (e.g., J K-1)?

2022-09-19 20:06 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: Minimum SST.
Can we please start using standard units notation (e.g., K)?

2022-09-19 20:11 UTC, gold2718 commented on src/physics/simple/frierson_cam.F90
> +    return
IMHO, a well-written subroutine or function should never need any `return` statement at all so I would support a rule that you should not include unnecessary `return` statements, or for that matter, any unnecessary statement (e.g., `implicit none` in a routine when it is already enforced at module scope).

2022-09-20 14:54 UTC, islasimpson commented on bld/namelist_files/namelist_definition.xml
> +       The ocean surface is a slab mixed layer with a specified heat capacity.
I think it may be in J K-1 m-2.  In the paper it's listed as 10^7 J K-1 m-2.  @patcal - do you agree?

2022-09-22 08:21 UTC, peverwhee requested changes
More small things!

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +  use spmd_utils,     only: mpicom, mstrid=>masterprocid, mpi_logical, mpi_real8
mpi_logical isn't used in this module

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +  integer,parameter:: CONDENSATE_USER       = 3  ! Optional user defined Consensation scheme
typo - condensation

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +  ! Some Physics buffer indicies
typo - indices

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +    integer :: istat,lchnk,icol,ncol,ll
I don't think `ll` is used in this routine

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +    use physconst,    only: cpair
this is already imported at the module level

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +    use physconst,    only: cpair
this is already imported at the module level

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +    use physconst,    only: cpair
this is already imported at the module level

2022-09-22 08:21 UTC, peverwhee commented on src/physics/simple/frierson_cam.F90
> +    ! frierson_radiative_tend: Run the radiatvie process
typo - radiative

2022-11-11 20:37 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The ocean surface is a slab mixed layer with a specified heat capacity.
@patcal - Could you confirm the units for this please?

2022-11-11 20:38 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: SST Width of Latitudinal variation.
@patcal - Another units question for you to confirm

2022-12-01 23:19 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       value. For the approximate(simple) solar flux of 1360., the albedo
done

2022-12-01 23:20 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The optial depths are specified as a function of Latitude to approximate
done

2022-12-01 23:20 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The optial depths are specified as a function of Latitude to approximate
done

2022-12-01 23:21 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       water vapor varies according to:
done

2022-12-01 23:22 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: Minimum SST.
added (K)

2022-12-01 23:22 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: Equator-Pole SST difference.
added (K)

2022-12-01 23:23 UTC, cacraigucar commented on cime_config/usermods_dirs/frierson/user_nl_cam
> +  frierson_Twidth     = 26.
Removed and added missing calls to add_default in build-namelist

2022-12-01 23:23 UTC, cacraigucar commented on cime_config/usermods_dirs/frierson/user_nl_cpl
> +orb_mode = "fixed_parameters"
removed

2022-12-01 23:42 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  real(r8),parameter:: frierson_T0     = 273.16_r8     ! Reference Temperature for E0
@patcal - this is the same value as SHR_CONST_TKTRIP.  The comment on that is `triple point of fresh water`.  Is this an appropriate quantity to use?

2022-12-01 23:45 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  real(r8):: frierson_Twidth     = unset_r8      ! IC: width parameter for sst (C)
@patcal - a units question for you

2022-12-01 23:51 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    ! Initialize radition and flux values to 0.0  (Add Init from restart file???)
@patcal - Do we need to init from restart file?

2023-01-10 05:57 UTC, patcal commented on bld/namelist_files/namelist_definition.xml
> +       The ocean surface is a slab mixed layer with a specified heat capacity.
Yes, the units are J K-1 m-2.

2023-01-10 06:11 UTC, patcal commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: SST Width of Latitudinal variation.
No it is a Latitudinal width scale in degrees.

2023-01-10 06:29 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +  real(r8),parameter:: frierson_T0     = 273.16_r8     ! Reference Temperature for E0
The saturation vapor pressure used by Frierson is off a bit, but it is intended to be the value at the triple point temperature 273.16 K.

2023-01-10 06:37 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +  real(r8):: frierson_Twidth     = unset_r8      ! IC: width parameter for sst (C)
Typo, The width is in degrees, so a better comment would be: 
     ! IC: Latitudinal width parameter for sst (degrees)

2023-01-10 06:42 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +    ! Initialize radition and flux values to 0.0  (Add Init from restart file???)
This was intended as a developmental question/reminder as to whether it would be worthwhile to add the ability to initialize values from a restart file here.  The comment can be removed.

2023-01-20 20:26 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The ocean surface is a slab mixed layer with a specified heat capacity.
added

2023-01-20 20:40 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: SST Width of Latitudinal variation.
Added clarification

2023-01-20 20:42 UTC, cacraigucar commented on src/control/cam_control_mod.F90
> +      write(iulog,*) 'Run model with Frierson(2006) physics'
done

2023-01-20 20:44 UTC, cacraigucar commented on src/physics/simple/physpkg.F90
> +    if((Nudge_Model).and.(Nudge_ON)) then
done

2023-01-20 20:45 UTC, cacraigucar commented on src/physics/simple/physpkg.F90
> +       call physics_update(state, ptend, ztodt, tend)
As @nusbaume and I discussed with a different PR, snapshot calls will be added when porting to CCPP (by the developer doing the port), but it is not necessary to add the additional overhead of doing that at this time.

2023-01-20 20:46 UTC, cacraigucar commented on src/physics/simple/physpkg.F90
> +      call physics_update(state, ptend, ztodt, tend)
See above comment about snapshot being deferred

2023-01-20 20:46 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +!          J. Atmos. Sci, Vol 63, 2548-2566.
done

2023-01-20 20:47 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  integer,parameter:: CONDENSATE_TJ16       = 2  ! Consensation from TJ2016 model.
Fixed all places with the typo in this file

2023-01-20 20:50 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  real(r8),parameter:: frierson_T0     = 273.16_r8     ! Reference Temperature for E0
set to SHR_CONST_TKTRIP

2023-01-20 20:51 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  private:: frierson_surface_init
done

2023-01-20 20:51 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  real(r8):: frierson_Albedo     = unset_r8      ! Frierson Albeo
done

2023-01-20 20:54 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  real(r8):: frierson_Twidth     = unset_r8      ! IC: width parameter for sst (C)
done

2023-01-20 21:09 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +          call endrun('frierson_readnl:: ERROR reading namelist')
done

2023-01-20 21:10 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call addfld('Cdrag',horiz_only,'A','n/a'    ,'Surface Drag'                                   )
changed to 1

2023-01-20 21:11 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +        ! phys_state PS values are Inf at this point.... HUH???
removed comment

2023-01-20 21:12 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    ! Initialize radition and flux values to 0.0  (Add Init from restart file???)
removed reminder comment

2023-01-20 21:13 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    real(r8) :: Ke        (state%ncol,pver+1) ! Eddy diffusivity at layer interfaces (m2/s)
changed

2023-01-20 21:16 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    ierr = pio_def_var(File,'Frierson_Qsfc',pio_double, hdimids, Qsurf_desc)
done

2023-01-20 21:18 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call pio_write_darray(File, Qsurf_desc, iodesc, Qsurf, ierr)
done

2023-01-20 21:22 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call pio_read_darray(File, vardesc, iodesc, Qsurf, ierr)
done

2023-01-20 21:22 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +  real(r8),private:: zvir      ! (rh2o/rair) - 1, needed for virtual temperaturr
fixed

2023-01-20 21:29 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    allocate(etamid(size(I_etamid)))
done

2023-01-20 21:29 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Precip_process: Implement NO large-scale consensation/precipitation
done

2023-01-20 21:30 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Set intial total, convective, and large scale precipitation rates to zero
fixed

2023-01-20 21:31 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    do i = 1, ncol
done

2023-01-20 21:31 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    logical,parameter:: do_evap        = .true.
done

2023-01-20 21:48 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +        qdel (:,k) = (qsat(:,k)-qv(:,k))/(1._r8+(latvap/cpair)*dqsat(:,k))
Added variable `latvap_div_cpair` and `latvap_div_rh2o`

2023-01-20 21:50 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Set intial total, convective, and large scale precipitation rates to zero
done

2023-01-20 21:51 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    do i = 1, ncol
done

2023-01-20 21:52 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: Crate
removed

2023-01-20 21:53 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: Crate
removed

2023-01-20 21:54 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Set intial total, convective, and large scale precipitation rates to zero
fixed

2023-01-20 21:54 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    do i = 1, ncol
done

2023-01-20 21:56 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: Ke   (ncol,pver+1)  ! Eddy diffusivity for PBL
added (momentum) at end of comment

2023-01-20 21:56 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: VSE  (ncol,pver)    ! Virtual-Dry Static energy.(huh?)
removed

2023-01-20 22:03 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +      Tv (:,k) = T (:,k)*(1._R8+zvir*Q(:,k))
global replace done

2023-01-20 22:09 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: Tv_srf(ncol)
removed

2023-01-20 22:11 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: za    (ncol)  ! Height at midpoint of the lowest model level (m)
removed

2023-01-20 22:11 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: R_scl (ncol)
removed

2023-01-20 22:11 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: K_coef(ncol)
removed

2023-01-20 22:12 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: E_denom,M_denom,Tnext,Qnext
removed

2023-01-20 22:12 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Calcualte a bulk Richardson number and determine
both fixed

2023-01-20 22:19 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: dVa  (ncol,pver)
done

2023-01-20 22:21 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Return Upwad/Downward long wave ratiation at Surface
done

2023-01-20 22:22 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: Fdown_s (ncol)        !
done

2023-01-20 22:23 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The prescribed fraction of the bounary layer depth
done

2023-01-20 22:24 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    rair   = I_rair
done

2023-01-20 22:24 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: Crate
removed

2023-01-20 22:28 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(in)   :: pdel  (ncol,pver) ! layer thickness (Pa)
I believe @patcal's intention may have been to have all the variations have the same interface.

2023-01-20 22:29 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Precip_process: Implement large-scale consensation/precipitation
fixed

2023-01-20 22:33 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(in)   :: rpdel(ncol,pver)    ! reciprocal of layer thickness (Pa)
@patcal - what are your thoughts on this?  Do I remove it from both this routine and the frierson_pbl_USER routine?

2023-01-20 22:34 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! implicit PBL calculation.  Set all value to 0. for now.
added

2023-01-20 22:35 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! update flux values and dericvatives
fixed

2023-01-20 22:36 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    !                     scheme user in the Frierson model.
fixed

2023-01-20 22:36 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8):: Qr     (ncol,pver)
removed

2023-01-20 22:38 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Calc current Tv values Heights
removed `values` instead of `Heights`

2023-01-20 22:39 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  use spmd_utils,     only: mpicom, mstrid=>masterprocid, mpi_logical, mpi_real8
removed

2023-01-20 22:40 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  integer,parameter:: CONDENSATE_USER       = 3  ! Optional user defined Consensation scheme
done

2023-01-20 22:40 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  ! Some Physics buffer indicies
done

2023-01-20 22:42 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    integer :: istat,lchnk,icol,ncol,ll
removed

2023-01-20 22:42 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    use physconst,    only: cpair
removed

2023-01-20 22:43 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    use physconst,    only: cpair
removed

2023-01-20 22:43 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    use physconst,    only: cpair
removed

2023-01-20 22:43 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    ! frierson_radiative_tend: Run the radiatvie process
removed

2023-01-23 16:23 UTC, fvitt requested changes

2023-01-23 16:23 UTC, fvitt commented on bld/namelist_files/use_cases/dctest_frierson.xml
> +<start_ymd> 10101 </start_ymd>
Does this setting do anything?  You can set `RUN_STARTDATE` in `cime_config/config_compsets.xml`.

2023-01-23 16:23 UTC, fvitt commented on bld/namelist_files/use_cases/dctest_frierson.xml
> +<aqua_planet              >.false. </aqua_planet>
Seems odd to set `aqua_planet = .false.` here.  Shouldn't the compset definition control this?

2023-01-23 16:23 UTC, fvitt commented on src/physics/simple/restart_physics.F90
> +#if ( defined SIMPLE )
Do you need to check the `SIMPLE` cpp def in this file?  If configured with simple_phys then the frierson code is available.

2023-01-23 22:20 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       The Frierson model prescribed a net solar flux which incorporated the
fixed

2023-01-23 22:20 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +       value. For the approximate (simple) solar flux of 1360., the albedo
added

2023-01-23 22:20 UTC, cacraigucar commented on bld/namelist_files/use_cases/dctest_frierson.xml
> +<start_ymd> 10101 </start_ymd>
removed

2023-01-23 22:21 UTC, cacraigucar commented on bld/namelist_files/use_cases/dctest_frierson.xml
> +<aqua_planet              >.false. </aqua_planet>
removed

2023-01-26 16:26 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +       Tsrf Initial Condition: SST Width of Latitudinal variation.
I would at least state that this is `degrees latitude`, simply because both latitude and SST can have units of "degrees", and I would prefer to have as little ambiguity as possible.

2023-01-27 16:31 UTC, nusbaume commented on src/physics/simple/frierson_cam.F90
> +  real(r8) :: frierson_Twidth     = unset_r8      ! IC: Latitudinal width parameter for sst (degrees)
I would specify `degrees` as `degrees latitude`, simply to avoid any ambiguity.

2023-01-27 16:31 UTC, nusbaume commented on src/physics/simple/frierson_cam.F90
> +    return
Added the following line under the "Should" section of our Fortran standards:

> All functions and subroutines should avoid un-necessary statements (e.g. a blank `return` at the end of a subroutine).

That way we have something to point to the next time something like this pops up.

2023-01-27 18:29 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +  real(r8) :: frierson_Twidth     = unset_r8      ! IC: Latitudinal width parameter for sst (degrees)
added latitude to comment

2023-01-27 18:30 UTC, cacraigucar commented on src/physics/simple/restart_physics.F90
> +#if ( defined SIMPLE )
Actually this limitation was not correct.  Fixed throughout this code

2023-01-27 18:44 UTC, fvitt approved these changes

2023-01-27 22:29 UTC, nusbaume commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: Ke   (ncol,pver+1)  ! Eddy diffusivity for PBL (momentum)
I think `Km` should have the `(momentum)` label, not `Ke`.

2023-01-27 22:29 UTC, nusbaume commented on src/physics/simple/frierson.F90
> +    real(r8):: MU (ncol,pver)
Since these are all local variables (so they won't matter for the CCPP), and given that we want this PR in sooner rather than later, I am marking this issue as resolved.

2023-01-27 22:56 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(out)  :: Ke   (ncol,pver+1)  ! Eddy diffusivity for PBL (momentum)
moved momentum label to Km

2023-01-27 23:04 UTC, nusbaume reviewed
Looks good!  Just have this last batch of comments.

2023-01-27 23:10 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! implicit PBL calculation.  Set all value to 0. for now.
done

2023-01-27 23:11 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Calc current Tv Heights
@patcal said he was looking into why he had that logic.  Changed `Heights` to `values`

2023-02-06 22:46 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +          elseif((0._r8 <= ZETA).and.(ZETA < Ri_c)) then
removed `(0._r8 <= ZETA)` check.  Do we need to do anything more?

2023-02-06 22:52 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    ! Calc current Tv Heights
done

2023-02-06 22:52 UTC, cacraigucar commented on src/physics/simple/frierson.F90
> +    real(r8),intent(in)   :: rpdel(ncol,pver)    ! reciprocal of layer thickness (Pa)
removed unnecessary items in calls

2023-02-07 18:09 UTC, nusbaume approved these changes
Everything looks great!  Just one last code cleanup possibility (but am approving now regardless).

2023-02-07 18:09 UTC, nusbaume commented on src/physics/simple/frierson.F90
> +      else
Given that `Ke` is already initialized to zero, I think you can replace this with:

```suggestion
      if(Cdrag(i) /= 0._r8) then

```

2023-02-07 18:13 UTC, peverwhee approved these changes

2023-02-13 22:26 UTC, cacraigucar commented on cime_config/config_compsets.xml
> +    <alias>FFRIERSON</alias>
Change compset name from FFRIERSON to FGRAYRAD.  @islasimpson - Do we want to change the `-phys`  configure option from `frierson` to `grayrad` as well?  How deep do we take this name change?  There are a number of namelist options which are prefixed with `frierson `as well as the name of the modules themselves.  We tend to have the namelist prefix be the same as the module that they refer to, so they will probably need to be consistent (and then we'll probably need to rename the internal routines to match).  Let us know whether we should go beyond renaming the compset.

2023-02-13 22:46 UTC, islasimpson reviewed
I've put suggestions of some key variables that I think need to be output.  Right now it seems like we have addflds for some variables and then they are never output.  We are also missing addfld and outfld calls for some important variables like precipitation and the temperature and moisture tendencies due to large scale condensation.  I put in where I thought they should be but it would be good if @patcal can confirm.  I'm also not sure what's going on with some of these additional sub-routines such as frierson_condensate_TJ16.  I suspect we might want the precipitation and temperature and moisture tendency outfld calls added in there too.  In general I'm confused about all these replicated subroutines with the _USER in there.  But I think it will be important for users to have outputs of the precipitation, the radiative fluxes and the temperature and humidity tendencies whatever namelist settings they set.

2023-02-13 22:46 UTC, islasimpson commented on src/physics/simple/frierson_cam.F90
> +    !---------------------------------
I think we should have an addfld for the diabatic heating due to large scale condensation.  We could call this DTCOND with a description "Temperature tendency due to large scale condensation".  @patcal - do you agree?  I'll point out in frierson.F90 where I think the relevant variable is but it would be good if Patrick agrees since he wrote the code and is, therefore, much more familiar with it.

2023-02-13 22:46 UTC, islasimpson commented on src/physics/simple/frierson_cam.F90
> +    call addfld('VD01',(/'lev' /),'A','kg/kg/s','Q tendency (vertical diffusion)'                 )
We should probably add a q tendency due to large scale condensation too.

2023-02-13 22:46 UTC, islasimpson commented on src/physics/simple/frierson.F90
> +
I suspect that qdel and tdel at this point are probably the specific humidity tendency and temperature tendency due to large scale condensation after accounting for re-evaporation that we could output as the specific humidity tendency due to large scale condensation and reevaporation.  Is this correct @patcal

2023-02-13 22:46 UTC, islasimpson commented on src/physics/simple/frierson.F90
> +    precl(:) = max(precl(:),0._r8)/dtime
I think this will be the variable that we'd want to output for large scale precipitation.   It looks like the units in the addfld should be m/s from the comment on the precl definition.

2023-02-13 22:50 UTC, islasimpson commented on cime_config/config_compsets.xml
> +    <alias>FFRIERSON</alias>
I think it sounds good to change the -phys configure option to grayrad.  I feel less strongly about the namelist options.  It seems ok to me to leave them as having the prefix frierson since I think these are probably variables that are defined in the Frierson et al study.

2023-04-27 23:05 UTC, islasimpson reviewed
I think we might need to have another iteration.  The most significant problem that I see at the moment is that there is something wrong with the downward, upward and net longwave fluxes.  I think we probably need these for both the surface and the top of model and right now there's only one.  But more importantly, the data itself doesn't look right and has a discontinuity at 0 degrees longitude.  A few other things that I haven't mentioned in any specific comments in the code...

(1) For the default output, I'd suggest we scrap any daily defaults.  I think users can decide which variables they want to output at higher frequency by themselves.

(2) For the default output, I think we should remove the following variables PRECC, PRECL, TS, SST as these are all zero and have gray_ equivalents.

(3) For the default output, it would be nice if we could add PTEQ and PTTEND (if they will work in this case)

(4) I'm a little concerned about some potential drifts and the fact that the globally averaged zonal surface wind stress is not closer to zero.  But I think I should run a longer simulation (this is ~10 years)
![Screenshot at 2023-04-27 17-05-19](https://user-images.githubusercontent.com/41842751/235009126-3e0019e8-f07f-4c1f-b66c-115731c36142.png)

2023-05-08 03:10 UTC, islasimpson commented
To follow up on the potential issues of drift that I mentioned above.  I ran a longer run and it seems to be ok.  PS and TS are not drifting.  The non-conservation of angular momentum is smaller than in the first part of the run and I think might be expected based on some other work about an issue with non-conservation of angular moment in the dycore (from Peter https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1002/2013MS000268, Fig 1).

It may be good to have the default initial conditions being from this spun up run.  The restarts are at 

/glade/scratch/islas/archive/FGRAYRAD.002/rest

![testing_frierson](https://user-images.githubusercontent.com/41842751/236725306-2429bf76-bfed-4839-a4e1-9c682229553c.png)

2023-05-08 16:22 UTC, cacraigucar commented
@islasimpson - Could you please add the mandatory metadata to the initial condition file.  Once you've done that, let me know and I'll do the rest of the work (getting it moved into inputdata, hooking it in as the initial condition file, etc.)

2023-05-08 17:14 UTC, islasimpson commented
Added the metadata to the following files...

/glade/scratch/islas/archive/FGRAYRAD.002/rest/0051-02-20-00000/FGRAYRAD.002.cam.i.0051-01-01-00000_withmeta.nc
/glade/scratch/islas/archive/FGRAYRAD.002/rest/0051-02-20-00000/FGRAYRAD.002.cpl.r.0051-02-20-00000_withmeta.nc
/glade/scratch/islas/archive/FGRAYRAD.002/rest/0051-02-20-00000/FGRAYRAD.002.cam.r.0051-02-20-00000_withmeta.nc

2023-05-10 22:38 UTC, cacraigucar commented
> Added the metadata to the following files...
> 
> /glade/scratch/islas/archive/FGRAYRAD.002/rest/0051-02-20-00000/FGRAYRAD.002.cam.i.0051-01-01-00000_withmeta.nc /glade/scratch/islas/archive/FGRAYRAD.002/rest/0051-02-20-00000/FGRAYRAD.002.cpl.r.0051-02-20-00000_withmeta.nc /glade/scratch/islas/archive/FGRAYRAD.002/rest/0051-02-20-00000/FGRAYRAD.002.cam.r.0051-02-20-00000_withmeta.nc

@islasimpson - I need to rename the file.  Does this name work?
`FGRAYRAD_f19.cam.i.0051-01-01-00000_c20230510.nc`

I've included the resolution and today's date and deleted some other information.  Does this name work?

Also, I think I only need the `.i.` file as it will be the ncdata file.

2023-05-10 22:49 UTC, islasimpson commented
> 

Sounds good to me.

2023-05-15 20:26 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +    call addfld('gray_Zm'    ,(/'lev' /),'A','m'      ,'ATM Layer Heights use in PBL'                    )
gray_Zm are the Geopotential heights of the model surfaces needed for PBL calculations.

2023-05-15 20:35 UTC, patcal commented on src/physics/simple/frierson_cam.F90
> +    call addfld('gray_Rf'    ,(/'lev' /),'A','1'      ,'Another Richardson number / Ri_c'                )
There are 2 definitions. The bulk Richardson number defined in equation (15) and 'another' bulk Richardson number defined in equation (16). The gray_Zm corresponds to the second definition in eqn (16) divided by Ri_c. I think what you have suggested is good, just for eqn 16 rather than 15. 

"Bulk Richardson number (Frierson et al 2006, eq 16) / Ri_c"

2023-05-18 20:59 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call addfld('gray_Zm'    ,(/'lev' /),'A','m'      ,'ATM Layer Heights use in PBL'                    )
@islasimpson - Does `Geopotential heights of the model surfaces needed for PBL calculations` address your concern?

2023-05-18 21:02 UTC, islasimpson commented on src/physics/simple/frierson_cam.F90
> +    call addfld('gray_Zm'    ,(/'lev' /),'A','m'      ,'ATM Layer Heights use in PBL'                    )
Maybe, but I'm not totally sure.  @patcal is this any different from the regular geopotential height on model surfaces?  If not, we could just refer to this as "Geopotential height"

2023-05-18 21:11 UTC, patcal commented
Yes, this variable contains a copy of the Geopotential Heights used for the
PBL calculations.
So you are right, it would be best to just call it that.


On Thu, May 18, 2023 at 3:03 PM islasimpson ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/physics/simple/frierson_cam.F90
> <https://github.com/ESCOMP/CAM/pull/537#discussion_r1198301578>:
>
> > +                            frierson_Z0     ,frierson_Ri_c  ,frierson_Karman  ,frierson_Fb      ,  &
> +                            frierson_Rs     ,frierson_DeltaS,frierson_Tau_eqtr,frierson_Tau_pole,  &
> +                            frierson_LinFrac,frierson_Boltz ,frierson_C0                           )
> +
> +    ! Add values for history output
> +    !---------------------------------
> +    call addfld('gray_QRL'   ,(/'lev' /),'A','K/s'    ,'Longwave heating rate for gray atmosphere'       )
> +    call addfld('gray_QRS'   ,(/'lev' /),'A','K/s'    ,'Solar heating rate for gray atmosphere'          )
> +    call addfld('gray_DTCOND',(/'lev' /),'A','K/s'    ,'T tendency - gray atmosphere moist process'      )
> +    call addfld('gray_DQCOND',(/'lev' /),'A','kg/kg/s','Q tendency - gray atmosphere moist process'      )
> +    call addfld('gray_EVAPDT',(/'lev' /),'A','K/s'    ,'T tendency due to re-evaporation'                )
> +    call addfld('gray_EVAPDQ',(/'lev' /),'A','kg/kg/s','Q tendency due to re-evaporation'                )
> +    call addfld('gray_KVH'   ,(/'ilev'/),'A','m2/s'   ,'Vertical diffusion diffusivities (heat/moisture)')
> +    call addfld('gray_KVM'   ,(/'ilev'/),'A','m2/s'   ,'Vertical diffusion diffusivities (momentum)'     )
> +    call addfld('gray_VSE'   ,(/'lev' /),'A','K'      ,'VSE: (Tv + gZ/Cp)'                               )
> +    call addfld('gray_Zm'    ,(/'lev' /),'A','m'      ,'ATM Layer Heights use in PBL'                    )
>
> Maybe, but I'm not totally sure. @patcal <https://github.com/patcal> is
> this any different from the regular geopotential height on model surfaces?
> If not, we could just refer to this as "Geopotential height"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/537#discussion_r1198301578>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJMQHAOJ4TMHGCYS6HRML7TXG2FALANCNFSM5P6HVQVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-18 21:15 UTC, islasimpson commented on src/physics/simple/frierson_cam.F90
> +    call addfld('gray_Zm'    ,(/'lev' /),'A','m'      ,'ATM Layer Heights use in PBL'                    )
Ok, sounds good.  Thanks.

2023-05-18 22:26 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call outfld('gray_LUflux',Fup         , ncol,lchnk)
Changed `Fup `to `Fup(:ncol,lchnk)` in outfld call.  Did the same for Fsolar and the two below.

2023-05-18 22:26 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call outfld('gray_LDflux',Fdown       , ncol,lchnk)
done

2023-05-18 22:26 UTC, cacraigucar commented on src/physics/simple/frierson_cam.F90
> +    call outfld('gray_LWflux',Fnet        , ncol,lchnk)
done

2023-05-27 18:11 UTC, islasimpson reviewed
Surface radiative fluxes look good now.  Added a minor comment about the description of the LW Net Radiative Flux.  It would be good to add in the TOA radiative fluxes as well though.  Here's what the surface radiative fluxes look like now...
![Screenshot from 2023-05-27 12-10-41](https://github.com/ESCOMP/CAM/assets/41842751/95e87851-7e9a-4e62-b7f5-b1e0c8cf91ab)

2023-05-27 18:11 UTC, islasimpson commented on src/physics/simple/frierson_cam.F90
> +    call addfld('gray_LWflux',horiz_only,'I','W/m2'   ,'LW Net Radiative Flux at Surface'                )
Suggest adding ("positive upward") to the description of the LW Net Radiative Flux at Surface.

2023-06-25 02:29 UTC, islasimpson reviewed
I checked the TOA fields and they look reasonable.  I realized that actually we only really need one of them (gray_LUflux_TOA) since the gray_LDflux_TOA is zero all the time and, therefore, gray_LWflux_TOA == gray_LUflux_TOA.  I think it's ok to leave them all in, or to omit them, whatever is easiest.

2023-06-28 23:09 UTC, merged