Katec/new clubb 1121
ESCOMP/CAM pull request #545
Opened 2022-03-18 23:43 UTC by Katetc

Bringing in the new CLUBB External.
Fixes #515 

Fixes #467 , Fixes #461 

Not sure about #429 as that hasn't been tested yet.

2022-03-21 22:56 UTC, gold2718 requested changes
I have a few issues that I think need to be addressed and several questions to answer.
Also, it seems like this version uses a lot more memory and will take more run time. Please include order-of-magnitude changes for performance and memory both in the PR description (at the top of the PR) and in the  ChangeLog (which should be filled out before the next round of reviews).

2022-03-21 22:56 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +                        +(latice)*rcm(i,k))*state1%pdel(i,k)/gravit
Is there a reason for the parentheses around `latice`? Same question below.

2022-03-21 22:56 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +  !!XXgoldyXX: Probably need a hist coord for nnzp for the vertical
Are these comments ever going to be addressed? In the old `addfld` interface (up to cam5_4_05), these fields only had `nnzp` levels (aka `stats_zm%kk`). Using `ilev` was supposed to be a temporary fix. How many extra (useless?) levels are we outputting here for CAM6? For WACCM6? For the CAM7 and  WACCM7 levels?

2022-03-21 22:56 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
>              stats_end_timestep_clubb, &
Are all of these interfaces (including the ones above) used outside of this module? If not, please do not make them `public`.

2022-03-21 22:56 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
Do all of these fields (including above and below) need to be flipped? If all CAM is doing is storing them in a `pbuf` buffer, why bother flipping them (and flipping them back)? I would only flip the fields that CAM uses (e.g., from the state for diagnostics).

2022-03-23 20:53 UTC, adamrher approved these changes
Lots of changes to clubb_intr. I have a bunch of (probably naive) questions. But otherwise I think it's good to go.

In this PR and PR https://github.com/ESCOMP/CAM/pull/546, physpkg is only modified in physics/cam and not physics/cam_dev. How come the F2000dev tests aren't failing?

2022-03-23 20:53 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
so this means all the tau variables are not used by default because ```clubb_l_diag_Lscale_from_tau``` is false. This would make sense based on my understanding of how Vince likes to bring in new externals; don't default the new bells and whistles on. Is that more or less why this is false?

2022-03-23 20:53 UTC, adamrher commented on bld/namelist_files/namelist_definition.xml
> +</entry>
In all these "tau" variables, can we get a description of what they are? A recall Colin saying that these tau values are "alternative" and more intuitive way to change known CLUBB parameters (c7,c8, blah blah), and so it would good to include that information. @zarzycki can you clarify? I remember you saying these tau vars are not adding more complexity, I believe.

I now see a Guo citation in this original tau issue: https://github.com/ESCOMP/CAM/issues/467 ... so maybe we should work together to add descriptions, using that paper.

2022-03-23 20:53 UTC, adamrher commented on bld/build-namelist
>     add_default($nl, 'clubb_l_diag_Lscale_from_tau');
OK I now see that ```clubb_ipdf_call_placement``` is being read in from the clubb_intr readnl subroutine. But I'm not seeing it in the defaults or the definitions. Everything in clubb_intr readnl should be in build-namelist, namelist_definitions and namelist_defaults, right?

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +
I've never seen this outside of physpkg. Can you enlighten me on why we're doing this? Is it to try to get timings for each call to clubb, instead of just the clubb_intr time?

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
what's the extra dimensions for?

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
I think this is possible provided you continue to flip the ones used by other modules. For example, MAM uses up2, vp2, wp2 to get in-cloud turbulent velocity.

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
this fixes issue https://github.com/ESCOMP/CAM/issues/461. Do we need to initialize this in the init subroutine instead? I'm a noob so not sure what's allowed.

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +
Do I have this right that you've refactored clubb_intr to no longer loop the main clubb api driver over ncols? So basically all/most variable now have an extra dimension pcols?

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      if ( pcols == ncol ) then
I'm not following why you can't just index all vars with ```:ncol``` to work for all cases (ncol<pcol or ncol==pcol), like you do for the else case.

2022-03-23 20:53 UTC, adamrher commented on src/physics/cam/physpkg.F90
>            if (is_subcol_on()) then
I guess this needs to be reproduced in cam_dev/physpkg.F90.

This is so annoying to maintain both. I caught the same issue with PR https://github.com/ESCOMP/CAM/pull/546 (and told Francis). How is this not causing a failure for the F2000dev test?

2022-03-28 19:36 UTC, huebleruwm commented on bld/namelist_files/namelist_definition.xml
> +</entry>
The behavior is well defined regardless of how these flags are set, but these flags are definitely confusing and probably could be named better.

2022-03-28 19:46 UTC, huebleruwm commented on src/physics/cam/physpkg.F90
> +             !$acc&     copyout( state_sc%t, state_sc%s, state_sc%omega, state_sc%q )
Initially the plan was to generate the subcolumns on the GPU and keep them there throughout the microphysics and averaging steps so that we never have to copy them at all. That would have to be done here, since we call microphysics after the call to subcol_gen in this procedure. However these plans have been put on hold, so it does seem most appropriate to move this data statement inside of subcol_gen_SILHS.

2022-03-28 19:54 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +                              pdf_params_chnk(:)    ! PDF parameters (thermo. levs.) [units vary]
Before we had 2 dimensions to handle both chunk and columns, but the arrays in our pdf_parameter type now have a dimension to handle columns, making the other dimension unnecessary, so I believe this comment is still accurate.

2022-03-28 19:58 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +                        +(latice)*rcm(i,k))*state1%pdel(i,k)/gravit
Visual clarity is all I can think of. Definitely unnecessary though.

2022-03-28 20:10 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
>              stats_end_timestep_clubb, &
These are actually variables, made public so that they can be accessed by the SILHS code. We know this is not ideal and we have open tickets to fix issues like this and remove the use of global variables. ```stats_rad_zt``` and ```stats_rad_zm``` could be removed though, since it seems silhs does not use them. 

If having public module variables is too big of an issue we could remove them, but it would break some stats functionality when running with silhs until we find a proper way to handle this.

2022-03-28 20:15 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
I don't see any reason that we flip them either. I assumed it was just keep them consistent with the other variables we store in pbuf, but if we don't care about that consistency then we could definitely reduce some computational cost by not flipping them.

2022-03-28 20:21 UTC, huebleruwm commented on bld/build-namelist
>     add_default($nl, 'clubb_l_diag_Lscale_from_tau');
I'm unsure of the standards on this as well, but it would certainly make sense to me to have all namelist variables be defined in all 3 of these files.

2022-03-28 20:48 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +    pdf_zm_mixt_frac_idx
The only reason we save these into pbuf is for restarts, we need to maintain their value each timestep for reproducibility. If this kind of functionality should be handled by an explicit restart interface instead then I suppose the answer is yes, but this does do the job as well.

2022-03-28 20:50 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +
Yes that's basically why. I've been doing a lot of work optimizing code, and with every new checkout I would add these calls around the whole of code in clubb_tend_cam and another just around the large column loop (that no longer exists but the call is still there for before-after measurements), so it felt like it made more sense to just include these. 

It might make sense to remove them for the merge though, since I doubt anyone other than us will be checking them.

2022-03-28 20:51 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
The new pcols dimensions that has been added.

2022-03-28 20:51 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +
Yes exactly.

2022-03-28 20:57 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +      if ( pcols == ncol ) then
The plan in the future is to replace all the pcols declarations in the local variables with ncol, since that way there will be no occasional garbage index. This has been the source of a lot of confusion in the past, so it felt nice to have a bit of code to make the issue clear so that it wouldn't creep up again. You are right though, the else clause is always sufficient.

2022-03-28 21:06 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +      end if
The est_kessler_microphys code was deprecated after adding the ACC flag I believe, so you are correct that it is redundant now. If we were to ever enable it again on CPUs though we would want both checks, so it feels correct to keep it. 

It does seem we should add a silhs specific acc flag though.

2022-03-28 21:16 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +#endif
The lack of a silhs specific compiler flag to enable/disable silhs to run with OpenACC was definitely an oversight. It seems to me that the appropriate way to do this would be to add a compiler flag such as ```SILHS_ACC``` surrounding all our acc statements. That way we can run other code with OpenACC without inadvertently enabling it in silhs. Am I correct in assuming that this is how we should be doing things?

2022-03-28 21:35 UTC, huebleruwm commented on src/physics/cam/physpkg.F90
>            if (is_subcol_on()) then
If we have ```is_subcol_on() = T``` but ```use_subcol_microp = F```, we allocate state_sc but then never deallocate it. The deallocation is done in the use_subcol_microp if statement, but the allocation is done in the is_subcol_on() if statement. It also looks like state_sc, which comes from ```subcol_gen```, is only used when use_subcol_microp is enabled. So the flags set like this would also mean that we are generating subcolumns then not doing anything with them. I don't remember if this causes a crash or not (I don't think it does), but it seems erroneous to have them set like this.

If we have ```is_subcol_on() = F``` but ```use_subcol_microp = T```, we get a crash since the microphyics will try to operate over subcolumns that have not been generated. So this is definitely not allowed.

My guess is that the code was written with grander plans in mind but that they were never followed up on. As it stands, these two flags definitely seem like they should be replaced with one flag.

2022-03-31 15:43 UTC, Katetc commented on Externals_CAM.cfg
> +sparse = ../.clubb_sparse_checkout
I meant to, and then just completely forgot about it in the push to get the PR in before spring break. And easy change to make now.

2022-03-31 15:43 UTC, Katetc commented on Externals_CAM.cfg
> +sparse = ../.silhs_sparse_checkout
Fixed this, thanks for the help!

2022-03-31 15:43 UTC, Katetc commented on src/physics/.clubb_sparse_checkout
> +src/CLUBB_core
Removed

2022-03-31 15:43 UTC, Katetc commented on src/physics/.silhs_sparse_checkout
> +src/SILHS
Removed

2022-03-31 18:03 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +                              pdf_params_chnk(:)    ! PDF parameters (thermo. levs.) [units vary]
Sorry, I was looking at the wrong side. It looks like the *old* comment was not right since it did not document both dimensions.

What I see documented now is that `pdf_params_chnk` is an array over thermodynamics levels. Is that correct?

2022-03-31 18:12 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
>              stats_end_timestep_clubb, &
Sorry, I had the wrong externals checked out when I looked.

2022-03-31 18:20 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +    pdf_zm_mixt_frac_idx
They work but at a (slight) increased cost both in the pbuf infrastructure overhead and in reduced optimization possibilities when using pointers.

2022-03-31 18:23 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +
`t_startf` and `t_stopf` are used in many interface modules as well as in the dycores. I have no problem keeping these.

2022-03-31 18:34 UTC, vlarson commented on bld/namelist_files/namelist_definition.xml
> +</entry>
These parameters are described in [tunable_parameters.in](https://github.com/larson-group/clubb_release/blob/96059a242e69c4e7ed340487ee6b7e4239c33541/input/tunable_parameters/tunable_parameters.in).

2022-03-31 18:49 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +</entry>
@vlarson, thanks, that will be a good source for adding the documentation here as this is the source of CESM documentation of namelist variables.

2022-03-31 19:00 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_c14                              silhs="1" > 0.5     </clubb_c14>
I'm not sure.

2022-03-31 19:05 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
Yes, that's why it's false.  The new tau variables are not needed unless `clubb_l_diag_Lscale_from_tau=T`.

2022-03-31 19:05 UTC, vlarson commented on bld/namelist_files/namelist_definition.xml
> +</entry>
I indicated above where the descriptions can be found in the clubb_release repo.

2022-03-31 23:24 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
OK. On a related note, we've been discussing the sensitivity to this namelist parameter [here](https://github.com/NCAR/amwg_dev/discussions/93#discussioncomment-2480030), and have decided that we'd like to have a new set of clubb tuning values for ```clubb_l_diag_Lscale_from_tau=T```, and that we should start w/ Colin's values in the link. Running this =T w/ our current tuning really messes up the climate, and so this will give us a reasonable climate to begin with if we decide to turn it on, which based on my conversations seems more likely than not. When ```clubb_l_diag_Lscale_from_tau=F```, we want it to fall back to usual clubb tunings ... which will allow us a sort of backward compatibility, because we don't currently run with this=T.

@Katetc is this the appropriate time to implement this? If yes, do you want me to issue a PR to your branch?

2022-03-31 23:32 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
nervermind ... this needs to be initialzied to zero at every time-step like it is done here.

2022-04-01 22:30 UTC, Katetc commented on bld/configure
> +       print $fh "$camsrcdir/src/physics/clubb/src/CLUBB_core\n";
Yes, true. Done

2022-04-01 22:30 UTC, Katetc commented on bld/configure
> +       print $fh "$camsrcdir/src/physics/silhs/src/SILHS\n";
Yes, done.

2022-04-01 22:36 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
I agree that it would be confusing to have some clubb variables correct for the CAM grid in the pbuf and other upside-down. The scout easily lead to problems in development of other parameterizations that might want to use this data in the future. I think consistency is good.

2022-04-01 22:42 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
First, these variables should _not_ be in the pbuf so I do not agree with that part of the argument.
Second, it would be great to get some feedback on avoiding easy cost reductions from the folks who have to try and squeeze long runs into a tight budget.

2022-04-04 18:12 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +</entry>
It might also be useful to add C_invrs_tau_wpxp_N2_thresh to the list of namelist variables.

2022-04-06 16:32 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_C_uu_buoy                                  > 0.3     </clubb_C_uu_buoy>
Hi @Katetc, it looks like C_uu_shr and C_uu_buoy are included twice in this list (see lines 1845-1846 above and the ones above this note). According to tests I've done with this code, it looks like the model runs with the first set (where both equal 0.3), which kind of surprises me since I would've thought later code would overwrite earlier code but I guess I don't know quite how it works. But in any case presumably there should only be one set? I think the second second where the values differ is the more recent one from CLUBB.

2022-04-06 19:21 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_C_uu_buoy                                  > 0.3     </clubb_C_uu_buoy>
@adamrher C_uu_shr and C_uu_buoy (which are really just the old C5 coefficient, now split apart to separately govern shear and buoyant contributions to turbulence) would be used regardless of the value of Lscale.  Colin must have just included C_uu_shr in his tuning process since it was probably relevant to the processes he was looking at.  However, I have been using Colin's value in my own runs with Lscale=T, so his value might work well with the rest of his C_invrs_tau* parameters for example.  I'm not sure how much effect it would have on results if we left it at 0.4 or 0.3.

2022-04-06 19:31 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_C_uu_buoy                                  > 0.3     </clubb_C_uu_buoy>
Yep, C_uu_shr and C_uu_buoy are used in both formulations. For Lscale=F, I'd keep them at 0.4/0.3 (or even set them both equal to the current value of C5 to reproduce our current CAM6 config).

For Lscale=T, @bstephens82 is correct -- I included C_uu_shr in the tuning because Kyle found it important in his simulations for governing the shape of the diffusivity profile in sheared flow. So I'd have a separate C_uu_shr setting right now for Lscale=T.

2022-04-06 19:32 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_C_uu_buoy                                  > 0.3     </clubb_C_uu_buoy>
ok thanks for the explainer. we should then probably have these two default to 0.4/0.3 and then condition then to Colin's values for Lscale=T.

Kate, whenever you finish implementing the namelists (no rush), can you request a re-review from me (and ben)?

2022-04-06 22:36 UTC, vlarson commented
@bmg929, just alerting you to this pull request.

2022-04-07 20:40 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
I have been working on this, and it seems like the only way to implement these namelist dependencies without circular references is to add a new configure option. So, I did that here. To set clubb_l_diag_Lscale_from_tau = true you will need the command 
`./xmlchange --append CAM_CONFIG_OPTS=-clubb_opts Lscale_from_tau`

If you do this, clubb_l_diag_Lscale_from_tau=T and if not it is F. You can still set it to T in the user_nl_cam, but in that case, the other specific namelist changes won't occur. I'm not sure if we want to leave the variable in the namelist with this being the case. But I thought I would send this out to you all for discussion.

2022-04-07 21:12 UTC, adamrher approved these changes
The namelists look correct to me, except the e3sm flag should be true ... Im approving anyways.

To be clear, when Lscale=T, all the old tau terms C1,C2,C4,C6,C8,C14 should be set to 1 when, except:

C4=5.2
C6(a,b)=2
C8 = 3.440377776099962
clubb_c8b =  0.0

And that is indeed the case.

2022-04-07 21:12 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_c6rt                                       > 4.0     </clubb_c6rt>
just commenting that since clubb_C_uu_shr / clubb_C_uu_buoy is a replacement for C5, and the old value of C5=0.3, that setting these to 0.3 for Lscale=T is correct.

2022-04-07 21:12 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_e3sm_config                              > .false. </clubb_l_e3sm_config>
After discussing w/ everyone, we agreed this e3sm flag should default to true. It's only relevant when Lscale=T, and so it should be true always.

2022-04-07 21:16 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
I would vote for removing the namelist, and have the config flag set a private Lscale logical to be passed into the clubb_api. does that make sense?

2022-04-07 21:36 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +</entry>
@bstephens82 , it looks like the index for C_invrs_tau_wpxp_N2_thresh (iC_invrs_tau_wpxp_N2_thresh) is not exposed publicly in clubb_api_module. I could probably hack around it by referencing the parameters_indexes module, but I think that's a bad precedent to set. I'm going to make a note and set issues in the larson-group repos so it will be available for the next time we bring in an update. So, I can't add this namelist parameter right now.

2022-04-07 21:37 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +</entry>
@adamrher I added the descriptions from parameters_tunable.in to the namelist_definitions file.

2022-04-08 10:18 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
> I have been working on this, and it seems like the only way to implement these namelist dependencies without circular references is to add a new configure option. So, I did that here. To set clubb_l_diag_Lscale_from_tau = true you will need the command `./xmlchange --append CAM_CONFIG_OPTS=-clubb_opts Lscale_from_tau`

Is it true that a circular reference is completely unavoidable?  I don't understand how the code works.  It would be convenient to have a way to handle this problem that doesn't require people to remember/know a special way to set one particular CLUBB flag.

@bmg929 is implementing a trap within CLUBB that sets `C1=C6=...=1` when `l_diag_Lscale_from_tau=T`.  NCAR could add a similar (redundant) trap in clubb_intr if it so desires.  

My hope is that `l_diag_Lscale_from_tau=T` can be made to work in time for CAM7.  This option is faster and more parallelizable and more tunable than the default mixing length.  
 
If no elegant solution can be found, could we resort to using CAM6 vs. CAM7 to make the distinction between the values of `C1`, `C6`?  I.e., for CAM6, we could specially set `C1`, `C6`, to their CAM6 values.  For CAM7, we could set them to 1.

> If you do this, clubb_l_diag_Lscale_from_tau=T and if not it is F. You can still set it to T in the user_nl_cam, but in that case, the other specific namelist changes won't occur. I'm not sure if we want to leave the variable in the namelist with this being the case. But I thought I would send this out to you all for discussion.

It's going to be hard for me to remember that one flag is treated differently from all the others.

2022-04-08 18:55 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +</entry>
Updated the documentation for these fields to try to be more clear.

2022-04-08 18:57 UTC, Katetc commented on bld/build-namelist
>     add_default($nl, 'clubb_l_diag_Lscale_from_tau');
clubb_ipdf_call_placement is now a full-fledged namelist option! Yes, it does need to be defined in all 3 files or you can't actually set it in the namelist without an error.

2022-04-08 18:57 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_c14                              silhs="1" > 0.5     </clubb_c14>
Left as is.

2022-04-08 19:05 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
Ok, so, there are probably other ways to prevent a circular reference. The way I have it currently implemented (with a config flag that sets namelist fields) is pretty standard for clubb physics tunings. We could do it all with code in clubb_intr as well, but I think for tuning purposes this is fine. Once the cam7 configure option is created, then we can key off of that instead.

To be clear, this flag is not treated differently from all others. My comment that Vince quoted above is saying that it is also still treated the same. There are not many other namelist options that set other namelist defaults. Most are configure flags and namelist options like I set up here. For instance, micro_mg_version is a config option first and then set as a namelist for the parameterization. You can choose, say, mg3 in configure and then set user_nl_cam to mg1 and you will probably just be ignored.

2022-04-08 19:18 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
How about we leave ```l_diag_Lscale_from_tau``` as a namelist ... and instead of conditioning all those other namelists on a new clubb configure option, we condition them on the exiting ```phys="cam_dev"```  configure option? That is, in order to run w/ lscale=T with the preferred tuning knobs, you have to run cam_dev. Which is fine w/ me because that is the current workhorse configuration. 

This will leave the option of turning on lscale=T even if you're not running cam_dev, but then the onus is on the user to set the all the tuning knobs themselves.

2022-04-08 20:03 UTC, gold2718 commented
> I have been working on this, and it seems like the only way to implement these namelist dependencies without circular references is to add a new configure option.

I agree that the current infrastructure has some limitations here but rather than a configure option, I would move the logic into build-namelist.
Grab the value for the switch variable (`clubb_l_diag_Lscale_from_tau`?) and if it is `True`, then set the default values for the affected variables using the `'val'=>xxx` input to `add_default`). If it is `False`, just call `add_default` without the third argument.

This hides the limitation so that the user interface works as expected.

2022-04-08 22:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +  !!XXgoldyXX: Probably need a hist coord for nnzp for the vertical
Well, I have all kinds of good news here. First is that this code is only called when the clubb_stats are active. So, it doesn't apply to any out-of-the-box configurations of CAM or CESM. If somebody does go through the work of turning on the clubb output stats, then, stats_zm%kk is always set to be the same as ilev. That means there are no wasted levels and no need for another vertical history field.

If you think of "useless" levels as being those above the top of clubb's active levels, then I think that is a much bigger question about history outputs from physics parameterizations. Most (all?) moist convective parameterizations in CAM do not run above the tropopause and so WACCM and high-top models are going to have "wasted" history output levels where there is never going to be data from convection-related parameterizations. If we want to move from having only two vertical dimensions to having multiple vertical dimensions, one for each parameterization so that history files are smaller and there are no wasted levels, then I think you are going to have some frustrated people from the post-processing team. But, again, that's something I think we should decide for all parameterizations, not just CLUBB. And it's probably a bigger discussion than we want have now.

2022-04-08 22:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +  !!XXgoldyXX: Probably need a hist coord for nnzp for the vertical
I'm going to remove these comments as I don't think they apply any more.

2022-04-08 23:01 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_C_uu_buoy                                  > 0.3     </clubb_C_uu_buoy>
I removed the duplicated variables and used the 0.4/0.3 values for default. I don't know if it should be noted, but the second set were 0.3/0.3. So, that's the other option, I guess.

2022-04-08 23:04 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_e3sm_config                              > .false. </clubb_l_e3sm_config>
Set the default for this value to true.

2022-04-11 19:41 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +</entry>
Moved over the documentation from tunable_parameters.in to this file for the website.

2022-04-11 21:51 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +      end if
I changed the _OPENACC in subcol_SILHS.F90 to be SILHS_ACC and I will open an issue with the Larson group about changing the flags inside of SILHS. This does kind of break OPENACC in SIHLS in CAM, but that is a very, very uncommon setup at this point and possibly broken right now anyway. We can wait until the next external update to get this working.

2022-04-11 21:51 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +#endif
I changed the _OPENACC in subcol_SILHS.F90 to be SILHS_ACC and I will open an issue with the Larson group about changing the flags inside of SILHS. This does kind of break OPENACC in SIHLS in CAM, but that is a very, very uncommon setup at this point and possibly broken right now anyway. We can wait until the next external update to get this working.

2022-04-11 21:53 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +#endif
Update, it's SILHS_OPENACC because SILHS_ACC sounds like some kind of alternative to OPEN_ACC and we don't mean that.

2022-04-12 15:19 UTC, gold2718 commented
@sjsprecious, please have a look at the OPENACC items in this PR

2022-04-12 15:54 UTC, sjsprecious commented on src/physics/cam/physpkg.F90
> +             !$acc&     copyout( state_sc%t, state_sc%s, state_sc%omega, state_sc%q )
@gold2718 @huebleruwm I agree that eventually we could generate the subcolumns on the GPU and keep them GPU resident through the microphysics, which may save some data movement time. But the structured data region here ends after the `subcol_gen` subroutine, which means nothing remains on the GPU after it and that is against what you want (unless I have a misunderstanding here). Thus moving the data copy statement into the code that you really work on for GPU offload would be a better solution (In PUMAS case, it will be the micro_pumas_v1.F90).

2022-04-12 15:58 UTC, sjsprecious commented on src/physics/cam/physpkg.F90
> +             !$acc&     copyout( state_sc%t, state_sc%s, state_sc%omega, state_sc%q )
IMO it is fine to put data copy directives inside CLUBB, PUMAS, RRTMGP, etc individually for initial GPU offload. Once the porting is done and we verify the correctness, we could push the data copy directives to the higher-level code like `physpkg.F90` or even `cam_comp.F90` to eliminate some unnecessary data movements, like what is done here.

2022-04-12 16:41 UTC, sjsprecious requested changes
Move the OpenACC data directive as @gold2718 suggests.

2022-04-12 17:07 UTC, sjsprecious commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
Do we need an OpenACC directive here?

2022-04-12 17:07 UTC, sjsprecious commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 2, pverp-top_lev+1
Do we need an OpenACC directive here?

2022-04-12 17:07 UTC, sjsprecious commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
Do we need an OpenACC directive here?

2022-04-12 17:07 UTC, sjsprecious commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
Do we need an OpenACC directive here?

2022-04-12 17:07 UTC, sjsprecious commented on src/physics/cam/subcol_SILHS.F90
> +        call outfld( 'SILHS_THLM_SCOL', THL_lh_out, pcols*psubcols, lchnk )
If any of these variables below are calculated on GPU, I think we need an `acc wait` before calling the `outfld` subroutine. If not, just discard this comment.

2022-04-12 17:14 UTC, sjsprecious commented
Regarding the OpenACC work in this PR, I wonder whether the OpenACC run produces similar climatology as the CPU run, which helps convince me that the GPU offload is done correctly. I usually check it through an ensemble consistency test or an AMWG diagnostic run.

2022-04-13 16:53 UTC, sjsprecious commented on src/physics/cam/subcol_SILHS.F90
> +        call outfld( 'SILHS_THLM_SCOL', THL_lh_out, pcols*psubcols, lchnk )
After a second thought, if any of these variables called in `outfld` are calculated on GPU, we actually need to add `acc end data` before `outfld` to make sure that the data is copied back to the host first.

2022-04-13 21:22 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +      !$acc&     copyin( state, state%zm, state%phis, rho_ds_zt, invs_exner ) &
Yes it all remained bit-for-bit when I added the async clauses. The speedup depends on how much of the GPU the kernels occupy, which depends on the number of GPU cores, columns, subcolumns, and vertical levels. So for example, when we run with something like 8000 subcolumns per grid column, all the kernels use 100% of the GPU during execution so kernels can't run in parallel and the total run time is large enough that the kernel launch latency is negligible, so the only speedup we see is from the asynchronous data copies which I believe was significant if I recall correctly. With small numbers of subcolumns in single column runs though I've observed about a 2x speedup.

2022-04-14 01:37 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +#endif
These are options that aren't generally used, so we didn't consider them worth porting to GPU's and we don't have any plans to at the moment. If we set those to true and run with openacc on in silhs the code would crash, so instead we prevent that with endrun calls to make the error clear. The other option would've been to put acc directives in those sections to copy data back to the host and let the CPU do those sections then copy the data back to device, but that would be very costly and we figured that if someone is running with openacc they don't want experimental code bottle-necking performance.

2022-04-14 01:48 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +    pdf_zm_mixt_frac_idx
An explicit interface for restarts does sound like a good idea in general. Is that something we can set up easily or does that need to be done at a higher level?

2022-04-14 02:06 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
I think having a restart interface does make more sense. Frees up some space in pbuf, and not flipping them won't confuse anyone.

2022-04-14 02:18 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +      !$acc wait
They do, all kernels that rely on async data statements are either in the same stream or use ```wait(stream #)``` for the copy to be complete.

2022-04-14 02:29 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
This option enables the storing of arrays like THL_lh_out, which are large and never even need to be copied off the device, so we don't want to use it with openacc enabled. It is hard coded to be false though, I believe it's only for debugging, but either a statement to update the host with the arrays needed in that section or adding it to the list of options that call endrun at the top would be more robust.

2022-04-14 02:49 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 2, pverp-top_lev+1
No for the same reason mentioned above.

2022-04-14 02:50 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        call outfld( 'SILHS_THLM_SCOL', THL_lh_out, pcols*psubcols, lchnk )
The data saved by these calls never even needs to be copied off the GPU, this section of code is for debugging and l_outfld_subcol is hard coded to false.

2022-04-14 03:08 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
I believe so. I vaguely remember seeing this before and deciding no but I can't find any reason there's no acc statement here. I think this is an error.

2022-04-14 03:13 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
I think so, this is similar to above. ```!$acc parallel loop collapse(3) default(present)``` should be sufficient. I'm confused by this code though since if ```ixrain > 0``` we set ```state_sc%q(num_subcols*(i-1)+j,k,ixrain) ``` but if ```ixsnow = 0``` we will overwrite it with other values. If we cant have both ```ixrain > 0``` and ```ixsnow = 0``` though then it's not an issue, either way I think we do need the OpenACC directive.

2022-04-14 03:14 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do i = 1, ngrdcol
Using subcol_SILHS_constrainmn with openacc is prevented, so no.

2022-04-14 18:47 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
This section only runs if ```subcol_SILHS_q_to_micro = F```, which is mainly for debugging. If we want it to be GPUized then adding ```!$acc parallel loop collapse(3) default(present)``` to the loop in the else clause should be sufficient.

2022-04-14 18:47 UTC, huebleruwm commented on src/physics/cam/subcol_SILHS.F90
> +        do k = 1, pver-top_lev+1
This section only runs if ```subcol_SILHS_n_to_micro = F```, which is mainly for debugging. If we want it to be GPUized then adding ```!$acc parallel loop collapse(3) default(present)``` to the loop in the else clause should be sufficient.

2022-04-14 21:17 UTC, gold2718 commented
@Katetc, I think the "Fixes" items have to be one per line in the PR description, please update it.

2022-04-14 21:55 UTC, Katetc commented on src/physics/cam/physpkg.F90
> +             !$acc&     copyout( state_sc%t, state_sc%s, state_sc%omega, state_sc%q )
Moved these to subcol_SILHS.F90 just before the generate subcolumn call.

2022-04-14 21:55 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +      !$acc&     copyin( state, state%zm, state%phis, rho_ds_zt, invs_exner ) &
Moved the calls to subcol_SILHS.F90 around the subcolumn generation.

2022-04-14 22:21 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_diag_Lscale_from_tau                     > .false. </clubb_l_diag_Lscale_from_tau>
I did manage to get this set up as keyed off just the namelist option after the suggestion from Steve. So, if you set l_diag_Lscale_from_tau=true in the user_nl_cam you get the specified tuning that @adamrher  requested. Note that to change this tuning or add other variables to it, you now need to edit build-namelist rather than namelist-defaults.xml

2022-04-14 22:50 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +      end if
Added an issue in larson-group/cam for this

2022-04-14 22:51 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    pdf_zm_mixt_frac_idx
Added an issue in github.com/larson-group/cam to address this going forward in the future.

2022-04-14 22:51 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        pdf_zm_mixt_frac(i,pverp-k+1)  = pdf_params_zm_chnk(lchnk)%mixt_frac(i,k)
Added an issue in github.com/larson-group/cam to address this in the future.

2022-04-14 22:54 UTC, Katetc commented on bld/build-namelist
>     add_default($nl, 'clubb_l_diag_Lscale_from_tau');
And this is in response to @adamrher 's comment above about cam_dev/physpkg.F90 , I have updated that with these changes. It didn't crash before because the changes are very minimal. Just adding another check for consistent flags and a call to initialize subcolumns correctly, and there's no test for cam_dev with subcolumns active. Which is fine for now.

2022-04-18 19:57 UTC, gold2718 requested changes
Mostly okay but one thing definitely needs fixing.

2022-04-18 19:57 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +    pdf_zm_mixt_frac_idx
> Added an issue in github.com/larson-group/cam to address this going forward in the future.

This is CAM code, not UW code, I think an issue should be opened in ESCOMP/CAM.

2022-04-18 19:57 UTC, gold2718 commented on src/physics/cam/subcol_SILHS.F90
> +        call freeunit(unitn)
Please remove this call (and figure out how it ever compiled).

2022-04-18 19:57 UTC, gold2718 commented on src/physics/cam/subcol_SILHS.F90
> +         open( newunit=unitn, file=trim(nlfile), status='old' )
Okay, mystery time. You are still calling `freeunit` below even though you removed its import statement.
How does this even compile? Please fix this!

2022-04-20 18:16 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_e3sm_config                              > .true.  </clubb_l_e3sm_config>
@zarzycki likes to run with it on, so pinging him. Maybe Colin hasn't seen this crash yet b/c he doesn't run w/ L58 as often as @bstephens82 has (I'm assuming the crash is occurring for L58)?

2022-04-20 18:36 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_e3sm_config                              > .true.  </clubb_l_e3sm_config>
To be honest, I just run this flag set to `true` because @vlarson suggested it when originally setting up CLUBB to mimic Zhun's code.

It appears the only branch for that flag is in mixing_length.F90 below -- this appears to be limited to the damping of scalar variances and scalar fluxes in stable (high N2) layers. I'm not sure why @bstephens82's code is crashing so readily but @adamrher is correct that we haven't done nearly as much stress testing with L58 as L32 so I'm fine setting it to false. We are probably going to want to retune the taus for L58 anyway.

If anything, the E3SM = true branch is a bit more opaque and less generalized...

```
        if ( l_e3sm_config ) then

          invrs_tau_zm = 0.5_core_rknd * invrs_tau_zm

          invrs_tau_xp2_zm = invrs_tau_bkgnd + invrs_tau_sfc + invrs_tau_shear &
                            + C_invrs_tau_N2_xp2 * brunt_freq_pos & ! 0
                            + C_invrs_tau_sfc * 2.0_core_rknd &
                            * sqrt(em) / ( gr%zm - sfc_elevation + z_displace )  ! small

          invrs_tau_xp2_zm = min( max( sqrt( ( ddzt( gr, um)**2 + ddzt(gr, vm)**2 ) &
                            / max( 1.0e-7_core_rknd, brunt_vaisala_freq_sqd_smth ) ), &
                            0.3_core_rknd ), 1.0_core_rknd ) * invrs_tau_xp2_zm

          invrs_tau_wpxp_zm = 2.0_core_rknd * invrs_tau_zm &
                             + C_invrs_tau_N2_wpxp * brunt_freq_out_cloud

        else ! l_e3sm_config = false

          invrs_tau_xp2_zm =  0.1_core_rknd * invrs_tau_bkgnd + invrs_tau_sfc &
                + invrs_tau_shear + C_invrs_tau_N2_xp2 * brunt_freq_pos

          invrs_tau_xp2_zm = merge(0.003_core_rknd, invrs_tau_xp2_zm, &
                zt2zm(gr, ice_supersat_frac) <= 0.01_core_rknd &
                .and. invrs_tau_xp2_zm  >= 0.003_core_rknd)

          invrs_tau_wpxp_zm = invrs_tau_zm + C_invrs_tau_N2_wpxp * brunt_freq_out_cloud

        end if ! l_e3sm_config
```

2022-04-20 18:48 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_e3sm_config                              > .true.  </clubb_l_e3sm_config>
Ill just note that the 2dt wind oscillations in the lowest layers predominantly occurs in stable regions over land (TBOT-TS>0), so this could be a clue since this e3sm flag is only active for stable regions.  

I concur w/ the group that we should default to false for now.

2022-04-21 17:27 UTC, zarzycki commented on bld/namelist_files/namelist_definition.xml
> +
I took a quick scan of this against my sandbox and we don't have `clubb_C_invrs_tau_wpxp_Ri` and `clubb_C_invrs_tau_wpxp_N2_thresh` as nl options in this PR. @vlarson, do you think we should include these as namelist options or keep them in parameters_tunable.F90? FWIW, @kylemnardi has found relatively minimal sensitivity to these two settings in his runs.

2022-04-21 17:55 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    pdf_zm_mixt_frac_idx
Ok, added issue #578 in ESCOMP/CAM

2022-04-21 18:02 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +
We looked at tau_wpxp_N2_thresh earlier in the PR and it's not currently exposed in clubb_api, so I can't add it as a namelist with this PR. I just remembered to add an issue with larson-group/cam so this will be available with the next tag. https://github.com/larson-group/cam/issues/151

2022-04-22 00:43 UTC, zarzycki commented on bld/namelist_files/namelist_definition.xml
> +
Oops, missed that. You're right, I modified the clubb_api to get that to work in my sandbox so I agree with the above.

2022-04-22 01:08 UTC, zarzycki commented
Currently, the OOB config produces a "fatal" error in cesm.log that isn't fatal.

```
38: Invalid configuration: l_min_xp2_from_corr_wx = F and l_enable_relaxed_clipping
38:  = F
38: They must have opposite values
38: Fatal error in setup_clubb_core
```

Relevant to this commit from the CLUBB repo: https://github.com/larson-group/clubb_release/commit/6f037c8025b8131ad603677a418099473fc8239a

Looks like that was commented out at UWM by @vlarson to pass a regression test? Regardless, should we set `l_min_xp2_from_corr_wx` to false by default to avoid that message?

2022-04-22 14:06 UTC, vlarson commented
> Currently, the OOB config produces a "fatal" error in cesm.log that isn't fatal.
> 
> ```
> 38: Invalid configuration: l_min_xp2_from_corr_wx = F and l_enable_relaxed_clipping
> 38:  = F
> 38: They must have opposite values
> 38: Fatal error in setup_clubb_core
> ```
> 
> Relevant to this commit from the CLUBB repo: [larson-group/clubb_release@6f037c8](https://github.com/larson-group/clubb_release/commit/6f037c8025b8131ad603677a418099473fc8239a)
> 
> Looks like that exit call was commented out at UWM by @vlarson to pass a regression test? Regardless, should we set `l_min_xp2_from_corr_wx` to false by default to avoid that message?

That commenting was related to the goal of preserving backwards compatibility.  Going forwards, I recommend setting `l_min_xp2_from_corr_wx = T` and `l_enable_relaxed_clipping = F`.  (I'm assuming that this new setting won't change the answers too much.)

2022-04-22 14:40 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+2) = rtm(i,pver-k+1)
This looks odd to me.  Previously, if `do_expldiff` was .true., then that would tell CLUBB to explicitly diffuse rtm and thlm, by setting l_do_expldiff_rtm_thlm=T, but that code is gone now (see the red-colored version of line 1105 above---and I think the consensus is that it should be gone).  But this block of code still seems to be adding thlm and rtm to the list of passive scalars...should it be doing this anymore?  Ditto for the short `if` statement above in clubb_intr.F90 starting with line 1404...this also keys off of l_do_expldiff_rtm_thlm and is about explicitly diffusing rtm and thlm.  My guess is that these parts of clubb_intr.F90 should be eliminated.  @vlarson?  @adamrher?

2022-04-22 15:18 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+2) = rtm(i,pver-k+1)
I never noticed that, and does raisea  red flag for me too. But I do take comfort that after clubb diffuses ```edsclr_in```, those tendencies are only provided to CAM for an explicit list of tracers that omits thlm and rtm:

https://github.com/Katetc/CAM/blob/f10d173697dd1261d9747be443693c3b97d68fa4/src/physics/cam/clubb_intr.F90#L3778-L3799

But this also raises more questions; why are they recreating an explicit list of species not to diffuse; isn't this list of valid tracers to diffuse done earlier up in the code as well?

2022-04-22 21:04 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+2) = rtm(i,pver-k+1)
I've spent some hours looking into this with the l_do_expldiff_rtm_thlm flag today, and if we are going to have it set to false going forward as seems to be the consensus, then my vote would be to completely get rid of the `clubb_expldiff` namelist variable and `do_expldiff` from clubb_intr.F90, a just have the `if` statements in clubb_intr.F90 that are currently controlled by `do_expldiff` instead be controlled directly by clubb_l_do_expldiff_rtm_thlm.  This is much more transparent as well as economical (why do we have three flags when we could just as easily have one?).  When I grep the entire ESCOMP/CAM repo with externals included, I can't find anything that clubb_expldiff (the namelist variables) or do_expldiff (the clubb_intr.F90 variable set by clubb_expldiff) do that the CLUBB flag couldn't do on its own.

2022-04-22 21:04 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+2) = rtm(i,pver-k+1)
I've spent some hours looking into this with the l_do_expldiff_rtm_thlm flag today, and if we are going to have it set to false going forward as seems to be the consensus, then my vote would be to completely get rid of the `clubb_expldiff` namelist variable and `do_expldiff` from clubb_intr.F90, a just have the `if` statements in clubb_intr.F90 that are currently controlled by `do_expldiff` instead be controlled directly by clubb_l_do_expldiff_rtm_thlm.  This is much more transparent as well as economical (why do we have three flags when we could just as easily have one?).  When I grep the entire ESCOMP/CAM repo with externals included, I can't find anything that clubb_expldiff (the namelist variables) or do_expldiff (the clubb_intr.F90 variable set by clubb_expldiff) do that the CLUBB flag couldn't do on its own.

2022-04-24 18:51 UTC, gold2718 approved these changes
Looks okay to me now.

2022-04-25 15:40 UTC, cacraigucar commented
@bstephens82, @Katetc - Just checking to make sure that as far as you know right now, you don't expect to make any changes other than to address reviewer comments, correct?  That is a criteria to move this into final review.

2022-04-25 16:03 UTC, bstephens82 commented
> @bstephens82, @Katetc - Just checking to make sure that as far as you know right now, you don't expect to make any changes other than to address reviewer comments, correct? That is a criteria to move this into final review.

Correct for me.

2022-04-25 16:24 UTC, Katetc commented
> @bstephens82, @Katetc - Just checking to make sure that as far as you know right now, you don't expect to make any changes other than to address reviewer comments, correct? That is a criteria to move this into final review.

Thanks Cheryl! Is @adamrher finished with his requested changes?

2022-04-25 17:41 UTC, adamrher commented
> Is @adamrher finished with his requested changes?

Yes, on the github side, I think I'm done. We have a couple email threads going around but they should be resolved shortly.

2022-04-26 15:55 UTC, cacraigucar reviewed
First batch of comments

2022-04-26 21:00 UTC, vlarson commented on src/physics/cam/clubb_intr.F90
> +    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
I believe that all these variables need to be saved from timestep to timestep if CLUBB's pdf closure is called after CLUBB's moments are updated.  This positioning of pdf closure is a new option.

2022-04-26 21:15 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
This is a good place to segue our offline email discussion to here @gold2718. I think we need to think a bit deeper on how to handle these pbuf variables if we move the pdf closure to the new post position. At the very least RCM should be advected by the dycore if we want to retain it time-step to time-step, and the pbuf is not the right place for that. I propose:

1. setting all these pbuf vars back to 'physpkg' scope
2. defaulting the ```clubb_ipdf_call_placement``` namelist back to the pre-position (value of 1)
3. open an issue outlining the challenges of moving the pdf call to the post-position

Is this OK people?

2022-04-26 21:35 UTC, vlarson commented on src/physics/cam/clubb_intr.F90
> +    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
Sounds fine to me.

2022-04-26 23:05 UTC, cacraigucar requested changes
Next set of comments.  My review is not complete.

2022-04-26 23:05 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +    wm_zm(1:ncol,:)           = zt2zm_api( pverp+1-top_lev, ncol, gr, wm_zt(1:ncol,:))
These left-hand side arrays should also be initialized to zero.

2022-04-27 01:42 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+2) = rtm(i,pver-k+1)
I've already implemented this within the current PR.  Some changes were already coming in that were going to change the default value of the l_do_expldiff_rtm_thlm flag (which is what we want, but I'm not sure it was does consciously), so I thought it was wise to clean up the code around that flag to make it more clear.

2022-04-27 21:00 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +       allocate(out_zt(pcols,pverp,stats_zt(1)%num_output_fields))
%num_output_fields must be the same for all columns. In the future we plan for the column dimension to be included in the arrays in the stats_ variables, so things like ```stats_zt(1)%num_output_fields``` will become ```stats_zt%num_output_fields```. Refactoring the stats variables will be a significant project though, so we implemented this hacky solution for now, but if %num_output_fields is differing from column to column then there's a bigger problem going on.

2022-04-27 21:04 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +      if ( pcols == ncol ) then
The if statement has been useful for debugging in the past, but has no useful function otherwise. The else clause is always sufficient, you could replace the entire if statement with the call that uses ```:ncol``` to slice the arrays. Commenting it out would make sense too. Future versions will not have the if statement.

2022-04-27 21:11 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +
Previously we had a large column loop around the core clubb code, so advance_clubb_core would act on only one column at a time. We've pushed the column loop into advance_clubb_core now so that we can parallelize/vectorize calculations over the column index. This does indeed require us to have larger arrays now, but ultimately this will improve performance.

2022-04-27 21:13 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +      if ( err_code(1) == clubb_fatal_error ) then
Leaving err_code as an array was an oversight. It should be a scalar as you suggest.

2022-04-27 21:20 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +                                 lmin(i), nu_vert_res_dep(i), err_code(i) )
It certainly wouldn't hurt. If we do trap it with an endrun we would want the following to be immediately after the call to ```setup_parameters_api``` and within the column loop.
```
if ( err_code(i) == clubb_fatal_error ) then
   call endrun(...)
end if
```

2022-04-27 21:33 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +    vm_forcing(:,:) = 0._r8
Purely for performance, but I believe it actually improves robustness. The initialized sections are ```(1:ncol,:)```, which is the only subsection of values we ever want to use. Almost every array is set up similarly, we loop over all vertical levels, but only from 1:ncol columns. Generally, this is actually the entire array, only when ncol<pcols is this a proper subsection, and when that happens we do not ever want to use the "fake" columns. So if you run with debug flags initializing values to Nan and the code crashes because the "fake" columns were used when they shouldn't be, then I'd argue that the part of code using the uninitialized memory is the erroneous section. So by not initializing the sections we don't ever want to use, we ensure that the uninitialized memory tests will detect spots that we are accidentally using those sections.

2022-04-27 21:33 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +    wm_zm(1:ncol,:)           = zt2zm_api( pverp+1-top_lev, ncol, gr, wm_zt(1:ncol,:))
The initialized sections are ```(1:ncol,:)```, which is the only subsection of values we ever want to use. Almost every array is set up similarly, we loop over all vertical levels, but only from 1:ncol columns. Generally, this is actually the entire array, only when ncol<pcols is this a proper subsection, and when that happens we do not ever want to use the "fake" columns. So if you run with debug flags initializing values to Nan and the code crashes because the "fake" columns were used when they shouldn't be, then I'd argue that the part of code using the uninitialized memory is the erroneous section. So by not initializing the sections we don't ever want to use, we ensure that the uninitialized memory tests will detect spots that we are accidentally using those sections.

2022-04-28 17:28 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +                                          ! flag is turned off.
We've had some recent discussions about this as well because I noticed that the way our flags work was very confusing before. All of these flags are contained within a derived type we defined for clubb, ```clubb_config_flags```, and our standard now is that if a flag is modifiable from a host model, then it must be contained in this derived type. If we add a flag to this derived type, it naturally will have to be added to the ```set_default_clubb_config_flags_api``` call as well, and will end up with a well defined default value. 

You are correct that they are declared as ```intent(out)``` by  ```set_default_clubb_config_flags_api```, and that is why I removed the ```.false.``` initialization. I felt that it made it a little more clear that we want ```set_default_clubb_config_flags_api``` to be the only thing setting the defaults before overriding with a namelist. I think we're going to stick with ```intent(out)``` though, since it will help force us to stick to these standards. I don't see any problem with adding the ```.false.``` intialization back in though if it provides some peace of mind.

2022-04-28 17:33 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +    logical :: clubb_cloudtop_cooling, clubb_rainevap_turb
They are included in ```namelist_defaults_cam.xml``` and ```namelist_definition.xml```, but if another layer of robustness is desired then yes I think they should be initialized to ```.false.```.

2022-04-28 17:47 UTC, huebleruwm commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_zt, stats_zm, stats_rad_zt, stats_rad_zm, stats_sfc)
We should be able to remove ```dummy_gr```, ```dummy_nu_vert_res_dep```, and ```dummy_lmin``` completely once those variables are removed from the call to ```setup_clubb_core_api```. We do have an open issue to make this change.

The stats variables are a little more complex though, since they are used by a function needed by silhs. I think it is possible to remove the need for them in silhs though, I'm not positive that they even work properly. We're planning to rework stats at some point and this is on the list of things to address. Removing their thread private requirement would be easier though, I believe all we need to do is allocate them with dimensions ```(pcols,begchunk:endchunk)``` and access them using ```lchnk```. I will add that to our ticket about them.

2022-04-28 21:39 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +                                          ! flag is turned off.
In general, we try and only set a namelist default in one place and the `intent(out)` makes it clear that that place is `set_default_clubb_config_flags_api` so I think we should leave it there and not add other initialization that might fool someone into thinking they can change the default there.

2022-04-28 22:58 UTC, cacraigucar reviewed
Next set of comments

2022-04-28 22:58 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +                                          ! flag is turned off.
Based on the feedback provided, I agree with the reasoning.  I accept this code section as it is.

2022-04-28 23:02 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +    end do
Last I heard, compilers are still producing better code with loops. Anyone have really recent data?

2022-04-29 20:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_zt, stats_zm, stats_rad_zt, stats_rad_zm, stats_sfc)
I have added CAM Issue #584 to make a note of this.

2022-04-29 20:59 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
Adam's issue is here: https://github.com/ESCOMP/CAM/issues/582

2022-04-29 22:01 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    end do
When John Dennis and Jian Sun optimized the PUMAS code for GPUs and improved performance, they changed almost every single array assignment into explicit loops. And there were a lot of them. So, CISL thinks explicit loops perform better. Check out the merge commit: https://github.com/ESCOMP/PUMAS/commit/f49fd869cf5b0b4449c8c12181fcb6e0e07f5717

2022-04-29 22:09 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+2) = rtm(i,pver-k+1)
Ben made these changes.

2022-04-29 22:28 UTC, Katetc commented on src/physics/cam/physpkg.F90
>            if (is_subcol_on()) then
I did move these changes over to the cam_dev physpkg as well.

2022-05-03 00:45 UTC, peverwhee approved these changes
looks good to me; just a couple of typos and a suggestion to add more "Default"s to namelist definitions

2022-05-03 00:45 UTC, peverwhee commented on src/physics/cam/clubb_intr.F90
> +    ! Fix the total energy coming out of CLUBB so it achieves enery conservation.
Typo here: "enery"

2022-05-05 18:26 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    vm_forcing(:,:) = 0._r8
The aux_nag tests look pretty good. There are four failures that I'm looking into today, two of them seem related to subcols. I don't think these forcing arrays are causing any problems.

2022-05-05 18:56 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
FWIW, @kylemnardi has found some improvement on his "cold blob" issues with...

```
clubb_l_min_wp2_from_corr_wx           = .false.    ! atm_in
clubb_l_min_xp2_from_corr_wx           = .false.     ! atm_in
l_enable_relaxed_clipping = .true.    ! in advance_xm_wpxp_module.F90
```

based on some conversations with @vlarson earlier this week. Not necessarily saying that should a default configuration, but I don't really have a good feel for pros/cons to either setup (my gut tells me they only occur in "edge cases" as a "backstop"?)

2022-05-05 19:00 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
Ok yes that was something he recommended to Kyle to try, and if Kyle's finding an improvement then I wonder if Vince might change his mind on that.

2022-05-06 15:57 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
> FWIW, @kylemnardi has found some improvement on his "cold blob" issues with...
> 
> ```
> clubb_l_min_wp2_from_corr_wx           = .false.    ! atm_in
> clubb_l_min_xp2_from_corr_wx           = .false.     ! atm_in
> l_enable_relaxed_clipping = .true.    ! in advance_xm_wpxp_module.F90
> ```
> 
> based on some conversations with @vlarson earlier this week. Not necessarily saying that should a default configuration, but I don't really have a good feel for pros/cons to either setup (my gut tells me they only occur in "edge cases" as a "backstop"?)

If Kyle truly finds a significant improvement with the above flag settings, then NCAR should use those.  Those flag settings are ones UWM used to use.  Brian and I can try to figure out what is wrong with l_min=T and relaxed=F.

2022-05-06 16:02 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
In that case, I would suggest using:

```
clubb_l_min_wp2_from_corr_wx           = .false.    ! atm_in
clubb_l_min_xp2_from_corr_wx           = .false.     ! atm_in
l_enable_relaxed_clipping = .true.    ! in advance_xm_wpxp_module.F90
```

for now. Admittedly, the taus coefficients are going to need to be retuned in a future tag anyways, so we can revisit these flags at that time. I think for now making sure they are consistent (i.e., not both T or not both F) is the most important thing.

2022-05-06 19:38 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
I got some errors from the clubbmf tests on Izumi that clubb_l_min_xp2_from_forr_wx has to be the opposite of l_enable_relaxed_clipping which is set to false and not a namelist variable at this point. Because of this and the requests above, I changed the default to true. I don't know why this requirement exists, and why it only caused an error for clubbmf, but here we are.

2022-05-06 19:42 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
I see that Colin and Vince are suggesting that we stay with false here, but my read of this conversation is that there's not a firm decision for the CAM defaults at this point. Since these values cause two tests to fail, setting them to true will help get the external brought in for now.

2022-05-06 20:01 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
Oooh wait. I totally mis-read Colin's comment there. I see, yes, I'll set l_enable_relaxed_clipping to true in advance_xm_wpxp_module and reset the defaults for the xp_from_corr_wx to false. My bad.

2022-05-06 21:11 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Option for the placement of the call to CLUBB's PDF closure. The optins include: ipdf_pre_advance_fields (1) calls the PDf closure before advancing prognostic fields. ipdf_post_advance_fields (2) cal
Fixed

2022-05-06 21:11 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Defualt: .false.
Done

2022-05-06 21:12 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
>  Flag to use mean theta-v in the calculation of Brunt-Vaisala frequency.
If this is for l_use_thvm_in_bv_freq I added a Default: .false. (which is correct)

2022-05-06 21:12 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
>  grid box.
Fixed

2022-05-06 21:13 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +clubb_up2_sfc_coef increases the values of up2 and vp2 at the surface.
Fixed

2022-05-06 21:13 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
>  in the wp2 (variance of vertical velocity) predictive equation.
Fixed

2022-05-06 21:14 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    ! Fix the total energy coming out of CLUBB so it achieves enery conservation.
Fixed

2022-05-09 18:44 UTC, cacraigucar requested changes
There are still a few changes which need to be made.

Also, once the SE reviews are completed and those changes addressed, are there still any changes coming?  I've been seeing some discussions on namelist settings.  Do those need to be settled for this PR?

2022-05-09 18:44 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +Option for the placement of the call to CLUBB's PDF closure. ipdf_pre_advance_fields (1) calls the PDf closure before advancing prognostic fields. ipdf_post_advance_fields (2, default) calls after ad
This still needs to be done

2022-05-09 18:44 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +       allocate(out_zt(pcols,pverp,stats_zt(1)%num_output_fields))
Will this be part of the changes in #584?  If so, could a note please be added to that issue.  If not, I believe a new issue needs to be opened.

2022-05-09 18:44 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
Resolving this discussion as a new issue has been opened for it

2022-05-10 04:06 UTC, nusbaume requested changes
An impressive amount of work!  I do have some questions and change requests, but hopefully they are all relatively minor.

2022-05-10 04:06 UTC, nusbaume commented on src/physics/cam/subcol_SILHS.F90
> +     type(pdf_parameter):: pdf_params_single_col
I would add a space to the left of the `::` here in order to better match the CAM style guide.

2022-05-10 14:19 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Coefficient in the wp2 (variance of vertical velocity) pressure term.
These are technically pressure terms (some oppose shear production and some oppose buoyant production).  To make it more clear, it could say something like "coefficient in the wp2 pressure terms opposing shear production".

2022-05-10 17:54 UTC, Katetc commented on Externals_CAM.cfg
> -repo_url = https://github.com/ESCOMP/CLUBB_CESM
Yes, that is the plan. This should bring CLUBB development in closer connection to CAM development. It also makes it simpler for where to add issues and see upcoming code changes/development/discussions.

2022-05-10 20:31 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +Coefficient in the wp2 (variance of vertical velocity) pressure term.
@bstephens82 Thanks for the explanation!  I am happy with the phrasing you provided (assuming the `clubb_C_uu_buoy` description is also updated accordingly).

2022-05-11 20:17 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +</entry>
Done

2022-05-11 21:23 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +       allocate(out_zt(pcols,pverp,stats_zt(1)%num_output_fields))
Added it to the #355 issue. A full refactor of stats_ variables would be a UWM job inside the externals, but we could maybe think of a more robust way to allocate these variables.

2022-05-12 19:41 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        zt_g(i,k+1) = state1%zm(i,pver-k+1)-state1%zi(i,pver+1)
I would prefer to leave the indexing for these differences the same as in previous version of this file that have been verified over time (the current indexing). Changing the indexing is just one more spot where uncertainty about solutions could be introduced here. And the usage of pverp versus pver is just a little less clear than pver+1.

2022-05-12 19:42 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +      sfc_elevation(i) = state1%zi(i,pver+1)
I would prefer to leave the indexing for these differences the same as in previous version of this file that have been verified over time (the current indexing). Changing the indexing is just one more spot where uncertainty about solutions could be introduced here. And the usage of pverp versus pver is just a little less clear than pver+1.

2022-05-12 19:48 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        wm_zt(i,k+1) = -1._r8*state1%omega(i,pver-k+1)/(rho_in(i,k+1)*gravit)
I would prefer to leave the indexing for these differences the same as in previous version of this file that have been verified over time (the current indexing). Changing the indexing is just one more spot where uncertainty about solutions could be introduced here. In this case, the lhs k+1 in mirrored in the rhs pver-(k+1) so switching to pverp would reduce the clarity of the calculation.

2022-05-12 19:53 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +          invrs_exner_zt(i,k+1) = inv_exner_clubb(i,pver-k+1)
I would prefer to leave the indexing for these the same as in previous version of this file that have been verified over time (the current indexing). Changing the indexing is just one more spot where uncertainty about solutions could be introduced here. And pver-(k+1) is more clearly mirroring the k+1 in the lhs of the equation.

2022-05-12 19:56 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +          edsclr_in(i,k+1,icnt+1) = thlm(i,pver-k+1)
I would prefer to leave the indexing for these the same as in previous version of this file that have been verified over time (the current indexing). Changing the indexing is just one more spot where uncertainty about solutions could be introduced here. And pver-(k+1) is more clearly mirroring the k+1 in the lhs of the equation.

2022-05-12 20:23 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +Option for the placement of the call to CLUBB's PDF closure. ipdf_pre_advance_fields (1) calls the PDf closure before advancing prognostic fields. ipdf_post_advance_fields (2, default) calls after ad
I see this mod has been made

2022-05-12 21:21 UTC, sjsprecious approved these changes

2022-05-12 21:28 UTC, bstephens82 approved these changes
I made a few additional comments, although whether changes need to be made I'll leave to Kate's judgment.

2022-05-12 21:28 UTC, bstephens82 commented on bld/build-namelist
> +
A minor concern I have about this code, which sets up the parameters when clubb_l_diag_Lscale_from_tau=T, is that this parameter set is the result of tuning with not only clubb_l_diag_Lscale_from_tau=T, but also clubb_l_e3sm_config=T and clubb_l_predict_upwp_vpwp=T  Both of the latter flags are going to be false by default, so if you just turn on the Lscale flag, this actually doesn't give a great-looking climate (the SWCF is too positive), which sort of defeats the purpose of this code block.  I've found that things improve somewhat if we increase the value of clubb_C_invrs_tau_N2_xp2 here, for example values in the range of 0.85 to 1.0 seem to work better (compared to the value here of 0.05).  But I assume further tuning will be done here, so maybe updating the value of C_invrs_tau_N2_xp2 is not necessary at this point.

Another question I had is whether it would be useful to somehow alert the user that turning on the Lscale flag will change these parameters in this way?  I'm not sure how easy it would be to put a line in the atm.log file saying that because that flag is T the parameters are being changed, but this did actually confuse me once or twice after I had forgotten this code was here.

2022-05-12 21:28 UTC, bstephens82 commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> +'um_ndg', 'vm_bt', 'vm_ma', 'vm_gf', 'vm_cf', 'vm_ta', 'vm_f', 'vm_sdmp', 'vm_ndg', 'wp3_bt', 'wp3_ma', 'wp3_ta', 'wp3_tp', 'wp3_ac', 'wp3_bp1', 'wp3_pr_turb', 'wp3_pr_dfsn',
In the new external there is also a new wp2 term, `wp2_pr_dfsn`, which could be added here.  If the corresponding wp3_pr_dfsn term is being added, I was just curious why the wp2_pr_dfsn term is not.

2022-05-12 21:28 UTC, cacraigucar reviewed
In the header, it says this PR might or might not address #429.  Could you please modify the statement so that it is correct?

2022-05-12 22:01 UTC, adamrher commented on bld/build-namelist
> +
Just spoke to ben about this, and he agreed with "perhaps in the interest of finishing this PR, we keep the scope of the PR to just establish the basic logic to condition namelists on lscale=T, and leave it to future task to optimize these to give you a reasonable climate." I think just establishing the logic is important, since we at the very least need to revert many of the C's to 1 when lscale=T, since this flag will specify 1/tau's intead of C's.

I might punt on putting any messages in the atm.log until we get more experience configuring and running the new clubb externals. But I don't have strong feelings either way.

2022-05-12 22:44 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        zi_g(i,k) = state1%zi(i,pverp-k+1)-state1%zi(i,pver+1)
I'd like to keep the indexing on these arrays the same for now. I'm less likely to introduce new errors if I just leave them alone (the same as in previous tags).

2022-05-13 11:51 UTC, vlarson approved these changes

2022-05-13 12:19 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
That's fine (going T/T for `clubb_l_min_xp2_from_corr_wx` and `clubb_l_min_wp2_from_corr_wx`).

We'll check how swapping those flags impacts climate and then update as needed in the CLUBB external (or have it exposed to the namelist API).

2022-05-13 12:20 UTC, zarzycki approved these changes

2022-05-13 19:52 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +              if(diff_mean.gt.0.0_r8) then
This is a bit of smoothing or nudging bit of code that prevents wildly high values of ice from forming. The else clause handles cases where temp_mean is smaller. So, it doesn't need to be abs.

2022-05-13 20:00 UTC, Katetc commented on src/physics/cam/subcol_SILHS.F90
> +               end if
Or maybe the if was off by one? :) Fixed it.

2022-05-16 15:17 UTC, cacraigucar commented
@adamrher, @Katetc and @vlarson - In your opinion does the problem with #429 need to be fixed before this goes into the CAM repot?

2022-05-16 15:26 UTC, vlarson commented
> @adamrher, @Katetc and @vlarson - In your opinion does the problem with #429 need to be fixed before this goes into the CAM repo?

No, it does not need to be fixed for this pull request because most users don't output CLUBB stats, and those that do, can forgo threading.  CLUBB stats with threading have always been broken.

It is a pity that CLUBB stats are still broken, but because the stats are now passed through CLUBB's argument list, at least the problem should be easier to debug.

2022-05-17 04:05 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +        zi_g(i,k) = state1%zi(i,pverp-k+1)-state1%zi(i,pver+1)
Fair enough!  I wasn't sure if it would be simpler to try and remove all of the `+1`s floating around,  but if you feel more comfortable with it as-is then there is no real reason to change it.

2022-05-17 04:30 UTC, nusbaume commented on src/physics/cam/subcol_SILHS.F90
> +              if(diff_mean.gt.0.0_r8) then
Thanks for the explanation  @Katetc!  Looking at the code again that totally makes more sense then how I was first interpreting it.

2022-05-17 04:40 UTC, nusbaume approved these changes
Looks good to me now, thanks!

2022-05-17 18:10 UTC, bstephens82 commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> +'um_ndg', 'vm_bt', 'vm_ma', 'vm_gf', 'vm_cf', 'vm_ta', 'vm_f', 'vm_sdmp', 'vm_ndg', 'wp3_bt', 'wp3_ma', 'wp3_ta', 'wp3_tp', 'wp3_ac', 'wp3_bp1', 'wp3_pr_turb', 'wp3_pr_dfsn',
Just a quick comment on the change that was made here involving wp2_pr_dfsn...would it be clearer if it was added alongside the other wp2_* budget terms in lines 39-40 rather than in line 30?  Obviously a very minor thing.  Second, I was wondering if wp2_pr_dfsn should also be added to the clubb_vars_zm list starting on line 66 (again probably most clearly alongside the other wp2_* terms there).

2022-05-17 19:51 UTC, cacraigucar approved these changes
Last two items:
- Remove the comment about #429, now that @adamrher has determined it still is an issue
- Create a ChangeLog (we can review it when you have it ready, if you would like another set of eyes)

2022-05-17 22:30 UTC, bstephens82 commented on bld/build-namelist
> +
Resolved.

2022-05-18 20:14 UTC, huebleruwm commented
> @huebleruwm - Could you please indicate whether or not you approve this PR as it currently stands? 

I do approve of this pull request

2022-05-20 23:45 UTC, Katetc commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> +'um_ndg', 'vm_bt', 'vm_ma', 'vm_gf', 'vm_cf', 'vm_ta', 'vm_f', 'vm_sdmp', 'vm_ndg', 'wp3_bt', 'wp3_ma', 'wp3_ta', 'wp3_tp', 'wp3_ac', 'wp3_bp1', 'wp3_pr_turb', 'wp3_pr_dfsn',
So, I added wp2_pr_dfsn to the clubb_vars list and build-enamelist started hanging for some reason. If this really should be in the SILHS test, then we can add it in a future PR.

2022-05-20 23:47 UTC, Katetc commented
Just a note, in testing this week, I had problems with two tests on Izumi giving me Nans and Seg Faults due to the changes to address Jesse's review. So, I rolled back the changes that were causing the problems. Unfortunately, I was not able to narrow it down to any specific line of code, because any of the three changes: using rga instead of gravit, multiply by rev_hdtime and adding a stat check to the allocate statements caused the tests to fail. The stat tests really do need to be made for future code compliance, but it was decided that they don't need to go into this particular PR.

2022-05-21 00:00 UTC, bstephens82 commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> +'um_ndg', 'vm_bt', 'vm_ma', 'vm_gf', 'vm_cf', 'vm_ta', 'vm_f', 'vm_sdmp', 'vm_ndg', 'wp3_bt', 'wp3_ma', 'wp3_ta', 'wp3_tp', 'wp3_ac', 'wp3_bp1', 'wp3_pr_turb', 'wp3_pr_dfsn',
Sounds good! Resolved.

2022-05-21 01:30 UTC, merged