Refactor ndrop to use generalized aerosol interfaces
ESCOMP/CAM pull request #546
Opened 2022-03-21 16:04 UTC by fvitt

This modifies ndrop (cloud-aerosol interface) code to use generalized (or abstract) cloud interfaces.  Introduced are abstract aerosol_properties and aerosol_state classes which are extended for concrete modal aerosol classes.  This is the 1st step (of many) to address issue #495 (integrating CARMA trop_strat model into CAM physics).

2022-03-28 05:07 UTC, gold2718 requested changes
I have only looked at the abstract interfaces so far. However, I think it is important to clarify this new interface before diving further into the code.

2022-03-28 05:07 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
I don't think that an abstract interface should be using model-specific interfaces. Perhaps take in an input for a log unit and return an error code instead of calling `endrun`?

2022-04-05 19:49 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +    real(r8),intent(in) :: alogsig(nbin)      ! ??? some log factor of each bin ???
log of the standard deviation (sigma) of the aerosol mode

2022-04-05 19:54 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       real(r8), optional, intent(out) :: hygro   ! hygroscopicity
@bardeenc @drmikemills 
Does hygroscopicity have units?

2022-04-05 19:55 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8), allocatable :: f2_(:)
Should maybe document the data members.

2022-04-05 20:01 UTC, fvitt commented on src/physics/cam/ndrop.F90
> +            amcube(:ncol)=aero_props%amcubecoef(m)*vaerosol(:ncol)/naerosol(:ncol)
maybe just use aero_props%amcube function directly

2022-04-07 19:40 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8), allocatable :: f2_(:)
Please note some of these variables have already been defined further down in the code.
!! The abstract aerosol interface allows aerosol representations that define a specific number of bins/modes (nbins). Each of the bins/modes consists of a specific number of species (nspecies) that are assumed to be internally mixed. Therefore each bin/number has a total aerosol number and total mass. Specific aerosol descriptions may not require to define/present total mass. The code allows either option.

nbin !! number of bins or modes   
ncnst_tot !! total number of bin/mode number, total mass, and number of species
ncnst_extd !! twice the total number of bin/mode number, bin total mass, and concentration species (not yet included)
nmasses !!  number of species per bin/mode plus 1 to consider the total mass (if available)
indexer !!  table for local indexing of bin/mode aero number and mmr. This table uses species index 0 for the number conc.

2022-04-07 19:42 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +
Add comment:
! Local indexing compresses the mode and number/mass indices into one index.
   ! This indexing is used by the pointer arrays used to reference state and pbuf
   ! fields. We add number = 0, total mass = 1 (if available), and mass from each constituency into mm.

2022-04-08 15:11 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8), allocatable :: f2_(:)
amcubecoefs may be removed here and just used in the rcubed (amcube) routine.

2022-04-08 15:11 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
I added some summary above to address this.

2022-04-08 17:08 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
nmassesa and nmassesv are not intuitive names to me. In the code it says:
nmassesa. ! number of species masses for all bins.    -> However, I do not see it being used anywhere?
nmassesv. ! number of species masses in a given bin number. -> again I don't see it used in the code at the moment. Will it be used in a different code (that is not added yet)?

2022-04-08 17:10 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +    real(r8),intent(in) :: alogsig(nbin)      ! ??? some log factor of each bin ???
Definitions here or on the top of the program or both? Should be consistent.

2022-04-08 17:18 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  ! returns coefficient factor for radius^3 calc
Instead of this function, I think, we can just have 1 function that returns rcubed and include the coefficient there.

2022-04-08 17:31 UTC, tilmes commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    call rad_cnst_get_info(0, nmodes=nmodes)
@gold2718  Can we assume for now that it works with rad_cnst?

2022-04-08 17:34 UTC, tilmes commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    amcube = (3._r8*volconc/(4._r8*pi*self%exp45logsig_(bin_ndx)*numconc))
Are we calculating amcube here or in aerosol_properties_mod.F90?  I am thinking, if you define the coefficient for the calculation, you can do it in aerosol_properties_mod, if you do it here, you want to also do the same for CARMA (not in here) and you could remove the coefficient.

2022-04-08 17:58 UTC, tilmes commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
This is aerosol model specific (MAM) and it does not seem to be needed?

2022-04-08 18:01 UTC, tilmes commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
line 686ff: this is also aerosol specific

2022-04-11 20:25 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  end function amcubecoef
Is `amcubecoef()` ever used other than for calculating r^3 for a given number and volume? If not, consider merging this function with `amcube()` and possibly making it `deferred` so that each aerosol model can calculate r^3 based on its representation

2022-04-11 20:26 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  end function amcubecoef
I was thinking the same, but the r^3 calculation needs volume and number and that would have to be passed to the r^3 calculation, maybe doing it like Francis suggesting is actually not a bad idea?

2022-04-11 20:41 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       real(r8), optional, intent(out) :: hygro   ! hygroscopicity
Would it make sense to have this be two functions `aero_props_get_density` and `aero_props_get_hygroscopicity`? Both outputs are already optional, and the separate functions' names would be more clear.

2022-04-11 21:15 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
I would suggest consistently using (or not) the `get_` prefix here:
```
     (...)
     procedure :: get_amcube
     procedure :: get_alogsig
     procedure(aero_props), deferred :: get_props
     procedure(aero_act_fracs), deferred :: get_act_fracs
     procedure(aero_num_names), deferred :: get_num_names
     procedure(aero_mmr_names), deferred :: get_mmr_names
```
or
```
     (...)
     procedure :: amcube
     procedure :: alogsig
     procedure(aero_props), deferred :: props
     procedure(aero_act_fracs), deferred :: act_fracs
     procedure(aero_num_names), deferred :: num_names
     procedure(aero_mmr_names), deferred :: mmr_names
```
One argument for the latter is that it's shorter and you're already using a trailing underscore for data member names, which will prevent naming conflicts with accessor functions.

2022-04-11 21:53 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     subroutine aero_actfracs(self, bin_ndx, smc, smax, fn, fm )
I think we discussed leaving the original names of functions and their arguments for now to help people familiar with the old names navigate the refactoring, but proposing new names in the comments. Here is one:
```
! proposed new name: aero_activation_fractions
```

2022-04-11 21:57 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     end subroutine aero_mmr_names
Is it likely that these will be unneeded once the CAM dependencies are removed from the aerosol code? If not, some description of what these names are used for could be included function descriptions

2022-04-11 22:22 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
@gold2718 - I don't disagree with your proposal, but I thought we decided that in the first wave of refactoring the CAM dependencies would be left in place, and that these would be addressed in the second wave of refactoring. Is this correct?

2022-04-11 22:32 UTC, gold2718 commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    call rad_cnst_get_info(0, nmodes=nmodes)
The whole point of the new interfaces is to provide a stable interface to CAM which allows the underlying implementation to evolve and change without affecting the CAM implementation. This code is grabbing data from inside of CAM rather than through its interface which makes it non-modular (i.e., it does not meet the purpose of the new interfaces).

2022-04-11 22:38 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
I'm not sure. My understanding is that we would continue to use elements of the CAM implementation for now but present interfaces that would not need to change when the implementation was made independent of CAM. In particular, this one seems like an easy add and one that is necessary for modular code.

2022-04-11 22:57 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  type, abstract :: aerosol_state
I think it would be helpful to include descriptions of `aerosol_state` and `aerosol_propoerties` that describe the conceptual differences between the two so that someone adding a new aerosol model can make the right choices about where to include specific data members

2022-04-12 14:12 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
@tilmes 
Search for `aero_props%nmasses` in `ndrop.F90`.  The `nmasses` procedure is overloaded (see the `generic` keyword) so that it can return either a single value for a given bin number or an array of values for all bins.

2022-04-12 14:35 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    call rad_cnst_get_info(0, nmodes=nmodes)
I think @gold2718 has his sights set on the end goal of having aerosol object code that is completely independent of CAM which is where we all want to end up.  Another goal is to develop an interface that works for both MAM and CARMA so that we can easily incorporate CARMA into the CAM physics parameterizations.  For the time being, we are using the rad_cnst interfaces to get information and state of the aerosols.  It may take a while to develop aerosol classes that are completely independent of CAM.

2022-04-12 14:37 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
I agree that `endrun` and `iulog` could be easily replaced at this point.  The `rad_cnst_get` interfaces are more difficult.

2022-04-12 14:41 UTC, fvitt commented on src/physics/cam/ndrop.F90
> +            amcube(:ncol)=aero_props%amcubecoef(m)*vaerosol(:ncol)/naerosol(:ncol)
This change causes the MAM baseline tests for fail due the roundoff differences in the CCN diagnostics.  This makes it a little tricky to verify that I have not changed MAM results.

2022-04-12 14:45 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  end function amcubecoef
I agree with these suggestions.  Note, these changes to amcube do cause roundoff differences in the CCN diagnostics of MAM.

2022-04-12 18:01 UTC, gold2718 commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    call rad_cnst_get_info(0, nmodes=nmodes)
I think I have misunderstood some of this. @fvitt, is it true that the `rad_cnst_get_info` uses only constituent information and nothing from the CAM state? If so, then this is a valid use. My real concern here is management of state and tendency information between the host model and the aerosol code.

2022-04-12 20:00 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  type, abstract :: aerosol_properties
please add comment:
```
!> aerosol_properties defines the configuration of any aerosol package (using any aerosol representation)
!! based on user specification. These values are set during initialization and do not vary during the simulation.
!!
!! Each aerosol package (e.g., MAM, CARMA, etc) must extend the aerosol_properties class to define the
!! details of their configuration. Any package must implement each of the deferred procedures of the abstract
!! aerosol_properties class, may include additional private data members and type-bound procedures, and may
!! override functions of the abstract class.
!!
!! Please see the modal_aerosol_properties module for an example of how the aerosol_properties class can
!! be extended for a specific aerosol package.
```

2022-04-12 20:26 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  type, abstract :: aerosol_state
please add comment:
```
!> aerosol_state defines the interface to the time-varying aerosol state variables (e.g., mixing ratios, number
!! concentrations). This includes the aerosol portion of the overall model state.
!!
!! Each aerosol package (e.g., MAM, CARMA, etc) must extend the aerosol_state class to allow access to
!! the state information (transported and not transported) of the aerosol package.
!! Any package must implement each of the deferred procedures of the abstract
!! aerosol_state class, may include additional private data members and type-bound procedures, and may
!! override functions of the abstract class.
!!
!! Please see the modal_aerosol_state module for an example of how the aerosol_state class can
!! be extended for a specific aerosol package.
```

2022-04-12 20:33 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  pure function nmassesv(self,bin_ndx) result(val)
suggest naming function: `n_masses_per_bin`

2022-04-12 20:34 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  pure function nmassesa(self) result(arr)
suggest naming function: `n_masses_all_bins`

2022-04-12 20:48 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  pure real(r8) function amcube(self, bin_ndx, volconc, numconc)
Consider moving this to `aerosol_state`

2022-05-10 17:37 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +    real(r8),intent(in) :: alogsig(nbin)      ! ??? some log factor of each bin ???
I have made the suggested change here

2022-05-10 17:40 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +
Added these comments.

2022-05-10 17:42 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    amcube = (3._r8*volconc/(4._r8*pi*self%exp45logsig_(bin_ndx)*numconc))
I removed the coefficients

2022-05-10 17:43 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  end function amcubecoef
done

2022-05-10 17:44 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
I wen with the 2nd option here

2022-05-10 17:46 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  type, abstract :: aerosol_state
Added this

2022-05-10 17:46 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  type, abstract :: aerosol_properties
Added

2022-05-10 17:46 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  pure function nmassesv(self,bin_ndx) result(val)
done

2022-05-10 17:47 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  pure function nmassesa(self) result(arr)
done

2022-05-10 19:39 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       real(r8), optional, intent(out) :: hygro   ! hygroscopicity
hygro does not have units

2022-05-10 20:57 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  type, abstract :: aerosol_properties
Good with me

2022-05-10 21:00 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +
looks good to me

2022-05-12 16:10 UTC, cacraigucar reviewed
My first round of questions/comments

2022-05-13 14:14 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8), allocatable :: f2_(:)
Hi @cacraigucar - I would say yes on both counts. I'm not sure about Fortran, but trailing underscores I think are fairly commonly used in other languages for data members (e.g., [here](https://google.github.io/styleguide/cppguide.html#Variable_Names)) and to prevent naming conflicts (e.g., [here](https://pep8.org/#naming-conventions)). I've found trailing underscores for private data members useful in Fortran for the reason you mentioned - you can have accessor functions with the data member name w/o the underscore (but I haven't seen anyone else specifically recommend it for Fortran).

2022-05-13 15:11 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +
This just defines the interface.  The extending concrete classes must implement the method.  See the implementation of `amcube` in `modal_aerosol_properties_mod.F90`.

2022-05-13 15:14 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    end select
This is a common routine used by both MAM and CARMA.  This particular block of code is executed only for MAM.

2022-05-13 15:17 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +    call microp_aero_final()
@cacraigucar : I can add the call to `cam_dev/physpkg`.  What are the regression tests that exercise `cam_dev/physpkg`?

2022-06-07 22:46 UTC, cacraigucar reviewed
Next round of comments/questions

2022-06-07 22:46 UTC, cacraigucar commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +          call endrun('phase error in loadaer')
Would it be useful to have this say loadaer1 instead of the generic loadaer?

2022-06-07 22:46 UTC, cacraigucar commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       import
I would suggest that `import` follow the same conventions as `use` and the fields being imported be explicitly listed

2022-06-07 22:46 UTC, cacraigucar commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_props_get), deferred :: get
`get` seems a little simplified to me for a name - it made me ask "get what"?  Should it be `get_props` at the minimum?

2022-06-09 21:12 UTC, peverwhee approved these changes
a few suggestions/comments

2022-06-09 21:12 UTC, peverwhee commented on src/physics/cam/microp_aero.F90
> +      allocate(factnum(pcols,pver,aero_props_obj%nbins()))
add stat check?

2022-06-13 21:22 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       import
Do you prefer `import :: aerosol_properties, r8`?  I would like to see the opinions of others on this.

2022-06-13 23:36 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    end select
Perhaps this code block could be replaced with a call to a limiter function that can be overridden in the modal_aerosol_properties class.

2022-06-21 21:01 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       import
Yes, it is always valuable to know what is being imported.

2022-06-24 23:11 UTC, gold2718 requested changes
A few things to change and a few older questions that have not yet been answered.

2022-06-24 23:11 UTC, gold2718 commented on src/physics/cam/ndrop.F90
> +         where(naerosol(:ncol)>1.e-3_r8 .and. hygro(:ncol).gt.1.e-10_r8)
Weird mix of old style and new (with the new code using the old syntax). Can you use `>` for both terms?

2022-06-24 23:11 UTC, gold2718 commented on src/physics/cam/ndrop.F90
> +               ccn(i,k,l)=ccn(i,k,l)+naerosol(i)*0.5_r8*(1._r8-erf(arg(i))) ! looks like activation frac fn (arg is a little diff) ??
These comments do not give me the warm fuzzies (especially the comment on the comment). Can you clarify a bit? What is "a little diff"?

2022-06-24 23:11 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     procedure :: set_transported
These calls need to be put into the code so that it would run correctly if the objects really had a copy of the transported data (instead of a pointer to the CAM state).

2022-06-27 18:43 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       import
done

2022-06-27 18:43 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    deallocate(self%voltonumbhi_)
Added checks

2022-06-27 18:44 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +       nmasses(m) = nspecies(m)
Did away with the redundant nmasses here.

2022-06-27 18:45 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  ! Ojbect clean
fixed

2022-06-27 22:42 UTC, nusbaume approved these changes
I have some small requests, but nothing that should really hold up this PR (assuming other people's requests are resolved).  Thus I'm happy to approve it now.

2022-06-28 12:29 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +    call microp_aero_final()
Done

2022-06-28 12:32 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    end select
This block is replaced with a generic limiter routine (aerosol model independent).

2022-06-28 13:50 UTC, fvitt commented on src/physics/cam/ndrop.F90
> +real(r8), parameter :: t0       = 273._r8
This is slightly different (SHR_CONST_TKFRZ = 273.15).

2022-06-28 15:23 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +            (dgnumhi**3._r8)*exp(4.5_r8*alogsig(m)**2._r8) )
I could make this change. However, this would introduce roundoff differences.

2022-06-28 16:11 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  end function n_masses_per_bin
This matches `n_masses_all_bins` which returns an array.

2022-06-28 18:56 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_props_get), deferred :: get
type-bound procedures are always called on an object, so as long as it's clear from the type what is being "got", I would argue that this:
```
  type(properties_t) :: my_properties
  real :: foo  
  foo = my_properties%get( "foo" )
```
is preferable to this:
```
  type(properties_t) :: my_properties
  real :: foo
  foo = my_properties%get_property( "foo" )
```

2022-06-28 19:15 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    use modal_aerosol_properties_mod, only: modal_aerosol_properties
removed the use statement here

2022-06-29 02:11 UTC, nusbaume commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +            (dgnumhi**3._r8)*exp(4.5_r8*alogsig(m)**2._r8) )
Right, good point! If some other change produces round-off differences then it would be great to bring this in as well, but otherwise I am happy if you want to maintain bit-for-bit output for this PR.

2022-06-29 02:25 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  end function n_masses_per_bin
Fair enough.  At first I was thinking it should match the previous functions given that it returns a single integer value like they do, but I can also see how it would be better to have it match `n_masses_all_bins` given that they return related physical quantities.  I'll go ahead and mark this particular request as resolved.

2022-06-29 19:18 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_properties_mod.F90
>      allocate( self%indexer_(nbin,0:maxval(nmasses)) )
It looks like this `allocate` statement is missing the actual `stat` output (but does have the `if ( ierr /= 0)` check).

2022-06-29 20:40 UTC, fvitt commented on src/physics/cam/ndrop.F90
> +         where(naerosol(:ncol)>1.e-3_r8 .and. hygro(:ncol).gt.1.e-10_r8)
fixed

2022-06-29 20:41 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_state_mod.F90
> +    integer :: m,mm,l
fixed

2022-06-29 20:43 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    allocate(newobj%voltonumbhi_(nmodes))
added status checks

2022-06-30 13:21 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +      allocate(factnum(pcols,pver,aero_props_obj%nbins()))
done

2022-06-30 13:23 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     integer, allocatable :: nmasses_(:)
added comments

2022-06-30 14:21 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     end subroutine aero_props_get
Comments have been added to document the interfaces.   More meaningful names are used for the arguments.

2022-06-30 14:23 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8), allocatable :: f2_(:)
comments have been added

2022-06-30 14:27 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     end subroutine aero_mmr_names
These are used to provide names for cam history output fields.

2022-06-30 17:47 UTC, gold2718 commented on src/physics/cam/ndrop.F90
> +real(r8), parameter :: t0       = 273._r8
Right. The question is whether that is the correct value. If it is, then what scientific constant is it? It would be great to have some idea of what these quantities are. `t0` seems to be used in equations as the difference between Kelvin and Celsius and 273 is not the correct conversion factor.
What is `surften`? Is it surface tension of water? Newtons / meter? Is it at a particular temperature?

2022-07-01 15:20 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
I agree with @fvitt's point. The `rad_cnst_get` interfaces are the main target of what I expected to be dealt with in the next phase.

2022-07-01 16:17 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     procedure :: set_transported
1. `get` and `set` are pretty vague words. While the OO community uses these terms fairly consistently, how about some help for the scientists that have to use and read this code later on? Please add some documentation.
2. Why aren't these abstract interfaces? Wouldn't each aerosol model have their own implementation of each of these?
3. I just want to note that while these interfaces provide the data for transport, they provide no  information (e.g., wet / dry, MW, name) that are used for transport and/or diagnostics. This interface will need to be added later.
4. Here are my notes about adding the calls:

`number_transported`: We will add the interface for this later when after the CAM thermo rewrite is done.

`get_transported`: A call needs to be added _just before_ each call to `p_d_coupling` 

`set_transported`: A call needs to be added _just after_ each call to `d_p_coupling`

2022-07-05 20:36 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
@tilmes dgnumwet is still used in microp_aero and yes this is MAM specific

2022-07-05 20:49 UTC, tilmes commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
@fvitt dgnumwet seems to be used to calculate rndst(i,k,3) = 0.5_r8*dgnumwet(i,k,mode_coarse_dst_idx)
What is rndst used for?  I may have thought, we only need it for BAM, but that may not be true.

2022-07-05 21:21 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
@tilmes RNDST is used in pumas.

2022-07-05 21:30 UTC, tilmes commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
@fvitt If only used in pumas, why isn't it provided from the aerosol model (as dust radius) directly?

2022-07-06 21:38 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +    real(r8),intent(in) :: f2(nbin)           ! abdul-razzak functions of width
Tried to improve the comments on f1 and f2

2022-07-06 21:42 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +          smax=1.e-20_r8
These are now parameters and tried to document the best I can.

2022-07-06 21:51 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +   class(aerosol_state), pointer :: aero_state_obj
Initializing the aero_state to null() at the subroutine caused threading issues when compiled with gnu.

2022-07-06 21:51 UTC, fvitt commented on src/physics/cam/zm_microphysics.F90
> +type(modal_aerosol_properties), pointer :: aero_props_obj
I have initialized the aero_props objects at the module level to null().

2022-07-06 22:25 UTC, gold2718 commented on src/physics/cam/microp_aero.F90
> +   class(aerosol_state), pointer :: aero_state_obj
It is true that one should (almost) never add initial values (including `null()`) to declarations in threaded code (it causes the `save` attribute to be set which is almost never what you want, even in non-threaded code).
The correct way to implement this behavior (IMHO) is to use the `nullify` statement(s) before other executable statements. In this case, that would be on line 480:
```
nullify(aero_state_obj)
```

2022-07-06 22:28 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  pure real(r8) function amcube(self, bin_ndx, volconc, numconc)
The modal aerosol model implementation of this function depends on `exp45logsig` property which is unique to the modal representation.  It is more convenient to leave `amcube` in `aerosol_properties` since `exp45logsig` is incapsulated in `modal_aerosol_properties`.

2022-07-06 23:22 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +   class(aerosol_state), pointer :: aero_state_obj
@gold2718 Thanks for the tip.  I added the `nullify` statement to initialize `aero_state_obj`.

2022-07-12 16:12 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     procedure :: set_transported
@gold2718 
I am not familiar with the CAM thermo rewrite and don't know why that would have any relevance with this.   I made an attempt to add calls to these interfaces in fv/stepon and added some commits.  Are the latest code mods moving in the right direction?

2022-07-12 19:15 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
@andrewgettelman Please weigh in on this discussion.  How is RNDST used in pumas?  Do we need to set this pbuf field here?

2022-07-12 19:39 UTC, tilmes commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
Andrew to clarify, currently, rndst, which seems to be a parameter of 4 dimensions (probably based on the old BAMS scheme), is set to a constant and then only bin 3 (coarse mode) is set to 0.5* diameter of coarse mode dust. To me we should define rndst, whatever that should be) in the aerosol interface, and not in mircop_aero.F90, so it can be defined specifically for each aerosols scheme. The question for you would be then, can rndst be one dimension and what exactly is it? So for CARMA, would we need to define it as a coarse mode dust radius, if so, where would be the cut-off size?

2022-07-12 20:00 UTC, andrewgettelman commented on src/physics/cam/microp_aero.F90
> +      call pbuf_get_field(pbuf, dgnumwet_idx, dgnumwet)
rndust can be 1 value, and you can define it wherever you want. It is whatever you want the coarse mode dust size to be. 

It is used in the old contact freezing parameterization, which is CAM5 and not CAM6 code (probably not CAM7 either):

https://github.com/ESCOMP/PUMAS/blob/pumas_cam-release_v1.26/micro_pumas_utils.F90#L1643

Which is from Young, 1974:
Young, K. C. “The Role of Contact Nucleation in Ice Phase Initiation of Clouds.” J. Atmos. Sci. 31 (1974): 768–76.

Which I think just needs whatever sizes of dust are in the model (multiple modes, or one mode). 

Again, we don't use this anymore in CAM6, but not sure I want to break it yet (the CAM6 contact nucleation as part of the classical nucleation theory might need some work).

Basically you do want the aerosols to provide this, but it should be queried in micro_aero_ts probably and loaded into pbuf. Unless you want to do it in the microphysics interface.

Hope that helps.

Regards,

Andrew

2022-07-19 03:00 UTC, gold2718 requested changes
I still do not see how this could work if the CAM state was not a pointer.

2022-07-19 20:44 UTC, cacraigucar reviewed
I was surprised to see I have a pending comment, but am unable to find it.  I'm submitting this review so we can see what my comment is.   (Now I see is was just a confirmation reply)

2022-07-25 23:03 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    call rad_cnst_get_info(0, nmodes=nmodes)
@gold2718 :   `rad_cnst_get_info` does not use the CAM state.

2022-07-29 18:44 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     ! This aerosol model with the state of the transported aerosol constituents
made the change as suggested

2022-07-29 18:44 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     ! This returns to current state of the transported aerosol constituents
made the change as suggested

2022-07-29 18:47 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +      aero_props_obj => modal_aerosol_properties()
Now get a pointer to an instantiated  aerosol state object from microp_aero

2022-07-29 18:47 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +   if (num_trans_aerosols>1) then
Should be `>0` -- made the change

2022-07-29 18:48 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +         call aero_state_obj%set_transported(aero_constituents(:,:,:,c))
Now pass in `phys_state%q`

2022-07-29 18:49 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +         aero_state_obj => modal_aerosol_state( phys_state(c), pbuf )
now use aero state created in microp_aero

2022-07-29 22:44 UTC, gold2718 commented on src/physics/cam/zm_microphysics.F90
> +type(modal_aerosol_properties), pointer :: aero_props_obj
I'm not seeing that change.

2022-07-29 22:49 UTC, gold2718 reviewed
I think the structural issues have been resolved!
There are still some unresolved conversations. Some are open requests for change, others may be fixed. @nusbaume, could you check your open conversations?
Getting really close.

2022-08-01 14:55 UTC, nusbaume commented on src/physics/cam/zm_microphysics.F90
> +type(modal_aerosol_properties), pointer :: aero_props_obj
I'm not seeing this change either.  Once this is done all of my concerns will be resolved.

2022-08-01 20:54 UTC, nusbaume commented on src/physics/cam/zm_microphysics.F90
> +type(modal_aerosol_properties), pointer :: aero_props_obj
Looks good now, thanks!

2022-08-01 20:56 UTC, nusbaume commented
@fvitt @gold2718  all of my issues have been resolved, so this PR is good to go (at least for me).  Thanks!

2022-08-04 02:31 UTC, gold2718 commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +  use cam_abortutils, only: endrun
I would at least like a plan on how we remove CAM dependence here. `pi` is easy, just `SHR_CONST_PI`. 
I think the `endrun` calls should be replaced with a call to a passed-in error handling function that takes a string. Where is a good place to open an issue on this? CAM? NCAR/ACOM-SE-tasks?

2022-08-04 02:32 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
@tilmes, Thanks for the summary. Are the issues you raised above resolved?

2022-08-04 03:18 UTC, gold2718 reviewed
Still trying to figure out this code. What is the timing like? It seems like the way `loadaer` is implemented, what used to be a loop over `pcols` is now a loop over `pcols*pcols` (`dropmixnuc` calls `loadaer` for a single bin (`loadaer2`) which calls `loadaer` for an entire array (`pcols` ==> `loadaer1`) and then returns the the desired column). Am I missing something?

2022-08-04 03:18 UTC, gold2718 commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
Is this code only active for modal aerosols?

2022-08-04 14:19 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +  use cam_abortutils, only: endrun
ESCOMP/CAM is a good place for the issue.

2022-08-04 14:39 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
Yes.  For now, only for modal.

2022-08-04 16:03 UTC, gold2718 commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
Is there a plan to create aerosol-model-agnostic interface (e.g., when the rad_cnst code gets absorbed into the new aerosol objects)? If so, it would be good to have an open issue on this as well as the current implementation introduces a new area that is model specific. If not, we need a plan!

2022-08-04 16:08 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
Yes we need to plan on how to deal with the `rad_cnst` interfaces.  I have not thought that far ahead yet.

2022-08-04 16:11 UTC, fvitt commented
> Still trying to figure out this code. What is the timing like? It seems like the way `loadaer` is implemented, what used to be a loop over `pcols` is now a loop over `pcols*pcols` (`dropmixnuc` calls `loadaer` for a single bin (`loadaer2`) which calls `loadaer` for an entire array (`pcols` ==> `loadaer1`) and then returns the the desired column). Am I missing something?

@gold2718 
The `loadaer2` method is only used in carma specific code and is not needed for this PR.  I propose that we leave loadaer2 out of this PR.  I might need to rethink this if it is really needed for carma.

2022-08-10 15:35 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
@gold2718 Is this resolved?

2022-08-10 15:36 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +  use cam_abortutils, only: endrun
@gold2718 Is this resolved?  Do I need to open the issue?

2022-08-10 15:39 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
This will be dealt with in a later PR.

2022-08-10 17:52 UTC, tilmes commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure(aero_mmr_names), deferred :: get_mmr_names
Yes, that  makes sense. @fvitt This is resolved.

2022-08-19 03:59 UTC, gold2718 requested changes
Just a couple of easy to fix (IMHO) items.

2022-08-19 03:59 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
> @gold2718 Is this resolved?

I don't think so. On April 12, you said, "I agree that `endrun` and `iulog` could be easily replaced at this point." but you did not go ahead and replace them. Since it represents an interface change, it would be good to get it into this version.

2022-08-19 03:59 UTC, gold2718 commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
Okay. I am leaving this conversation unresolved for this PR.

2022-08-19 03:59 UTC, gold2718 commented on src/dynamics/fv/stepon.F90
> +   clim_modal_aero = (nmodes > 0)
It occurs to me that an easy way to correct this might be for microp_aero to make `aero_props_obj` be `public, protected`. Then, this becomes:
```suggestion
   clim_modal_aero = associated(aero_props_mod)
```
and you do not need the call to `rad_cnst_get_info` above. You could also have a logical function interface that returns `associated(aero_props_mod)` so that it works similarly to `aerosol_state_object`.

2022-08-19 17:52 UTC, cacraigucar approved these changes

2022-08-19 19:21 UTC, fvitt commented on src/dynamics/fv/stepon.F90
> +   clim_modal_aero = (nmodes > 0)
@gold2718 I like your thinking.  I implemented `aerosol_properties_object` which returns the pointer to the `aero_props_obj` in `microp_aero`.  Let me know if you okay with what I did here.

2022-08-19 19:41 UTC, gold2718 commented on src/dynamics/fv/stepon.F90
> +   clim_modal_aero = (nmodes > 0)
@fvitt, yes, this is great, thanks!

2022-08-19 23:44 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  use cam_logfile, only: iulog
I removed the dependencies on `endrun` and `iulog` from the aerosol class code.

2022-08-22 15:05 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +          call endrun('phase error in aerosol_state::loadaer1')
An error string is now returned to caller.

2022-08-22 17:41 UTC, gold2718 commented on src/dynamics/fv/stepon.F90
> +   call rad_cnst_get_info(0, nmodes=nmodes)
Turns out this is now taken care of.

2022-08-22 17:45 UTC, gold2718 commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +  use cam_abortutils, only: endrun
This is up to you and ACOM. At some point, you will want to remove CAM dependence but that is not relevant for CAM.

2022-08-22 17:54 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    use ppgrid, only: pcols, pver
This has been fixed.

2022-08-22 17:54 UTC, gold2718 approved these changes
Looks good now, thanks for all the work!

2022-08-23 17:27 UTC, cacraigucar requested changes
At today's meeting, the issue with NAG needing the --mismatch flag to compile was identified as needing to be looked at further.  As a result of this, I am requesting that Steve re-review the code and I am also rescinding my approval until we confirm this isn't an issue with the new class structure.

2022-08-25 23:03 UTC, gold2718 requested changes
I think you are missing an `abstract` keyword

2022-08-25 23:03 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  interface
Since you have deferred methods, I believe this needs to be `abstract`:
```suggestion
  abstract interface
```

2022-08-25 23:36 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  interface
Do we need to add the `abstract` key word in `aerosol_state_mod.F90` as well?

2022-08-25 23:57 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  interface
I believe so but doesn't that module already use the `abstract` keyword?

2022-08-26 00:03 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  interface
Oops, I was looking at the wrong code base. Yes, you should have one but you only run into this nag error in certain (explicitly polymorphic) situations.

2022-08-26 00:23 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  interface
Thanks. The `abstract` key word fixes the nag issue.

2022-08-26 13:59 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +  interface
Sorry for not noticing that earlier. I think the general rule is:

> An abstract interface gives a name to a set of characteristics and argument keyword names that would constitute an explicit interface to a procedure, without declaring any actual procedure to have those characteristics.

2022-08-26 18:23 UTC, cacraigucar approved these changes

2022-08-30 17:30 UTC, tilmes approved these changes

2022-09-01 04:39 UTC, gold2718 requested changes
I don't understand why you are using the modal aerosol interface in ZM microphysics instead of the generic routine from microp_aero (`aerosol_properties_object`).

2022-09-01 04:39 UTC, gold2718 commented on src/physics/cam/zm_microphysics.F90
> +use modal_aerosol_properties_mod, only: modal_aerosol_properties
This seems like a step backwards.

2022-09-01 04:39 UTC, gold2718 commented on src/physics/cam/zm_microphysics.F90
> +type(modal_aerosol_properties), pointer :: aero_props_obj => null()
Why can't this be `class(aerosol_properties)`?

2022-09-01 04:39 UTC, gold2718 commented on src/physics/cam/zm_microphysics.F90
> +   aero_props_obj => modal_aerosol_properties()
This seems like a step backwards. Why can't you use `aerosol_properties_object`?

2022-09-01 14:48 UTC, fvitt commented
> I don't understand why you are using the modal aerosol interface in ZM microphysics instead of the generic routine from microp_aero (`aerosol_properties_object`).

Sorry for the backwards step.  It was a solution to a failing regression test (outfrq3s_convmic).  I have implemented another solution which I don't think is a step backwards.

2022-09-01 14:51 UTC, fvitt commented on src/physics/cam/zm_microphysics.F90
> +   aero_props_obj => modal_aerosol_properties()
There was an issue of timing.  This was attempting to get a pointer to aerosol properties object was instantiated.   I now get the pointer later.

2022-09-02 17:50 UTC, merged