cam6_3_118: Integrating HEMCO emissions component in CESM
ESCOMP/CAM pull request #560
Opened 2022-04-05 15:24 UTC by jimmielin

Please refer to companion issue: https://github.com/ESCOMP/CAM/issues/504 for previous discussion.

An updated copy of the code description plus compile and run instructions is written below:

## Intro
HEMCO is a versatile emissions and data component with the primary purpose of processing emissions data online with inventory selection, masking, and scaling functionality performed as described by a configuration file (see [Lin et al., 2021 Figure 2](https://gmd.copernicus.org/articles/14/5487/2021/gmd-14-5487-2021-f02.png)). Emissions data is ingested from individual netCDF files of different inventories and combined into a collection of 3-D emissions containers for each chemical species. HEMCO also is capable of processing generic data containers that are used to provide data (e.g., UV albedo) for GEOS-Chem chemistry within CESM (working PR: https://github.com/ESCOMP/CAM/pull/484).

Motivation to implement HEMCO as an online emissions data source is to remove the need for re-processing offline emission datasets for simulations, instead allowing users to select on-the-fly emission inventories to use, their hierarchy/precedence and effective geographical region, and apply scale factors on-line. The original netCDF input data does not need to be modified, sub-setting and regridding are performed by HEMCO automatically to the target simulation domain.

In its current implementation, HEMCO within CESM can provide emissions and data to GEOS-Chem chemistry (#484) and CAM-chem chemistry.

## High level code description
The HEMCO-to-CESM interface (`HEMCO_CESM`) has been implemented as a module within CAM residing under `src/hemco`. The most recent version of the code is available at: https://github.com/jimmielin/HEMCO_CESM but will eventually be hosted under `ESCOMP/HEMCO_CESM`. It includes:
* the main HEMCO source code as an external sourced from the HEMCO repository maintained by the GEOS-Chem Support Team (https://github.com/geoschem/HEMCO/),
* a main driver (`hemco_interface`) designed to be called from `control/cam_comp.F90`, and
* supporting routines (`hco_cam_exports`) designed to export data from the HEMCO interface.

HEMCO in CESM runs on its own separate grid and MPI decomposition (as initialized by `hco_esmf_grid`), currently limited to a rectilinear latitude-longitude grid (see limitations), and regrids its computed data to the CAM grid as described by `cam_physics_mesh` in recent versions of CAM.

3-D emissions can be computed. ESMF regridding is layer-by-layer, and vertical regridding is only performed when files are read into `HEMCO_CESM`.

Emissions and data computed are written into the CAM physics buffer (prefixed by `HCO_`) and retrieved by whatever component within CAM that requires this data.

**The version of code submitted as pull request here does not have any GEOS-Chem dependencies and can be considered independently of the #484 PR for GEOS-Chem chemistry.**

## Requirements
Apart from the main HEMCO source code, the following things are required:
* `USE_ESMF_LIB=true` is required for compile and `env_mach_specific.xml` needs to point to an ESMF version supporting netCDF I/O (`ncdfio` and not `defio`). This may be the default already in recent versions of CAM.

## Limitations and points of discussion
* HEMCO uses its own input module, using "vanilla" netCDF routines. HEMCO supports the implementation of different input modules (e.g., for operation within MAPL for the GEOS model, HEMCO uses *ExtData*). Due to time limitations it is not certain when HEMCO will support CDEPS as the input module.
* For HEMCO to replace the current CAM-chem emissions module, input datasets used presently by CAM-chem for emissions need to be ported to HEMCO in a combination of input files (if these emission inventories are unavailable in HEMCO; see [Lin et al., 2021, Table 1](https://gmd.copernicus.org/articles/14/5487/2021/gmd-14-5487-2021-t01.png)) and configuration files to combine the inventories into an end result consistent with presently-used configurations (e.g., CEDS + BB4CMIP6). The responsibility of maintaining input data sets and configuration files would need to be discussed as well.

## Build instructions
Building instructions for a test case with CAM-chem support:

* Checkout ESCOMP/CESM at `master`
* **include modded CAM external.** Edit `Externals.cfg` to source from testing branch, based off `cam_development` (as of now, `cam6_3_095`)
```
[cam]
branch = HEMCO-CESM_rebased_on_cam6_3_045
protocol = git 
repo_url = https://github.com/CESM-GC/CAM
local_path = components/cam
externals = Externals_CAM.cfg
required = True
```

* `./manage_externals/checkout_externals`
* `cd cime/scripts`
* `./create_newcase --case ~/hemco_dev_202201 --compset FCSD_HCO --res f09_f09_mg17 --run-unsupported --mach cheyenne --project project_number_here` (change `--case` and `--project` as appropriate). HEMCO compsets ending in `_HCO` for common chemistry compsets have been implemented. These add `%HEMCO` to the compset long name.
* `./case.setup` and `./case.build`
* You may also want to empty `ext_frc_specifier`, `srf_emis_specifier` in the atm namelist; they will be ignored if `HEMCO_CESM` is enabled, but emptying it will allow the pre-run phase to skip detection of these files.
* run case for testing (`./case.submit`)

### Notes
* Compsets including HEMCO have been added with the suffix `_HCO` and long name equivalent `%HEMCO`.
* HEMCO is now always built with CESM with minimal impact to compile time, however now ESMF lib must be included (`USE_ESMF_LIB=true`)
* HEMCO is configured as a **runtime** option using `use_hemco = .true.` in the physics control namelist.

## End notes and implementation roadmap
Target branch has been rebased over `cam6_3_095`, the latest `cam_development` as of March 7 2023. Changes include:
* Runtime option `use_hemco` in phys control namelist to control HEMCO routine at runtime.
* Namelist options
* `_HCO` compsets for common chemistry compsets, adding `%HEMCO` to compset long name. This long name triggers the `-hemco` configure option used to set up namelist entries for HEMCO, but these namelist entries can also be added in the future.
* everything else self-contained within the `hemco` external (in `src/hemco`) and of course the `HEMCO` external (in `src/hemco/HEMCO`) containing shared HEMCO code by all models.

We suggest implementing HEMCO within CESM in phases, first bringing HEMCO into CESM so GEOS-Chem can be operational, then implementing a transitional period for CAM-chem users to possibly use HEMCO, finally moving all CAM-chem compsets to full HEMCO usage.

Thank you for your help and please do not hesitate to provide any feedback.

2022-07-27 18:08 UTC, fvitt requested changes
Does HEMCO need to be a configure/build option?  Can it be a runtime option?  Does HEMCO work when CAM is on an unstructured grid?

2022-07-27 18:08 UTC, fvitt commented on src/chemistry/mozart/mo_srf_emissions.F90
> +#else
Similar to mo_extfrc, it would be preferable to have HEMCO specific modules to set surf emis fluxes rather than put HEMCO specific code in mo_srf_emissions.

2022-07-27 18:08 UTC, fvitt commented on src/chemistry/mozart/mo_srf_emissions.F90
> +        pbuf_chnk => pbuf_get_chunk(hco_pbuf2d, lchnk)
Should use pbuf passed into subroutine rather and a module level pointer to pbuf2d

2022-07-27 20:32 UTC, jimmielin commented
Hi @fvitt, thanks for the review. I'll update the code based on your comments.

> Does HEMCO need to be a configure/build option? Can it be a runtime option? 

HEMCO can be a runtime option. However, we need to make sure emissions are either handled by `mo_extfrc` and `mo_srf_emissions`, or HEMCO, never both, to avoid double-counting of emissions. Should we introduce a runtime option to select which emissions are used? 

Of note is that GEOS-Chem chemistry only works with HEMCO (@lizziel), so there needs to be error-handling to ensure HEMCO is enabled when GEOS-Chem chemistry is used, as well.

> Does HEMCO work when CAM is on an unstructured grid?

Yes, tested with `ne30` grid for unstructured. And `f09_f09_mg17`, `f19_f19_mg17` for regular grids.

2022-07-27 20:33 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +    call pbuf_add_field('HCO_IN_JOH',  'global', dtype_r8, (/pcols/), hco_joh_idx )
These are used to pass the NO2 and OH J-values from chemistry to HEMCO for computation of ship plume emissions.

2022-08-08 18:11 UTC, jimmielin commented on bld/namelist_files/namelist_definition.xml
> +
Apologies. Fixed.

2022-08-08 18:12 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +    call pbuf_add_field('HCO_IN_JOH',  'global', dtype_r8, (/pcols/), hco_joh_idx )
Added comments in code to clarify purpose.

2022-08-08 18:12 UTC, jimmielin commented on src/chemistry/mozart/mo_extfrc.F90
> +          pbuf_chnk => pbuf_get_chunk(hco_pbuf2d, lchnk)
Fixed. Code now lives in `src/chemistry/mozart/hco_cc_emissions.F90`.

2022-08-08 18:12 UTC, jimmielin commented on src/chemistry/mozart/mo_extfrc.F90
> +#if defined( HEMCO_CESM )
Code now lives in `src/chemistry/mozart/hco_cc_emissions.F90`.

Calls to `extfrc_set` are removed and go to `hco_set_extfrc` instead, when appropriate.

2022-08-08 18:12 UTC, jimmielin commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +    integer  :: jno2_idx, joh_idx
Fixed.

2022-08-08 18:13 UTC, jimmielin commented on src/chemistry/mozart/mo_srf_emissions.F90
> +#else
Code now lives in `src/chemistry/mozart/hco_cc_emissions.F90`.

Code now calls `hco_set_srf_emissions` instead of `set_srf_emissions`, when appropriate.

`IFDEF` checks to patch out file reads, etc. in `mo_srf_emissions` when `HEMCO_CESM` is enabled, are still present in the original CAM-chem files.

2022-08-08 18:13 UTC, jimmielin commented on src/chemistry/mozart/mo_srf_emissions.F90
> +        pbuf_chnk => pbuf_get_chunk(hco_pbuf2d, lchnk)
Fixed. Code now lives in `src/chemistry/mozart/hco_cc_emissions.F90`.

2022-08-08 18:15 UTC, jimmielin commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +    joh_idx   = get_rxt_ndx( 'jo3_b' )
Fixed in 9ef4fea3.

2022-08-08 18:31 UTC, jimmielin commented
Thanks for your comments. I have updated the code to reflect requested changes.

Code that is HEMCO-specific to retrieve emissions from the physics buffer are now in a separate module, `src/chemistry/mozart/hco_cc_emissions.F90`. This module implements two subroutines:
* `subroutine hco_set_srf_emissions( lchnk, ncol, sflx, pbuf )`
* `subroutine hco_set_extfrc( lchnk, zint, frcing, ncol, pbuf )`

These replace `set_srf_emissions`, and `extfrc_set` from `mo_srf_emissions.F90`, and `mo_extfrc.F90`, when the compile option `HEMCO_CESM` is set. This is to prevent double-counting of emissions.

Right now HEMCO-CESM is still implemented as a compile-time option. I can move it to a runtime option in the namelist in future commits if we want to go in this direction.

2022-10-20 17:57 UTC, fvitt requested changes

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +
The jno2 and joh photolysis reactions will not be present in some configurations.  Should there be a check for these reactions before the rate fields are added to pbuf?

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +#endif
Please re-arranage the if/else as:

```
#if defined( HEMCO_CESM )
 ...
#else 
 ...
#endif 
```

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +!               enabled at runtime.
I don't believe stubs are used.  The cpp ifdefs in the code replace the legacy file based emissions with HEMCO,

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +module hco_cc_emissions
Please use consistent indentation in this module.  Perhaps, tabs need to be replaced with spaces.

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        else
Please change as:

```suggestion
        if ( tmpIdx > 0 ) then
```

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            ! if(masterproc) write(iulog,*) "mo_srf_emissions hemco: debug added emiss for", solsym(n), maxval(sflx(1:ncol, n))
Please remove commented out code.

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +    real(r8), pointer     :: pbuf_ik(:,:)              ! ptr to pbuf data (/pcols,pver/)
Do the HEMCO surface emissions have a vertical dimension?

The `_ik` suffix is a little confusion.  Perhaps the pointer variable would be better named something like `pbuf_ptr` or `pbuf_fld`.

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        else
Please replace with:
```suggestion
        if(tmpIdx > 0) then
```

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +             endif
More commented out code that should be removed

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/mo_setext.F90
> +#endif
Prefer to arrange the if / else block as:
```
#if defined( HEMCO_CESM )
 ...
#else 
 ...
#endif 
```
```

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
Do you need to make any changes to `mo_extfrc.F90`?  The cpp ifdefs in `mo_setext.F90` should be sufficient.

2022-10-20 17:57 UTC, fvitt commented on src/chemistry/mozart/mo_srf_emissions.F90
> +#if !defined ( HEMCO_CESM )
Do you need changes in `mo_srf_emissions.F90`?  The changes in `chemistry.F90` should be sufficient.

2022-10-20 17:57 UTC, fvitt commented on src/control/cam_comp.F90
> +   ! run hemco (first phase?)
Please remove the `?`.

2022-10-20 17:57 UTC, fvitt commented on src/control/cam_comp.F90
> +   call HCOI_Chunk_Run(cam_in, phys_state, pbuf2d, 1)
This would be more clear if you could explicitly specify what the `1` represents something like:
```suggestion
   call HCOI_Chunk_Run(cam_in, phys_state, pbuf2d, phase=1)
```

2022-10-20 17:57 UTC, fvitt commented on src/control/cam_comp.F90
> +   call HCOI_Chunk_Run(cam_in, phys_state, pbuf2d, 2)
Could you change this to something like:
```suggestion
   call HCOI_Chunk_Run(cam_in, phys_state, pbuf2d, phase=2)
```

2022-10-21 15:47 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +module hco_cc_emissions
My bad. Fixed.

2022-10-21 15:48 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +!               enabled at runtime.
Thank you, updated to reflect actual behavior.

2022-10-21 15:48 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +#endif
Thanks, done.

2022-10-21 15:49 UTC, jimmielin commented on src/chemistry/mozart/mo_srf_emissions.F90
> +#if !defined ( HEMCO_CESM )
Thanks, missed removing this due to an oversight. No changes in `mo_srf_emissions.F90` are necessary now.

2022-10-21 15:53 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            ! if(masterproc) write(iulog,*) "mo_srf_emissions hemco: debug added emiss for", solsym(n), maxval(sflx(1:ncol, n))
Done.

2022-10-21 15:54 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +    real(r8), pointer     :: pbuf_ik(:,:)              ! ptr to pbuf data (/pcols,pver/)
No, but the entire 3-D emissions data is in one single physics buffer which has a vertical dimension. To mimic the behavior of CAM-chem's emissions, `hco_set_srf_emissions` reads the surface layer of the pbuf, and `hco_set_extfrc` reads the remaining layers (`do k = 1, pver-1`).

Changed to `pbuf_ptr`.

2022-10-21 15:56 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        else
Thank you, fixed.

2022-10-21 15:56 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +             endif
Thank you, removed by getting rid of the extraneous if/else clause.

2022-10-21 15:57 UTC, jimmielin commented on src/chemistry/mozart/mo_setext.F90
> +#endif
Thank you, fixed.

2022-10-21 15:59 UTC, jimmielin commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
Since `extfrc_inti` is called from `mo_chemini.F90` (this is necessary as it initializes the `_XFRC`, `_CLXF` ... diagnostics) we need to patch out the warning messages that no forcing files are present - because when HEMCO handles emissions, the list of external forcing files is always empty.

2022-10-21 16:01 UTC, jimmielin commented on src/control/cam_comp.F90
> +   call HCOI_Chunk_Run(cam_in, phys_state, pbuf2d, 1)
Thanks, fixed.

2022-10-21 16:02 UTC, jimmielin commented on src/control/cam_comp.F90
> +   call HCOI_Chunk_Run(cam_in, phys_state, pbuf2d, 2)
Thanks, fixed.

2022-10-21 16:10 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +
Thanks, now checks for `get_rxt_idx('jno2') > 0` (& for jo3_b) before allocating pbuf fields. Same when updating these fields in `mo_gas-phase_chemdr`.

Can I ask what is the convention for a `if` statement like this?
```fortran
    if(rxt_jno2_idx > 0 .and. hco_jno2_idx > 0) then
      call pbuf_get_field(pbuf, hco_jno2_idx, hco_j_tmp_fld)
      ! this is already in chunk, write /pcols/ at surface
      hco_j_tmp_fld(:ncol) = reaction_rates(:ncol,pver,rxt_jno2_idx)
    endif
```

I write both conditions explicitly since `rxt_jno2_idx > 0` is the science condition, and `hco_jno2_idx > 0` is for safety. But, `hco_jno2_idx`'s pbuf-field will never be initialized by `chemistry.F90` if `rxt_jno2_idx` does not exist. So the clauses are redundant. I can just keep one, but not sure which is clearer. I feel the rest of the code generally checks for the science condition.

2022-10-24 15:22 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        else
Thanks, changed.

2022-10-24 15:22 UTC, jimmielin commented
Thank you @fvitt for the comments and edits. I have updated the pull request with the corresponding updates.

2022-10-31 19:54 UTC, jimmielin commented
I've updated the PR with an additional update:

The `&hemco` namelist now includes a `hemco_grid_xdim` and `hemco_grid_ydim` configuration to specify the HEMCO intermediate grid resolution. Previously, this was hardcoded in `src/hemco/hemco_interface.F90` and was not optimal.

Defaults are provided for `1.9x2.5`, `0.9x1.25` and `ne30np4` grids in `namelist_defaults.xml`.

Additionally, the `HEMCO-CESM` interface version used is now tagged (`hemco-cesm1_0_hemco3_5_0`) instead of tracking the `development` branch.

Thanks,
Haipeng

2022-11-01 20:37 UTC, fvitt requested changes
more questions

2022-11-01 20:37 UTC, fvitt commented on bld/config_files/definition.xml
> +WARNING THIS IS ON BY DEFAULT FOR DEVELOPMENT - DO NOT SUBMIT THIS TO PRODUCTION CODE
Is this warning still true?

2022-11-01 20:37 UTC, fvitt commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
How about simply adding a return at the top of the _inti routine if HEMCO is active?

2022-11-01 20:37 UTC, fvitt commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
This check is not needed -- `n_frc_files` will be zero when HEMCO is active.

2022-11-01 20:37 UTC, fvitt commented on src/control/cam_comp.F90
> +
Can this be moved to chem_init?

2022-11-01 20:37 UTC, fvitt commented on src/control/cam_comp.F90
> +#endif
Can this be moved to chem_timestep_init?

2022-11-01 20:37 UTC, fvitt commented on src/control/cam_comp.F90
> +#endif
Move to chem_timestep_init?  Why 2 phases?

2022-11-01 20:37 UTC, fvitt commented on src/control/cam_comp.F90
> +#endif
Move to chem_final?

2022-11-01 22:12 UTC, jimmielin commented on bld/config_files/definition.xml
> +WARNING THIS IS ON BY DEFAULT FOR DEVELOPMENT - DO NOT SUBMIT THIS TO PRODUCTION CODE
Yes. Apologies I forgot about looking into this. I'll push a commit shortly with some compsets enabling HEMCO, so I can make this default to 0.

2022-11-01 22:14 UTC, jimmielin commented on src/control/cam_comp.F90
> +
`chem_init` is implemented by each mechanism(?) under `src/chemistry` so this would duplicate code to call HEMCO initialization. Could we keep it here, so it would automatically apply to all chemistry mechanisms?

2022-11-01 22:18 UTC, jimmielin commented on src/control/cam_comp.F90
> +#endif
First run of phase 1 will set the physics buffer fields used by HEMCO to communicate to chemistry to zero, so no uninitialized data will be read by chemistry.

We run HEMCO actual computation in phase 2 so the physics variables used by HEMCO to compute state-dependent emissions are available to HEMCO at that point.

2022-11-01 22:19 UTC, jimmielin commented on src/control/cam_comp.F90
> +#endif
Please see above comment on moving to `chem_timestep_init` - this would duplicate code across different mechanisms.

2022-11-01 22:19 UTC, fvitt commented on src/control/cam_comp.F90
> +
There is 1 version of `chem_init` for all mechanisms.  It is in `src/chemistry/mozart/chemistry.F90`

2022-11-01 22:26 UTC, jimmielin commented on src/control/cam_comp.F90
> +
> There is 1 version of `chem_init` for all mechanisms. It is in `src/chemistry/mozart/chemistry.F90`

I think we override this in GEOS-Chem (although it's not merged yet). Could we instead move the routines to `physpkg.F90`, in `phys_init`, `phys_run1`, `phys_run2`, and `phys_final`?

2022-11-01 22:29 UTC, fvitt commented on src/control/cam_comp.F90
> +
Yes, `physpkg` would be better.

2022-11-01 22:58 UTC, jimmielin commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
Thank you, I will remove this.

> How about simply adding a return at the top of the _inti routine if HEMCO is active?
We still need the calls to add `_XFRC`, `_CLXF`, and `_CMXF` history fields by `extfrc_inti`, so part of the subroutine still has to run. Maybe I can return after the calls to `addfld`?

2022-11-02 15:19 UTC, fvitt commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +    integer  :: jno2_idx, joh_idx
I think you need to remove this line:
```suggestion
```

2022-11-02 15:19 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +
I think it is good to check both indices are greater than zero.

2022-11-02 15:29 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +    real(r8), pointer     :: pbuf_ik(:,:)              ! ptr to pbuf data (/pcols,pver/)
Hmm... It seems that `hco_set_extfrc` could set forcings in all the vertical layers then `hco_set_srf_emissions` would not be needed.

2022-11-02 16:05 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +    real(r8), pointer     :: pbuf_ik(:,:)              ! ptr to pbuf data (/pcols,pver/)
Yes, this is possible from the HEMCO side. However, there are two possible issues:
* The list of species available for external forcing is hard-coded in `extfrc_lst` in `mo_sim_dat.F90`. This is a very short list and does not include all species. We would have to update `extfrc_lst` for each mechanism to include all emitted species. Right now this is not a problem, because the species emitted in the vertical in the default HEMCO setting are already in the shortlist (`so4_a1`, `NO`, `NO2`, `num_a1`)
* I am not sure why surface emissions are handled separately (it is passed to `cam_in%cflx` after exiting `mo_srf_emissions`), but there could be additional handling of the surface emissions to distribute them during the boundary layer mixing process. This is the case in GEOS-Chem, so if it happens in CAM-chem as well we may want to keep it as-is.

2022-11-02 16:05 UTC, jimmielin commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
We still need the calls to add `_XFRC`, `_CLXF`, and `_CMXF` history fields by `extfrc_inti`, so part of the subroutine still has to run. Maybe I can return after the calls to `addfld`?

2022-11-02 16:05 UTC, jimmielin commented on src/control/cam_comp.F90
> +#endif
Thanks, will move to `physpkg` now.

2022-11-02 16:06 UTC, jimmielin commented on src/control/cam_comp.F90
> +#endif
Thanks, will move to `physpkg` now.

2022-11-02 16:06 UTC, jimmielin commented on src/control/cam_comp.F90
> +
Thanks, will move to `physpkg` now.

2022-11-04 15:58 UTC, jimmielin commented
Thanks for the comments. I have updated the PR with the following changes:

* Now HEMCO routine calls are moved to `physpkg.F90`
* Reverted all changes in `mo_extfrc.F90`; instead, added `hco_extfrc_inti` to replace `extfrc_inti`
* Added component sets with option `%HEMCO` for CAM: `FCSD_HCO`, `FCnudged_HCO`, `FCHIST_HCO`, `FC2000climo_HCO`, `FC2010climo_HCO`.

2022-11-04 15:59 UTC, jimmielin commented on src/chemistry/mozart/mo_extfrc.F90
> +#if !defined ( HEMCO_CESM )
now added `hco_extfrc_inti`. Reverted all changes in `mo_extfrc.F90`

2022-11-04 15:59 UTC, jimmielin commented on bld/config_files/definition.xml
> +WARNING THIS IS ON BY DEFAULT FOR DEVELOPMENT - DO NOT SUBMIT THIS TO PRODUCTION CODE
Now added compsets. Warning no longer applies

2023-01-17 18:32 UTC, cacraigucar commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
We were taking a quick look at this PR to get a feel for the scope of upcoming reviews, and these preprocessor directives jumped out at us.  We were curious why HEMCO is being introduced conditionally like this.  From discussions with AMP scientists, it sounds like HEMCO will be a mandatory feature in a good number of CAM runs moving forward (for regridding emission files as an example).  

We just wanted to find out why it was felt that HEMCO should come in as a preprocessor dependent feature.  Is it due to a possible extensive compilation time or memory requirements or was there some other reason?

2023-01-19 21:13 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
@jimmielin has expressed to me the concern of having both the legacy file based emissions and HEMCO emissions activate at the same time.  To avoid this situation, the HEMCO_CESM preprocessor variable was implemented is my understanding   There are other was to avoid this situation, such as adding logic to `build-namelist` and the CAM code.  
In my opinion, the interface to HEMCO should not be controlled by HEMCO_CESM preprocessor variable.  It should be always available and turned on via a runtime switch, such as `hemco_emis_active = .true`, and be a runtime option rather than a build-time option.

2023-01-19 21:23 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
Hello @cacraigucar, @fvitt. Thanks for your comments. I am OK with including HEMCO as a runtime option, but the `HEMCO_CESM` component also includes the `HEMCO` external which is the full HEMCO source code. If HEMCO is to be kept as a runtime option, this would mean that it would always be retrieved and potentially compiled, even if HEMCO might not be used. Would that be acceptable?

Additionally, the HEMCO-CESM option requires `./xmlchange USE_ESMF_LIB=true` to compile successfully as it uses the ESMF regridder.

I am not aware of extensive compile/memory requirements, just that we try to avoid compiling unnecessary code / introducing dependencies if not necessary.

2023-01-19 22:11 UTC, fvitt requested changes

2023-01-19 22:11 UTC, fvitt commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +#if defined ( HEMCO_CESM )
You can remove the `#if defined ( HEMCO_CESM )` checks from `mo_gas_phase_chemdr`.  They are not really needed.

2023-01-19 22:11 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            frcing(:ncol,k,m) = pbuf_ik(1:ncol,k) * kg_to_molec / ((zint(:ncol,k)-zint(:ncol,k+1)) * km_to_cm)
`frcing` argument has `intent(inout)` attribute.  So we need to accumilate the HECMO sources to other sources, such as lightning production of NOx.
```suggestion
            frcing(:ncol,k,m) = frcing(:ncol,k,m) + pbuf_ik(1:ncol,k) * kg_to_molec / ((zint(:ncol,k)-zint(:ncol,k+1)) * km_to_cm)
```

2023-01-19 22:11 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +             endif
Looks like the commented out code is still there.

2023-01-19 22:24 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +       call pbuf_add_field('HCO_IN_JOH',  'global', dtype_r8, (/pcols/), hco_joh_idx )
These `pbuf_add_field` calls can be moved to `hemco_interface` module.

2023-01-19 22:26 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +       call pbuf_add_field('HCO_IN_JOH',  'global', dtype_r8, (/pcols/), hco_joh_idx )
Thanks for your comment. HEMCO uses the presence of `HCO_IN_JNO2` and `HCO_IN_JOH` pbuf fields to identify whether a particular feature involving these J-rates are activated. This is why I added them in `chemistry.F90` instead of `hemco_interface.F90` so these fields are only added if the reactions `jno2` and `jo3_b` are available.

2023-01-19 22:31 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
The surface fluxes are passed to diffusion where they are distributed in the boundary layer. This is consistent with how surface fluxes are handled in CAM-chem.

Double counting is avoided by the loop index in `hco_cc_emissions`, subroutine `hco_set_extfrc`:
```fortran
do k = 1, pver-1
```

which ignores the lowest layer.

2023-01-19 22:32 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            pcnst_is_extfrc = (get_extfrc_ndx(trim(solsym(n))) > 0)
Apologies for the bug. Fixed.

2023-01-19 22:33 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            frcing(:ncol,k,m) = pbuf_ik(1:ncol,k) * kg_to_molec / ((zint(:ncol,k)-zint(:ncol,k+1)) * km_to_cm)
Thanks, fixed.

2023-01-19 22:34 UTC, cacraigucar commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
I've been hearing from people like @adamrher, that HEMCO is going to allow the use of random grids.  I also believe that at least a minimal set of emission files are needed even if chemistry is turned off, is that correct @fvitt?  If both of those statements are true, then I believe that we will be moving to a point where we will no longer have emission files on any predefined grids, and will instead be mapping on the fly.

Let me know if I am understanding this correct or not

2023-01-19 22:38 UTC, jimmielin commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +#if defined ( HEMCO_CESM )
Thanks, fixed. Also removed extraneous USE statement encapsulated by HEMCO_CESM directive.

2023-01-19 22:39 UTC, jimmielin commented on bld/configure
> +
This would build HEMCO source in all compsets which may not be desirable, as HEMCO-enabled compsets also set other namelist variables such as the path to HEMCO configuration file and configuration for HEMCO grid. We can merge discussion about this into the discussion about removing the `HEMCO_CESM` pre-processor constant.

2023-01-19 22:40 UTC, jimmielin commented on bld/configure
> +    $cfg_cppdefs .= ' -DMODEL_ -DMODEL_CESM -DHEMCO_CESM -DUSE_REAL8 ';
`MODEL_`, `MODEL_CESM`, and `USE_REAL8` are used by HEMCO source (included as an external) maintained by the GEOS-Chem Support Team to identify coupling to external model specific, and CESM-specific code.

2023-01-19 22:41 UTC, jimmielin commented on bld/configure
> +    # -- Added by hplin - 5/2020
Thanks, fixed

2023-01-19 22:50 UTC, cacraigucar commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
According to stackoverflow (https://stackoverflow.com/questions/26675185/difference-between-nullifypointer-and-pointer-null)  pointing to null() and using nullify are identical.  CAM typically uses `nullify(variable_name)` in the code body, but it isn't a rule, I don't believe.  

That said, I think the variable being nullified here should be pbuf_ptr_2d, correct?

2023-01-19 23:04 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
Oops, my bad! Fixed to `pbuf_ptr_2d`. Thanks for pointing it out.

2023-01-20 00:06 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
@cacraigucar your understanding is correct.
Emissions of aerosols in CAM6 (without chemistry) can be handled by HEMCO which will be helpful when regionally refined grids are used.

2023-01-23 20:37 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
This is not consistent with how 3D external forcings are handled in CAM-Chem.  CAM-chem does not convert the lowest layer of the 3D forcings to a surface flux.  All layers of the 3D forcings are used in the chemical solver as additional sources.  Why do you need to treat the lowest layer of the 3D emissions differently?

2023-01-23 20:41 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +       call pbuf_add_field('HCO_IN_JOH',  'global', dtype_r8, (/pcols/), hco_joh_idx )
The check for jno2 and jo3_b photo reactions can be done the the `hemco_interface`.  I feel that these `pbuf_add_field` calls should be moved to the `hemco_interface` module.

2023-01-23 21:12 UTC, lkemmons commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
I prefer to keep the treatment of 3D emissions (external forcings) as we have always handled them in CAM-chem -- all levels are treated the same - including them in the chemical solver (as Francis suggests).  I doubt it makes any significant difference in actual atmospheric composition from how purely surface (2D) emissions are treated.  I think we can keep the code simpler just adding all levels of the 3D emissions to the chemical solver without causing any degradation in the simulations.

2023-01-23 21:32 UTC, cacraigucar commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
Since it sounds like once HEMCO is introduced, it will be use in all CAM runs (to remap emission files to the proper grid), I'm not sure why it would be optional.  @fvitt, can you give an example setup where you think we would not being using HEMCO?

2023-01-23 21:45 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
There are a few cases where there are no aerosol emissions such as in CAM4 or when prescribed aerosols are used.  I think those cases are becoming less common.

2023-01-23 21:58 UTC, cacraigucar commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
@nusbaume and @adamrher  - What do you both think about making HEMCO optional?  The use cases where it won't be used are sounding like they are limited.  If we do make it optional, should it be configure/build time or runtime?  I'm leaning toward having it a standard part of CAM and not being optional at all, but can be convinced otherwise.

2023-01-24 23:32 UTC, fvitt commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
The CAM software engineers would prefer to not have HEMCO be a configure / build time option, but rather a run time option that can be activated via a namelist switch, provided that the compilation of HEMCO is not too burdensome.

2023-02-06 17:52 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
Thanks for the feedback @fvitt and @lkemmons. I was starting work on this but realized that not all species have 3D forcings in CAM-chem, only a select list in `extfrc_lst` (in `mo_sim_dat`). If we were to use the 3D forcings interface for all species when interfacing with HEMCO, we would have to either (1) expand `extfrc_lst` to all the species available, or, since expanding the list would mean it is equal to `solsym`, (2) remove `extfrc_lst` altogether from CAM and use `solsym` instead.

Alternatively, I can set 3D forcings at all levels for species in the `extfrc_lst`, and pass the remaining species' emissions into `sflx` instead. But this would still be inconsistent.

Looking forward to your thoughts.

2023-02-06 20:00 UTC, fvitt commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
@jimmielin There is no need to have 3D forcings for all species.  The request is to remove the 3D forcings from `hco_set_srf_emissions` and use all levels of the 3D forcings in `hco_set_extfrc`.

2023-02-06 20:02 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +                pbuf_ptr_3d => null()
Oh I see, thank you @fvitt! I'll make the update and push a commit shortly.

2023-03-02 22:59 UTC, jimmielin commented on bld/configure
> +    if ($hemco) {
Removed. Now HEMCO is always built. The `$hemco` var is still kept in `configure` in order for `build-namelist` to toggle the `use_hemco` namelist variable, but no longer controls compile.

2023-03-02 23:00 UTC, jimmielin commented on bld/configure
> +
We now build HEMCO on all compsets. I'll resolve this conversation so we can discuss it in just one thread.

2023-03-02 23:00 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +#if (defined HEMCO_CESM)
We now always build HEMCO and control HEMCO using a runtime switch in the namelist `use_hemco = .true.` (`.false.` by default except in `%HEMCO` compsets)

2023-03-02 23:02 UTC, jimmielin commented
I have updated the pull request by changing HEMCO into a runtime option controlled in the atm namelist.

- `use_hemco` is located in `&phys_ctl_nl` as HEMCO routines may or may not run in `physpkg.F90`, the namelist variable controls it and this logical is propagated using `phys_getopts` to lower levels in the code.
- `&phys_ctl_nl use_hemco` will be set to `.false.` by default.
- In compsets with modifier `%HEMCO` in long name, `use_hemco` will be set to `.true.` by default in these compsets.
- The pre-processor variable `HEMCO_CESM` has been deprecated in favor of the runtime option. Currently, the model must still be built with this pre-processor variable because of upstream dependencies requiring this definition. In a future version of HEMCO, we will change this pre-processor variable to `MODEL_CESM` to be consistent with other definitions.

2023-03-06 17:00 UTC, fvitt commented
@jimmielin Are you able to build compsets that do not use HEMCO?  Using the head of your branch, my attempts to do so fail.  For example, the FC2000climo compset.

2023-03-06 17:21 UTC, jimmielin commented
> @jimmielin Are you able to build compsets that do not use HEMCO? Using the head of your branch, my attempts to do so fail. For example, the FC2000climo compset.

Hi @fvitt, I'm able to build `FC2000climo` but since HEMCO is now always built it requires `./xmlchange USE_ESMF_LIB=true` to be set at all times.

2023-03-06 19:06 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +       call pbuf_add_field('HCO_IN_JOH',  'global', dtype_r8, (/pcols/), hco_joh_idx )
Moved to HEMCO-CESM now. Thanks!

2023-03-06 19:07 UTC, gold2718 commented
> Hi @fvitt, I'm able to build FC2000climo but since HEMCO is now always built it requires ./xmlchange USE_ESMF_LIB=true to be set at all times.

Is this still needed with NUOPC builds? Is NUOPC the default for this branch? Maybe it is time to merge this branch up to the head of cam_development?

2023-03-06 22:44 UTC, fvitt requested changes
Things are looking better from my point of view.  Just a couple small changes for this iteration.

2023-03-06 22:44 UTC, fvitt commented on bld/build-namelist
> +}
Let's include the hemco namelist settings only if HEMCO is active:
```suggestion
add_default($nl, 'use_hemco');
if ($nl->get_value('use_hemco') =~ m/$TRUE/io) {
    add_default($nl, 'cam_physics_mesh');
    add_default($nl, 'hemco_config_file');
    add_default($nl, 'hemco_grid_xdim');
    add_default($nl, 'hemco_grid_ydim');

    # In a compset with %HEMCO modifier enabled, set the value
    # of the use_hemco variable to true
    #
    # use_hemco is in &phys_ctl_nl so that the relevant routine calls
    # can be controlled in physpkg and at levels below
    $nl->set_variable_value('phys_ctl_nl', 'use_hemco', '.true.');
}
```

2023-03-06 22:44 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
Include a path relative to `$inputdata` and a creatation date in the file name.  
For example:
 ```
<hemco_config_file>atm/cam/geoschem/emis/HEMCO_Config_c230303.rc</hemco_config_file>
```

2023-03-06 22:46 UTC, fvitt commented
@cacraigucar I think this is ready for other SEs to review.

2023-03-07 20:57 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
Hi @fvitt, the standard input files are ready. Could you please copy the 3 config files from `/glade/work/hplin/hco_inputdata` to the inputdata directory?

`/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/` would work great.

```
➜  hco_inputdata  ls /glade/work/hplin/hco_inputdata
total 1120
-rw-r--r-- 1 hplin umit0034 534910 Mar  7 13:53 HEMCO_Config_FCnudged.CC.c230306.rc
-rw-r--r-- 1 hplin umit0034 534910 Mar  7 13:53 HEMCO_Config_FCnudged.CC.interp.c230307.rc
-rw-r--r-- 1 hplin umit0034  65133 Mar  7 10:31 HEMCO_Diagn.3_5_0.c230307.rc
```

I will update the PR shortly. Thanks!

2023-03-07 21:36 UTC, jimmielin commented
I have brought this PR's underlying branch up to the latest `cam_development`. Currently testing cases manually then I will add automated tests.

2023-03-07 22:27 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
I copied the files over

2023-03-07 22:36 UTC, cacraigucar commented
I just wanted to check in.  @fvitt indicated this was ready for review, but I see a number of commits have been made today.  Ideally when a PR starts review, the only changes which happen from that point forward are ones to address review requests.  Is this PR at that stage yet, or should we wait a bit longer for the final implementation details to be committed?

2023-03-07 22:42 UTC, jimmielin commented
> I just wanted to check in. @fvitt indicated this was ready for review, but I see a number of commits have been made today. Ideally when a PR starts review, the only changes which happen from that point forward are ones to address review requests. Is this PR at that stage yet, or should we wait a bit longer for the final implementation details to be committed?

My apologies @cacraigucar. I thought I had to bring this up to `cam_development` as the pull request was originally built over `cam6_3_045` which resulted in several merge conflicts with the current development status.

The final implementation details are committed. I can also revert a431b51e which merges up to `cam_development` to bring it back to the state it was after @fvitt's review.

2023-03-07 22:48 UTC, cacraigucar commented
@jimmielin - No, please keep it at the merged state as that is what we'll want, especially since you needed to address some merge problems.  Knowing that that was the reason for the recent commits and that your active development is done, we will put this into our review queue.  Thanks for the clarification

2023-03-07 23:25 UTC, jimmielin commented
Thank you. The code is ready for review, all conflicts with `cam_development` have been resolved.

2023-03-08 02:41 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
Thanks! Is there anything I need to do for `hemco_config_file` property to automatically prepend `$inputdata_root`? I currently have in `namelist_definition.xml`
```xml
<entry id="hemco_config_file" type="char*256" input_pathname="abs" category="hemco"
       group="hemco_nl" valid_values="" >
Full pathname of the HEMCO_Config.rc input file used to configure HEMCO.
Default: set by build-namelist.
</entry>
```
I added the property `input_pathname="abs"` which should be prepend `/glade/p/cesmdata/cseg/inputdata` but writing in `user_nl_cam`
```
hemco_config_file = 'atm/cam/geoschem/emis/HEMCO_Config_FCnudged.CC.c230306.rc'
```
then running `./preview_namelists` still generates `atm_in` with only the relative path and not the absolute path for `hemco_config_file`. Is there anything I need to edit in `build-namelist` perhaps? Thanks!

2023-03-08 16:00 UTC, fvitt commented
> I just wanted to check in. @fvitt indicated this was ready for review, but I see a number of commits have been made today. Ideally when a PR starts review, the only changes which happen from that point forward are ones to address review requests. Is this PR at that stage yet, or should we wait a bit longer for the final implementation details to be committed?

@cacraigucar Sorry if I jumped the gun on this.  We should probably wait for final details and the regression tests work as expected.  

@jimmielin My HEMCO test failed with a run-time error.  It may be that the wrong hemco configuration file is being used.

2023-03-08 16:39 UTC, jimmielin commented
> @jimmielin My HEMCO test failed with a run-time error. It may be that the wrong hemco configuration file is being used.

Hi @fvitt, could you let me know which compset and error (in either `atm.log` or `cesm.log`)? I am not pointing to the `HEMCO_Config.rc` at inputdata yet but the configuration file at `/glade/work/hplin/hco_inputdata/HEMCO_Config_FCnudged.CC.c230306.rc` should be world-readable and ready for use.

> @cacraigucar Sorry if I jumped the gun on this. We should probably wait for final details and the regression tests work as expected.
I'm happy to implement regression tests for HEMCO compsets in `aux_cam` and a new set `camchem_hemco`. I'll update the pull request when these are ready and confirmed to work.

2023-03-08 20:53 UTC, jimmielin commented
Hi @fvitt, this is now fixed. Please update externals as well as I had to update the `cam/src/hemco` external to a new tag to fix this issue.

Apologies for introducing more changes. I have realized that `RUN_STARTDATE` in the `FC2000...` and `FC2010...` compsets is set to `0001-01-01` but the emissions should be cycled from year `2000` and `2010` and not year `0001`. I added a new namelist variable `hemco_emission_year` in `&hemco_nl` which is now set to `2000` or `2010` for the climo runs and `-1` for other runs, allowing for override of the year used in the HEMCO clock.

I have added regression tests for `FCnudged_HCO` on `f09_f09_mg17` and `ne30`, and added them to both `aux_cam` and a new `camchem_hco` category. Please let me know if I should add a few more (perhaps one for `FC2000climo_HCO` to test `hemco_emission_year`). I am running the reference simulations now to establish baseline results.

2023-04-03 22:23 UTC, lkemmons commented
It would be extremely helpful to have HEMCO available for the ASD simulations Ben Gaubert and I will be running on Derecho, if at all possible!  Thanks!

2023-04-10 14:34 UTC, brian-eaton requested changes
First batch of comments.  Primarily addresses the issue that a runtime option shouldn't be controlled using a build-time (i.e. `configure`) mechanism.

2023-04-10 14:34 UTC, brian-eaton commented on bld/configure
> +     -hemco             Switch enables the use of the Harmonized Emissions Component.
Remove `-hemco` option.  Since HEMCO is always built this option should be turned on by the namelist setting, not by configure.

2023-04-10 14:34 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<use_hemco hemco="1">.true.</use_hemco>
This default can be removed. Setting `use_hemco=.true.` is either done by the `%HEMCO` modifier in `config_component.xml`, or by a user mod, e.g. in `user_nl_cam`.

2023-04-10 14:47 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<use_hemco hemco="1">.true.</use_hemco>
This comment just applies to line 3379.

2023-04-10 19:13 UTC, brian-eaton requested changes
The current branch is not hooking the HEMCO emissions into the cam_dev physics package.  This should be done with modifications in `src/physics/cam_dev/physpkg.F90`.

2023-04-10 19:21 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<use_hemco hemco="1">.true.</use_hemco>
Thanks for the comment. Can I confirm that by

> Setting use_hemco=.true. is either done by the %HEMCO modifier in config_component.xml, or by a user mod, e.g. in user_nl_cam.

You mean that I should modify `config_component.xml` (maybe the `CAM_NAMELIST_OPTS` section) to have something like

```xml
    <values match="last" modifier="additive">
...
      <value compset="_CAM.*%HEMCO">use_hemco=.true.</value>
...
```

I think the `-hemco` is just kept for that, and for inserting the other HEMCO namelist variables into `&hemco_nl` as appropriate when compset name has `%HEMCO`. If I can control `use_hemco=.true.` this way I can get rid of the whole configure option.

2023-04-10 19:23 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +    endif
`hemco_interface` has to be aware of all chunks as the ESMF regridder needs to be aware of all the chunks. This is similar to how the ionosphere interface was built.

2023-04-11 00:05 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<use_hemco hemco="1">.true.</use_hemco>
Yes, that's exactly what I meant.  The regular expression match you provided is a correct way to turn HEMCO on directly from the compset definition.  Alternatively the user can add the namelist setting directly to `user_nl_cam`.  The `-hemco` option should be removed from configure.

2023-04-11 00:07 UTC, brian-eaton commented on src/physics/cam/physpkg.F90
> +    endif
Thanks for that information.

2023-04-11 04:05 UTC, jimmielin commented on cime_config/config_component.xml
> +
Removed. Now updates `use_hemco=.true.` in `CAM_NAMELIST_OPTS`.

2023-04-11 04:05 UTC, jimmielin commented on bld/configure
> +    "hemco"                     => \$opts{'hemco'},
Now removed.

2023-04-11 04:05 UTC, jimmielin commented on bld/configure
> +
Now removed.

2023-04-11 04:05 UTC, jimmielin commented on bld/config_files/definition.xml
Now removed.

2023-04-11 04:07 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +
Now removed. Note that the definitions are redundant with the `waccmx_opt="ionosphere"`, and we should be supporting the same options as the ionosphere interface for `cam_physics_mesh` (it's the same underlying implementation for regridding).

So I removed these 3 HEMCO-specific lines and also removed `waccmx_opt="ionosphere"` from the `cam_physics_mesh` definition lines above, so they're always available to HEMCO and the Ionosphere interface. Please let me know if further updates are necessary. Thank you!

2023-04-11 04:07 UTC, jimmielin commented on src/physics/cam/phys_control.F90
Thanks for the background context. I have removed `use_hemco` from `phys_getopts`, and now directly `USE` it in other modules (e.g., `physpkg.F90`)

2023-04-11 04:07 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +
Yes, I also rearranged some other initialization code for performance in `hco_cc_emissions.F90`. Thanks for pointing this out.

2023-04-11 04:08 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        if(tmpIdx > 0) then
Thanks for pointing this out, all revised.

2023-04-11 04:08 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        if(tmpIdx > 0) then
Thanks for pointing this out, all revised.

2023-04-11 04:08 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        ! has_emis(m) = .true.
Removed, thanks!

2023-04-11 04:08 UTC, jimmielin commented on bld/build-namelist
> +    $nl->set_variable_value('phys_ctl_nl', 'use_hemco', '.true.');
Thanks, removed. Please let me know if further revisions to the surrounding block(s) are necessary.

2023-04-11 04:08 UTC, jimmielin commented on bld/configure
> +     -hemco             Switch enables the use of the Harmonized Emissions Component.
Removed, thanks!

2023-04-11 04:09 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<use_hemco hemco="1">.true.</use_hemco>
Thanks, removed and implemented in the manner requested.

2023-04-11 04:09 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +end module hco_cc_emissions
Done, thanks.

2023-04-11 04:11 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +    endif
We might not need 2 phases (in phase 1 we zero out some pbuf fields for safety) but I need to confirm this. I will get back to this comment after I confirm we can remove this. It will also need an update to the upstream HEMCO_CESM external.

2023-04-11 13:49 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +
This seems right to me.  @fvitt, do you agree?

2023-04-11 13:58 UTC, brian-eaton commented on bld/build-namelist
> +    $nl->set_variable_value('phys_ctl_nl', 'use_hemco', '.true.');
Looks good.

2023-04-11 14:21 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +
pls ignore. i see these mesh files are already on the trunk, and not due to this PR. Ill register my concern elsewhere.

2023-04-13 02:12 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +    endif
I've verified that we currently only need phase 2. HEMCO internally distinguishes between phase 1 and phase 2, but the HEMCO-CESM interface safely merges them into one at this point and runs together in CAM phase 2.

I've kept the interface to pass the `phase` for future use and removed the call in `phase=1`.

This needs an upstream update to tag `hemco-cesm1_1_4_hemco3_6_2` which I also updated `Externals_CAM.cfg` with.

2023-04-17 14:50 UTC, cacraigucar commented
@fvitt - Would addressing #787 (by making a PR to ccs_config and removing the mesh files from this PR) be appropriate to do at this time?

2023-04-17 17:50 UTC, brian-eaton commented
I think it would be better to address this separately.  I've assigned myself to #787.

2023-05-09 18:42 UTC, brian-eaton commented
@jimmielin, at our SE meeting this week we set finishing this review at high priority.  A couple of my comments haven't been addressed yet.  Status?

2023-05-09 19:13 UTC, jimmielin commented on cime_config/config_compsets.xml
> +
Removed, thanks!

2023-05-09 19:22 UTC, jimmielin commented
Thanks for the reminder @brian-eaton, I have fixed the `USE_ESMF_LIB` setting and marked it as resolved.

> The current branch is not hooking the HEMCO emissions into the cam_dev physics package. This should be done with modifications in src/physics/cam_dev/physpkg.F90.

Thanks, this has been added to `cam_dev` as well.

2023-05-13 15:10 UTC, nusbaume requested changes
Thanks for getting HEMCO plugged into CAM!  It will be great if we can eventually use HEMCO to reduce the total number of needed input files.

Anyways, I do have one major concern about the location of the HEMCO config file, but otherwise I just have some hopefully minor change requests.  Let me know if there are any questions or concerns with what I have requested, and thanks again!

2023-05-15 01:59 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +!BOP
Thanks for your comment! Yes, this is consistent with other source code in the GEOS-Chem ecosystem that use a script [ProTeX](http://wiki.seas.harvard.edu/geos-chem/index.php/Automatic_documentation_with_protex) that automatically generates documentation. While the file is not automatically included in GEOS-Chem auto-generated code documentation right now, we may want to document it as part of GEOS-Chem/HEMCO interfaces in the future.

2023-05-15 02:01 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +    endif
Thank you for the suggestion! Included.

2023-05-15 02:02 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +        call hcoi_chunk_init()
Done, thanks!

2023-05-15 02:02 UTC, jimmielin commented on src/physics/cam_dev/physpkg.F90
> +        call hcoi_chunk_init()
Done, thanks!

2023-05-15 02:02 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +             endif
Removed, thanks!

2023-05-15 02:03 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        kg_to_molec = 1/(adv_mass(n) / avogadro * cm2_to_m2 * kg_to_g)
Thanks for the suggestion! Fixed.

2023-05-15 02:07 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>/glade/work/hplin/hco_inputdata/HEMCO_Config_FCnudged.CC.c230306.rc</hemco_config_file>
Thanks for the comment! 

1. Yes - this will eventually be moved to the inputdata server. Francis created a directory for this and moved this particular file to:

`/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/HEMCO_Config_FCnudged.CC.c230306.rc`

However, somehow specifying the relative path (`atm/cam/geoschem/emis/HEMCO_Config_FCnudged.CC.c230306.rc`) causes my run to fail (cannot find the file) and `atm_in` generated only includes the relative path, not the absolute path so maybe I have not set up `hemco_config_file` definition correctly. Could you see if my definition is correct?

```xml
<!-- HEMCO -->
<entry id="hemco_config_file" type="char*256" input_pathname="abs" category="hemco"
       group="hemco_nl" valid_values="" >
Full pathname of the HEMCO_Config.rc input file used to configure HEMCO.
Default: set by build-namelist.
</entry>
```

2. Yes - this will work for all the compsets despite named as FCnudged.

2023-05-15 15:39 UTC, nusbaume commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>/glade/work/hplin/hco_inputdata/HEMCO_Config_FCnudged.CC.c230306.rc</hemco_config_file>
Thanks for the feedback!  Setting the namelist defaults to the following worked for me (i.e. gave the correct, absolute path in `atm_in`):

`<hemco_config_file>atm/cam/geoschem/emis/HEMCO_Config_FCnudged.CC.c230306.rc</hemco_config_file>`

If that doesn't work for you can you then point me to the failed case?  Thanks!

2023-05-15 15:41 UTC, nusbaume commented on src/chemistry/mozart/hco_cc_emissions.F90
> +!BOP
Thanks for the feedback!  If it is designed for a documentation generation system then I think it is fine as-is, and so will go ahead and mark this resolved.

2023-05-15 16:08 UTC, cacraigucar requested changes
My requests so far, but I have not completed my code review

2023-05-16 13:57 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>/glade/work/hplin/hco_inputdata/HEMCO_Config_FCnudged.CC.c230306.rc</hemco_config_file>
@jimmielin, if you set the variable `hemco_config_file` in `user_nl_cam`, then you need to set the absolute pathname.  `build-namelist` won't prepend the inputdata location to values read from `user_nl_cam`.  The way that @nusbaume added it to the namelist defaults file is one way to get the inputdata location prepended.  The other way is when the relative path is specified in a use case file (which is really just a defaults file whose entries have higher precedence than the `namelist_defaults_cam.xml` file).

2023-05-16 15:21 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
It's not obvious where the best place for this check would be.  The `use_hemco` variable is read in a different location from where the `chem_inparm` variables are read.  The place where both are known is `build-namelist`.  I'd like to suggest that `build-namelist` be modified to not put the `ext_frc_specifier` and `srf_emis_specifier` variables in the namelist when `use_hemco=.true.`.  This potentially could benefit users on non-NCAR platforms by not invoking the download of a bunch of files that won't be used.  This change could be done in the following way.  In `build-namelist` around line 2851 replace the following code
```
add_default($nl, 'use_hemco');
if ($nl->get_value('use_hemco') =~ m/$TRUE/io) {
    add_default($nl, 'cam_physics_mesh');
    add_default($nl, 'hemco_config_file');
    add_default($nl, 'hemco_grid_xdim');
    add_default($nl, 'hemco_grid_ydim');
}
```
by
```
add_default($nl, 'use_hemco');
if ($nl->get_value('use_hemco') =~ m/$TRUE/io) {
    add_default($nl, 'cam_physics_mesh');
    add_default($nl, 'hemco_config_file');
    add_default($nl, 'hemco_grid_xdim');
    add_default($nl, 'hemco_grid_ydim');
    $nl->delete_variable('chem_inparm', 'ext_frc_specifier');
    $nl->delete_variable('chem_inparm', 'srf_emis_specifier');
}
```
Note that this code block occurs after the chemistry schemes have finished adding `ext_frc_specifier` and `srf_emis_specifier`.

Thoughts?

2023-05-16 17:34 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
That doesn't play well with how the current hemco compsets are defined.  Take `FC2000climo_HCO` which uses use case `2000_trop_strat_vbs_cam6`.  That use case adds the `srf_emis_specifier` and `ext_frc_specifier` variables, as well as sets `hemco_emission_year`.  Your suggestion would require a new use case files that exclude the `srf_emis_specifier` and `ext_frc_specifier` variables.  It would also require changes to `build-namelist` to check in all the places it's currently setting  `srf_emis_specifier` and `ext_frc_specifier` that hemco isn't in use.  That's not such a big deal, but I'm not so wild about the need to duplicate a bunch of chemistry use case files to create hemco specific versions.  I think my solution is easier, but not sure whether it's best for the long run.  What do you think?

2023-05-17 04:14 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>/glade/work/hplin/hco_inputdata/HEMCO_Config_FCnudged.CC.c230306.rc</hemco_config_file>
Thanks @nusbaume and @brian-eaton for the clarification!

I have modified the name of the config file to better clarify that it is compatible with other compsets, as well as changing some defaults for HEMCO extensions.
The new input file is located at `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.c230517.rc`. @fvitt, may I ask if it could be moved to `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis`? I'll update the path to a relative path in a commit once the file is moved.

Thank you!

2023-05-17 04:26 UTC, jimmielin commented on cime_config/testdefs/testlist_cam.xml
> +  <!--  Test of CAM-chem component sets with Harmonized Emissions Component (HEMCO) -->
Thanks! I moved the `ne30` case to `prealpha` from `aux_cam`.

2023-05-17 19:46 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
Would it be possible to only raise an error if a user has `use_hemco = .true.` and has also set `ext_frc_specifier` or `srf_emis_specifier` in `user_nl_cam`?  In my opinion @brian-eaton's solution would be the cleanest fix, but by throwing this extra error we might be able to better avoid the inevitable forum post where someone asks why their additions to `user_nl_cam` aren't working, as the removal of those chemistry inputs when HEMCO is being used might not be immediately obvious to some users.

2023-05-17 19:51 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
@nusbaume Are you suggesting a run time error when this occurs?  Checks can be added to the model that are exercised at init time.

2023-05-17 20:01 UTC, nusbaume commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
In an ideal world it would be nice to add this check somewhere in `build_namelist` or somewhere that would run this check whenever `preview_namelists` is run.  

However if that is not easily doable then I think a run time check is also fine.  I would rather kill the model at init time then have a user do a long model run just to find out that their emissions weren't what they thought they were.

2023-05-18 02:26 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
It is possible to do the check @nusbaume  suggests by adding code to `build-namelist` between where it processes the `user_nl_cam` input and where the use case input is processed (around line 408).  That check can't be done at runtime because `CAM` doesn't know what feature of `build-namelist` was used to add variables to the namelist.   If we decide to do this, we still need the fix I suggested above to remove the settings of `ext_frc_specifier` and `srf_emis_specifier` that are made by the use case files or constructed in `build-namelist`.

I'll volunteer to add this check if we decide that's what we want to do.  Also we should update the documentation for `ext_frc_specifier` and `srf_emis_specifier` in the namelist definition file to make it clear that these variables cannot be set when HEMCO is being used.

2023-05-18 16:00 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
I've been told that HEMCO is the way of the future.   If that is indeed the case, then perhaps all of our use_cases get revised to use HEMCO and then @brian-eaton's concern of doubling chemistry use_cases would be alleviated.  We can then have `build-namelist` error out if both `use_hemco = .true.` and either `ext_frc_specifier `or `srf_emis_specifier` are specified.

2023-05-18 17:50 UTC, cacraigucar requested changes

2023-05-18 17:50 UTC, cacraigucar commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            frcing(:ncol,k,m) = frcing(:ncol,k,m) + pbuf_ik(1:ncol,k) * kg_to_molec / ((zint(:ncol,k)-zint(:ncol,k+1)) * km_to_cm)
Perhaps I'm missing something, but I don't see that `m` is assigned to anything prior to this line

2023-05-18 17:50 UTC, cacraigucar commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +         hco_j_tmp_fld(:ncol) = reaction_rates(:ncol,pver,rxt_joh_idx)
This comment appears to be misleading as the code is just assigning the surface value

2023-05-18 17:55 UTC, cacraigucar commented
Also, before we do our final re-reviews, could this branch be merged to the head of cam_development, since there are merge conflicts indicated?

2023-05-19 00:20 UTC, brian-eaton commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +    hco_joh_idx  = pbuf_get_index('HCO_IN_JOH',errcode=err)
@cacraigucar, I think this code is OK.  This is the standard way to ask the pbuf whether or not a particular field is registered when you don't want the code to exit if the field isn't there.  And this call is made in the init subroutine rather than in `gas_phase_chemdr` where it is used (and where the "error" is handled) because the query is expensive.  So it gets done just once in `gas_phase_chemdr_init` and then the index is checked to be sure it's positive before it gets used.

2023-05-19 00:32 UTC, brian-eaton commented on src/chemistry/mozart/hco_cc_emissions.F90
> +        hco_pbuf_idx(n) = pbuf_get_index(fldname_ns, RC)
This code looks OK.  The pbuf indices (or the value -1 if the requested field isn't in the pbuf) are set in the init method `hco_extfrc_inti`, and checks are in place to verify the indices are positive before they are used in both `hco_set_srf_emissions` and `hco_set_extfrc`.

2023-05-19 00:57 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            frcing(:ncol,k,m) = frcing(:ncol,k,m) + pbuf_ik(1:ncol,k) * kg_to_molec / ((zint(:ncol,k)-zint(:ncol,k+1)) * km_to_cm)
Thanks for noticing, looks like this got wiped out by one of the code edits! I'll fix this.

2023-05-19 00:58 UTC, jimmielin commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +         hco_j_tmp_fld(:ncol) = reaction_rates(:ncol,pver,rxt_joh_idx)
Fixed, thanks!

2023-05-19 00:59 UTC, jimmielin commented on src/chemistry/mozart/mo_gas_phase_chemdr.F90
> +    ! all sub-mechanisms in CAM-chem
Yes, I have added more context to this comment. There are checks below for the index > 0 before populating relevant fields.

2023-05-19 01:00 UTC, jimmielin commented on src/chemistry/mozart/chemistry.F90
> +       ! (hplin, 8/8/22)
Thanks, removed.

2023-05-19 01:02 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +          endif
Thanks, this makes sense. I have removed the two extraneous checks.

2023-05-19 01:04 UTC, jimmielin commented
Thanks all for the reviewer comments. I will merge to the head of `cam_development` and run another set of checks to make sure everything is working as intended, then update back so final re-reviews can be done.

2023-05-23 21:48 UTC, jimmielin commented on src/chemistry/mozart/hco_cc_emissions.F90
> +            frcing(:ncol,k,m) = frcing(:ncol,k,m) + pbuf_ik(1:ncol,k) * kg_to_molec / ((zint(:ncol,k)-zint(:ncol,k+1)) * km_to_cm)
All fixed, thanks! 3-D emissions should be all fixed now.

2023-05-23 21:51 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
Hi @fvitt,

I've made an updated version of the input file for CAM-chem chemistry compsets at `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.c230517.rc`. Could you please help move this to `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis`? Thank you!

2023-05-23 21:58 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
> Hi @fvitt,
> 
> I've made an updated version of the input file for CAM-chem chemistry compsets at `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.c230517.rc`. Could you please help move this to `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis`? Thank you!

Done

2023-05-23 22:04 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
Thanks @fvitt! 
Sorry for the repeat ping, could you also move `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.c230523.rc` as well?

I'll update the compset XML shortly to point to the new files.

2023-05-23 22:26 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
> Thanks @fvitt! Sorry for the repeat ping, could you also move `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.c230523.rc` as well?
> 
> I'll update the compset XML shortly to point to the new files.

done

2023-05-24 03:14 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>HEMCO_Config.rc</hemco_config_file>
Thank you, relative path updated.

2023-05-24 03:15 UTC, jimmielin commented on bld/namelist_files/namelist_definition.xml
> +will be ignored.
Thank you, I have incorporated the changes from @brian-eaton in https://github.com/ESCOMP/CAM/pull/560/commits/52f7cf136437ee40caa5cb29669e1c2390bc8ad1.

2023-05-24 03:15 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hemco_config_file>/glade/work/hplin/hco_inputdata/HEMCO_Config_FCnudged.CC.c230306.rc</hemco_config_file>
Thank you, relative path in inputdata is now used for `hemco_config_file` default.

2023-05-24 14:19 UTC, brian-eaton approved these changes

2023-05-24 14:29 UTC, cacraigucar approved these changes

2023-05-25 15:28 UTC, fvitt commented
When mct coupling/mediator is used the ESMF lib is not generally available which causes build failures in the _Vmct regression tests, such as listed below.  One option is to stop testing mct.  Another is to set USE_ESMF_LIB = TRUE in these tests.
```
    FAIL ERC_D_Ln9_Vmct.T42_T42_mg17.FDABIP04.cheyenne_intel.cam-outfrq3s_usecase MODEL_BUILD time=4
    FAIL ERC_D_Ln9_Vmct.T42_T42_mg17.FHS94.cheyenne_intel.cam-outfrq3s_usecase MODEL_BUILD time=4
    FAIL ERP_D_Ln9_Vmct.f09_f09_mg17.QSC6.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=5
    FAIL ERP_D_Ln9_Vmct.f19_f19_mg17.QPC6.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=4
    FAIL ERP_Ln9_Vmct.f09_f09_mg17.2000_CAM60_CLM50%SP_CICE5%PRES_DOCN%DOM_MOSART_SGLC_SWAV.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=4
    FAIL SMS_D_Ln9_Vmct.T42_T42.2000_CAM60%SCAM_CLM50%SP_CICE5%PRES_DOCN%DOM_SROF_SGLC_SWAV.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=2
```
Thoughts?

2023-05-25 15:44 UTC, cacraigucar commented
> When mct coupling/mediator is used the ESMF lib is not generally available which causes build failures in the _Vmct regression tests, such as listed below. One option is to stop testing mct. Another is to set USE_ESMF_LIB = TRUE in these tests.
> 
> ```
>     FAIL ERC_D_Ln9_Vmct.T42_T42_mg17.FDABIP04.cheyenne_intel.cam-outfrq3s_usecase MODEL_BUILD time=4
>     FAIL ERC_D_Ln9_Vmct.T42_T42_mg17.FHS94.cheyenne_intel.cam-outfrq3s_usecase MODEL_BUILD time=4
>     FAIL ERP_D_Ln9_Vmct.f09_f09_mg17.QSC6.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=5
>     FAIL ERP_D_Ln9_Vmct.f19_f19_mg17.QPC6.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=4
>     FAIL ERP_Ln9_Vmct.f09_f09_mg17.2000_CAM60_CLM50%SP_CICE5%PRES_DOCN%DOM_MOSART_SGLC_SWAV.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=4
>     FAIL SMS_D_Ln9_Vmct.T42_T42.2000_CAM60%SCAM_CLM50%SP_CICE5%PRES_DOCN%DOM_SROF_SGLC_SWAV.cheyenne_intel.cam-outfrq9s MODEL_BUILD time=2
> ```
> 
> Thoughts?
Will this requirement that ESMF be compiled bleed over into all of the coupled (B compset) MCT tests which they may still be running?  If so, then we probably need to bring this up with CSEG and it might be that final push to remove MCT from CESM (and then also CAM).

If it is only impacting CAM (F compset) MCT cases, then my reasoning is as follows:

Our thoughts were that as long as CESM has MCT as an option, we should have a minimal set of tests to keep it tested.  I would suggest you add `USE_ESMF_LIB = TRUE ` to these tests.  If we have any CAM prealpha or prebeta MCT tests, add it to them as well.

2023-05-25 20:14 UTC, brian-eaton commented
@cacraigucar, I believe the requirement that ESMF be available will be true for all compsets that use CAM as the atm component.  That's because the decision was made to always build HEMCO, and it's building/linking the HEMCO code that is requiring ESMF whether or not it is being used for emissions.

2023-05-25 21:48 UTC, cacraigucar commented
@brian-eaton - That confirmed what I suspected.  

@fvitt - It looks like bringing in HEMCO is the time that CAM will no longer support MCT.  Please add the removal of the MCT tests from the CAM testlist in this PR.   @nusbaume and @peverwhee agreed with this decision.

2023-05-27 02:04 UTC, adamrher requested changes
I have provided my review, warts and all. I like the build-namelist logic from Brian and wish to get more clarity on the resolution of the source emissions files..

2023-05-27 04:55 UTC, jimmielin commented on src/chemistry/pp_none/chemistry.F90
> +  subroutine chem_emissions( state, cam_in, pbuf )
This is because `chem_emissions` can only have one subroutine signature and `mozart/chemistry.F90`'s `chem_emissions` (which has "actual" logic instead of stubs here) will pass the `pbuf` to `hco_set_srf_emissions` to set surface emissions based on HEMCO data stored in the physics buffer. So the same subroutine definition and arguments need to be copied to `pp_none` and `pp_terminator` as well.

2023-05-27 04:55 UTC, jimmielin commented on src/chemistry/pp_terminator/chemistry.F90
> +    use physics_buffer,   only: physics_buffer_desc
Same as above for `pp_none`:

> This is because `chem_emissions` can only have one subroutine signature and `mozart/chemistry.F90`'s `chem_emissions` (which has "actual" logic instead of stubs here) will pass the `pbuf` to `hco_set_srf_emissions` to set surface emissions based on HEMCO data stored in the physics buffer. So the same subroutine definition and arguments need to be copied to `pp_none` and `pp_terminator` as well.

2023-05-27 04:56 UTC, jimmielin commented on src/physics/cam_dev/physpkg.F90
> +    if(use_hemco) then
Fixed, thanks

2023-05-27 04:56 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +    if(use_hemco) then
Fixed, thanks.

2023-05-27 04:57 UTC, jimmielin commented on src/physics/cam/physpkg.F90
> +        ! initialize harmonized emissions component (HEMCO). this will add
Removed the additional comments as they're redundant with the comment in

```
    ! This needs to be last as it requires all pbuf fields to be added
    if (cam_snapshot_before_num > 0 .or. cam_snapshot_after_num > 0) then
        call pbuf_cam_snapshot_register()
    end if
```

below.

2023-05-27 05:00 UTC, jimmielin commented on bld/configure
> +#   MODEL_     - HEMCO/GEOS-Chem components running in model environment
Thanks for the concern. Could you please elaborate on "conflating HEMCO w/ a specific chemistry package"?

The fact that these CPP definitions are used (and GEOS-Chem is mentioned here) is because HEMCO and GEOS-Chem use the same CPP definition "conventions" for identifying their presence within an external model environment. `MODEL_` is the generic marker for coupling to an external model, and `MODEL_CESM` denotes specific features for CESM.

Perhaps it's just the comment that is not clear. I'm happy to revise it.

2023-05-27 05:03 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!-- Default emissions grid resolution at 2x2.5 degree: coarser may result in masking artifacts -->
Thank you so much for pointing this out. This is an arbitrary choice - and I really appreciate hearing about how the current workflow handles masking. 

If the default is `0.9x1.25` then I am happy to set the default to `288 x 201` (`0.9x1.25`), and also use the same for `1.9x2.5` since it does improve masking accuracy by a significant degree. Would that work?

2023-05-27 05:04 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<cam_physics_mesh hgrid="0.47x0.63">atm/cam/coords/fv0.47x0.63_esmf_c210305.nc</cam_physics_mesh>
Thanks! Ideally we would also have a good way to set `<hemco_grid_xdim>` and `<hemco_grid_ydim>` automatically... but `0.9x1.25` could be a sensible fallback default - but definitely higher resolutions may want separate definitions to ensure resolution is not wasted.

2023-05-27 05:05 UTC, jimmielin commented
Thanks for the review comments. I am awaiting upstream `geoschem/HEMCO` to incorporate @fvitt's updates to HEMCO for NAG compiler compatibility and tag a release, so I can incorporate the proper external. I will follow up on this early next week.

2023-05-27 15:00 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!-- Default emissions grid resolution at 2x2.5 degree: coarser may result in masking artifacts -->
I'm actually suggesting that the default emissions be as close to the native resolution of the dataset as possible, therefore when we run at higher-res than 1˚, and the default hemco emissions grid is invoked, that it will mitigate grid aliasing to 1˚-2˚ resolution. I am trying to channel the concerns of ACOM here, so maybe I'll bring @lkemmons in to verify that I'm not taking crazy pills. 

If you look at the MUSICA website, their offline emissions remapping workflow (which I presumed HEMCO was going to replace) maps from the native emissions grid to the target grid. These native grid resolutions vary depending on which emissions, but CAMS, CMIP and QFED are all higher than 1˚, up to 0.1˚. See more info here: https://wiki.ucar.edu/display/MUSICA/Regridding+emissions. 

Maybe the issue here is that HEMCO has an order of magnitude more emissions datasets, and that you're forced to choose a common resolution to represent them all? And since upscaling is ill-advised, you may be slave to the lowest resolution dataset in choosing this common resolution?

For the workhorse grids (0.9x1.25, ne30np4), I'm totally fine with the emission's being on this 201x288 grid (note that this grid isn't identical to 09x1.25, as that has 192x288 points)

2023-05-27 15:07 UTC, adamrher commented on bld/configure
> +#   MODEL_     - HEMCO/GEOS-Chem components running in model environment
got it. it is my understanding that all chemistry packages will need to conform to the same ccpp definitions, once we complete making CAM ccpp compliant. So the reference to GEOS-Chem here will not be unique at that point? 

I may not be understanding the exact issue here, so let me revisit this comment next week. My primary concern is really just that it be clear that hemco can be used for any arbitrary chemistry solver, and not tied to one.

2023-05-27 15:10 UTC, adamrher commented on src/chemistry/pp_none/chemistry.F90
> +  subroutine chem_emissions( state, cam_in, pbuf )
got it. just so you know, ccpp compliant CAM will not have a physics buffer. That is going to be one of the most difficult challenges of ccpp'izing CAM. So just letting you know; no action req'd.

2023-05-28 00:42 UTC, adamrher commented on bld/build-namelist
> +sub check_user_input {
resolving this convo b/c it doesn't need to be discussed in this PR.

2023-05-30 19:14 UTC, jimmielin commented on bld/configure
> +#   MODEL_     - HEMCO/GEOS-Chem components running in model environment
Thanks! HEMCO is not tied to any particular chemistry solver. It's just that we happened to use the same `MODEL_` and `MODEL_CESM` pre-processor constants as GEOS-Chem to delimit coupling-specific code in HEMCO.

2023-05-30 19:21 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!-- Default emissions grid resolution at 2x2.5 degree: coarser may result in masking artifacts -->
> I'm actually suggesting that the default emissions be as close to the native resolution of the dataset as possible, therefore when we run at higher-res than 1˚, and the default hemco emissions grid is invoked, that it will mitigate grid aliasing to 1˚-2˚ resolution.

Yes, I completely agree. the choice of default is rather tricky because of your later comment here:

> [edit - after thinking about this some more, I am going to flip-flop an agree that the default emissions grid should be coarse, and even 2˚ is fine by me, since we need to consider how this choice may or may not slow down the regression testing. Many of our tests use a coarse 10˚ grid for expediency, and so a coarse emissions grid makes sense for many of the regressions tests.

Which is why I chose 2-degree as a rather arbitrary choice between decent performance and not-too-distorted accuracy. We observe issues with masking at boundaries when using a 4x5 grid in GEOS-Chem standalone model (see Figure 3 in https://gmd.copernicus.org/articles/14/5487/2021/#section2) which is why I chose 2 degree to at least mitigate this by a little bit. But ultimately, the choice should be "as fine as possible, as long as the memory and compute supports it" which is a vague and moving answer...

I understand your note about "upscaling" - but that was not the main consideration, since most of the emissions are covered by CEDS which we load 0.5 degree files for in HEMCO right now, so it's not too restrictive. The other inventories are minor and usually 0.66 or 2 degree, so 2 degree is actually the 'worst case scenario' choice if we have to consider "upscaling".

Circling back to what we should do about this... How about we set `se_refined_mesh="1"` default resolution to be 0.5 or 1 degree, and leave the other defaults as-is? Would it be a good compromise?

2023-05-30 19:54 UTC, lkemmons commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!-- Default emissions grid resolution at 2x2.5 degree: coarser may result in masking artifacts -->
@adamher I hope that we can have the internal HEMCO emissions grid be as fine, or finer, than the final model grid. For example, if we want to run an ne30x8 (0.125 degrees) grid I would like to take advantage of any emissions inventories that are at 0.1 degree, for example, so would like the internal grid to be 0.1 degree.
Apologies if I misunderstand this issue.

2023-05-30 21:51 UTC, nusbaume approved these changes
My concern with the HEMCO config files has been resolved, so I am happy with this PR now assuming the NAG issues get fixed.  Thanks again for the new model infrastructure!

2023-05-30 23:01 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!-- Default emissions grid resolution at 2x2.5 degree: coarser may result in masking artifacts -->
@jimmielin how do you get the emissions onto the hemco grid? Is it the case that two mappings occur in order to get emissions on the target grid? 1) source->hemco grid mapping, and 2) hemco grid-> target mapping?

If so, I would suggest just setting ```se_refined_mesh="1"``` to a 0.5˚ grid for now to move this PR along, and then we can open a separate issue discussing how we can get HECMO to mimic a source->target mapping behavior that @lkemmons is advocating for.

2023-06-01 19:05 UTC, jimmielin commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!-- Default emissions grid resolution at 2x2.5 degree: coarser may result in masking artifacts -->
> how do you get the emissions onto the hemco grid? Is it the case that two mappings occur in order to get emissions on the target grid? 1) source->hemco grid mapping, and 2) hemco grid-> target mapping?
Yes. This was by design in order to allow for a separate HEMCO grid to exist when the model is running at low resolution but mapping at low resolution is undesirable.

> If so, I would suggest just setting se_refined_mesh="1" to a 0.5˚ grid for now to move this PR along
Thanks, I added a 0.5x0.625 default for `se_refined_mesh="1"`.

> and then we can open a separate issue discussing how we can get HECMO to mimic a source->target mapping behavior
Agreed. The HEMCO_CESM could should be flexible to accommodate this, but we need to write a regridder to get the source files directly onto the target grid. It would be very useful for the HEMCO community in general, especially for the UFS folks who are working on getting HEMCO in as well.

2023-06-01 19:07 UTC, jimmielin commented
Thanks all - I have updated HEMCO-CESM upstream to include the new tagged version with NAG fixes.

I am drafting the changes for the ChangeLog, but looking at the past changelog history it looks like it is written for a complete cam tag instead for a specific PR. I hope this is helpful:

```
===============================================================

Tag name:
Originator(s): jimmielin
Date: June 1, 2023
One-line Summary: Integration of Harmonized Emissions Component (HEMCO) as emissions infrastructure
Github PR URL: https://github.com/ESCOMP/CAM/pull/560

Purpose of changes (include the issue number and title text for each relevant GitHub issue):
 - Add HEMCO_CESM as interface between CAM to the Harmonized Emissions Component (HEMCO): https://github.com/ESCOMP/CAM/issues/504

Describe any changes made to build system:
 - Adds HEMCO build paths under src/hemco
 - Adds pre-processor constants MODEL_, MODEL_CESM, HEMCO_CESM, USE_REAL8 for use by HEMCO to identify it is running in the CESM model environment and requires 8-bit precision

Describe any changes made to the namelist:
 - cam_physics_mesh now is defined for all compsets instead of only for WACCMX ionosphere-enabled compsets
 - added %HEMCO component sets FC2000climo_HCO, FC2010climo_HCO, FCHIST_HCO, FCnudged_HCO, FCts2nudged_HCO, and FCSD_HCO that enable HEMCO by default
 - added use_hemco, hemco_config_file, hemco_emission_year, hemco_grid_xdim, hemco_grid_ydim for configuring HEMCO
 - ext_frc_specifier and srf_emis_specifier are ignored if use_hemco is true.


List any changes to the defaults for the boundary datasets: N/A

Describe any substantial timing or memory changes:

Code reviewed by: brian-eaton, cacragucar, nusbaume, fvitt, adamrher, lkemmons

List all files eliminated: N/A

List all files added and what they do:
A       src/chemistry/mozart/hco_cc_emissions.F90
          - Provides surface emissions and external forcing when HEMCO is enabled

List all existing files that have been modified, and describe the changes:
M       .gitignore
M       Externals_CAM.cfg
          - Adds HEMCO-CESM external

M       bld/build-namelist
M       bld/config_files/definition.xml
M       bld/namelist_files/namelist_defaults_cam.xml
M       bld/namelist_files/namelist_definition.xml
M       bld/namelist_files/use_cases/2000_cam6.xml
M       bld/namelist_files/use_cases/2000_trop_strat_vbs_cam6.xml
M       bld/namelist_files/use_cases/2010_cam6.xml
M       bld/namelist_files/use_cases/2010_trop_strat_vbs_cam6.xml
          - Refer to namelist changes

M       bld/configure
          - Refer to build changes
M       cime_config/config_component.xml
M       cime_config/config_compsets.xml
          - Adds %HEMCO compset modifier and _HCO compsets for CAM-chem compsets to enable HEMCO by default

M       cime_config/testdefs/testlist_cam.xml
          - Adds test for HEMCO on f09 in aux_cam and camchem_hco test sets, ne30 in prealpha and camchem_hco test sets to test CAM with HEMCO

M       src/chemistry/mozart/chemistry.F90
M       src/chemistry/mozart/mo_chemini.F90
M       src/chemistry/mozart/mo_gas_phase_chemdr.F90
M       src/chemistry/mozart/mo_setext.F90
          - Calls HEMCO-provided routines in hco_cc_emissions instead of existing set_srf_emissions and extfrc_set when HEMCO is enabled
          - Adds pbuf argument to chem_emissions subroutine as necessary for HEMCO-CESM interface to access pbuf to retrieve emissions computed by HEMCO

M       src/chemistry/pp_none/chemistry.F90
M       src/chemistry/pp_terminator/chemistry.F90
          - Subroutine arguments added pbuf for consistent definition as mozart/chemistry.F90

M       src/control/runtime_opts.F90
          - Read HEMCO namelist

M       src/physics/cam/phys_control.F90
          - Read use_hemco variable from physics namelist
          
M       src/physics/cam/physpkg.F90
M       src/physics/cam_dev/physpkg.F90
          - Call HEMCO routines in physics phase 2

If there were any failures reported from running test_driver.sh on any test
platform, and checkin with these failures has been OK'd by the gatekeeper,
then copy the lines from the td.*.status files for the failed tests to the
appropriate machine below.  All failed tests must be justified.

cheyenne/intel/aux_cam:

izumi/nag/aux_cam:

izumi/gnu/aux_cam:

CAM tag used for the baseline comparison tests if different than previous
tag:

Summarize any changes to answers, i.e.,
- what code configurations:
- what platforms/compilers:
- nature of change (roundoff; larger than roundoff but same climate; new
  climate):

If bitwise differences were observed, how did you show they were no worse
than roundoff?

If this tag changes climate describe the run(s) done to evaluate the new
climate in enough detail that it(they) could be reproduced, i.e.,
- source tag (all code used must be in the repository):
- platform/compilers:
- configure commandline:
- build-namelist command (or complete namelist):
- MSS location of output:

MSS location of control simulations used to validate new climate:

URL for AMWG diagnostics output used to validate new climate:

===============================================================
```

2023-06-01 20:47 UTC, fvitt commented
@jimmielin 
The ChangeLog draft seems fine for a start.  Please push it to your branch.
Are you okay with me pushing changes to your branch?  Or do you prefer that I point you to changes to my sandbox on cheyenne?  I have changes to `testlist_cam.xml` to remove MCT tests and will be making updates to `ChangeLog` to report the results of the regression tests.  Thanks.

2023-06-01 20:48 UTC, jimmielin commented
Thanks @fvitt, I'll push the ChangeLog to my branch.

Please feel free to make changes on my branch directly.

2023-06-01 21:12 UTC, fvitt commented
@jimmielin It looks like I don't have permissions to push to your fork/branch.
`ERROR: Permission to CESM-GC/CAM.git denied to fvitt.`

2023-06-01 21:35 UTC, adamrher approved these changes
It occurred to me that the ```cam_physics_mesh``` entires aren't exhaustive, but that is fine as this PR https://github.com/ESCOMP/CAM/issues/787 will generalize the code for all meshes, with Brian already assigned to it. So Im approving this PR.

2023-06-01 21:36 UTC, jimmielin commented
> @jimmielin It looks like I don't have permissions to push to your fork/branch. `ERROR: Permission to CESM-GC/CAM.git denied to fvitt.`

Sorry about that, please try now. I thought I granted access when creating the pull request but it doesn't seem like it went through, I just added you manually to `CESM-GC/CAM`. Thanks!

2023-06-02 20:52 UTC, fvitt commented
I am experiencing build failures with NAG compiled SCAM test on izumi:
 `SMS_D_Ln7_Vnuopc.T42_T42_mg17.QPSCAMC5.izumi_nag.cam-scmarm`

The compiler error messages are like:
```
Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 410: Inconsistent structure for arg 4 in call to NF_GET_ATT_INT
Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 478: Inconsistent structure for arg 4 in call to NF_GET_ATT_REAL
Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 546: Inconsistent structure for arg 4 in call to NF_GET_ATT_DOUBLE
Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 831: Inconsistent structure for arg 4 in call to NF_GET_ATT_INT
Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 888: Inconsistent structure for arg 4 in call to NF_GET_ATT_REAL
Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 945: Inconsistent structure for arg 4 in call to NF_GET_ATT_DOUBLE
```

NAG is complaining about how HEMCO is using Fortran77 netcdf interfaces.
@jimmielin Can HEMCO be updated to use Fotran90 netcdf interfaces?  

This SCAM test uses `nagfor` to compile the code rather than `mpif90`, as the other tests do.  This is because SCAM forces `MPILIB` to be `mpi-serial`.

I would like thoughts from the group on how to proceed.  We could try to implement a workaround such as don't force `MPILIB` to be `mpi-serial`, or move this test to `gnu`.  I think it would be best to update HEMCO.

2023-06-02 21:11 UTC, fvitt commented
`mpif90` includes the `-mismatch` nag compiler flag:
```
nagfor -mismatch -g -I/cluster/mvapich2-2.3.3-gcc-8.1.0-nag-6.2/include -I/cluster/mvapich2-2.3.3-gcc-8.1.0-nag-6.2/include -L/cluster/mvapich2-2.3.3-gcc-8.1.0-nag-6.2/lib -lmpifort -Wl,-Wl,,-rpath -Wl,-Wl,,/cluster/mvapich2-2.3.3-gcc-8.1.0-nag-6.2/lib -lmpi
```
I suspect that this is why the other NAG tests were able to build.

2023-06-02 21:19 UTC, cacraigucar commented
> I am experiencing build failures with NAG compiled SCAM test on izumi: `SMS_D_Ln7_Vnuopc.T42_T42_mg17.QPSCAMC5.izumi_nag.cam-scmarm`
> 
> The compiler error messages are like:
> 
> ```
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 410: Inconsistent structure for arg 4 in call to NF_GET_ATT_INT
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 478: Inconsistent structure for arg 4 in call to NF_GET_ATT_REAL
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 546: Inconsistent structure for arg 4 in call to NF_GET_ATT_DOUBLE
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 831: Inconsistent structure for arg 4 in call to NF_GET_ATT_INT
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 888: Inconsistent structure for arg 4 in call to NF_GET_ATT_REAL
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 945: Inconsistent structure for arg 4 in call to NF_GET_ATT_DOUBLE
> ```
> 
> NAG is complaining about how HEMCO is using Fortran77 netcdf interfaces. @jimmielin Can HEMCO be updated to use Fotran90 netcdf interfaces?
> 
> This SCAM test uses `nagfor` to compile the code rather than `mpif90`, as the other tests do. This is because SCAM forces `MPILIB` to be `mpi-serial`.
> 
> I would like thoughts from the group on how to proceed. We could try to implement a workaround such as don't force `MPILIB` to be `mpi-serial`, or move this test to `gnu`. I think it would be best to update HEMCO.

Do @lkemmons and others need this tag for Monday for the ASD work?  If so, we could move the NAG test to gnu and open an issue to fix this error properly and move the test back to NAG at that time.  If there is no need to have this tag by Monday, I would suggest we try to fix this properly at this time.  

@lkemmons - Can you let us know?

2023-06-02 22:10 UTC, lkemmons commented
I do not need this immediately.  I think it would be best to fix it
properly.


On Fri, Jun 2, 2023 at 3:19 PM cacraigucar ***@***.***> wrote:

> I am experiencing build failures with NAG compiled SCAM test on izumi:
> SMS_D_Ln7_Vnuopc.T42_T42_mg17.QPSCAMC5.izumi_nag.cam-scmarm
>
> The compiler error messages are like:
>
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 410: Inconsistent structure for arg 4 in call to NF_GET_ATT_INT
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 478: Inconsistent structure for arg 4 in call to NF_GET_ATT_REAL
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 546: Inconsistent structure for arg 4 in call to NF_GET_ATT_DOUBLE
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 831: Inconsistent structure for arg 4 in call to NF_GET_ATT_INT
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 888: Inconsistent structure for arg 4 in call to NF_GET_ATT_REAL
> Error: /home/fvitt/camdev/HEMCO-CESM_rebased_on_cam6_3_045/src/hemco/HEMCO/src/Shared/NcdfUtil/hco_m_netcdf_io_readattr.F90, line 945: Inconsistent structure for arg 4 in call to NF_GET_ATT_DOUBLE
>
> NAG is complaining about how HEMCO is using Fortran77 netcdf interfaces.
> @jimmielin <https://github.com/jimmielin> Can HEMCO be updated to use
> Fotran90 netcdf interfaces?
>
> This SCAM test uses nagfor to compile the code rather than mpif90, as the
> other tests do. This is because SCAM forces MPILIB to be mpi-serial.
>
> I would like thoughts from the group on how to proceed. We could try to
> implement a workaround such as don't force MPILIB to be mpi-serial, or
> move this test to gnu. I think it would be best to update HEMCO.
>
> Do @lkemmons <https://github.com/lkemmons> and others need this tag for
> Monday for the ASD work? If so, we could move the NAG test to gnu and open
> an issue to fix this error properly and move the test back to NAG at that
> time. If there is no need to have this tag by Monday, I would suggest we
> try to fix this properly at this time.
>
> @lkemmons <https://github.com/lkemmons> - Can you let us know?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/560#issuecomment-1574327582>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH5BH7JRHSUFSM2Q7DFZFLLXJJKGTANCNFSM5STEFIPA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-02 22:15 UTC, cacraigucar commented
@lkemmons - Thanks for letting us know

@fvitt - I am going to go ahead and let other tags be made in front of this PR, until it is ready.

2023-06-03 01:12 UTC, brian-eaton commented
@fvitt, I'm leaning towards your proposal to not force the `MPILIB` to be `mpi-serial`.  `mpi-serial` was often a problem.  If we stop building `MCT` then it goes away.  Do we have an option for an mpi serial library with ESMF?

2023-06-05 13:33 UTC, fvitt commented
> @fvitt, I'm leaning towards your proposal to not force the `MPILIB` to be `mpi-serial`. `mpi-serial` was often a problem. If we stop building `MCT` then it goes away. Do we have an option for an mpi serial library with ESMF?

The failing test uses NUOPC coupling.  So, presumably the option of using mpi-serial with ESMF has been supported.

2023-06-05 14:53 UTC, cacraigucar commented
> > @fvitt, I'm leaning towards your proposal to not force the `MPILIB` to be `mpi-serial`. `mpi-serial` was often a problem. If we stop building `MCT` then it goes away. Do we have an option for an mpi serial library with ESMF?
> 
> The failing test uses NUOPC coupling. So, presumably the option of using mpi-serial with ESMF has been supported.

I believe that as long as we support `mpi-serial` we should not remove this test.  Also, since HEMCO is going to be an integral part of all CAM runs as we move forward with it, that also gives importance to keeping this test.  As I said before, I am okay with opening an issue on this and addressing it in a not-too-distant PR.  It sounded like @lkemmons was okay with taking the time to try to solve this now.  @fvitt - I leave this up to you whether you solve this now or in the next month or so - your call.  Just let me know when you are ready to make the tag, and I can let you know the timing of tags at that point.  This tag will move in as soon as whatever tag is in preparation is made (if there is one at that time).

2023-06-05 19:55 UTC, jimmielin commented
> NAG is complaining about how HEMCO is using Fortran77 netcdf interfaces.
@jimmielin Can HEMCO be updated to use Fotran90 netcdf interfaces?

Thanks @fvitt for catching these errors. It looks like nagfor is not happy with the Fortran 77 interfaces for calls like

```fortran
status = Nf_Get_Att_Int( fId, vId, attName, attValue )

status = Nf_Get_Att_Real( fId, vId, attName, attValue )

status = Nf_Get_Att_Double( fId, vId, attName, attValue )

status = Nf_Get_Att_Text( fId, NF_GLOBAL, attName, attValue )
```

Not sure what the Fortran 90 equivalents are, I'll look it up and PR the upstream HEMCO repository for a fix.

2023-06-05 20:38 UTC, jimmielin commented
Hi @fvitt, it might take us a significant amount of time to migrate the F77 interfaces to F90 since the GEOS-Chem Support Team is short-staffed and it'll involve a lot of work in the netCDF utilities code we use. Given this is not really a bug and it's just F77 netCDF interface peculiarities, is there any way we can apply `-mismatch` to this source file in particular? Thanks!

2023-06-05 21:57 UTC, fvitt commented
@jimmielin The changes for fotran90 netcdf are in branch/fork https://github.com/fvitt/HEMCO/tree/3.6.2-cesm_netcdf
This will build with `nagfor`.

Please update HEMCO to use fotran90 netcdf when you are able to.

I will remove the `serial-mpi` setting as it has caused problems in other areas in CESM.  Thus the `-mismatch` flag will be applied to the NAG build and the test should pass.

2023-06-06 03:46 UTC, fvitt approved these changes

2023-06-06 14:48 UTC, lkemmons approved these changes
Thanks everyone for all your work on this!

2023-06-06 19:38 UTC, jimmielin commented
Tracking it down now. There might be issues with restarts in HEMCO if PEs are switched, I'm verifying the results to make sure nothing unexpected was introduced. Will update back

2023-06-07 04:06 UTC, jimmielin commented
Thanks @cacraigucar, @fvitt. I downgraded the test to ERS (test restart only) or PEM (test PEs only) but still could not match bit-for-bit, although the difference is smaller, so there may be a mix of underlying issues causing the ERP tests to fail. Because HEMCO seems to return slightly different (~1e-4 order relative) results to the external forcing fields this propagates to all chemistry species, but I think the relative difference is acceptable as an 'alpha' version feature for now while we track it down.

I am unsure whether it's an issue with the regridder (in HEMCO-CESM) or an restart issue further upstream in HEMCO. I'll have to debug further to chase down the exact issue, so we might have to mark this as a known bug for now and I'll work on addressing this in the next HEMCO update.

Also, I had a question about test sets. What are the `SMS_` tests doing exactly? The documentation says "Smoke tests" and I couldn't find any further explanation of what they do. Some of the `camchem` tests use SMS instead.

2023-06-07 17:56 UTC, fvitt commented
@jimmielin @cacraigucar 
Should we change the HCO test to SMS_ ?
I am thinking of moving it to:
 ```
SMS_D_Ln9_Vnuopc.f09_f09_mg17.FCSD_HCO.cheyenne_intel.cam-outfrq9s
```
Or maybe a lower res test:
```
SMS_D_Ln9_Vnuopc.f19_f19_mg17.FC2000climo_HCO.cheyenne_intel.cam-outfrq9s
```
Otherwise, baselines and restart test will fail for future tags till the restart issue is fixed.

2023-06-07 18:04 UTC, cacraigucar commented
> @jimmielin @cacraigucar Should we change the HCO test to SMS_ ? I am thinking of moving it to:
> 
> ```
> SMS_D_Ln9_Vnuopc.f09_f09_mg17.FCSD_HCO.cheyenne_intel.cam-outfrq9s
> ```
> 
> Or maybe a lower res test:
> 
> ```
> SMS_D_Ln9_Vnuopc.f19_f19_mg17.FC2000climo_HCO.cheyenne_intel.cam-outfrq9s
> ```
> 
> Otherwise, baselines and restart test will fail for future tags till the restart issue is fixed.

I am tempted to recommend two tests:  An SMS test which we expect to pass and keeping the ERP test as a known failure.  My reasoning is that it is crucial to get the ERP test working before we adopt HEMCO throughout CAM, so we don't want this failure to get forgotten.

2023-06-07 18:10 UTC, jimmielin commented
Thanks @fvitt and @cacraigucar. I was speaking with @lizziel earlier and we are aware of potential issues with precision within HEMCO (some areas use `r4` while most uses `r8`) that could lead to issues with BFB match and it is planned to be addressed soon. 

However, I'm testing the `SMS` test right now but I'm getting a failure somewhere, which is concerning to me and I would like to hold this PR if possible for a day or two while I try to track down the source of the differences. At the very least I want to make sure it is not code introduced in the HEMCO-CESM interface or within this PR - so we can consolidate the BFB issues upstream at the HEMCO level and file the issue in the appropriate place.

Sorry for the troubles! I'll update back as I make more progress.

2023-06-07 18:26 UTC, fvitt commented
@jimmielin  I am okay with waiting.  @cacraigucar may want to move ahead with other tags.

2023-06-08 18:59 UTC, jimmielin commented
Thanks, I was able to get the `SMS` tests to pass by tuning the SMM pipeline depth in `ESMF_FieldRegridStore` to `16` in HEMCO-CESM.

I am trying to see if this fixes the `ERP` tests as well, or there are other underlying causes. Once I confirm I will update the HEMCO-CESM external with the fixes.

2023-06-09 06:25 UTC, jimmielin commented
Hi @fvitt, could you please copy this new configuration file to input data `atm/cam/geoschem/emis/`? The path is:
`/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.NEx.c230608.rc`. Thank you!

I've made some fixes to HEMCO-CESM as well as to the configuration file to ensure BFB match under the `SMS` test, and merged up to `cam_development` head.

To remind myself that `ERP` and `ERS` are not yet fixed, I've kept these as separate tests so it is easier to isolate issues as well. I've arranged these as:
* `SMS_Lh12_Vnuopc.f09_f09_mg17.FCSD_HCO.cheyenne_intel.cam-outfrq3h` under `aux_cam` and `camchem_hco`, and we know this should pass;
* `ERS_Ln9_Vnuopc.f09_f09_mg17.FCSD_HCO.cheyenne_intel.cam-outfrq9s` under `camchem_hco` to test exact restarts (which should be fixed before `ERP` is fixed), known failure;
* `ERP_Ln9_Vnuopc.f09_f09_mg17.FCSD_HCO.cheyenne_intel.cam-outfrq9s` under `aux_cam`, `prealpha`, and `camchem_hco`, known failure.

It'll be a priority for us to get ERS and ERP fixed asap.

I also moved tests to `FCSD_HCO` instead of `FCnudged_HCO`. I am unable to get identical outputs from the exact two same runs in `FCnudged_HCO`. All regridded results from HEMCO (and output from HEMCO history fields) appear to be the same, but other areas in CAM(-chem) show differences as reported in logs:

```
15723c15723
<  nstep, te        5   0.26133468717376633E+10   0.26133480444684682E+10   0.64996984756607461E-04   0.98520561561018985E+05   0.22552395239472389E+03
---
>  nstep, te        5   0.26133468717422619E+10   0.26133480444683876E+10   0.64996725418133629E-04   0.98520561561185226E+05   0.22552395239472389E+03
15972c15972
<  nstep, te        6   0.26135753775186563E+10   0.26135761857487063E+10   0.44795048362129934E-04   0.98520529982337990E+05   0.22552395239472389E+03
---
>  nstep, te        6   0.26135753796915398E+10   0.26135761878709807E+10   0.44792243419964037E-04   0.98520529984882698E+05   0.22552395239472389E+03
16220c16220
< Global flash freq (/s), lightning NOx (TgN/y) =    19.9091    2.2034
---
> Global flash freq (/s), lightning NOx (TgN/y) =    19.9095    2.2034
```

The `nstep, te` output comes from `src/physics/cam/check_energy.F90`. I'm not sure why these errors are there but I will check in the morning if this is an issue pre-existing within `FCnudged`.

2023-06-09 14:05 UTC, fvitt commented
> @fvitt, could you please copy this new configuration file to input data `atm/cam/geoschem/emis/`? The path is:
> `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.NEx.c230608.rc`

The new config file has been copied to 
```
/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/HEMCO_Config.CC.CEDS_AEIC19.NEx.c230608.rc
```

2023-06-09 15:46 UTC, cacraigucar commented
Perhaps a README could be placed in the `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis` directory that contains the mandatory metadata that we typically place in netCDF files.  

See https://www2.cesm.ucar.edu/working_groups/Atmosphere/amwg_datasets.html  for the fields

2023-06-09 15:50 UTC, jimmielin commented
Thanks @cacraigucar for the suggestion. The HEMCO data files include a README including documentation for the file processing workflow as well, and this is standard for all HEMCO data sets. e.g., `/glade/p/univ/umit0034/ExtData/HEMCO/CEDS/v2020-08/README` describe the CEDS inventory data processing, `/glade/p/univ/umit0034/ExtData/HEMCO/GFED4/v2020-02/README` for GFED4, etc.

I wonder how we can merge this into `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis`. Perhaps, the `README` could include the relative paths for the README files in the enabled emission inventories and relevant documentation.

2023-06-09 20:09 UTC, jimmielin commented
With the fixes in the latest commit(s) I can get `SMS` test to pass. I also verified that change in `NTHRDS` will match BFB (so it's not an OpenMP issue), but not `NTASKS` - something is up with the MPI in regridding in HEMCO_CESM that has to be investigated more closely.

If possible, I suggest moving forward by keeping the `SMS` test (known to pass) and mark `ERP` as a known failure. I will continue investigating the restart and MPI issues and resolve them as soon as possible, as we have similar concerns for HEMCO in the GEOS-Chem standalone model.

2023-06-14 17:55 UTC, fvitt commented
I have ran a few tests for the HCO compets multiple times.  ERS and ERP tests consistently fail.  BASELINE tests do not consistently pass for me.   Should we keep both the SMS and ERP on the aux_cam test list if the BASELINE tests are not consistently passing?

I would like to test HEMCO on izumi with the nag compiler. However, I have discovered the the HEMCO configuration files have hard wired paths that are specific to cheyenne. Thus the HCO compsets are not portable to other machines without modifications to the hemco config files.

2023-06-14 18:07 UTC, cacraigucar commented
We need to fix the configuration files so that they run on any platform.  We do not knowingly commit something to CAM which only runs on cheyenne.

2023-06-14 18:22 UTC, jimmielin commented
Hi @fvitt, @cacraigucar, is there any way I can obtain the absolute path of `inputdata` at runtime?

There are two relevant lines in the HEMCO configuration file that need to be revised:
```
ROOT:                        /glade/p/univ/umit0034/ExtData/HEMCO
...
DiagnFile:                   /glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/HEMCO_Diagn.3_5_0.c230307.rc
```

We can solve this by:
* Changing the HEMCO configuration file handling so that a token (maybe `{CESM_INPUTDATA}`) can be replaced by the correct `inputdata` path (`/glade/p/cesmdata/cseg/inputdata`) at runtime. 
* Soft-linking `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/ExtData/HEMCO` to `/glade/p/univ/umit0034/ExtData/HEMCO` so the full set of HEMCO input files is accessible as a path from `inputdata`. The files in `/glade/p/univ/umit0034/ExtData/HEMCO` may be too large to host under `cesmdata/cesg/inputdata` for now. I think we have not decided yet how these files will be maintained in coordination between the CESM and GEOS-Chem communities (the full dataset is currently hosted at WUSTL at http://geoschemdata.wustl.edu/ExtData/HEMCO/)

2023-06-15 15:19 UTC, jimmielin commented
Thanks @fvitt, I can work on this now. Just to confirm:

> The absolute paths will be set at build-namelist time.

If I set `hemco_data_root` as a relative path in the default (e.g., `atm/cam/geoschem/emis/ExtData/HEMCO`) and set it up with `input_pathname="abs"` in the definition, the namelist generation will transform this to an absolute path (`/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/ExtData/HEMCO`), is that correct? 

Then it should be easy for me to make HEMCO_CESM provide that to HEMCO instead.

I'll add two namelist variables, `hemco_data_root` and `hemco_diagn_file` (named consistently with `hemco_config_file`).

> It would be nice if there is a minimal set of HEMCO input files for CAM-Chem that can be easily downloaded to other machines. 

We've explored this idea before but didn't go through. I will look at some reasonable defaults for the compsets we added. Probably still need a few years worth of data, hopefully a within a few GBs.

2023-06-15 15:27 UTC, fvitt commented
> If I set `hemco_data_root` as a relative path in the default (e.g., `atm/cam/geoschem/emis/ExtData/HEMCO`) and set it up with `input_pathname="abs"` in the definition, the namelist generation will transform this to an absolute path (`/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/ExtData/HEMCO`), is that correct?

Correct.  For an example see `"Nudge_Path"` in `bld/namelist_files/namelist_definition.xml`.

2023-06-15 18:59 UTC, jimmielin commented
Thanks @fvitt, I have added these features into HEMCO-CESM and updated the external version to `hemco-cesm1_2_0_hemco3_6_2_cesm`. The namelist variables `hemco_data_root` and `hemco_diagn_file` will control the root data directory and diagnostics file location, so they will be machine-agnostic.

1. I have created a new version of the HEMCO configuration file at `/glade/work/hplin/hco_inputdata/HEMCO_Config.CC.CEDS_AEIC19.NEx.c230615.rc` (note it doesn't have any Cheyenne-specific paths now). Could you please copy it to `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis`?

I think these old files can also be deleted now:
```
-r--r--r-- 1 fvitt cseg 534910 May 23 15:57 HEMCO_Config.CC.CEDS_AEIC19.c230517.rc
-r--r--r-- 1 fvitt cseg 534933 May 23 16:25 HEMCO_Config.CC.CEDS_AEIC19.c230523.rc
-r--r--r-- 1 fvitt cseg 534933 Jun  9 08:02 HEMCO_Config.CC.CEDS_AEIC19.NEx.c230608.rc
-r--r--r-- 1 fvitt cseg 534910 Mar  7 15:27 HEMCO_Config_FCnudged.CC.c230306.rc
-r--r--r-- 1 fvitt cseg 534910 Mar  7 15:27 HEMCO_Config_FCnudged.CC.interp.c230307.rc
```

So we just keep `HEMCO_Config.CC.CEDS_AEIC19.NEx.c230615.rc` and `HEMCO_Diagn.3_5_0.c230307.rc`.

2. For the new data root to work, `/glade/p/univ/umit0034/ExtData/HEMCO` has to be linked from `/glade/p/cesmdata/cseg/inputdata/atm/cam/geoschem/emis/ExtData/HEMCO`. The extra folder `ExtData` is intentional to keep the folder hierarchy consistent with GEOS-Chem data conventions.

3. I will work on finding a minimal set of data that works at least to run the `_HCO` compsets out of the box and update back soon.

Thanks!

2023-06-16 08:19 UTC, gold2718 commented
Sorry for the late question but I've been wondering if all this work has to be done at run time.
If the config file could be parsed at build namelist (cime_config/buildnml) time, the files for the _current run_ could be identified and added to Buildconf/cam.input_data_list. Then the usual process (check_input_data) would find the files in various servers (the WUSTL server could easily be added) to make sure they are available for the run. Finding the files at runtime would then be easier, similar to how other files are found and opened in CESM.
Is this a completely dumb idea?

2023-06-16 15:30 UTC, jimmielin commented
Hi @gold2718, thanks for the comment - that is a great idea and something we want to move towards. However it's probably not feasible at the moment.

The current infrastructure for HEMCO to identify necessary files for the run is a "dry-run" option which will go through all the time steps and simulate the read of files (only checking if they exist) and printing out a list of present/not present. But this currently relies on the GEOS-Chem model to drive this and there's no lightweight version of this program.

We could also parse the configuration file directly, but it would take time to develop, and we have plans to move to YAML or other open formats in the future, so we don't want to develop this for the current config file format which will be superseded soon.

So definitely in the future we want to integrate into `check_input_data` by having a script to parse the HEMCO config file & the namelists and list the necessary files, but the infrastructure is not ready yet. So we have to do this juggling at run time at the moment.

2023-07-07 01:26 UTC, brian-eaton commented
@fvitt, I think this error is due to including the attribute `input_pathname="abs"` in the namelist definition.  If you remove that then that variable won't be put into the list of input datafiles.

2023-07-07 14:19 UTC, jimmielin commented
Hi @brian-eaton, would `build-namelist` still automatically make it an absolute path if `input_pathname="abs"` is removed? We specify `<hemco_data_root>atm/cam/geoschem/emis/ExtData/HEMCO</hemco_data_root>` in `namelist_defaults_cam.xml` so its relative to inputdata. Thanks!

2023-07-07 14:21 UTC, jimmielin commented
Hi @fvitt, may I ask if this definition look correct for specifying this as a relative path to inputdata? It looks like `check_input_data` is attempting to look for a file but this is a path. Maybe I configured this wrong.

```
<entry id="hemco_data_root" type="char*256" input_pathname="abs" category="hemco"
       group="hemco_nl" valid_values="" >
Full pathname of HEMCO data root for use in reading HEMCO input files. (e.g., 'atm/cam/geoschem/emis/ExtData/HEMCO').
Default: set by build-namelist.
</entry>
```

2023-07-07 14:28 UTC, fvitt commented
@jimmielin and @brian-eaton 
I needed to create a link to `/glade/p/univ/umit0034/ExtData`.
I think we should keep `input_pathname="abs"` in the `hemco_data_root` definition so that the check happens.

2023-07-07 14:43 UTC, brian-eaton commented
@fvitt, you're right.  I forgot how the variables that specify a root filepath work.

2023-07-10 14:24 UTC, fvitt commented
@jimmielin @lkemmons @cacraigucar 
If there are no objections I would like to move forward with merging this into cam_development with the understanding that HEMCO will not supported until the restart/reproducibility issues are resolved.

2023-07-10 17:01 UTC, lkemmons commented
I have no objections.


On Mon, Jul 10, 2023 at 8:24 AM Francis Vitt ***@***.***>
wrote:

> @jimmielin <https://github.com/jimmielin> @lkemmons
> <https://github.com/lkemmons> @cacraigucar
> <https://github.com/cacraigucar>
> If there are no objections I would like to move forward with merging this
> into cam_development with the understanding that HEMCO will not supported
> until the restart/reproducibility issues are resolved.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/560#issuecomment-1629084756>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH5BH7NXT5ECW67VPEY2D43XPQGBRANCNFSM5STEFIPA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-17 15:00 UTC, fvitt approved these changes

2023-07-17 15:00 UTC, merged