PUMAS GPU regression test suite
ESCOMP/CAM pull request #577
Opened 2022-04-20 16:48 UTC by sjsprecious

This PR introduces a new regression test suite for the GPU-enabled PUMAS codes, which works on Casper.

There is no source code change here but just a few xml files. It also requires the updated `CICE5/CICE6/CIME/ccs_config` modules to work properly.

This regression test suite includes five different ERP tests:
- CAM run with MG2, default namelist
- CAM run with MG3, default namelist
- CAM run with MG3, change the MG logical variables from their default values to the opposite values
- CAM run with MG3, default namelist, different PCOLS values
- CAM run with MG3, default namelist, different number of GPUs per node

Previously I made some GPU changes and somehow the CAM run could finish but return wrong results. The latter two new tests are able to detect those unexpected NBFB changes quickly before doing an ECT test and therefore I add them to the test suite.

To generate a baseline for this GPU regression test suite on Casper, use the following commands:

- `cd /path_to_CAM_main_dir/test/system`
- `module load python/3.7.9`
- `env BL_TESTDIR='' CAM_ACCOUNT=YOUR_PROJECT_ID CAM_FC=nvhpc-gpu CIME_MACHINE=casper ./test_driver.sh --cesm casper_gpu --baseline-dir /path_to_save_baseline -f
`

To perform a GPU regression test against the baseline generated above, use the following commands:
- `env BL_TESTDIR=/path_to_save_baseline CAM_ACCOUNT=YOUR_PROJECT_ID CAM_FC=nvhpc-gpu CIME_MACHINE=casper ./test_driver.sh --cesm casper_gpu --no-baseline -f`

The status of the regression test could be viewed through the following commands:
- `cd /glade/scratch/$user/casper_gpu`
- `./cs.status.casper_gpu_nvhpc-gpu_xxxx`, where `xxxx` is the time stamp for this test run

Ideally we should observe `PASS` for all the output from the command above. However, I saw `FAIL` for the `COMPARE_base_rest` and there were 4 different fields in the cpl restart file. I later ran the ERP test for the PUMAS CPU codes on Casper and got the same error. However, if I switched the `ERP` test to `ERS` test and re-ran it with PUMAS GPU codes, there was no `FAIL` in the output. Thus I think the error message here is not caused by the PUMAS GPU codes but I do not know how to fix this issue.

Code review: @gold2718 @cacraigucar @andrewgettelman @johnmauff

2022-04-24 19:00 UTC, gold2718 approved these changes
Couple of comments but otherwise, looks good!

2022-04-24 19:00 UTC, gold2718 commented on cime_config/testdefs/testmods_dirs/cam/outfrq9s_mg2_default/shell_commands
> +./xmlchange ROOTPE_CPL='0'
For future reference, `xmlchange` recognizes these variables as categories so you can replicate this behavior with:
```suggestion
./xmlchange NTASKS=36
./xmlchange NTHRDS=1
./xmlchange ROOTPE='0'
```

2022-04-24 19:00 UTC, gold2718 commented on test/system/test_driver.sh
> +    if [ -n "${BL_TESTDIR}" ] && [ ! -d "${BL_TESTDIR}" ]; then
Nice catch! I guess folks were not running this with a blank value for `BL_TESTDIR`.

2022-04-24 19:08 UTC, gold2718 requested changes
On second thought, I would like a chance to see your ChangeLog entry (can be before you have final test data).

2022-04-24 21:03 UTC, sjsprecious commented on cime_config/testdefs/testmods_dirs/cam/outfrq9s_mg2_default/shell_commands
> +./xmlchange ROOTPE_CPL='0'
Thanks @gold2718. I just updated all the `shell_commands` files with your suggestions.

2022-04-24 21:04 UTC, sjsprecious commented on test/system/test_driver.sh
> +    if [ -n "${BL_TESTDIR}" ] && [ ! -d "${BL_TESTDIR}" ]; then
Thanks! That is exactly how I find out this issue and I hope I am not the only one using an empty `BL_TESTDIR`.

2022-04-28 15:20 UTC, cacraigucar approved these changes

2022-04-28 16:03 UTC, nusbaume approved these changes
Looks good to me!  Just one possible typo.

2022-04-28 16:03 UTC, nusbaume commented on test/system/test_driver.sh
> +       ## Would fail to compile on Casper with long foler name
Possibly a typo here (`foler`)?

2022-04-28 16:16 UTC, peverwhee approved these changes

2022-04-28 16:33 UTC, sjsprecious commented on test/system/test_driver.sh
> +       ## Would fail to compile on Casper with long foler name
Thanks @nusbaume for catching it. Just fix the typo!

2022-04-30 00:54 UTC, peverwhee commented
this was brought in with #581

2022-04-30 00:54 UTC, closed without merging