PUMAS remove pack/unpack code from interface layer
ESCOMP/CAM pull request #580
Opened 2022-04-22 19:51 UTC by cacraigucar

Closes #254

2022-04-27 21:08 UTC, nusbaume requested changes
Looks pretty good!  However, I do have some change requests and questions that need addressing.  Also, please note that most of the changes I requested are needed for both versions of `micro_pumas_cam.F90`, even though I only listed them once.  Of course if you have any questions or concerns with my requests just let me know.  Thanks!

2022-04-27 21:14 UTC, cacraigucar commented on cime_config/SystemTests/sct.py
> +            stat,DIFFs,err=run_cmd('ncdump -ff -p 9,17 -v QDIFF,TDIFF '+netcdf_filename+' | egrep //\.\*DIFF | sed s/^\ \*// | sed s/^0,/0.0,/ | sed s/^0\;/0.0\;/ | sed s/\[,\;\].\*// |  uniq')
Yes, this is issue #556.  I don't have that it closes this issue as whoever has the next tag will be bringing in this issue.  I needed it to get one of my regression tests to pass.

2022-04-27 21:22 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      allocate(qsatfac(ncol,pver))
Added

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
The reason that it is set to `pver` is probably more a result of me trying to get this PR to work than anything else.  Inside micro_mg1_0.F90 and micro_pumas_data.F90, they have `pver`.  But since it is being passed in instead of "used", it could conceivably be any value.  I decided since they actually used the name `pver`, that I would treat it as such.   I would suggest that if we not pass in `pver`, that `pver` in PUMAS also be renamed to something other than `pver`.  I would request that this be opened as an issue if you feel like it is an important change and we defer it to later.

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc%q(:ncol,:,1) = qvlat(:ncol,:)
Agreed, there are probably a number of "cleanup" issues which could be addressed.   I approached this PR as the minimal changes required to remove the pack/unpack.  Since this was in the original code this way, I would suggest leaving it as is for now.  Do you agree?  @gold2718 - what are your thoughts on here and the other place that @nusbaume has suggested for code cleanup?

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
>                " but micro_pumas_tend has ice number tendencies.")
Same comment as before as to not modifying the code beyond what is needed for pack/unpack removal.  This change I would be okay with making as it is limited in scope and would not make the code harder to see the actual changes due to pack/unpack differences.  I'd like to hear @gold2718 opinion on these code cleanup changes.

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc_mpdq = ptend_loc%q(:,:,1)
Let's see what @gold2718 has to say on these cleanup issues

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
@Katetc - can you answer this?  I assumed that it was because either the physics_ptend_sum might change the answer or physics_update zeroes out the ptend_loc structure.  I assumed since @Katetc took the time to add this, there was a reason for it, but I did not investigate.

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +   if (qsatfac_idx == 0) then
Agreed - the check should be identical as to that used for the allocate.  Fixed

2022-04-27 23:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      ! If we are NOT progronosing ice and snow tendencies, then get them from the Pbuf
Fixed

2022-04-27 23:13 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +    prect  = 0._r8
Good catch - I removed all of them except for the nan_array which actually needs it.

2022-04-27 23:23 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc%q(:ncol,:,1) = qvlat(:ncol,:)
This would be a good item to add now (i.e., this PR) as part of general code cleanup that has been lacking here (partially due to the complexity of dealing with the pack / unpack code).

2022-04-27 23:23 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
>                " but micro_pumas_tend has ice number tendencies.")
This would be a good item to add now (i.e., this PR) as part of general code cleanup that has been lacking here (partially due to the complexity of dealing with the pack / unpack code).

2022-04-27 23:24 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc_mpdq = ptend_loc%q(:,:,1)
This should be part of the previous `ixq` change.

2022-04-28 21:41 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc%q(:ncol,:,1) = qvlat(:ncol,:)
Added here and in cam_dev

2022-04-28 21:41 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
>                " but micro_pumas_tend has ice number tendencies.")
Done

2022-04-28 21:42 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc_mpdq = ptend_loc%q(:,:,1)
Fixed here and numerous other places in this routine and cam_dev

2022-04-28 21:57 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
I looked into physics_update and I've confirmed that when it is called, the ptend_loc structure has all of its elements deallocated at the end of the routine.  Since these three fields are being output later in the code after the final num_steps has been iterated, they need to be copied.  I believe this is preferable to calling outfld multiple times and overwriting those fields on each iteration of num_steps before the physics_update is called.

2022-05-02 21:10 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
@cacraigucar Thanks for looking into it!  However, in this case couldn't one just use the PUMAS output variables (`tlat`, `qvlat`, and `qcten`) directly? 

Also, the way the code is currently written implies that the instantaneous tendency on the last `micro_mg_num_steps` sub-step is what is written to the history file.  Is that behavior correct, or should it be summed over the total number of sub-steps as is done for `ptend`?  I realize this question is probably more for @Katetc .

2022-05-03 15:19 UTC, andrewgettelman commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
I'm not sure what is being asked. PUMAS itself operates on everything it is handed (there is no top_lev in the microphysics, just nlev). I guess pver == nlev in the microphysics itself. So the microphysics should just get what levels the model wants it to operate on. I don't know if we are passing it everything or not. Sorry: I don't know an easy way to look at the code from the PR page.

2022-05-03 15:36 UTC, andrewgettelman commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
This is a chronic issue. There is no answer but I think I would prefer the instantaneous tendency is output from the last sub-step. Not summed.

2022-05-03 15:40 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
@andrewgettelman you can find a copy of the source code file on cheyenne/casper here:

`/glade/work/nusbaume/SE_projects/code_reviews/cacraig_CAM/src/physics/cam_dev/micro_pumas_cam.F90`

Basically there is a `top_lev` variable throughout the code that appears to limit some of the input and output variables related to PUMAS, but PUMAS itself is taking the entire column.  So my question is if PUMAS is wasting time processing microphysical tendencies at altitudes that then won't be used in the rest of CAM, or if the model should be processing the entire column, and thus maybe `top_lev` shouldn't be used at all?  Of course it may also be correct as-is.  

Mostly I just wanted to ask if there is a possible mismatch in this code related to `top_lev`, and if so then if we should make an issue so that we remember to deal with it later.

2022-05-03 15:43 UTC, andrewgettelman commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
Top lev is used I believe throughout the physics. So we don't want the microphysics working above it (since CLUBB doesn't for example). So I think it is correct. This did cause issues in the code that I think Kate and Cheryl had to deal with carefully. So they may be able to comment further. 

I have not looked at the code (and do not have time today). But can try to look later this week if we cannot resolve it.

2022-05-03 15:54 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
@andrewgettelman Thanks for the explanation!  In that case though it sounds like the variables being passed into PUMAS should be limited by `top_lev`, as otherwise PUMAS will be doing work on levels that then aren't used in CAM.  

I will wait to hear from @Katetc in case I am still missing something, but if she is ok with it then I'll go ahead and make the issue so we can deal with it later.

2022-05-03 21:42 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
I am a little confused as to how this works. PUMAS is still using Fortran 77 arrays (e.g., `t(mgncol,nlev)`) while CAM is passing in full-height Fortran 95 arrays `state_loc%t(:ncol,:)`.  Currently, the packer takes the levels from `top_lev` to `pver`.
If we pass in all the levels, won't PUMAS see the levels between `1` and `nlev` where `nlev = pver - top_lev + 1`?

2022-05-03 22:00 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
@gold2718 - No, while the entire array is being passed in,  we are also passing in `ncol` and `pver` for the two dimensions.   Would you propose that we try passing in `ncol`, and using `nlev` instead where `nlev= pver -top_lev +1`?   As I said at the beginning of this discussion, it was one of the many changes I tried to get these updates to work.  It may be that it turned out to be an unnecessary change.

2022-05-03 23:13 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
This gets at @andrewgettelman's comment that "So we don't want the microphysics working above it". This version will force PUMAS to work from the top of the atmosphere on down.

The only "quick fix" is to replace the colon, e.g., `state_loc%t(:ncol,top_lev:)` and pass in `nlev` instead of `pver`.

However, I am more in favor of updating PUMAS to use Fortran 90 arrays and explicitly passing in top_lev (or better yet, both a top_lev and a bot_lev). That would provide the ability to pass in continuous arrays in all situations and CAM can easily adjust its calls after (if) that update is made.

For now, I recommend the "quick fix" above.

2022-05-04 02:51 UTC, andrewgettelman commented
Re-ran my analysis on the latest pack-unpack code from Cheryl. Figure attached. Two pairs of nearly identical lines: one set with CAM physics and FV the other set with CAMDEV physics in SE.  The pairs look the same: so the pack/unpack is good.

[zm_npackV2_diff_2yr.pdf](https://github.com/ESCOMP/CAM/files/8617640/zm_npackV2_diff_2yr.pdf)


Also: I am using cam6_3_055 for the control: not sure if Cheryl updated the tag. It doesn't matter in the end. Looks good.

I also checked the variables like MPDICE that were giving trouble in the earlier version: and they look fine as well.

So all good from my side.

2022-05-04 17:56 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
I think I understand how we got here. In the pack/unpack version of the code, there was a call to `call post_proc%accumulate()` which did sum variables over the steps. That explains why the variables existed and why the had the `target` attribute (required by the packer system). Knowing that, I think we are okay removing these as all those variables are no longer accumulated. This includes pbuf variables uwed in other routines. Does that sound right?

2022-05-04 21:06 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
These three variables are the exception and I believe they DO need to remain. They store the values for the last tendency of t, q, and liq.  There is no other way to output these tendencies as they are destroyed at the time physics_update is called.  The target attribute has been removed.

2022-05-04 22:17 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
Well, out of all the izumi regression tests, there is one failure after implementing the "quick fix" as described by @gold2718 .  It is the QPWmaC6 test and it is giving "state%t has invalid value -3.369e+08 at location[6]".   It also says "ERROR Invalid value produced in physics_state by package clubb".   I've run this test twice and I get the same error message (though the values may change).  I will investigate, but welcome any "guesses".  Since this is a WACCM run, I guess I shouldn't be surprised that it is having an issue based on the changes I made.  BTW, I did verify that this job runs fine using the previous version without this mod, so these changes appear to the be the cause of the problem.  Also, I did try initializing `tlat(:ncol,:top_lev-1)=0._r8` and that did not fix the problem.

2022-05-05 03:18 UTC, andrewgettelman commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
I'm lost. So the 'quick fix' doesn't work, but the original version works? It's WACCM, so top_lev may be set differently. I think the intent was to have PUMAS operate on everything it gets. From the code currently in the repo, it gets nlev (which I assume is all levels) and I assume the packed fields are also all levels? 

Seems obvious from the error that there are random/garbage temperature values at some top level?  I don't think passing nlev and top_lev: is going to work since len(top_lev:) ≠ nlev?  Isn't nlev = number of levels? Or did I miss something.

2022-05-05 04:31 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
The packer also packed levels so that only the levels between `top_lev` and `pver` were passed to PUMAS.
`top_lev` is always `trop_cloud_top_lev`.
I have not seen Cheryl's latest code but if she is passing in `state_loc%t(:ncol,top_lev:)` then she needs to pass in `nlev = pver - top_lev + 1` instead of `pver`.

2022-05-05 15:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
I pushed the changes which limit the levels passed to PUMAS (but fails with the WACCM run).  I have several ideas I will explore today.

2022-05-05 15:43 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
@cacraigucar That is true for the `ptend_loc` variables, but I don't think it's true for the direct PUMAS outputs (e.g. `tlat`).  So I think you can just use those outputs (`tlat`, `qvlat`, and `qcten`) directly in the `outfld` calls, like what is done for `qiten`, and not have to use these extra local variables.

I realize this is all sort of nit-picky, but given that the model's memory footprint seems to be a major issue at high-resolution I figure we should take every chance we get to remove un-necessary variables.

2022-05-05 16:47 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +                 microp_uniform, ncol, pver, ncol, 1, dtime/num_steps, &
Initializing the PUMAS output variables above top_lev has solved the failing WACCM test!  I'm currently rerunning the izumi regression tests.

2022-05-05 19:53 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), target :: ptend_loc_mpdliq(state%psetcols,pver)
Removed.  @Katetc If there was a reason you introduced these variables which we didn't see, please let us know

2022-05-05 21:42 UTC, nusbaume approved these changes
Looks great now, thanks!  Just found one last minor issue.

2022-05-05 21:42 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +   call outfld('MPDLIQ',      ptend_loc%q(:,:,ixcldliq), psetcols, lchnk, avg_subcol_field=use_subcol_microp)
I think the `ptend_loc` references here needs to be replaced with `qvlat` and `qcten`, respectively (in order to avoid the deallocation issue you mentioned previously).

The same holds for `cam_dev` as well.

2022-05-05 22:21 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +   call outfld('MPDLIQ',      ptend_loc%q(:,:,ixcldliq), psetcols, lchnk, avg_subcol_field=use_subcol_microp)
Of course!  Dumb mistake on my part :-(

2022-05-06 16:45 UTC, fvitt commented
Don't think I need to review this.

2022-05-06 19:18 UTC, andrewgettelman approved these changes
Took a quick look. This looks fine to me if it passes the tests. Thanks!

2022-05-06 22:09 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +        rhog, &
This is silly but the indentation here is weird and confusing. Can we realign these only calls to be more organized?

2022-05-06 22:12 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
>     type(physics_state),         intent(in)    :: state
While we are cleaning up white space, it would be nice to add a bit of separation and maybe even a comment between the use statements and the parameter list here.

2022-05-06 22:14 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> -
Just wanted to say I love seeing all this red in this PR!!

2022-05-06 22:14 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +        rhog, &
Combined lines 1367 and 1368 in both cam and cam_dev versions.  Will be in next push.

2022-05-06 22:16 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +        rhog, &
What is your suggestion? My preference is to just not have continuation lines in `use` statements:
```
use micro_pumas_utils, only: size_dist_param_basic, size_dist_param_liq
use micro_pumas_utils, only: mg_liq_props, mg_ice_props, avg_diameter
use micro_pumas_utils, only: rhoi, rhosn, rhow, rhows, rhog, qsmall, mincld
```

2022-05-06 22:26 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
>     type(physics_state),         intent(in)    :: state
Blank line added in both version of this code.  Will be in next push

2022-05-06 22:55 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +        rhog, &
Adopted Steve's suggestion

2022-05-07 00:43 UTC, gold2718 approved these changes
I think this is okay to go although I have a couple of questions.
Also, the PR description only shows Jian's comment, there is no description of what the PR does.

2022-05-07 00:43 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +      re_ice => nan_array
Is this really necessary or would setting them to `NULL()` work as well?

2022-05-07 00:43 UTC, gold2718 commented on src/physics/cam/micro_pumas_cam.F90
> +      ptend_loc%q(:ncol,:,ixnumliq) = ncten(:ncol,:)
This does extra copying, could be trimmed.
```suggestion
      ptend_loc%s(:ncol,top_lev:) = tlat(:ncol,top_lev:)
      ptend_loc%q(:ncol,top_lev:,ixq) = qvlat(:ncol,top_lev:)
      ptend_loc%q(:ncol,top_lev:,ixcldliq) = qcten(:ncol,top_lev:)
      ptend_loc%q(:ncol,top_lev:,ixcldice) = qiten(:ncol,top_lev:)
      ptend_loc%q(:ncol,top_lev:,ixnumliq) = ncten(:ncol,top_lev:)
```
There are similar issues below.

2022-05-07 01:15 UTC, peverwhee approved these changes
looks good to me!

2022-05-07 16:12 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +      re_ice => nan_array
I couldn't remember, so I tried removing the nan_array and pointing to NULL instead.  When I do that, I get "Attempt to use pointer TND_QSNOW when it is not associated with a target" on cheyenne.  I will be restoring the nan_array

2022-05-08 19:06 UTC, merged