Bring in Issue Templates
ESCOMP/CAM pull request #587
Opened 2022-05-03 01:00 UTC by peverwhee

This is a PR to the **main branch** - adds the issue templates for all branches.

closes #586

2022-05-03 14:15 UTC, nusbaume commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://bb.cgd.ucar.edu/cesm/forums/ctsm-clm-mosart-rtm.134/
I think this URL should be:

```suggestion
    url: https://bb.cgd.ucar.edu/cesm/forums/cam.133/
```

2022-05-03 21:38 UTC, cacraigucar requested changes
My requested changes were submitted using the new templates as issues in Courtney's repo.

2022-05-03 21:44 UTC, gold2718 commented
> My requested changes were submitted using the new templates as issues in Courtney's repo.

That does not leave a record that any of us can easily see (or are even permanent since we do not even know what issues you are talking about). Please document your concerns and questions here.

2022-05-03 22:06 UTC, cacraigucar requested changes
@goldy - I was exercising the templates to get the feel for them.  I've included for posterity sake my requests here.  

My last request was:

For all of the issues, could the question "Will you be implementing this yourself" be added? If the answer is yes, can the assignee be assigned to the user who is opening the issue?

2022-05-03 22:06 UTC, cacraigucar commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: File a bug report - for CAM developers' use only (all other users should use the CESM forum)
@peverwhee Added my suggestion of augmenting the description here

2022-05-03 22:06 UTC, cacraigucar commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://bb.cgd.ucar.edu/cesm/forums/cam.133/
I pointed this out, and then saw that Jesse had the same comment

2022-05-03 22:13 UTC, peverwhee commented
@cacraigucar Thanks Cheryl!

To answer your question, yes I will add the "Will you be implementing this yourself" question to the other templates; however, I don't believe that selections within the template can trigger changes to other elements of the template. I added text to instruct the user to assign herself if applicable.

2022-05-03 22:14 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: What CAM tag you were using
good call -updated

2022-05-03 22:14 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://bb.cgd.ucar.edu/cesm/forums/ctsm-clm-mosart-rtm.134/
that it should! changed!

2022-05-03 22:15 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +        - "No"
added.

2022-05-03 22:15 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/other.yml
> +      multiple: false
updated.

2022-05-03 22:21 UTC, peverwhee commented
Also: @cacraigucar would we prefer the "Will you be implementing this __ yourself?" be required? It's currently not.

2022-05-03 22:40 UTC, cacraigucar commented
> Also: @cacraigucar would we prefer the "Will you be implementing this __ yourself?" be required? It's currently not.

Sure - it gives us one more clue on who might implement this and that is important.

2022-05-03 23:51 UTC, gold2718 approved these changes
Some musings. Not sure if changes are required or just suggested.

2022-05-03 23:51 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/other.yml
> +      description: If yes, please also add the "answer changing" label
Do you need triage level access to do this? If so, perhaps, we want to add a "if possible" disclaimer.

2022-05-03 23:51 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/other.yml
> +      description: If Yes, please also assign this issue to yourself
Do you need triage level access to do this? If so, perhaps, we want to add a "if possible" disclaimer.

2022-05-03 23:51 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      description: If Yes, please also assign this issue to yourself
Do you need triage level access to do this? If so, perhaps, we want to add a "if possible" disclaimer.

2022-05-03 23:51 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      description: If yes, please also add the "answer changing" label
Do you need triage level access to do this? If so, perhaps, we want to add a "if possible" disclaimer.

2022-05-03 23:51 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      label: Will this change answers?
In some sense, if it changes answers it is not an enhancement but a bug fix or science change. An enhancement should include a way to have it off by default and turn it on via a new namelist variable.

2022-05-03 23:51 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: If Yes, please also assign this issue to yourself
Do you need triage level access to do this? If so, perhaps, we want to add a "if possible" disclaimer.

2022-05-05 05:48 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/other.yml
> +      description: If yes, please also add the "answer changing" label
added!

2022-05-05 05:48 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/other.yml
> +      description: If Yes, please also assign this issue to yourself
added!

2022-05-05 05:49 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      description: If Yes, please also assign this issue to yourself
added!

2022-05-05 05:49 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      description: If yes, please also add the "answer changing" label
added!

2022-05-05 05:49 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: If Yes, please also assign this issue to yourself
added!

2022-05-05 05:50 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      label: Will this change answers?
That is an interesting point. Since a science change/discussion also uses this template, I'm leaning towards leaving this? But I could add some additional text in the description about this.

Thoughts @cacraigucar and @nusbaume ?

2022-05-05 15:26 UTC, gold2718 commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      label: Will this change answers?
I guess we should be more clear about the information we really want here. Internal to CAM, an enhancement, including most science changes, should come with a default configuration that does not change answers for regression tests. This allows scientists and SEs to dissect the causes of various changes to simulations. Perhaps a better wording here is:
```suggestion
      label: Will this change regression-test answers?
```

2022-05-05 16:51 UTC, cacraigucar approved these changes

2022-05-06 19:35 UTC, peverwhee commented on .github/ISSUE_TEMPLATE/enhancement_request.yml
> +      label: Will this change answers?
added clarifying language

2022-05-06 19:35 UTC, merged