High priority science updates for mom6 coupled runs and fixes for issues #506 #530 #543 #551 #563
ESCOMP/CAM pull request #590
Opened 2022-05-06 20:22 UTC by jtruesdal

This is a misc tag encompassing high priority updates for MOM6 coupled runs (reference AMWG discussion issue 98 
 https://github.com/NCAR/amwg_dev/issues/98#issuecomment-1094076161) as well as fixes for the following issues:
- Noise in derived quantities in ne30pg3 configuration #551
- nvfortran fails to compile MPAS-A dycore due to generic operator interface issues #563 
- Divide-by-zero bug on cam_dev L58 grid when DEBUG=TRUE #543 
- bug: sponge layer extends to surface in low top (z=~10km) setup #530
- F2000dev bombs out for finite-volume dycores (FV and FV3) #506 

closes #551 
closes #563
closes #543 
closes #530 
closes #506

2022-05-10 19:22 UTC, cacraigucar requested changes

2022-05-10 19:22 UTC, cacraigucar commented on src/physics/cam_dev/physpkg.F90
> +    if (moist_mixing_ratio_dycore) call set_dry_to_wet(state)    ! Physics had dry, dynamics wants moist
Does this addition need to be added to src/physics/cam/physpkg.F90 as well?  I believe we are trying to keep them the cam and cam_dev versions of physpkg.F90 as identical as possible.

2022-05-10 19:26 UTC, adamrher commented on src/physics/cam_dev/physpkg.F90
> +    if (moist_mixing_ratio_dycore) call set_dry_to_wet(state)    ! Physics had dry, dynamics wants moist
no, it is in physics/cam/phspkg.F90, and I accidentally deleted it when I was creating physics/cam_dev/physpkg.F90. So John is just putting it back in.

2022-05-11 18:05 UTC, jtruesdal commented on doc/ChangeLog
> +  ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPC6.izumi_nag.cam-outfrq3s_am (Overall: PASS)
Will Do.

2022-05-11 18:14 UTC, jtruesdal commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +     ! pre-compute reference temperature profile (Simmons and Jiabin, 1991, QJRMS, Section 2a)
done.

2022-05-11 18:25 UTC, cacraigucar approved these changes

2022-05-11 22:28 UTC, peverwhee approved these changes

2022-05-12 15:53 UTC, nusbaume requested changes
Looks good, but I have a couple questions that I would like to have answered before approving.  Thanks!

2022-05-12 15:53 UTC, nusbaume commented on src/dynamics/se/dyn_comp.F90
> +         press = (hvcoord%hyam(k)+hvcoord%hybm(k))*hvcoord%ps0
Should this be changed to:

```
press = hvcoord%hyam(k)*hvcoord%ps0+hvcoord%hybm(k)*pstd
```

In order to match the pressure values printed above?

2022-05-12 17:35 UTC, nusbaume commented on src/dynamics/se/dyn_comp.F90
> +         nu_scale_top(k) = 8.0_r8*(1.0_r8+tanh(1.0_r8*log(ptop/press(1)))) ! tau will be maximum 8 at model top
@PeterHjortLauritzen Right!  I totally missed that.  Thanks for the explanation!

2022-05-12 17:45 UTC, nusbaume commented on src/physics/cam/zm_conv.F90
> +
@swrneale Sounds good!  I just wanted to double-check.

2022-05-12 23:05 UTC, fvitt approved these changes

2022-05-13 04:55 UTC, jtruesdal commented on doc/ChangeLog
> +  - map PHIS from GLL to physics grid in dp_coupling
Good catch.  I'll remove it.

2022-05-13 04:55 UTC, jtruesdal commented on doc/ChangeLog
> +  - replace inadvertently deleted line converting dry mixing rations to wet
will correct.

2022-05-13 05:04 UTC, jtruesdal commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +     T1 = lapse_rate*Tref*cpair/gravit
Can that possibly still be true?  It's hard to believe that modern compilers don't optimize that away.  Personally I think /gravit is more clear than *rga.  Unless this is a sticking point I would say leave it.

2022-05-13 05:16 UTC, jtruesdal commented on src/dynamics/se/dyn_comp.F90
> +         press = (hvcoord%hyam(k)+hvcoord%hybm(k))*hvcoord%ps0
modified as suggested.

2022-05-13 18:20 UTC, nusbaume commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +     T1 = lapse_rate*Tref*cpair/gravit
My understanding is that the only time you can guarantee that optimization is occurring is if you use a specific compiler flag for it, or if you use the `-Ofast` optimization option, neither of which we use (to my knowledge) when building CAM, at least by default.  

That being said, I do think you are correct that the compiler will do it "sometimes" with less aggresive optimizations, so I have no idea if we can generally assume it is being done or not.  Maybe @briandobbins knows? 

Regardless, after looking over the code again I realized that this calculation is only being done once, so I agree that any performance gain would likely be trivial.  Thus I am happy to leave this as-is.

2022-05-13 18:20 UTC, nusbaume approved these changes
Looks great now, thanks!

2022-05-16 08:30 UTC, gold2718 approved these changes
Looks good but please make the few minor changes indicated.

2022-05-16 08:30 UTC, gold2718 commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    else if (ptop>1e-1_r8) then
Real literals should include a decimal point (to avoid confusing static code checkers).

2022-05-16 08:30 UTC, gold2718 commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    else if (ptop>1E-4_r8) then
Real literals should include a decimal point (to avoid confusing static code checkers).

2022-05-16 08:30 UTC, gold2718 commented on doc/ChangeLog
> + https://github.com/ESCOMP/CAM/pull/XXX
```suggestion
 https://github.com/ESCOMP/CAM/pull/590
```

2022-05-16 08:30 UTC, gold2718 commented on doc/ChangeLog
> +Code reviewed by: TBD
```suggestion
Code reviewed by: swrneale, PeterHjortLauritzen, adamrher, fvitt, cacraigucar, peverwhee, nusbaume, gold2718
```

2022-05-16 23:48 UTC, merged