Add capability for SCAM forcing based on gridded met fields. Connected to issue #594.
ESCOMP/CAM pull request #595
Opened 2022-05-20 17:34 UTC by JulioTBacmeister

This capability currently requires pre-computed gridded fields on FV latlon 1 degree grid

Have run a number of cases using this capability - can provide user_nl_cam as well path to gridded ERA reanalysis.

Have also run with this capability is off and standard SCAM IOPs. Answers *look* fine but have not done rigorous testing.

2022-05-25 19:25 UTC, jtruesdal commented
@JulioTBacmeister could you add @jtruesdal as a developer on your repo if it's OK for me to make changes to this branch for the PR.

2022-05-25 20:20 UTC, JulioTBacmeister commented
@jtruesdal I've made you a collaborator and github implies you should have received an invite of some sort. Let me know if I should do something else.

2022-05-26 22:11 UTC, peverwhee commented
@JulioTBacmeister @jtruesdal 

Jim Edwards came across the following when debugging our CICE/SCAM issues:

Because the namelist variable **scm_ana_frc_file_template** is a template rather than an actual file, this message appears when you build:

> Model cam missing file scm_ana_frc_file_template = '%y/ERAI_fv09_L58.cam2.i.%y-%m-%d-%[s.nc](http://s.nc/)'

To avoid this, we may need a change to CAM's buildnml so that this isn't written to the
Buildconf/cam.input_data_list

2022-05-27 15:49 UTC, JulioTBacmeister commented
Yes. I've noticed this message.  The model nevertheless builds and runs without issues.  This should have also come up when the nudging code was incorporated - it uses a similar template.

2022-05-27 16:15 UTC, peverwhee commented
> Yes. I've noticed this message. The model nevertheless builds and runs without issues. This should have also come up when the nudging code was incorporated - it uses a similar template.

Gotcha. I'll open a low-priority issue for the nudging message.

2022-05-27 21:38 UTC, peverwhee commented
@JulioTBacmeister @jtruesdal 

OK, bringing this up again because it looks like the logic can handle the nudging template file because it does not see it as an absolute path (and thus we do not get the warning). Because of the "%y/" at the start of the scm_ana_frc_file_template file, we get the warning for this new variable.

If you replace line 4405 in bld/build_namelist with the following (to not write the variables whose pathnames start with '%' to the cam.input_data_list file), it should remove the warning:

```
if (!($pathname =~ '%.*') {
    print $fh "$var = $pathname\n";
}
```

I'm also happy to make a PR to your branch with this change.

Thanks!

2022-05-27 22:19 UTC, JulioTBacmeister commented
I made the change in build_namelist on my branch and pushed it to origin.  Would you check it?

2022-05-27 23:23 UTC, peverwhee commented
@JulioTBacmeister Looks good to me. Sorry my code snippet was missing a parenthesis! Thanks!

2022-05-28 06:55 UTC, gold2718 requested changes
Suggested approach to problem with pathnames.

2022-05-28 06:55 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +</entry>
This variable is a string, not a filename (path), therefore, it should not have the `input_pathname` attribute. I believe this is the source of the build-namelist problems.

2022-05-28 06:55 UTC, gold2718 commented on bld/build-namelist
> +                            print $fh "$var = $pathname\n";
I do not think this should be needed (see below) and could have unintended effects.

2022-06-08 19:11 UTC, peverwhee commented
@nusbaume @cacraigucar and I recommended (via email) that Julio remove the shell scripts and ncdata file from the scam_STUB usermods directory. Documenting that here.

XML variables set in the shell script(s) can be set in scam_STUB/shell_commands and variables written to user_nl_cam can be added to scam_STUB/user_nl_cam

2022-06-08 20:48 UTC, cacraigucar commented
@JulioTBacmeister and @adamrher - Is this Stub IOP another IOP which we want to support?  If so, I would suggest that the user_nl_cam and shell_commands be put in cime_config/usermods_dirs/scam_Stub_IOP or something like that.  You can see what was done for cime_config/usermods_dirs/scam_arm97 as an example.  @jtruesdal may be able to give some addtional guidance as he's done this more recently than I have.

2022-07-27 16:32 UTC, cacraigucar commented on Externals_CAM.cfg
> +tag = clubb_4ncar_20220311_f51de38/src/SILHS
@JulioTBacmeister - Are these changes really needed for your SCAM PR?  Hopefully you can use the tags that are currently being used in CAM instead

2022-07-27 16:43 UTC, JulioTBacmeister commented on Externals_CAM.cfg
> +tag = clubb_4ncar_20220311_f51de38/src/SILHS
I want to use the "new" CLUBB external brought in with cam6_3_059.  This is so that we can assess prognostic momentum transport using SCAM.

2022-07-28 21:10 UTC, JulioTBacmeister commented
Superseded by PR #628

2022-07-28 21:10 UTC, closed without merging