Improvements to WACCMX AMIE/LTR high-latitiude potential input readers
ESCOMP/CAM pull request #596
Opened 2022-05-20 22:49 UTC by fvitt

Improvements to WACCMX AMIE/LTR high-latitiude potential input readers

 - Use time_coordinate time interpolation utility in LTR and AMIE modules
 - Do not assume grid dimension sizes for LTR/Gamera inputs
 
closes #562 
closes #592

2022-06-07 21:51 UTC, cacraigucar commented on src/chemistry/utils/input_data_utils.F90
> +             call endrun('time_coordinate%initialize: input file must contain time or date variables '//trim(filepath))
Does this error message need to be refined?  This is not checking any time fields at this point, but rather `date` or `month`/`day`/`year`.

2022-06-07 21:51 UTC, cacraigucar commented on src/chemistry/utils/input_data_utils.F90
> +          ierr = pio_get_var( fileid, varid, year )
What happens if `year` does not exist in the file, and the pio_get_var is called with whatever is returned in varid?  Does it run without failing, or do you need to check ierr after each of these calls, instead of once at the end of this section?

2022-06-07 21:51 UTC, cacraigucar commented on src/chemistry/utils/input_data_utils.F90
> +          dates(:) = year(:)*10000 + month(:)*100 + day(:)
Since year, month and day are not initialized and error codes are not being checked, the caluculation of dates could conceivably be using just random stack data.  Even worse if the file contained `day`, but not  `month` or `year`, then this incorrect value could be used later in the code.

2022-06-07 22:47 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +             call endrun('time_coordinate%initialize: input file must contain time or date variables '//trim(filepath))
I tried to improve on this.

2022-06-07 22:48 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +          ierr = pio_get_var( fileid, varid, year )
I added error checking here.

2022-06-07 22:49 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +          dates(:) = year(:)*10000 + month(:)*100 + day(:)
Good point. I tried to improve the error checking in this section.

2022-06-07 22:50 UTC, cacraigucar commented on src/chemistry/utils/input_data_utils.F90
> +             call endrun('time_coordinate%initialize: input file must contain time or date variables '//trim(filepath))
Much better - thanks

2022-06-07 22:50 UTC, cacraigucar approved these changes

2022-06-08 20:27 UTC, gold2718 requested changes
Please fix incorrect call to `pio_seterrorhandling`.

2022-06-08 20:27 UTC, gold2718 commented on doc/ChangeLog
> + WACCMX time interpolation fix for multiple day AMIE input file #562 #562
Why are issue numbers repeated?

2022-06-08 20:27 UTC, gold2718 commented on doc/ChangeLog
> +Describe any substantial timing or memory changes:
Please mark these as NA so we know you did not forget to fill them out.

2022-06-08 20:31 UTC, cacraigucar commented on doc/ChangeLog
> + WACCMX time interpolation fix for multiple day AMIE input file #562 #562
I can probably answer this one - For the new "improved" github project pages, I added the # to the title of a few issues and PRs so that they would show up on the page.  I suspect Francis just copied the title as it appears (with it appearing a second time).

2022-06-09 01:50 UTC, nusbaume approved these changes
Looks good to me (assuming Steve's concerns are addressed)!  Otherwise just some small minor stuff.

2022-06-09 01:50 UTC, nusbaume commented on src/ionosphere/waccmx/ltr_module.F90
> +  use input_data_utils, only : time_coordinate
I might replace `only :` with `only:` to better match the CAM coding standards.

2022-06-09 14:20 UTC, peverwhee approved these changes

2022-06-09 16:17 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +             write(iulog,*) prefix//'model calendar '//trim(model_calendar)// &
Is there a problem with concat?  I used the concatenations to construct the error strings the way I want them to appear in the log files.  I am not sure how comma separated strings will appear with the "*" format.

2022-06-09 16:18 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +          ierr = pio_get_var( fileid, varid, dates )
Thanks for the tip.  I will make the change.

2022-06-10 13:21 UTC, fvitt commented on doc/ChangeLog
> + WACCMX time interpolation fix for multiple day AMIE input file #562 #562
fixed

2022-06-10 13:21 UTC, fvitt commented on doc/ChangeLog
> +Describe any substantial timing or memory changes:
done

2022-06-10 13:21 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +          ierr = pio_get_var( fileid, varid, dates )
done

2022-06-10 13:21 UTC, fvitt commented on src/chemistry/utils/input_data_utils.F90
> +             ierr = pio_get_var( fileid, varid, ut )
done

2022-06-10 13:22 UTC, fvitt commented on src/ionosphere/waccmx/amie_module.F90
> +  use input_data_utils, only : time_coordinate
done

2022-06-10 13:22 UTC, fvitt commented on src/ionosphere/waccmx/ltr_module.F90
> +  use input_data_utils, only : time_coordinate
done

2022-06-13 17:05 UTC, gold2718 commented on src/chemistry/utils/input_data_utils.F90
> +             write(iulog,*) prefix//'model calendar '//trim(model_calendar)// &
Concatenation requires creation of a new string and copying. It is a (minor) hit and I have seen no examples where the `*` format produces a different result (in either case, the run-time system is free to break up strings across lines as it sees fit).

Have you seen different results between a concatenated string vs. multiple argument output?

2022-06-14 13:42 UTC, merged