cleaning up clubb bugs, misc clubb issues
ESCOMP/CAM pull request #598
Opened 2022-05-25 17:30 UTC by adamrher

Fixes https://github.com/ESCOMP/CAM/issues/278 https://github.com/ESCOMP/CAM/issues/336 https://github.com/ESCOMP/CAM/issues/496 https://github.com/ESCOMP/CAM/issues/497

2022-05-25 17:36 UTC, adamrher commented
@Katetc @JulioTBacmeister @bstephens82 @swrneale I'd say about half of the CLUBB outfld vars are incorrectly assigned to "ilev" when they are technically on the "lev". This is because in clubb, the midpoint grid contains pverp entries, just like the interface grid, because there is a ghost point in the subsurface. 

Does everyone agree with putting these outfld vars on the correct grid? Or leave it as it is?

2022-05-25 17:42 UTC, JulioTBacmeister commented
I think the CLUBB output should be on the correct grid.

2022-05-25 17:46 UTC, Katetc commented
Does that mean we won't output the ghost point? That's probably fine. I can't remember if it was ever important. Be careful with the array truncation code, that's an easy thing to get weird seg fault errors in.

2022-05-25 19:11 UTC, adamrher commented
> Does that mean we won't output the ghost point?

Yes. Which is fine IMO too. The clubb documentation says that after the state is advanced in clubb, it just copies the pver values into pverp (the ghost point). So there's no additional information.

I'll plan on fixing the outfld's then...

2022-05-25 19:20 UTC, bstephens82 commented
Sounds good to me.

2022-05-26 14:53 UTC, bstephens82 approved these changes

2022-05-26 14:53 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +     inv_exner_clubb_surf(i) = 1._r8/((state1%pint(i,pverp)/p0_clubb)**(rair/cpair))
This statement contains an `i` but is outside of the `i` loop...is that intentional?

2022-05-26 14:53 UTC, bstephens82 commented on src/physics/cam/check_energy.F90
> +  integer  :: dqcore_idx = 0
Should this be commented?

2022-05-26 14:53 UTC, bstephens82 commented on src/physics/cam/physpkg.F90
> +  integer ::  dqcore_idx         = 0
Should these two lines be commented?

2022-05-26 14:53 UTC, bstephens82 commented on src/physics/cam_dev/physpkg.F90
>    integer ::  cmfmczm_idx        = 0     ! Zhang-McFarlane convective mass fluxes
Should this be commented?

2022-05-26 15:22 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +     inv_exner_clubb_surf(i) = 1._r8/((state1%pint(i,pverp)/p0_clubb)**(rair/cpair))
good catch! yep this is a mistake; wasn't looking closely at the loop nesting

2022-05-26 15:26 UTC, adamrher commented on src/physics/cam/check_energy.F90
> +  integer  :: dqcore_idx = 0
fixed

2022-05-26 15:26 UTC, adamrher commented on src/physics/cam/physpkg.F90
> +  integer ::  dqcore_idx         = 0
done

2022-06-22 19:43 UTC, cacraigucar reviewed
First pass review

2022-06-22 23:12 UTC, adamrher commented on src/physics/cam/cam_diagnostics.F90
> +    call outfld ('uIVT     ',ftem, pcols   ,lchnk     )
no reason. I removed this redundancy and just put ftem4/5 in the outfld calls directly.

2022-06-22 23:13 UTC, adamrher commented on src/physics/cam/micro_pumas_cam.F90
> +integer :: micro_mg_num_steps   = 1      ! Number of substepping iterations done by MG (versions 1.5 and later).
thanks! I actually pulled this out of the branch because it relates to outputting the time-steps to the log. But I made a new branch with just the time-step output code, and added your mods to micro_pumas_cam.

2022-06-22 23:15 UTC, adamrher commented on src/physics/cam/check_energy.F90
> +    call pbuf_add_field('DQCORE','global',dtype_r8,  (/pcols,pver,dyn_time_lvls/),dqcore_idx)
done

2022-06-22 23:16 UTC, adamrher commented on src/physics/cam/check_energy.F90
> +    call addfld('DQCORE', (/ 'lev' /), 'A', 'kg/kg/s' , 'Q tendency due to dynamical core')
changed it to "Water vapor tendency ..."

2022-06-22 23:17 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        if (k.gt.1) then
done (ive been reminded of this before ... hopefully it will take this time)

2022-06-22 23:19 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +         !                            thv should have condensate loading to be consistent with earlier def's
done

2022-06-23 15:44 UTC, adamrher commented
@cacraigucar this PR is almost ready for prime time. Three outstanding issues:

1. @Katetc are there are low hanging clubb issues that we should add to this PR?
2. Do I need to merge up to the head? My branch is currently based on cam6_3_060.
3. Currently doing a quick science eval of these changes, which should be completed by tomorrow.

2022-06-23 20:28 UTC, cacraigucar commented
> 2. Do I need to merge up to the head? My branch is currently based on cam6_3_060.

Yes, this will need to be merged to the head of cam_development before we run the final regression testing (once the reviews are complete and we are ready to begin the tagging process).  The code is fairly close to the head, so not critical for the review stage, especially since the tags since then have been pretty orthogonal.

2022-06-24 20:45 UTC, adamrher commented
@JulioTBacmeister
@swrneale 
@andrewgettelman 
@bstephens82

Impact of this PR is [here](https://webext.cgd.ucar.edu/F2000climo/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs/atm/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8-cam6_3_060_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8/) --8 years, L58, F2000dev. Seems to be a bit more convection in W.Pac, and an increase in ice water path. Nothing alarming.

2022-06-24 20:59 UTC, swrneale commented
West Pacific and Indian Monsoon are quite a bit wetter, which makes biases a bit worse. But in the far East Pacific it's slightly better. Mixed bag I guess. Do you have expectations of how stable/unstable the state is it on exit from CLUBB when you change the position of the PDF closure?

2022-06-24 21:07 UTC, adamrher commented
wait a second I see something wrong - [PBLH](https://webext.cgd.ucar.edu/F2000climo/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs/atm/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8-cam6_3_060_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8/set5_6/set5_ANN_PBLH_c.png).

I had previously tested the impact of the pdf closure position and not found any appreciably change. Rather it seems like I messed up the PBLH calculation in clubb_intr.

2022-06-24 21:18 UTC, swrneale commented
Is it using the Holslag Boville PBLH calculation still? Does the PDF closure come at a difference place relative to this calculation now?

2022-06-24 21:29 UTC, adamrher commented
Yes to Holstag Boville. No the pdf closure is not in a different place from the perspective of the PBLH call.

It's got to be one of two things. I changed the definition of theta to use the true exner function (not state%exner), and then in the theta_v calculation I added condensate loading. Doing two simulations with each of these reverted back right now. Note these theta / theta_v calculations are only used by the PBLH calculation.

2022-06-26 01:42 UTC, adamrher commented
I fixed this bug I introduced into the PBLH calculation. The problem was that I naively just replaced state%exner with the exner defined in clubb_intr. But state%exner is cryptically named -- it is actually 1/exner. This has tripped up many of us before, and so should probably be fixed.

So this is fixed, and I'm re-running 10 years to evaluate the impact of this PR.

2022-06-26 22:37 UTC, adamrher commented
Ten year runs of L58, cam_dev, [showing impact of this PR](https://webext.cgd.ucar.edu/F2000climo/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220625_fixexner2_Nx2yrs/atm/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220625_fixexner2_Nx2yrs.1_9-cam6_3_060_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.1_9/). @swrneale there are no precip changes in tropical pacific or indian monsoon region anymore. The only changes I see are TS, primarily over land. Interestingly TREFHT has much smaller changes. This resembles what we found when we tested the impact of [scaling sensible heat fluxes in isolation](https://webext.cgd.ucar.edu/F2000climo/cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_scaleshf_Nx5yrs.arh/atm/cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_scaleshf_Nx5yrs.2_20-cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_Nx5yrs.2_20/set5_6/set5_ANN_TS_c.png). Note these old expts are L32 runs, whereas these new expts are L58 cam_dev. The largest TS changes are over high elevation regions, the Himalayas and the big ice sheets. This is where we expect the largest changes since dividing by exner is only going to impact regions where PS is very different from P0=1000 hPa.

Recall also that the scaling of the sensible heat fluxes drastically reduces CLUBB's energy leak, so this is a substantial enhancement to the model. See Figure 12 of @PeterHjortLauritzen's very short little GRL paper [here](https://www.cgd.ucar.edu/cms/pel/papers/LetAl2022JAMES.pdf).

2022-06-28 19:38 UTC, cacraigucar reviewed
A few more minor points.  I think this will be ready for full review once you remove it from draft status.

2022-06-28 19:38 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +      !  (sec 4.3.2 in Lauritzen et al. 2022, JAMES)
Do you have a DOI for this reference?  We've started trying to put those in as well.

2022-06-28 19:38 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +   !                          - replace with rho at mid-points using mass def, to be consistent w/ earlier def's
Just a reminder to remove this after all the reviewers have seen it.  I assume you will be removing the commented out lines as well.

2022-06-28 19:38 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +     call outfld( 'THLM_CLUBB',       temp2d,                 pcols, lchnk )
Since the arithmetic was removed, you can remove the copy operation and just put the thlm in the outfld call directly.  This comment applies to the rcm_in_layer below as well.

2022-06-28 19:48 UTC, cacraigucar reviewed
One more general comment.  I believe that the description needs one issue number following a keyword like "fixes" to get the automation to close the issue.  @nusbaume is that correct, or can you have a list of issues?

2022-06-28 19:49 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      !  (sec 4.3.2 in Lauritzen et al. 2022, JAMES)
it's still in review, so no doi yet, unfortunately. and section numbering might change. maybe we should just remove line 2903 for now?

2022-06-28 21:34 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +     inv_exner_clubb_surf(i) = 1._r8/((state1%pint(i,pverp)/p0_clubb)**(rair/cpair))
Resolved.

2022-06-28 21:34 UTC, bstephens82 commented on src/physics/cam/check_energy.F90
> +  integer  :: dqcore_idx = 0
Resolved.

2022-06-28 21:34 UTC, bstephens82 commented on src/physics/cam/physpkg.F90
> +  integer ::  dqcore_idx         = 0
Resolved.

2022-06-28 21:34 UTC, bstephens82 commented on src/physics/cam_dev/physpkg.F90
>    integer ::  cmfmczm_idx        = 0     ! Zhang-McFarlane convective mass fluxes
Resolved.

2022-06-29 00:35 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +     call outfld( 'THLM_CLUBB',       temp2d,                 pcols, lchnk )
ok. same goes for existing entires before and after this line. Removed all unnecessary copy operations nearby.

2022-06-29 00:35 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +   !                          - replace with rho at mid-points using mass def, to be consistent w/ earlier def's
ok. will remove when everyone has done a first pass.

2022-06-29 03:00 UTC, nusbaume commented
@cacraigucar @adamrher Sadly you do need to have the "fixes" statement repeated for each issue, as well as just the issue number alone with the "#" sign (not the full URL).  

I went ahead and updated the main PR description to match these requirements, so hopefully that was ok!

2022-06-30 00:02 UTC, gold2718 approved these changes

2022-06-30 16:30 UTC, peverwhee approved these changes

2022-07-03 03:08 UTC, nusbaume requested changes
Looks good, but I do have some minor code clean-up requests.

2022-07-05 16:22 UTC, adamrher commented on src/physics/cam/cam_diagnostics.F90
> +    ftem5(:ncol,:) = state%q(:ncol,:,1) * state%v(:ncol,:) *state%pdel(:ncol,:) * rga
OK. This does seem to be pervasive throughout this subroutine. I added in ixq / get_index_pbuf locally to the subroutine, and changed all occurrences of ```state%q(:ncol,:,1)``` to ```state%q(:ncol,:,ixq)```. I didn't try to define ixq at the module level because ixq is a intent(in) argument to one of the other subroutines in the module, which would create duplicate definitions.

2022-07-05 16:23 UTC, adamrher commented on src/physics/cam/cam_diagnostics.F90
> +    real(r8) :: ftem5(pcols,pver) ! another temporary workspace
replaced these with existing ftem1 and ftem2 arrays.

2022-07-05 16:24 UTC, adamrher commented on src/physics/cam_dev/physpkg.F90
> +       dqcore(:ncol,:pver) = (state%q(:ncol,:pver,1) - dqcore(:ncol,:pver))/ztodt
done

2022-07-05 16:26 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdel(i,pver-k+1) &
done

2022-07-05 16:29 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +   rho(1:ncol,1:pver) = (1._r8/gravit)*state1%pdel(1:ncol,1:pver)/(state1%zi(1:ncol,1:pver)-state1%zi(1:ncol,2:pverp))
done

2022-07-05 17:42 UTC, nusbaume commented on src/physics/cam/cam_diagnostics.F90
> +    ftem5(:ncol,:) = state%q(:ncol,:,1) * state%v(:ncol,:) *state%pdel(:ncol,:) * rga
No worries, I actually only expected that you would modify the new code, so way to go above and beyond!

2022-07-05 17:42 UTC, nusbaume approved these changes
Looks great now, thanks!

2022-07-05 17:49 UTC, cacraigucar commented on src/physics/cam/physpkg.F90
> +       dqcore(:ncol,k) = state%q(:ncol,k,ixq)
ixq is not in scope (defined) in tphysac.  I'm working on a mod to fix this.  The cam_dev version already had the ixq defined in tphysac, which is why this was missed.

2022-07-05 17:52 UTC, adamrher commented on src/physics/cam/physpkg.F90
> +       dqcore(:ncol,k) = state%q(:ncol,k,ixq)
ah right, only in cam_dev/physpkg.F90 is ixq defined at the tphysac level.

2022-07-05 21:55 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
At least two regression tests are erroring out at this location:

[11] Runtime Error: *** Arithmetic exception: Floating invalid operati[11] on - aborting
[11] /home/cacraig/cam_clubb_kitchensink/src/control/cam_history_buffers.F90, line 104: Error occurred[11]  in CAM_HISTORY_BUFFERS:HBUF_ACCUM_ADD
[11] /home/cacraig/cam_clubb_kitchensink/src/control/cam_history.F90, line 3429: Called by CAM_HISTORY:OUTFLD
[11] /home/cacraig/cam_clubb_kitchensink/src/physics/cam/clubb_intr.F90, line 4153: C[11] alled by CLUBB_INTR:CLUBB_TEND_CAM

A run can be seen at: 
/scratch/cluster/cacraig/aux_cam_nag_20220705130436/ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s.GC.aux_cam_nag_20220705130436/run

@adamrher  - Can you take a look at this?  I can check into this tomorrow if you don't solve this.  I'm guessing a mismatch in dimensions possibly.

2022-07-05 22:06 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
can you provide a create test command to reproduce this error?

2022-07-05 22:12 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
The create_newcase used was:

 /home/cacraig/cam_clubb_kitchensink/cime/CIME/scripts/create_newcase.py --case /scratch/cluster/cacraig/aux_cam_nag_20220705130436/ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s.GC.aux_cam_nag_20220705130436 --res f10_f10_mg37 --compset QPWmaC6 --test --machine izumi --compiler nag --output-root /scratch/cluster/cacraig/aux_cam_nag_20220705130436 --workflow default --srcroot /home/cacraig/cam_clubb_kitchensink --driver nuopc --user-mods-dir /home/cacraig/cam_clubb_kitchensink/cime_config/testdefs/testmods_dirs/cam/outfrq3s --walltime 00:30:00

I know you need to remove the --test and --workflow default since you won't be in the testing suite.

2022-07-05 22:36 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
> isn't there a much easier way to run this test? Say:
> 
> ./create_test ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s
> 
> ??

Yes, you can use that command as well

2022-07-06 01:36 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
It looks to be throwing a fit over all my new array subsetting in the outfld calls. E.g., this gives an error:
```
   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),  pcols, lchnk )
```
This does not:
```
   call outfld( 'RHO_CLUBB',        rho,                   pcols, lchnk )
```
I introduced this (1:ncol,1:pver) subsetting of arrays for about 10 different outfld calls in this PR. These arrays are of size (pcol,pverp). The problem is that clubb's grid for the mid-point levels has pverp entries, whereas CAM's mid-point grid only has pver entries, because clubb plops an additional vertical level in the subsurface. So my goal is to omit the pverp / subsurface point, and only outfld the 1:pver entries of the arrays, since they should be on CAM's  ```lev``` grid. 

@cacraigucar can you take a look at this tmrw?

2022-07-06 03:28 UTC, gold2718 commented on src/physics/cam/clubb_intr.F90
> +   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
> It looks to be throwing a fit over all my new array subsetting in the outfld calls. E.g., this gives an error:
> 
> ```
>    call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),  pcols, lchnk )
> ```

Makes sense, try:
```
   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),  ncol, lchnk )
```
Note the change in the third argument (which is the size of the first dimension of the second argument).

2022-07-06 20:52 UTC, cacraigucar approved these changes

2022-07-07 22:04 UTC, merged