Updates to deposition module in share code externals
ESCOMP/CAM pull request #602
Opened 2022-06-01 02:12 UTC by fvitt

These are updates needed to read deposition data from file.  Changes to drydep_mod share code replaced hard-wired data in drydep_mod with a netcdf input file. Changes here are needed for the updates to the relevant external share code bases.

closes #601

2022-06-27 19:38 UTC, cacraigucar requested changes
Hit approve button by accident - it should be request changes

2022-06-27 21:12 UTC, gold2718 requested changes
I second @cacraigucar's requests and added a few more minor requests.

2022-06-27 21:12 UTC, gold2718 commented on src/cpl/nuopc/atm_import_export.F90
> +  public  :: set_options
This is not a good name for the cap level. Please change it to
```suggestion
  public  :: read_surface_namelists
```
or come up with some other appropriate (i.e., more specific) name.

2022-06-27 21:12 UTC, gold2718 commented on src/cpl/nuopc/atm_import_export.F90
> +  subroutine set_options()
Change name (see above).

2022-06-27 21:12 UTC, gold2718 commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +  use atm_import_export   , only : set_options, advertise_fields, realize_fields
Change name (see comment in atm_import_export.F90).

2022-06-27 21:12 UTC, gold2718 commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +    ! read drv flds options
Please change the comment as this has nothing to do with the driver:
```suggestion
    ! read mediator fields options
```

2022-06-29 13:29 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<dep_data_file>atm/cam/chem/trop_mozart/dvel/dep_data_c201019.nc</dep_data_file>
done

2022-06-29 13:49 UTC, fvitt commented on src/cpl/nuopc/atm_import_export.F90
> +  public  :: set_options
Would you be okay with `read_fields_namelists`?

2022-06-29 19:23 UTC, peverwhee approved these changes

2022-06-29 19:47 UTC, gold2718 commented on src/cpl/nuopc/atm_import_export.F90
> +  public  :: set_options
Would `read_surface_field_namelists` be more specific while still being accurate?

2022-07-05 13:38 UTC, fvitt commented on src/chemistry/mozart/mo_neu_wetdep.F90
> +! code taken from models/drv/shr/shr_drydep_mod.F90
Removed the comment

2022-07-05 14:24 UTC, fvitt commented on src/cpl/nuopc/atm_import_export.F90
> +  public  :: set_options
Updated as suggested

2022-07-05 14:25 UTC, fvitt commented on src/cpl/nuopc/atm_import_export.F90
> +  subroutine set_options()
done

2022-07-05 14:25 UTC, fvitt commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +  use atm_import_export   , only : set_options, advertise_fields, realize_fields
done

2022-07-05 14:25 UTC, fvitt commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +    call set_options()
done

2022-07-05 14:25 UTC, fvitt commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +    ! read drv flds options
updated the comment

2022-07-25 21:50 UTC, cacraigucar commented on Externals.cfg
> +branch = dep_data_file
@fvitt - Are we still waiting for the official tags for these?

2022-07-25 22:21 UTC, fvitt commented on Externals.cfg
> +branch = dep_data_file
@cacraigucar 
Yes. Still waiting for the tags.  Who should we ping for these?

2022-07-25 22:37 UTC, cacraigucar commented on Externals.cfg
> +branch = dep_data_file
@fvitt  - I'm not sure.  I've added it to tomorrow's CSEG meeting agenda.

2022-07-26 21:53 UTC, cacraigucar approved these changes

2022-07-27 15:51 UTC, lizziel commented
I am using the updates in this PR (and the related ones) for development of GEOS-Chem in CESM. One of the things that has confused me is that wet deposition requires parameters from dry deposition modules, previously for `seq_drydep_mod`, and now for `shr_drydep_mod`. I see the netcdf file that replaces the hard-coded values in `seq_drydep_mod.F90` is more generically named to indicate deposition rather than dry deposition (`dep_data_file.nc` rather than `drydep_data_file.nc`). Would you consider updating the module names to be generic as well? I can add this comment to the conversations of the relevant PRs if you agree.

2022-07-27 16:17 UTC, fvitt commented
> 

@lizziel Your request is a little late for this PR.  The PRs for the externals have been merged into the main repos and have been closed.  This PR is close to being merged into cam_development as it is.  I suggest you open a new issue in https://github.com/ESCOMP/CMEPS for your request.

2022-07-27 17:42 UTC, lizziel commented
@fvitt, thanks for the response. I'll open a new issue for this.

2022-07-29 20:38 UTC, nusbaume approved these changes
Looks good!  Just a couple optional cosmetic changes (and a question for the other CAM SEs).

2022-07-29 20:38 UTC, nusbaume commented on src/chemistry/mozart/mo_drydep.F90
> +  use shr_drydep_mod,   only : nddvels =>  n_drydep, drydep_list, mapping
I might remove the spaces between `only` and `:` here in order to better match the CAM style guide.

2022-07-29 20:38 UTC, nusbaume commented on src/chemistry/mozart/mo_neu_wetdep.F90
> +  use shr_drydep_mod,   only : n_species_table, species_name_table, dheff
I might remove the spaces between `only` and `:` here in order to better match the CAM style guide.

2022-07-29 20:38 UTC, nusbaume commented on src/chemistry/mozart/mo_neu_wetdep.F90
> +  real(r8), parameter :: rad2deg = 180._r8/pi
@gold2718 @cacraigucar @peverwhee I feel like I have seen this particular calculation in multiple places throughout CAM.  Would it make sense to add this (and an inverse `deg2rad`) into `physconst` so that this parameter doesn't have to be repeated so much? 

I should note that we don't have to necessarily do it for this PR, I just think that if we all agree then it would be good to make an issue for it so one of us can tackle it later.

2022-07-29 22:23 UTC, gold2718 commented on src/chemistry/mozart/mo_neu_wetdep.F90
> +  real(r8), parameter :: rad2deg = 180._r8/pi
It's minor in the sense that the parameter is baked into the code (no run-time cost).
A better solution for cases like this will come when all the dycores use the new physics grid infrastructure which has coordinates in both radians and degrees.

2022-07-29 22:24 UTC, gold2718 approved these changes
Looks okay to me

2022-08-03 20:22 UTC, merged