Misc tag for Gravity Wave, contrail, cam_snapshot and SE dycore writes
ESCOMP/CAM pull request #612
Opened 2022-06-28 20:36 UTC by cacraigucar

Issues being closed:

Closes #362 (contrail bug fix)
Closes #610  (SE dycore writes)
Closes #606 (cam_snapshot fix)

PRs being closed:
Closes #535 (contrail bug fix)
Closes #447 (GW diags)

Note to reviewers:  #535 and #447 were already reviewed.  The only unreviewed files are:  cam_snapshot_common.F90 and global_norms_mod.F90.  Also note that most of the changes in these two files are whitespace.  The actual code changes are minimal

2022-06-29 02:50 UTC, nusbaume approved these changes
Looks good!  Just one optional code clean-up request.

2022-06-29 02:50 UTC, nusbaume commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
Would it make more sense to have this whole section of `write` statements inside a single `if (hybrid%masterthread) then` check?  Otherwise it seems like we are repeatedly doing the same check multiple times.

2022-06-29 15:42 UTC, cacraigucar commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
I will leave this up to @jtruesdal as he was the creator of this code.

2022-06-29 16:53 UTC, gold2718 requested changes

2022-06-29 16:53 UTC, gold2718 commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
I think it is worth doing the cleanup.

2022-06-29 19:02 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
Yes. I agree please clean this up as Jesse is recommending.

2022-06-29 19:07 UTC, jtruesdal approved these changes

2022-06-29 19:07 UTC, cacraigucar commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
Made the change

2022-06-29 19:40 UTC, nusbaume commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
Just for the sake of completeness (and probably annoyance) does it make sense to include the:

`write(iulog,*) ": sponge layer viscosity scaling factor"`

line just below that code block inside the new if statement as well?

2022-06-29 19:54 UTC, gold2718 commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    if ((hybrid%masterthread) write(iulog,* )""
I would say yes but do not see how this print statement provides any information. Maybe in the past, the relevant values were printed but no they are not so I would remove it. @jtruesdal? @PeterHjortLauritzen?

2022-06-29 22:30 UTC, gold2718 requested changes
I'm taking myself off the re-review list for now since all of my requested changes have _not_ been made.

2022-06-30 16:34 UTC, peverwhee approved these changes

2022-07-01 15:51 UTC, merged