Upper boundary conditions specification via namelist
ESCOMP/CAM pull request #614
Opened 2022-07-08 23:19 UTC by fvitt

Implements upper boundary conditions namelist options for low and high-top models.  The defaults setting only specify fixed upper boundary conditions for WACCM.

closes #216 
closes #533

2022-07-21 15:24 UTC, fvitt commented
Should remove deprecated NOy UBC module (dead code):
 src/chemistry/mozart/noy_ubc.F90

2022-07-21 15:35 UTC, cacraigucar commented
> Should remove deprecated NOy UBC module (dead code): src/chemistry/mozart/noy_ubc.F90

@fvitt - Feel free to make this change and push it back to your branch.  I started reviewing yesterday, but this change won't impact my review.

2022-07-25 17:34 UTC, cacraigucar requested changes

2022-07-26 15:28 UTC, fvitt commented on doc/ChangeLog
> + - get upper boundar fluxes separately for WACCMX
fixed

2022-07-26 15:28 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +    call mpi_bcast(ubc_file_cycle_yr,  1, mpi_integer, masterprocid, mpicom, ierr)
added checks

2022-07-26 15:29 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +    call mpi_bcast(ubc_source,    pcnst*len(ubc_source(1)),    mpi_character,masterprocid, mpicom, ierr)
added checks

2022-07-26 15:30 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +       !call add_default(hist_names(m), 2, ' ' )
removed

2022-08-01 20:46 UTC, cacraigucar approved these changes

2022-08-05 20:19 UTC, nusbaume requested changes
Looks good, but I did have some (hopefully minor) change requests.

2022-08-05 20:19 UTC, nusbaume commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
The number `2.03E-13` looks really specific.  Do you know where it came from?

2022-08-05 21:21 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
@hanli-liu Can you comment on the `2.03E-13` factor used in the calculation of the fluxes of H at the upper boundary of WACCMX?

2022-08-06 15:06 UTC, hanli-liu commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
This is the hydrogen escape flux due to charge exchange adopted from TIME-GCM. According to TIME-GCM notes, this value comes from Liu & Donahue (1974) and Hunten & Donahue (1976).

2022-08-08 15:06 UTC, nusbaume commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
Thanks @hanli-liu!  Do the TIME-GCM notes have the titles for the papers as well?  It looks like there were multiple "Liu & Donahue 1974" papers related to Hydrogen in the upper atmosphere, so I just want to make sure we cite the correct one.

2022-08-08 15:13 UTC, nusbaume commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
I am also happy with instead just using the TIME-GCM notes directly if they have been published somewhere (whichever option is easier).

2022-08-08 17:28 UTC, hanli-liu commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
You may use the following reference for TIME-GCM:
Roble, R. G., Energetics of the mesosphere and thermosphere, in The Upper Mesosphere and Lower Thermosphere: A Review of Experiment and Theory, Geophys. Monogr. Ser., vol. 87, edited by R. M. Johnson and T. L. Killeen, pp. 1 –22, AGU, Washington, D. C., 1995.
This paper does not give a detailed description of the flux used in the model, but it did refer to the work by Liu&Donahue (1974) and Hunten&Donahue (1976). The Liu&Donahue reference is:
Liu, S.C., and T. M. Donahue, Mesospheric hydrogen related to exospheric escape mechanisms, J. Atmos. Sci.,
31, 1466-1470, 1974. (Equation 4 there).

2022-08-08 17:53 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
@nusbaume and @hanli-liu 
Are you okay with making this factor a parameter documented as:
```
    real(r8), parameter :: h_escape_flx_factor = 2.03e-13_r8 ! for hydrogen escape flux due to charge exchange
    ! adopted from TIME-GCM (T. L. Killeen, pp. 1 –22, AGU, Washington, D. C., 1995) following
    ! Liu, S.C., and T. M. Donahue, Mesospheric hydrogen related to exospheric escape mechanisms, J. Atmos. Sci.,
    ! 31, 1466-1470, 1974. (Equation 4 there). DOI: 10.1175/1520-0469(1974)031<1466:Mhrtee>2.0.Co;2
    ! https://journals.ametsoc.org/view/journals/atsc/31/5/1520-0469_1974_031_1466_mhrtee_2_0_co_2.xml
```

2022-08-08 18:05 UTC, hanli-liu commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
The reference to TIME-GCM:
R. G. Roble, pp. 1-21, AGU Geophys. Monogr. Ser 87, 1995.

2022-08-08 18:45 UTC, nusbaume commented on src/chemistry/mozart/upper_bc.F90
> +            (2.03E-13_r8 * qh_top(iCol) * nmbartop / (cnst_mw(h_ndx) / avogad) * t(iCol,1))
@fvitt Making the factor a parameter with the provided documentation sounds good to me.  Thanks!
@hanli-liu Thanks again for looking all of this up!

2022-08-09 19:46 UTC, nusbaume approved these changes
Looks good now, although there were a couple of questions missed from the first review round that I tried to highlight (but I don't think they have to hold up this PR).

2022-08-09 19:46 UTC, nusbaume commented on src/chemistry/mozart/upper_bc.F90
> +             n_fixed_vmr=n_fixed_vmr+1
Looks like this question was missed from the first review round.

2022-08-09 19:46 UTC, nusbaume commented on bld/build-namelist
> +if (($chem =~ /waccm_ma/ or $chem =~ /waccm_tsmlt/ ) and !$waccmx) {
Looks like this question was missed from the first review round.

2022-08-19 03:25 UTC, gold2718 requested changes
Just a few requests and questions.

2022-08-19 03:25 UTC, gold2718 commented on doc/ChangeLog
> +Describe any changes made to build system:
Please indicate no changes:
```suggestion
Describe any changes made to build system: NA
```

2022-08-19 03:25 UTC, gold2718 commented on doc/ChangeLog
> +     SNOE
I do not think you need to repeat all the details of the namelist changes here, however, if you do keep it, please update this section if (when?) you update the description in namelist_definition.xml

2022-08-19 12:56 UTC, fvitt commented on bld/build-namelist
> +if (($chem =~ /waccm_ma/ or $chem =~ /waccm_tsmlt/ ) and !$waccmx) {
Not for WACCM-X and maybe not for CAM (not sure). I added a note to the description.

2022-08-19 13:26 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +             n_fixed_vmr=n_fixed_vmr+1
If both `mmr` and `vmr` are both present (or some other unrecognized string is used) then at initialization the model will abort with an error message something like:
 `ERROR: ubc_init: incorrect units in UBC source: 1.d-12vmrmmr`

2022-08-19 13:28 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +  SNOE
I added brief descriptions for these legacy waccm upper boundary setters

2022-08-19 13:29 UTC, fvitt commented on src/chemistry/utils/tracer_data.F90
> +
Corrected in many places in tracer_data.F90

2022-08-19 13:29 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +  type(trfld), pointer :: fields(:)
done

2022-08-19 13:30 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +    upper_bc_file_specified = .not. ubc_file_path == 'NONE'
Changed as suggested

2022-08-19 13:30 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +       write(iulog,*) prefix//'ubc_file_fixed_tod = ',ubc_file_fixed_tod
Changes concats to commas

2022-08-19 13:38 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +       case ('k','kg/kg','mmr')
Changed as suggested

2022-08-19 13:38 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +       case ('mol/mol','mole/mole','vmr')
changed as suggested

2022-08-19 13:39 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +          vmrndx = index(trim(ubc_source(m)),'vmr')
Yes

2022-08-19 13:39 UTC, fvitt commented on doc/ChangeLog
> +Describe any changes made to build system:
Added NAs

2022-08-19 13:39 UTC, fvitt commented on doc/ChangeLog
> +     SNOE
Removed the details here

2022-08-19 17:34 UTC, peverwhee approved these changes
looks good to me - one small typo

2022-08-19 19:28 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +  value (mmr|vmr)
This is better, thanks. Can you include a one-liner for `value` as well?
```suggestion
  value (mmr|vmr) - Set to a constant value (e.g., 0.123 mmr)
```
Is my example the right way to do this?

2022-08-19 19:28 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +  SNOE
Okay but please see my other (new) comment about 'value'

2022-08-19 19:36 UTC, gold2718 approved these changes
Minor documentation request for namelist_definition (and please fix the type @peverwhee found) but otherwise, looks okay.

2022-08-19 19:41 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +  public :: ubc_fixed_temp     ! true if temperature at upper bounary is fixed
fixed

2022-08-19 19:41 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +  value (mmr|vmr)
Made this change -- just did not like your example value.

2022-08-22 19:28 UTC, merged