CAM Thermo Refactor
ESCOMP/CAM pull request #615
Opened 2022-07-11 22:14 UTC by peverwhee

### Overview
Separating out physconst into the following three modules:
1. **physconst.F90**: Data and interfaces needed to contain more fundamental constants.
2. **air_composition.F90**: Data and interfaces for quantities which vary with the composition of the atmosphere (e.g., number and types of condensed water species).
3. **cam_thermo.F90**: Interfaces to compute thermodynamic quantities (e.g., thermal energy).

### Testing
Ran all aux_cam tests on izumi and cheyenne. All pass vs. cam6_3_064 baselines. 

closes #542

2022-07-17 22:27 UTC, gold2718 requested changes
Great work!
A few, mostly minor, changes, then I think it will be ready for full review.

2022-07-17 22:27 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +       end if
Holy combinatorial explosion batman! I think this code is correct but there is no way we are getting close to testing all the cases.
Currently, I think there is only one call (in se/dycore/prim_advance_mod.F90).
@PeterHjortLauritzen, is there an intended use for the other optional arguments to `get_rho_dry` (`rho_dry`, `rhoi_dry`, `pmid_out`, & `pint_out` -- only `rho_dry` is currently used)? Are there expected to be any groupings (e.g., `pmid_out` and `pint_out` always used together)?

2022-07-17 22:27 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +       else if (get_at_interfaces == 0) then
What happened to the code that used to be here? Is there a reason it is gone?

2022-07-20 20:06 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +      use constituents,  only: pcnst
removed

2022-07-20 20:06 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +           active_species_idx_dycore=thermodynamic_active_species_idx)
agreed. removed.

2022-07-20 20:07 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +                 dp_dry(:, jdx, :), dp(:, jdx, :), ps=ps, ptop=ptop)
Indeed! Fixed.

2022-07-20 20:07 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +       else if (get_at_interfaces == 0) then
Picky, picky.  Code reinserted.

2022-07-20 20:07 UTC, peverwhee commented on src/utils/air_composition.F90
> +               thermodynamic_active_species_cv (icnst) = cv1 / mw
Thanks!

...you did it.

2022-07-20 20:09 UTC, peverwhee commented on src/utils/air_composition.F90
> +            call dry_air_species_info('N', ix, mw)
cnst_get_ind, which is called in dry_air_species_info, needs 'N' rather than 'N2' but I could add logic to dry_air_species_info to swap in 'N' for the call conditionally?  That way the error messages say N2...

2022-07-20 20:09 UTC, peverwhee commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
Fair enough. Shall I revert it since it's an unnecessary change?

2022-07-21 16:29 UTC, gold2718 commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
No, it does protect against changing any of the pointers inside of `dyn_in` or `dyn_out` so slightly better than useless :)

2022-07-21 16:30 UTC, gold2718 commented on src/utils/air_composition.F90
> +               thermodynamic_active_species_cv (icnst) = cv1 / mw
Not everywhere (e.g., I missed this particular spot and some below).

2022-07-21 19:25 UTC, gold2718 approved these changes
Looks good now. I will look into the `'N'` vs. '`N2`' issue, could just be a naming mismatch somewhere (e.g., in `cnst_add`).

2022-07-21 19:34 UTC, fvitt commented on src/utils/air_composition.F90
> +            call dry_air_species_info('N', ix, mw)
@gold2718 None of our model configurations include N2 in the constituents.  However, waccm does include N (atomic nitrogen) in the chemistry (and in the constituents array), and the molecular weight of N2 is derived from the molecular weight of N.

2022-07-21 23:15 UTC, cacraigucar reviewed
First pass comments

2022-07-22 16:00 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +
I see that it is being used in utils/physconst.F90

2022-07-22 16:26 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +
- It cannot be used in physconst because that would be a circular dependency. Are you looking at an old version?
- I do not see any calls to `get_R`, however, we might need the routine for future work. @PeterHjortLauritzen, is it possible that some of the other dycores, or some physics routines could need this routine moving forwards?

2022-07-22 16:36 UTC, cacraigucar reviewed
Submit current comments to clarify one issue immediately

2022-07-22 16:36 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +   ! See Lauritzen et al. (2018) for formulaes
Is "formulaes" an accepted variation or should it be formulas?

2022-07-22 16:36 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +   public :: cam_thermo_calc_kappav
Missing description comment?

2022-07-22 16:36 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +
I initially did my search on a checkout I had.  I then went to look in the current code and accidentally hit submit.  When I looked in the current code, I did see that it is called in cam_thermo.F90 (line 722 and 725) and I amended my comment.  It is being used, so no need to get a response from @PeterHjortLauritzen.  I thought I resolved the conversation as well to indicate it was no longer relevant.

2022-07-22 16:55 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +
Lines 722 and 725 in cam_thermo are calls from the 2D version of get_R to the 1D version of get_R, so I don't think that counts as get_R being "used"

2022-07-22 16:58 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +
@peverwhee - True - I just was happy to see the calls, I wasn't looking at the context.  

I guess @PeterHjortLauritzen is on the hook to let us know if we should keep this routine for the future or not.

2022-07-22 17:46 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +
The intention was to have the routine ready for future work.

2022-07-22 18:05 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +   ! See Lauritzen et al. (2018) for formulaes
They are equivalent (at least according to my dictionaries).

2022-07-22 18:09 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +
Let's keep it then. The calls on 722 and 725 are just the 2-D version calling the 1-D version so there are no "real" calls yet.
Maybe the ChangeLog should note that this is untested code since no one is using it yet.

2022-07-22 18:17 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +   ! See Lauritzen et al. (2018) for formulaes
My dictionary indicates plural of formulas or formulae (no s).  It is a dictionary from the mid-70's so this may be an evolution since then or a more global spelling

2022-07-22 18:20 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +
I would augment Steve's suggestion to also include the comment about the code being untested above the routines themselves as a user will probably refer to the call and can see the comment there when they go to use it.

2022-07-22 18:54 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +   ! See Lauritzen et al. (2018) for formulaes
Nope, I missed the extra 's'. So someone needs to pick one of the accepted plurals, can't have both :)

2022-07-25 17:08 UTC, cacraigucar commented on src/utils/physconst.F90
> +               call endrun(subname//'ERROR reading namelist, physconst_nl')
The relevant code is a few lines below this line.  The MPI_bcast calls need to have their error codes checked

2022-07-26 16:52 UTC, peverwhee commented on src/utils/air_composition.F90
> +2000  format("*** ",a,2("   ",E18.10),"  ***")
nope. removed.

2022-07-26 16:52 UTC, peverwhee commented on src/utils/air_composition.F90
> +           masterprocid, mpicom, ierr)
checks added.

2022-07-26 16:53 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +
comment added to code and to changelog (changelog not yet committed)

2022-07-26 16:53 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   ! See Lauritzen et al. (2018) for formulaes
I chose formulae

2022-07-26 16:53 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   public :: cam_thermo_calc_kappav
added

2022-07-26 16:53 UTC, peverwhee commented on src/utils/physconst.F90
> +               call endrun(subname//'ERROR reading namelist, physconst_nl')
checks added.

2022-07-26 18:05 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +   public :: get_R
This is maybe more of a philosophical/design question then a strictly engineering question, but there are some quantities here like the gas constant (R) and average molecular weight (mbarv) that, to my understanding, depend solely on the chemical composition of the gas mixture.  This means that although they can vary in space/time, particularly for high-top models where molecular diffusion matters, they shouldn't depend on other thermodynamic quantities like temperature or pressure that vary even in a well-mixed atmosphere.

Thus I am wondering if maybe these subroutines should be pushed down to the `air_composition` layer,  or possibly a new module between `air_composition` and `cam_thermo`, that deals with quantities that can vary in the atmosphere, but only depend on the chemical composition?  I am happy to be overruled, but just wanted to bring this up as a possible point of discussion.

@gold2718 @PeterHjortLauritzen

2022-07-26 20:42 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +   public :: get_R
I am trying to recall why they ended up in cam_thermo in the first place. I think it is because variables such as `thermodynamic_active_species_idx` started out there but that turned out to not be viable so maybe now we can push these interfaces down to air_composition:
```
get_R
get_R_dry
get_mbarv
get_cp
get_cp_dry
```

2022-07-26 21:10 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   public :: get_R
Will do. Do we also want to move cpairv, rairv, cappav, and mbarv to air_composition? And possibly cam_thermo_update -> air_composition_update?

2022-07-26 23:44 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +   public :: get_R
To move the interfaces above, you do have to move `cpairv`, `rairv` etc. to air_composition.
However, while most of `cam_thermo_update` is just calling the interfaces that are moving, I wonder about `get_molecular_diff_coef` (and therefore `kmvis` and `kmcnd`) which feels a lot more like thermo to me. That means that we need a `cam_thermo_update` but perhaps, the other routines could move to an `air_composition_update` which `cam_thermo_update` could call. Or would that be too confusing?

2022-07-27 03:42 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   public :: get_R
I think a new air_composition_update makes the most sense (which is called from cam_thermo_update). I'll go with that but can change it if others disagree

2022-07-27 16:35 UTC, PeterHjortLauritzen approved these changes
@peverwhee: Thank you! Very nice and clear refactoring of the thermo/composition code (the conditionals still make me dizzy but probably necessary since different subroutines want the same quantity but based on different forms of the input variables). Now our challenge will be to make sure new code uses these modules as well as existing physics (I am starting to take action on the latter) ...

A science request:

Thermal energy is really enthalpy. Can we rename one subroutine name and comments?

That is, 

- replace "subroutine get_thermal_energy" with "get_enthalpy_energy"
- troughout search and replace "thermal energy" with "enthalpy" in the comments.

2022-07-27 17:09 UTC, gold2718 commented
> * replace "subroutine get_thermal_energy" with "get_enthalpy_energy"

This seems a bit redundant. Did you mean?

replace "subroutine get_thermal_energy" with "get_enthalpy"

??

2022-07-28 15:43 UTC, peverwhee commented
@PeterHjortLauritzen I made the requested changes, but went with get_enthalpy instead of get_enthalpy_energy. If you want get_enthalpy_energy, let me know!

2022-07-29 17:21 UTC, nusbaume requested changes
Sorry for taking so long, I just wanted to make sure I understood the changes as well as possible.

Now I am not saying we have lice, but a lot of my requests are small nit-picks, or requests to change comments.  However, there are a few requests that might be a little more substantial, or require scientist input (I tried to "@" people in that situation).  Of course if you have any questions or concerns with anything I brought up just let me know.  Thanks again for all the hard work!

2022-07-29 17:21 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
I assume the `1.e-7_r8` and the `1.e-5_r8` are doing some sort of unit conversions, but what are they converting to/from?  If not a conversion then what are these values physically (@jtruesdal @PeterHjortLauritzen)?

2022-07-29 17:51 UTC, gold2718 commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
This is the fun and games of pointers in Fortran. Technically, `dyn_out` is not being modified. Some modifications to memory locations that _happen_ to be pointed to by pointers located in `dyn_out` does not bother `dyn_out` which can claim that it kept all of its pointer locations intact.
Of course, C has more fine-grained control over stuff like this which is why C programmers spend so much time worrying about `const` correctness (I know I have).
So what do we want to do about it? I'm on the fence.

2022-07-29 17:52 UTC, gold2718 commented on src/utils/physconst.F90
> +   real(r8), public, parameter :: rhoh2o      = shr_const_rhofw      ! Density of liquid water (STP)
Well if we are fixing up comments, we should move to CF-standard units (e.g., `kg m-3` instead of `kg/m^3`).

2022-07-29 17:52 UTC, gold2718 commented on src/utils/physconst.F90
> +   ! Molecular weights
or `g mol-1`

2022-07-29 18:00 UTC, cacraigucar commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
My vote is to make it intent(inout) to signify to readers that dyn_out is having "values" modified even though technically since the pointers are not being modified, this is legal.  All that is gained by keeping dyn_out being intent(in) is that it protects the pointer locations from being changed.  I think the benefit to readers outweighs the slight benefit to pointer protection.

2022-07-29 18:03 UTC, nusbaume commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
Ahh, good point (pun intended)! Since the `dyn_out` structure itself is not being touched then I am happy with leaving this as `intent(in)`, as I imagine it would provide some protection in case someone mistakenly does cause one of the `dyn_out` pointers to point somewhere else in this subroutine?

2022-07-29 18:05 UTC, nusbaume commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
Nevermind, just saw Cheryl's comment, and I guess she convinced me to go back to the `intent(inout)` side of the argument.

2022-07-29 18:08 UTC, nusbaume commented on src/utils/physconst.F90
> +   real(r8), public, parameter :: rhoh2o      = shr_const_rhofw      ! Density of liquid water (STP)
I am fine with this, but I might then vote that all of the unit comments in this module be changed to be CF-compliant (so I'll leave it up to @peverwhee as to whether she wants to do that or not).

2022-07-29 18:37 UTC, gold2718 commented on src/utils/physconst.F90
> +   real(r8), public, protected :: Cpd_on_Cpv = shr_const_cpdair/shr_const_cpwv
They sort of _are_ derived from the variables above because (at least most of them) need to be updated if any of the "constants" change. For instance, you can enter a different value for `gravit` in which case, `rga` needs to be updated as well. I would leave this section alone.

2022-07-29 18:50 UTC, gold2718 commented on src/utils/air_composition.F90
> +               thermodynamic_active_species_kc(icnst)  = 0.0_r8
Maybe I'm looking at it wrong but to me, these values look like they _are_ for atomic hydrogen. Did you mean molecular hydrogen?

2022-07-29 19:11 UTC, gold2718 commented on src/utils/air_composition.F90
> +      real(r8),           intent(in) :: to_moist_factor(:,:)
Good idea, then the code inside `cam_thermo_udpate` could be cleaned up since it is optional there -- just pass it through instead of making a local copy (although it might be good to check the size of the first dimension if `to_moist_factor` is present to make sure it matches `ncol`).

2022-07-29 19:14 UTC, nusbaume commented on src/utils/air_composition.F90
> +               thermodynamic_active_species_kc(icnst)  = 0.0_r8
Sorry, I realize this is atomic hydrogen. I  guess I just meant that it's weird that it apparently has no impact on molecular diffusivity or thermal conductivity (i.e. the values for `kv` and `kc` are zero).  Now maybe that was a purposeful choice, but if so then it might good to have a comment here explaining why, as I thought all gases have at least some diffusivity and conductivity value (but its been a long time since I took a p-chem or stat. mechanics class so I could just be forgetting something).

2022-07-29 19:21 UTC, nusbaume commented on src/utils/physconst.F90
> +   real(r8), public, protected :: Cpd_on_Cpv = shr_const_cpdair/shr_const_cpwv
That's fair.  I realized I made this suggestion before looking at the `physconst_init` subroutine where many of these values are modified.  I'll go ahead and marked this as resolved.

2022-07-29 19:26 UTC, gold2718 commented on src/utils/air_composition.F90
> +      end if
I guess so. I was hoping to avoid a repeated copy to a local inside the loop but it turned out that the variable was used in too many places to avoid uglyifying (technical term) the code too much.

2022-07-29 19:29 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     do kdx = SIZE(tracer, 2) - 1, 2, -1
An excellent question. My guess is that it should be
`do kdx = SIZE(tracer, 2), 2, - 1`

But I am unsure. @gold2718 @PeterHjortLauritzen ?

SIZE(tracer,2) is nlev

2022-07-29 21:18 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +     else
Yes but I would really like if we stopped using magic numbers and just used strings or public module parameters* (don't know why I didn't clobber this when I first saw it).

*or even public module parameters that are strings :)

2022-07-29 21:56 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +     do kdx = SIZE(tracer, 2) - 1, 2, -1
@PeterHjortLauritzen, does `Richardson_number(nlev)` need to be set? It is currently unset on the CAM trunk. As an `intent(out)` variable, the value could be anything.

2022-07-29 22:09 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +       end if
It is a tradeoff of code vs. lots of run-time copying of fields. We went with code although you pointed out some areas above where checks were not needed.

2022-07-29 23:55 UTC, peverwhee commented on src/dynamics/fv/dyn_comp.F90
> +   type (dyn_export_t), intent(in)  :: dyn_out   ! Export container
updated to intent(inout) per majority rule

2022-07-29 23:55 UTC, peverwhee commented on src/dynamics/se/dycore/prim_advection_mod.F90
> +    use hybvcoord_mod,          only : hvcoord_t
spaces removed

2022-07-29 23:55 UTC, peverwhee commented on src/physics/waccmx/ion_electron_temp.F90
> +    use cam_thermo,         only : cpairv
spaces removed

2022-07-29 23:55 UTC, peverwhee commented on src/physics/waccmx/ion_electron_temp.F90
> +    use physconst,  only : gravit ! Gravity (m/s2)
spaces removed

2022-07-29 23:55 UTC, peverwhee commented on src/physics/waccmx/steady_state_tei.F90
> +    use cam_thermo,       only : mbarv                       ! Constituent dependent mbar
spaces removed

2022-07-29 23:55 UTC, peverwhee commented on src/chemistry/mozart/mee_ionization.F90
> +    use cam_history,     only : outfld
spaces removed

2022-07-29 23:55 UTC, peverwhee commented on src/physics/cam/molec_diff.F90
> +  use air_composition, only : mbarv
spaces removed

2022-07-29 23:56 UTC, peverwhee commented on src/physics/waccm/nlte_lw.F90
> +    use physics_buffer,  only : physics_buffer_desc
spaces removed

2022-07-29 23:56 UTC, peverwhee commented on src/utils/physconst.F90
> +   real(r8), public, parameter :: cday        = shr_const_cday       ! sec in calendar day ~ sec
fixed

2022-07-29 23:56 UTC, peverwhee commented on src/utils/physconst.F90
> +   real(r8), public, parameter :: tref        = 288._r8              ! Reference temperature
units added

2022-07-29 23:56 UTC, peverwhee commented on src/utils/physconst.F90
> +   real(r8), public, parameter :: rhoh2o      = shr_const_rhofw      ! Density of liquid water (STP)
all units changed to CF-standard units

2022-07-29 23:56 UTC, peverwhee commented on src/utils/physconst.F90
> +   ! Molecular weights
done (g mol-1)

2022-07-29 23:57 UTC, peverwhee commented on src/utils/physconst.F90
> +   real(r8), public, protected :: sday    = shr_const_sday   ! sec in siderial day ~ sec
nit picked

2022-07-29 23:57 UTC, peverwhee commented on src/utils/physconst.F90
> +   real(r8), public, protected :: mwh2o   = shr_const_mwwv   ! molecular weight h2o
moved up to molecular weights section (units not added since the header has the units for all of those)

2022-07-29 23:57 UTC, peverwhee commented on src/utils/physconst.F90
> +   real(r8), public, protected :: mwdry   = shr_const_mwdair ! molecular weight dry air
moved up to molecular weights section (units not added since the header has the units for all of those)

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +      real(r8),           intent(in) :: to_moist_factor(:,:)
to_moist_factor now optional and cam_thermo_update code cleaned up accordingly

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +      ! active_species_idx_dycore: array of indicies for index of
un-typoed

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +      ! tracedr: Tracer array
detypofied

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +      end if
redundant code removed

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +               mw = cnst_mw(ix)
replaced with air_species_info call

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +               mw = cnst_mw(ix)
replaced with air_species_info call

2022-07-29 23:58 UTC, peverwhee commented on src/utils/air_composition.F90
> +               mw = cnst_mw(ix)
replaced with air_species_info call

2022-07-29 23:59 UTC, peverwhee commented on src/utils/air_composition.F90
> +            else
dry_air_species_info changed to air_species_info

2022-07-29 23:59 UTC, peverwhee commented on src/utils/air_composition.F90
> +            mw = 2.0_r8 * cnst_mw(ix)
fixed and use statements removed

2022-07-29 23:59 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   ! get_rho_dry: dry densisty from temperature (temp) and
typo struck down with the great fury of the gods

2022-07-30 00:00 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +      end if
code replaced with a check to ensure dimension 1 of to_moist_factor (if present) is equal to ncol

2022-07-30 00:00 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +      end do
good call! code replaced with call to get_sum_species

2022-07-30 00:01 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     else
public module parameters DRY_MIXING_RATIO=1 and MASS_MIXING_RATIO=2 added. Also: checks added to ensure mixing_ratio is one of those two.

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +       end if
indeed. fixed

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     real(r8), intent(in)            :: dp(:,:)     ! dry pressure level thickness
fixed.

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     end do
redundant code removed.

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     else
check added.

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     else
check added.

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     end if
indeed. change made.

2022-07-30 00:02 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   ! get pressure from dry pressure and thermodynamic active species (e.g., forms of water: water vapor, cldliq, etc.)
changed to surface pressure

2022-07-30 00:03 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     real(r8), intent(in)   :: tracer_mass(:,:,:)                      ! Tracer array
units added

2022-07-30 00:03 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     real(r8), intent(in)   :: tracer_mass(:,:,:,:)                      ! Tracer array
units added.

2022-07-30 00:03 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +       end if
yep. fixed.

2022-07-30 00:03 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     integer,  dimension(thermodynamic_active_species_num)         :: idx_local
just to mess with you, Jesse. Fixed.

2022-07-30 00:03 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     integer,  intent(in)           :: get_at_interfaces             ! 1: compute kmvis and kmcnd at interfaces
I agree. changed to logical and associated calls updated

2022-07-30 00:04 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +             temp_local = .5_r8 * (temp(idx, kdx - 1) + temp(idx, kdx))
nit picked

2022-08-01 15:30 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
This is copy-paste WACCM-x code. @fvitt @hanli-liu can you help out here? Thanks

2022-08-01 15:49 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +     if (present(rho_dry)) then
I think that users would usually request either the interface value of rho or the layer mean value. One is not derived from the other (although one could choose that discretization). If a user were to request both then there is a duplication in the computation of R (which is only variable on WACCM-x setup). I would advocate for keeping code as is ...

2022-08-01 15:59 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +       end if
Good point Steve!

The original get_rho_dry was intended to have two options:

compute rho at interfaces or compute rho as layer means. 

The option to output pint and pmid was just so that one would not repeatedly re-compute pint and pmid when calling other thermo subroutines within the same code block). The current usage of get_rho_dry does not use pmid and pint. In hindsight I should just have left them out ... hence I suggest to remove pmid and pint as optional outputs so that code is not a combinatorial armageddon!

2022-08-01 16:03 UTC, PeterHjortLauritzen commented on src/utils/air_composition.F90
> +               thermodynamic_active_species_kc(icnst)  = 0.0_r8
This is copy-paste WACCM-x code. @fvitt @hanli-liu can you help out here? Thanks

2022-08-01 16:16 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +   real(r8), parameter :: kc4 = 0.69_r8
This is copy-paste WACCM-x code. @fvitt @hanli-liu can you help out here? Thanks

2022-08-01 16:59 UTC, hanli-liu commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
These are not unit conversions. The actual values of the viscosity/diffusion coefficients are 4.03x10^-7, 3.42x10^-7...etc. In the current coding, kv1, kv2... are set to 4.03, 3.42 etc and 10^-7 is multiplied at the end. To avoid confusion, it may be better to redefine the parameter values kv1, kv2 etc with 10^-7, and kc1, kc2 etc with 10^-5.

2022-08-01 17:11 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +     do kdx = SIZE(tracer, 2) - 1, 2, -1
Good catch!

The Richardson number loop should be

do k=nlev,2,-1

instead of 

do k=nlev-1,2,-1

2022-08-01 17:13 UTC, PeterHjortLauritzen commented
@nusbaume thanks for your thorough review. Let me know if I missed something or if my comment is unclear ...

2022-08-01 17:49 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +     if (present(rho_dry)) then
Thanks for the explanation!  Since it sounds like a user would generally only ever ask for either `rho` or `rhoi` I agree that there wouldn't be much benefit, so will go ahead and mark this as resolved.

2022-08-01 17:59 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
Thanks for the explanation @hanli-liu!  I would personally vote to move the `10^-7` and `10^-5` numbers to the parameter values themselves, if for no other reason then it helps avoid extra multiplications each time step during the calculation of the diffusion coefficients.  

@peverwhee I realize that this may change answers, but if the `richardson_number` bug fix does the same thing then it might not hurt to add this in for this PR as well.

2022-08-01 18:05 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
My vote would be to keep this PR bit-for-bit and any changes that cause answer changes go into a separate PR.

2022-08-01 18:11 UTC, gold2718 commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
> My vote would be to keep this PR bit-for-bit and any changes that cause answer changes go into a separate PR.

I would rather not leave a bug in the code now that we have found it.

2022-08-01 21:07 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +   public :: cam_thermo_calc_kappav
Thanks for double-checking for me!  I figured that was the case, but was feeling especially paranoid and so just wanted to make sure.  It is probably not a big-enough issue to worry about (at least for now), so I'll go ahead and mark this conversation as resolved.

2022-08-01 21:24 UTC, cacraigucar approved these changes

2022-08-02 15:26 UTC, PeterHjortLauritzen commented on src/physics/waccm/nlte_lw.F90
> +    use physics_buffer,  only : physics_buffer_desc
From @ hanli-liu regarding the origin of these functions: The equations can be found in Liu et al (2010, doi:10.1029/2010JA015586, equations 3-4). The original reference can be found in the paper (Banks and Kockarts, 1973).

2022-08-02 15:34 UTC, nusbaume commented on src/physics/waccm/nlte_lw.F90
> +    use physics_buffer,  only : physics_buffer_desc
Great, thanks for the citation @PeterHjortLauritzen and @hanli-liu!

2022-08-02 15:45 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +   real(r8), parameter :: kc4 = 0.69_r8
@peverwhee It looks like these values all come from the following manuscript:

Liu, H.-L., et al. (2010), Thermosphere extension of the Whole Atmosphere Community Climate Model, J. Geophys. Res., 115, A12302, doi:[10.1029/2010JA015586](https://doi.org/10.1029/2010JA015586).

So I would add a comment here that includes that citation.  I also still might vote for these variables to be moved to `air_composition` as well, but that's not as high of a priority as just getting the citation added.  Thanks!

2022-08-02 15:45 UTC, hanli-liu commented on src/utils/air_composition.F90
> +               thermodynamic_active_species_kc(icnst)  = 0.0_r8
That's right. In the domain we are considering, hydrogen's contribution to viscosity/diffusivity is small and thus not considered.

2022-08-09 17:39 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
@peverwhee I believe this modification can be applied here if issue #635 is resolved and still have it be bit-for-bit.

2022-08-09 17:40 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +     do kdx = SIZE(tracer, 2) - 1, 2, -1
@peverwhee I believe this modification can be applied here if issue #635 is resolved and still have it be bit-for-bit.

2022-08-19 03:28 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +       cnst_cnd = (kc1 * mmro2 * o2_mwi + kc2 * mmrn2 * n2_mwi) * mbar * 1.e-5_r8
Updates from #635 moved into cam_thermo.F90

2022-08-19 03:29 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +     do kdx = SIZE(tracer, 2) - 1, 2, -1
Updates from #635 moved to cam_thermo.F90

2022-08-19 03:29 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +   real(r8), parameter :: kc4 = 0.69_r8
citation added and variables moved to the air_composition module

2022-08-19 03:30 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +       end if
pmid and pint removed as optional outputs

2022-08-22 17:13 UTC, nusbaume approved these changes
Looks great now, thanks again for getting this all re-factored!

2022-08-26 21:11 UTC, fvitt approved these changes
Looks good. Thanks for separating out the non-constants from the physconst module.  I only had a few minor comments.  Hopefully these are bit-for-bit changes for all the test cases.

2022-08-26 21:11 UTC, fvitt commented on src/utils/cam_thermo.F90
> +module cam_thermo
How about a brief description here at the top of the module so I have to peruse through the module to figure out what this does.

2022-08-28 21:24 UTC, peverwhee commented on src/utils/air_composition.F90
> +   !---------------  Variables below here are for WACCM-X ---------------------
line removed

2022-08-28 21:25 UTC, peverwhee commented on src/utils/air_composition.F90
> +module air_composition
comment description added. 

as for namelist vs dynamic determination of the species, I'd vote that to be a future change and can make an issue for that if there's agreement - @gold2718 @nusbaume @cacraigucar

2022-08-28 21:27 UTC, peverwhee commented on src/dynamics/fv/dp_coupling.F90
> +! Call cam_thermo_update to compute cpairv, rairv, mbarv, and cappav as constituent dependent variables
I believe the comment is accurate in that cam_thermo_update calls air_composition_update, which computes the module variables cpariv, rairv, and mbarv and then uses cpairv and rairv to compute cappav. Hope that makes sense.

2022-08-28 21:27 UTC, peverwhee commented on src/utils/cam_thermo.F90
> +module cam_thermo
description added.

2022-08-28 21:27 UTC, peverwhee commented on src/dynamics/mpas/dp_coupling.F90
> +        ! Call cam_thermo_update to compute cpairv, rairv, mbarv, and cappav as
I believe the comment is accurate in that cam_thermo_update calls air_composition_update, which computes the module variables cpariv, rairv, and mbarv and then uses cpairv and rairv to compute cappav. Hope that makes sense.

2022-08-28 22:23 UTC, gold2718 commented on src/utils/air_composition.F90
> +module air_composition
The namelist should be correct (using defaults), however, I do not think we want to limit experimentation now or in the future.

2022-08-29 14:03 UTC, cacraigucar commented on src/utils/air_composition.F90
> +module air_composition
@gold2718 and @fvitt - It sounds like the current implementation in this PR is correct with the previous, but a new issue for expanded capabilities is requested.  Is this statement correct?  If so, then I agree with @peverwhee and we commit this as it is now implemented and open a new issue

2022-08-29 14:34 UTC, nusbaume commented on src/utils/air_composition.F90
> +module air_composition
I am also fine with making this a new issue (if I am understanding the request correctly).

2022-08-29 15:24 UTC, fvitt commented on src/utils/air_composition.F90
> +module air_composition
> > My suggest for the list of major species does not need to happen in this PR. It was just something to think about. I think you should go ahead and merge it in as it is.
> 
> @fvitt, is there a case where the "wrong" list of major species is selected by default? If so, I think we should fix that (e.g., via namelist defaults).

I don't believe so.

2022-08-29 15:26 UTC, gold2718 commented on src/utils/air_composition.F90
> +module air_composition
Okay. I will wait to see the new issue since at the moment, I do not understand the problem that needs solving.

2022-08-29 19:06 UTC, peverwhee commented on src/utils/air_composition.F90
> +module air_composition
As I'm making the issue, I'm leaning towards this being a confusing update that perhaps we shouldn't do. What we could do is have the model dynamically determine the major species, but have an optional namelist variable that you can use if you'd like to perform a test (eg toggle a species off). But I'm not sure if that would cause more confusion than anything.

2022-08-29 20:39 UTC, merged

2022-08-29 21:04 UTC, peverwhee commented on src/utils/air_composition.F90
> +module air_composition
Issue added: https://github.com/ESCOMP/CAM/issues/647 for further discussion