Corrections to WACCMX coordinate maps for oplus and geomag history grids
ESCOMP/CAM pull request #625
Opened 2022-07-22 19:09 UTC by fvitt

Fixes issue #624 

The follow test passes with these changes:
 SMS_D_Ln3_Vnuopc.ne5pg3_ne5pg3_mg37.QPX2000.izumi_nag.cam-outfrq3s

This PR moves this WACCMX test back to izumi_nag

2022-07-25 17:26 UTC, gold2718 approved these changes

2022-07-25 17:26 UTC, gold2718 commented on src/ionosphere/waccmx/edyn_init.F90
> +      end if
Yowza! This is similar to the fix that went into FV when PIO2 came along. I still can't figure out how this worked with previous versions of PIO2.

2022-07-25 18:47 UTC, fvitt commented on src/ionosphere/waccmx/edyn_init.F90
> +      end if
@gold2718 ,
I think more consistency checks where added to the latest version of PIO2.  

It is mysterious to my how this worked on cheyenne with pio2.5.7 (latest pio2 tag).  

I don't completely understand the fix.  I just mimicked what was done for fv_centers grid.

2022-07-26 16:56 UTC, nusbaume approved these changes

2022-07-26 16:56 UTC, peverwhee approved these changes

2022-07-26 18:36 UTC, cacraigucar requested changes
I never hit submit yesterday on this!

2022-07-26 18:40 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_cam"/>
I know this is addressing a bug with the NAG compiler with this compset/configuration and as such is correct to do.  Since the NAG regression test suite is already overloaded, is it possible to move a different WACCM NAG test to be GNU, so that the net result is that the number of NAG tests is not increased.

2022-07-27 14:07 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="nag" category="aux_cam"/>
Moved FW4madSD to gnu

2022-07-27 17:05 UTC, cacraigucar approved these changes

2022-08-03 20:22 UTC, merged