Cam zonal mean 01
ESCOMP/CAM pull request #629
Opened 2022-08-02 15:22 UTC by patcal

Initial Implementation of zonal_mean.F90 module for computing Zonal Mean values to answer issue #368.

Implemented usage to optionally apply a zonal mean filter in nudging.F90.

Note the usage description in the comments is for the stand-alone offline 
zonal_mean module. The usage description for the installed MPI version 
can be found at the top of the zonal_mean.F90 module.

2022-08-25 17:44 UTC, fvitt commented on src/physics/cam/nudging.F90
> +  real(r8),allocatable:: Zonal_Bamp3d(:,:)
@patcal You made the basis amplitude arrays global (ie, shared by all openMP threads) by declaring these at the module level.  Will this be thread safe?  This might be okay if these are used at timestep_init when the model is not threaded.

2022-08-26 20:16 UTC, fvitt commented on src/physics/cam/zonal_mean.F90
> +module Zonal_Mean
The name of this module clashes with `src/dynamics/fv/zonal_mean.F90`

2022-09-26 17:33 UTC, fvitt commented
@patcal The zonal mean utility seems to produce slightly different results when changing the number of MPI tasks.  Do you have any ideas why this might be the case?

2022-09-26 20:50 UTC, patcal commented
Hi @fvitt 
For me the shr_reprosum_calc() routine is a black box and I inferred the arguments 
for it from other usage cases. So I expect that there may be some optional arguments
that can be added to provide stable results. Based on the ~available~ documentation, I 
have no idea what they should be. There are differences in the arguments I use for this 
routine in the Zonal_Mean module where I was trying different settings, but that was just 
guesswork so it is possible that those optional arguments may be causing problems.

2022-09-27 17:28 UTC, fvitt commented
@patcal,
I have come to the conclusion that roundoff errors are occurring before the sum across the tasks takes place via `shr_reprosum_calc`.   There are differences in the last 1 or 2 of digits of the sums, depending on the number of mpi tasks (or PE layout).  I have yet to come up with clever way of dealing with the differences.

2022-09-29 22:20 UTC, nadavis-ncar commented
It would be helpful to have the option to zonally filter the target data in the same way as the model data. There are cases where we may want to use the same target data, but use either the full field or the zonal mean as we see fit. That way we wouldn't need to create multiple target datasets. For flexibility it should probably be a separate namelist option. E.g., Nudge_ZonalFilter_Model and Nudge_ZonalFilter_Target.

2022-09-29 22:51 UTC, nadavis-ncar commented
Disregard the above, I see how this propagates through to the target data as well.

2022-09-29 22:53 UTC, patcal commented
Patrick,

No, I overlook the changes where this propagates to the target data as
well. You can disregard my previous comment.

-Nick

Nicholas A. Davis <https://staff.ucar.edu/users/nadavis>
Atmospheric Chemistry Observations and Modeling
National Center for Atmospheric Research


On Thu, Sep 29, 2022 at 4:35 PM Patrick Callaghan ***@***.***> wrote:

> Hi @Nicholas Davis ***@***.***>
>
> That base functionality is already included. There is not a namelist
> interface for switching to
> zonal nudging yet, currently it is a hardcoded 'Nudge_ZonalFilter' flag
> that when toggled to true, filters
> 3D model and the 3D input target data to zonal mean values, and then
> applies nudging to the
> differences. So the target data does not need to be pre-processed with a
> zonal filter before
> reading it in. Were you suggesting options to be able to, for example,
> alternatively nudge 3D
> model states to zonal filtered target data?
>
> --> Patrick
>
>
> On Thu, Sep 29, 2022 at 4:20 PM nadavis-ncar ***@***.***>
> wrote:
>
>> It would be helpful to have the option to zonally filter the target data
>> in the same way as the model data. There are cases where we may want to use
>> the same target data, but use either the full field or the zonal mean as we
>> see fit. That way we wouldn't need to create multiple target datasets. For
>> flexibility it should probably be a separate namelist option. E.g.,
>> Nudge_ZonalFilter_Model and Nudge_ZonalFilter_Target.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ESCOMP/CAM/pull/629#issuecomment-1262875154>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AJMQHANKGK2OGBK3JDWVDS3WAYI2FANCNFSM55LSHE2A>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-09-30 16:32 UTC, fvitt commented
@patcal Are you okay with me pushing changes directly to your cam_ZonalMean_01 branch in your github fork?  Or would you prefer a pull request?

2022-09-30 17:10 UTC, patcal commented
@Francis Vitt ***@***.***> ,
Yes,  go ahead and push your mods to cam_ZonalMean_01.

On Fri, Sep 30, 2022 at 10:32 AM Francis Vitt ***@***.***>
wrote:

> @patcal <https://github.com/patcal> Are you okay with me pushing changes
> directly to your cam_ZonalMean_01 branch in your github fork? Or would you
> prefer a pull request?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/629#issuecomment-1263783297>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJMQHAKLDYLDWVG7MGA7CXTWA4I23ANCNFSM55LSHE2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-10 17:52 UTC, fvitt commented on src/physics/cam/nudging.F90
> +     elseif(Nudge_TSmode == 1) then   !***** FOR ZONAL MEAN VALUES WILL THIS OPTION BE A PROBLEM?? *****
@patcal Should we not allow zonal filtering when Nudge_TSmode == 1 ?

2022-10-10 17:54 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +       </entry>
@patcal Can you provide descriptions for these namelist options?

2022-10-10 18:01 UTC, patcal commented
@Francis Vitt ***@***.***>
TSmode was an option created in the early development of the nudging
module and I don't know if users ever use anything other than the default
setting.
This likely will go away in upcoming revisions to nudging, so I would not
spend time implementing zonal filtering for this option now.

--> Patrick



On Mon, Oct 10, 2022 at 11:52 AM Francis Vitt ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/physics/cam/nudging.F90
> <https://github.com/ESCOMP/CAM/pull/629#discussion_r991526916>:
>
> > @@ -1230,7 +1279,7 @@ subroutine nudging_timestep_init(phys_state)
>           ncol=phys_state(lchnk)%ncol
>           Target_S(:ncol,:pver,lchnk)=cpair*Target_T(:ncol,:pver,lchnk)
>         end do
> -     elseif(Nudge_TSmode == 1) then
> +     elseif(Nudge_TSmode == 1) then   !***** FOR ZONAL MEAN VALUES WILL THIS OPTION BE A PROBLEM?? *****
>
> @patcal <https://github.com/patcal> Should we not allow zonal filtering
> when Nudge_TSmode == 1 ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/629#pullrequestreview-1136366813>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJMQHAL7PLZXIIMBMCPGBVLWCRJW7ANCNFSM55LSHE2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-10 19:59 UTC, fvitt commented on src/utils/zonal_mean_mod.F90
> +      real(r8),intent(out):: O_Bamp (:)
@patcal It seems that the zdata input to ZonalProfile needs to be on the zonal average profile grid of size nlat, rather than on the cam physics grid (pcols,begchunk:endgrid).  Is this correct?  I don't see how this can be used in cam without having the input zdata on the zonal averaged grid.

2022-10-11 07:02 UTC, patcal commented
Hi @Nicholas Davis ***@***.***>

That base functionality is already included. There is not a namelist
interface for switching to
zonal nudging yet, currently it is a hardcoded 'Nudge_ZonalFilter' flag
that when toggled to true, filters
3D model and the 3D input target data to zonal mean values, and then
applies nudging to the
differences. So the target data does not need to be pre-processed with a
zonal filter before
reading it in. Were you suggesting options to be able to, for example,
alternatively nudge 3D
model states to zonal filtered target data?

--> Patrick


On Thu, Sep 29, 2022 at 4:20 PM nadavis-ncar ***@***.***>
wrote:

> It would be helpful to have the option to zonally filter the target data
> in the same way as the model data. There are cases where we may want to use
> the same target data, but use either the full field or the zonal mean as we
> see fit. That way we wouldn't need to create multiple target datasets. For
> flexibility it should probably be a separate namelist option. E.g.,
> Nudge_ZonalFilter_Model and Nudge_ZonalFilter_Target.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CAM/pull/629#issuecomment-1262875154>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJMQHANKGK2OGBK3JDWVDS3WAYI2FANCNFSM55LSHE2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-11 22:28 UTC, fvitt approved these changes

2023-01-11 22:29 UTC, fvitt commented
@cacraigucar , This PR is ready for other SEs to review.

2023-01-18 23:00 UTC, nusbaume approved these changes
Looks good!  Just a few small requests/questions.

2023-01-18 23:04 UTC, nusbaume commented on src/physics/cam/nudging.F90
> +     allocate(Zonal_Bamp3d(Nudge_ZonalNbasis,pver))
Whoops, forgot one last request.  Can you add `stat` checks to these `allocate` statements.

2023-01-19 21:36 UTC, cacraigucar requested changes

2023-01-19 21:36 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="prealpha"/>
Is it necessary to add a new test, or can one of the existing tests (FCnudged) be expanded to use this setup?

2023-01-19 21:36 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="gnu" category="aux_cam"/>
Curious why this test is using CAM4 physics instead of CAM6 (QPC6)?  Also, some tests were added with the TEM PR.  Could one of them be modified to handle what this is testing and we don't need to add a new aux_cam test?

2023-01-19 21:36 UTC, cacraigucar commented on src/physics/cam/nudging.F90
> +    if (allocated(Zonal_Bamp3d)) deallocate(Zonal_Bamp3d)
I would suggest moving these lines above `call ZM%final()`.  The reason being that if additional variables are deallocated in the future, they most likely will be placed at the end, and the call to `ZM%final` may become lost for someone looking quickly at the routine.

2023-01-19 21:36 UTC, cacraigucar commented on src/physics/cam/nudging.F90
>       call endrun('Varibale "PS" is missing in '//trim(anal_file))
`Varibale` should be `Variable` here and all the other lines where the typo occurs above

2023-01-20 18:46 UTC, fvitt commented on src/physics/cam/nudging.F90
> +   call MPI_bcast(Nudge_ZonalNbasis,   1, mpi_integer, mstrid, mpicom, ierr)
@cacraigucar Do I need to add checks after all the mpi_bcast calls?  If the MPI bast fails does it actually return an error code that can be dealt with?

2023-01-20 19:21 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="gnu" category="aux_cam"/>
QPC4 is a cheaper configuration and is sufficient for testing the new functionality.

2023-01-20 19:27 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="prealpha"/>
This is testing a different type of nudging and thus needs to be tested separately.  I would be OK with removing this from the prealpha list if we think the ne5 aux_cam test added below is sufficient.

2023-01-20 19:50 UTC, cacraigucar commented on src/physics/cam/nudging.F90
> +   call MPI_bcast(Nudge_ZonalNbasis,   1, mpi_integer, mstrid, mpicom, ierr)
According to:  https://www.mpich.org/static/docs/latest/www3/MPI_Bcast.html, there are a number of useful error codes that are returned.

2023-01-20 19:58 UTC, fvitt commented on src/physics/cam/nudging.F90
> +   call MPI_bcast(Nudge_ZonalNbasis,   1, mpi_integer, mstrid, mpicom, ierr)
@cacraigucar  There are 72 calls to mpi_bcast in this module.  Do I need to add checks after all of those mpi_bcast calls?

2023-01-20 20:16 UTC, fvitt commented on src/physics/cam/nudging.F90
> +   call MPI_bcast(Nudge_ZonalNbasis,   1, mpi_integer, mstrid, mpicom, ierr)
I have added all the checks.

2023-01-20 20:16 UTC, fvitt commented on src/physics/cam/nudging.F90
> +    if (allocated(Zonal_Bamp3d)) deallocate(Zonal_Bamp3d)
done

2023-01-20 20:16 UTC, fvitt commented on src/physics/cam/nudging.F90
>       call endrun('Varibale "PS" is missing in '//trim(anal_file))
fixed

2023-01-20 20:17 UTC, fvitt commented on src/physics/cam/nudging.F90
> +     allocate(Zonal_Bamp3d(Nudge_ZonalNbasis,pver))
done

2023-01-20 20:29 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="prealpha"/>
What about moving it to prebeta?  We don't expect it to fail, but it is a good "last ditch check"

2023-01-24 16:37 UTC, cacraigucar approved these changes

2023-01-25 16:18 UTC, merged