CAM answer changing bug fixes for SE dycore, SSTICE and thermodynamics
ESCOMP/CAM pull request #636
Opened 2022-08-09 19:27 UTC by cacraigucar

There were several answer changing bug fixes recently discovered in CAM.  They are grouped together is this PR.

Closes #633
Closes #634 
Closes #635

2022-08-09 19:55 UTC, nusbaume requested changes
Impressively quick turnaround!  However, I still think we need to make additional modifications in `physconst.F90` in order to avoid double-counting.

2022-08-09 19:55 UTC, nusbaume commented on src/utils/physconst.F90
> +   kv1 = 4.03_r8 * 1.e-7_r8, &
I think we also need to remove these scaling factors from `get_molecular_diff_coef` and `get_molecular_diff_coef_reference` as well.  Otherwise they'll be double-counted.

2022-08-09 23:46 UTC, fvitt reviewed
Can you explain the need for the changes in physconst?  How do those changes affect waccmx?

2022-08-10 00:08 UTC, cacraigucar commented
> Can you explain the need for the changes in physconst? How do those changes affect waccmx?

@nusbaume can explain more.  These were answer changing items from  PR #615 that @nusbaume identified as being changed.  There is more explanation in issue #635.  The answers are supposed to be roundoff, unless I implemented something wrong.

2022-08-10 04:45 UTC, gold2718 requested changes
Some cleanup for consistency

2022-08-10 04:45 UTC, gold2718 commented on src/utils/physconst.F90
> +          thermodynamic_active_species_kc(icnst)  = 56._r8 * 1.e-5_r8
I thought the point of this change was to move all the math into parameters so this should be:
```suggestion
          thermodynamic_active_species_kv(icnst)  = kv2
          thermodynamic_active_species_kc(icnst)  = kc1
```
Am I missing something? If not, similar changes should be made below (500, 501, 519, 520).

2022-08-10 14:35 UTC, nusbaume commented on src/utils/physconst.F90
> +          thermodynamic_active_species_kc(icnst)  = 56._r8 * 1.e-5_r8
Wow, I have no idea how I missed that, good catch!  I agree that we should replace all of these values with their respective parameters.

2022-08-10 14:39 UTC, fvitt commented
> > Can you explain the need for the changes in physconst? How do those changes affect waccmx?
> 
> @nusbaume can explain more. These were answer changing items from PR #615 that @nusbaume identified as being changed. There is more explanation in issue #635. The answers are supposed to be roundoff, unless I implemented something wrong.

Will you verify that the changes are no larger than roundoff?

2022-08-10 14:45 UTC, nusbaume commented
@fvitt @cacraigucar These changes were driven by confusion on what the `1.e-7_r8` and `1.e-5_r8` numbers were in `get_molecular_diff_coef` while reviewing the CAM thermo review (PR #615).  We were told there that these numbers were in fact part of the `kv` and `kc` parameters themselves, and so it was decided to move them to the parameter definitions instead of using them as an extra factor during the calculation of the molecular diffusivity/conductivity.

Since we are changing the order of operations, but not the equations themselves, it _should_ only have a roundoff effect.  If it doesn't then I agree that we have done something wrong here.

2022-08-10 19:30 UTC, cacraigucar commented on src/utils/physconst.F90
> +   kv1 = 4.03_r8 * 1.e-7_r8, &
done

2022-08-10 19:36 UTC, cacraigucar commented on src/utils/physconst.F90
> +          thermodynamic_active_species_kc(icnst)  = 56._r8 * 1.e-5_r8
Done. (though I used kc2 instead of kc1).  Even though they are the same value currently, I thought it should be kc2.

2022-08-10 22:22 UTC, gold2718 requested changes
After a close look, it seem there were uses of some of these constants without the `1.e-7` or `1.e-5` factors. Some of the uses are even in the exponent. What is the correct usage here and why the discrepancy?

2022-08-10 22:22 UTC, gold2718 commented on src/utils/physconst.F90
> +       cnst_cnd = (kc1*mmro2*o2_mwi + kc2*mmrn2*n2_mwi)*mbar
What do we do about lines below such as 1955, 1956, 2020, and 2021 that used `kc4` and `kv4` without the `1.e-7_r8` factor?

2022-08-10 22:22 UTC, gold2718 commented on src/utils/physconst.F90
> +             tref**kv4
You removed the scaling factor from `kv1` and `kv2`, however, `kv4` in this equation have been redefined with no change to the expression. What is the correct usage here?

2022-08-10 22:22 UTC, gold2718 commented on src/utils/physconst.F90
> +             tref**kc4
You removed the scaling factor from `kc1` and `kc2`, however, `kc4` in this equation have been redefined with no change to the expression. What is the correct usage here?

2022-08-10 23:26 UTC, cacraigucar commented
After @gold2718 pointed out that these variable are used with and without scaling, I am going to introduce a new set of variables that have scaled in the name (i.e. kc1scaled, etc.)   These will only replace the variables which have the scale factors in the equations.  The variables which do not have the scaling will be unchanged.  I will do a careful edit instead of responding to review comments.

2022-08-10 23:34 UTC, gold2718 commented
> I am going to introduce a new set of variables that have scaled in the name (i.e. kc1scaled, etc.) These will only replace the variables which have the scale factors in the equations. The variables which do not have the scaling will be unchanged

Since @hanli-liu indicated that the constants are correct _with_ the scale factors (in a post on [#615](https://github.com/ESCOMP/CAM/pull/615#discussion_r934736907)), I do not think this is correct. The question is what is the role of the the "non-scaled" variables currently in physconst.F90?

2022-08-10 23:40 UTC, fvitt commented
It seems to me that the 1.e-5 and 1.e-7 scaling factors should stay where they are currently used -- just define them once as parameters.

2022-08-10 23:47 UTC, cacraigucar commented
There are currently two proposals for this PR:

1. Leave the code as it is for the most part and replace 1.e-7_r8 with scale_v_factor and 1.e-5_r8 with scale_c_factor in all the appropriate places and make these values parameters.  Note that the variable names need to be something better than what I picked.  (@fvitt's  suggestion)  
2. Set kv1=4.03_r8 * 1.e-7_r8 and kv1_unscaled=4.03_r8 and make appropriate substitutions throughout the code (modification to @nusbaume's suggestion)

@gold2718's question on why these variables are scaled sometimes and not other times, might lend some thought onto which of these two approaches would be the best implementation

2022-08-11 02:39 UTC, nusbaume commented
I would personally still vote to have the factors applied directly to all of the parameter except `kv4` and `kc4`, because those are the only parameters that are exponents as opposed to multiplicative factors.  Basically just check out equations 3 and 4 here:

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2010JA015586

I am happy if we want to rename them from `kv4` to something like `kv_temp_exp` that indicates why they don't contain the scaling factor.  If the scaling factors are being applied inside an exponent, or the non-exponent parameters are being applied somewhere without the parameter, then my guess is that either the equations in the paper are wrong, or that is an actual physics bug.

I also am voting to apply these scaling factors in the parameters simply because it saves the literal number of multiplications that have to be done in the model.  If we leave them as an extra factor then aren't we doing extra multiplications every timestep as opposed to just once during the creation of the parameter itself?  Of course I realize this is likely not a very big cost, and maybe the compiler is smart enough to parameterize it automatically, but it just seems like we are making the code do extra work.   

However, if we find that this method simply doesn't produce round-off level differences then as an alternative I would certainly vote instead for @fvitt's suggestion, which probably can just be applied in the Thermo PR and doesn't need to be done here.

2022-08-11 03:56 UTC, gold2718 commented
> ... as opposed to just once during the creation of the parameter itself?

As an FYI, the "creation of the parameter" is done at compile time and the machine value sits in code space (not data space).

2022-08-11 15:24 UTC, fvitt commented
The equations are a little tricky for me.  If @nusbaume's suggestions are no larger than roundoff than go with that.

2022-08-11 20:09 UTC, cacraigucar commented on src/utils/physconst.F90
> +          thermodynamic_active_species_kc(icnst)  = 56._r8 * 1.e-5_r8
These values do not have the scaling factor when they are saved and subsequently used, so I am going to leave them as the hardcoded numbers.  I could use the scaled numbers and divide by the scaling factor if that is preferred.

2022-08-11 20:31 UTC, nusbaume commented on src/utils/physconst.F90
> +          thermodynamic_active_species_kc(icnst)  = 56._r8 * 1.e-5_r8
Actually the scaling factor is applied to them.  Note that, for example, `thermodynamic_active_species_kv` is only used in one place (in the entire  code base), and that is in the calculation of `kmvis` in `get_molecular_diff_coef`.  Note then too that immediately after the loop over the different constituents the `kmvis` variable is then multiplied by the scale factor `1.e-7_r8` (which is the one we'll remove).

I might end up looking like a fool on this (in which case I owe you multiple preliminary code reviews), but I am pretty sure you just need to do the following:

1.  Add the scale factors to the parameter definitions _except_ for `kv4` and `kc4`, which might need to be renamed to indicate that they are exponents.

2.  Replace the various numbers in the setting of `thermodynamic_active_species_kv` and `thermodynamic_active_species_kc` with their respective parameter equivalent.

3.  Remove all `1.e-7_r8` and `1.e-5_r8` numbers from  `get_molecular_diff_coef` and `get_molecular_diff_coef_reference`.

The following model differences should then only be due to a (algebraically valid) change in the order of operations.

2022-08-16 20:35 UTC, fvitt commented on src/utils/physconst.F90
> +               kmcnd(i,j,k) = kmcnd(i,j,k)*mbarvi*temp_local**kc_temp_exp
What happened to the 1.e-7 and 1.e-5 factor here?

2022-08-16 21:48 UTC, cacraigucar commented on src/utils/physconst.F90
> +               kmcnd(i,j,k) = kmcnd(i,j,k)*mbarvi*temp_local**kc_temp_exp
The thermodynamic_active_species_kv (and _kc) now have the factors in them.  Those values are then summed in kmvis and kmcnd and the scaling was done at the end.    I believe that this is equivalent arithmetically, but if not, let me know.

2022-08-16 21:53 UTC, fvitt commented on src/utils/physconst.F90
> +               kmcnd(i,j,k) = kmcnd(i,j,k)*mbarvi*temp_local**kc_temp_exp
Ah okay.   Thanks for explaining.

2022-08-17 17:43 UTC, fvitt approved these changes

2022-08-17 17:45 UTC, gold2718 approved these changes
I like these changes and the answer changes seem acceptable.

2022-08-17 22:22 UTC, jtruesdal approved these changes

2022-08-18 18:00 UTC, merged