Upper boundary conditions specification via namelist
ESCOMP/CAM pull request #643
Opened 2022-08-23 16:53 UTC by fvitt

fixes #642

2022-08-23 17:24 UTC, cacraigucar commented
@nusbaume, @gold2718 and @peverwhee - I have assigned all of us to be reviewers.  Keeping in mind that this PR is to document the code which they are currently running, I believe our review should concentrate on just finding any bugs or potential problems with the code.  Typos in comments are fine to correct, but actual code changes should be kept to "being critical".  Of course, my suggestion could be overruled by the group.

2022-08-25 03:22 UTC, nusbaume approved these changes
Looks good to me, although I also did a relatively quick review.  If the group would prefer a more thorough review just let me know (or ask for my review again).  Thanks!

2022-08-26 23:19 UTC, gold2718 requested changes
A few (hopefully minor) changes please.

2022-08-26 23:19 UTC, gold2718 commented on src/chemistry/mozart/upper_bc.F90
> +  public :: ubc_fixed_temp     ! true if temperature at upper bounary is fixed
Typo

2022-08-26 23:19 UTC, gold2718 commented on src/chemistry/mozart/upper_bc.F90
> +          if (index(ubc_source(n),'vmr')>0) then
I still think this is better as an `else if`.

2022-08-26 23:19 UTC, gold2718 commented on src/chemistry/mozart/upper_bc.F90
> +       !call add_default(hist_names(m), 2, ' ' )
Remove?

2022-08-26 23:19 UTC, gold2718 commented on src/chemistry/mozart/upper_bc.F90
> +          continue
I don't think this has any effect anymore but it could give someone the wrong idea about what was intended. Remove?

2022-08-26 23:19 UTC, gold2718 commented on src/chemistry/mozart/upper_bc.F90
> +          vmrndx = index(trim(ubc_source(m)),'vmr')
This is a supported code base so please put in the error check:
```suggestion
          mmrndx = index(trim(ubc_source(m)),'mmr')
          vmrndx = index(trim(ubc_source(m)),'vmr')
          if (mmrndx>0 .and. vmrndx>0) then
             call endrun(prefix//'incorrect units in UBC source: '//trim(ubc_source(m)))
          end if
```

2022-08-26 23:19 UTC, gold2718 commented on doc/ChangeLog
> +Describe any substantial timing or memory changes:
Please document lack of changes (e.g., `NA`).

2022-08-26 23:19 UTC, gold2718 commented on doc/ChangeLog
> + - for regression tests
Is there a regression test that uses these? If not, why add these to the PR?

2022-08-30 16:45 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +		  'T->MSIS', 'H->MSIS', 'N->MSIS','O->MSIS', 'O2->MSIS', 'H2->TGCM', 'NO->SNOE'
done

2022-08-30 16:45 UTC, fvitt commented on src/chemistry/mozart/upper_bc_file.F90
> +       !call add_default(hist_names(m), 2, ' ' )
removed

2022-08-30 16:45 UTC, fvitt commented on src/chemistry/utils/mo_msis_ubc.F90
> +      endif
done

2022-08-30 16:46 UTC, fvitt commented on src/control/runtime_opts.F90
> +   call ubc_readnl(nlfilename)
No.  Order does not matter.

2022-08-30 16:47 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +  public :: ubc_fixed_temp     ! true if temperature at upper bounary is fixed
fixed

2022-08-30 16:47 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +          if (index(ubc_source(n),'vmr')>0) then
changed as suggested

2022-08-30 16:47 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +       !call add_default(hist_names(m), 2, ' ' )
removed

2022-08-30 16:47 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +          continue
removed

2022-08-30 16:47 UTC, fvitt commented on src/chemistry/mozart/upper_bc.F90
> +          vmrndx = index(trim(ubc_source(m)),'vmr')
done

2022-08-30 16:47 UTC, fvitt commented on doc/ChangeLog
> +Describe any substantial timing or memory changes:
done

2022-08-30 16:51 UTC, fvitt commented on doc/ChangeLog
> + - for regression tests
removed

2022-09-01 18:53 UTC, gold2718 approved these changes
Just need a minor change in the ChangeLog, otherwise looks good.

2022-09-13 23:46 UTC, merged