Abstract aerosol interfaces in ice nucleate
ESCOMP/CAM pull request #656
Opened 2022-09-21 20:14 UTC by fvitt

closes #648

2022-10-14 21:07 UTC, gold2718 reviewed
I'm trying to understand this and have a few questions.

2022-10-18 22:28 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    end if
Sulfate is the only  "_strat" type for now.  I don't know how I feel about having a function that truncates the type string.   If there were more "_strat" types I could see your point.

2022-10-18 22:28 UTC, fvitt commented on src/physics/cam/microp_aero.F90
> +   end if
These were moved as suggested.

2022-10-18 22:28 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     ! return aerosol bin size weights for a given bin, column and verical layer
fixed

2022-10-18 22:33 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_state_mod.F90
> +
This is no longer relevant.  I have implemented `update_bin` method and removed these incomplete methods which where used only for the CARMA aerosols.

2022-10-18 22:34 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_state_mod.F90
> +
No longer relevant.

2022-10-18 22:34 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       import
fixed

2022-10-20 16:37 UTC, nusbaume requested changes
Looks good!  I mostly just have some typo and parameter suggestions (and wanted to get them in before I go MIA).

2022-10-20 22:53 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +      dust_num_col(:ncol,:) = naer2(:ncol,:,idxdst1)/25._r8 *1.0e-6_r8 &
Added `per_cm3` parameter.  Does this make sense?

2022-10-20 22:54 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     subroutine aero_species_name(self, bin_ndx, species_ndx, specname)
This subroutine was not used.  I removed it.

2022-10-20 22:54 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     ! returns constituent name of ambient aersol number mixing ratios
fixed

2022-10-20 22:54 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     ! returns constituent name of ambient aersol mass mixing ratios
fixed

2022-10-20 22:55 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     procedure(aero_icenuc_size_wght2), deferred :: icenuc_size_wght2
Used your suggestions on the names.

2022-10-20 22:55 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +      allocate(aer_cnst_idx(aero_props%nbins(),0:maxval(aero_props%nspecies())))
Done

2022-10-20 22:55 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +                  ! this aerosol constituent will need to updated
fixed

2022-10-20 22:56 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +                                 ! this aerosol constituent will need to updated
Corrected the grammar here

2022-10-21 15:55 UTC, nusbaume requested changes
I think some of the "hidden conversation" questions/suggestions above were missed.  I tried to mark them again but not 100% sure how that will show up on your end.  Otherwise just one extra comment addition request.

2022-10-21 15:55 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +                  + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*1.0e-6_r8
Missed question/suggestion.

2022-10-21 15:55 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    character(len=32) :: spectype, sptype
Missed question/suggestion.

2022-10-21 15:55 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +            + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*1.0e-6_r8
Missed question/suggestion.

2022-10-21 15:55 UTC, nusbaume commented on src/physics/cam/nucleate_ice_cam.F90
> +   real(r8), parameter :: per_cm3 = 1.e-6_r8
I might just add a comment here saying something like:

`Conversion factor for cubic meters to cubic centimeters`

Or something like that, just to be really clear to future users/developers.

2022-10-25 19:06 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +                  + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*1.0e-6_r8
Changed as suggested

2022-10-25 19:07 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +            + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*1.0e-6_r8
Changed as suggested

2022-10-25 22:23 UTC, gold2718 approved these changes
Looks good in broad strokes (translation, I did not scrape through every last line of code).

2022-10-25 23:09 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +            + size_wghts(:ncol,:)*type_wghts(:ncol,:)*num_col(:ncol,:)*rho(:ncol,:)*1.0e-6_r8
Turns out sulfate_strat is a special case and needs to be outside the species loop

2022-10-27 23:50 UTC, peverwhee approved these changes
Looks good - you can take or leave my suggestions about the variable name "l"

2022-10-27 23:50 UTC, peverwhee commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    character(len=32) :: spectype, sptype
I agree with Jesse that a parameter set to 32 would make changing these lengths in the future much simpler.

2022-10-27 23:50 UTC, peverwhee commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    do l = 1, aero_props%nspecies(bin_ndx)
can we use a variable other than "l"? (hard to search for; looks like "1"...)

2022-10-27 23:50 UTC, peverwhee commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       do l = 1,aero_props%nspecies(m)
same here - I'd prefer a different variable.

2022-10-27 23:50 UTC, peverwhee commented on src/physics/cam/nucleate_ice_cam.F90
> +            do l = 1, aero_props%nspecies(m)
here, too? A variable other than "l"?

2022-10-27 23:50 UTC, peverwhee commented on src/physics/cam/nucleate_ice_cam.F90
> +                        do l = 1, aero_props%nspecies(m)
and this l?

2022-10-31 17:34 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +       character(len=32), intent(out) :: specname ! species name
done

2022-10-31 17:35 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +   real(r8), parameter :: per_cm3 = 1.e-6_r8
done

2022-10-31 17:36 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    do l = 1, aero_props%nspecies(bin_ndx)
done

2022-10-31 17:36 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       do l = 1,aero_props%nspecies(m)
done

2022-10-31 17:36 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +            do l = 1, aero_props%nspecies(m)
done

2022-10-31 17:36 UTC, fvitt commented on src/physics/cam/nucleate_ice_cam.F90
> +                        do l = 1, aero_props%nspecies(m)
done

2022-11-01 19:16 UTC, merged