MAM5 camchem and MAM4 size parameters
ESCOMP/CAM pull request #669
Opened 2022-10-05 17:32 UTC by fvitt

closes #663 
closes #664 

As discussed in issue #664, this changes the size parameters for the coarse mode in MAM4. Thus, this changes answers for cam6 physics configurations (larger than roundoff).

2022-11-28 20:16 UTC, peverwhee requested changes
Couple of small requests & a question

2022-11-28 20:16 UTC, peverwhee commented on bld/namelist_files/namelist_defaults_cam.xml
> +<mam4_mode3_file rad="rrtmg" ver="strat" phys="cam6">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc</mam4_mode3_file>
Question that may not make sense: what precipitated this addition? Do we need to add a similar phys specification to one of the mam5 files?

2022-11-28 20:16 UTC, peverwhee commented on cime_config/config_component.xml
> +    <desc atm="CAM%DEV[%L58][%L93][%CCTS1][%MAM5]">CAM7 development physics:</desc>
perhaps fix alignment so the description itself lines up with the lines above

2022-11-28 23:58 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<mam4_mode3_file rad="rrtmg" ver="strat" phys="cam6">atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_sig1.2_dgnl.40_c150219.nc</mam4_mode3_file>
When phys is `cam_dev` we want to default for `mam4_mode3_file` to be `mam4_mode2_rrtmg_aitkendust_c141106.nc` in line 444.  We want to maintain the default for cam6. Thus, the `phys="cam6"` specifier was added.

2022-11-29 01:30 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FC2000mam5" grid="f19_f19_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
done

2022-11-29 01:30 UTC, fvitt commented on cime_config/config_component.xml
> +    <desc atm="CAM%DEV[%L58][%L93][%CCTS1][%MAM5]">CAM7 development physics:</desc>
done

2022-11-30 19:04 UTC, peverwhee approved these changes
thanks Francis!

2022-12-13 15:14 UTC, nusbaume approved these changes

2022-12-13 19:48 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FCLTHIST" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
Could this test use the ne5 grid for testing purposes?

2022-12-13 20:53 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FCLTHIST" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
@adamrher recommends using ne3pg3_ne3pg3_mg37 for coarse regression testing

2022-12-13 21:49 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne30np4" nlev="58" chem="trop_strat_mam5_vbs">atm/cam/inic/se/f.e22.FCnudged.ne30_ne30_mg17.release-cesm2.2.0_spinup.2010_2020.001.cam.i.2011-01-01-00000_L58_c220310.nc</ncdat
done

2022-12-13 22:23 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FCLTHIST" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
It turns out that the files are not yet ready for ne3pg3 grids.  @fvitt - would it be okay to update to that grid when the files are ready in an upcoming tag?  Until then, it sounds like ne16_ne16_mg17 is available and coarser than ne30pg3.  Could we use that grid in the interim?

2022-12-13 23:33 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FC2000mam5" grid="f19_f19_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
This 2-deg test uses 2 cheyenne nodes and runs in less than 10 minutes.  Is that not fast enough?

2022-12-13 23:40 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FC2000mam5" grid="f19_f19_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
That probably is fine, but as we add tests, especially at the aux_cam level, it does add up over time (both timing and output file sizes).  As we start moving our testing to the new vertical resolution grids, that too will increase our times and storage requirements for testing. I'm just trying to be frugal with our tests, but if you feel like 2 degrees is better to use for the tests instead of the 10 degree, I defer that decision to you.

2022-12-13 23:41 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FCLTHIST" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
After offline discussions, it appears that ne30pg3_ne30pg3_mg17 is the only resolution which is currently available.  We may revisit this resolution at a later date when we have more tests on the `LT` grid

2022-12-13 23:46 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FC2000mam5" grid="f19_f19_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
It seems that we are trying to support too many in CAM -- too many dycores, chemistry options, etc...

Maybe we can remove some tests like tests of MAM5 without chemistry which I don't think we want to support.

2022-12-13 23:59 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FC2000mam5" grid="f19_f19_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
Testing is definitely a balancing act.  If you would like to remove some tests (`aux_cam`, `prealpha `and/or `prebeta`) that you think are obsolete or no longer needed, I would encourage you to do so.  I am not concerned about the "extra" tests like `camchem`.

2022-12-14 18:41 UTC, cacraigucar approved these changes
If you can remove any regression tests, please do so (based on your comment)

2022-12-16 17:11 UTC, merged