Misc tag
ESCOMP/CAM pull request #680
Opened 2022-10-25 23:08 UTC by peverwhee

The only updates that haven't already been reviewed are the CAM thermo bug and addfld call removal (listed first)

### CAM thermo bug
Indexing bugfix for get_dp in cam_thermo.F90
closes #679 

### Remove CIN addfld call from convect_shallow
Removing because it doesn't have an associated outfld call.
closes #674

### Interpolate Output Fixes
Allows for single-precision (e.g. ndens = 2) interpolated output, and allows for variables with missing values (e.g. AODVIS) to be output correctly in the standard monthly average (h0) files, at least for certain SE-CSLAM grids.
closes #658
closes #644 
addresses #564 
was reviewed in #659 

### DAE Test Fixes
Needs a cmeps externals update to fix tests fully. Will bring cmeps external in with future Externals update PR.
closes #671 
addresses #670 
was reviewed in #671

### Data reader bug in WACCMX
fixes restart issue Cecile encountered
closes #672 
closes #667 
was reviewed in #672

2022-10-25 23:22 UTC, fvitt requested changes
some initial suggestions

2022-10-25 23:22 UTC, fvitt commented on doc/ChangeLog
> +           - add testmods for new WACCMX restart tests
```suggestion
           - add testmods for WACCM-SC chemistry restarts across the Dec 16 boundary
```

2022-10-25 23:22 UTC, fvitt commented on doc/ChangeLog
> +           - Add new WACCMX restart tests
```suggestion
           - Add new tests for WACCM-SC chemistry restarts across the Dec 16 boundary
```

2022-10-25 23:22 UTC, fvitt commented on doc/ChangeLog
> +           - WACCMX fix bug data reader
```suggestion
           - fix bug in data reader used for WACCM-SC loss rates input
```

2022-10-25 23:22 UTC, fvitt commented on doc/ChangeLog
> +Tag name: cam6_3_080
Looks like you have inadvertently repeated the change log for tag `cam6_3_080`

2022-10-25 23:29 UTC, peverwhee commented on doc/ChangeLog
> +Tag name: cam6_3_080
indeed I did! removed.

2022-10-25 23:29 UTC, peverwhee commented on doc/ChangeLog
> +           - WACCMX fix bug data reader
changed.

2022-10-25 23:29 UTC, peverwhee commented on doc/ChangeLog
> +           - Add new WACCMX restart tests
changed.

2022-10-25 23:29 UTC, peverwhee commented on doc/ChangeLog
> +           - add testmods for new WACCMX restart tests
thanks, francis! changed.

2022-10-25 23:42 UTC, fvitt approved these changes
Seem okay to me. Thanks.

2022-10-26 14:57 UTC, nusbaume approved these changes
Looks great, thanks @peverwhee!

2022-10-26 14:57 UTC, nusbaume commented on doc/ChangeLog
> +Github PR URL:
Just a reminder to not forget the PR URL here:

`https://github.com/ESCOMP/CAM/pull/680`

2022-10-27 19:25 UTC, peverwhee commented
@fvitt I'm getting DIFFs for this test: ERP_Ln9_Vnuopc.f19_f19_mg17.FWsc1850.cheyenne_intel.cam-outfrq9s

When you get a spare moment, can you take a look at these differences? Is this expected?

Cheyenne test directory: /glade/scratch/courtneyp/aux_cam_20221026152937/ERP_Ln9_Vnuopc.f19_f19_mg17.FWsc1850.cheyenne_intel.cam-outfrq9s.GC.aux_cam_20221026152937

2022-10-27 19:48 UTC, fvitt commented
@peverwhee Differences are expected for WACCM-SC due to the bug fix boundarydata.F90.  There is a correction in the initial read of multiple fields from an input file.

2022-10-27 20:00 UTC, peverwhee commented
@fvitt Thanks Francis

2022-10-27 20:44 UTC, jtruesdal approved these changes
Good job.  Reviewed this for Cheryl a little while ago with comments so everything looks good to go.

2022-10-27 22:52 UTC, peverwhee commented on doc/ChangeLog
> +Github PR URL:
added

2022-10-27 22:52 UTC, merged