Katetc/rainbows pr
ESCOMP/CAM pull request #702
Opened 2022-11-19 00:38 UTC by Katetc

Fixes #683 Add Diagnostic Rainbow Calculation

RAINBOWS!!! I'M NOT KIDDING!!!!111!

Does not change answers.

2022-11-21 22:32 UTC, andrewgettelman approved these changes
Thanks Kate. This looks good. I ran with CAM and CAM_DEV and verify that I can reproduce the results I was expecting. Good from my side.

2023-09-01 12:59 UTC, nusbaume requested changes
Looks good!  Just have a few minor change requests (it looks like a lot simply because I repeated the same comments for both cam and cam_dev).

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +! Spome rain (liquid > 1.e-6 kg/kg, convective precip > 1.e-7 m/s
Typo (`Spome` -> `Some`).

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam_dev/micro_pumas_cam.F90
> +use cam_logfile,    only: iulog
This line isn't needed because `iulog` is already being brought in below.

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8), parameter :: rb_pmin =85000.                       ! Minimum pressure for surface layer
I would include the `_r8` here:

```suggestion
   real(r8), parameter :: rb_pmin =85000._r8                    ! Minimum pressure for surface layer
```

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam_dev/micro_pumas_cam.F90
> +   real(r8), parameter :: rb_pmin =85000.                       ! Minimum pressure for surface layer
I would include the `_r8` here:

```suggestion
   real(r8), parameter :: rb_pmin =85000._r8                    ! Minimum pressure for surface layer
```

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam_dev/micro_pumas_cam.F90
> +   real(r8) :: rval
I would make `rval` a logical instead of a real, as that is how it is being used.

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam/micro_pumas_cam.F90
> +   ! Zero out diagnostic  out arrays
I might update this comment to match the one in cam_dev:

```suggestion
   ! Zero out diagnostic rainbow arrays
```

2023-09-01 12:59 UTC, nusbaume commented on src/physics/cam_dev/micro_pumas_cam.F90
> +! Spome rain (liquid > 1.e-6 kg/kg, convective precip > 1.e-7 m/s
Typo (`Spome` -> `Some`).

2024-04-01 20:49 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +   ! Rainbows: solar zenit angle (SZA)
Fixed

2024-04-01 20:49 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +   real(r8) :: rval
Made it a logical

2024-04-01 20:49 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +! Spome rain (liquid > 1.e-6 kg/kg, convective precip > 1.e-7 m/s
Fixed

2024-04-01 20:50 UTC, Katetc commented on src/physics/cam_dev/micro_pumas_cam.F90
> +use cam_logfile,    only: iulog
Removed

2024-04-01 20:50 UTC, Katetc commented on src/physics/cam_dev/micro_pumas_cam.F90
> +   real(r8), parameter :: rb_pmin =85000.                       ! Minimum pressure for surface layer
Fixed

2024-04-01 20:50 UTC, Katetc commented on src/physics/cam_dev/micro_pumas_cam.F90
> +   real(r8) :: rval
Made it a logical

2024-04-01 20:50 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +   ! Zero out diagnostic  out arrays
Fixed

2024-04-01 20:50 UTC, Katetc commented on src/physics/cam_dev/micro_pumas_cam.F90
> +! Spome rain (liquid > 1.e-6 kg/kg, convective precip > 1.e-7 m/s
Fixed

2024-04-09 20:32 UTC, nusbaume approved these changes
Everything looks great to me now, thanks!

2024-04-12 18:28 UTC, cacraigucar requested changes
My comments in cam/micro_pumas_cam.F90 also apply to cam_dev/micro_pumas_cam.F90

2024-04-12 18:28 UTC, cacraigucar commented on src/physics/cam/micro_pumas_cam.F90
> +
Is the code for this comment gone?

2024-04-22 18:10 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +         rlats, rlons                                      ! chunk latitudes and longitudes (radians)
I agree. Updated the variable declarations here in both files.

2024-04-22 18:10 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +! Converted Python code in a loop....
Removed this comment in both files

2024-04-23 17:30 UTC, cacraigucar approved these changes

2024-04-25 22:32 UTC, sjsprecious commented on src/physics/cam/micro_pumas_cam.F90
> +   do i = 1, ngrdcol
If I do not use SCM or SILHS (e.g., just the default F2000 compset), does `ngrdcol` equal to `ncol` in this case?

2024-04-25 22:32 UTC, sjsprecious commented on Externals.cfg
> +tag = ccs_config_cesm0.0.85
By changing the tag from `ccs_config_cesm0.0.99` to `ccs_config_cesm0.0.85`, the PUMAS GPU code won't be compiled correctly. Will the `ccs_config_cesm0.0.99` tag be brought separately later?

2024-04-26 00:58 UTC, Katetc commented on src/physics/cam/micro_pumas_cam.F90
> +   do i = 1, ngrdcol
If subcolumns are not on (SILHS or any other subcolumn source) then ngrdcol is equal to ncol. The SCM issue was a result of the ccs_config tag, but I'm not sure why.

2024-04-26 01:01 UTC, Katetc commented on Externals.cfg
> +tag = ccs_config_cesm0.0.85
The ccs_config_cesm0.0.99 tag was causing the single column model test to fail. I'm not sure why, and I don't think it's in the scope of this tag to figure it out. When you work with Brian to bring in the GPU test suite, hopefully you can find and address the problem. Or, if somebody else updates the externals for CAM, they will need to fix this test. I will update the description to note this.

2024-04-26 02:12 UTC, sjsprecious commented on Externals.cfg
> +tag = ccs_config_cesm0.0.85
Oh, thanks for the clarification. Do you have the steps to reproduce the failed single column model test?

2024-04-26 02:13 UTC, sjsprecious commented on src/physics/cam/micro_pumas_cam.F90
> +   do i = 1, ngrdcol
Thanks for the clarification. That is good to know.

2024-04-26 15:25 UTC, cacraigucar commented
@Katetc - Which test is the failing scm test?  I would suggest you add a prealpha test for it as well, so that when @fischer-ncar  updates the ccs_config (which I think he has already done, or may be doing with the next alpha tag), that the test fails at that level.  I assume that when you say scm, this is a SCAM test.  We want to make sure that we don't break SCAM with this next beta tag.

2024-04-26 15:28 UTC, Katetc commented
> @Katetc - Which test is the failing scm test? I would suggest you add a prealpha test for it as well, so that when @fischer-ncar updates the ccs_config (which I think he has already done, or may be doing with the next alpha tag), that the test fails at that level. I assume that when you say scm, this is a SCAM test. We want to make sure that we don't break SCAM with this next beta tag.

HI Cheryl, this test fails with the newest ccs_config tag: SCT_D_Ln7.T42_T42_mg17.QPC5.derecho_intel.cam-scm_prep and passes with the current one. So I'm rolling back the ccs_config tag in this PR. I'll open an issue about this. And I can add a prealpha marking to this test as well.

2024-04-26 17:24 UTC, Katetc commented
I have added this issue to be addressed regarding the ccs_config tag: https://github.com/ESCOMP/CAM/issues/1017

2024-04-26 20:06 UTC, Katetc commented
I have added this issue to be addressed regarding unexpected test DIFFs for HEMCO: https://github.com/ESCOMP/CAM/issues/1018

2024-04-26 20:08 UTC, merged