Katetc/new clubb cam6 3 080
ESCOMP/CAM pull request #712
Opened 2022-12-05 23:24 UTC by Katetc

Fixes #675

Merging in changes from cam_development and uwm development. Namelist rearrange to alphabetical order for ease of checking going forward.

2022-12-06 00:44 UTC, bstephens82 approved these changes

2022-12-06 23:15 UTC, adamrher requested changes
Request changes please. I noticed that some of the mods in the old clubb_intr, before my kitchen sink PR cleaning it up, have made there way back in (best example is the outfld call for rcm, trying to multiply it by 1000 to make it g/kg when it should be in kg/kg). It seems inevitable that I will miss something that I previously cleaned up and will get snuck back in ...

2022-12-06 23:15 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        do k=clubbtop(i),pver
comment to be removed after ensuring this branch doesn't crash:

I changed the depth of the active layer to be between pverp and clubbtop, instead of pverp and clubbtop+1. I think this is a better option since we are defining the active layer using the interface grid, not the mid-point grid from which it was defined. Therefore the interface above k_midpoint=clubbtop is k_interface=clubbtop.

2022-12-06 23:15 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) =  rtp2(:ncol,:)*1.0e6_r8
veto unit conversions as these are old mods and no longer consistent with units in history fields

2022-12-06 23:15 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    rtpthlp_output(:ncol,:) = rtpthlp_output(:ncol,:) * 1000._r8
veto unit conversions as these are old mods and no longer consistent with units in history fields

2022-12-06 23:15 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) = rcm(:ncol,:) * 1000._r8
veto unit conversions as these are old mods and no longer consistent with units in history fields

2022-12-06 23:15 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) = rcm_in_layer(:ncol,:) * 1000._r8
veto unit conversions as these are old mods and no longer consistent with units in history fields

2022-12-07 00:26 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_predict_upwp_vpwp                        > .false. </clubb_l_predict_upwp_vpwp>
Yes those are the right settings for those two flags.

2022-12-07 00:35 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_predict_upwp_vpwp                        > .false. </clubb_l_predict_upwp_vpwp>
just to be clear ```clubb_l_mono_flux_lim_spikefix``` increases the lower limit on variance for thlm? whereas ```clubb_l_mono_flux_lim_rtm=.true.``` limits the fluxes? It is these two pieces that we agree to use as the recipe for (mostly) eliminating spikes, right? Or am I forgetting something?

2022-12-07 01:12 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_predict_upwp_vpwp                        > .false. </clubb_l_predict_upwp_vpwp>
Right the thlm mfl flag should be true also. The um and vm flags should be false, at least until we turn on prognostic momentum fluxes (I believe the mfl would not operate on um and vm unless we were using prognostic momentum fluxes).

2022-12-07 17:00 UTC, cacraigucar reviewed
First round of review comments

2022-12-07 17:00 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +    real(r8), dimension(state%ncol,pverp+1-top_lev) :: &
I am not keen on having a large number of arrays dimensioned to be "ncol" instead of "pcols".  The reason being that it makes it much harder to keep track of array sizes since there will be a mixture of both as all variables which are stored in the pbuf need to be dimensioned "pcols".  Typically in CAM we always set arrays to be pcols and if we need to operate on only ncol of them, we do that via `(:ncol)`  @Katetc - Could you elaborate on why you made this modification? 

Note that the PUMAS code has a mixture of array dimensions and I found it cumbersome to need to check which array was which size when I was making mods.  I'm not sure I like to see this bleeding into the CLUBB code as well.

@nusbaume - do you have an opinion?

I realize at this late date, we probably don't have a choice but to accept these changes as reverting it back to pcols would be very time consuming.

2022-12-07 19:28 UTC, bstephens82 requested changes

2022-12-07 19:28 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_predict_upwp_vpwp                        > .false. </clubb_l_predict_upwp_vpwp>
Sorry when I was responding to this last night I was on my phone and I think I couldn't see the code you were referring to.  To give a more complete answer, the correct flag settings here are:
~~~
<clubb_l_mono_flux_lim_rtm                        > .true. </clubb_l_mono_flux_lim_rtm>
<clubb_l_mono_flux_lim_spikefix                   > .true. </clubb_l_mono_flux_lim_spikefix>
<clubb_l_mono_flux_lim_thlm                       > .true. </clubb_l_mono_flux_lim_thlm>
<clubb_l_mono_flux_lim_um                         > .false. </clubb_l_mono_flux_lim_um>
<clubb_l_mono_flux_lim_vm                         > .false. </clubb_l_mono_flux_lim_vm>
~~~
When we turn on prognostic momentum fluxes at some point (ie l_predict_upwp_vpwp=T) then we can presumably set the um and vm flags here to true. They are true in the UWM CLUBB repo (which uses prognostic momentum fluxes by default).

2022-12-07 19:28 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: 1
The default here is "2" now I believe.  I agree with Cheryl's comment about having the defaults here being possibly problematic.

2022-12-07 19:28 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: .true.
The default for this flag is false.

2022-12-07 19:28 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Default value here should be updated once it's fixed in namelist_defaults.

2022-12-07 19:28 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Default value here should be updated once it's fixed in namelist_defaults.

2022-12-07 19:28 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Default value here should be updated once it's fixed in namelist_defaults.

2022-12-07 19:46 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_penta_solve_method                         > 1       </clubb_penta_solve_method>
In the namelist_definitions file this is said to default to 0 (which was my expectation since this is new code that to my knowledge is somewhat experimental).  So should this be set to zero here?

2022-12-07 19:58 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: 0
These two lines I think need to be updated.  The parameter `clubb_tridiag_solve_method` only has one valid value currently, which is "1" (so that should be the default here---it's set correctly in namelist_defaults).  But the "Valid values" line should also be updated to reflect this.  Option "1" is lapack...I don't believe there's any other viable option.  CLUBB's code here will shut it down if this equals something other than the lapack option: https://github.com/larson-group/clubb/blob/873ae270b4c4c112e6e7da83ba0f7df4aff9b958/src/CLUBB_core/matrix_solver_wrapper.F90#L342-L359.

2022-12-07 21:12 UTC, Katetc commented
> Request changes please. I noticed that some of the mods in the old clubb_intr, before my kitchen sink PR cleaning it up, have made there way back in (best example is the outfld call for rcm, trying to multiply it by 1000 to make it g/kg when it should be in kg/kg). It seems inevitable that I will miss something that I previously cleaned up and will get snuck back in ...

Yes, Adam, and thank you for your help with this. After the last external update, our changes to clubb_intr.F90 didn't get pushed back to the UWM repo and they also did a lot of refactoring of this file this summer. This PR represents my best attempt at merging everybody's changes back together, but it is inevitable that some things don't merge exactly correctly. After this CAM PR we will make sure to push all these changes back into the UWM CAM repo.

2022-12-07 21:17 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    clubb_l_intr_sfc_flux_smooth = .false.  ! Add a locally calculated roughness to upwp and vpwp sfc fluxes
The clubb_l_intr_sfc_flux_smooth variable is the namelist flag for Colin's "patch" that I just added in this PR. Since it only applies to code in clubb_intr, I didn't add the variable to the clubb_config_flags_api that sets the default values for the rest of the variables in a call to set_default_clubb_config_flags_api. So, I guess the answer to your fist question (convention) is yes, they are set in the config_flags_api. And yes, this is an exception because it is a flag not actually used by clubb.

2022-12-13 23:06 UTC, Katetc commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
Ok, so, these are parameters introduced in this version of clubb_intr.F90 but the UWM guys didn't put them in the read namelist code. They actually don't seem to be in the namelist at the moment. There's no requirement that every logical parameter in clubb go into the CAM namelist, and I don't see that these were expected to be put into the namelist since they aren't in clubb_readnl. There are many other clubb parameters that aren't in clubb_readnl and aren't included in the CAM namelist. Similar to clubb_l_use_precip_frac, clubb_l_predict_upwp_vpwp and others. I assume these would be set using a source mod if somebody wanted to set them. And that UWM doesn't want them exposed to the namelist because they may not be a commonly used setting (or something they don't want us setting) in CAM.

2022-12-13 23:11 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_predict_upwp_vpwp                        > .false. </clubb_l_predict_upwp_vpwp>
Updated to these.

2022-12-13 23:12 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_godunov_upwind_wpxp_ta                   > .false. </clubb_l_godunov_upwind_wpxp_ta>
See comment above. Since UWM didn't put these in clubb_readnl, I think they don't want them exposed as namelist options.

2022-12-13 23:27 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
Ok so I was confused because the larson-group repo has this change with a fairly recent (February 2022) commit. But I have found all of the emails and this conversation: https://github.com/ESCOMP/CAM/issues/582 that explains the reasoning here. Reverted.

2022-12-13 23:35 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +      se_dis(i) = (te_a(i) - te_b(i))/(state1%pint(i,pverp)-state1%pint(i,clubbtop(i)))
This did trigger a test failure in one cheyenne test where clubbtop(i) == pverp and we had a divide by zero. I updated to check for that before doing the division. But, looking at your comment above, I just wanted to let you know this was possible.

2022-12-13 23:47 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      se_dis(i) = (te_a(i) - te_b(i))/(state1%pint(i,pverp)-state1%pint(i,clubbtop(i)))
ok, that was def. my fault. I need to go in and modify three lines of code to revert back then. I am going to try to do a PR against your branch correctly. stay tuned.

2022-12-14 00:29 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +       do i=1,ncol
Don't know why the PR isn't showing "outdated" but I did this.

2022-12-14 00:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) =  rtp2(:ncol,:)*1.0e6_r8
Ok so I just reimplemented  all of these changes and I had the distinct feeling that I've done this before. I think maybe I did integrate these changes back in but they ... got lost ... somewhere. I suspect I will find them on a branch in a different clone somewhere else.... Or an unsaved emacs file backup....

2022-12-14 00:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    rtpthlp_output(:ncol,:) = rtpthlp_output(:ncol,:) * 1000._r8
Veto'd

2022-12-14 00:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) = rcm(:ncol,:) * 1000._r8
Veto'd

2022-12-14 00:33 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) = rcm_in_layer(:ncol,:) * 1000._r8
Veto'd

2022-12-14 00:35 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_do_adv                           silhs="1" > .false. </clubb_do_adv>
Previously there was ONLY a silhs line and I wasn't sure what namelist_defaults was doing in the non-silhs case. I added the other line to be explicit about what happens in default cases.

2022-12-14 16:17 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_do_adv                           silhs="1" > .false. </clubb_do_adv>
Since you now have the default for all of CLUBB, I suggest you remove the line for SILHS, since it will be set for SILHS via line 1835.

2022-12-15 02:30 UTC, adamrher commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
OK that's fine by me if UWM doesn't want all namelists available at the CAM level. I propose we assume that if UWM puts it in the readnl subroutine, then it's intended for CAM namelists.  ```clubb_l_enable_relaxed_clipping``` is in readnl, whereas ```clubb_l_linearize_pbl_winds``` is not, I think.

2022-12-15 20:27 UTC, Katetc commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
Sorry Adam, I don't see clubb_l_enable_relaxed_clipping in the `namelist /clubb_params_nl/ ` list. It is in the MPI_BCAST calls, but not in the namelist list. This is why I don't think it should be add to the cam namelist.

2022-12-15 20:34 UTC, adamrher commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
ok, fine with me. ill resolve this convo once you remove the mpi bast call in readnl.

2022-12-15 21:53 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_penta_solve_method                         > 1       </clubb_penta_solve_method>
When I added both `penta_solve_method` and `tridiag_solve_method` to the clubb namelist files, I started with "0" for the same reasoning, but clubb crashed on the first timestep that way. I removed the namelist items and ran the test (and it worked) and the clubb log wrote out default values of 1 for both of these. When I put default values of 1 here, they work great. I'm running a test now to try `penta_solve=0` and `tridiag=1`. If that works I'm fine with that setting. But, the code suggests the defaults should be 1 for both.

2022-12-15 22:00 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: 1.0
Hmm. Ok, so Lscale_from_tau is false by default, so, technically, the defaults here are the default. I don't think we usually document special case defaults here. For instance, many of these CLUBB fields have different defaults when SILHS is turned on. Should I document that here too?

2022-12-15 22:03 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_penta_solve_method                         > 1       </clubb_penta_solve_method>
Ah, ok, I see what's going on...there is no "0" for penta_solve_method in the source code, it starts at "1" which is lapack, and then 2 and 3 are the newer experimental options.  So yeah I guess both should default to "1".

2022-12-15 22:36 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
>  Default: 0.3
I am totally in support of removing the Default: documentation here. So I did it.

2022-12-15 22:53 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_do_adv                           silhs="1" > .false. </clubb_do_adv>
Okee dokee

2022-12-15 22:54 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_penta_solve_method                         > 1       </clubb_penta_solve_method>
Yep. Test failed. Defaults are still 1.

2022-12-15 23:05 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: 0
Ah good catch. Updated.

2022-12-15 23:08 UTC, bstephens82 commented on bld/namelist_files/namelist_definition.xml
> +Default: 0
yeah I think this was why I thought lapack was "0" haha.

2022-12-15 23:09 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Removing the default values from this file because it's annoying for everybody to keep them up to date.

2022-12-15 23:09 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Removing the default values from this file because it's annoying for everybody to keep them up to date.

2022-12-15 23:10 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: .false.
Removing the default values from this file because it's annoying for everybody to keep them up to date.

2022-12-15 23:11 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: .true.
Removing the default values from this file because it's annoying for everybody to keep them up to date.

2022-12-15 23:11 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: 1
Removing the default values from this file because it's annoying for everybody to keep them up to date.

2022-12-15 23:42 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    real(r8), dimension(state%ncol,pverp+1-top_lev) :: &
Added some warning labels. Comments that point out appropriate usage for NCOL or PCOL arrays.

2022-12-20 18:58 UTC, zarzycki commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
> Similar to clubb_l_use_precip_frac, **clubb_l_predict_upwp_vpwp and others**. I assume these would be set using a source mod if somebody wanted to set them.

I assume this was a typo (or I'm misinterpreting), but we definitely want `clubb_l_predict_upwp_vpwp` to be exposed via the namelist (it currently is). :)

2022-12-20 19:04 UTC, zarzycki commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
FWIW, based on https://github.com/NCAR/amwg_dev/discussions/106#discussioncomment-3614557, we do apply a source mod to `advance_xm_wpxp_module` to change `l_enable_relaxed_clipping` as part of the CPT/CAM7 code. This now appears to be set as a default to .false. in `model_flags.F90` in the UWM repo.

```
l_enable_relaxed_clipping = .true.      !advance_xm_wpxp_module
```

So ideally we'd either set this to .true. across the board in the CLUBB external for CAM or we include it as a namelist option with a default of .false. to mimic CAM6 behavior but .true. for CAM_dev/CAM7. I think. I cannot remember why we toggled it to .true., I believe it had something to do with our runaway cooling over rough terrain in some 1deg simulations.

2022-12-20 19:09 UTC, zarzycki commented on src/physics/cam/clubb_intr.F90
> +
Looks good to me! The only difference from my previous PR is I nested this block inside the 1,ncol loop from above. I am not sure if optimal practice is to separate the thermodynamic surface flux setting (e.g., wpthlp_sfc and wprtp_sfc) from the momentum fluxes into two loops as above or if there should be one ncol loop with a nested if statement for the mom fluxes.

2023-01-05 23:20 UTC, Katetc commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
Ok, so, based on Colin's comment here, I did add clubb_l_enable_relaxed_clipping to the namelist list with a default value of .false. that can be changed by the camdev experiments.

2023-01-05 23:25 UTC, adamrher commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
ok thanks @Katetc and @zarzycki for catching this (before its too late!)

2023-01-05 23:26 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Default: 1.0
Ok, I removed all of the "Default" documentation from namelist_definition.xml except the "_history" fields which have a single default value and I think that is useful information in the webpage.

2023-01-05 23:27 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    temp2dp(:ncol,:) =  rtp2(:ncol,:)*1.0e6_r8
Done

2023-01-05 23:52 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +
I don't think it makes a lot of difference one way or the other. This way makes the most sense to me based on the namelists and macmic switches needed. Also, I have a vague feeling that pushing loops as low as possible is best for GPUs. But I could be wrong there.

2023-01-06 18:50 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_penta_solve_method                         > 1       </clubb_penta_solve_method>
Resolved.

2023-01-06 19:00 UTC, bstephens82 approved these changes
I didn't find anything that I had questions or comments about...thanks Kate!

2023-01-09 23:10 UTC, adamrher commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
@Katetc I'm still not seeing l_enable_relaxed_clipping in the namelist?

2023-01-09 23:16 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +      se_dis(i) = (te_a(i) - te_b(i))/(state1%pint(i,pverp)-state1%pint(i,clubbtop(i)))
this has been fixed as Kate merged my PR into this PR branch.

2023-01-09 23:37 UTC, Katetc commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
Well, there was one unpushed commit on my branch but I think it was my merge. So, I don't know if this commit was there before but the namelist was added [in this commit
](https://github.com/ESCOMP/CAM/pull/712/commits/9dd39370c5b519804479c6e160c85b9782c0e940)

2023-01-09 23:58 UTC, adamrher commented on bld/build-namelist
>     add_default($nl, 'clubb_l_e3sm_config');
i see it now. thx

2023-01-10 23:16 UTC, cacraigucar requested changes
One minor change requested

2023-01-10 23:16 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +Default: 25.0e-6 m
This is the default for CAM runs, but cam_dev has a different default.  This comment will most likely be wrong for CAM7

2023-01-11 19:12 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        do k=clubbtop(i),pver
As I was noodling around with this coed block I realized I broke this clubbtop / energy fixer in cam6_3_066, and have opened an issue: https://github.com/ESCOMP/CAM/issues/739. Resolving this convo without full testing since it won't pass the energy fixer until this new issue is resolved in another PR.

2023-01-11 22:40 UTC, nusbaume approved these changes
Looks good!  Just some very minor code clean-up stuff.

2023-01-11 22:40 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +    rho(:ncol,pverp)  = state1%ps(:ncol)/(rairv(:ncol,pver,lchnk)*state1%t(:ncol,pver))
Should these be explicitly looped over instead of using array slicing?  I noticed there were changes above where array slices were replaced with explicit loops, and it seems like doing that here would make things more consistent.  Plus it might make the actual code a little easier to read.

2023-01-11 22:40 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +        eps = rairv(i,k,lchnk)/rh2o
Can we make a `1._r8/rh2o` parameter and use that here instead of doing the division every time?

2023-01-11 22:40 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +    rrho(1:ncol) = (1._r8/gravit)*(state1%pdel(1:ncol,pver)/dz_g(1:ncol,pver))
You could replace `1._r8/gravit` with `rga` from `physconst` here.

2023-01-11 23:01 UTC, adamrher approved these changes
Sorry Kate, I found a handful of clubb_intr statements that were being reverted back to our old clubb_intr. Approving, assuming you will address them as the are straight forward.

2023-01-12 15:49 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +       ! Adjust surface stresses using winds from the prior macmic iteration
based on internal discussions with Colin and Thomas, we need to add this statement below:
"! based on Thomas Toniazzo's implementation in NorESM"

2023-01-12 16:16 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
FWIW, this is the set of defaults via build-namelist + namelist_defaults.xml that disagree with what we (cc: @bstephens82) have in: https://github.com/NCAR/amwg_dev/discussions/106#discussioncomment-3614557

If I add...

```
clubb_l_diag_lscale_from_tau=.true.
clubb_l_predict_upwp_vpwp=.true.
```

to user_nl_cam with `-phys cam_dev`

(new.txt is this PR, old.txt is my hand-modified sandbox)

```
zarzycki@cheyenne5:~/scratch/FHIST-ne30-free-x321/run> diff old.txt new.txt 
87c87
<  C_invrs_tau_N2_xp2           =   0.800000000000000     
---
>  C_invrs_tau_N2_xp2           =   5.000000000000000E-002
99a100
>  a3_coef_min                  =    1.00000000000000     
102a104,105
>  penta_solve_method =            1
>  tridiag_solve_method =            1
105,106c108,109
<  l_min_wp2_from_corr_wx =  F
<  l_min_xp2_from_corr_wx =  F
---
>  l_min_wp2_from_corr_wx =  T
>  l_min_xp2_from_corr_wx =  T
116c119
<  l_vert_avg_closure =  F
---
>  l_vert_avg_closure =  T
120,123c123,126
<  l_standard_term_ta =  T
<  l_partial_upwind_wp3 =  T
<  l_godunov_upwind_wpxp_ta =  T
<  l_godunov_upwind_xpyp_ta =  T
---
>  l_standard_term_ta =  F
>  l_partial_upwind_wp3 =  F
>  l_godunov_upwind_wpxp_ta =  F
>  l_godunov_upwind_xpyp_ta =  F
129c132
<  l_stability_correct_tau_zm =  F
---
>  l_stability_correct_tau_zm =  T
144c147
<  l_vary_convect_depth T
---
>  l_vary_convect_depth F
147c150,157
<  l_smooth_Heaviside_tau_wpxp =  T
---
>  l_smooth_Heaviside_tau_wpxp =  F
>  l_enable_relaxed_clipping =  F
>  l_linearize_pbl_winds =  F
>  l_mono_flux_lim_thlm =  T
>  l_mono_flux_lim_rtm =  T
>  l_mono_flux_lim_um =  F
>  l_mono_flux_lim_vm =  F
>  l_mono_flux_lim_spikefix =  T
```

Do we want to try and toggle these booleans when clubb_l_diag_Lscale_from_tau is true?

2023-01-12 21:50 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    rho(:ncol,pverp)  = state1%ps(:ncol)/(rairv(:ncol,pver,lchnk)*state1%t(:ncol,pver))
There's actually several lines of code above these that weren't changed to explicit loops, so I think, in context, it makes sense. Also, Adam had an important request about the code in these lines below, which I think takes precedence here. I want the code to look the way he left it in his clean-up PR. I suspect it will eventually be turned to loops, especially as the GPU support comes in this year.

2023-01-12 22:03 UTC, cacraigucar approved these changes

2023-01-12 23:53 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    clubb_penta_solve_method = unset_i,  & ! Specifier for method to solve then penta-diagonal system
Fixed

2023-01-12 23:53 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    clubb_l_linearize_pbl_winds,        & ! Code to linearize PBL winds
Added some "Flag" language

2023-01-12 23:54 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +      sfc_elevation, &    		          ! Elevation of ground			      	[m AMSL]			      	[m]
Lined everything up in an aesthetically pleasing manor.

2023-01-12 23:54 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    if( (cld_macmic_num_steps > 1) .and. (clubb_l_intr_sfc_flux_smooth) ) then
Removed

2023-01-12 23:55 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        eps = rairv(i,k,lchnk)/rh2o
Completed

2023-01-13 00:11 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    rrho(1:ncol) = (1._r8/gravit)*(state1%pdel(1:ncol,pver)/dz_g(1:ncol,pver))
Done

2023-01-13 00:11 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    rho(:ncol,1:pver) = state1%pmid(:ncol,1:pver)/(rairv(:ncol,1:pver,lchnk)*state1%t(:ncol,1:pver))
Sorry about this. I reverted this to the more recent code

2023-01-13 00:11 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    shalcu(:,pver) = 0.0_r8
Reverted, thanks for catching it!

2023-01-13 00:11 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        thv(i,k) = th(i,k)*(1.0_r8+zvir*state1%q(i,k,ixq))
Reverted

2023-01-13 00:12 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +       ! Adjust surface stresses using winds from the prior macmic iteration
Added

2023-01-13 00:30 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
@zarzycki it had occurred to me to do that. But I went immediately to (a) there's no doubt that these tunings will change, and add/subtract more namelist values not incl. in your list, so we should probably wait to hard code these until we have a more final configuration. (b) weariness about using Lscale flag to toggle on all these non Lscale namelists. (c) let's just finish this PR already --- we're going to have to do more clubb_intr PR's over the next months anyways (e.g., I broke the energy fixer: https://github.com/ESCOMP/CAM/issues/739).

I'm fully expecting to have to relay a pretty loaded user_nl_cam w/ preferred namelists to Cecile for our CAM7 evaluations.

2023-01-13 02:16 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
I think that is reasonable -- FWIW, I just tested and we can toggle everything except `l_vary_convect_depth`, `l_partial_upwind_wp3`, and `l_standard_term_ta` with simple user_nl_cam switches. Those 3 appear to be exposed in clubb_intr.F90 but do **not** have matches in namelist_definition.xml, so preview_namelist fails if one tries to set them in the case dir.

A couple quick thoughts. If @bstephens82 or @vlarson **absolutely** thinks we should change any of these bools in namelist_defaults, we should just do it, IMO.

If we could at least expose the above 3 variables to be toggled in user_nl_cam (by adding in build-namelist, namelist_defaults, and namelist_definition?) that would be extremely helpful, because then we can just inject a block of text for users to repro whatever our latest config is. Currently I hardcode them with CLUBB source mods, which is suboptimal.

2023-01-13 02:24 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
I 100% agree to expose those three namelists at the cam level. ```l_vary_convect_depth``` is very important to control for CLASP folks.

2023-01-13 13:23 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
Putting `l_vary_convect_depth`, `l_partial_upwind_wp3`, and `l_standard_term_ta` in the namelists sounds good to me.

2023-01-13 15:59 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +       ! Adjust surface stresses using winds from the prior macmic iteration
sorry we've moved the goal posts - it is now

"! implementation after Thomas Toniazzo (NorESM) and Colin Zarzycki (PSU)"

2023-01-13 16:30 UTC, zarzycki commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
OK, so perhaps we add them to CAM's namelist like other CLUBB logicals and have their defaults (for now) be:

```
l_vary_convect_depth F
l_standard_term_ta =  F
l_partial_upwind_wp3 =  F
```

which should match the internal CLUBB defaults. Then if we want to evaluate them moving forward they can be toggled in user_nl_cam. It is much easier to have a block of options carried about in user_nl_cam vs. asking folks to do sourcemods. Then in the future if we are 100% sure we want to switch them with the taus code we can do so in namelist_defaults (future PR).

Is that reasonable/doable, @Katetc?

2023-01-13 17:45 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
>  <clubb_l_stability_correct_tau_zm                 > .true.  </clubb_l_stability_correct_tau_zm>
This sounds like a great plan to me. Thanks, guys, for the quick discussion!

2023-01-13 23:56 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +       ! Adjust surface stresses using winds from the prior macmic iteration
Updated!

2023-01-17 03:19 UTC, zarzycki approved these changes

2023-01-17 04:35 UTC, merged