cam6_3_112: Refactor aerosol heterogeneous freezing process
ESCOMP/CAM pull request #714
Opened 2022-12-06 17:25 UTC by fvitt

Refactor heterogeneous freezing code to use abstract aerosol interfaces 
Closes #738

2022-12-14 13:31 UTC, tilmes commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8), parameter :: spechygro_pom = 0.1_r8            ! POM hygroscopicity
To be consistent, the hygroscopicity values should be in general not set here, but taking from the phys-props files. However, we may need to test if this makes a difference.

2022-12-14 13:44 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
> +         limfac = 0.01_r8 ! Limit to 1% of available potential IN (for BC), no limit for dust
I have not noticed before that there was this limit for BC and not for dust, maybe this is something where one could tune the amount of ice number (something Andrew is suggesting?) If that is the case, would it be something to add as a namelist variable?

2022-12-14 15:55 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +         limfac = 0.01_r8 ! Limit to 1% of available potential IN (for BC), no limit for dust
Yes these scaling factors for BC and dust should probably namelist parameters.

2022-12-14 15:57 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8), parameter :: spechygro_pom = 0.1_r8            ! POM hygroscopicity
Agree.  The hygroscopicity values should be set from the aerosol_properties object rather than hard wired in here.

2022-12-14 23:30 UTC, mattldawson reviewed
Looks great to me! Just a few minor comments about function descriptions

2022-12-14 23:30 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8), intent(out) :: numdens(:,:)         ! dust number densities (#/cm^3)
```suggestion
    real(r8), intent(out) :: numdens(:,:)         ! species number densities (#/cm^3)
```

2022-12-14 23:30 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       awcam(:ncol,:) = 0._r8
should this be `awfacm`?

2022-12-14 23:30 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  subroutine mass_factors(self, bin_ndx,  species_type, ncol, nlev, aero_props, rho, awcam, awfacm)
Should this be two functions? One to calculate the (BC+POA+SOA)/(BC+POA+SOA+SO4) ratio and one to calculate the mass density of species `species_type`?

2022-12-14 23:30 UTC, mattldawson commented on src/physics/cam/hetfrz_classnuc.F90
> +real(r8), parameter :: Mso4 = 96.06_r8
should some of these come from elsewhere, similar to @tilmes comment above?

2022-12-21 16:22 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  ! mass mean radius (meters)
Not sure.  @tilmes ?

2022-12-28 21:28 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +         limfac = 0.01_r8 ! Limit to 1% of available potential IN (for BC), no limit for dust
Scaling factors for BC and dust have been implemented as namelist parameters.

2022-12-28 21:31 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8), parameter :: spechygro_pom = 0.1_r8            ! POM hygroscopicity
These hygroscopicity factors now members aerosol properties object which are set from the phys-props files.

2022-12-28 21:31 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     ! returns TRUE if bin spc provides heterogeneous freezing nuclei
changed as suggested

2022-12-28 21:31 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +     ! return aerosol bin size weights for het freezing
changes as suggested

2022-12-28 21:32 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  ! coated fraction
changed as a suggested

2022-12-28 21:33 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  end function coated_frac
Good point.  The limits are now applied here.

2022-12-28 21:33 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8), intent(out) :: numdens(:,:)         ! dust number densities (#/cm^3)
changed as suggested

2022-12-28 21:33 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       awcam(:ncol,:) = 0._r8
Good catch.  Fixed.

2022-12-28 21:34 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +real(r8), parameter :: Mso4 = 96.06_r8
Fixed

2023-01-10 21:34 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +  subroutine mass_factors(self, bin_ndx,  species_type, ncol, nlev, aero_props, rho, awcam, awfacm)
Or maybe just include a description of what is being calculated in the function comments, if you want to avoid recalculating intermediate values?

2023-02-16 22:41 UTC, nusbaume requested changes
Looks good!  I do have some (hopefully small) change requests and questions though.

2023-02-17 21:02 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8),pointer :: aer_mmr(:,:)
We could use the same pointer (aer_mmr).  However, I prefer different pointers for the different aerosol species.

2023-02-17 21:03 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8) :: specdens
same comment here

2023-02-17 21:10 UTC, gold2718 commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    if ((trim(mode_name)/='aitken').and.(trim(mode_name)/='primary_carbon')) then
They might not be required but I think they make the code easier to read and show the intent of the logic (which is faster in your head, reading or recalling the rules of operator precedence)?

2023-02-17 21:53 UTC, nusbaume commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    if ((trim(mode_name)/='aitken').and.(trim(mode_name)/='primary_carbon')) then
Are you saying you don't have a daily Fortran operator precedence mantra?!

This is a good point, so I am happy to leave this line as-is.  However, I guess I would then recommend applying the "extra parentheses" idea to Line 389 just below here, i.e. change this:

`if ( trim(species_type)=='black-c' .or. trim(species_type)=='dust' ) then`

to

`if ( (trim(species_type)=='black-c') .or. (trim(species_type)=='dust') ) then`

Pinging @fvitt so he sees it.

2023-02-17 21:54 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8),pointer :: aer_mmr(:,:)
Fair enough!  I was going back and forth myself on whether to bring this up or not, so I'll go ahead and mark it resolved.

2023-02-17 21:55 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8) :: specdens
Same comment here as well.  I'll go ahead and mark it resolved.

2023-02-18 02:10 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc_cam.F90
> +   character(len=32) :: species_type
changed as suggested

2023-02-18 02:10 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   Dvap = 0.211e-4_r8*(temp/273.15_r8)*(101325._r8/pres)
done

2023-02-18 02:11 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   real(r8), parameter :: Ktherm_dst = 0.72_r8 ! clay
done

2023-02-18 02:11 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +      rgimm_aer = 2*vwice*sigma_iw/(boltz*t*LOG(aw*supersatice))
done

2023-02-18 02:11 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   do_imm = t <= 263.15_r8
done

2023-02-18 02:11 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   real(r8), intent(in) :: Acnt                       ! prefactor
done

2023-02-18 02:11 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   real(r8), intent(in) :: Adep                       ! prefactor
done

2023-02-18 02:11 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   rgdep=2*vwice*sigma_iv/(boltz*t*LOG(rhwincloud*supersatice))
done

2023-02-18 02:11 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    end do
done

2023-02-18 02:15 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    if ((trim(mode_name)/='aitken').and.(trim(mode_name)/='primary_carbon')) then
I agree with @gold2718 on this one and added parentheses to Line 389.

2023-02-18 02:15 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       frac(:ncol,:) = 0._r8
changed as suggested

2023-02-18 02:21 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +    end if
Yes the model will abort if all 3 species are not found.  I don't know how to set the factors if 3 species are not included in the aerosol model.  Someone would need to figure out what to do in such a configuration.   I feel that is outside the scope of this PR.

2023-02-18 02:26 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hetfrz_bc_scalfac>0.0D0</hetfrz_bc_scalfac>
corrected the Defaults in namelist definition file

2023-02-18 02:29 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hetfrz_dust_scalfac>0.05D0</hetfrz_dust_scalfac>
@tilmes Did we decide what the default hetfrz dust scaling factor should be?

2023-02-18 02:47 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<hetfrz_dust_scalfac>0.05D0</hetfrz_dust_scalfac>
@fvitt I'm going to add this to the itinerary for the Tues meeting. We need more AMP scientists' engaged with these changes.

2023-02-21 14:55 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +    end if
@fvitt Thanks for the explanation!  It sounds like my hypothetical situation will likely never come up (or if it does we can worry about it then).  So I'm happy with this code as-is.

2023-02-21 15:09 UTC, nusbaume approved these changes
Looks great to me now.  Thanks!

@cacraigucar feel free to start your review whenever you get the chance.

2023-03-10 20:55 UTC, jtruesdal commented
While reviewing some of this code for another PR I noticed some items that should be taken care of.

In these routines there seem to be a lot of magic numbers that should be commented and/or moved into variables.
Duplicated definitions of shared constants (boltz planck)
There are several naked 4* used in hetfrz_classnuc_cam.F90 that should be r8.

2023-04-05 15:59 UTC, fvitt commented
@cacraigucar 
After consulting with @tilmes, this is a high priority PR -- higher than #560 (HEMCO)

2023-04-06 03:23 UTC, nusbaume requested changes
Still looks good to me, although I do have a couple questions and one change request.

2023-04-06 03:23 UTC, nusbaume commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    integer, intent(in) :: species_ndx       ! species number
It doesn't look like `species_ndx` is being used here.  Will alternative versions of `soluble` likely need it?  If not then I might get rid of it here and in the abstract procedure definition.

2023-04-08 14:39 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +       do k = 1,nlev
done

2023-04-08 14:40 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     procedure :: soluble
changed as suggested

2023-04-08 14:42 UTC, fvitt commented on src/chemistry/aerosol/modal_aerosol_properties_mod.F90
> +    integer, intent(in) :: species_ndx       ! species number
Removed the species_ndx argument for now.  Can add it if other aerosol models need it.

2023-04-08 19:20 UTC, nusbaume approved these changes
Looks great now, thanks!!

2023-04-27 22:34 UTC, cacraigucar requested changes

2023-04-27 22:34 UTC, cacraigucar commented on src/physics/cam/hetfrz_classnuc.F90
>     ! mean free path: Seinfeld & Pandis 8.6
I know these aren't modified comments (here and below), but would it be possible to add the DOI for each of the comments which refer to a paper?

2023-04-27 22:34 UTC, cacraigucar commented on src/physics/cam/hetfrz_classnuc.F90
> +   if (do_imm) then
Is it appropriate to mention why the limitation for Temperature is below 263.15?

2023-05-01 14:10 UTC, fvitt commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8) :: pom_equivso4_factor_ = -huge(1._r8)
@mattldawson Do you have thoughts on this?

2023-05-01 14:38 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
>     ! mean free path: Seinfeld & Pandis 8.6
@tilmes Can you help with the DOIs?

2023-05-01 14:45 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc_cam.F90
> +   class(aerosol_state),optional, intent(in) :: aero_state
Removed the optional keywords here.

2023-05-01 14:46 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   if (do_imm) then
Don't know.  @tilmes ?

2023-05-02 18:39 UTC, mattldawson commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8) :: pom_equivso4_factor_ = -huge(1._r8)
My understanding is that using `bind(c)` avoids the name mangling problems (in theory).

In practice, I haven't run into problems with this. Here is a small example of some code we put together for a workshop that is mixed Fortran, C, and C++ that uses trailing underscores for data members in all three languages: https://github.com/NCAR/aerosol-workshop-driver (see e.g., `src/array/`)

That said, it's also not a big deal not to use the trailing underscores. It's just a style that's been adopted in some other languages (e.g., https://google.github.io/styleguide/cppguide.html#Variable_Names) that I thought might be useful but haven't seen much in Fortran.

2023-05-02 19:23 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
> +   if (do_imm) then
This is the temperature threshold for imm. freezing. We can add a comment

2023-05-02 19:25 UTC, cacraigucar commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8) :: pom_equivso4_factor_ = -huge(1._r8)
My only exposure to C/Fortran code was when I brought in the C ali code.  There (using other CESM examples as my guide), I needed to create a Fortran interface block to describe the interface and in that interface the name of the subroutine was "ali_" .  It looks like if I'd used bind(c) along with "use ISO_C_BINDING" I could have referenced it as "ali" in the interface block.    Since this aerosol code belongs to you folks, I defer to you on whether you keep the underscore convention or change it something which does not require the user to use bind(c).

2023-05-02 19:49 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
>     ! mean free path: Seinfeld & Pandis 8.6
https://doi.org/10.5194/acp-14-10411-2014

2023-05-02 19:53 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +   if (do_imm) then
-10 C

2023-05-02 20:39 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
>     ! water vapor diffusivity: Pruppacher & Klett 13-3
@tilmes doi

2023-05-02 20:39 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
>     ! G-factor = rhoh2o*Xi in Rogers & Yau, p. 104
@tilmes doi

2023-05-02 20:40 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +         ! Young (1974) first equ. on page 771
@tilmes doi

2023-05-02 20:40 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
> +         ! calculate T-Tc as in Cotton et al.
@tilmes doi

2023-05-02 20:58 UTC, fvitt commented on src/physics/cam/hetfrz_classnuc.F90
>     ! droplet terminal velocity after Chen & Liu, QJRMS 2004
@tilmes doi

2023-05-03 07:12 UTC, gold2718 commented on src/chemistry/aerosol/aerosol_properties_mod.F90
> +     real(r8) :: pom_equivso4_factor_ = -huge(1._r8)
First, I don't see any `bind(c)` here, is it being used? Is there any need for it?

Second, the underscore is on a private variable. If it ever needed to be changed, it could happen without affecting "user" (which I read as anyone _using_ the aerosol code).

Third, if a `bind(c)` becomes (or is?) necessary, that will happen in the aerosol code, not in "user" code. Since the function available to the "user" is a member of an object, there is usually some name mangling going on behind the scenes anyway so I doubt any conflict would arise.

So I think this naming scheme is fine (and easy to understand).

2023-05-12 17:27 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
>     ! droplet terminal velocity after Chen & Liu, QJRMS 2004
https://doi-org.cuucar.idm.oclc.org/10.1256/qj.03.41

2023-05-12 17:28 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
>     ! G-factor = rhoh2o*Xi in Rogers & Yau, p. 104
[https://doi.org/10.1175/1520-0469(1974)031<0768:TROCNI>2.0.CO;2](https://doi.org/10.1175/1520-0469(1974)031%3C0768:TROCNI%3E2.0.CO;2)

2023-05-12 17:28 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
> +         ! Young (1974) first equ. on page 771
doi: 10.1175/1520-0469(1974)031<0768:TROCNI>[2.0.CO](http://2.0.co/);2

2023-05-12 17:30 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
>     ! G-factor = rhoh2o*Xi in Rogers & Yau, p. 104
this is a text book https://link.springer.com/book/10.1007/978-0-306-48100-0

2023-05-12 17:30 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
>     ! water vapor diffusivity: Pruppacher & Klett 13-3
this is a text book https://link.springer.com/book/10.1007/978-0-306-48100-0

2023-05-12 17:32 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
>     ! water vapor diffusivity: Pruppacher & Klett 13-3
Seinfeld and Pandis: Book: ISBN: 978-1-118-94740-1

2023-05-12 17:32 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
>     ! G-factor = rhoh2o*Xi in Rogers & Yau, p. 104
Rogers & Yau, p. 104: not found currently... leave as is

2023-05-12 17:36 UTC, tilmes commented on src/physics/cam/hetfrz_classnuc.F90
> +         ! calculate T-Tc as in Cotton et al.
Still checking, but can be added later...

2023-05-12 17:37 UTC, tilmes approved these changes

2023-05-17 20:06 UTC, cacraigucar approved these changes

2023-05-18 20:13 UTC, merged