SOA and DMS updates for CAM without chemistry
ESCOMP/CAM pull request #727
Opened 2022-12-14 17:33 UTC by fvitt

closes #571

Draft PR for the time being.  Still working on details.

2022-12-14 17:42 UTC, fvitt commented
@Duseong @lkemmons @tilmes 
I think we need to apply the corresponding changes to `waccm_sc_mam4` mechanism which is being used by `cam_dev` physics. 
Preferably, the new `chem_mech.in` files would be produced by the chemistry Cafe.

2022-12-14 22:34 UTC, lkemmons commented
Updated CAM and WACCM-SC mechanisms have been created in the Chemistry Cafe and are available at:
/glade/u/home/emmons/mechanisms/MZ311_CAM_MAM4_20221214.in
/glade/u/home/emmons/mechanisms/MZ312_WACCM_SC_MAM4_20221214.in
I have not run any simulations with these.

2023-01-10 21:36 UTC, tilmes approved these changes

2023-01-12 23:07 UTC, nusbaume requested changes
Looks good, but I did have some questions/suggestions that would be good to get responses to.

2023-01-17 15:30 UTC, fvitt commented on bld/build-namelist
> +                . "+ 14.1167*farnescene_b'";
This would require updates to the namelist parsing code in external share code.  Will look into it.

2023-01-19 02:39 UTC, fvitt commented on bld/build-namelist
> +        my $abs_filepath = set_abs_filepath('atm/cam/chem/ocnexch/Csw_DMS_Lana2011_f09f09_1750_2100_20200717a.nc', $inputdata_rootdir);
fixed

2023-01-19 02:40 UTC, fvitt commented on bld/namelist_files/use_cases/2010_cam6.xml
> +<csw_cycle_yr>2000</csw_cycle_yr>
fixed

2023-01-19 02:40 UTC, fvitt commented on bld/namelist_files/use_cases/waccm_sc_2010_cam6.xml
> +<csw_cycle_yr>2000</csw_cycle_yr>
fixed

2023-01-19 02:43 UTC, fvitt commented on bld/build-namelist
> +                . "+ 14.1167*farnescene_b'";
I have a solution for this.  Updates are needed cmeps and cpl7 shr code.  See the updates to Externals.cfg.

2023-01-19 17:02 UTC, nusbaume approved these changes
Thanks for tackling this @fvitt!  I just have one question related to the new externals

2023-01-19 17:11 UTC, cacraigucar commented on Externals.cfg
> +branch = megan_expr
I think we (as CSEG) agreed that we wouldn't make tags with branches to personal repos.  @fvitt - Are you okay holding up this PR until you get the changes into the ESCOMP/CMEPS repo?  Another reason is that this tag will break in CESM testing as they will only be pointing to an ESCOMP/CMEPS tag.

2023-01-19 17:15 UTC, fvitt commented on Externals.cfg
> +branch = megan_expr
> I think we (as CSEG) agreed that we wouldn't make tags with branches to personal repos. @fvitt - Are you okay holding up this PR until you get the changes into the ESCOMP/CMEPS repo? Another reason is that this tag will break in CESM testing as they will only be pointing to an ESCOMP/CMEPS tag.

Sounds reasonable.  I agree we should get new externals tags first.

2023-01-20 05:57 UTC, jtruesdal requested changes
I had a few questions on the added functionality of srf_emis_specifier which now includes a factor in addition to the pathname of the precursor file. Do you expect to change these factors for runtime experimentation or for use in tuning the aerosols?  If these default values for the factors are expected to remain static I would suggest placing them in the precursor file with appropriate metadata and accessing them from there. If instead these factors are to become a new part of the namelist I would like to see a reference for how they were derived. The precursor files do have appropriate metadata regarding their creation but I don't see anything for the factors. Is there a paper that can be referenced?  I would like to see a comment/reference in build_namelist where the factors are appended to the precursor filename and in the code where they are used. Lastly there is also the web namelist documentation for srf_emis_specifier which will need to be updated. How do we keep track of that future documentation update?

2023-01-20 16:36 UTC, tilmes commented
@jtruesdal This is a good question, and I can give you some answers:

First the number that are used are not expected to change, unless we change our VBS scheme is CAMchem, which is not something we are planning to do in the near future.

To explain this better, in the original CAM version, we used SOAG emissions. Those were preprocessed before the model would run, and assumed predefined yields that were also applied to SOA precursor emissions like isoprenes etc based on some emission dataset maybe coming from the model itself or from emission inventories. This had caused a headache in the past, since mistakes happened on the preprocessing side. What we are doing here, we are removing the step of having to pre calculated those emissions, and instead apply the emission yields directly to the SOA precursor emissions that come from the land. This also has the advantage of making then much more interactive with the land model and more consistent. Instead of using the yields that were used to preprocess the emissions in the past, we derived new yields that are specific to our model. 

Duseong Jo has a paper that is close to be submitted and he describes how these yields were derived:
"SOA yields (used for the interactive emissions) have been calculated based on the VBS yields in CAM-chem. SOA yields for the first four bins and 50% of the fifth bin are summed up for each compound. Only half of the fifth bin yield is used, as it is the most volatile bin. We consider SOA yields from OH reactions only in this calculation, because reaction with OH is dominant for VOCs. Only low NOx yields are used in this study which is consistent with Tilmes et al. (2019), which is appropriate for global climate studies with 1॰ horizontal resolution of the model grid."

With that said and to answer your question, we do not want these factors to be used for tuning actives, and they are not expected to change. The paper should be submitted very soon to GMD so we should have a reference soon. If you like we can share a draft with you?   I am not sure how the software engineers best handle this, but I hope this helps to explain the details?

2023-01-20 16:38 UTC, fvitt commented
@Duseong @lkemmons @tilmes
Can one of you test my branch code I have under 
'''
 /glade/work/fvitt/camdev/soa_dms_updates
'''
I think I have uncovered a bug in the megan_specifier parser. Some of the terms at the end of the extra long megan_specifier for SOAE may have been ignored.

2023-01-20 18:18 UTC, Duseong commented
> @Duseong @lkemmons @tilmes Can one of you test my branch code I have under ''' /glade/work/fvitt/camdev/soa_dms_updates ''' I think I have uncovered a bug in the megan_specifier parser. Some of the terms at the end of the extra long megan_specifier for SOAE may have been ignored.

Thanks Francis, let me test it out. I already removed a few minor species from that megan_specifier parser to avoid some errors, but let's see. I will do a year run from your new repository and compare it against the previous run.

2023-01-20 18:36 UTC, lkemmons commented
@jtruesdal @tilmes @Duseong  -- I would like to further clarify: the 'srf_emis_specifier' provides the filenames used for anthropogenic and biomass burning emissions.  We use these emissions files for all sorts of CAM and CAM-chem simulations.  The factors included as prefixes to the filenames are specific for running CAM with simple chemistry, which has the new SOAE species.  You suggested including those factors in the "precursor files", which I guess you mean the emissions files.  By including the factors in the namelist we do not need to make any changes to the emissions files, which have many uses.  This makes it clear to users what they are, and makes it easy to change for user experiments or other changes in the future.  I recommend we keep the formulation as we have provided in the namelist (atm_in).  This will all get replaced when we switch to using HEMCO.

2023-01-20 21:34 UTC, jtruesdal commented
@lkemmons @tilmes @Duseong   Thank you very much for the background and I agree that appending the factors to the filenames makes sense for CAM. The remaining piece is a reference for the factors. a doi would be nice and concise if it will be available in time, but the first few sentences from description provided above would work as well. @cacraigucar is there anything to do as part of this PR to update the documentation for srf_emis_specifier?

2023-01-20 23:39 UTC, fvitt commented on bld/build-namelist
> +        my %soae_fctrs = ('BENZENE_an_srf_file' => '4.4323D0',
@jtruesdal @Duseong @tilmes @lkemmons 
Not sure how to document these SOAE emissions factors here.  This is my brief attempt.  Please provide the precise text you would like to see here.

2023-01-20 23:42 UTC, fvitt commented on Externals.cfg
> +branch = megan_expr
We now now new tags for the externals.

2023-01-21 00:11 UTC, jtruesdal commented on bld/build-namelist
> +        my %soae_fctrs = ('BENZENE_an_srf_file' => '4.4323D0',
Thanks Francis that would give a user enough of a foothold to understand where these came from.  If the github PR discussions will be around until this is all replaced by HEMCO then instead of 'doi provided when available' maybe just add

-- see https://github.com/ESCOMP/CAM/pull/727 discussion for additional detail.

jt

2023-01-21 00:19 UTC, jtruesdal commented on bld/build-namelist
> +        my %soae_fctrs = ('BENZENE_an_srf_file' => '4.4323D0',
Github replaced the full address for the PR with a link above. I think the code should have the text address for the link. (which I can't figure out how to type here as github keeps replacing it with number_sign 127)

2023-01-24 18:19 UTC, Duseong commented
Thanks again @fvitt, new factors after megan parser bug fix are available in this namelist file: 
/glade/u/home/cdswk/CAM-chem/SimpleSOA/f.e22.Fnudged.f09_f09_mg17.cam6_3_050.2013.NEW_PARA.vbs_yield_5th20p_meganfix/user_nl_cam

See "srf_emis_specifier" and "megan_specifier"



And there is one thing to note, we have to turn off "DMS_other_surface" emission when using online DMS scheme (OASISS).
'DMS -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/CMIP6_emissions_1750_2015/emissions-cmip6_DMS_other_surface_1750-2015_0.9x1.25_c20170322.nc'

This one has to be removed for OASISS, and to be read when OASISS is turned off. It would be great if you could make this automatically. Thanks!

2023-01-24 18:37 UTC, fvitt commented
@Duseong 

The "OASISS" DMS scheme is turned on with the following namelist setting, correct?

```
&ocean_emis_nl
 bubble_mediated_transfer               = .false.
 csw_cycle_yr           = 2000
 csw_specifier          = 'DMS -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/ocnexch/Csw_DMS_Lana2011_f09f09_1750_2100_20200717a.nc'
 csw_time_type          = 'CYCLICAL'
 ocean_salinity_file            = '/glade/p/cesmdata/cseg/inputdata/atm/cam/chem/ocnexch/SSS_climatology_f09f09_c20230110.nc'
/
```

2023-01-24 18:42 UTC, Duseong commented
@fvitt, That's correct, DMS is emitted from this OASISS scheme through "csw_specifier"
@tilmes, let us know if I missed something here.

2023-01-24 23:18 UTC, fvitt commented
@Duseong 
Please confirm I have implemented your updates correctly and the "DMS_other_surface" emissions file is not included when DMS is emitted from this OASISS scheme, as you expect.  My latest branch code can be found under:
/glade/work/fvitt/camdev/soa_dms_updates

2023-01-25 00:14 UTC, Duseong commented
> @Duseong Please confirm I have implemented your updates correctly and the "DMS_other_surface" emissions file is not included when DMS is emitted from this OASISS scheme, as you expect. My latest branch code can be found under: /glade/work/fvitt/camdev/soa_dms_updates

@fvitt I am trying to check namelist files, but I came across this error when "preview_namelists" or "case.build"
Could you help me figure this out?

-----------------------------------------------------------------------------------
Namelist default for variable stream_meshfile refers to unknown XML variable SSTICE_MESH_FILENAME.
Traceback (most recent call last):
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/utils.py", line 634, in import_and_run_sub_or_cmd
    mod = importlib.import_module(f"{compname}_cime_py")
  File "/glade/u/home/cdswk/python/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cice_cime_py'

During handling of the above exception, another exception occurred

Traceback (most recent call last):
  File "./case.build", line 256, in <module>
    _main_func(__doc__)
  File "./case.build", line 249, in _main_func
    dry_run=dry_run,
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/build.py", line 1295, in case_build
    return run_and_log_case_status(functor, cb, caseroot=caseroot)
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/utils.py", line 2435, in run_and_log_case_status
    rv = func()
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/build.py", line 1288, in <lambda>
    dry_run,
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/build.py", line 1163, in _case_build_impl
    buildlist,
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/build.py", line 693, in _build_checks
    case.create_namelists()
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/case/preview_namelists.py", line 97, in create_namelists
    case=self,
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/utils.py", line 644, in import_and_run_sub_or_cmd
    run_sub_or_cmd(cmd, cmdargs, subname, subargs, logfile, case, from_dir, timeout)
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/utils.py", line 685, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/glade/work/fvitt/camdev/soa_dms_updates/components/cice//cime_config/buildnml", line 341, in buildnml
    _create_namelists(case, confdir, namelist_infile, nmlgen)
  File "/glade/work/fvitt/camdev/soa_dms_updates/components/cice//cime_config/buildnml", line 161, in _create_namelists
    nmlgen.init_defaults(infile, config)
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/nmlgen.py", line 168, in init_defaults
    self.add_default(self._definition.get(entry, "id"))
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/nmlgen.py", line 706, in add_default
    default = self.get_default(name, allow_none=True)
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/nmlgen.py", line 383, in get_default
    default[i] = self.quote_string(scalar)
  File "/glade/work/fvitt/camdev/soa_dms_updates/cime/CIME/nmlgen.py", line 217, in quote_string
    if string == "" or (string[0] not in ('"', "'") or string[0] != string[-1]):
TypeError: 'NoneType' object is not subscriptable

-----------------------------------------------------------------------------------

2023-01-26 15:18 UTC, fvitt commented
@cacraigucar We now have the updates in and ready to move forward with this PR.

2023-01-26 16:44 UTC, cacraigucar commented
@fvitt - Have you addressed all of the comments that @jtruesdal made?  If so, we should ask for a re-review from him

2023-01-26 17:39 UTC, Duseong commented on src/chemistry/modal_aero/modal_aero_gasaerexch.F90
>        end do
That's correct, but we thought it's OK to remove this line, 
one reason is that's scientifically correct with our updates and the second reason is that there's another line to prevent zero for further calculations. 

a_opoa is used in lines 1320 or 1364 like below:
`a_ooa_sum_tmp(m) = a_opoa(m) + sum( a_soa(m,1:ntot_soaspec) )`


And this a_ooa_sum_tmp has another check to prevent zero like this (line 1368)
`sat(m,ll) = g0_soa(ll)/max( a_ooa_sum_tmp(m), a_min1 )`

2023-01-26 20:22 UTC, fvitt commented on bld/build-namelist
> +        }
If  `csw_time_type` is `CYCLICAL` a runtime error will occur with a message like:
```
 open_trc_datafile: cycle year not found :            0
 ERROR: open_trc_datafile: cycle year not found /terminator-data1/fvitt/inputdata/atm/cam/chem/ocnexch/Csw_DMS_Lana2011_f09f09_1750_2100_20200717a.nc
```

2023-01-26 20:51 UTC, cacraigucar commented on src/chemistry/modal_aero/modal_aero_gasaerexch.F90
>        end do
@Duseong - Thank you for the reassurance that zero values will not be creeping through.

2023-01-26 20:52 UTC, cacraigucar commented on bld/build-namelist
> +        }
@fvitt  - Is it worth trying to trap the error at the build level instead of the run level?

2023-01-26 21:15 UTC, fvitt commented on bld/build-namelist
> +        }
I added a check.

2023-02-06 16:54 UTC, cacraigucar approved these changes

2023-02-06 21:17 UTC, jtruesdal approved these changes

2023-02-07 17:13 UTC, merged