cam6_3_095: chemistry updates
ESCOMP/CAM pull request #737
Opened 2023-01-10 17:37 UTC by fvitt

Closes #558 

This PR changes answers not only for chemistry configurations but also for cam5 and cam6 without full chemistry due to updates to `DMS + OH` reaction rate parameters in `mo_usrrxt.F90`. 

In addition to addressing issue #558, this PR also updates the chemistry configurations to default MAM5 aerosols.

2023-01-11 02:31 UTC, lkemmons requested changes
There are new xs_long_file and xs_short_file files:
 xs_long_file = '/gpfs/fs1/p/acom/acom-climate/dkin/inputs/lut/temp_prs_GT200nm_c221005mm.nc'
 xs_short_file = '/gpfs/fs1/p/acom/acom-climate/dkin/inputs/lut/xs_short_c221005mm.nc'

2023-01-11 02:43 UTC, lkemmons requested changes
Need to update photolysis lut files, and minor correction in a comment.

2023-01-11 02:43 UTC, lkemmons commented on src/chemistry/mozart/mo_sad.F90
> +!     6 April     2022; update nat_part_dens from 1e-01 to 5.0e-4
This comment should be "from 1e-02"

2023-01-11 02:43 UTC, lkemmons commented on bld/namelist_files/namelist_defaults_cam.xml
> +<xs_long_file >atm/waccm/phot/temp_prs_GT200nm_c220622mm.nc</xs_long_file>
Sorry - there are newer files for these
 xs_long_file = '/gpfs/fs1/p/acom/acom-climate/dkin/inputs/lut/temp_prs_GT200nm_c221005mm.nc'
 xs_short_file = '/gpfs/fs1/p/acom/acom-climate/dkin/inputs/lut/xs_short_c221005mm.nc'

2023-01-11 17:44 UTC, fvitt commented on src/chemistry/mozart/mo_sad.F90
> +!     6 April     2022; update nat_part_dens from 1e-01 to 5.0e-4
Fixed

2023-01-11 17:44 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<xs_long_file >atm/waccm/phot/temp_prs_GT200nm_c220622mm.nc</xs_long_file>
Done

2023-01-24 17:15 UTC, lkemmons approved these changes
Looks good to me

2023-02-03 20:43 UTC, nusbaume approved these changes
Looks good, just some possible chemistry options list updates and some DOIs to add.

2023-02-03 20:43 UTC, nusbaume commented on src/chemistry/mozart/mo_usrrxt.F90
> +    real(r8), parameter :: gamma_no2  = 8.0e-6_r8       ! Liu et al., Environ.Sci.&Tech, 53, 3517, 2019
Does this `Liu et al.` paper have a DOI that could be pointed to here?

2023-02-03 20:43 UTC, nusbaume commented on src/chemistry/mozart/mo_sad.F90
> +!                       (Wilka et al., ACP, 2021)
Can you include the DOI here as well (`10.5194/acp-21-15771-2021`).

2023-02-03 21:35 UTC, lkemmons commented
for mo_usrrxt:
gamma_no2  = 8.0e-6_r8       ! Liu et al., Environ.Sci.&Tech, 53, 3517, 2019
doi:10.1021/acs.est.8b06367

2023-02-03 21:36 UTC, lkemmons commented on src/chemistry/mozart/mo_usrrxt.F90
> +    real(r8), parameter :: gamma_no2  = 8.0e-6_r8       ! Liu et al., Environ.Sci.&Tech, 53, 3517, 2019
doi:10.1021/acs.est.8b06367

2023-02-04 16:02 UTC, fvitt commented on bld/configure
> +                        [ trop_mam3 | trop_mam4 | trop_mam7 | trop_mozart |
fixed

2023-02-04 16:02 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +       group="phys_ctl_nl" valid_values="trop_mam3,trop_mam4,trop_mam7,trop_mozart,trop_strat_mam4_vbs,trop_strat_mam4_vbsext,trop_strat_mam5_vbs,
fixed

2023-02-04 16:03 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FCHIST" grid="ne0CONUSne30x8_ne0CONUSne30x8_mt12" name="ERS_Lh3_P720x1" testmods="cam/outfrq3h">
added

2023-02-04 16:03 UTC, fvitt commented on src/chemistry/mozart/mo_usrrxt.F90
> +    real(r8), parameter :: gamma_no2  = 8.0e-6_r8       ! Liu et al., Environ.Sci.&Tech, 53, 3517, 2019
done

2023-02-04 16:03 UTC, fvitt commented on src/chemistry/mozart/mo_sad.F90
> +!                       (Wilka et al., ACP, 2021)
done

2023-02-10 22:24 UTC, cacraigucar commented on src/chemistry/mozart/mo_usrrxt.F90
> +! OBSOLETE - for mechanisms prior to Dec 2022
Should these obsolete sections either be removed or have a warning/endrun?  Or is the ability to run these mechanisms still supported?

2023-02-10 22:24 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> -  <test compset="QPMAM5" grid="f10_f10_mg37" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq3s">
I wsa happy to see tests actually being deleted!  That said, since the defaults seem to be moving from mam4 to mam5, do we still need a test with mam4?  I looked and didn't see one, but I could have missed it

2023-02-10 23:17 UTC, lkemmons commented on src/chemistry/mozart/mo_usrrxt.F90
> +! OBSOLETE - for mechanisms prior to Dec 2022
No. Maybe 'OBSOLETE' was the wrong label.  These sections are needed if people want to run CMIP6 configurations with CAM6-chem, or with CAM5-chem - will these still be available?

2023-02-13 16:54 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> -  <test compset="QPMAM5" grid="f10_f10_mg37" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq3s">
It really depends on the level of support you folks think you will be providing for mam4 moving forward.  Is mam5 going to be the workhorse setup (it appears that it is) and mam4 is just being retained for historical and comparison purposes?  If that is the case, perhaps just a single test at aux_cam and one at prealpha would be sufficient, just to make sure that it still works.

2023-02-13 21:22 UTC, cacraigucar approved these changes

2023-02-15 15:08 UTC, merged