Cloud to ground lightning flash frequency passed to land model
ESCOMP/CAM pull request #747
Opened 2023-02-03 15:45 UTC by fvitt

Closes #567

2023-02-03 15:51 UTC, fvitt commented on src/chemistry/mozart/mo_lightning.F90
> +             cld2grnd_flash_freq(i) = cam_in(c)%landfrac(i)*flash_freq_land *cgic(i,c) * factor ! cld-to-grnd flash frq (per min)
@lkemmons Does this formulation look correct for the cloud-to-ground lightning flash frequency?  Is it correct to include `factor` here which is `0.1_r8*lght_no_prd_factor`, the namelist lightning NOx production rate tuning parameter.

2023-02-07 04:53 UTC, lkemmons commented on src/chemistry/mozart/mo_lightning.F90
> +             cld2grnd_flash_freq(i) = cam_in(c)%landfrac(i)*flash_freq_land *cgic(i,c) * factor ! cld-to-grnd flash frq (per min)
No, 'factor' is just for getting the right amount of NO emissions per flash, and should not be applied to the flash frequency that is passed to the land.

2023-02-07 04:54 UTC, lkemmons commented on src/chemistry/mozart/mo_lightning.F90
> +
The descriptions of these 3 fields should say 'lightning' not 'lighting'.

2023-02-07 13:31 UTC, fvitt commented on src/chemistry/mozart/mo_lightning.F90
> +       call addfld( 'FLASHENGY',    horiz_only,  'I', 'J',       'lightning flash energy' ) ! flash energy
@lkemmons What should the units be on the flash energy?

2023-02-07 16:37 UTC, lkemmons commented on src/chemistry/mozart/mo_lightning.F90
> +       call addfld( 'FLASHENGY',    horiz_only,  'I', 'J',       'lightning flash energy' ) ! flash energy
The flash energy is in joules (J).
Could we change LNO_PROD units to 'molecules/cm3/s' - I think that is consistent with other chemical rates?

2023-02-17 13:36 UTC, wwieder commented
This PR caught the attention of the LMWG. Thanks for working on this, @fvitt!  

We're wondering what the timeline for this PR may be, as there's quite a bit of work this could spark on the land side if we can get interactive lightning (and therefore fire ignitions) into CESM3?

2023-02-27 23:50 UTC, cacraigucar requested changes
Preliminary review - may have additional comments, but wanted to get a couple of questions answered

2023-02-27 23:50 UTC, cacraigucar commented on Externals.cfg
> +repo_url = https://github.com/fvitt/CMEPS.git
When will this come into CMEPS?

2023-02-27 23:50 UTC, cacraigucar commented on src/chemistry/mozart/mo_lightning.F90
> +    factor = 0.1_r8*lght_no_prd_factor
Why are you scaling this factor instead of using directly the namelist setting?

2023-02-28 16:41 UTC, fvitt commented on src/chemistry/mozart/mo_lightning.F90
> +    factor = 0.1_r8*lght_no_prd_factor
@lkemmons Do you know the rationale for scaling down `lght_no_prd_factor` here. This is pre-existing code and I don't know the reason for it.  I would like the changes in this PR to be bit-for-bit type changes.   If scaling `lght_no_prd_factor` namelist settings by a factor of 0.1 does not cause any baseline test to fail then I am okay with it.  Otherwise, I would advocate leaving it as it is for this PR.

2023-02-28 16:47 UTC, lkemmons commented on src/chemistry/mozart/mo_lightning.F90
> +    factor = 0.1_r8*lght_no_prd_factor
@fvitt I do not recall either why we included 0.1 in the code for additional scaling to the lght_no_prd_factor in the namelist.  Maybe 0.1 was the optimal value at some point for some configuration.  
If we remove the 0.1 factor here we will need to change all the default CAM-chem and WACCM namelists.  I agree it would be simpler to have a single factor and remove the 0.1, but I also agree with Francis it would be better to NOT change it at this point.

2023-03-22 21:39 UTC, cacraigucar requested changes

2023-03-22 21:39 UTC, cacraigucar commented on src/chemistry/mozart/mo_lightning.F90
> +    if (calc_nox_prod) then
Won't `calc_nox_prod` always be true if you reach this point?  I'm not seeing that the test `    if (calc_nox_prod) then` is needed here.  I also have the same question for line 274 below.

2023-03-23 22:20 UTC, fvitt commented on src/chemistry/mozart/mo_lightning.F90
> +    if (calc_nox_prod) then
Changed how `calc_nox_prod` is set.

2023-03-29 22:19 UTC, brian-eaton reviewed
Looks good.  A couple of minor comments.

2023-03-30 17:10 UTC, fvitt commented on src/chemistry/mozart/mo_lightning.F90
> +  real(r8),protected, allocatable :: prod_no(:,:,:)
`prod_no` is public (always has been).  See line 24.  It is used in `src/chemistry/mozart/mo_setext.F90`.  Isn't it a good idea to protect it since it is public?

2023-03-30 17:11 UTC, nusbaume requested changes
Looks good, just have one small change request and a question.

2023-03-30 17:29 UTC, fvitt commented on bld/build-namelist
> +  }
done

2023-03-30 18:14 UTC, brian-eaton commented on src/chemistry/mozart/mo_lightning.F90
> +  real(r8),protected, allocatable :: prod_no(:,:,:)
@fvitt, sorry I missed that (but so did Steve:).  Stylewise I think it's preferable to have all the attributes for a module variable in one statement.  But a change here isn't necessary.

2023-03-30 18:15 UTC, brian-eaton approved these changes

2023-04-04 15:50 UTC, jtruesdal approved these changes
Looks Ok to me.

2023-04-24 16:29 UTC, fvitt commented on src/chemistry/mozart/mo_lightning.F90
> +          call endrun
fixed

2023-04-24 16:29 UTC, fvitt commented on src/control/camsrfexch.F90
> +       cam_out(c)%lightning_flash_freq(:) = -huge(1._r8)
changed to 0.

2023-04-24 20:34 UTC, cacraigucar approved these changes

2023-04-25 02:38 UTC, nusbaume approved these changes

2023-04-27 16:57 UTC, merged