Switch to turn off soil erosion in CAM for dust emissions
ESCOMP/CAM pull request #748
Opened 2023-02-03 19:29 UTC by fvitt

closes #651 
closes #141

2023-02-03 20:50 UTC, fvitt commented
@ekluzek @dmleung This is the PR for soil erosion switch in CAM.  Please review.  Thanks.

2023-02-17 21:05 UTC, ekluzek requested changes
The default for soil_erod_active should be TRUE, until we bring the changes into the CTSM side, when it'll be FALSE. Looks like this is only documented wrong in the namelist definition file.

2023-02-17 21:05 UTC, ekluzek commented on bld/namelist_files/namelist_definition.xml
> +Default: FALSE
Default should be TRUE, until after this is in CTSM and always on in there.

2023-03-21 21:55 UTC, dmleung commented
ESCOMP/CTSM#1967 now has the corresponding changes in CTSM.

2023-04-03 19:57 UTC, ekluzek commented
This also relates to #778.

This will also update both CMEPS and CTSM, so will happen after those tags are made.

The CMEPS issue is: https://github.com/ESCOMP/CMEPS/issues/353

2023-07-31 21:12 UTC, ekluzek commented
Added a design doc about this here:

https://docs.google.com/document/d/18nZ3LJF5W-YF9iBhqed6s_NWeKOvSSL2-k0Lye1nnLg

2023-07-31 22:05 UTC, ekluzek commented
When we are closer to having this all together and working, we should validate that the dust emission is similar when in CTSM as in CAM by comparing results between the two. We expect answers to be different by greater than roundoff, but they should be qualitatively similar.

2024-07-11 21:08 UTC, ekluzek commented
@fvitt note that the CMEPS PR has been tagged as cmeps0.14.73. The PR to use that in CTSM is https://github.com/ESCOMP/CTSM/pull/2545. Once the CTSM tag is in place this one could come in.

2024-07-23 22:54 UTC, ekluzek commented
The latest CAM (cam6_4_015) has already updated beyond the needed CMEPS tag (to cmeps1.0.2), so this can start to be changed to use the namelist items in the drv_flds_in for dust_emis_inparm. If this PR is hard to update, it could also be restarted from the latest CAM tag.

2024-07-24 16:32 UTC, fvitt commented
@ekluzek Thanks for the comments and pointing me to this PR.   I will probably start a new branch and PR this is quite old...

2024-08-06 14:58 UTC, closed without merging