modify CLUBB to operate on dry density / mixing ratios
ESCOMP/CAM pull request #750
Opened 2023-02-07 23:29 UTC by adamrher

Fixes https://github.com/ESCOMP/CAM/issues/739

2023-02-08 17:39 UTC, cacraigucar requested changes

2023-02-08 17:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +    call addfld ('DPDLFICE',         (/ 'lev' /),  'A', 'kg/kg/s',  'Detrained ice from deep convection (dry mixing ratio)')
Should the output field names be modified slightly so that users with old files know that the contents have changed (the longname change may not be significant enough for them to see that)?

2023-02-08 17:39 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +        !   so that the energy checker doesn't complain.
An extra space creeped into the end of this line.  Could it please be removed (we try not to have trailing spaces)

2023-02-08 21:24 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +    call addfld ('DPDLFICE',         (/ 'lev' /),  'A', 'kg/kg/s',  'Detrained ice from deep convection (dry mixing ratio)')
good point. I re-wrote the outfld call so it outputs moist mixing ratios --- so same as before.

2023-02-08 21:24 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        !   so that the energy checker doesn't complain.
done

2023-02-08 21:26 UTC, cacraigucar approved these changes

2023-02-08 21:59 UTC, fvitt requested changes

2023-02-08 21:59 UTC, fvitt commented on src/physics/cam/clubb_intr.F90
> +        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))
could use rga here (and other places throughout `clubb_intr`)
```suggestion
        rho_ds_zt(i,k+1)       = rga*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))
```

2023-02-08 22:56 UTC, jtruesdal commented on src/physics/cam/clubb_intr.F90
> +        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))
Since pdeldry=pdel * (1-q) there is no change to the value of rho_ds_zt here so just making the code more readable?

2023-02-08 23:00 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))
@PeterHjortLauritzen can correct if I'm wrong, but I believe pdel is held fixed over the entire physics time-step, whereas the state%q array can change throughout the physics.

2023-02-08 23:05 UTC, nusbaume approved these changes
Looks good!  Mostly just supporting Francis's comment and requesting a potential change to one Fortran comment.

2023-02-08 23:47 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))
done

2023-02-08 23:47 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
>      ! constituents are all treated as wet mmr by clubb
done

2023-02-08 23:48 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        wl_a(i) = wl_a(i) + (rcm(i,k))*state1%pdeldry(i,k)/gravit
done

2023-02-08 23:48 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        wl_b(i) = wl_b(i) + state1%q(i,k,ixcldliq)*state1%pdeldry(i,k)/gravit
done

2023-02-08 23:49 UTC, adamrher commented on src/physics/cam/clubb_intr.F90
> +        det_ice(i)                = det_ice(i) - ptend_loc%q(i,k,ixcldice)*state1%pdeldry(i,k)/gravit
done

2023-02-08 23:54 UTC, fvitt approved these changes

2023-02-09 00:06 UTC, PeterHjortLauritzen commented on src/physics/cam/clubb_intr.F90
> +        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdeldry(i,pver-k+1)/dz_g(i,pver-k+1))
Correct (and very confusing!). When we convert from wet to dry (or vice versa) we usedpdel and pdeldry ratios and these stay fixed throughout physics (since CAM physics assumes that total water is constant). That said, water species do change throughout physics and if we were to use "(1._r8-state1%q(i,pver-k+1,ixq))" for the conversion then we would violate the constant pressure assumption ...

ps. in our upcoming PR we will include all water in pressure which means that phase changes will not results in a spurious source/sink of total water (which in CAM, currently, is just water vapor).

2023-02-09 00:21 UTC, jtruesdal approved these changes

2023-02-09 23:15 UTC, merged