Science and infrastructure changes to improve energy/mass budget reporting and closure.
ESCOMP/CAM pull request #761
Opened 2023-03-10 18:10 UTC by jtruesdal

Add inline energy/mass budgets support. (#519) Science changes are included that help close the mass and energy budgets of physics and the SE/MPAS dycores (#521) as well as adding all water constituents to atmospheric mass (pressure) (#520)  

We've been testing with an interim CTSM repo that has MPAS land boundary condition files.  I will be submitting a parallel PR to  get the updated MPAS files into the land repo.

As of this PR energy/mass budgets have been added for physics and the SE and MPAS dycores.  The work of budget improvement, expansion to other supported dycores, and refactor of the logging infrastructure will continue in future PRs.  
Most functional regression testing are passing and baselines are expected to fail due to the climate changing science updates.

Similar to amwg_diagnostic functionality, energy/mass budget diagnostic fields will be added to a history file via the thermo_budget_histfile_num namelist parameter. Globally averaged energy budget summaries are also calculated and written to the atm log file every time the budget history tape is written to. The period over which energy and mass budgets are averaged is the same as the averaging period of the  history budget file. Thus history budgets can be output/averaged  at time step, hour, or month resolutions using the nhtfrq variable  specific to the budget history file identified by   (.false.) The default is .false. (no budgeting) because of the  global gathers needed to create the budgets.

2023-04-16 02:27 UTC, nusbaume requested changes
This is definitely an impressive new model development!  I did have a lot of questions and requests for changes (140 to be exact), but the vast majority of them should be trivial.  Of course please let me know if you have any questions or concerns with any of my suggestions.  

Also, once this review round is done I believe this PR will be ready to be brought out of draft mode and given a full review status, at least assuming the science results are OK.

2023-04-16 02:27 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +      !     or potential enerhy (z coordinate)
Typo here (`enerhy` -> `energy`).

2023-04-16 02:27 UTC, nusbaume commented on src/utils/cam_thermo.F90
>           end if
It looks like you are checking the same variable twice here?

2023-04-17 20:45 UTC, jtruesdal commented on src/control/budgets.F90
> +  integer,           public            :: budget_num     = 0 !
I will review the variables in the budget module for proper access.  I think budget_num may be able to be private along with some others.

2023-04-17 20:45 UTC, jtruesdal commented on src/control/budgets.F90
> +  logical,           public            :: thermo_budget_history = .false.
Will review for protected/private access.

2023-04-17 21:17 UTC, jtruesdal commented on src/control/budgets.F90
> +  character(len=128),public, protected :: budget_longname(budget_array_max) ! long name of budgets
We do have standard length strings for names and descriptions, I will look to see what is appropriate and make sure they are consistent across the module.

2023-04-17 21:19 UTC, jtruesdal commented on src/control/budgets.F90
> +               TRIM(ADJUSTL(longname))
I will make this consistent with the previous longname/var_description fixes noted above.

2023-04-17 22:10 UTC, jtruesdal commented on src/control/budgets.F90
> +            TRIM(ADJUSTL(thermo_budget_vars(me_idx)))//"_"//TRIM(ADJUSTL(str1(idx+1:)))
Its just historical at this point and was a convenience for Peter as he knew the budgets as the sum/dif of 2 shorter snapshot names and not the single budget longname which was added later. I'll talk to Peter about getting rid of the short form budget name as they really don't carry enough info for the more general user.  We may opt to keep it until the API for these budgets is better defined.

2023-04-17 22:15 UTC, jtruesdal commented on src/control/budgets.F90
> +          global=global/dstepsize
This is a debug line and will be removed.

2023-04-17 23:36 UTC, jtruesdal commented on src/control/budgets.F90
> +  function is_budget(name)
OK after greping I see PURE showing up in a number of routines although I'm not sure of the benefit being provided in the context of CESM or CAM. Maybe those particular routines were written to take advantage of the benefits of PURE. I always think of the use of PURE in terms of functional programming where functions are written generically in a specific style to allow them to be combined to form new ones. In that case there is a well thought out overarching design that was developed to create an ecosystem of hierarchical functions that combine to efficiently solve the problem at hand.  Thats not to say modern fortran can not make use of that paradigm only that we haven't tried to take advantage of that very often in CAM.  I certainly wasn't thinking of that when I put these little convenience functions together.  Can you tell me why you would like this labeled PURE?  In my very very limited experience unless a module or modules are really designed to make good use of functional programming or if its required to allow the compiler to maintain a deterministic outcome, it just seems to get in the way, especially when you want to debug PURE function(s).

2023-04-18 00:09 UTC, jtruesdal commented on src/cpl/nuopc/atm_comp_nuopc.F90
> +                  abs(abs(lonMesh(n) - lon(n))- 360._r8) < grid_tol) then
Yeah this isn't pretty and I'm open to better fixes.  This edge case turned up when testing an mpas where lonmesh was -180 to 180 and lon was 0 to 360.

QPC6.mpasa480_mpasa480.intel.2x1.izumi.cam6_3_087_ESCOMP.02/run/cesm.log.592929.izumi.cgd.ucar.edu.230220-104035:[1] ERROR: CAM n, lonmesh(n), lon(n), diff_lon =      1   -174.9529452257118       185.0470496248849             0.36000D+03

2023-04-18 00:25 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata hgrid="mpasa120" nlev="32" analytic_ic="1" aquaplanet="1" >atm/cam/inic/mpas/mpasa120_L32_notopo_coords_c201216.nc</ncdata>
Agreed. Removed the line.

2023-04-18 00:25 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> + N ==&gt; average over nsteps not nacs
Modified as recommended.

2023-04-18 00:26 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> +Produce output for the AMWG diagnostic package.
Replaced "AMWG" diagnostic package with "energy budget".

2023-04-18 00:27 UTC, jtruesdal commented on doc/ChangeLog
> +	Add inline energy/mass budgets support. (#519) Science changes are
We are still working on the final API but yet these instructions will go into the CAM user guide with some type of hyperlink to the scientific description document covering the energy budget consistency checks implemented in the code.  I'll put in an issue to identify all additional changes to be added to the budgeting code.

2023-04-18 00:28 UTC, jtruesdal commented on src/control/budgets.F90
> +       budget_readnl,         &! budget_readnl: read cam thermo namelist
budget_put_global was removed as it was unused.  Globals are updated in the cam_history subroutines when activated by the namelist and only an accessor is needed for printing the budgets.  The remaining comments were replaced with your recommendations.

2023-04-18 00:28 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine budget_readnl(nlfile)
Done.

2023-04-18 00:28 UTC, jtruesdal commented on src/control/budgets.F90
> +          end if
Done.

2023-04-18 00:29 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine budget_init()
Done.

2023-04-18 00:30 UTC, jtruesdal commented on src/control/budgets.F90
> +          end if
Yep you are corrected.  Swapped the lines.

2023-04-18 00:31 UTC, jtruesdal commented on src/control/budgets.F90
> +         optype    !  dif (difference) or sum or stg (stage)
Right. Modified as recommended.

2023-04-18 00:31 UTC, jtruesdal commented on src/control/budgets.F90
> +          end if
Much better. Committed as recommended.

2023-04-18 00:31 UTC, jtruesdal commented on src/control/budgets.F90
> +    if (b_ind < 0) call endrun(sub//'FATAL field name '//name//' not found'//' looked for '//trim(adjustl(str1)))
Done.  This comment is now consistent with all the other.

2023-04-18 00:31 UTC, jtruesdal commented on src/control/budgets.F90
> +    real(r8),          intent(out) :: global  ! global budget index (in q array)
Correct the erroneous comment.

2023-04-18 00:31 UTC, jtruesdal commented on src/control/budgets.F90
> +          write(iulog,*)'returning ',trim(adjustl(str1)),' global ',global
Removed debug output.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +       write(errmsg,*) sub//': FATAL: name not found: ', trim(name)
Might as well be consistent.  Modified as recommended.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +                call endrun(errmsg)
Corrected.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +             write(errmsg,*) sub//': FATAL: bad value optype should be sum of dif:', optype
Corrected.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +  function budget_ind_byname (name)
Since this is only a convenience function used by one procedure its probably better to be a internal function of budget_get_global.  I'll go that path if I can't get rid of it altogether.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +    ! to call endrun when name is not found.
Corrected.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +    character(len=*), parameter    :: sub='budget_ind_byname'
Yep ... Removed.

2023-04-18 00:32 UTC, jtruesdal commented on src/control/budgets.F90
> +    character(len=*), parameter :: sub='is_budget'
Removed.

2023-04-18 00:33 UTC, jtruesdal commented on src/control/budgets.F90
> +       if (trim(name) == trim(budget_name(m)).or.trim(name) == trim(budget_stagename(m))) then
Added.

2023-04-18 16:38 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> + N ==&gt; average over nsteps not nacs
There needs to be some documentation regarding how `N` is different than `A`.  What problem was solved by introducing this new averaging technique?

2023-04-18 22:11 UTC, jtruesdal commented on src/control/cam_history.F90
> +              allgrids_wt(wtidx)%decomp_type=fdecomp
allgrids_wt(:)%decomp_type are initialized to -1 and valid decomp types are > 0. As decomp types are found they will replace the leading most -1 filling the allgrids_wt array from first to last.  You're right though, if allgrids is not large enough and the array is filled with valid format types when another one is found then it will replace the lowest value format type.  I will add an error check and mask for -1 for minloc to catch overwrites.

2023-04-19 15:09 UTC, fvitt commented
This PR seems to be in draft mode.  Should the status be changed to "Ready for review"?

2023-04-19 15:16 UTC, cacraigucar commented
> This PR seems to be in draft mode. Should the status be changed to "Ready for review"?

I asked John this question last night and he confirmed it should be changed.  I guess we each thought the other did it :-)

2023-04-19 15:24 UTC, cacraigucar requested changes
First batch of comments

2023-04-19 16:37 UTC, jtruesdal commented on src/control/budgets.F90
> +    character (len=256)         :: str1, str2, str3, strstg1, strstg2
Again used share_kind_cl as it seems consistent with other str lengths used in the model.

2023-04-19 16:38 UTC, jtruesdal commented on src/control/budgets.F90
> +    ! to call endrun when name is not found.
I removed the abort argument and forgot to update comment.  Corrected.

2023-04-19 16:38 UTC, jtruesdal commented on src/control/budgets.F90
> +  use cam_history_support, only: max_fieldname_len,ptapes
Done.

2023-04-19 16:41 UTC, jtruesdal commented on src/control/budgets.F90
> +    integer                        :: f(ptapes),ff               ! hentry index
Done.  Used h_ind (hentry field index) and m_ind (masterlist field index).

2023-04-19 16:49 UTC, jtruesdal commented on Externals.cfg
> +repo_url = https://github.com/jtruesdal/ctsm
Removed.

2023-04-19 17:38 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> + N ==&gt; average over nsteps not nacs
The 'A' fields are averaged over the number of accumulations which by convention are typically outfld'd once a model time step.  The budget fields which capture dribbled (subdivided) tendencies are outfld'd multiple times per model time step within one or more sub-stepping loops. To properly average these variables they need to be normalized over the number of model time steps (nsteps hence 'N') not the number of accumulations.  I couldn't come up with an easier understandable way to implement this but I am open to suggestions.  

As for the comment maybe ... average over model nsteps for fields outlfd'd more than once per model step.

2023-04-19 17:55 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> + N ==&gt; average over nsteps not nacs
For those fields that are outfld'd once a time step N averaging is equivalent to A averaging.

2023-04-19 18:00 UTC, cacraigucar requested changes
Next round of comments

2023-04-19 18:00 UTC, cacraigucar commented on src/control/budgets.F90
> +  character(cl),     public, protected :: budget_stagename(budget_array_max) ! long name of budgets
Could the comments on these two variables be modified so that they indicate what the difference is between these two variables?

2023-04-19 18:00 UTC, cacraigucar commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
I would propose making this be an input all the time (and remove `optional `).  My reasoning is that folks copy/paste existing code all of the time, and this variable controls logic that is important to be set correctly.  

The same comment applies to e_m_budget

2023-04-19 18:08 UTC, jtruesdal commented on src/control/budgets.F90
> +          end if
Actually I removed the optional for longname and now require it.  That information is provided to the addfld call for the budget variables.

2023-04-19 18:15 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +    character(len=max_chars) :: field_op = ''             ! 'sum' or 'dif'
Created a field_op_len=3 parameter in cam_history_support to be consistent with other length parameters defined for the history handler.  This line now looks like

character(len=field_op_len) :: field_op = ''

2023-04-19 18:16 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +  logical function field_info_is_composed(this)
See above comments on PURE.  Will leave this alone for now as PURE is not required.

2023-04-19 18:19 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +    real(r8)                  :: hbuf_integral  ! area weighted integral of active field
Agreed.  This is something I tried to do with the get and put accessors but forgot to mark the variable private so it is only modified by get and put.  FYI protected is only for module scope variables and can't be part of a type but the same type of scoping is provided by the private/get/put implemented here.

2023-04-19 18:21 UTC, jtruesdal commented on src/control/cam_history.F90
> +#define HDEBUG1 FALSE
Removed.

2023-04-19 18:22 UTC, jtruesdal commented on src/control/cam_history.F90
> +    character(len=max_chars) :: field_op  = ''   ! field derived from sum/dif of field1 and field2
Defined a field_op_len of 3 parameter in cam_history_support which is being used in place of max_chars.

2023-04-19 18:23 UTC, jtruesdal commented on src/control/cam_history.F90
> +              wtidx=MAXLOC(allgrids_wt(:)%decomp_type, MASK = allgrids_wt(:)%decomp_type .EQ. fdecomp)
People are strange ... what can I say.  Replaced.

2023-04-19 18:38 UTC, jtruesdal commented on src/control/cam_history.F90
> +                        tape(t)%hlist(f)%field%op_field2_id = ff
Done.

2023-04-19 18:43 UTC, cacraigucar requested changes
Not able to see this unsubmitted comment, so sending it along anyway

2023-04-19 18:45 UTC, jtruesdal commented on src/control/cam_history.F90
> +    allocate(tmpintegral(maxnflds,mtapes))
Moved tmpintegral and the others below the inquire.

2023-04-19 18:48 UTC, jtruesdal commented on src/control/cam_history.F90
> -          if(masterproc) write(iulog, *) 'Reading history variable ',fname_tmp
Shyly removes line from pocket and places back in code ... Yes unintentional.

2023-04-19 18:49 UTC, jtruesdal commented on src/control/cam_history.F90
> -      write(iulog,'(a,i0)')'  hwrt_prec = ',tape(t)%hlist(n)%hwrt_prec
They did cause an issue when I defined DEBUG but I can't remember what exactly the issue was.  May have been a problem with an early incantation of my mods.  I'll retest and replace them if there is not a problem.

2023-04-19 18:57 UTC, jtruesdal commented on src/control/cam_history.F90
> +    allgrids_wt => grid_wts
I think it is initialized properly. The only components of grid_wts are an integer (which is initialized to -1 in the declaration) and an allocatable array which is allocated and filled with the area weights for that grid when a new decomp type is encountered.

2023-04-19 18:58 UTC, jtruesdal commented on src/control/cam_history.F90
> +              wtidx=MAXLOC(allgrids_wt(:)%decomp_type, MASK = allgrids_wt(:)%decomp_type .EQ. fdecomp)
Yes.  Replaced.

2023-04-19 19:04 UTC, jtruesdal commented on src/control/cam_history.F90
> +              allgrids_wt(wtidx)%decomp_type=fdecomp
I placed the same check for overwriting as above.  It shouldn't ever get here but if it does because of a problem introduced in another part of the history handler it will endrun instead of overwriting.

2023-04-19 19:06 UTC, jtruesdal commented on src/control/cam_history.F90
> +            write(errmsg,*) sub//'FATAL: nstep normalization is bad, currstep,beg_nstep, nsteps=',currstep, tape(t)%hlist(f)%beg_nstep
Replaced.

2023-04-19 19:09 UTC, jtruesdal commented on src/control/cam_history.F90
> +    integer                 :: begdim1,enddim1,begdim2,enddim2,begdim3,enddim3        !
Commented and removed unused comm_id.

2023-04-19 19:16 UTC, jtruesdal commented on src/control/cam_history.F90
> +    dimind = tape(t)%hlist(f)%field%get_dims(begdim3)
Yep.  Removed

2023-04-19 19:17 UTC, jtruesdal commented on src/control/cam_history.F90
> +         call endrun('dyn_readnl: ERROR: budget_optype unknown:'//trim(op))
Corrected.

2023-04-19 19:17 UTC, jtruesdal commented on src/control/cam_history.F90
> +    return
Old Dog New Trick.  Removed.

2023-04-19 19:27 UTC, jtruesdal commented on src/control/cam_history.F90
> +             if(.not. restart) then
Moved outside.

2023-04-19 19:54 UTC, jtruesdal commented on src/dynamics/eul/dycore_budget.F90
> +subroutine print_budget(hstwr)
Unsure.  I will strip it down anyway.

2023-04-19 19:54 UTC, jtruesdal commented on src/dynamics/fv/dycore_budget.F90
> +subroutine print_budget(hstwr)
Unsure. Will strip down anyway.

2023-04-19 19:57 UTC, jtruesdal commented on src/dynamics/se/dycore_budget.F90
> +  use shr_kind_mod,           only: r8=>shr_kind_r8
removed.

2023-04-19 19:58 UTC, jtruesdal commented on src/dynamics/se/dycore_budget.F90
> +  use cam_thermo,             only: thermo_budget_vars_descriptor, thermo_budget_num_vars, thermo_budget_vars_massv
Removed the bottom 2

2023-04-19 20:28 UTC, jtruesdal commented on src/dynamics/fv/metdata.F90
> +             end do
@PeterHjortLauritzen And this looks like an answer changing bug for FV as qini is being updated within the loops and will not contain the initial q values.

2023-04-19 20:36 UTC, jtruesdal commented on src/dynamics/fv3/dycore_budget.F90
> +  use shr_kind_mod,           only: r8=>shr_kind_r8
Cleaned up.

2023-04-19 20:36 UTC, jtruesdal commented on src/dynamics/fv3/dycore_budget.F90
> +  use cam_thermo,             only: thermo_budget_vars_descriptor, thermo_budget_num_vars, thermo_budget_vars_massv
Removed bottom 2.

2023-04-19 20:38 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +#ifdef phl_cam_development
Done.

2023-04-19 20:38 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +      ! update cp_dycore in modeule air_composition.
Done

2023-04-19 20:43 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   end do
Done.

2023-04-19 20:45 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   Rold=Rold*cv/Rgas
Done

2023-04-19 20:47 UTC, jtruesdal commented on src/dynamics/mpas/dp_coupling.F90
> +   qwv = tracers(index_qv,:,1:nCellsSolve)-dtime*q_tend(index_qv_phys,:,1:nCellsSolve)!xxx not needed
Removed comment as it is used.

2023-04-19 21:06 UTC, jtruesdal commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
Agreed. Also proposed that above for Jesse's comments regarding the optional statement.

2023-04-19 21:33 UTC, jtruesdal commented on src/control/budgets.F90
> +          call addfld (TRIM(ADJUSTL(name_str)),   horiz_only, 'N', TRIM(ADJUSTL(units_str)),TRIM(ADJUSTL(desc_str)),gridname=gridname)
Split

2023-04-19 21:40 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +      call e_m_budget('dEdt_phys_total_in_dyn','dAM','dBF',pkgtype='dyn',optype='dif',longname="dE/dt physics total in dycore (phys) (dAM-dBF)")
Thanks.  I'll check all the files.  These are corrected.

2023-04-19 21:43 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine e_m_snapshot (name, pkgtype, longname, cslam)
Agree.  I will wait just a little while to rename these routines while others are actively commenting.

2023-04-19 21:44 UTC, jtruesdal commented on src/utils/cam_thermo.F90
> +      !     or potential enerhy (z coordinate)
Done

2023-04-19 21:47 UTC, jtruesdal commented on src/utils/cam_grid_support.F90
> +    if (masterproc) write(iulog,*)'adding cam_grid_attribute gridname,name,dimname=',gridname,name,dimname
Debugging.  Removed.

2023-04-19 21:51 UTC, jtruesdal commented on src/physics/simple/physpkg.F90
> +      toticeini = 0.0_r8
Thanks.  Done.

2023-04-19 21:59 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +    ncol  = state%ncol
Removed.

2023-04-19 22:00 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +     end if
Fixed

2023-04-19 22:20 UTC, jtruesdal commented on src/dynamics/se/dycore_budget.F90
> +  character(len=*), parameter :: subname = 'check_energy:print_budgets'
fixed subname. also changed check_energy to dycore_budget in this and all other dycore_budget routines.

2023-04-19 22:22 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +! This algorythm is independent of thread count and task count.
Fixed in both places.

2023-04-19 22:23 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +!JMD    print *,'global_integral: before loop'
Done.

2023-04-19 22:24 UTC, jtruesdal commented on src/dynamics/se/dp_coupling.F90
> +      factor_array(1:ncol,1:nlev) = 1/factor_array(1:ncol,1:nlev)
Done.

2023-04-19 22:25 UTC, jtruesdal commented on src/dynamics/se/dp_coupling.F90
> +      ! update cp_dycore in modeule air_composition.
Done

2023-04-19 22:27 UTC, jtruesdal commented on src/dynamics/mpas/dycore_budget.F90
> +    ! save adiabatic dycore dE/dt and dry-mass adjustment to avoid samping error
Done

2023-04-19 22:37 UTC, jtruesdal commented on src/infrastructure/phys_grid.F90
> +               areawt_d(col_index) = phys_columns(col_index)%weight/(4.0_r8*PI)
Done.

2023-04-20 17:54 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +  ! SE dycore specific energy tendencies
fixed

2023-04-20 17:55 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +  use cam_thermo,     only: teidx, thermo_budget_vars_descriptor, thermo_budget_num_vars, thermo_budget_vars_massv
fixed

2023-04-20 17:57 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dp_coupling.F90
> +       se=internal_energy, po =potential_energy, ke =kinetic_energy,                  &
beautification implemented

2023-04-20 18:40 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> + N ==&gt; average over nsteps not nacs
It seems that `A` averaging should be correct for tendencies outfld'd in subcycled code as long as those tendencies are computed using the correct time interval of the subcycle.  If the tendency for a partial step is computed using the time interval of the full step, then it's actually a partial tendency.

I feel that the `N` averaging is adding too subtle a distinction to the time averaging operators.  It also seems to be overloaded in cam_history to decided whether to set up area weights.  My suggestion would be to compute tendencies using the appropriate substep size, or to create temporary storage so that partial tendencies can be accumulated and then outfld'd outside the subcycle loop.

I recognize that it may be late in the game to try and implement this kind of change for this PR.  In that case I'd recommend creating an issue so we can come back to it.

2023-04-20 19:00 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dp_coupling.F90
> +      end do
Good catch. yes

2023-04-20 19:05 UTC, jtruesdal commented on src/control/cam_history.F90
> +  logical function composed_field(fname, fname1, fname2)
Yes better as a subroutine. I will rework this.

2023-04-20 19:25 UTC, jtruesdal commented on src/control/budgets.F90
> +             budget_longname(budget_num) = trim(str1)
Revised longname to not be optional as other commenters have also requested.

2023-04-20 19:27 UTC, jtruesdal commented on src/control/budgets.F90
> +module budgets
Yes I agree.  I will leave that name change for a little later in the comment period when the flurry has died down.

2023-04-20 19:30 UTC, PeterHjortLauritzen commented on src/dynamics/fv/metdata.F90
> +             end do
Good catch (again). I don't think this code is answer changing just really slow (doing the same computations ncol*plev times). Fixed.

2023-04-20 19:35 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dp_coupling.F90
> +        thetavk = theta_m(k,iCell)/sum_water! (1.0_r8 + q(index_qv,k,iCell))  !convert modified theta to virtual theta
Comment "(1.0_r8 + q(index_qv,k,iCell)) " removed

2023-04-20 19:55 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dp_coupling.F90
> +                               thermo_budget_num_vars,thermo_budget_vars
fixed

2023-04-20 20:06 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +  real(r8) :: dEdt_param_efix_in_dyn(4) ! dEdt of physics total in dynamical core
fixed

2023-04-20 20:06 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +    real(r8),         pointer :: wbuf(:,:,:) => NULL() ! pointer to area weights
They don't, all the budget fields being averaged are 2d so hbuf and wbuf both have a second index of 1.  I will make this a 2d array and restructure the loops using array syntax where I can.

2023-04-20 20:07 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    write(iulog,*)"FYI: all difference (diff) below are absolute normalized differences"
fixed

2023-04-20 20:28 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    end if
moved

2023-04-20 20:29 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +      !      call endrun(subname//"Error in energy fixer budget")
done

2023-04-20 20:35 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    tmp = (E_dyBF(1)-previous_E_bf)/1800.0_r8!-previous_dEdt_phys_total_dynE
debug trash left behind ... apologies

2023-04-20 21:33 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    if (abs(E_dyBF(1))>eps) then
In the very first time-step this diagnostic won't work hence the diagnostic is only computed if not in the first time-step where E_dyBF(1)=0

2023-04-20 21:33 UTC, cacraigucar requested changes
next wave of comments

2023-04-20 21:34 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    write(iulog,*)" on an A-grid (physics grid) the as physics increment (also on A-grid)?"
fixed

2023-04-20 21:34 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    write(iulog,*)" dE/dt adiabatic dynamical core must therefore be estiamted"
fixed

2023-04-20 21:49 UTC, jtruesdal commented on src/control/cam_history.F90
> +        if (tape(t)%hlist(f)%avgflag .eq. 'N') then ! set up areawt weight buffer
Agreed. This averaging is an optional spatial postprocessing step. Maybe a new optional flag_global_avg for addfld? I don't think keying on decomp_type would work as the global average should work for any decomp/grid as long as area_wts are added when the grid is defined.

2023-04-20 21:52 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    dEdt_dycore_phys = -dEdt_efix_dynE(1)-previous_dEdt_dry_mass_adjust
was added earlier so comment no longer relevant

2023-04-20 21:52 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +  character(len=*), parameter :: subname = 'check_energy:print_budgets'
done

2023-04-20 21:54 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +          write(iulog,*) "Error: dMASS/dt parameterizations (pAP-pBP) .ne. dMASS/dt physics total (pAM-pBF)"
definitely Nit-picking here ...

2023-04-20 21:54 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +    previous_dEdt_phys_total_dynE = dEdt_phys_total_dynE(1)!xxx
leftover debugging code

2023-04-21 00:47 UTC, jtruesdal commented on Externals.cfg
> +repo_url = https://github.com/jtruesdal/ctsm
Externals.cfg should be OK now even though this still shows the outdated code mods.

2023-04-21 15:36 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    common /gblintcom/I_shared
removed everywhere in global_norms_mod.F90

2023-04-21 16:11 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    avg_area = avg_area*rearth*rearth/1000000._r8
clarified in code

2023-04-21 16:13 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +              call util_function(cdp_fvm,nc,nlev,name_out(wvidx),ie)
done

2023-04-21 16:14 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore_budget.F90
> +    end if
yes

2023-04-21 16:15 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore_budget.F90
> +        !      call endrun(subname//"Error in energy fixer budget")
removed

2023-04-21 16:16 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore_budget.F90
> +      if (abs(E_dyBF(1))>eps) then
To avoid computation at time-step 1 where this diagnostic is not defined (samping issue)

2023-04-21 16:19 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore_budget.F90
> +    if (ntrac>0) then
done

2023-04-21 16:22 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore_budget.F90
> +              call budget_get_global('dAR-dAD',m_cnst,dMdt_vert_remap)
fixed. thanks

2023-04-21 16:22 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_grid.F90
> +   real(r8),        pointer     :: pearea_wt(:) => null()  ! pe-local areas
@jtruesdal can you chime in?

2023-04-21 16:26 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine e_m_snapshot (name, pkgtype, longname, cslam)
I've also been asked to rename budget to cam_budget which sounds like a good idea so how about naming the two routines in question cam_budget_snapshot and cam_budget_register?

2023-04-21 17:18 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine e_m_budget (name, stg1name, stg2name, pkgtype, optype, longname, cslam)
See above suggestion for cam_budget_register

2023-04-21 17:28 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore_budget.F90
> +          write(iulog,*) ""
sure. done

2023-04-21 17:44 UTC, cacraigucar commented on src/control/budgets.F90
> +  subroutine e_m_snapshot (name, pkgtype, longname, cslam)
I would propose that the module be named cam_budget (both for the module name and the filename) and that all externally used routines be prefixed with cam_budget_xxx.

2023-04-21 19:33 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    real (kind=r8), intent(in) :: h(npts,npts,nets:nete)
sure. Changed to fld (for field)

2023-04-21 19:39 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_grid.F90
> +            pearea_wt(ii) = pearea(ii)/(4.0_r8*PI)
OK. Done

2023-04-21 19:40 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_grid.F90
> +               fvm_areawt(mapind) = fvm_area(mapind)/(4.0_r8*PI)
OK. Done

2023-04-21 19:40 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_grid.F90
> +               physgrid_areawt(mapind) = physgrid_area(mapind)/(4.0_r8*PI)
OK. Done

2023-04-21 20:07 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_comp.F90
> +         call e_m_snapshot(TRIM(ADJUSTL(stage(istage))), 'dyn', longname=TRIM(ADJUSTL(stage_txt(istage))), cslam=ntrac>0)
done

2023-04-21 20:29 UTC, PeterHjortLauritzen commented on src/physics/cam/check_energy.F90
> +        cp_or_cv(:ncol,:) = cp_or_cv_dycore(:ncol,:,lchnk)
sure. done

2023-04-21 20:32 UTC, PeterHjortLauritzen commented on src/physics/cam/check_energy.F90
> +      scaling(:ncol,:) = cpairv(:ncol,:,lchnk)/cp_or_cv(:ncol,:)
sure. done.

2023-04-21 20:33 UTC, PeterHjortLauritzen commented on src/physics/cam/check_energy.F90
> +         z_mid = state%z_ini(1:ncol,:), se = se(1:ncol),                             &
yes (just not used if vertical coordinate is not height)

2023-04-21 20:38 UTC, jtruesdal commented on src/control/budgets.F90
> +             write(errmsg,*) sub, ': FATAL: bad value optype should be sum of dif:', optype
Fixed.

2023-04-21 20:38 UTC, jtruesdal commented on src/control/budgets.F90
> +          if (optype=='stg') then
Changed as recommended.

2023-04-21 20:39 UTC, jtruesdal commented on src/control/budgets.F90
> +          budget_num = budget_num+1
Check implemented.

2023-04-21 20:39 UTC, jtruesdal commented on src/control/budgets.F90
> +    do m = 1, budget_array_max
Yes.  Replaced.

2023-04-21 20:39 UTC, jtruesdal commented on src/control/budgets.F90
> +      do m = 1, budget_array_max
Replaced budget_array_max with budget_num.

2023-04-21 20:46 UTC, PeterHjortLauritzen commented on src/physics/cam/check_energy.F90
> +            tt_tmp   = state%q(i,k,ixtt)*state%pdeldry(i,k)/gravit
done

2023-04-21 20:46 UTC, PeterHjortLauritzen commented on src/physics/cam/check_energy.F90
> +            tt_tmp   = state%q(i,k,ixtt)*state%pdel(i,k)/gravit
change made in numerious places (utils_cam_thermo.F90, dynamics/se/dycore/*F90)

2023-04-21 20:49 UTC, PeterHjortLauritzen commented on src/physics/cam/phys_control.F90
> -                                                       ! liquid budgets.
no. CAM4 removed. removed lines restored.

2023-04-21 20:52 UTC, PeterHjortLauritzen commented on src/physics/cam/geopotential.F90
> +          end do
Outcommend and left message:
 
 !  the outcommented code is left for when/if we will support
 ! FV3 and/or FV with condensate loading

2023-04-21 20:53 UTC, PeterHjortLauritzen commented on src/physics/cam/geopotential.F90
> +        end if
ok. done.

2023-04-21 21:46 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +      call e_m_budget('dEdt_phys_total_in_dyn','dAM','dBF',pkgtype='dyn',optype='dif',longname="dE/dt physics total in dycore (phys) (dAM-dBF)")
OK Sorry about the mixup. Hopefully these are OK now.  I also formatted some other very long lines.

2023-04-21 22:15 UTC, jtruesdal commented on src/control/budgets.F90
> +         optype    !  dif (difference) or sum
snapshot and budgets used to be a single subroutine but their data is still a bit mingled.  optype is really only defined for budgets as they are the difference of two snapshots, so optype is not applicable when defining a snapshot.  Let me look at cleaning this up a bit.

2023-04-21 22:44 UTC, jtruesdal commented on src/control/budgets.F90
> +  character(len=128),public, protected :: budget_stagename(budget_array_max) ! long name of budgets
They are intended.  I'm cleaning this up but that change will most likely be identified in an issue and made at a later time.

2023-04-24 15:19 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dycore_budget.F90
> +real(r8), save :: previous_dEdt_phys_total_dynE = 0.0_r8!xxx
removed

2023-04-24 15:21 UTC, PeterHjortLauritzen commented on src/physics/cam/geopotential.F90
> +          !
fixed

2023-04-24 15:27 UTC, PeterHjortLauritzen commented on src/utils/air_composition.F90
> +   ! cp_or_cv_dycore:  composition dependent specific heat at constant pressure
comment corrected

2023-04-24 15:27 UTC, PeterHjortLauritzen commented on src/utils/air_composition.F90
> +      mbarv(:pcols,  :pver, begchunk:endchunk)       = mwdry
removed

2023-04-24 16:09 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +      !(mmr = dry mixing ratio, if not use to_moist_factor to convert)
fixed

2023-04-24 16:13 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
>           end if
I wanted to double check ... joke aside ... fixed

2023-04-24 20:46 UTC, brian-eaton commented on src/control/cam_history.F90
> +        if (tape(t)%hlist(f)%avgflag .eq. 'N') then ! set up areawt weight buffer
I'm fine with postponing any refactoring of the `N` option to a follow-up issue.

2023-04-24 23:26 UTC, jtruesdal commented on src/control/cam_history.F90
> +        tape(t)%hlist(f)%field%field_op(1:max_chars) = ' '
Thanks for that catch, updated.

2023-04-24 23:27 UTC, jtruesdal commented on src/control/cam_history.F90
> +        if (tape(t)%hlist(f)%avgflag .eq. 'N') then ! set up areawt weight buffer
I will place this item in the issue.

2023-04-24 23:34 UTC, jtruesdal commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
Removed optional and improved comments.

2023-04-24 23:36 UTC, jtruesdal commented on src/control/budgets.F90
> +  character(cl),     public, protected :: budget_stagename(budget_array_max) ! long name of budgets
The comments have been updated.

2023-04-24 23:36 UTC, jtruesdal commented on src/control/cam_history.F90
> +  ! composed field: Determinie if fname is composed from 2 other
Corrected.

2023-04-24 23:38 UTC, jtruesdal commented on src/control/cam_history.F90
> +    character(len=*), intent(in), optional :: op           ! currently 'dif'/'sum' supported dif ex fname = op_f1name - op_f2name
Renamed op to optype as recommended.  After trying to search for all the op instances I whole heartedly agree that 'op' is hard to search for.

2023-04-25 01:54 UTC, jtruesdal commented on src/dynamics/mpas/dyn_comp.F90
> +   real(r8), dimension(:),     pointer :: areaCell ! cell area (m^2)
Removed

2023-04-25 05:48 UTC, jtruesdal commented on src/control/budgets.F90
> +          global=global/dstepsize
removed

2023-04-25 05:54 UTC, jtruesdal commented on src/control/cam_history.F90
> -      write(iulog,'(a,i0)')'  hwrt_prec = ',tape(t)%hlist(n)%hwrt_prec
Replaced

2023-04-25 05:57 UTC, jtruesdal commented on src/dynamics/eul/dycore_budget.F90
> +subroutine print_budget(hstwr)
subroutine stripped down

2023-04-25 05:58 UTC, jtruesdal commented on src/dynamics/fv/dycore_budget.F90
> +subroutine print_budget(hstwr)
Subroutine minimized.

2023-04-25 06:25 UTC, jtruesdal commented on src/dynamics/se/dyn_grid.F90
> +   real(r8),        pointer     :: pearea_wt(:) => null()  ! pe-local areas
Done.

2023-04-25 06:41 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine e_m_snapshot (name, pkgtype, longname, cslam)
This sounds good.  I will implement the name changes near the end of the comment period.

2023-04-25 06:47 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> +       group="thermo_budget_nl" valid_values="1,2,3,4,5,6,7,8,9" >
Done.

2023-04-25 15:13 UTC, nusbaume commented on src/control/budgets.F90
> +  function budget_ind_byname (name)
It can still be a `pure` function even if it is an internal function.  We generally want to label (actually pure) functions as `pure` as it can sometimes help the compiler optimize the code, and makes it clear to a developer that no side-effects exist.

2023-04-25 15:35 UTC, nusbaume commented on src/control/budgets.F90
> +  function is_budget(name)
You are correct that a true functional programming paradigm would involve the combination of various different generic functions, and that we don't really take full advantage of that.  However, just because we don't do that now doesn't mean we won't do it in the future.  Plus it is considered good programming (at least nowadays) to have functions avoid side effects, as otherwise it can be a subroutine.  Finally, labeling functions `pure` can sometimes help the compiler make better optimization decisions, as well as help with different architectures like GPUs.  

That all being said, is using `pure` causing debugging issues for you?  If so can you provide an example?

2023-04-25 17:38 UTC, nusbaume commented on src/control/cam_history.F90
> +             if(.not. restart) then
That makes sense, thanks for the explanation!  Will go ahead and mark this as resolved.

2023-04-25 17:56 UTC, nusbaume commented on src/dynamics/mpas/dp_coupling.F90
> +                               thermo_budget_num_vars,thermo_budget_vars
It looks like `moidx`, `mridx`, and `ttidx` were removed from both `use`  statements instead of just one.  Just wanted to check that was on purpose?

2023-04-25 18:05 UTC, PeterHjortLauritzen commented on src/dynamics/mpas/dp_coupling.F90
> +                               thermo_budget_num_vars,thermo_budget_vars
yes (they are not used in the code)

2023-04-25 18:37 UTC, nusbaume commented on src/dynamics/mpas/dycore_budget.F90
> +    if (abs(E_dyBF(1))>eps) then
Got it, that makes sense.  I'll go ahead and mark this as resolved.

2023-04-25 18:53 UTC, nusbaume commented on src/dynamics/se/dp_coupling.F90
> +      ! update cp_dycore in modeule air_composition.
Looks like this change still needs to be committed?

2023-04-25 19:15 UTC, nusbaume commented on src/dynamics/se/dyn_grid.F90
> +   real(r8),        pointer     :: pearea_wt(:) => null()  ! pe-local areas
It looks like this change still needs to be  committed?

2023-04-25 19:29 UTC, nusbaume commented on src/infrastructure/phys_grid.F90
> +               areawt_d(col_index) = phys_columns(col_index)%weight/(4.0_r8*PI)
It looks like this change still needs to be committed?

2023-04-25 19:42 UTC, nusbaume commented on src/physics/cam/geopotential.F90
> +          end do
It's fine to comment this out, I just want to note here that I don't think this code will ever run because it looks like it is inside an `else` clause for the following if-statement:

`if (.not.(dycore_is('MPAS') .or. dycore_is('SE'))) then`

which would mean the `LR` and `FV3` checks will always be False.

2023-04-25 19:49 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +      !(mmr = dry mixing ratio, if not use to_moist_factor to convert)
Looks like this change still needs to be committed?

2023-04-25 19:51 UTC, nusbaume commented on src/utils/cam_thermo.F90
> +      ! Update the physics "constants" that vary
Looks like this change still needs to be committed?

2023-04-25 19:52 UTC, nusbaume commented on src/utils/cam_thermo.F90
>           end if
Looks like this change still needs to be committed?

2023-04-25 20:02 UTC, PeterHjortLauritzen commented on src/dynamics/se/dp_coupling.F90
> +      ! update cp_dycore in modeule air_composition.
oups

2023-04-25 20:06 UTC, PeterHjortLauritzen commented on src/physics/cam/geopotential.F90
> +          end do
When/if we support 'LR' or 'FV3' then these dycores would be in the else statement, that is, say we support FV3 then

if (.not.(dycore_is('MPAS') .or. dycore_is('SE'))) then

would be replaced with 

if (.not.(dycore_is('MPAS') .or. dycore_is('SE').or. dycore_is('FV3'))) then

and the if-statement is needed because FV3 handles mid-level pressure differently.

2023-04-25 20:07 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +      !(mmr = dry mixing ratio, if not use to_moist_factor to convert)
believe it is fixed now

2023-04-25 20:08 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
> +      ! Update the physics "constants" that vary
apologies. pushed

2023-04-25 20:09 UTC, PeterHjortLauritzen commented on src/utils/cam_thermo.F90
>           end if
apologies. pushed

2023-04-25 20:21 UTC, jtruesdal commented on src/dynamics/se/dyn_grid.F90
> +   real(r8),        pointer     :: pearea_wt(:) => null()  ! pe-local areas
I have some changes on hold because I was running into answer changes that were greater than roundoff which i am looking into.  There may be a couple more down the line.

2023-04-25 22:10 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +   subroutine get_hydrostatic_energy_1hd(tracer, moist_mixing_ratio, pdel_in, &
This subroutine is not called anywhere in the CAM code.  Should it be?

2023-04-25 22:22 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +   subroutine get_hydrostatic_energy_1hd(tracer, moist_mixing_ratio, pdel_in, &
> This subroutine is not called anywhere in the CAM code. Should it be?

Never mind - I see it is in an interface and is being used with that name.

2023-04-25 22:28 UTC, jtruesdal commented on src/utils/cam_thermo.F90
> +   subroutine get_hydrostatic_energy_1hd(tracer, moist_mixing_ratio, pdel_in, &
If @PeterHjortLauritzen agrees I will remove it.

2023-04-25 22:31 UTC, cacraigucar commented on src/utils/cam_thermo.F90
> +   subroutine get_hydrostatic_energy_1hd(tracer, moist_mixing_ratio, pdel_in, &
Please don't remove it!  As I said, I missed that it is in an interface called get_hydrostatic_energy (in case there is a 2d version in the future).  That is called in many places.

2023-04-25 22:45 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> + N ==&gt; average over nsteps not nacs
Updated the comment and will be moving this to follow-up issue.

2023-04-25 22:46 UTC, jtruesdal commented on src/control/budgets.F90
> +  integer,           public            :: budget_num     = 0 !
Done. Updated access as recommended and cleaned up comments.

2023-04-25 22:46 UTC, jtruesdal commented on src/control/budgets.F90
> +  logical,           public            :: thermo_budget_history = .false.
Done.

2023-04-25 22:46 UTC, jtruesdal commented on src/control/budgets.F90
> +            TRIM(ADJUSTL(thermo_budget_vars(me_idx)))//"_"//TRIM(ADJUSTL(str1(idx+1:)))
Would like to keep this for now but will add this item to follow-up issue for discussion and refactor.

2023-04-25 22:46 UTC, jtruesdal commented on src/control/budgets.F90
> +  function budget_ind_byname (name)
Done.

2023-04-25 22:47 UTC, jtruesdal commented on src/control/budgets.F90
> +  function is_budget(name)
Done.  (Being old school I default to print for debugging if I need to see something quickly, which requires removing pure before you can get it to compile.)

2023-04-25 22:47 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +  logical function field_info_is_composed(this)
Done.

2023-04-25 22:47 UTC, jtruesdal commented on src/dynamics/se/dp_coupling.F90
> +      ! update cp_dycore in modeule air_composition.
Done.

2023-04-25 22:49 UTC, jtruesdal commented on src/dynamics/se/dyn_grid.F90
> +   real(r8),        pointer     :: pearea_wt(:) => null()  ! pe-local areas
Nullified the pointers after the declaration.

2023-04-25 22:50 UTC, jtruesdal commented on src/infrastructure/phys_grid.F90
> +               areawt_d(col_index) = phys_columns(col_index)%weight/(4.0_r8*PI)
Done now.

2023-04-25 22:53 UTC, jtruesdal commented on src/control/budgets.F90
> +  character*3, public :: budget_optype(budget_array_max)! stage or difference or sum
Done. Clarified both budget_optype and budget_pkgtype

2023-04-25 22:53 UTC, jtruesdal commented on src/control/budgets.F90
> +         optype    !  dif (difference) or sum
Removed stg, updated comments and initialized all the character types at declaration, including budget_optype.

2023-04-25 22:54 UTC, jtruesdal commented on src/control/budgets.F90
> +    if (ierr /= 0) call endrun(subname//": FATAL: mpi_bcast: thermo_budget_histfile_num")
Done.

2023-04-25 22:55 UTC, jtruesdal commented on src/control/cam_history.F90
> +  logical function composed_field(fname, fname1, fname2)
Created composed_field_info subroutine to return the needed information.

2023-04-25 22:56 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +    field_info_is_composed = (trim(adjustl(this%field_op))=='sum' .or. trim(adjustl(this%field_op))=='dif')
Good catch, both the optype and composed field_ids need to be set.  Added the check for field_id1 and field_id2

2023-04-25 22:57 UTC, jtruesdal commented on src/control/cam_history.F90
> +    character(len=*), intent(in), optional :: op           ! currently 'dif'/'sum' supported dif ex fname = op_f1name - op_f2name
Also updated comments.

2023-04-25 22:58 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +    real(r8),         pointer :: wbuf(:,:,:) => NULL() ! pointer to area weights
wbuf is now 2d.  Will add item to follow-up issue to remove this and refactor to get area and normalization factor directly from grid object.

2023-04-25 23:23 UTC, cacraigucar requested changes
My final for now review (except perhaps responses to changes which have yet to be made on my previous comments).

2023-04-25 23:23 UTC, cacraigucar commented on src/control/cam_history.F90
> +    if (present(optype)) then
There should probably be a check in addfld as well that optype is "sum" or "dif" since addfld calls are added by the user all of the time.

2023-04-26 00:38 UTC, jtruesdal commented on doc/ChangeLog
> +	Add inline energy/mass budgets support. (#519) Science changes are
There is a place holder for this in issue #796

2023-04-26 00:39 UTC, jtruesdal commented on src/control/budgets.F90
> +            TRIM(ADJUSTL(thermo_budget_vars(me_idx)))//"_"//TRIM(ADJUSTL(str1(idx+1:)))
There is a place holder for this in issue #796

2023-04-26 00:45 UTC, jtruesdal commented on src/control/budgets.F90
> +  character(len=128),public, protected :: budget_stagename(budget_array_max) ! long name of budgets
There is a place holder for this in issue #796

2023-04-26 00:46 UTC, jtruesdal commented on src/control/cam_history_support.F90
> +    real(r8),         pointer :: wbuf(:,:,:) => NULL() ! pointer to area weights
There is a place holder for this in issue #796

2023-04-26 00:46 UTC, jtruesdal commented on src/control/cam_history.F90
> +        if (tape(t)%hlist(f)%avgflag .eq. 'N') then ! set up areawt weight buffer
There is a place holder for this in issue #796

2023-04-26 03:43 UTC, nusbaume approved these changes
All of my concerns have been resolved or properly deferred, so I am happy with this PR.  Thanks @jtruesdal and @PeterHjortLauritzen for all your work on the review responses!

2023-04-26 18:02 UTC, jtruesdal commented on src/control/cam_history.F90
> +    if (present(optype)) then
Good catch! Done.

2023-04-26 18:03 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine e_m_budget (name, stg1name, stg2name, pkgtype, optype, longname, cslam)
Done.

2023-04-26 18:04 UTC, jtruesdal commented on src/control/budgets.F90
> +  subroutine e_m_snapshot (name, pkgtype, longname, cslam)
Done.

2023-04-27 17:46 UTC, fvitt commented
I don't have time to do a proper review

2023-04-27 18:04 UTC, cacraigucar commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
@jtruesdal - I am still seeing the optional attribute here (in the new cam_budget_em_snapshot routine)

2023-04-27 18:11 UTC, cacraigucar commented on src/control/budgets.F90
> +  subroutine e_m_snapshot (name, pkgtype, longname, cslam)
I suggest one last routine name needs to be changed: `is_budget` should be `is_cam_budget`

2023-04-27 18:13 UTC, cacraigucar commented on src/control/budgets.F90
> +  subroutine e_m_budget (name, stg1name, stg2name, pkgtype, optype, longname, cslam)
I don't see `register` in this name.  I believe with the revised naming it should be `cam_budget_em_register`

2023-04-27 18:45 UTC, jtruesdal commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
I'm seeing one optional for the logical variable cslam in cam_budget_em_snapshot.  Sometimes I have to adjust the commits shown pull do to make sure all commits are included.

2023-04-27 19:05 UTC, cacraigucar commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
Yes, the cslam logical is one that I don't think should be optional.  My reasoning is that a user who copies a call from a non-SE run won't know about this option and it has implications on what is run.  I believe that a user should be forced to set it regardless.

2023-04-27 21:10 UTC, jtruesdal commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
I misunderstood, I thought you were talking about longname.  Let me take a look at the logic to see if I can get around adding cslam to the calling list.

2023-04-27 22:22 UTC, jtruesdal commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
The FVM grid is only defined when using CSLAM.  Since the grid_support utility provides a function to see if FVM is defined I don't need to pass the optional. I can use this line inside the routine.
       use_cslam=cam_grid_id('FVM')>0
I'll push this if it tests OK and you are good with this alternative.

2023-04-27 22:32 UTC, cacraigucar commented on src/control/budgets.F90
> +    logical,          intent(in), optional :: &
That sounds like the perfect solution!

2023-04-27 23:04 UTC, cacraigucar commented on src/control/budgets.F90
> +  character(len=128),public, protected :: budget_stagename(budget_array_max) ! long name of budgets
I am okay with closing this PR with this unresolved.  I will not resolve this conversation to ease referring back to this when I'm reviewing #796

2023-04-27 23:04 UTC, cacraigucar approved these changes

2023-04-28 22:27 UTC, merged