create initial FLTHIST and FMTHIST compsets for CAM7
ESCOMP/CAM pull request #767
Opened 2023-03-20 15:36 UTC by cacraigucar

Closes #765

2023-03-28 14:41 UTC, fvitt requested changes

2023-03-28 14:41 UTC, fvitt commented on cime_config/config_component.xml
> +    <desc atm="CAM%DEV[%LT][%MT][%L58][%L93][%CCTS1]"                                                                                              >CAM7 development physics:</desc>
Should `%L58` and `%L93` be replaced by `%LT` and `%MT`?

2023-03-28 14:41 UTC, fvitt commented on cime_config/config_component.xml
> +      <value compset="_CAM%DEV%MT">-nlev 93 -chem ghg_mam4</value>
Can we have the chemistry specifier separate from the model top height specifier?
So the existing CAMChem compsets FCLTHIST and FCMTHIST become:

```
   FCLTHIST             : HIST_CAM%DEV%LT%CCTS1_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FCMTHIST             : HIST_CAM%DEV%MT%CCTS1_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
```

Maybe have something like `_CAM%DEV%LT%GHGMAM4` for the CAM7 `ghg_mam4` chemistry. I can imagine there being a `ghg_mam7` chemistry in the future.

2023-03-28 14:41 UTC, fvitt commented on cime_config/config_compsets.xml
> +  </compset>
Do we need to specify the chemistry in these (%GHGMAM4)?

2023-03-28 16:31 UTC, brian-eaton commented on cime_config/config_component.xml
> +      <value compset="_CAM%DEV%MT">-nlev 93 -chem ghg_mam4</value>
Ooops.  The `%LM` above should read `%MT`

2023-03-28 17:31 UTC, brian-eaton commented on cime_config/config_component.xml
> +      <value compset="_CAM%DEV%MT">-nlev 93 -chem ghg_mam4</value>
@fvitt, you are correct.  I realized that when I started testing.  `bld/configure` is the place where the default chemistry has always been set and that's what's needed now.

2023-03-28 18:07 UTC, brian-eaton commented on bld/namelist_files/use_cases/hist_cam_lt.xml
> +<solar_parms_data_file>atm/cam/solar/SolarForcingCMIP6_18491230-23000102_c20200615.nc</solar_parms_data_file>
Fixed.

2023-03-28 18:08 UTC, brian-eaton commented on cime_config/config_component.xml
> +    <desc atm="CAM%DEV[%LT][%MT][%L58][%L93][%CCTS1]"                                                                                              >CAM7 development physics:</desc>
Change has been made in both `config_component.xml` and `config_compsets.xml`.

2023-03-28 18:09 UTC, brian-eaton commented on cime_config/config_compsets.xml
> +  </compset>
I have set the default chemistry in `bld/configure` so that it doesn't need to be specified in the compset definition.  This is consistent with our treatment of chemistry to this point.

2023-03-28 18:52 UTC, fvitt approved these changes
Looks good to me.  Thanks.

2023-03-28 20:46 UTC, nusbaume approved these changes

2023-03-29 14:39 UTC, brian-eaton approved these changes

2023-03-30 18:55 UTC, cacraigucar commented
@fvitt and @brian-eaton - @cecilehannay is noticing that this file has been removed from the use_case.  Is it correct that it should not be in her namelist (@fvitt approved the namelist with this file in and we want to make sure it should not be there).

2023-03-30 18:57 UTC, fvitt commented
> @fvitt and @brian-eaton - @cecilehannay is noticing that this file has been removed from the use_case. Is it correct that it should not be in her namelist (@fvitt approved the namelist with this file in and we want to make sure it should not be there).

Which file?

2023-03-30 19:06 UTC, cacraigucar commented
> > @fvitt and @brian-eaton - @cecilehannay is noticing that this file has been removed from the use_case. Is it correct that it should not be in her namelist (@fvitt approved the namelist with this file in and we want to make sure it should not be there).
> 
> Which file?

<!-- Kp and F10.7 -->
<solar_parms_data_file>atm/cam/solar/SolarForcingCMIP6_18491230-23000102_c20200615.nc</solar_parms_data_file>

Sorry - I copied, but forgot to paste :-)

2023-03-30 19:11 UTC, fvitt commented
Correct. The `solar_parms_data_file` input is not used in the low-top configuration.  It is used in high-top configurations -- waccm and wacm-x.

2023-03-31 18:17 UTC, merged