cam6_3_102: Fix cam_dev TEM diags issue
ESCOMP/CAM pull request #770
Opened 2023-03-30 15:26 UTC by fvitt

fixes #769 

Also :
 - adopts the `zm` naming convention for the zonal mean outputs.  
 - add 'Uzm','Vzm','Wzm','THzm' output fields

2023-03-31 22:29 UTC, fvitt commented
@cacraigucar This is ready for full review now.  Thanks.

2023-03-31 22:54 UTC, cacraigucar approved these changes

2023-03-31 22:54 UTC, cacraigucar commented on src/physics/cam/phys_grid_ctem.F90
> +    integer, parameter :: ctem_zavg_phys_decomp = 333 ! Must be unique within CAM
Just curious what this number is and why it changed.  Perhaps a little bit more description in the comment would be helpful?

2023-03-31 22:59 UTC, fvitt commented on src/physics/cam/phys_grid_ctem.F90
> +    integer, parameter :: ctem_zavg_phys_decomp = 333 ! Must be unique within CAM
The number is used for registration of the zonal mean history grid.  The 201 number apparently was not unique.  There was a problem when I tried to use SE grid interpolate_output feature and TEM zm output in the same run.  Changing the number fixed the issue.

2023-04-03 15:12 UTC, nusbaume requested changes
Looks good, just one request to update some history field descriptions.

2023-04-03 15:12 UTC, nusbaume commented on src/physics/cam/phys_grid_ctem.F90
> +    call addfld ('THzm', (/'lev'/), 'A','K',      'Zonal-Mean potential temp - defined on ilev', gridname='ctem_zavg_phys' )
It looks like these are all defined on `lev`, not `ilev`.  Should we remove the `ilev` statement from the history field description?

2023-04-03 15:26 UTC, fvitt commented on src/physics/cam/phys_grid_ctem.F90
> +    call addfld ('THzm', (/'lev'/), 'A','K',      'Zonal-Mean potential temp - defined on ilev', gridname='ctem_zavg_phys' )
fixed

2023-04-03 15:43 UTC, nusbaume approved these changes
Everything looks good to me now.  Thanks!

2023-04-03 19:50 UTC, brian-eaton approved these changes

2023-04-04 14:41 UTC, merged