CAM tuning F and increase PE count for MT compsets
ESCOMP/CAM pull request #820
Opened 2023-05-25 19:43 UTC by cacraigucar

Introduce tuning "F" 
Increase PE count for MT compsets

closes #812 
closes #818

2023-06-01 21:54 UTC, fvitt reviewed
A few questions/comments.

2023-06-01 21:54 UTC, fvitt commented on bld/config_files/definition.xml
> +Model top specifier
```suggestion
Model top specifier
  lt : ~ 40 km top
  mt : ~ 80 km top
```

2023-06-01 21:54 UTC, fvitt commented on cime_config/config_pes.xml
> +          <ntasks_wav>-50</ntasks_wav>
I believe the glacier and wave models are stubs.   Can these be removed and use the default `ntasks`, `nthrds`, and `rootpe` for these?

2023-06-01 21:54 UTC, fvitt commented on cime_config/config_component.xml
> +      <value compset="_CAM.*%MT">-nlev 93 -model_top mt</value>
I guess you are not setting a default number of layers for `lt` or `mt` model top.  So the`-nlev` setting is still needed.

2023-06-01 21:54 UTC, fvitt commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
I imagine some of the setting for the SE dycore are more dependent on number of model layers rather the physics and altitude of the of the model top.  I am not going to fret over it too much...

2023-06-02 02:51 UTC, brian-eaton commented on bld/config_files/definition.xml
> +Model top specifier
It would be useful to point out that `model_top` is being set by the compset definition.

2023-06-02 02:51 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<gw_apply_tndmax phys="cam_dev" chem="ghg_mam4" model_top="lt">.false.</gw_apply_tndmax>
This seems like overkill on the attribute specification.  Either `phys="cam_dev" chem="ghg_mam4"` or `model_top="lt"` would suffice.  Using `phys="cam_dev" chem="ghg_mam4"` here would be my choice.

2023-06-02 02:51 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
If Francis isn't going to fret, then neither am I.  I agree that it's hard to evaluate whether these attribute settings make sense without knowing what the requirements are.

2023-06-02 02:51 UTC, brian-eaton commented on cime_config/config_component.xml
> +      <value compset="_CAM.*%MT">-nlev 93 -model_top mt</value>
I believe `nlev` will always be needed for the initial file (unless the model infrastructure were refactored to be totally dynamic).  It's the initial file which sets the model top.

2023-06-02 17:41 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
A question I had when first looking at the changes in `namelist_defaults_cam.xml` was whether the new settings that were being enabled by the `phys="cam_dev"` attribute were intended to be applied to the `F2000dev` compset as well.  I now see that that issue was discussed here [https://github.com/NCAR/amwg_dev/discussions/275](url) and that @adamrher was OK with it.  But the value of `gw_apply_tndmax` is `.true.` for `F2000dev` and is `.false.` for the `LT` compsets.  Since both are low top models using `cam_dev` physics I've been trying to understand what the important difference is between these compsets to help inform how to set the attributes that provide the different default values.  I'm guessing now that the difference is more related to the vertical resolution difference than it is to model top.  This may be related to @fvitt's comment above about dependence on number of layers.  Adam, what's your take?

2023-06-02 18:07 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<gw_apply_tndmax phys="cam_dev" chem="ghg_mam4" model_top="lt">.false.</gw_apply_tndmax>
The `chem="ghg_mam4"` attribute is what would keep this setting from being used with `F2000dev`.  So the resolution here depends on @adamrher  confirming that indeed the setting for `F2000dev` should be `.true.` as it is for `F2000climo`, or not...

2023-06-02 21:44 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<gw_apply_tndmax phys="cam_dev" chem="ghg_mam4" model_top="lt">.false.</gw_apply_tndmax>
Apologies Brian, I missed this question to me since I get email prompts even when I'm not mentioned. I would like the gw settings in F2000dev to be identical to whatever the latest FLTHIST compset is. The only difference from FLTHIST is the ```chem="ghg_mam4"``` where I'd like to retain the chem options from F2000climo in F2000dev. Does that answer your question(s) Brian?

2023-06-03 00:42 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<gw_apply_tndmax phys="cam_dev" chem="ghg_mam4" model_top="lt">.false.</gw_apply_tndmax>
Thanks Adam.  I think that should make it easier to just use `phys="cam_dev"` as the attribute for many of the new `LT/MT` compset settings.

2023-06-05 15:21 UTC, nusbaume commented on bld/namelist_files/namelist_defaults_cam.xml
> +<gw_apply_tndmax phys="cam_dev" chem="ghg_mam4" model_top="lt">.false.</gw_apply_tndmax>
I agree with everyone that `phys="cam_dev"` should be the first control on the namelist defaults, with the `model_top` attribute only needed when a namelist variable changes with respect to `LT` or `MT`, or some other model top setting (so in this particular case where they are the same I don't think `model_top` is needed at all).

In terms of my original request, basically the one thing I don't want to see (for now) is a `model_top` attribute that doesn't have `phys="cam_dev"` listed first.  This is because these LT and MT settings are only in the context of CAM7 physics, and by requiring the `phys` attribute it will protect us from mistakenly modifying other model configuration settings (e.g. CAM6).   

Anyways, I hope that helps, and let me know if you are still confused or concerned about this particular ask!

2023-06-07 22:39 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<gw_apply_tndmax phys="cam_dev" chem="ghg_mam4" model_top="lt">.false.</gw_apply_tndmax>
Set it just to "cam_dev"

2023-06-07 22:39 UTC, cacraigucar commented on cime_config/config_pes.xml
> +          <ntasks_wav>-50</ntasks_wav>
No longer setting the ntasks for MT, since further testing indicated that it is not a memory issue

2023-06-08 22:20 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Do we even need this additional entry? cam_dev satisfies the first if block:

```
(not $waccm_phys)
use_gw_front=.true.
use_gw_convect_dp=.true.
```

Also, what if nothing satisfied this if block ... is tau_o_ubc just not set? Shouldn't it be initialized to false somewhere above this code block, as a fall back value?

2023-06-08 22:26 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_um phys="cam_dev"          > .true. </clubb_l_mono_flux_lim_um>
@bstephens82 the mlf limiter on um/vm wouldn't get invoked if clubb_l_predict_upwp_vpwp=F, or does it?

2023-06-08 22:27 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_um phys="cam_dev"          > .true. </clubb_l_mono_flux_lim_um>
Correct. It only operates on the winds if using prognostic momentum fluxes.

2023-06-08 22:32 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
What happens if we have mg3=T, hgrid="1.9x2.5" can cam_dev=T?

I'm inclined to recommend a larger hammer -- can we just condition this on cam_dev, and not mg3? I want it to work for cam_dev + mg2, but I'm not sure whether we should have another entry for cam_dev+mg2, or just have the large hammer to simplify the interpretation.

2023-06-08 22:37 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
>  <micro_mg_vtrmi_factor microphys="mg2"  >  1.D0    </micro_mg_vtrmi_factor>
same issue - what if I turn on mg2 and cam_dev? Does the last entry that satisfies the logic the one that wins out?

Actually I would just delete the mg2 entry, as its set to the default value. That would alleviate my concerns.

2023-06-08 22:40 UTC, adamrher requested changes
Hi I've provided some comments asking for clarification. 

I accidentally added some comments as one-off comments, and not part of the review. oops.

2023-06-08 22:40 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_hypervis_subcycle  phys="cam_dev" hgrid="ne30np4" npg="3" model_top="lt"    > 4 </se_hypervis_subcycle>
I don't see why this needs to be conditioned on npg="3". I'd prefer it not. We may need to wait for @PeterHjortLauritzen to get his take.

2023-06-08 22:42 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_um phys="cam_dev"          > .true. </clubb_l_mono_flux_lim_um>
In that case, I would suggest that the default for these (```clubb_l_mono_flux_lim_um``` and ```clubb_l_mono_flux_lim_um```) always be set to true. request to get rid of the cam_dev qualifier. If anything it should be qualified on ```clubb_l_predict_upwp_vpwp```, but as Ben said, it's not really necessary since its not used when predict_upwp=F.

2023-06-08 23:24 UTC, cacraigucar commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
@adamrher - I wasn't sure that cam_dev will always satisfy the "and" part of the statement.  Since I was told it should be set for all cam_dev runs, that is what I was doing, even if the other settings were to be changed.  It sounds like the finer granularity of the above if statement is sufficient, so I should remove this section?

tau_0_ubc is initialized to false in gw_drag.F90 and keeps that setting unless it is overriden with a namelist setting.  If none of these settings are executed, then the atm_in file will not have the variable appear in it.  

Removing the "large hammer" cam_dev check

2023-06-08 23:24 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_um phys="cam_dev"          > .true. </clubb_l_mono_flux_lim_um>
Always set to true now

2023-06-08 23:24 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
I'm happy with using the large `cam_dev` hammer since it sounds like the values will be the same.  We can fine tune it with additional qualifiers if needed in the future.

In answer to the question, I believe with the namelist_defaults_cam.xml file, the last value which matches is what is ultimately set.

2023-06-08 23:24 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
>  <micro_mg_vtrmi_factor microphys="mg2"  >  1.D0    </micro_mg_vtrmi_factor>
Deleted unnecessary line qualified by mg2

2023-06-08 23:24 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_hypervis_subcycle  phys="cam_dev" hgrid="ne30np4" npg="3" model_top="lt"    > 4 </se_hypervis_subcycle>
That question I can not answer, as it was already being selected with `npg=3`.  Do you want to hold up this PR until @PeterHjortLauritzen returns from PTO or should we just open an issue to investigate it?

2023-06-09 00:16 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
I think that the first logic block is sufficient; if all of those gw namelists are false, meaning only orographic **could** be on, I don't think tau_0_ubc is consequential. Let me ask Julio tmrw, and resolve this convo then.

2023-06-09 00:23 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
After thinking a little more on this; I'm going to advocate for the qualifiers, but that we should (a) also include one for mg2 and cam_dev, and (b) move both just above the mgX and hgrid=2deg entries; I'd like to retain the hgrid=2deg tunings even if we do turn on cam_dev. When people run 2deg I'd like them to have the 2deg tunings. If it needs to be retuned with cam_dev, then we can make that change then.

2023-06-09 00:32 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_hypervis_subcycle  phys="cam_dev" hgrid="ne30np4" npg="3" model_top="lt"    > 4 </se_hypervis_subcycle>
I'm going to make some executive decisions here. Dycore time-stepping should not have either (a) cam_dev qualifiers, or (b) npg qualifiers. These are both physics, and are orthogonal to the dynamics. Time-stepping should only be a function of the hgrid, the number of levels and the model top location. I suspect the waccm physics qualifier is a proxy for changes in vertical levels and/or model top.

2023-06-09 00:38 UTC, adamrher requested changes
My requests here reflect that the dycore time-stepping should not be conditioned on physics. If someone wants to run something other than cam_dev, than they should still get stable time-stepping.

2023-06-09 00:38 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_nsplit phys="cam_dev" hgrid="ne30np4"  model_top="mt" >  3  </se_nsplit>
remove cam_dev qualifier.

2023-06-09 00:38 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
unresolving this conversation because I don't think physics should qualify the dycore time-stepping. If someone wants to try to run -phys cam6 w/ mt, then have at it. Please remove the cam_dev qualifier.

2023-06-09 00:38 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_nu_top phys="cam_dev" model_top="mt"     > 1.0e6 </se_nu_top>
remove cam_dev qualifier; if someone wants to run mt w/ a different physics they should have this value of nu_top.

2023-06-09 17:19 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
I've not much to add since Brian is in agreement with me here. And I won't step into the debate on use cases vs namelist_defaults because I admittedly have very little familiarity with use cases and their pros / cons.

> There's no obvious correlation here between model top and the setting of se_nsplit.

As I've been dragged into understanding high top modeling, I've learned that b/c the mt lid is right above where there's a lot of wave breaking, that this is a particularly bad combination as waves are reflecting off the lid and the sponge layer apparently can't completely rid this dynamic. Or at least thats my cartoon understanding of it. So I think the non-monotonic relationship of model top and cfl limiting time-step is to be expected.

So I will add that the ```waccm_pyhs="1"``` modifier is very opaque since its keying off the vertical grid / model top aspect that one should not associate with physics. I figure we let this be grandfathered in at this point, but that we not introduce anymore of this type of logic going forward.

2023-06-09 17:40 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
I've checked with Julio, and have come up with a better solution. Yes, lets keep that cam_dev hammer out of the logic, and instead expand the first if block to include the three orographic options:

```
    ($do_gw_front or $do_gw_front_igw or
     $do_gw_convect_dp or $do_gw_convect_sh or
     $do_gw_oro or $do_gw_rdg_beta or $do_gw_rdg_gamma)) {
    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
```

Since tau_0_ubc controls the b.c.'s for all the various gw schemes, this ensures that we have tau_0_ubc=T if any of the gw schemes are on (and not running waccm_phys).

2023-06-09 18:04 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
I'll add for the record here that when the namelist defaults have an equal number of attribute matches, it's the first one that gets returned.  But it's not robust to depend on this behavior (mainly because maintenance is difficult).  The attributes should always be chosen to avoid a tie.  When the logic gets complicated, it's best to move it to `build-namelist` where the availability of programming logic makes it easier to ensure the desired defaults.  That might be the case here since it looks like `silhs` may already getting its default using the assumption that an attribute count tie results in the first element being chosen.

2023-06-09 18:40 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_nu_top phys="cam_dev" model_top="mt"     > 1.0e6 </se_nu_top>
@nusbaume - Since you specifically asked me to use `phys="cam_dev"` with all model_top settings, I want to make sure you are okay with Adam's rationale.

2023-06-09 18:40 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
@nusbaume - Another explanation on why I am being advised to remove the `phys="cam_dev"` qualifier from the lines with `-model_top`

2023-06-09 19:03 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
I'd advocate for moving this particular namelist setting to build-namelist, since it's getting so complicated.

2023-06-09 19:23 UTC, nusbaume commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_rsplit phys="cam_dev" model_top="mt"            > 6 </se_rsplit>
I am happy to drop the `phys` qualifer.  I mostly just wanted it to prevent any unexpected namelist behavior, but since it sounds like including it could itself produce (at least scientifically) unexpected behavior then we can go ahead and drop it.

2023-06-09 19:27 UTC, nusbaume commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_nu_top phys="cam_dev" model_top="mt"     > 1.0e6 </se_nu_top>
I am fine to remove it here too, as I agree that in general the physics shouldn't control the dycore settings.

2023-06-10 18:49 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
@adamrher, here is proposed code for `build-namelist` to implement the `micro_mg_dcs` defaults.  Please have a look and let me know if this provides the defaults you have in mind.

    # tunings for micro_mg_dcs
    my $microphys = $cfg->get('microphys');
    my $hgrid = $cfg->get('hgrid');
    my $silhs = $cfg->get('silhs');

    my $micro_mg_dcs = '400.D-6';        # default for cam5/mg1

    if ($microphys eq 'mg2') {
        if ($phys eq 'cam6') {
            $micro_mg_dcs = '500.D-6';   # default for cam6/mg2
        }
        elsif ($phys eq 'cam_dev') {
            $micro_mg_dcs = '250.D-6';   # default for cam_dev/mg2
        }
    }

    if ($microphys eq 'mg3') {
        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
    }

    if ($microphys =~ /mg2|mg3/ and $silhs eq '1') {
        $micro_mg_dcs = '390.D-6';       # default for SIHLS
    }
    elsif ($microphys =~ /mg2|mg3/ and $hgrid =~ /1.9x2.5/) {
        $micro_mg_dcs = '200.D-6';       # default for FV 2-deg
    }    

    add_default($nl, 'micro_mg_dcs', 'val'=>$micro_mg_dcs);

2023-06-14 15:23 UTC, PeterHjortLauritzen commented on bld/namelist_files/namelist_defaults_cam.xml
> +<se_nu_top phys="cam_dev" model_top="mt"     > 1.0e6 </se_nu_top>
agreed

2023-06-14 20:50 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
The build-namelist mods look good to me, Brian.

I will chat with Julio tmrw about the 2deg tunings, to get his take, and report back here.

2023-06-15 20:47 UTC, fvitt approved these changes

2023-06-15 22:06 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
I talked w/ Julio --- lets discuss this on Tuesday w/ the bigger group. Assuming you weren't planning on completing this PR before Tues?

2023-06-15 22:34 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
I'd rather get the PR "correct" than to get it in quickly.  I've added an item to Tuesday's agenda for discussion

2023-06-16 17:26 UTC, cacraigucar commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
This change is introducing answer changes for tests like FHIST.  Is that okay? @adamrher and @JulioTBacmeister what are your thoughts ?

2023-06-16 21:28 UTC, cacraigucar commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
This change is also changing answers for compsets like F2000climo (which uses mg3).  Is this wanted?  @adamrher @JulioTBacmeister

2023-06-16 21:52 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
hmmm ... we'll need to discuss this on Tues as well. It depends on what we want the non-FLT/FMT compsets to "mean" in CESM3.

I suspect we may want to go back to adding an explicit cam_dev if statement, but lets talk on Tues.

2023-06-16 21:55 UTC, adamrher commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
I think @brian-eaton may have made a typo? The default for mg3 in namelist_defaults was:

```
<micro_mg_dcs microphys="mg3"> 500.D-6 </micro_mg_dcs>
```

so I think this needs to be changed to 500E-6.

2023-06-16 21:56 UTC, adamrher commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
actually I don't think its a typo, I think an explicit cam_dev if statement needs to be added to the mg3 block, that sets it to 250E-6. Otherwise use the default 500E-6.

2023-06-17 00:25 UTC, brian-eaton commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
@cacraigucar, `F2000climo` uses `cam6` which implies `mg2`.  I don't think this build-namelist code should be a change for `F2000climo` which should still be getting `micro_mg_dcs=500E-6`.  That said, I was looking at your testing on cheyenne and see that there's an `F2000climo` compset run with `C96` which uses testmods from `cam/outfrq9s_mg3`.  That test using a `cam6/mg3` combo, which is not a configuration from a standard compset, should see diffs.
@adamrher, since `cam_dev` implies `mg3` (at least that's what's in configure), I intentionally set the default for `mg3` to 250e-6 which I thought was the value we wanted for the FLT* and FLM* compsets.  So I'm still thinking the way I set these defaults up is OK.  What do you think?

2023-06-17 00:31 UTC, adamrher commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
right, ok, so the issue is that for compsets using cam6 physics, you shouldn't be running tests using ```cam/outfrq9s_mg3```, since cam6 by definition in configure is mg2

```
elsif ($phys_pkg eq 'cam6') {
    $microphys_pkg = 'mg2';
}
```
I think that we need to ensure that tests using cam6 compsets (F2000climo,FHIST,etc...) are not xml'ing in mg3. I can't think of why this was done in the first place, but it's possible I'm missing something.

2023-06-17 00:58 UTC, adamrher commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
But to answer your broader question whether we can equate cam_dev with mg3, and therefore set the default mg3 values to represent cam_dev settings , I actually would like to revisit this at our tuesday meeting ... mg3 adds two additional dynamics tracers and I'm not sure we should be adding this additional computational cost to the already very expensive cam_dev/cam7, as it is intended to run with the increased levels L32->L58. Andrew keeps telling me the mg3 enhancements don't make a difference at 1˚.

2023-06-17 01:22 UTC, brian-eaton commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
In the past we've often set up tests using phys/chem combos or non-standard physics and/or chem configurations that a researcher may well like to try (e.g., `cam6/mg3`).  I don't think that's a bad idea.  In the case of running `F2000climo/mg3` I think the issue is just that we always need to justify "baseline comparison" failures in our regression tests.  This particular failure would be justified by saying it was due to changing an mg3 default namelist setting, if that's what we decide to do.  The issue the test raised turns out to be a good one:)

2023-06-20 16:25 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Following our convo at todays mtg, we decided we should preserve the L32 cam6 compsets (which will need to be renamed, and cheryl is planing to open a git issue to get that convo started) and so lets revert this logic back to how we first had it with the explicit cam_dev logic:

```
if ((not $waccm_phys) and
    ($do_gw_front or $do_gw_front_igw or
     $do_gw_convect_dp or $do_gw_convect_sh)) {
    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
} elsif ($phys =~ /cam_dev/) {
    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
```

This will maintain the value of false for cam6 compsets, which only uses orographic gw settings.

2023-06-20 16:56 UTC, gold2718 commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Out of curiousity, what is going to happen with 20 or so `science_support` tags? Are we still claiming they give answers compatible with publications?

2023-06-20 17:52 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
Following today's convo, I'd like to divorce cam_dev from mg version type. I'd like to make the 2deg tunings to be explicit they are for cam6 physics. So I propose:

```
# tunings for micro_mg_dcs
my $microphys = $cfg->get('microphys');
my $hgrid = $cfg->get('hgrid');
my $silhs = $cfg->get('silhs');

my $micro_mg_dcs = '400.D-6';        # default for cam5/mg1

if ($microphys =~ /mg2|mg3/) {
    if ($phys eq 'cam6') {
        $micro_mg_dcs = '500.D-6';   # default for cam6
    }
    elsif ($phys eq 'cam_dev') {
        $micro_mg_dcs = '250.D-6';   # default for cam_dev
    }
}

if ($microphys =~ /mg2|mg3/ and $silhs eq '1') {
    $micro_mg_dcs = '390.D-6';       # default for SIHLS
}
elsif ($microphys =~ /mg2|mg3/ and $hgrid =~ /1.9x2.5/ and $phys eq 'cam6') {
    $micro_mg_dcs = '200.D-6';       # default for FV 2-deg/cam6
}    

add_default($nl, 'micro_mg_dcs', 'val'=>$micro_mg_dcs);
```
maybe this can be done a bit more cleanly by throwing the 2deg if statement into the first ```if ($phys eq 'cam6')``` block?

My proposal is to also add ```phys="cam6"``` to the 2deg tunings, requiring modifying two entries in namelist_defaults:

```
<clubb_gamma_coef hgrid="1.9x2.5" phys="cam6" > 0.280   </clubb_gamma_coef>
```
...
```
<seasalt_emis_scale ver="strat" clubb_sgs="1" hgrid="1.9x2.5" phys="cam6">1.10D0</seasalt_emis_scale>
```

I'm not too concerned if this fails baselines (e.g., 2deg runs not running cam6); these 2deg tunings are intended to be specific to cam6.

2023-06-20 17:58 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Not sure about all 20, but in terms of the CMIP6 CESM2 FV1deg workhorse, technically, that has **not** been scientifically supported since we transitioned from cesm2.1.X for cesm2.2 or later, and started adding in new bells and whistles activated by the cam6 compsets.

2023-06-20 18:16 UTC, adamrher commented on bld/build-namelist
> +        $micro_mg_dcs = '250.D-6';       # default for cam_dev/mg3
my proposal above (https://github.com/ESCOMP/CAM/pull/820#discussion_r1235619211) addresses this convo as well. Will resolve this convo when we resolve that convo. Those mods should actually cause this baseline to pass, I think, but that's more of a bonus. Based on this conversation I'm of the opinion it doesn't matter too much if this baseline fails since it was a unique combo of cam6 and mg3, and therefore susceptible to changing the mg3 defaults.

And in response to my other claim

```
I think that we need to ensure that tests using cam6 compsets (F2000climo,FHIST,etc...) are not xml'ing in mg3. I can't think of why this was done in the first place, but it's possible I'm missing something.
```

Brian made clear that I was missing something; these exotic test combinations are useful as our user base will use exotic combinations, and so its nice to get these baseline failures so it reminds us how changing defaults changes impacts exotic combos.

2023-06-20 20:00 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
> maybe this can be done a bit more cleanly by throwing the 2deg if statement into the first if ($phys eq 'cam6') block?

I agree.

2023-06-20 20:29 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<micro_mg_dcs         microphys="mg3" phys="cam_dev">                  250.D-6    </micro_mg_dcs>
I have already put it and the SILHS check in the upper logic and am running tests now.  If it seems to be behaving properly, I'll go ahead and commit my changes so folks can see the proposed implementation.

2023-06-20 22:20 UTC, brian-eaton approved these changes

2023-06-20 22:30 UTC, adamrher requested changes
You did not revert the tau_0_ubc logic block back to how it was before. See this convo that I will resolve once completed: https://github.com/ESCOMP/CAM/pull/820/files#r1235512849

2023-06-20 22:30 UTC, adamrher commented on bld/build-namelist
> +
remove the ".../mg2" from the comments "default for ..."

2023-06-20 23:01 UTC, cacraigucar commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Sorry - I missed this when I made the edits.  Do I get "brownie points" for the issue I opened about making sure we review our `science_support` tags before our next code freeze?   The change has been made to build-namelist now.

2023-06-20 23:01 UTC, cacraigucar commented on bld/build-namelist
> +
done

2023-06-20 23:04 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Once you insert the cam_dev hammer back into this logic block (sorry if I wasn't clear on that), you'll get ur brownie points for the science support issue.

```
} elsif ($phys =~ /cam_dev/) {
    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
```

2023-06-20 23:11 UTC, cacraigucar commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
Added the cam_dev hammer back in.  Looking for my brownie points now?

2023-06-20 23:15 UTC, adamrher commented on bld/build-namelist
> +    add_default($nl, 'tau_0_ubc', 'val'=>'.true.');
brownie points granted. see brian dobbins for sweets.

2023-06-20 23:16 UTC, adamrher approved these changes

2023-06-21 03:32 UTC, nusbaume approved these changes

2023-06-21 18:08 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
I have an unexpected answer change for the SILHS regression test and have confirmed it is due to these two namelist settings being changed.  Is this expected and more importantly, are these the appropriate settings for SILHS?
@bstephens82 @adamrher @JulioTBacmeister @PeterHjortLauritzen

2023-06-21 18:26 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
@cacraigucar can you confirm this failing test does **not** invoke cam_dev?

@bstephens82 if Cheryl confirms this not a cam_dev test, then I think this means that the u/v mfl limiters are consequential for running diagnostic momentum fluxes (since only cam_dev can toggle on predict_upwp=T), contrary to what we thought.

2023-06-21 19:12 UTC, cacraigucar commented
@adamrher - I confimed that `cam_physpkg = 'cam6'`.  This was the only cheyenne test which had answer changes which I did not expect (all the rest were cam_dev).  

Should I halt the regression tests as we'll be changing something?

2023-06-21 19:38 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
Ah I see what's happening. For some reason, that predates this PR, there is this namelist entry:

```
<clubb_l_predict_upwp_vpwp              silhs="1" > .true.  </clubb_l_predict_upwp_vpwp>
```

I have no idea who did this or why. Nonetheless this would explain the baseline failure. @bstephens82 do you know about this? I'm inclined to delete this line from namelist_defaults.xml in this PR unless someone can tell me why we are turning on prognostic momentum with silhs.

2023-06-21 19:41 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
@adamrher - I confirmed that this was the setting from day 1 when SILHS was introduced into CAM.

2023-06-21 19:50 UTC, bstephens82 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
Yeah I don't know about that. Im not aware of a connection between SILHS and prognostic momentum fluxes.

2023-06-21 19:52 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
hmm ... my gut is now saying b/c this is grandfathered in, and plus SILHS is a bit of a mess right now, that we shouldn't mess with SILHS in this PR and perhaps just accept the baseline failure.

But I can only make sense of this baseline failure if there was also a silhs baseline failure for the last clubb externals update PR, where we introduced these nl's (```clubb_l_mono_flux_lim_um```/```clubb_l_mono_flux_lim_vm```) and had them default to false.

2023-06-21 19:58 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
In cam6_3_091, when the CLUBB and SILHS libraries were updated, the SILHS regression test along with all the CLUBB tests had answer changes and the explanation was "Expected answer changes due to new CLUBB code".

2023-06-21 20:07 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_mono_flux_lim_vm                         > .true.  </clubb_l_mono_flux_lim_vm>
ah, should've seen that coming. I say proceed with the testing and accept the silhs baseline failure. good to know going forward that silhs has prognostic momentum on from its inception.

2023-06-23 22:27 UTC, merged