Refactor aerosol optics for radiation transfer
ESCOMP/CAM pull request #824
Opened 2023-05-30 20:47 UTC by fvitt

closes #816 

Abstract interfaces to aerosol optical properties are introduced here (abstract aerosol_optics class).  This is extended to a concrete refractive_aerosol_optics classes which is used for modal aerosols here.

NOTE: The refactor introduces round-off level changes in the calculation of aerosol properties for long-wave radiation.

2023-06-23 22:56 UTC, cacraigucar reviewed
A couple of questions, but much more to review

2023-06-23 22:56 UTC, cacraigucar commented on src/physics/cam/aerosol_optics_cam.F90
> +       !aero_props(iaermod)%obj => carma_aerosol_properties()
Should this still be commented out?

2023-06-23 22:56 UTC, cacraigucar commented on src/physics/cam/aerosol_optics_cam.F90
> +       if ((lwavlen_lo(i)<=10._r8) .and. (lwavlen_hi(i)>=10._r8)) then
Should 10._r8 be a parameter (with a name that indicates what it is)?

2023-06-26 14:21 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +       !aero_props(iaermod)%obj => carma_aerosol_properties()
@cacraigucar, 
The `carma_aerosol_properties` class does not yet exist in cam_development.  If you don't like the commented out code in line 170, I could remove line 170 or remove the `else if (carma_active) then` block from this PR.  It will need to be restored when we have a `carma_aerosol_properties` class -- when CARMA trop_strat aerosols are added.

2023-06-26 16:17 UTC, cacraigucar commented on src/physics/cam/aerosol_optics_cam.F90
> +       !aero_props(iaermod)%obj => carma_aerosol_properties()
We've always been inclined to not include code for future development, as sometimes future development never happens.  It can also be misleading to users as they see the code, but don't see that the line that does the work is commented out.  With this information, if you know "for sure" that CARMA trop_strat is coming in in the near future, I will leave the decision up to you on how to handle this.  I would at the very least put in a comment "deferred implementation"

2023-06-26 17:40 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +       !aero_props(iaermod)%obj => carma_aerosol_properties()
I removed the `carma_active` code for this PR.

2023-06-26 17:41 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +       if ((lwavlen_lo(i)<=10._r8) .and. (lwavlen_hi(i)>=10._r8)) then
Added a parameter for 10 microns wavelength.

2023-07-05 22:29 UTC, cacraigucar requested changes
Next batch of review comments

2023-07-06 20:18 UTC, fvitt commented on src/chemistry/aerosol/refractive_aerosol_optics_mod.F90
> +  subroutine binterp(table,ncol,km,im,jm,x,y,xtab,ytab,ix,jy,t,u,out)
I would like to use the following utility for interpolation of the optics tables and do way with `subroutine binterp` 
https://github.com/fvitt/CAM/blob/carma_mam_classes/src/physics/cam/table_interp_mod.F90

This what we have been using for interpolation of the CARMA optics tables.

I hesitated in using this for the MAM optics because I am thinking that this would introduce changes that may be larger than round-off.  There is already a round off level change in the long-wave optics.  How concerned are we about answer changes?  @cacraigucar

2023-07-06 22:19 UTC, fvitt commented on bld/namelist_files/use_cases/2000_trop_strat_vbs_cam6.xml
> +         'CFC11STAR', 'AODDUST', 'AODDUST02', 'T', 'U', 'V', 'O3', 'OH', 'NO3', 'HO2',
Are there any compsets that use the `cime_config/usermods_dirs/CMIP6_*` settings in the latest development versions?  As far as I can tell, those are not being used anymore.

2023-07-06 22:25 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +       num_aero_models = num_aero_models+1 ! count aerosol models
Yes this is for future development. This is to allow for both MAM and CARMA (or other) aerosols in the same simulation.  There are some comments on this near line 45.

2023-07-06 22:27 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    end if
Don't think so.  This would be clearer if there was a `carma_active` block.

2023-07-06 22:28 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    end if
Don't think so.  See comment above.

2023-07-07 15:59 UTC, fvitt commented on src/chemistry/aerosol/refractive_aerosol_optics_mod.F90
> +  real(r8), parameter :: xrmax=log(25.e-6_r8)
done

2023-07-07 16:00 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +         if (ilev.le.troplev(icol)) then
done

2023-07-07 16:00 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    if (dimlen .ne. nlwbands) then
done

2023-07-07 16:00 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    call cam_pio_openfile(ncid, infilename, PIO_NOWRITE)
the check has been added

2023-07-07 16:02 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    ierr = pio_inq_dimid(ncid, 'lw_band', did)
checks have been added for `ierr` return status in several places

2023-07-07 16:32 UTC, cacraigucar commented on src/chemistry/aerosol/refractive_aerosol_optics_mod.F90
> +  subroutine binterp(table,ncol,km,im,jm,x,y,xtab,ytab,ix,jy,t,u,out)
Perhaps we could open an issue for this and have `binterp` be updated in its own separate PR.  I think we want to make sure that we aren't missing a bigger accidental change with this PR, so don't want to bring in a knowingly larger than round-off change.

2023-07-07 16:48 UTC, nusbaume commented on src/chemistry/aerosol/refractive_aerosol_optics_mod.F90
> +  subroutine binterp(table,ncol,km,im,jm,x,y,xtab,ytab,ix,jy,t,u,out)
I would also vote for leaving this subroutine as-is for this PR, but opening an issue to help us remember to update/replace `binterp` at some point in the future (when we also aren't changing the aerosol interface itself).

2023-07-12 22:13 UTC, cacraigucar reviewed
If this is ready for tagging while I am on PTO, I give my approval if someone can verify these last items are addressed.

2023-07-12 22:13 UTC, cacraigucar commented on src/physics/cam/aerosol_optics_cam.F90
> +    end if
Could you point out where the check is occurring?  I can't seem to find it

2023-07-12 22:43 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    call cam_pio_openfile(ncid, infilename, PIO_NOWRITE)
See the check at line 166

2023-07-12 22:50 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    end if
Line 166 I have:
```
if (water_refindex_file=='NONE') then
       call endrun(prefix//'water_refindex_file must be specified')
...
```

2023-07-26 15:15 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +      call outfld('AODABSdn'//diag(list_idx), aodabs, pcols, lchnk)
I don't think this `AODABSdn` line is needed, as there is already an `outfld` call for it above.

2023-07-28 14:43 UTC, fvitt commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8) :: vol(ncol)
It might help with vectorization of the column loop if vol is an array.  Otherwise it could be a scalar.

2023-08-01 14:38 UTC, fvitt commented on src/chemistry/aerosol/refractive_aerosol_optics_mod.F90
> +  subroutine binterp(table,ncol,km,im,jm,x,y,xtab,ytab,ix,jy,t,u,out)
@cacraigucar and @nusbaume ,
I propose that answer changing modifications be brought in as a separate PR before this PR.  This will ensure that the refactor is not making an accidental change.  Then the climate should be bit-for-bit unchanged.  Some of the aerosol optics diagnostics may have roundoff level differences.  See issue #865.

2023-08-23 17:22 UTC, cacraigucar approved these changes
I believe there are a few of Matt's comments which should be addressed and are not

2023-08-27 15:50 UTC, nusbaume commented on src/chemistry/aerosol/aerosol_state_mod.F90
> +    real(r8) :: vol(ncol)
That a good point!  I'm fine to leave this as-is then.

2023-08-27 16:24 UTC, nusbaume requested changes
Getting close, but it does look like some of my requests were missed from the previous review.  I tried to comment on them to make them visible, but if you can't find them then please let me know.

2023-08-27 16:24 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +  use spmd_utils, only : masterproc
Looks like this request was missed in the first review round.

2023-08-27 16:24 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +             call endrun(subname // ':: ERROR reading namelist')
Looks like this request was missed in the first review round.

2023-08-27 16:24 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +    character(len=*), parameter :: prefix = 'aerosol_optics_cam_sw: '
Looks like this request was missed in the first review round.

2023-08-27 16:24 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +    character(len=256) :: locfile
Looks like this request was missed in the first review round.

2023-08-27 16:24 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +      call outfld('AODABSdn'//diag(list_idx), aodabs, pcols, lchnk)
Looks like this request was missed in the first review round.

2023-08-27 16:24 UTC, nusbaume commented on src/physics/cam/aerosol_optics_cam.F90
> +      call outfld('AODABS'//diag(list_idx), aodabs, pcols, lchnk)
Looks like this request was missed in the first review round.

2023-08-28 14:18 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +  use spmd_utils, only : masterproc
done

2023-08-28 14:18 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +             call endrun(subname // ':: ERROR reading namelist')
done

2023-08-28 14:18 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +    character(len=*), parameter :: prefix = 'aerosol_optics_cam_sw: '
fixed

2023-08-28 14:18 UTC, fvitt commented on src/physics/cam/aerosol_optics_cam.F90
> +      call outfld('AODABS'//diag(list_idx), aodabs, pcols, lchnk)
fixed

2023-08-28 14:56 UTC, nusbaume approved these changes
Everything looks good to me now.  Thanks!

2023-08-29 19:58 UTC, merged