Turn on HB where CLUBB is not active
ESCOMP/CAM pull request #849
Opened 2023-07-05 23:22 UTC by jtruesdal

To stabilize non-FV dycores the Holtslag-Boville PBL scheme will be turned on for those layers where CLUBB is not active.  A new namelist variable will be added to allow this new functionality.

The issue for the PR is #846.  This PR will also address issue #772.

The science validation for this code is:
https://webext.cgd.ucar.edu/FLTHIST/f.cam6_3_112.FLTHIST_v0c.ne30.non-ogw-ubcT-effgw0.3-rdg_beta0.5-vtrmi1.5-hb-tt.001/atm/

2023-07-05 23:24 UTC, jtruesdal commented
I am making some minor corrections due to regression test failures but will "undraft" this PR very soon.

2023-07-11 22:29 UTC, jtruesdal commented
@nusbaume Ready for initial review.  This PR is only for using HB scheme with cam_dev.

2023-08-08 21:28 UTC, nusbaume requested changes
Looks pretty good!  I only have some (hopefully) minor change requests and a few questions.

2023-08-08 21:28 UTC, nusbaume commented on src/physics/cam/hb_diff.F90
> +    character(len=16), intent(in) :: eddy_scheme
I don't think `eddy_scheme` is being used in this subroutine.

2023-08-08 21:28 UTC, nusbaume commented on src/physics/cam/vertical_diffusion.F90
> +     if (clubb_do_hb_above) then
Do we actually want to do this?  I thought this change was originally because of the physics re-order in `cam_dev`, and so it might cause problems if someone turns this option on for, say, CAM6 physics.

2023-08-08 21:37 UTC, nusbaume commented
Also forgot to ask if this PR will fully resolve issues #772 and #846?  If so it would be good to add the "closes #XXX" keyword to the main PR description box so that those issues are closed automatically once this PR is merged in.

2023-08-08 22:18 UTC, PeterHjortLauritzen commented on src/physics/cam/hb_diff.F90
> +    integer, intent(in) :: lchnk                      ! chunk index (for debug only)
Removed (Jesse = NAG compiler :-) )

2023-08-08 22:21 UTC, PeterHjortLauritzen commented on src/physics/cam/hb_diff.F90
> +    real(r8) :: thv(pcols,pver)         ! virtual temperature
agree. Comment fixed

2023-08-08 22:22 UTC, PeterHjortLauritzen commented on src/physics/cam/hb_diff.F90
> +    ! virtual temperature
fixed

2023-08-08 22:23 UTC, PeterHjortLauritzen commented on src/physics/cam/hb_diff.F90
> +    return
removed (also removed from subroutine compute_hb_diff on which this subroutine is based)

2023-08-08 22:23 UTC, PeterHjortLauritzen commented on src/physics/cam/vertical_diffusion.F90
> +  use phys_control,      only : waccmx_is, fv_am_correction, cam_physpkg_is
correct. removed.

2023-08-08 22:24 UTC, PeterHjortLauritzen commented on src/physics/cam/vertical_diffusion.F90
> +       call init_hb_diff(gravit, cpair, ntop_eddy, nbot_eddy, pref_mid, &
fixed

2023-08-10 00:05 UTC, jtruesdal commented on doc/ChangeLog
> +  - Introduced namelist variable clubb_do_hb_above. Default False unless using cam6 or cam_dev then
Yes.  Corrected the comment.  We will add cam6 when waccmx is working with this scheme.

2023-08-10 00:05 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +     ! run HB scheme where CLUBB is not active when running cam6 or cam_dev
Yep. Corrected the comment.

2023-08-10 00:05 UTC, jtruesdal commented on src/physics/cam/hb_diff.F90
> +    character(len=16), intent(in) :: eddy_scheme
Removed it here and in the call to compute_hb_free_atm_diff in vertical_diffusion.F90

2023-08-10 16:56 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +     if (clubb_do_hb_above) then
@PeterHjortLauritzen Jesse's catch here was actually a bug I introduced when getting the mods ready for the PR. Since it will affect the tests and could be the reason for the cam6 waccm failure I am rerunning the regression tests.  If everything passes we will be able to include CAM6 as part of this PR and be done with it. Thanks again for your careful review Jesse!

2023-08-11 00:57 UTC, PeterHjortLauritzen commented on src/physics/cam/vertical_diffusion.F90
> +     if (clubb_do_hb_above) then
My re-creation of the failing regression test (FX2000; CAM_CONFIG_OPTS: -phys cam6 -waccmx -ionosphere wxie -chem waccm_ma_mam5) is still failing with this code change ...

2023-08-14 19:34 UTC, jtruesdal commented
I modified the description to note that this PR currently applies to cam_dev and the issues noted will be kept open until a future PR addresses a couple cam6 regression errors.  The issues will be fully resolved and closed in that future PR.

2023-08-15 19:27 UTC, nusbaume commented on src/physics/cam/hb_diff.F90
> +    ! virtual temperature
It doesn't look like this change was actually committed/pushed?

2023-08-15 19:27 UTC, nusbaume commented on src/physics/cam/hb_diff.F90
> +    return
It doesn't look like this change was actually committed/pushed?

2023-08-15 22:47 UTC, PeterHjortLauritzen commented
> I think some changes were either not committed or not pushed. I tried to mark which changes were still "missing", but if it is unclear which changes those are just let me know. Thanks!

Sorry had a several day delay in pushing changes ...

2023-08-15 22:47 UTC, PeterHjortLauritzen commented on src/physics/cam/hb_diff.F90
> +    ! virtual temperature
Got very distracted and did not push ...

2023-08-18 05:24 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> +Logical: If True activate Holtslag and Boville PBL scheme where CLUBB is not active
Replaced PBL with "vertical diffusion"

2023-08-18 05:25 UTC, jtruesdal commented on src/physics/cam/hb_diff.F90
> +    integer, intent(in) :: lchnk                      ! chunk index (for debug only)
removed lchnk in called and calling routines.

2023-08-18 05:25 UTC, jtruesdal commented on src/physics/cam/hb_diff.F90
> +    real(r8) :: thv(pcols,pver)         ! virtual temperature
Looks to be OK now

2023-08-18 05:25 UTC, jtruesdal commented on src/physics/cam/hb_diff.F90
> +    ! virtual temperature
Fixed.

2023-08-18 05:25 UTC, jtruesdal commented on src/physics/cam/hb_diff.F90
> +    return
Looks like its OK now

2023-08-18 05:25 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +       call init_hb_diff(gravit, cpair, ntop_eddy, nbot_eddy, pref_mid, &
Looks to be fixed now.

2023-08-18 16:51 UTC, nusbaume approved these changes
Everything looks good to me now, thanks!

2023-08-18 17:22 UTC, cacraigucar requested changes
Need to use a keyword in the description to automatically close the issues.  `closes #XXX` is an example.

Submitting these comments early as they may take a bit to implement.  I plan on doing a more complete review, so more comments may be forthcoming (I also want to get feedback on whether my understanding is correct or not).

2023-08-18 17:22 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +<entry id="clubb_do_hb_above" type="logical" category="pbl"
I propose changing the name of this to be `do_hb_above_clubb`.   There are several reasons I believe this is advantageous:

1. It reads more like what it is doing (initially I saw this flag indicating clubb doing somthing in regards to hb)
2. This variable is really controlling hb and not clubb
3. All other `clubb_` namelists are controlling clubb behaviour

2023-08-18 17:22 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +         clubb_do_hb_above
I believe on my argument above, that this is actually controlling hb behaviour and not clubb.  If that is indeed the case, then I propose this namelist should be in the hb_diff module (and a namelist reader will need to be added to that module).

2023-08-18 20:18 UTC, cacraigucar requested changes
Next round of change requests

2023-08-21 13:38 UTC, jtruesdal commented on src/dynamics/se/dycore/global_norms_mod.F90
> +      if (sponge_del4_nu_div_fac.ne.1.0_r8) then
Fixed both instances.

2023-08-21 13:38 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +      call compute_hb_free_atm_diff( lchnk     , ncol          , &
Jesse noted that lchnk was not used in compute_hb_diff and hb_free_atm_diff and I removed them but apparently missed this parameter in the calling routine.  It's fixed now.

2023-08-21 13:47 UTC, jtruesdal commented on src/physics/cam/clubb_intr.F90
> +         clubb_do_hb_above
Sounds good to me. if @PeterHjortLauritzen agrees I'll make the changes.

2023-08-21 15:49 UTC, brian-eaton requested changes

2023-08-21 15:49 UTC, brian-eaton commented on src/physics/cam/vertical_diffusion.F90
> +      clubbtop_idx = pbuf_get_index('clubbtop')
The call to pbuf_get_index belongs in vertical_diffusion_init (so it's only done once).

2023-08-21 15:49 UTC, brian-eaton commented on src/physics/cam/vertical_diffusion.F90
> +  use physics_buffer,     only : pbuf_get_index
This should be removed along with the corresponding call below (belongs in init method).

2023-08-21 15:49 UTC, brian-eaton commented on src/physics/cam/vertical_diffusion.F90
> +  integer  :: clubbtop_idx
This should be private module data (initialized by init method).

2023-08-21 15:49 UTC, brian-eaton commented on src/physics/cam/clubb_intr.F90
> +         clubb_do_hb_above
I would suggest putting this in phys_ctl_nl.  That's a good place for a control variable that's needed in both clubb_intr and vertical_diffusion.  Putting it in vertical_diffusion is also an option since that's where the control layer is for vertical diffusion.  But clubb_intr can't access it directly from vertical diffusion because of circular dependency issues.  Another option is to let vertical_diffusion_register add clubbtop to the pbuf, then have clubb_ini_cam check to see whether the index is in the pbuf.  But I think putting it in phys_ctl_nl is probably the easiest, and most readily understandable.

2023-08-22 21:30 UTC, jtruesdal commented on doc/ChangeLog
> +  - Introduced namelist variable clubb_do_hb_above. Default False unless using cam6 or cam_dev then
As the cam6 fix is now included for using HB above CLUBB I changed the comment to reflect that it can be used for cam_dev and cam6.

2023-08-22 21:30 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +     ! run HB scheme where CLUBB is not active when running cam6 or cam_dev
As the cam6 fix is now included for using HB above CLUBB I changed the comment to reflect that it can be used for cam_dev and cam6.

2023-08-22 21:32 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> +<entry id="clubb_do_hb_above" type="logical" category="pbl"
Changed clubb_do_hb_above to do_hb_above_clubb and moved definition from clubb control section of namelist to "PBL and vertical diffusion" section.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/clubb_intr.F90
> +         clubb_do_hb_above
Moved HB control variable to to phys_ctl_nl. Now variable accessed via phy_getopts call like other physics control variables.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/clubb_intr.F90
> +    integer :: err_idx, idx
Removed.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/clubb_intr.F90
> +    use physics_buffer,  only: pbuf_add_field, dtype_r8, dtype_i4, dyn_time_lvls, pbuf_get_index
Removed.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +  use physics_buffer,      only : pbuf_add_field, dtype_r8, dtype_i4, pbuf_get_index
Removed.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +      clubbtop_idx = pbuf_get_index('clubbtop')
Moved call to pbuf_get_index as recommended.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +  use physics_buffer,     only : pbuf_get_index
Updated as recommended.

2023-08-22 22:51 UTC, jtruesdal commented on src/physics/cam/vertical_diffusion.F90
> +  integer  :: clubbtop_idx
Moved to private data.

2023-08-22 23:36 UTC, jtruesdal commented
@cacraigucar @nusbaume @brian-eaton Just a heads up: there is new code to look at for your rereview in addition to mods related to your comments.  Peter corrected the bug which caused cam6 FV regression failures.  The new mods are in geopotential.F90.  Previously do_hb_above_clubb was only enabled for cam_dev but now that we've corrected the error I am also enabling do_hb_above_clubb for cam6 as well.  Running HB above clubb is now the default for all dycores running cam6 or cam_dev physics.  Jesse, I unresolved 2 comments of yours that referenced incorrect comments that were modified with this latest addition (I added cam6 to the comment along with cam_dev.)

2023-08-23 12:56 UTC, brian-eaton commented on src/physics/cam/clubb_intr.F90
> +         clubb_do_hb_above
This is OK, but I'd like to point out that more recently we've just been accessing variables from the `phys_control` module by giving them `public, protected` attributes.  It's easier than adding arguments to the accessor methods which were implemented before the `protected` attribute was available.

2023-08-23 15:23 UTC, jtruesdal commented on src/physics/cam/clubb_intr.F90
> +         clubb_do_hb_above
I didn't notice that we had some public protected in there which is cleaner and easier.  I will update to that method as phys_control is already a mix of the two.  A little less to cleanup in the future.

2023-08-24 02:35 UTC, nusbaume approved these changes
The new changes look good to me!

2023-08-24 17:35 UTC, fvitt commented on doc/ChangeLog
> +     - pre-existing failure
Is HB active above clubb in this test case?  Shouldn't HB mixing stabilize WACCM-SE?  Does this need a new spunup IC file?

2023-08-28 23:08 UTC, jtruesdal commented on doc/ChangeLog
> +     - pre-existing failure
@PeterHjortLauritzen Do you have any insight into this failure? I think it is a crossing of levels failure. The HB mixing will stabilize WACCM-SE but it may not be enough to overcome an out of balance IC file. (If that is the issue)

2023-08-31 03:11 UTC, nusbaume requested changes
Looks good, but I did have one question that would be great for someone to sanity-check me on.

2023-08-31 03:11 UTC, nusbaume commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +                    cpair*T0*(grad_logexner(:,:,2)-pgf_term(:,:,2)/exner(:,:))
Is this formulation still equivalent to the previous one?  It looks like `grad_exner` variable was still just the gradient of the exner function at this point, but the `pgf_term` variable now includes a `cp_dry(:,:,k)*theta_v(:,:)` term as well.

2023-08-31 17:29 UTC, cacraigucar approved these changes

2023-09-01 22:40 UTC, jtruesdal commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +                    cpair*T0*(grad_logexner(:,:,2)-pgf_term(:,:,2)/exner(:,:))
I agree. @PeterHjortLauritzen could you double check the implementation for these lines?

2023-09-05 21:42 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +                    cpair*T0*(grad_logexner(:,:,2)-pgf_term(:,:,2)/exner(:,:))
Thanks @nusbaume ! Indeed a bug - I have verified that answers are bit-for-bit with the code version before the buggy commit.

2023-09-05 22:27 UTC, nusbaume approved these changes

2023-09-05 22:28 UTC, nusbaume commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +                    cpair*T0*(grad_logexner(:,:,2)-pgf_term(:,:,2)/exner(:,:))
Thanks @jtruesdal and @PeterHjortLauritzen!  The new code looks good to me.

2023-09-06 19:28 UTC, PeterHjortLauritzen commented on doc/ChangeLog
> +     - pre-existing failure
@fvitt Thanks for the comment/reminder: 

Yes HB helps stabilize the initial condition but the existing initial condition uses an older topography. With the new topography (where PHIS=0 over ocean) some spin-up with more damping is necessary (due to the gravity waves excited by the change in topography). Here is a spun-up initial condition:

/glade/p/cgd/amp/pel/inic/FW2000.ne30pg3_ne30pg3_nlev70.i.nc

(I did not know that when running with full chemistry the model does not run when using an FWsc2000 initial conditions - hangs at startup with plenty error messages in the CESM log file; so I took the default IC file and overwrote U,V,T,Q, PS with the spun-up fields from an FWsc2000 IC file I had: ncks -m -A -C -v U,V,T,Q,PS spinup.ic.nc orig.ic.nc)

For the failing test:

SMS_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30

we can now use the default se_nsplit. (no need to increase to 30 anymore).

Need some guidance to make these changes ... or maybe @jtruesdal can do it.

2023-09-06 19:58 UTC, fvitt commented on doc/ChangeLog
> +     - pre-existing failure
@PeterHjortLauritzen 
Full TSMLT chemistry can be tricky to spin up if all the chemical constituents are starting from zero concentrations (no chemical tracers in the IC file). The chemical solver may not converge in some places.  Are these the type of error messages you are seeing?
I am not sure what you need guidance on.  It sounds like you have a working IC by using the dynamical fields taken from a working FWsc2000 IC file...

2023-09-06 20:24 UTC, PeterHjortLauritzen commented on doc/ChangeLog
> +     - pre-existing failure
Yes exactly those errors ...

I have everything I need ... but I don't think I have permissions to add new IC files etc. I think @jtruesdal can take care of it ...

2023-09-06 20:27 UTC, PeterHjortLauritzen approved these changes

2023-09-06 20:43 UTC, PeterHjortLauritzen commented on doc/ChangeLog
> +     - pre-existing failure
... just realized I did not add the mandatory meta data to IC file and change the file name to incl. creation date!

Modified IC file now:

/glade/p/cgd/amp/pel/inic/FW2000.ne30pg3_ne30pg3_nlev70_c230906.nc

2023-09-07 13:54 UTC, fvitt requested changes
A few suggestions

2023-09-07 13:54 UTC, fvitt commented on bld/namelist_files/namelist_definition.xml
> +Default: none
Should the default be "FALSE" or "set by build-namelist"?

2023-09-07 13:54 UTC, fvitt commented on src/dynamics/se/dycore/control_mod.F90
> +  integer, public :: pgf_formulation !PGF formulation - see prim_advance_mod.F90
Initialize this to -1 here to ensure that it get properly set later
```suggestion
  integer, public :: pgf_formulation = -1 !PGF formulation - see prim_advance_mod.F90
```

2023-09-07 13:54 UTC, fvitt commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +           pgf_term(:,:,2)  = density_inv(:,:)*grad_p_full(:,:,2,k)
Is this block for pgf_formulation==2? Should check for pgf_formulation==2.  Error out if pgf_formulation is not 1 or 2.

2023-09-07 13:54 UTC, fvitt commented on src/physics/cam/vertical_diffusion.F90
> +  clubbtop_idx = pbuf_get_index('clubbtop')
Is the `clubbtop` pbuf field always available?
```suggestion
  if (do_hb_above_clubb) then
     ! pbuf field denoting top of clubb
     clubbtop_idx = pbuf_get_index('clubbtop')
  end if
```

2023-09-07 19:52 UTC, jtruesdal commented on doc/ChangeLog
> +     - pre-existing failure
I will check over the new IC file and load it onto our local systems.  I'll submit it to the data repository once the PR is approved.

2023-09-08 22:13 UTC, PeterHjortLauritzen commented on bld/namelist_files/namelist_definition.xml
> +Default: none
Default in namelist_defaults_cam.xml is false. Please check if I modified the code correctly ... thanks

2023-09-08 22:13 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/prim_advance_mod.F90
> +           pgf_term(:,:,2)  = density_inv(:,:)*grad_p_full(:,:,2,k)
Done!

2023-09-08 22:15 UTC, PeterHjortLauritzen commented on src/physics/cam/vertical_diffusion.F90
> +  clubbtop_idx = pbuf_get_index('clubbtop')
I think it is always available when using CLUBB

2023-09-08 23:40 UTC, brian-eaton commented on src/physics/cam/vertical_diffusion.F90
> +  clubbtop_idx = pbuf_get_index('clubbtop')
`clubb` is only on by default for `cam6/cam_dev`.  So I think the original code will fail for pre-cam6 configurations.  Francis's suggested change is one approach.  Another would be to use the optional `errcode` argument to `pbuf_get_index` so that if it's not available the function will just return -1 rather than `call endrun`.

2023-09-08 23:56 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +Default: none
It is done correctly, but the default depends on the physics package.  So the documentation in `namelist_definition.xml` should read:
`Default: Set by build-namelist.` instead of `Default: none`

2023-09-11 13:18 UTC, PeterHjortLauritzen commented on bld/namelist_files/namelist_definition.xml
> +Default: none
Thanks. Changed to "Set by build-namelist."

2023-09-11 18:02 UTC, jtruesdal commented on doc/ChangeLog
> +     - pre-existing failure
SMS and ERP WACCM tests now passing using the new IC and default se_nsplit

2023-09-11 18:09 UTC, fvitt approved these changes

2023-09-12 20:28 UTC, merged