CAM-chem updates
ESCOMP/CAM pull request #850
Opened 2023-07-06 19:30 UTC by fvitt

closes #771 
fixes #538

2023-07-12 21:26 UTC, cacraigucar approved these changes

2023-07-14 15:39 UTC, nusbaume requested changes
Looks good, but I did have a few small requests and one question.

2023-07-14 15:39 UTC, nusbaume commented on src/chemistry/mozart/chemistry.F90
> +       allocate( megan_wght_factors(shr_megan_mechcomps_n) )
I would add `stat` checks to these allocate statements.

2023-07-14 15:39 UTC, nusbaume commented on src/chemistry/mozart/chemistry.F90
> +    end function aero_has_emis
I believe this function can be `pure`.

Also, I might add `intent(in)` to the `spcname` variable just to be paranoid.

2023-07-14 15:39 UTC, nusbaume commented on src/chemistry/mozart/ocean_emis.F90
> +  logical function ocean_emis_species(name)
I believe this function can be `pure`.

2023-07-14 21:11 UTC, fvitt commented on bld/namelist_files/use_cases/hist_trop_strat_vbsfire_cam6.xml
> +   'ACTREL', 'AQ_SO2', 'AREA', 'BROX', 'BROY', 'BRY', 'CLOX', 'CLOY', 'CLY',  'NOX', 'NOY', 'TBRY', 'TCLY',  'CFC11STAR',
Yes. Thanks.

2023-07-14 21:11 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +       allocate( megan_wght_factors(shr_megan_mechcomps_n) )
done

2023-07-14 21:12 UTC, fvitt commented on src/chemistry/mozart/chemistry.F90
> +    end function aero_has_emis
done

2023-07-14 21:12 UTC, fvitt commented on src/chemistry/mozart/ocean_emis.F90
> +  logical function ocean_emis_species(name)
done

2023-07-17 15:08 UTC, nusbaume approved these changes
Looks great now, thanks!  I did find one possible typo in a comment, but I don't think it requires holding up this PR for another review.

2023-07-17 15:08 UTC, nusbaume commented on src/chemistry/mozart/ocean_emis.F90
>    ! returns TRUE of species has ocean emissions
I assume `returns TRUE of` should be `returns TRUE if`?

2023-07-19 19:32 UTC, merged