New PUMAS external with machine learning support
ESCOMP/CAM pull request #858
Opened 2023-07-17 23:23 UTC by Katetc

Preliminary PR with the tag for PUMAS now including early support for a machine learning kernel.

2023-10-13 22:25 UTC, cacraigucar requested changes

2023-10-13 22:25 UTC, cacraigucar commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +               stochastic_emulated_filename_quantile
This was a note to myself that this write statement needed to be dealt with.  Either iulog needs to be used or the write needs to be removed.

2023-10-13 22:25 UTC, cacraigucar commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +  write(0,*) ' Inside stochastic_tau_readnl, pumas_stochastic_tau_kernel_filename=',pumas_stochastic_tau_kernel_filename
This was a note to myself that this write statement needed to be dealt with.  Either iulog needs to be used or the write needs to be removed.

2023-10-13 22:25 UTC, cacraigucar commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +integer, parameter, public  :: ncd = 35
Should this be namelist option, or does ML always use 35?  If it becomes a namelist then it should be renamed soemthing like "pumas_ml_ncd".   If it becomes a namelist, then the same change needs to be made in stochastic_emulated_cam.F90

2023-10-13 22:25 UTC, cacraigucar commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +integer, private  :: cutoff_id                       ! cutoff between cloud water and rain drop, D = 40 microns
I believe these can all be removed - they don't appear to be used anywhere in this module

2023-10-13 22:25 UTC, cacraigucar commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +use micro_pumas_utils, only: pi, rhow, qsmall
These are not used and can be removed

2023-10-13 22:25 UTC, cacraigucar commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +use micro_pumas_utils, only: pi, rhow, qsmall
These are not used and can be removed

2023-10-23 22:53 UTC, Katetc commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="derecho"  compiler="intel" category="aux_pumas"/>
Can I use test_driver.sh to run the aux_pumas suite? I don't know how to do that... I'm just using the create_test command. And, when using the command, I need to specify that it's a derecho test.

2023-10-23 22:56 UTC, Katetc commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s_pumas_tau" supported="false">
I agree with this in the long run, but right now, the ML code is still early development. It's likely there will be updates and changes, and it is a VERY experimental option that is not available in any out-of-the-box sense. I don't think these tests _currently_ belong in aux_cam or pre_alpha. Perhaps the next PUMAS PR.

2023-10-24 03:25 UTC, peverwhee commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="derecho"  compiler="intel" category="aux_pumas"/>
@Katetc you can run test_driver.sh with the "--cesm aux_pumas" argument.

As @cacraigucar mentioned, the test_driver script is currently looking for "cheyenne" for derecho tests, so just running 

> ./test_driver.sh --cesm aux_pumas

should do the trick and the duplicate "derecho" test in testlist_cam can be removed.

2023-10-24 19:30 UTC, Katetc commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="derecho"  compiler="intel" category="aux_pumas"/>
Awesome, thanks! I'll remove the duplicate tests now. I'm wondering if I can use test_driver on the aux_glc testlist for cism wrapper too... I'll have to give this a try. :)

2023-10-24 20:12 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +integer, parameter, public  :: ncd = 35
Because of the fact that this is used as a dimension in arrays (and not just a limit or adjustable scaling factor), I'm hesitant to add it as a namelist parameter right at this moment. I can add an issue in PUMAS to ask if this should be namelist parameter in the future, and to thoroughly test what the impact of that might be at that time.

2023-10-24 20:20 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +integer, parameter, public  :: ncd = 35
https://github.com/ESCOMP/PUMAS/issues/62

2023-10-24 20:21 UTC, Katetc commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +               stochastic_emulated_filename_quantile
Added the iulog and Adjusted the message just a bit.

2023-10-24 20:21 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +  write(0,*) ' Inside stochastic_tau_readnl, pumas_stochastic_tau_kernel_filename=',pumas_stochastic_tau_kernel_filename
Added the iulog and adjusted the message a bit.

2023-10-24 20:27 UTC, Katetc commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +integer, private  :: cutoff_id                       ! cutoff between cloud water and rain drop, D = 40 microns
I agree, removed

2023-10-24 20:37 UTC, Katetc commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +use micro_pumas_utils, only: pi, rhow, qsmall
"r8" is not used, so I removed it. "cl" and "addfld" are both used, so not removed. "pi", "rhow", and "qsmall" not used, so removed.

2023-10-24 20:44 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +use micro_pumas_utils, only: pi, rhow, qsmall
Removed "r8" and "micro_pumas_utils" use statements. Left "cl" and "addfld" as they are used.

2023-10-26 18:20 UTC, peverwhee approved these changes
Thanks for addressing all of @cacraigucar 's comments! I just have one small question in configure.

2023-10-26 18:20 UTC, peverwhee commented on bld/configure
> +    unless ($microphys_pkg =~ /^mg|pumas/) {
based on lines 842-845, is checking for "pumas" necessary?

2023-10-26 18:20 UTC, peverwhee commented on bld/configure
> +    unless ($microphys_pkg =~ /^mg|pumas/) {
(same question for all the "|pumas" checks in this file)

2023-11-02 17:53 UTC, Katetc commented on bld/configure
> +    unless ($microphys_pkg =~ /^mg|pumas/) {
I gave adding pumas a go and it just didn't work. I'll remove these guys too. :)

2023-11-02 18:00 UTC, sjsprecious commented on bld/configure
> +    unless ($microphys_pkg =~ /^mg|pumas/) {
maybe you can try `$microphys_pkg =~ /^(mg|pumas)/` instead (an answer from ChatGPT)?

2023-11-02 18:05 UTC, Katetc commented on bld/configure
> +    unless ($microphys_pkg =~ /^mg|pumas/) {
Oh, this particular code worked. But, overall, when I tried to make "microphys=pumas" work in CAM physics, there were too many hard coded places where "mg" or something similar lurked and I couldn't find them all before I ran out of time and good will. I got tripped up with CLDLIQ not showing up in the pbuf for some reason...anyway. Cheryl (and others) don't want code hanging around that isn't ultimately used, as this isn't currently used, and I understand that.

2023-11-02 19:02 UTC, Katetc commented
Hi all, I also wanted to add a note that, currently, the "Emulated" option in the ML is not working. It was for a while with Cheryl's work and then some updates from the group broke it. The ML group are working on another update now that should fix it going forward. As I mentioned in a comment above, the code modification here are still early stages, and issues won't impact any other compset or configuration in CAM. I don't know if we will have the final changes before we get to the CAM tag, so there may be another PUMAS update in the next few weeks.

2023-12-08 13:48 UTC, nusbaume requested changes
Looks good!  Just have some minor change requests.

2023-12-08 13:48 UTC, nusbaume commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +           call endrun(sub // ':: ERROR reading namelist')
I might include the `iostat` value in the error message as well:

```suggestion
           call endrun(sub // ':: ERROR reading namelist, iostat = ' // int2str(ierr))
```
where `int2str` comes from `string_utils`.

2023-12-08 13:48 UTC, nusbaume commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +    call addfld('ank_r',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
Should these be `rain` instead of `cloud liquid`?

2023-12-08 13:48 UTC, nusbaume commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency of ML fixer is activated')
minor grammar issue:

```suggestion
    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency that ML fixer is activated')
```

2023-12-08 13:48 UTC, nusbaume commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +           call endrun(sub // ':: ERROR reading namelist')
I might include the `iostat` value in the error message as well:

```suggestion
           call endrun(sub // ':: ERROR reading namelist, iostat = ' // int2str(ierr))
```
where `int2str` comes from `string_utils`.

2023-12-08 13:48 UTC, nusbaume commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +    call addfld('ank_r',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
Should these be `rain` instead of `cloud liquid`?

2023-12-08 13:48 UTC, nusbaume commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency of ML fixer is activated')
Grammar change:

```suggestion
    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency that ML fixer is activated')
```

2023-12-14 00:23 UTC, Katetc commented on cime_config/SystemTests/mgp.py
> +from CIME.SystemTests.restart_tests import SystemTestsCompareTwo
Because I was using a CAM restart test for guidance and didn't know that you could do that. I have updated the test now, thanks!

2023-12-16 00:17 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Coefficients for the stochastic collection kernel used by the TAU stochastice collection code, invoked in PUMAS with micro_pumas_warm_rain = 'tau'
Fixed

2023-12-16 00:19 UTC, Katetc commented on cime_config/SystemTests/mgp.py
> +        run_two_description="restart",
When I first made this test, I tried this but changing this text broke it somehow (I forget exactly why). When I changed to pulling the test import from Restart to CompareTwo, this seems to be working now! So, I was able to follow your suggestion. Yey!

2023-12-16 00:19 UTC, Katetc commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="MGP_D_Ln9" testmods="cam/outfrq3s">
Added

2023-12-16 00:19 UTC, Katetc commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s_pumas_tau" supported="false">
Added

2023-12-16 00:20 UTC, Katetc commented on src/physics/cam_dev/micro_pumas_cam.F90
> +   call addfld ('nrtend_SB2001',     (/ 'trop_cld_lev' /), 'A', '#/kg/s',  'rain number tendency due to autoconversion  & accretion from SB2001')
Added if tests for these.

2023-12-16 00:20 UTC, Katetc commented on src/physics/cam_dev/micro_pumas_cam.F90
> +   call outfld('nrtend_KK2000',  proc_rates%nrtend_KK2000,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
Added if tests for these also.

2023-12-16 00:20 UTC, Katetc commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +           call endrun(sub // ':: ERROR reading namelist')
Added this

2023-12-16 00:20 UTC, Katetc commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +    call addfld('ank_r',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
Yep. Fixed!

2023-12-16 00:21 UTC, Katetc commented on src/physics/cam_dev/stochastic_emulated_cam.F90
> +    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency of ML fixer is activated')
Fixed it.

2023-12-16 00:21 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +           call endrun(sub // ':: ERROR reading namelist')
Added

2023-12-16 00:21 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +    call addfld('ank_r',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
Yep, fixed it!

2023-12-16 00:21 UTC, Katetc commented on src/physics/cam_dev/stochastic_tau_cam.F90
> +    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency of ML fixer is activated')
Fixed

2023-12-18 20:24 UTC, cacraigucar approved these changes
Resolved all @nusbaume conversations.  Giving my final approval as well.

2024-01-02 20:34 UTC, cacraigucar commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!--micro_mg_vtrms_factor phys="cam_dev"   >  0.5D0    </micro_mg_vtrms_factor-->
My previous comment did not appear in this PR, so I am repeating it.  I am wondering why you commented this out instead of removing it completely?  If it will return in an upcoming PR, I am okay with leaving it, but if not, I would suggest it be removed in your next PR.

2024-01-02 21:20 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<!--micro_mg_vtrms_factor phys="cam_dev"   >  0.5D0    </micro_mg_vtrms_factor-->
It was for testing quickly last week. I'll remove it before the merge.

2024-01-02 22:37 UTC, merged