Aerosol optics updates
ESCOMP/CAM pull request #868
Opened 2023-08-02 19:21 UTC by fvitt

closes #865 

Answer changes are expected to be near roundoff

2023-08-04 19:44 UTC, cacraigucar approved these changes

2023-08-09 23:02 UTC, nusbaume requested changes
Looks good!  Just have a couple change requests and a question.

2023-08-10 14:54 UTC, fvitt commented on src/physics/cam/modal_aer_opt.F90
> +                flag_xyfill=.true.)
fixed

2023-08-10 14:54 UTC, fvitt commented on src/physics/cam/modal_aer_opt.F90
> +              'Aerosol optical depth summed over all sw wavelenghts', flag_xyfill=.true.)
fixed

2023-08-10 14:54 UTC, fvitt commented on src/physics/cam/modal_aer_opt.F90
> +                  ! write(iulog,*) 'cext=',(cext(l,i),l=1,ncoef)
removed

2023-08-10 17:17 UTC, nusbaume approved these changes
Looks great now, thanks!

2023-08-11 17:12 UTC, merged