Change "time" value for averaged quantities to midpoint of averaging period
ESCOMP/CAM pull request #869
Opened 2023-08-03 18:48 UTC by peverwhee

### Overview
Per #159 - this PR changes the "time" variable in a history file with averaged (and/or min/max/stdev quantities) to be the midpoint of the averaging period (basically, the average of the time_bounds variable).

Side affects of the above/related changes in this PR (all implemented):
* Instantaneous history files (avgflag_pertape = 'I') cannot have averaged fields due to the time mismatch
* Averaged history files (avgflag_pertape /= 'I') cannot have instantaneous fields (same reason)
* Changed 'time_bnds' variable name to 'time_bounds'
* Ensured the 'cell_methods' metadata field always includes "time: XXXXX" (where XXXXX refers to the avgflag) for history fields so that it's always clear what operation is being done on/for that field

### Tests performed locally
* Tested out-of-the-box Kessler (h0 is instantaneous) - runs and time field is current time
* Tested trying to add an average field to h0 - fails as expected
* Tested adding an average tape (h1) - runs and time field is midpoint(s)
* Tested adding an instantaneous field to h1 - fails as expected
* Tested adding instantaneous field (":I") to h0 and average field (":M") to h1 - works as expected

Related to: https://github.com/ESCOMP/CTSM/pull/2019

closes #159

2023-08-04 22:57 UTC, peverwhee commented
Requesting @fvitt take a look at the updated WACCM use case namelists

2023-08-05 01:07 UTC, fvitt requested changes
Some suggestions

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccm_tsmlt_1850_cam6.xml
> +<nhtfrq>          0,  -24,  -6,  -3,  -1,   1, -24,-120,-120  </nhtfrq>
Set the corresponding mfilt to 73

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccm_tsmlt_2000_cam6.xml
> +<nhtfrq>          0,  -24,  -6,  -3,  -1,   1, -24,-120,-120  </nhtfrq>
Set the corresponding mfilt to 73

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccm_tsmlt_2010_cam6.xml
> +<mfilt>           1,    5,  20,  40, 120, 240, 365,  73, 365  </mfilt>
```suggestion
<mfilt>           1,    5,  20,  40, 120, 240, 365,  73, 73  </mfilt>
```

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccm_tsmlt_hist_cam6.xml
> +<mfilt>           1,    5,  20,  40, 120, 240, 365,  73, 365  </mfilt>
```suggestion
<mfilt>           1,    5,  20,  40, 120, 240, 365,  73, 73  </mfilt>
```

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccmx_ma_2000_cam4.xml
> +  'DTCORE', 'CLDLIQ', 'CLDICE', 'CONCLD', 'FRONTGF', 'BUTGWSPEC', 'BTAUE', 'BTAUW', 'BTAUN', 'BTAUS', 'TAUE',
Should move `'FRONTGF'` to fincl4 which should be designated as `'I'`

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccmx_ma_2000_cam6.xml
> +	 'Z3GM', 'OpDens', 'EDens', 'FRONTGF'
`'FRONTGF'` should be moved to fincl4

2023-08-05 01:07 UTC, fvitt commented on bld/namelist_files/use_cases/waccmxie_ma_2000_cam4.xml
> +	 'TCLY', 'TOTH', 'UIONTEND', 'VIONTEND', 'DiTCORE', 'CLDLIQ', 'CLDICE', 'CONCLD',
```suggestion
	 'TCLY', 'TOTH', 'UIONTEND', 'VIONTEND', 'DTCORE', 'CLDLIQ', 'CLDICE', 'CONCLD',
```

2023-08-07 17:54 UTC, peverwhee commented on bld/namelist_files/use_cases/sd_waccm_ma_cam4.xml
>  <mfilt>             1,  30, 120, 240, 240, 480, 365,  73,  30  </mfilt>
changed.

2023-08-07 17:54 UTC, peverwhee commented on bld/namelist_files/use_cases/1950-2010_ccmi_refc1_waccmx_ma.xml
> +<mfilt>             1,   24,    7,    7,   10, 365,  10  </mfilt>
changed, though I did not add the extra average history tape and instead changed the existing tape numbers in the finclx variables.

2023-08-07 17:54 UTC, peverwhee commented on bld/namelist_files/use_cases/sd_waccm_ma_cam6.xml
>  <mfilt>             1,  30, 120, 240, 240, 480, 365,  73,  30  </mfilt>
changed.

2023-08-07 17:54 UTC, peverwhee commented on bld/namelist_files/use_cases/sd_waccm_sulfur.xml
> +  'PS', 'PSL', 'U', 'V', 'T', 'Z3', 'PHIS','FRONTGF', 'OMEGA'
moved.

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_ma_1850_cam6.xml
> +<nhtfrq>            0, -24,  -6,  -3,  -1,   1, -24,-120,-120  </nhtfrq>
changed

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_ma_2000_cam6.xml
> +<nhtfrq>            0, -24,  -6,  -3,  -1,   1, -24,-120,-120  </nhtfrq>
changed

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_ma_hist_cam6.xml
> +<nhtfrq>            0, -24,  -6,  -3,  -1,   1, -24,-120,-120  </nhtfrq>
changed.

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_sc_2000_cam4.xml
> +<mfilt>            1,   10,   20,  73, 365, 10 </mfilt>
changed.

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_tsmlt_1850_cam6.xml
> +<nhtfrq>          0,  -24,  -6,  -3,  -1,   1, -24,-120,-120  </nhtfrq>
changed.

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_tsmlt_2010_cam6.xml
> +<mfilt>           1,    5,  20,  40, 120, 240, 365,  73, 365  </mfilt>
changed.

2023-08-07 17:55 UTC, peverwhee commented on bld/namelist_files/use_cases/waccm_tsmlt_hist_cam6.xml
> +<mfilt>           1,    5,  20,  40, 120, 240, 365,  73, 365  </mfilt>
changed.

2023-08-07 17:56 UTC, peverwhee commented on bld/namelist_files/use_cases/waccmx_ma_2000_cam4.xml
> +  'DTCORE', 'CLDLIQ', 'CLDICE', 'CONCLD', 'FRONTGF', 'BUTGWSPEC', 'BTAUE', 'BTAUW', 'BTAUN', 'BTAUS', 'TAUE',
moved and changed.

2023-08-07 17:56 UTC, peverwhee commented on bld/namelist_files/use_cases/waccmx_ma_2000_cam6.xml
> +	 'Z3GM', 'OpDens', 'EDens', 'FRONTGF'
moved and changed

2023-08-07 17:56 UTC, peverwhee commented on bld/namelist_files/use_cases/waccmxie_ma_2000_cam4.xml
> +	 'TCLY', 'TOTH', 'UIONTEND', 'VIONTEND', 'DiTCORE', 'CLDLIQ', 'CLDICE', 'CONCLD',
fixed

2023-10-13 00:40 UTC, closed without merging