Fix memory issue, default PE layout for FMTHIST
ESCOMP/CAM pull request #872
Opened 2023-08-10 22:21 UTC by fvitt

closes #812 
closes #841

2023-08-11 15:42 UTC, cacraigucar commented
ERP test gave a floating point exception in wetdep.  My test case is at:
glade/scratch/cacraig/ERP_D_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FMTHIST.cheyenne_gnu.cam-outfrq9s.20230810_165939_t5efa4

1:Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
1:
1:Backtrace for this error:
109:#0  0x2b376d377bff in ???
109:#1  0x11bfc2b in __wetdep_MOD_wetdepa_v2
109:    at /glade/scratch/cacraig/cam_unstr_emis_fix/src/chemistry/aerosol/wetdep.F90:522
109:#2  0xc74c03 in __aero_model_MOD_aero_model_wetdep
109:    at /glade/scratch/cacraig/cam_unstr_emis_fix/src/chemistry/modal_aero/aero_model.F90:1543

2023-08-14 15:44 UTC, cacraigucar requested changes
Thank

2023-08-16 16:57 UTC, fvitt commented
> ERP test gave a floating point exception in wetdep. My test case is at: glade/scratch/cacraig/ERP_D_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FMTHIST.cheyenne_gnu.cam-outfrq9s.20230810_165939_t5efa4
> 
> 1:Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation. 1: 1:Backtrace for this error: 109:#0 0x2b376d377bff in ??? 109:#1 0x11bfc2b in __wetdep_MOD_wetdepa_v2 109: at /glade/scratch/cacraig/cam_unstr_emis_fix/src/chemistry/aerosol/wetdep.F90:522 109:#2 0xc74c03 in __aero_model_MOD_aero_model_wetdep 109: at /glade/scratch/cacraig/cam_unstr_emis_fix/src/chemistry/modal_aero/aero_model.F90:1543

The ERP test should pass with my latest changes

2023-08-16 17:15 UTC, fvitt commented on cime_config/config_pes.xml
> +      <pes pesize="any" compset="_CAM%DEV%MT%GHGMAM4_">
The default PE layouts for derecho seem to work okay

2023-08-16 17:16 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FMTHIST" grid="ne30pg3_ne30pg3_mg17" name="SMS_Ln9" testmods="cam/outfrq9s">
changed as suggested

2023-08-16 17:16 UTC, fvitt commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="aux_cam"/>
changed as suggested

2023-08-16 22:41 UTC, cacraigucar approved these changes

2023-08-16 22:55 UTC, cacraigucar commented
> > ERP test gave a floating point exception in wetdep. My test case is at: glade/scratch/cacraig/ERP_D_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FMTHIST.cheyenne_gnu.cam-outfrq9s.20230810_165939_t5efa4
> > 1:Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation. 1: 1:Backtrace for this error: 109:#0 0x2b376d377bff in ??? 109:#1 0x11bfc2b in __wetdep_MOD_wetdepa_v2 109: at /glade/scratch/cacraig/cam_unstr_emis_fix/src/chemistry/aerosol/wetdep.F90:522 109:#2 0xc74c03 in __aero_model_MOD_aero_model_wetdep 109: at /glade/scratch/cacraig/cam_unstr_emis_fix/src/chemistry/modal_aero/aero_model.F90:1543
> 
> The ERP test should pass with my latest changes

I should have pointed out that I was able to run the ERP test which previously failed, and it does indeed run properly.  Thanks @fvitt!!

2023-08-22 02:45 UTC, nusbaume approved these changes
Looks good!  I found a couple small things but nothing that would require a re-review.

2023-08-22 02:45 UTC, nusbaume commented on cime_config/testdefs/testlist_cam.xml
> +      <option name="comment">"CAM7 dev low top ~40 km"</option>
I don't think we need the quotations inside the comment text itself, e.g.:

```suggestion
      <option name="comment">CAM7 dev low top ~40 km</option>
```

The same holds for the other test description comments below as well.

2023-08-22 02:45 UTC, nusbaume commented on src/dynamics/se/dyn_comp.F90
> +        write(iulog,*) "Molecular viscoity and thermal conductivity reference profile"
Typo here (`viscoity` -> `viscosity`).

2023-08-23 20:04 UTC, merged