CAM misc tag for derecho testing, fix SILHS output and fix single-exe for PLB tests
ESCOMP/CAM pull request #884
Opened 2023-09-12 22:12 UTC by cacraigucar

closes #879 (Add derecho support for test_driver)
closes #792  (changes to fix single-exe option for PLB tests) 
closes #855 (Bug fix for SILHS history output being garbled)

2023-09-13 16:49 UTC, fvitt commented
I believe you should update the external ccs_config tag to ccs_config_cesm0.0.75 for derecho testing

2023-09-18 20:28 UTC, cacraigucar commented
I have a request to have an updated ccs_config tag made which allows cheyenne tests to pass for all users (so it hopefully that external will be updated).   Feel free to review the rest of this PR, knowing that the ccs_config external may be updated

2023-09-19 19:26 UTC, jtruesdal approved these changes
Looks good.  While reviewing I did notice that the fms library updates are not consistent with the current fv3 tag.  Nice catch.  FMS will be updated with an fv3 PR in the near future.

2023-09-20 16:44 UTC, nusbaume requested changes
Looks good, but I did have a few minor test_driver questions and change requests.

2023-09-20 16:44 UTC, nusbaume commented on test/system/test_driver.sh
> +    CAM_RESTART_THREADS=1
Why set these variables at all if they are just going to be ignored?

2023-09-20 17:51 UTC, fischer-ncar commented on test/system/test_driver.sh
> +        exit
Agreed, I'll add a non-zero exit code.

2023-09-20 17:52 UTC, fischer-ncar commented on test/system/test_driver.sh
> +    CAM_RESTART_THREADS=1
I believe that if you force all of the tests to run on a single node, like on izumi, then these variables will probably be used.  I was just concentrating on getting the tests running on derecho and didn't wont to dig too deep into the script.

2023-09-20 17:52 UTC, fischer-ncar commented on test/system/test_driver.sh
> +#PBS -l walltime=4:00:00
It should be walltime.  All of the CISL examples use walltime, and ccs_config is also using walltime.

2023-09-20 20:57 UTC, nusbaume commented on test/system/test_driver.sh
> +    CAM_RESTART_THREADS=1
Ahh, that makes sense.  I'm fine to leave this as-is then.

2023-09-20 20:59 UTC, nusbaume commented on test/system/test_driver.sh
> +#PBS -l walltime=4:00:00
Sorry, I wasn't referring to the `walltime` PBS variable, I was referring to the actual `wallclock_limit` variable set earlier in the script. In other words should this line be:

```suggestion
#PBS -l walltime=$wallclock_limit
```

2023-09-20 23:02 UTC, fischer-ncar commented on test/system/test_driver.sh
> +#PBS -l walltime=4:00:00
Okay, I got it.  I pushed commits to use $wallclock_limit for derecho, cheyenne, and casper.

2023-09-21 14:42 UTC, nusbaume approved these changes
Thanks @fischer-ncar!  Everything looks good to me now.

@cacraigucar just a reminder to bring those changes into this PR before merging.  Thanks!

2023-09-21 15:21 UTC, cacraigucar commented
This PR is being abandoned due to answer changes updating the externals.  We do not want to combine code changes with changes to externals which are answer changing.  Some of the items are addressed by PR #888

2023-09-21 15:21 UTC, closed without merging