WACCMX-FV bug fix:convert wet species to dry before calling cam_thermo_dry_air_update
ESCOMP/CAM pull request #887
Opened 2023-09-20 16:58 UTC by jtruesdal

This PR corrects a bug introduced in cam6_3_109.  Physics requires constituents mixing ratio's to be dry but was using constituent thermodynamic properties based on the wet mixing ratio returned by dynamics.  To fix this bug, the routine called to convert mixing ratios from wet to dry was moved further up in d_p_coupling so that it happens before the thermodynamic properties are calculated for physics.

closes issue #885

2023-09-22 20:17 UTC, PeterHjortLauritzen commented
Fixed https://github.com/ESCOMP/CAM/issues/690

2023-09-25 22:54 UTC, cacraigucar requested changes

2023-09-25 22:54 UTC, cacraigucar commented on src/dynamics/fv/dp_coupling.F90
> +       call set_wet_to_dry(phys_state(lchnk))    ! Dynamics had moist, physics wants dry. xxx
What are `xxx` in these comments for?  Do they need to be removed?

2023-09-26 17:22 UTC, PeterHjortLauritzen commented on src/dynamics/fv/dp_coupling.F90
> +       call set_wet_to_dry(phys_state(lchnk))    ! Dynamics had moist, physics wants dry. xxx
yes. Done

2023-09-26 17:25 UTC, cacraigucar commented
@jtruesdal FYI - to get the automated closing to happen, you'll need to remove the word "issue" between "closes" and the issue #

2023-09-26 17:26 UTC, cacraigucar approved these changes

2023-09-28 06:42 UTC, jtruesdal commented
Thanks.  Removed Issue.

2023-10-03 02:32 UTC, nusbaume approved these changes
Looks good!  Just found one very minor typo.

2023-10-03 02:32 UTC, nusbaume commented on src/dynamics/fv/dp_coupling.F90
> +       ! (note: cam_thermo_dry_air_update assumes dry unless optianal conversion factor provided)
Typo here (`optianal` -> `optional`).

2023-10-06 17:57 UTC, jtruesdal commented on src/dynamics/fv/dp_coupling.F90
> +       ! (note: cam_thermo_dry_air_update assumes dry unless optianal conversion factor provided)
Corrected.

2023-10-06 18:18 UTC, merged