ZM clean up in preparation for using via CCPP and remove zmconv_microp feature
ESCOMP/CAM pull request #890
Opened 2023-09-29 23:00 UTC by cacraigucar

This PR is the first step in the CCPP conversion process.  It has the ZM module separated into its key components and all of the CAM "use" statements lower down have been removed and variables are passed in the calling lists.

zmconv_microp and the zm_microphysics are being removed with this PR as well.  It was deemed that this implementation is not the correct way to embed the microphysics in ZM.

2023-11-14 20:49 UTC, nusbaume approved these changes
Looks fine to me!  I have some minor concerns that will need to be addressed eventually before conversion is complete, but nothing  that should hold up this PR (especially if it is needed for science work).

2023-11-14 20:49 UTC, nusbaume commented on bld/configure
> +$cfg_cppdefs .= " -DOLD_CAM";
Is this used anymore?  If not then I might remove it.

2023-11-20 19:16 UTC, mwaxmonsky approved these changes
Looks great!  Had a few questions discussed during our weekly SIMA meeting so no need for any changes that I can see.

Thanks for tackling this one @cacraigucar!

2024-01-12 18:31 UTC, nusbaume requested changes
Have some minor cleanup and a question about the `lengath` variable, but once those are resolved then this PR should be ready to go!

2024-01-12 18:31 UTC, nusbaume commented on src/physics/cam/zm_conv_intr.F90
> +!CACNOTE - Is zm_org really a constituent or was it just a handy structure to use for an allocatable which persists in the run?
Question for @swrneale

2024-01-12 18:31 UTC, nusbaume commented on src/physics/cam/zm_conv_intr.F90
> +   real(r8),allocatable :: orgt_alloc(:,:), org_alloc(:,:)
I don't think these two variables are needed, as they don't appear to be used anywhere (besides the allocation step below).

2024-01-12 18:31 UTC, nusbaume commented on src/physics/cam/zm_conv_intr.F90
> +   real(r8) :: orgt_noalloc(state%ncol,pver), org_noalloc(state%ncol,pver)
I might rename these variable to something like `zm_org2d_ncol` and `orgt_ncol`, because if you removed the unused `alloc` variables above then the `noalloc` statements won't really make much sense.

2024-01-12 18:31 UTC, nusbaume commented on src/physics/cam/zm_conv_intr.F90
> +                  jt(:ncol), maxg(:ncol), ideep(:ncol), 1, lengath,  &
I am probably being paranoid, but there should be a check sometime before this call to check if `lengath` is bigger than `ncol`, and if so then just use `ncol` here for `lengath`?  Otherwise it seems at least theoretically possible for `lengath` to cause an array out-of-bounds error inside the CCPP-ized code.

2024-01-12 18:31 UTC, nusbaume commented on src/physics/spcam/crmclouds_camaerosols.F90
> +                  jt(:ncol),maxg(:ncol),ideep(:ncol), 1, lengath,  &
Same note here about ensuring that `lengath` is not bigger than `ncol`.

2024-01-12 18:36 UTC, swrneale commented on src/physics/cam/zm_conv_intr.F90
> +   real(r8),allocatable :: orgt_alloc(:,:), org_alloc(:,:)
They are not currently needed, but it is part of my ancient yet grand plan to include convective organization. I have a dusty issue on this #190 . Feel free to remove 'org' related infrastructure, I can just refer back to an old tag to remind myself of the implementation if need be.

2024-01-19 22:04 UTC, mwaxmonsky approved these changes
Looks great @cacraigucar!

2024-01-19 22:20 UTC, cacraigucar commented on src/physics/cam/zm_conv_intr.F90
> +   real(r8) :: orgt_noalloc(state%ncol,pver), org_noalloc(state%ncol,pver)
renamed

2024-01-19 22:20 UTC, cacraigucar commented on src/physics/cam/zm_conv_intr.F90
> +   real(r8),allocatable :: orgt_alloc(:,:), org_alloc(:,:)
Good catch.  I had several different flavors of variables while I was trying to get this all to work.  I neglected to delete these two.  Since @swrneale is going to be working on implementing this, I will leave the 'org' things here.

2024-01-20 01:00 UTC, nusbaume approved these changes
Looks great now, thanks @cacraigucar!

2024-01-23 23:57 UTC, merged