Update atmospheric_physics external
ESCOMP/CAM pull request #891
Opened 2023-10-03 16:01 UTC by nusbaume

This PR updates the atmospheric_physics external in CAM, which requires some source modifications on the CAM-side.  There has also been some replacement of CAM code with CCPP physics routines in order to reduce duplication.

Finally, this PR also fixes a bug found in Kessler where it was using the wrong pressure when converting to/from potential temperature via the exner function.

Fixes #752 
Fixes #802

2023-10-04 21:15 UTC, cacraigucar requested changes

2023-10-04 21:15 UTC, cacraigucar commented on src/physics/cam/geopotential.F90
> +          tvfac   = 1._r8 + zvir(i,k) * q(i,k,ixq)
Good catch- we tried to stamp all of these hardwired 1 a number of years ago, but obviously we didn't find them all.

2023-10-04 21:15 UTC, cacraigucar commented on src/physics/cam/geopotential.F90
> +      !end if
I'm not crazy about this "uncomment this section'.  Isn't there something which we could key off of to make the appropriate selection.  I know this isn't new, but the comment is and it made me see it :-)

2023-10-04 21:50 UTC, cacraigucar requested changes

2023-10-04 21:50 UTC, cacraigucar commented on src/dynamics/se/dp_coupling.F90
> +                                        errflg, errmsg)
As I'm resolving my comments in the NCAR/atmospheric_physics PR, I see that you did adopt the horiziontal_loop_extent dimension as it should be in CAM-SIMA.  I believe that this then will have a mismatch for this side.  I'm not sure if the dycore does the same allocations for the state variables as physics, where the variables are dimensioned by pcols.  If so, then the phys_state and cpairv variables need to be subsetted in the call, for instance `phys_state(lchnk)%t(1:ncol,:)`

2023-10-06 16:26 UTC, nusbaume commented on src/utils/ccpp_constituent_prop_mod.F90
> +! This module is a placeholder for the CCPP generated module of the same name
Fair point!  All `stub` comments updated accordingly.

2023-10-06 16:28 UTC, nusbaume commented on src/utils/ccpp_constituent_prop_mod.F90
> +      procedure :: standard_name     => ccpt_get_standard_name
In the actual CCPP-framework there is a `ccp` type and a `ccpt` type which points to the `ccp` object, but which has methods that are essentially the same. I am guessing I just copied the `ccpt` routines over instead of the `ccp` routines.  I've gone ahead and removed all of the extra "t"s.  

I am not 100% sure if we need to formalize a naming convention yet, simply because a lot of this is actually "hidden" from the physics routines themselves.  As long as the final public method name matches the framework then everything should work as expected.

2023-10-06 16:29 UTC, nusbaume commented on src/utils/ccpp_constituent_prop_mod.F90
> +module ccpp_constituent_prop_mod
Good idea!  Created a new `src/utils/cam_ccpp` directory to help better organize the source code.

2023-10-06 16:29 UTC, nusbaume commented on src/physics/cam/geopotential.F90
> +      ! Note, zi(i,k) is the interface above zm(i,k)
Agreed, moved the comment down to just above the `do k = pver, 1, -1` line.

2023-10-06 16:29 UTC, nusbaume commented on src/physics/cam/geopotential.F90
> +          tvfac   = 1._r8 + zvir(i,k) * q(i,k,ixq)
Thanks!  Every once in a while I get lucky and improve the code.

2023-10-06 16:30 UTC, nusbaume commented on src/physics/cam/geopotential.F90
> +      !end if
After looking at the code I realized I can just uncomment it as-is and it should work properly.  It does mean that there will be a useless dycore check done every time this subroutine is called, but I doubt it will be a big performance hit.

2023-10-06 22:06 UTC, cacraigucar requested changes

2023-10-06 22:06 UTC, cacraigucar commented on src/physics/cam/geopotential.F90
> +use ccpp_constituent_prop_mod, only: ccpp_const_props      !CCPP constituent properties array (stub version)
Still says `stub`

2023-10-06 22:06 UTC, cacraigucar commented on src/physics/cam/physpkg.F90
> +    ! Initialize stub CCPP constituent properties array
Still says `stub`

2023-10-06 22:06 UTC, cacraigucar commented on src/physics/cam_dev/physpkg.F90
> +    ! Initialize stub CCPP constituent properties array
Still says `stub`

2023-10-13 17:53 UTC, nusbaume commented on Externals_CAM.cfg
> +branch = updated_standard_names
This has now been updated to point to an official tag.

2023-10-13 17:54 UTC, nusbaume commented on src/physics/simple/held_suarez_cam.F90
> +    call held_suarez_1994_run(pver, ncol, pref_mid_norm, clat, cappav(:,:,lchnk), cpairv(:,:,lchnk), &
Good catch! `ncol` has now been added to all array arguments.

2023-10-13 17:54 UTC, nusbaume commented on src/physics/cam/geopotential.F90
> +use ccpp_constituent_prop_mod, only: ccpp_const_props      !CCPP constituent properties array (stub version)
Replaced with `CAM version`.

2023-10-13 17:54 UTC, nusbaume commented on src/physics/cam/physpkg.F90
> +    ! Initialize stub CCPP constituent properties array
Replaced with `CAM`.

2023-10-13 17:54 UTC, nusbaume commented on src/physics/cam_dev/physpkg.F90
> +    ! Initialize stub CCPP constituent properties array
Replaced with `CAM`.

2023-10-13 18:54 UTC, cacraigucar requested changes
We had some committed code which had the 1:ncol error as well as more places you added code.  This should be all of them in this PR.  

Basically the rule of thumb is that any run methods which have arrays dimensioned by pcols in CAM, need to have that subsetted by 1:ncol in the call.   (BTW, my ZM conversion doesn't have pcols removed from the lower layer yet - that will come with the metadata creation step - I went and checked!)

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call calc_exner_run(ncol, pver, cpairv(:,:,lchnk), rairv(:,:,lchnk), psurf_ref, state%pmid, pk, errmsg, errflg)
These need to be subset by 1:ncol as well.  I'll look at adding something to the conversion document.

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call temp_to_potential_temp_run(ncol, pver, temp, pk, th, errmsg, errflg)
Add 1:ncol to this call as well

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call calc_dry_air_ideal_gas_density_run(ncol, pver, rairv(:,:,lchnk), state%pmiddry, temp, rho, errmsg, errflg)
Add 1:ncol here as well

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call wet_to_dry_water_vapor_run(ncol, pver, state%pdel, state%pdeldry, qv, qv_dry, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call wet_to_dry_cloud_liquid_water_run(ncol, pver, state%pdel, state%pdeldry, qc, qc_dry, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call wet_to_dry_rain_run(ncol, pver, state%pdel, state%pdeldry, qr, qr_dry, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +                     qr_dry, prec_sed, relhum, scheme_name, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call potential_temp_to_temp_run(ncol, pver, th, pk, temp, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call dry_to_wet_water_vapor_run(ncol, pver, state%pdel, state%pdeldry, qv_dry, qv, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call dry_to_wet_cloud_liquid_water_run(ncol, pver, state%pdel, state%pdeldry, qc_dry, qc, errmsg, errflg)
Add 1:ncol here

2023-10-13 18:54 UTC, cacraigucar commented on src/physics/simple/kessler_cam.F90
> +    call dry_to_wet_rain_run(ncol, pver, state%pdel, state%pdeldry, qr_dry, qr, errmsg, errflg)
Add 1:ncol here

2023-10-16 16:09 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call temp_to_potential_temp_run(ncol, pver, temp, pk, th, errmsg, errflg)
Done.

2023-10-16 16:09 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call calc_dry_air_ideal_gas_density_run(ncol, pver, rairv(:,:,lchnk), state%pmiddry, temp, rho, errmsg, errflg)
Done.

2023-10-16 16:09 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call wet_to_dry_water_vapor_run(ncol, pver, state%pdel, state%pdeldry, qv, qv_dry, errmsg, errflg)
Done.

2023-10-16 16:09 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call wet_to_dry_rain_run(ncol, pver, state%pdel, state%pdeldry, qr, qr_dry, errmsg, errflg)
Done.

2023-10-16 16:10 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +                     qr_dry, prec_sed, relhum, scheme_name, errmsg, errflg)
Done.

2023-10-16 16:10 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call potential_temp_to_temp_run(ncol, pver, th, pk, temp, errmsg, errflg)
Done.

2023-10-16 16:10 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call dry_to_wet_water_vapor_run(ncol, pver, state%pdel, state%pdeldry, qv_dry, qv, errmsg, errflg)
Done.

2023-10-16 16:10 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call dry_to_wet_cloud_liquid_water_run(ncol, pver, state%pdel, state%pdeldry, qc_dry, qc, errmsg, errflg)
Done.

2023-10-16 16:10 UTC, nusbaume commented on src/physics/simple/kessler_cam.F90
> +    call dry_to_wet_rain_run(ncol, pver, state%pdel, state%pdeldry, qr_dry, qr, errmsg, errflg)
Done.

2023-10-18 18:01 UTC, cacraigucar approved these changes

2023-10-26 16:29 UTC, peverwhee approved these changes
A couple of non-critical questions/comments about the constituent_prop_mod stub.

2023-10-26 16:29 UTC, peverwhee commented on src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90
> +      end if
I get why this error message exists for ccp_get_standard_name, but why these other subroutines?

2023-10-26 16:29 UTC, peverwhee commented on src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90
> +   end subroutine ccp_get_standard_name
Why do we need this at all?

2023-10-26 17:36 UTC, nusbaume commented
@jtruesdal just pinging you about reviewing this PR when you get the chance!

2023-10-26 19:55 UTC, jtruesdal approved these changes
Thanks for the ping.  Looks good.

2023-10-27 15:36 UTC, nusbaume commented on src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90
> +      end if
Good point!  I've changed the error messages to just be empty strings in order to avoid confusion (and to hint that CAM doesn't actually use these specific error messages).  If however you think I should actually be generating and using an error message variable here and in CAM then please let me know.

2023-10-27 15:38 UTC, nusbaume commented on src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90
> +   end subroutine ccp_get_standard_name
Because in CAM we are building (but not running) the CCPP-ized version of `qneg`, which uses the `standard_name` constituent property, which in-turn is pointing to this subroutine (in the same way that the real CCPP constituents object points to a subroutine).  

So without a subroutine like this the CAM build will fail.  I could simplify it further, but I also imagine in the future we'll have physics schemes which will really need to use this subroutine, or something like it, which is why I kept it in there.

Hopefully that makes sense?  If you still think it would be a good idea to simplify it even further then just let me know.

2023-10-31 16:48 UTC, merged