Separate history tapes into hXi and hXa
ESCOMP/CAM pull request #903
Opened 2023-10-13 00:43 UTC by peverwhee

Per https://github.com/ESCOMP/CAM/issues/159 - this PR changes the "time" variable in a history file with averaged (and/or min/max/stdev quantities) to be the midpoint of the averaging period (basically, the average of the time_bounds variable).

Side affects of the above/related changes in this PR (all implemented):
* Each history tape _can_ now result in TWO files - hXa and hXi (if only one file is necessary, it will still carry the "i" or "a" flag for clarity)
* Changed 'time_bnds' variable name to 'time_bounds'
* Ensured the 'cell_methods' metadata field always includes "time: XXXXX" (where XXXXX refers to the avgflag) for history fields so that it's always clear what operation is being done on/for that field
* Any user-specified history file name or template will also have "a" or "i" appended to it and may result in two files

Testing
* All regression tests run successfully (except for known failures)
* Currently working on writing a script to compare the resultant ncdata file(s) vs baselines

Related to: https://github.com/ESCOMP/CTSM/pull/2019

closes https://github.com/ESCOMP/CAM/issues/159

Supersedes #869

2023-10-17 22:33 UTC, cacraigucar reviewed
Asking a basic question to aid my understanding during the review process

2023-10-17 22:33 UTC, cacraigucar commented on src/control/cam_history.F90
> +  integer, parameter :: restartdimcnt              = 11
Why did this get bumped up to 11?

2023-10-18 00:36 UTC, peverwhee commented on src/control/cam_history.F90
> +  integer, parameter :: restartdimcnt              = 11
I had to add a new restart dimension for the variables that hold the names of the history files (nhfil and cpath). The new dimension is defined on ~line 1424 and is set to the parameter maxsplitfiles(=2) from cam_grid_support.

nhfil and cpath used to just be have one dimension which was the # of tapes, but now there's a second dimension for the two potential split files.

2023-10-18 22:45 UTC, cacraigucar requested changes
My brain is officially fried and I'm just doing the review!!  I am impressed with the changes you've made!  

First batch of review comments - more may be coming tomorrow

2023-10-18 22:45 UTC, cacraigucar commented on src/control/cam_history.F90
> +            end if
This is a little fragile - assuming that the first file is accumulated and the second is instantaneous.  With this current implementation, that is the case, but if someone flipped them down at line 5650, then it would no longer work.  Since this history is nearing end-of-life and the likelihood of it getting broken is low, I won't require this be fixed, but if it is easy to determine which is which, I'd suggest that be used instead.

2023-10-18 22:45 UTC, cacraigucar commented on src/control/cam_history.F90
> +    get_hfilepath = cpath( tape, 1 )
I was questioning if this should be for both files or just the first.   When I searched through the code tree, I do not see it being used at all.  I will still ask the question though

2023-10-18 22:45 UTC, cacraigucar commented on src/control/cam_history.F90
> +            end if
If there is an easy way to determine which file is accumulated instead of just relying on it being the first, I would add that here as well.

2023-10-18 22:45 UTC, cacraigucar commented on src/control/cam_history.F90
> +           end if
Previously this was not being set for instantaneous fields.  Does this matter?

2023-10-19 06:44 UTC, gold2718 commented on src/control/cam_history.F90
> +          end do
I have not looked much into this but I'm pretty sure there used to be a restart history file for any history file that had non-Instantaneous (last value) fields. Has that changed with this PR?

2023-10-19 06:52 UTC, gold2718 commented on src/control/cam_history.F90
> +            end if
Maybe assign a parameter to the instantaneous file?

2023-10-19 15:43 UTC, cacraigucar requested changes

2023-10-19 15:43 UTC, cacraigucar commented on src/control/cam_history.F90
>  !                 mdimsize, PIO_DOUBLE, fdecomp)
This  commented out section is wrong with hlist(f).  I suggest you either delete the section or fix the index

2023-10-19 15:43 UTC, cacraigucar commented on src/control/cam_history.F90
> +        end if
There are still some functions which use "f".  I did a `grep hlist\(f\)` to find them.  I would suggest it might be good to be fully consistent throughout this routine.

2023-10-19 16:20 UTC, peverwhee commented on src/control/cam_history.F90
> +        end if
yep - good call. I missed the ones outside of a loop context. fixed.

2023-10-19 16:20 UTC, peverwhee commented on src/control/cam_history.F90
> +      end do
loop removed.

2023-10-19 16:21 UTC, peverwhee commented on src/control/cam_history.F90
> +      end do
loop removed

2023-10-19 16:25 UTC, peverwhee commented on src/control/cam_history.F90
> +           end if
before the decision to split the files, this discussion here: https://github.com/ESCOMP/CTSM/pull/2019#issuecomment-1660639903

was about how to tell what type of file it is. For consistency with what CLM has, I added the instantaneous cell_value string. But I also see how this isn't super necessary anymore because the filename has the specifier in it already...

2023-10-19 16:28 UTC, cacraigucar commented on src/control/cam_history.F90
> +           end if
I'll leave it up to the developer on what is best - I was just asking the question...

2023-10-19 16:29 UTC, peverwhee commented on src/control/cam_history.F90
> +            end if
I agree @cacraigucar that this is fragile. Good point.

@gold2718 what do you mean by "assign a parameter to the instantaneous file"?

My initial thought is to add "accumulate_file_index" and "instantaneous_file_index" parameters and use those instead of "1" and "2" throughout the code. But I'm open to other options (I just don't yet understand yours...)

2023-10-19 16:37 UTC, peverwhee commented on src/control/cam_history.F90
> +        if(pio_file_is_open(tape(t)%Files(1))) then
This shouldn't need to loop over files. The split history files don't have separate field lists, so a second loop through here wouldn't do anything (all the field varids will have already been deallocated).

2023-10-19 16:51 UTC, gold2718 commented on src/control/cam_history.F90
> +            end if
That is exactly what I was talking about, just using real language :)
I think those parameter names are fine except that I still don't really like 'instantaneous' because that does not describe which instant (I like last value because you get the last sample you happened to talk before writing the file).

2023-10-19 17:18 UTC, cacraigucar commented on src/control/cam_history.F90
> +            end if
I would encourage you to keep "instantaneous" as this is what the ultimate file is called.  If we were to change to "last value", we'd need to overhaul everything (including changing the "I" designator) and coordinate with CTSM.  I believe "I" is what we are currently stuck with.

2023-10-19 17:51 UTC, peverwhee commented on src/control/cam_history.F90
> +            end if
@cacraigucar agreed. Parameters added.

2023-10-19 17:52 UTC, peverwhee commented on src/control/cam_history.F90
> +    get_hfilepath = cpath( tape, 1 )
Since it's not used, I also pretty much ignored it. But, for the sake of cleanliness, I amended the routine to take in a flag and either output the accumulated or instantaneous filepath

2023-10-19 17:53 UTC, peverwhee commented on src/control/cam_history.F90
> +            end if
parameter added for the indices - check is now against accumulated_file_index

2023-10-19 17:53 UTC, peverwhee commented on src/control/cam_history.F90
>  !                 mdimsize, PIO_DOUBLE, fdecomp)
fixed the index.

2023-10-19 18:06 UTC, peverwhee commented on src/control/cam_history.F90
> +          end do
Still mulling over this. I _think_ it needs to be a loop. This is after we read the single restart history file (which we closed on line 2339) and when we're setting up the other history files.

2023-10-19 18:13 UTC, cacraigucar commented on src/control/cam_history.F90
> +          end do
It doesn't hurt to keep it as a loop

2023-10-19 18:33 UTC, peverwhee commented on src/control/cam_history.F90
> +            end if
i would lean toward overkill, but am willing to be overruled.

2023-10-19 18:34 UTC, cacraigucar requested changes
Whew - I finished my review and I've resolved the conversations which are fixed.  Again, good job on these changes!

2023-10-19 18:34 UTC, cacraigucar commented on src/control/cam_history.F90
> +                if (hfile_accum(t) .and. .not. restart) then
Could you ever get here with a restart file (i.e. why are you checking restart) since you've already determined that there is more than one file?  If it is important to check for a restart file, then you probably need to do so on the else section as well.

2023-10-19 18:34 UTC, cacraigucar commented on src/control/cam_history.F90
>            else
Since this is a restart, I believe the loop is unnecessary

2023-10-19 18:36 UTC, cacraigucar commented on src/control/cam_history.F90
> +            end if
Since I suggested overkill as well, I'd say go for it!

2023-10-19 19:27 UTC, peverwhee commented on src/control/cam_history.F90
> +                if (hfile_accum(t) .and. .not. restart) then
this else is for when there is only one file. I think it's right to not check for restart in the else section since we want the non-averaged time variable on restart files

2023-10-19 19:28 UTC, peverwhee commented on src/control/cam_history.F90
>            else
removed.

2023-10-19 19:33 UTC, cacraigucar commented on src/control/cam_history.F90
> +                if (hfile_accum(t) .and. .not. restart) then
Oops - the highlighting didn't work too well.  It is the else loop right above this one (the one for the instantaneous tape)

2023-10-19 19:38 UTC, cacraigucar commented on src/control/cam_history.F90
> +                if (hfile_accum(t) .and. .not. restart) then
I see you removed the restart check that I was worried about, so all good now

2023-10-20 20:13 UTC, cacraigucar requested changes
Thanks for adding those new parameters.  It helped me find some areas which I believe are bugs.

2023-10-20 20:13 UTC, cacraigucar commented on src/control/cam_history.F90
> +           end if
Is this section where the aaccumulated_file_index and instantaneous_file_index need to be set (and not as a parameter above?  As it is right now, the instananeous is assigned to 2, but should be 1 if there is only one file.   I believe the "Files(1)" on the two lines here also need to have the variables used instead of "1"

2023-10-20 20:13 UTC, cacraigucar commented on src/control/cam_history.F90
> +      end if
I think these "Files(1)" should also use the varaibles (after they are assigned in the previous comment.

2023-10-20 20:13 UTC, cacraigucar commented on src/control/cam_history.F90
> +               call cam_PIO_openfile (tape(t)%Files(1), nhfil(t,instantaneous_file_index), PIO_WRITE)
I think these "Files(1)" should also use the varaibles (after they are assigned in the previous comment.

2023-10-20 23:27 UTC, peverwhee commented on src/control/cam_history.F90
> +           end if
Yeah, the indexing here was technically correct (since the index parameters are set before we know how many files we have), but very confusing. As a result, I've changed the looping over num_files to instead be over the size of Files and then checking whether or not each file is open before operating on it. For example, if you only have an instantaneous file, you'd only be doing things during the second iteration of the loop because instantaneous_file_index = 2

TLDR: these indexes are now set to the parameters.

2023-10-20 23:27 UTC, peverwhee commented on src/control/cam_history.F90
> +      end if
same here.

2023-10-20 23:27 UTC, peverwhee commented on src/control/cam_history.F90
> +               call cam_PIO_openfile (tape(t)%Files(1), nhfil(t,instantaneous_file_index), PIO_WRITE)
and also here.

2023-10-26 03:38 UTC, nusbaume requested changes
Great work @peverwhee!  I mostly just have some minor clean-up suggestions.

2023-10-26 03:38 UTC, nusbaume commented on src/control/cam_history.F90
>  !                 mdimsize, PIO_DOUBLE, fdecomp)
I know you didn't write this, but it seems like we should be doing nothing here, which means I might vote to remove the commented out code.

2023-10-26 03:38 UTC, nusbaume commented on src/control/cam_history.F90
> +          do f = 1, t
Should we only be looping to `t` here, or should we be looping through all of the tapes (`ptapes`), which is what it looks like it was doing in the original version?

2023-10-26 03:38 UTC, nusbaume commented on src/control/cam_history.F90
> +                 call endrun
I would add some sort of error message to this `endrun` call (even it just says to look at the atm log file).

2023-10-26 03:38 UTC, nusbaume commented on src/control/cam_history.F90
> +            end if
I don't think you need the `.and.` option here:

```suggestion
            if (hfile_accum(t)) then
               call cam_PIO_openfile (tape(t)%Files(accumulated_file_index), nhfil(t,accumulated_file_index), PIO_WRITE)
            end if
            if (hfile_inst(t)) then
               call cam_PIO_openfile (tape(t)%Files(instantaneous_file_index), nhfil(t,instantaneous_file_index), PIO_WRITE)
            end if
```

2023-11-01 15:23 UTC, brian-eaton commented on src/control/cam_history.F90
> +            end if
@gold2718, I'm not understanding your dislike of referring to a file as "instantaneous".  That file contains instantaneous time samples, i.e., the values of the state variables at the end of discrete time steps.  The suggestion of "last value" is an implementation detail related to the use of history buffers which doesn't clearly describe the file contents.  What am I missing?

2023-11-01 16:32 UTC, gold2718 commented on src/control/cam_history.F90
> +            end if
The issue in (possibly only) my mind is that there are a (potentially large) number of "instantaneous" samples that are capture by `outfld` calls. However, none of these are written to a history file, only the last captured sample is written out. Perhaps "last_sample" is more accurate. This is not a huge deal but is something that has always bothered me since I have run into folks who didn't understand that it works like that (capturing then overwriting all the samples except the last one before a write).

2023-11-01 20:38 UTC, brian-eaton commented on src/control/cam_history.F90
> +            end if
@gold2718, I think what we're trying to convey in the filename is something about the temporal characteristics of the data.  Focusing on the implementation of collecting the time samples (e.g., by overwritting the history buffer each time a sample is collected until it's time to write the buffer) ignores that other implementations are possible, like not putting anything in the buffer until the desired timestep is reached.  The sample collection implementation doesn't describe the temporal characteristics of the data.  Instantaneous does.

2023-11-01 21:06 UTC, gold2718 commented on src/control/cam_history.F90
> +            end if
In the new instantaneous files, does the time variable always match the time step of the sample?

2023-11-01 21:59 UTC, brian-eaton commented on src/control/cam_history.F90
> +            end if
Yes.

It has always been the case that the time coordinate matches the end of the time step producing the data for an instantaneous field.  From the code I've looked at so far the time coordinate in the hXi file is the same as it's always been for instantaneous fields.  I am running tests as I review this PR to check these details.

2023-11-01 22:35 UTC, peverwhee commented on src/utils/cam_grid_support.F90
> +    type(vardesc_ptr_t)       :: vardesc(2)        ! If we are to write coord
an excellent point. changed.

2023-11-01 22:36 UTC, peverwhee commented on src/control/cam_history.F90
> +           hfilename_spec(t) = temp_spec
I had convinced myself that I needed it when I got an apparently-unrelated error. You're right. Temp variable removed.

2023-11-01 22:37 UTC, peverwhee commented on src/control/cam_history.F90
>      return
removed

2023-11-01 22:38 UTC, peverwhee commented on src/control/cam_history.F90
> +
good call! spaces removed

2023-11-01 22:38 UTC, peverwhee commented on src/control/cam_history.F90
> +           end if
indeed! simiplified

2023-11-01 22:39 UTC, peverwhee commented on src/control/cam_history.F90
> +            do f = 1, size(tape(t)%Files)
I had waffled on that. I used the size in case some person someday decided to set it to some random variable/integer. But that would cause other problems anyway, so i've switched all the size(tape(t)%Files) to maxsplitfiles

2023-11-01 22:39 UTC, peverwhee commented on src/control/cam_history.F90
> +      end if
simplified

2023-11-01 22:39 UTC, peverwhee commented on src/control/cam_history.F90
> +!            '$Id$')
yep. removed

2023-11-01 22:39 UTC, peverwhee commented on src/control/cam_history.F90
> +             ! solar / geomagetic activity indices...
typo fixed

2023-11-01 22:40 UTC, peverwhee commented on src/control/cam_history.F90
> +           end if
simplified

2023-11-01 22:40 UTC, peverwhee commented on src/control/cam_history.F90
> +       ret = pio_enddef(tape(t)%Files(f))
added ret check and endrun call.

2023-11-01 22:40 UTC, peverwhee commented on src/control/cam_history.F90
> +    integer,     intent(in)    :: f
comments added

2023-11-01 22:40 UTC, peverwhee commented on src/control/cam_history.F90
>  !                 mdimsize, PIO_DOUBLE, fdecomp)
removed and logic amended

2023-11-01 22:42 UTC, peverwhee commented on src/control/cam_history.F90
> +          do f = 1, t
I changed it to t since this is a loop nested within a loop over ptapes, but now I'm questioning how that will work with threading, so i've changed it back to ptapes

2023-11-01 22:42 UTC, peverwhee commented on src/control/cam_history.F90
> +                 call endrun
message added

2023-11-01 22:42 UTC, peverwhee commented on src/control/cam_history.F90
> +            end if
simplified

2023-11-01 22:50 UTC, brian-eaton commented on src/control/cam_history.F90
> +    get_hfilepath = cpath( tape, 1 )
Another option (which gets my vote) is to remove dead code.  This function isn't referenced anywhere.  Same comment for `get_hist_restart_filepath` and `get_ptapes`.

2023-11-01 22:54 UTC, gold2718 commented on src/control/cam_history.F90
> +            end if
I do not think you answered my question. You are saying that the time that shows up in the file is the same as the time step active when the write occurs. I'm asking if the time that shows up in the file matches the time step that was active when the `outfld` buffer was captured for each and every field in the file. For instance, what if a particular diagnostic is only called every other time step and the write step is one where it was not captured.

2023-11-01 22:58 UTC, gold2718 commented on src/control/cam_history.F90
> +          do f = 1, t
I seriously doubt `wshist` (if I got the right subroutine) can ever be threaded.

2023-11-01 23:26 UTC, brian-eaton commented on src/control/cam_history.F90
> +           end if
I'll jump in to add that the reason `cell_methods` wasn't used for instantaneous data is that instantaneous is the default value.  To be consistent with the CF Metadata Conventions this should be added as `time: point`, not `time: instantaneous`.  CF uses `point` to indicate both time and space points.  I think it would be better to leave it out than to use a non-conforming value.

2023-11-02 08:00 UTC, gold2718 commented on src/control/cam_history.F90
> +           end if
I think `point` is a great term to use to replace `instantaneous`. Closer to the truth and CF compliant!

2023-11-02 14:50 UTC, brian-eaton commented on src/control/cam_history.F90
> +            end if
Take 2.  Yes, the time variable always matches the time step of an instantaneous sample assuming that outfld was called during that time step.

You are correct to point out that outfld isn't called every time step for all fields that are output.  Radiation fields are a prime example. To analyze fields like that one needs to look at the details of when the outfield calls are made, and at what happens during the time step(s) when outfld is not called.  In the case of radiation, the heating rates that are applied during time steps when radiation isn't run (and outfld calls are not made) are from the most recent calculation (they are saved in the physics buffer).  So even though the outfld call for the instantaneous field was not made at the time indicated by the time coordinate, the field is in fact valid at that time.  I'm not claiming this to be the case for all fields that fall into this category.  But I do claim that all fields in this category are instantaneous, even if there is a mismatch in the associated time coordinate.

2023-11-02 15:22 UTC, nusbaume commented on src/control/cam_history.F90
> +           end if
I am also happy if we use `time: point` as the metadata attribute to label the quantity as different from the accumulated files.  I just want _something_ there, because the actual file names are easily changed, and part of the reason we are doing this entire exercise is because the post-processing folks basically didn't like our metadata (so I don't want to give them more ammunition).

2023-11-02 20:00 UTC, nusbaume commented on src/control/cam_history.F90
> +          do f = 1, t
Ahh, I think I understand now!  I am fine then with either `ptapes` or `t` (and your original `t` method is very likely more performant, at least for the average CAM configuration).

2023-11-02 20:01 UTC, nusbaume approved these changes
Thanks for dealing with my concerns!  I am happy with this PR now.

2023-11-07 18:39 UTC, brian-eaton commented on src/control/cam_history.F90
> +             end if
When the output frequency is specified to be every time step, i.e., `nhtfrq==1`, this is instantaneous output.  But if instantaneous output has not been explicitly requested (for most variables the default output is averaged) then it should be recognized that this is a special case of instantaneous data and the metadata should be adjusted accordingly.  This code is instead outputting the time coordinate as the average value of the beginning and end of the time step.  That's not correct.  The data produced during a single time step should have the time coordinate from the end of the time step, which is what happens when instantaneous output is explicitly specified.  Here is a suggested change to the conditional.  Note that the condition `.not. is_satfile(t)` is already satisfied, so can just replace that by `nhtfrq(t) /= 1`

`
 if (f == accumulated_file_index .and. .not. restart .and. .not. is_initfile(t) .and. nhtfrq(t) /= 1) then
`

2023-11-07 22:17 UTC, gold2718 commented on src/control/cam_history.F90
> +             end if
I think I missed something. For an `'I'` file, what difference do you expect in the NetCDF file for `nhtfrq == 1` and `nhtfrq /= 1`?

2023-11-07 23:42 UTC, brian-eaton commented on src/control/cam_history.F90
> +             end if
For an `'I'` file the time coordinate will always be at the end of the time step which is being written, regardless of `nhtfrq`.

The issue I'm addressing is when the averaging flag of a variable is not `'I'`.  Suppose `avgflag_pertape='A'` and suppose `nhtfrq=1`.  Then the output is instantaneous even though `avgflag='A'`.  The code I referenced is then setting the time coordinate to be at the midpoint of the time step being written which is not correct for instantaneous output.  The suggested modification is recognizing that `nhtfrq=1` is a special case of instantaneous output and setting the time coordinate accordingly.  Make sense?

2023-11-08 01:07 UTC, peverwhee commented on src/control/cam_history.F90
> +             end if
ooh this is a excellent catch! I guess I similarly need to update the logic for other spots where we're conditionally writing accumulated vs instantaneous data

2023-11-08 01:07 UTC, peverwhee commented on src/control/cam_history.F90
> +           end if
I am also happy with `time: point`

2023-11-08 08:35 UTC, gold2718 commented on src/control/cam_history.F90
> +             end if
Thanks; I understand although I think the time for this case should be set wherever the post-processing community wants it set (since, as you pointed out many many months ago, the time bounds are always the best way to know what is actually in the file).

I'm still not happy with the term, instantaneous, which is a concept from physics that is explicitly not measurable while CAM diagnostics files are all about what _is_ measurable. Of course, engineers abuse the term all the time so . . . :smirk:

2023-11-08 15:32 UTC, brian-eaton commented on src/control/cam_history.F90
> +             end if
The post-processing community has never asked that the time coordinate of an instantaneous time sample be placed at the midpoint of the time step that produced it.  Also note that for instantaneous samples the time bounds associated with the time coordinate are not relevant.  That's why our current history files are CF compliant even though they mix instantaneous and non-instantaneous output.

I would argue that the term instantaneous in this discussion is a mathematical concept, not a physical one.  We're solving a discretized system of equations and the solutions are valid at points in time.

2023-11-08 15:46 UTC, brian-eaton commented on src/control/cam_history.F90
> +              str = 'instantaneous'
Another place to deal with the special case of `nhtfrq==1`:
```suggestion
           if (tape(t)%hlist(fld)%avgflag == 'I' .or. nhtfrq(t) == 1) then
              str = 'point'
```

2023-11-08 15:51 UTC, brian-eaton commented on src/control/cam_history.F90
> +             end if
@peverwhee, In addition to the comment I just added for line 4827 of `cam_history.F90`, at line 2520 the `time_op` value should change from `' '` to `'point'`.  I couldn't figure out how to make this comment at that point in the code since there are no changes there.

2023-11-08 17:37 UTC, brian-eaton commented on src/control/cam_history.F90
> +           hfilename_spec(t) = trim(hfilename_spec(t)) // '%f'
This code doesn't recognize that the `.nc` file extension is part of the template.
```suggestion
           ! Append file type - instantaneous or accumulated - to filename
           ! specifier provided (in front of the .nc extension).
           tlen = len_trim(hfilename_spec(t))
           hfilename_spec(t) = hfilename_spec(t)(:tlen-3)  // '%f.nc'
```
and provide the declaration for `integer :: tlen`.

2023-11-08 18:35 UTC, gold2718 commented on src/control/cam_history.F90
> +             end if
> I would argue that the term instantaneous in this discussion is a mathematical concept, not a physical one. We're solving a discretized system of equations and the solutions are valid at points in time.

Oh no, math plus engineering vs. physics! That's like rock and paper ganging up on scissors :grimacing:
Good thing we are only doing math and not trying to describe physical reality :smirk:

2023-11-08 22:52 UTC, peverwhee commented on src/control/cam_history.F90
> +          do f = 1, t
changed back to t

2023-11-08 22:52 UTC, peverwhee commented on src/control/cam_history.F90
> +           end if
changed!

2023-11-08 22:56 UTC, peverwhee commented on src/control/cam_history.F90
> +             end if
logic updated to treat nhtfrq == 1 as instantaneous; time_op value changed to 'point'

2023-11-08 22:56 UTC, peverwhee commented on src/control/cam_history.F90
> +              str = 'instantaneous'
changed!

2023-11-08 22:57 UTC, peverwhee commented on src/control/cam_history.F90
> +           hfilename_spec(t) = trim(hfilename_spec(t)) // '%f'
good catch - code updated

2023-11-10 15:51 UTC, brian-eaton commented on src/control/cam_history.F90
> +             end if
I'm afraid commit 7a0e5282 is a regression.  My testing revealed that if the `h0` stream contains averaged and instantaneous fields (as declared in their `avgflag` values) and `nhtfrq==1`, only the `h0i` file is produced and it only contains the fields that have `avgflag='I'`.  The fields with `avgflag='A'` are not output, even though they should be output with instantaneous values.

The changes I suggested (and tested) didn't attempt to change the `avgflag` settings for the case `nhtfrq==1`.  They only make sure the file contains the metadata and time coordinates which are correct for instantaneous fields even though they appear in an `hXa` file due to their `avgflag` values.

If we want the `nhtfrq==1` case to have filenames consistent with our new convention for instantaneous data, I think the best approach is to modify the field `avgflag` setting to be `'I'`.  This would eliminate the need to add an `'.or. nhtfrq(t)==1'` condition in other code locations.  I suggest the following code be added at line 792 in `cam_history.F90`:
```
      ! If nhtfrq == 1, then the output is instantaneous.  Enforce this by setting
      ! the per-file averaging flag.

      do t = 1, ptapes
         if (nhtfrq(t) == 1) then
            avgflag_pertape(t) = 'I'
         end if
      end do
```

2023-11-10 17:24 UTC, brian-eaton commented on src/utils/cam_grid_support.F90
> +    logical                            :: attrs_defined(2) = .false.
Should this `2` be `maxsplitfiles`?  If not a parameter should be used that indicates what the array length should be.

2023-11-13 16:10 UTC, brian-eaton commented on src/control/cam_history.F90
>        ! The first empty slot in the current fincl array is index f from loop above.
`index f` should be `index fld`

2023-11-15 01:23 UTC, brian-eaton commented on src/control/cam_history.F90
> +                  trim(nhfil(t,instantaneous_file_index))
Add space between filenames
```suggestion
            write(iulog,*)'Opening netcdf history files ', trim(nhfil(t,accumulated_file_index)), &
                  '  ', trim(nhfil(t,instantaneous_file_index))
```

2023-11-29 20:34 UTC, peverwhee commented on src/control/cam_history.F90
> +             end if
Updated to enforce instantaneous output for nhtfrq = 1. Also added code at line ~486 to override any flags specified in fincl to 'I' when nhtfrq = 1

2023-11-29 20:35 UTC, peverwhee commented on src/control/cam_history.F90
> +                  trim(nhfil(t,instantaneous_file_index))
good call - added

2023-11-29 20:35 UTC, peverwhee commented on src/control/cam_history.F90
>        ! The first empty slot in the current fincl array is index f from loop above.
updated!

2023-12-01 23:47 UTC, cacraigucar approved these changes
I left my one conversation unresolved as I'm not sure if the side discussion was finished or not.  But my concern was addressed to my satisfaction

2023-12-07 00:20 UTC, brian-eaton approved these changes
Looks good.  Nice work!

2023-12-07 00:35 UTC, merged

2023-12-07 02:16 UTC, ekluzek commented
@peverwhee nice to see this in. We are going to study it in CTSM and figure out what we need to do using this as strong inspiration. Thanks so much.

2023-12-07 12:21 UTC, billsacks commented
Thank you very much for your work on this, @peverwhee ! It's exciting to see this completed!!!