Rename SE dycore time_mod to dyn_time_mod
ESCOMP/CAM pull request #904
Opened 2023-10-16 16:39 UTC by jimmielin

This commit renames time_mod in the SE dycore to dyn_time_mod in order to avoid naming conflicts with building with GEOS-Chem.

All USE statements updated; zero differences in run output are expected.

This is being submitted as a separate PR than #484 as it is a zero-diff update of file names and might need discussion that is separate from the GEOS-Chem changes to CAM code.

On the GEOS-Chem side we intend to rename our utilities in the GEOS-Chem code with a prefix to avoid future instances of naming conflicts as well. This will be discussed by the GEOS-Chem support team. Copying @lizziel.

Thanks!

2023-10-18 21:01 UTC, nusbaume requested changes
Thanks for implementing these changes!  I was just wondering if you could make the new module name a little more specific to avoid this same issue possibly happening again in the future.

2023-10-18 23:37 UTC, jimmielin commented on src/dynamics/se/dycore/dyn_time_mod.F90
> +module dyn_time_mod
Thanks for the suggestion! Now renamed to `se_dyn_time_mod`.

2023-10-19 19:54 UTC, cacraigucar approved these changes

2023-10-26 17:03 UTC, peverwhee commented
@PeterHjortLauritzen Can you review this when you get a moment?

2023-10-26 21:05 UTC, PeterHjortLauritzen approved these changes
Looks good to me!

2023-11-01 15:17 UTC, nusbaume commented
Not sure why the closing script didn't catch this, but these code changes were brought in with PR #891, and so this PR can be closed.

2023-11-01 15:17 UTC, closed without merging