Provide RRTMGP as a radiation parameterization
ESCOMP/CAM pull request #909
Opened 2023-10-25 22:14 UTC by brian-eaton

Issue #255 - Provide RRTMGP as a radiation parameterization

resolves #255

2023-10-31 02:31 UTC, sjsprecious commented on bld/config_files/definition.xml
> +<entry id="rad" valid_values="rrtmgp,rrtmg,camrt,none" value="">
should `rrtmgp_gpu` be a valid value, too?

2023-10-31 02:31 UTC, sjsprecious commented on bld/configure
> +            print $fh "$camsrcdir/src/physics/rrtmgp/ext/rte-kernels/accel\n";
Should the paths be `ext/rrtmgp/kernels-openacc` and `ext/rte/kernels-openacc`?

2023-10-31 02:31 UTC, sjsprecious commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bam_sulf   rad="rrtmgp">atm/cam/physprops/sulfate_rrtmg_c080918.nc</bam_sulf>
Do all these settings apply to the GPU configuration, too?

2023-10-31 02:31 UTC, sjsprecious commented on bld/namelist_files/namelist_definition.xml
> +       group="phys_ctl_nl" valid_values="rrtmgp,rrtmg,camrt" >
Shall we add `rrtmgp_gpu`, too?

2023-10-31 14:53 UTC, brian-eaton commented on bld/config_files/definition.xml
> +<entry id="rad" valid_values="rrtmgp,rrtmg,camrt,none" value="">
No.  Notice that `rrtmgp_gpu` is a valid value for the `-rad` argument of `configure`.  The configure script strips off the `_gpu` part before setting the `rad` parameter which gets written to the `config_cache.xml` file.  The configure script uses the `_gpu` specification to correctly set the filepaths.  But the namelist script which uses the `config_cache.xml` file to choose default values only needs to know that the radiation parameterization is `rrtmgp`.

2023-10-31 15:00 UTC, brian-eaton commented on bld/configure
> +            print $fh "$camsrcdir/src/physics/rrtmgp/ext/rte-kernels/accel\n";
No.  There was a bunch of file and directory rearranging in the `develop` branch of `rte-rrtmgp` which is where our fixes are located.  The external for RRTMGP use by CAM is currently a hash on the `develop` branch which will be merged to `main` when the next release tag is made.

2023-10-31 15:04 UTC, brian-eaton commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bam_sulf   rad="rrtmgp">atm/cam/physprops/sulfate_rrtmg_c080918.nc</bam_sulf>
Yes.  And this is exactly the reason that `rrtmgp_gpu` is not added to the `config_cache.xml` file.  Otherwise all these settings which have been duplicated (for now) from the `rrtmg` versions would also need to be duplicated for `rrtmgp_gpu`.  `rrtmgp_gpu` is just a different implementation of RRMTGP, not a different radiation parameterization.

2023-10-31 15:05 UTC, brian-eaton commented on bld/namelist_files/namelist_definition.xml
> +       group="phys_ctl_nl" valid_values="rrtmgp,rrtmg,camrt" >
No.  For reasons discussed in previous conversations.

2023-10-31 15:07 UTC, sjsprecious commented on bld/config_files/definition.xml
> +<entry id="rad" valid_values="rrtmgp,rrtmg,camrt,none" value="">
Thanks for your clarification. That is clear to me now!

2023-10-31 15:13 UTC, sjsprecious commented on bld/configure
> +            print $fh "$camsrcdir/src/physics/rrtmgp/ext/rte-kernels/accel\n";
Thanks for your clarification. I did not realize that the paths are different on the `develop` branch and it makes sense to me now.

2023-10-31 15:14 UTC, sjsprecious commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bam_sulf   rad="rrtmgp">atm/cam/physprops/sulfate_rrtmg_c080918.nc</bam_sulf>
That is awesome. Thanks for your clarification.

2023-10-31 15:14 UTC, sjsprecious commented on bld/namelist_files/namelist_definition.xml
> +       group="phys_ctl_nl" valid_values="rrtmgp,rrtmg,camrt" >
Thanks for your clarification.

2023-10-31 15:17 UTC, sjsprecious commented on Externals_CAM.cfg
> +required = True
In our debugging process, I did not see this repo being used. Could you please explain what these data are used for?

2023-10-31 15:37 UTC, brian-eaton commented on Externals_CAM.cfg
> +required = True
This is also part of the file and directory reorganization on the `develop` branch of `rte-rrtmgp`.  The datasets used by RRTMGP, which were previously stored with the source code, have been moved to a separate repo, `rrtmgp-data`.  The filenames of the datasets have removed the creation date part that we use to identify versions of CAM datasets, and instead are using tags in the git repo for version control.

2023-10-31 15:41 UTC, sjsprecious commented on Externals_CAM.cfg
> +required = True
Thanks for your clarification.

2023-11-29 20:29 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
@nusbaume is going to do the review on this PR, but I thought I'd take a quick look at the tests.  Should one of these tests use NAG (to make sure that everything compiles with it)?  Also, I would suggest that at least one of these tests be moved to prealpha, to make sure that CESM updates don't break RRTMGP functionality (maybe the WACCM one?)

2023-12-06 18:28 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
I initially added the `QPC6` test using NAG, but the RRTMGP code fails to compile with our old NAG-6 compiler.  The error indicated that the compiler didn't recognize the intrinsic function `findloc` which was added to Fortran 2008.  Updating our NAG compiler to version 7 should resolve this issue.

I will move the `SMS_D_Ln9.ne30pg3_ne30pg3_mg17.FMTHIST` test to prealpha.

2023-12-20 22:02 UTC, nusbaume requested changes
Fantastic work!  I realize that it looks I have a ton of comments, but most (all?) of them are either very minor or just questions I had.  Thanks again for seeing this through!

2024-01-24 00:29 UTC, brian-eaton commented on bld/build-namelist
> +if ($rad_pkg eq 'rrtmg') {
I wasn't sure, so I ran a test and CARMA does not currently work with RRTMGP.  There are a couple of issues.  First, CARMA is trying to access the spectral band boundaries before they are set.  In RRTMG these bounds are hard-coded as parameters, but in RRTMGP they are read from a dataset during the init call.  It would probably work to move that read to the register call (CARMA is trying to access the values from its register call), but of course any changes to the initialization sequence need to be carefully tested.  The second problem is that both the spectral band boundaries, and the order of the bands are slightly different in RRTMGP.  This will require more careful looking at the CARMA code to see how to make appropriate changes.  The code comments where the spectral boundaries are accessed in CARMA make it clear that CARMA has made some hard-coded assumptions about the RRTMG bands.

I don't think we want to hold up this PR to address these problems.  I would propose that a check be added to configure to disallow using CARMA with RRTMGP at this time.

2024-01-24 18:30 UTC, brian-eaton commented on bld/build-namelist
> +if ($rad_pkg =~ m/rrtmg/) { # matches both rrtmg and rrtmgp
`m//` is the Perl pattern matching operator.  It can be abbreviated as `//` when `/` is used as the pattern delimiter (other delimiters are possible).

2024-01-24 19:17 UTC, brian-eaton commented on bld/namelist_files/use_cases/1850_cam5.xml
> +<?xml version="1.0"?>
Exactly.  I added a note to the PR text, and in the ChangeLog file.

2024-01-24 19:41 UTC, brian-eaton commented on bld/namelist_files/use_cases/1850_cam5.xml
> +<!-- External forcing for BAM or MAM -->
I copied this file from the cesm1_2_2 source.  In that source the main `namelist_defaults_cam.xml` file contains emissions for 2000 for `trop_mam3`, so the overrides are needed in the use case file.  There are also defaults in the main file for bulk aerosol emissions, but they're also for year 2000 emissions.  This is certainly a buyer beware situation if someone tries to run `F1850` with `CAM5` physics **and** tries to use a different chemistry package than `trop_mam3`.

2024-01-29 16:48 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="QPC6" grid="ne5pg3_ne5pg3_mg37" name="ERP_D_Ln9" testmods="cam/outfrq9s_rrtmgp">
Done.

2024-01-29 16:50 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="cheyenne" compiler="intel" category="aux_cam"/>
cheyenne changed to derecho.  comment updated.

2024-01-29 16:59 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FW2000climo" grid="ne30pg3_ne30pg3_mg17" name="SMS_Ln9" testmods="cam/outfrq9s_rrtmgp">
Done.

2024-01-29 17:00 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="PC6" grid="f09_f09_mg17" name="SMS_Ld5" testmods="cam/cam6_port_f09_rrtmgp">
Done.

2024-01-29 17:17 UTC, brian-eaton commented on doc/ChangeLog
> +  SMS_D_Ln9.ne30pg3_ne30pg3_mg17.FMTHIST.cheyenne_intel.cam-outfrq9s_rrtmgp
Done.

2024-01-30 01:03 UTC, brian-eaton commented on bld/build-namelist
> +if ($rad_pkg eq 'rrtmg') {
Based on discussion today with CAM SEs I've added the check in configure to disallow RRTMGP + CARMA.

2024-01-30 01:28 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +         call endrun('number of lw bands does not match')
Done.

2024-01-30 01:29 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +   real(r8),intent(out) :: tau_w_g(nswbands,pcols,pver) ! assymetry parameter * tau * w
Fixed.

2024-01-30 01:29 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +  real(r8),intent(out) :: tau_w_g(nswbands,pcols,pver) ! assymetry parameter * tau * w
Fixed.

2024-01-30 14:41 UTC, brian-eaton commented on src/physics/cam/ebert_curry.F90
>  module ebert_curry
Name changed to `ebert_curry_ice_optics`.

2024-01-30 14:50 UTC, brian-eaton commented on src/physics/cam/oldcloud.F90
> +   return
Removed.

2024-01-30 14:51 UTC, brian-eaton commented on src/physics/cam/oldcloud.F90
> +          !emis(i,k) = 1._r8 - exp(-1.66_r8*kabs*clwp(i,k))
Removed.

2024-01-30 14:52 UTC, brian-eaton commented on src/physics/cam/oldcloud.F90
> +          !emis(i,k) = 1._r8 - exp(-1.66_r8*kabs*clwp(i,k))
Removed.

2024-01-30 14:53 UTC, brian-eaton commented on src/physics/cam/oldcloud.F90
> +          !emis(i,k) = 1._r8 - exp(-1.66_r8*kabs*clwp(i,k))
Removed.

2024-01-30 15:47 UTC, brian-eaton commented on src/physics/cam/slingo.F90
>  !------------------------------------------------------------------------------------------------
Name changed to `slingo_liq_optics`.

2024-01-30 16:10 UTC, brian-eaton commented on src/physics/cam/oldcloud.F90
> +   parameter (kabsl = 0.090361_r8)
Done.

2024-01-30 16:14 UTC, brian-eaton commented on src/physics/rrtmgp/mcica_subcol_gen.F90
> +   ! class(ty_gas_optics), intent(in) :: kdist  ! spectral information ! Wrong?
Done.

2024-01-30 16:14 UTC, brian-eaton commented on src/physics/rrtmgp/mcica_subcol_gen.F90
> +   ! class(ty_gas_optics), intent(in) :: kdist  ! spectral information  ! Wrong?
Done.

2024-01-30 16:18 UTC, brian-eaton commented on src/physics/rrtmgp/radconstants.F90
> +! GASES TREATED BY RADIATION (line spectrae)
Fixed.

2024-01-30 17:00 UTC, brian-eaton commented on src/physics/rrtmgp/radconstants.F90
> +   allocate( values(2,nswbands) )
Done.

2024-01-30 18:07 UTC, brian-eaton commented on src/physics/rrtmgp/radconstants.F90
> +      call endrun('radconstants.F90: get_band_index_by_value: band not found: ')
Done.

2024-01-30 22:48 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   real(r8) :: flux_lw_clr_up(pcols,pverp) ! upward shortwave clearsky flux
Yup.  Fixed.

2024-01-30 22:57 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +            call endrun(sub//': ERROR reading namelist')
Done.

2024-01-30 22:59 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   call mpi_bcast(rad_uniform_angle, 1, mpi_logical, mstrid, mpicom, ierr)
Good catch.  Fixed.

2024-01-30 23:04 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   end if
Fixed.

2024-01-30 23:43 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +         alb_dif)
Double-check done.  `toa_flux` is the only allocatable that I found to be missing from the deallocate statement.

2024-01-31 18:20 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   allocate(cosp_cnt(begchunk:endchunk))
Done.  There are about 50 allocate calls in this file so I added a subroutine to make the checks cleaner.

2024-01-31 19:30 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   end if
This function is identical to the `camrt` and the `rrtmg` versions.  I agree that the code is confusing, and that your interpretation of what it's actually doing is correct.  I have attempted to make the function description a bit more clear.

2024-01-31 19:54 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   call pio_seterrorhandling(file, PIO_BCAST_ERROR)
The reason to ask that PIO return all error codes rather than to fail internally is to allow reading datasets that may not contain a particular variable being queried.  This code reads both SW and LW datasets, but the SW datasets don't contain variables for the planck function and the LW files don't contain variables for solar forcing.

2024-01-31 20:35 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +            ftem(i,k) = (qrs(i,k) + qrl(i,k))/cpair * (1.e5_r8/state%pmid(i,k))**cappa
This code is identical to what appears in the `camrt` and `rrtmg` versions.  The value of `psurf_ref` comes from the initial file and I'm not sure we can depend on it being 1.e5.  I don't know how MPAS sets the reference pressure array (which it only does to make CAM happy since it uses a height based coordinate).  I don't think thermodynamic consistency is an issue since this field is a diagnostic quantity only.  It's not used to compute the dry static energy tendency.

2024-01-31 22:32 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +                          gravit / state%pdel(:ncol,k)
I made this change and verified that the diffs are roundoff.  Since the tests for RRTMGP will be introduced with this PR then the tests will fail due to no baselines rather than a roundoff diff.

2024-02-05 15:16 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   call outfld('LWCF'//diag(icall),    ftem,          pcols, lchnk)
Good question.  I believe it's because there are no clouds above the model top.  Hence, the downward LW would be the same in the cloudy and clear sky calculations and the downward contributions would cancel in the cloud forcing calculation.  This is the same expression for `LWCF` that's used in the RRTMG code.

2024-02-05 15:19 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   character(len=256) :: locfn ! path to file on local storage
Done.

2024-02-05 15:31 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   allocate(int2log(minor_absorber_intervals_lower))
Agreed.  Done.

2024-02-06 14:41 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +   if (do_direct_local) allocate(fluxes%bnd_flux_dn_dir(ncol, nlevels, nbands))
It turns out that the spectral fluxes are used to partition the all-sky downward SW fluxes at the surface into UV/visible and near-IR parts.  The spectral fluxes for the all-sky LW are only used when `spectralflux=.true.`.  And the spectral fluxes for both SW and LW clear-sky calculations are not used at all.  I've refactored the code to use objects of type `ty_fluxes_broadband`, which only contains the broadband fluxes, for the clear-sky calculations.  The routines `initialize_rrtmgp_fluxes`, `reset_fluxes`, and `free_fluxes` are modified to have a polymorphic `ty_fluxes_broadband` dummy argument so allocation of arrays for spectrally resolved components only happens for objects of type `ty_fluxes_byband`.  In addition `initialize_rrtmgp_fluxes` is modified to only allocate the spectral fluxes for SW objects, or for a LW object when `spectralflux=.true.`.  Interestingly the change to using `ty_fluxes_broadband` objects for the clear-sky calculations results in a roundoff level answer change, presumably due to a difference in how the g-point values are summed.  This answer change does not impact the simulation because clear-sky calculations are only used for diagnostic output.

2024-02-06 14:52 UTC, brian-eaton commented on src/physics/spcam/crm/CLUBB/crmx_mt95.f90
> +! Code converted to Fortran 95 by Jose Rui Faustino de Sousa
I use a code differencing tool that flags non-ascii characters as diffs, even if it's the same non-ascii character in both files.  In this case the character is a lowercase e with an acute diacritical mark.  I don't know that we have a policy concerning non-ascii characters in comments, but it was annoying to always have this file show up with diffs when there were none.

2024-02-06 14:55 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +            alb_dif(iband,i) = 0.5 * (cam_in%aldif(idxday(i)) + cam_in%asdif(idxday(i)))
Fixed.

2024-02-06 15:55 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +logical function is_visible(wavenumber)
Agreed.  Done.

2024-02-06 16:15 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   allocate(gas_vmr(numactivecols, nlay))
Done.

2024-02-06 16:18 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +            P_top = 50.0_r8
`P_top` moved in front of loop.

2024-02-06 16:24 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +            beta = 0.0_r8
I would call those lines unused and unnecessary rather than defensive:)  Removed.

2024-02-06 17:09 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +               chi_eff = chi_eff / 2.1415e-5_r8               ! O3 column above in DU
The rrtmg version of this code for setting O3 in the "extra layer" has an outfld call for this value.  I've removed the code since the addfld/outfld calls are also missing in the rrtmgp version.

2024-02-06 17:15 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   real(r8), intent(out) :: cld_lw_abs_cloudsim(pcols,pver) ! in-cloud snow optical depth (for COSP)
Agreed.  Fixed.

2024-02-06 17:18 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   real(r8) :: ice_tau_w_g(nswbands,pcols,pver) ! ice assymetry parameter * tau * w
Fixed.

2024-02-06 17:18 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +      allocate( &
Done.

2024-02-06 17:39 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +
The validate check would be redundant since it's checking that the limits imposed in lines 992 and 993 are in fact satisfied.  At one point I tried removing the imposed limits and using the validate check, but that just triggers an `endrun` when the conditions aren't satisfied.  Ideally the aerosol optics code would ensure that it's producing valid values, but that apparently isn't the case.  I don't see that the RRTMG code checks for these limits.  RRTMGP is more restrictive about getting valid inputs.

2024-02-07 20:41 UTC, jedwards4b commented
@cacraigucar there are a number of ways to limit the checked out repository in git, specifically  
```
 --depth <depth>
           Create a shallow clone with a history truncated to the specified number of commits. Implies --single-branch unless
           --no-single-branch is given to fetch the histories near the tips of all branches. If you want to clone submodules
           shallowly, also pass --shallow-submodules.
```
git submodule add also has a --depth option.

However I don't think that there is an easy way to apply them with manage_externals.

2024-02-07 20:54 UTC, cacraigucar commented
> @cacraigucar there are a number of ways to limit the checked out repository in git, specifically
> 
> ```
>  --depth <depth>
>            Create a shallow clone with a history truncated to the specified number of commits. Implies --single-branch unless
>            --no-single-branch is given to fetch the histories near the tips of all branches. If you want to clone submodules
>            shallowly, also pass --shallow-submodules.
> ```
> 
> git submodule add also has a --depth option.
> 
> However I don't think that there is an easy way to apply them with manage_externals.

Doing a clone by hand with --depth 1 doesn't appear to impact the size at all.  The .git/objects/pack directory is still the same size.  Any other suggestions?

2024-02-07 20:55 UTC, jedwards4b commented
Actually you can bring these in as submodules using the --depth option as suggested and then use the manage_externals interface to submodules:
```
[rrtmgp]
protocol = git
from_submodule = True
required = True
```

2024-02-07 20:59 UTC, jedwards4b commented
Perhaps you made an error?
 ```
git clone -b v1.7 --depth 1 https://github.com/earth-system-radiation/rte-rrtmgp.git
Cloning into 'rte-rrtmgp'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 126 (delta 10), reused 66 (delta 6), pack-reused 0
Receiving objects: 100% (126/126), 204.39 KiB | 1.70 MiB/s, done.
Resolving deltas: 100% (10/10), done.
Note: switching to '4d8c5df4c63434aaab854afd1b02f5986d41dfb3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

casper-login1: ~/tmp
:) du -sk rte-rrtmgp/
3186	rte-rrtmgp/
```
 git clone -b v1.7 https://github.com/earth-system-radiation/rte-rrtmgp.git rte-rrtmgp.full
Cloning into 'rte-rrtmgp.full'...
remote: Enumerating objects: 7537, done.
remote: Counting objects: 100% (2860/2860), done.
remote: Compressing objects: 100% (873/873), done.
remote: Total 7537 (delta 2082), reused 2644 (delta 1920), pack-reused 4677
Receiving objects: 100% (7537/7537), 118.07 MiB | 18.80 MiB/s, done.
Resolving deltas: 100% (5213/5213), done.
Note: switching to '4d8c5df4c63434aaab854afd1b02f5986d41dfb3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

casper-login1: ~/tmp
:) du -sk rte-rrtmgp.full/
242583	rte-rrtmgp.full/
```

2024-02-07 21:17 UTC, cacraigucar commented
> Perhaps you made an error?
> 
> ```
> git clone -b v1.7 --depth 1 https://github.com/earth-system-radiation/rte-rrtmgp.git
> Cloning into 'rte-rrtmgp'...
> remote: Enumerating objects: 126, done.
> remote: Counting objects: 100% (126/126), done.
> remote: Compressing objects: 100% (114/114), done.
> remote: Total 126 (delta 10), reused 66 (delta 6), pack-reused 0
> Receiving objects: 100% (126/126), 204.39 KiB | 1.70 MiB/s, done.
> Resolving deltas: 100% (10/10), done.
> Note: switching to '4d8c5df4c63434aaab854afd1b02f5986d41dfb3'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>  git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>  git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> casper-login1: ~/tmp
> :) du -sk rte-rrtmgp/
> 3186	rte-rrtmgp/
> ```
> 
> git clone -b v1.7 https://github.com/earth-system-radiation/rte-rrtmgp.git rte-rrtmgp.full Cloning into 'rte-rrtmgp.full'... remote: Enumerating objects: 7537, done. remote: Counting objects: 100% (2860/2860), done. remote: Compressing objects: 100% (873/873), done. remote: Total 7537 (delta 2082), reused 2644 (delta 1920), pack-reused 4677 Receiving objects: 100% (7537/7537), 118.07 MiB | 18.80 MiB/s, done. Resolving deltas: 100% (5213/5213), done. Note: switching to '4d8c5df4c63434aaab854afd1b02f5986d41dfb3'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may do so (now or later) by using -c with the switch command. Example:
> 
> git switch -c
> 
> Or undo this operation with:
> 
> git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> casper-login1: ~/tmp :) du -sk rte-rrtmgp.full/ 242583 rte-rrtmgp.full/
> 
> ```
> 
> ```

Yup - I must have done something wrong, as my size is dramtically reduced.

What exactly do I put in the Externals.cfg file?

> Perhaps you made an error?
> 
> ```
> git clone -b v1.7 --depth 1 https://github.com/earth-system-radiation/rte-rrtmgp.git
> Cloning into 'rte-rrtmgp'...
> remote: Enumerating objects: 126, done.
> remote: Counting objects: 100% (126/126), done.
> remote: Compressing objects: 100% (114/114), done.
> remote: Total 126 (delta 10), reused 66 (delta 6), pack-reused 0
> Receiving objects: 100% (126/126), 204.39 KiB | 1.70 MiB/s, done.
> Resolving deltas: 100% (10/10), done.
> Note: switching to '4d8c5df4c63434aaab854afd1b02f5986d41dfb3'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>  git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>  git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> casper-login1: ~/tmp
> :) du -sk rte-rrtmgp/
> 3186	rte-rrtmgp/
> ```
> 
> git clone -b v1.7 https://github.com/earth-system-radiation/rte-rrtmgp.git rte-rrtmgp.full Cloning into 'rte-rrtmgp.full'... remote: Enumerating objects: 7537, done. remote: Counting objects: 100% (2860/2860), done. remote: Compressing objects: 100% (873/873), done. remote: Total 7537 (delta 2082), reused 2644 (delta 1920), pack-reused 4677 Receiving objects: 100% (7537/7537), 118.07 MiB | 18.80 MiB/s, done. Resolving deltas: 100% (5213/5213), done. Note: switching to '4d8c5df4c63434aaab854afd1b02f5986d41dfb3'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may do so (now or later) by using -c with the switch command. Example:
> 
> git switch -c
> 
> Or undo this operation with:
> 
> git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> casper-login1: ~/tmp :) du -sk rte-rrtmgp.full/ 242583 rte-rrtmgp.full/
> 
> ```
> 
> ```

Yup, I must have done something wrong as I now see the size I need.  Sorry about that!

What exactly do we need to put into our workflow and/or manage_externals?  RRTMGP in this PR is a part of Externals_CAM.cfg.  When I add "from_submodule = True" into the rrtmgp sections, I get an error from manage_externals that I have over specified with both from_submodule and tag.  I also don't know where I'd put in the --depth 1.    I'm trying to find a solution that a user cloning CAM and running manage_externals will get the smaller sized checkout.  Is this possible?

2024-02-07 21:24 UTC, jedwards4b commented
You want to bring rrtmgp into cam as a submodule 
`git submodule add --depth=1 -b v1.7 https://github.com/earth-system-radiation/rte-rrtmgp.git src/physics/rrtmgp/ext
`
and add the code exactly as I have it above to Externals_CAM.cfg
You won't be able to add a tag to the Externals_CAM.cfg file.

2024-02-07 21:34 UTC, cacraigucar commented
Thanks @jedwards4b .  I think I finally understand (I've never dealt with submodules before).  

@brian-eaton - Can you add the two rrtmgp checkouts as submodules (using the command Jim provided above with the --depth 1)?  Then you'll need to modify the Externals_CAM.cfg file for these two externals.  This should reduce the RRTMGP size tremendously.  I've done this by hand and it appears to work for me, so let me know if you have any questions.

2024-02-07 21:37 UTC, jedwards4b commented
Just so you are aware for developers - you can go to the submodule directory and run git fetch origin to get the entire repository locally if you want it.

2024-02-07 22:18 UTC, nusbaume commented on bld/build-namelist
> +if ($rad_pkg eq 'rrtmg') {
Just leaving this comment un-resolved so that we remember to make a Github issue about CARMA not working with RRTMGP after this PR has been merged.

2024-02-07 22:37 UTC, nusbaume approved these changes
Thanks for responding to all of my comments! This PR looks good to me now.  I did find one last set of typos, and one optional suggestion, but I don't believe it needs another review from me.

2024-02-07 22:37 UTC, nusbaume commented on src/physics/rrtmgp/radiation.F90
> +            ftem(i,k) = (qrs(i,k) + qrl(i,k))/cpair * (1.e5_r8/state%pmid(i,k))**cappa
Good point(s)!  I am fine to leave this as-is then, especially since having it be consistent with the older `camrt` and `rrtmg` versions may be more important then consistency with other aspects of the model, especially given that it is just a diagnostic.

2024-02-07 23:00 UTC, cacraigucar requested changes
Submitting my comments from my short review (lots still to go).

2024-02-07 23:00 UTC, cacraigucar commented on bld/configure
> +        $rad_pkg =~ s!_gpu!!
Wouldn't it have been more straightforward to set  $rad_pkg to  'rrtmgp' since by the if statement above, it can't be anything but that?

2024-02-07 23:00 UTC, cacraigucar commented on Externals_CAM.cfg
> +required = True
Change these once rrtmgp is brought in as a submodule

2024-02-07 23:00 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FW2000climo" grid="ne30pg3_ne30pg3_mg17" name="SMS_Ln9" testmods="cam/outfrq9s_rrtmgp">
I'm torn between testing with the coarse ne3pg3 grid versus moving this test to prealpha (I feel like adding a 40 minute job to aux_cam is a bit much).

2024-02-07 23:00 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +      <option name="wallclock">00:30:00</option>
I'm surprised that this test has a 30 minute time limit, while FMTHIST has a 20.  Does it need to be 30 minute, or does the FMTHIST need to be bumped up?

2024-02-12 17:16 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +   real(r8),intent(out) :: tau_w_g(nswbands,pcols,pver) ! asymetry parameter * tau * w
Done.  I've done a global search to try and stamp out all the misspellings of asymmetry.

2024-02-12 17:16 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +   real(r8),intent(out) :: tau_w_g(nswbands,pcols,pver) ! asymetry parameter * tau * w
Done.

2024-02-12 17:16 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +   real(r8),intent(out) :: tau_w_g(nswbands,pcols,pver) ! asymetry parameter * tau * w
Done.

2024-02-12 17:16 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +  real(r8),intent(out) :: tau_w_g(nswbands,pcols,pver) ! asymetry parameter * tau * w
Done.

2024-02-12 23:17 UTC, cacraigucar reviewed
Next round of comments - still need to look at a few more routines

2024-02-13 01:14 UTC, brian-eaton commented on src/physics/rrtmgp/radiation.F90
> +subroutine check_allocate(istat, sub, info)
I made that change and got rid of the local `check_allocate` routine.  It turns out there is also an `alloc_err` routine in module `error_messages` which I had found and used in `rrtmgp_inputs`.  That one allows putting the size of the requested allocate statement into the error message.

2024-02-13 01:18 UTC, brian-eaton commented on bld/configure
> +        $rad_pkg =~ s!_gpu!!
Changed.

2024-02-13 01:34 UTC, brian-eaton commented on src/physics/cam/cloud_rad_props.F90
> +        if( iciwpth(i,k) < 1.e-80_r8 .or. dei(i,k) == 0._r8) then
I replaced `1.e-80_r8` by parameter `tiny` which is commonly used as a limiter which doesn't have any particular physical meaning.

2024-02-13 14:17 UTC, brian-eaton commented on src/physics/rrtmgp/mcica_subcol_gen.F90
> +!  --------------------------------------------------------------------------
I don't know the answer to that.  I left it in because it was in the original code that I refactored and cleaned up.  But the algorithms have not changed from the original.  I moved the notice to try and clarify.  What do you think?

2024-02-13 14:24 UTC, brian-eaton commented on src/physics/rrtmgp/radconstants.F90
> +! the datasets are read.
At some point I moved the check to the `set_wavenumber_bands` subroutine in the `radconstants` module.  Comment fixed.

2024-02-13 17:44 UTC, brian-eaton commented
> You want to bring rrtmgp into cam as a submodule `git submodule add --depth=1 -b v1.7 https://github.com/earth-system-radiation/rte-rrtmgp.git src/physics/rrtmgp/ext ` and add the code exactly as I have it above to Externals_CAM.cfg You won't be able to add a tag to the Externals_CAM.cfg file.

@jedwards4b, I'm trying to add the RRTMGP source as a submodule following your instructions, but am getting an error.  Here's what happens, starting from a clean clone of my CAM fork on branch rrtmgp:
```
% cd /work/src
% git clone -b rrtmgp https://github.com/brian-eaton/CAM cam-rrtmgp
remote: Enumerating objects: 34903, done.
remote: Counting objects: 100% (1191/1191), done.
remote: Compressing objects: 100% (565/565), done.
remote: Total 34903 (delta 724), reused 992 (delta 601), pack-reused 33712
Receiving objects: 100% (34903/34903), 39.37 MiB | 22.91 MiB/s, done.
Resolving deltas: 100% (25327/25327), done.

% cd cam-rrtmgp
% git status
On branch rrtmgp
Your branch is up to date with 'origin/rrtmgp'.

nothing to commit, working tree clean

% git submodule add --depth=1 -b v1.7 \
  https://github.com/earth-system-radiation/rte-rrtmgp.git src/physics/rrtmgp/ext
The following paths are ignored by one of your .gitignore files:
src/physics/rrtmgp/ext
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```
So I added the -f option:
```
% git submodule add --depth=1 -b v1.7 -f \
  https://github.com/earth-system-radiation/rte-rrtmgp.git src/physics/rrtmgp/ext
Cloning into '/work/src/cam-rrtmgp/src/physics/rrtmgp/ext'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 129 (delta 11), reused 58 (delta 5), pack-reused 0
Receiving objects: 100% (129/129), 206.66 KiB | 2.46 MiB/s, done.
Resolving deltas: 100% (11/11), done.
fatal: 'origin/v1.7' is not a commit and a branch 'v1.7' cannot be created from it
fatal: unable to checkout submodule 'src/physics/rrtmgp/ext'
```
I don't understand this error.  `v1.7` is a tag on branch `main` in the `rte-rrtmgp` repo.  Any ideas?

2024-02-13 18:38 UTC, nusbaume commented
Hi @brian-eaton @jedwards4b @cacraigucar I have been working on this today, and I have reached a point where I believe there is a bug in manage_externals which prevents submodules from working properly.  When I add the two RRTMGP repos as submodules (which I know is working because I can use commands like `git submodule update` to get the relevant files but with a much smaller disk footprint), but then try to use `checkout_externals` with the `from_submodules` flag I get the following error:

```
{   'externals': '',
    'from_submodule': True,
    'repo': {   'branch': '',
                'hash': '',
                'protocol': 'git',
                'repo_url': '',
                'sparse': '',
                'tag': ''},
    'required': True}
ERROR:root:No parent submodule for "rte-rrtmgp"
```

The problem is that the `.gitmodules` file definitely exists in the top-level directory, and definitely contains a submodule named `rte-rrtmgp`.  Quickly looking through the code it appears that the issue could be that there is a `parent_repo` variable that doesn't seem to be set anywhere, although I could certainly be wrong on that front.

If I am wrong here and someone else can get it to work properly then definitely ignore this comment post.  However if everyone else  runs into the same problem then at this point I might vote to just leave the checkout as-is, and then once we bring in git-fleximod we'll implement a single depth checkout to reduce the large disk space overhead.  To me that seems like a better use of everyone's time then trying to fix software (manage_externals) which is going away soon.  Thoughts?

2024-02-13 19:22 UTC, jedwards4b commented
@nusbaume is correct, this is a manage_extenals bug - if you checkout cesm so that cam is not the toplevel directory the submodule checkout will work correctly.  

@brian-eaton Reverse the --depth and -b options:

 git submodule add -b v1.7 --depth=1  -f   https://github.com/earth-system-radiation/rte-rrtmgp.git src/physics/rrtmgp/ext
Adding existing repo at 'src/physics/rrtmgp/ext' to the index

2024-02-13 20:15 UTC, brian-eaton commented on Externals_CAM.cfg
> +required = True
As per comments below (thanks @jedwards4b and @nusbaume) will leave this alone for now.  Will revisit when we bring in git-fleximod.

2024-02-14 15:47 UTC, cacraigucar requested changes
Final set of review comments.

Kudos to whoever wrote the excellent code comments (especially in the rrtmgp_inputs.F90 module).  They really helped with reviewing the code!

2024-02-14 15:47 UTC, cacraigucar commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   if (nlay == pverp) then
Will this work with all variations of CAM current and future since model tops can change?  I would think a better check would be to retrieve the pressure at the top and make the if check based off of that

2024-02-14 15:47 UTC, cacraigucar commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +      P_top = 50.0_r8
Should this be a namelist setting  - rrtmgp_pres_top or something like that?  I'm asking because the comment indicated that this was based on tuning the model.

2024-02-14 15:47 UTC, cacraigucar commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   ! the sw/lw band boundaries in the radconstants module.
Does a check need to be added to ensure that set_wavenumber_bands has been called prior to this routine?

2024-02-14 17:52 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FW2000climo" grid="ne30pg3_ne30pg3_mg17" name="SMS_Ln9" testmods="cam/outfrq9s_rrtmgp">
According to the TestStatus file the run time is 349 which is less than the build time.  If that's wall seconds then I can conservatively cut the wallclock time to 10 minutes.  I'll go ahead and do that.

2024-02-14 17:54 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FW2000climo" grid="ne30pg3_ne30pg3_mg17" name="SMS_Ln9" testmods="cam/outfrq9s_rrtmgp">
According to the TestStatus file the run time is 349 which is less than the build time.  If that's wall seconds then I can conservatively cut the wallclock time to 10 minutes.  I'll go ahead and do that.

2024-02-14 18:00 UTC, brian-eaton commented on cime_config/testdefs/testlist_cam.xml
> +      <option name="wallclock">00:30:00</option>
Changed to 20:00.  The TestStatus file reports the run time is 659.

2024-02-19 15:50 UTC, brian-eaton commented on src/physics/rrtmgp/radconstants.F90
> +subroutine get_sw_spectral_boundaries(low_boundaries, high_boundaries, units)
Subroutine `get_sw_spectral_boundaries` is an accessor function for the private module data ` wavenumber_low_shortwave` and `wavenumber_high_shortwave`.  Subroutine `get_lw_spectral_boundaries` is an accessor function for the private module data ` wavenumber_low_longwave` and `wavenumber_high_longwave`.  They could be combined along with an additional argument to specify whether the `sw` or `lw` spectra was being requested and logic to access the correct arrays.  I don't see any particular advantage to doing it that way.

2024-02-19 16:09 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +real(r8), parameter :: tiny = 1.0e-80_r8
Do you mean if RRTMG changes the tiny value?  I think the only consistency that's required is within the module so that all the clipping operations use the same tiny value.  Presumably, since this value is arbitrary, changing it might introduce a roundoff level change in the simulation, but would not be climate changing.  I'm guessing this value was chosen because it worked in RRTMG, so it should work here as well.

2024-02-19 16:32 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   [ 14, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
Unlike the RRTMG code, the RRTMGP interface code doesn't make any assumption about the spectral band boundaries or their order.  That data is read from input datasets.  What the RRTMGP code is assuming is the band order in the RRTMG optics datasets.  The reason this mapping is hard-coded is that the optics datasets don't contain the metadata that they should contain to describe the spectral bands.  Furthermore a couple of the bands used by RRTMGP don't have the same bounds that the RRTMG versions have.  The bottom line is that the optics datasets used by RRTMGP should be updated to match the RRTMGP band boundaries.  But this hack enables continued use of the RRTMG datasets until the scientists decide the approximation involved is no longer acceptable.

2024-02-19 17:08 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   if (nlay == pverp) then
`nlay` depends on the number of model layers that are below the RRTMGP top of 1 Pa.  It is set in `subroutine radiation_init` making use of the reference pressures at the model layer interfaces.  The condition `nlay == pverp` tells you that the radiation is using 1 more than the `pver` layers that CAM has, hence the addition of the "extra layer".  Dealing with the fact that RRTMGP usually uses a different number of layers than CAM is the most subtle aspect of the interface code.  But this is also true for RRTMG, so we were able to leverage a lot of existing code to deal with this issue.

2024-02-19 19:33 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +      P_top = 50.0_r8
I prefer not to expose parameters before the scientists have expressed a desire to be able to easily change them.  This algorithm for setting O3 in the "extra layer" has been in RRTMG for a long time and to my knowledge no one has needed/wanted to change it.  @brianpm, what do you think about this?  Note that the "extra layer" is only used by low top models.  FMT* and WACCM have tops above the 1 Pa upper limit of RRTMGP.

2024-02-19 19:39 UTC, brian-eaton commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   ! the sw/lw band boundaries in the radconstants module.
Subroutine `get_sw_spectral_boundaries` checks that `set_wavenumber_bands` has been called and calls endrun with an informative message if it hasn't.

2024-02-19 21:45 UTC, brianpm commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +      P_top = 50.0_r8
I'd agree that we should just leave it for now. There are very few (if any) users who would have a good reason to mess with this value, and it would not be helpful as a tuning parameter for the climate.

2024-02-20 23:51 UTC, cacraigucar approved these changes
Great job everyone on this PR!!!

2024-02-20 23:51 UTC, cacraigucar commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   if (nlay == pverp) then
Thanks for the explanation.  I am leaving this unresolved so we can easily see your explanation about this important aspect of the code

2024-02-20 23:51 UTC, cacraigucar commented on src/physics/rrtmgp/rrtmgp_inputs.F90
> +   [ 14, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
Leaving this comment "unresolved" as it will make it easier to find this explanation.

2024-02-20 23:51 UTC, cacraigucar commented on src/physics/rrtmgp/mcica_subcol_gen.F90
> +!  --------------------------------------------------------------------------
Let's go ahead and leave it.

2024-02-20 23:51 UTC, cacraigucar commented on cime_config/testdefs/testlist_cam.xml
> +  </test>
We will need to keep this in mind if more tests start to use RRTMGP (or if it ever becomes default).

2024-02-21 19:00 UTC, merged