Adding convective gustiness to U10: Add UGUST output to CAM
ESCOMP/CAM pull request #943
Opened 2023-12-20 15:28 UTC by megandevlan

This corresponds to issue https://github.com/ESCOMP/CAM/issues/540, and CMEPS https://github.com/ESCOMP/CMEPS/issues/267 (PR soon to come on CMEPS side). 

Adding convective gusts to U10 occurs in the coupler, but the added magnitude (UGUST) needs to be output in CAM; these mods enable that. 

Run to confirm the impact of this change is at: https://github.com/NCAR/amwg_dev/issues/440

2023-12-21 23:53 UTC, cacraigucar commented
This PR will need an update to Externals.cfg for the CMEPS external.  @jedwards4b says this is currently cmeps0.14.48, but recent discussions indicate that another tag may be made.

2023-12-22 03:30 UTC, megandevlan commented
I believe the CMEPS external will now be cmeps0.14.49.

2024-01-02 05:25 UTC, peverwhee approved these changes
one nitpick, but looks good!

2024-01-02 05:25 UTC, peverwhee commented on src/physics/cam/cam_diagnostics.F90
> +    call addfld ('UGUST',      horiz_only, 'A', 'm/s','Gustiness term added to U10')
nitpick, but would be nice if this line (and 1789) can be adjusted to align with the above lines for readability

2024-01-02 15:26 UTC, megandevlan commented on src/physics/cam/cam_diagnostics.F90
> +    call addfld ('UGUST',      horiz_only, 'A', 'm/s','Gustiness term added to U10')
Thanks for catching that! Just updated my branch so that the lines are properly aligned now.

2024-01-03 18:52 UTC, cacraigucar requested changes
The CMEPS external needs to be added to this PR.

This appears to only be adding a diagnostic variable at the CAM level.  If that is the case, this is fine.  If it does somehow change answers for cam_dev runs (due to the CMEPS external update), then a way to turn this on/off via a namelist might need to be introduced.

2024-01-03 20:46 UTC, megandevlan commented
The CAM mods are mostly to add the diagnostic variable, but it's true that for that to work I should have updated the externals -  I _think_ I've done that here. There's a namelist option to turn the gusts on/off, which is set in usr_nl_cpl (add_gust)

2024-01-05 21:13 UTC, cacraigucar approved these changes

2024-02-23 18:43 UTC, merged