SCAM-SE feature addition plus bugfixes and some refactoring.
ESCOMP/CAM pull request #958
Opened 2024-01-10 17:58 UTC by jtruesdal

This update includes some refactoring of SCAM, a few bugfixes, and adding the capability to use spectral elements dycore to do vertical transport in the column.  The SE feature addition follows the E3SM implementation where a complete coarse resolution (ne3np4) of the SE dycore is initialized but only a single element is run through vertical transport with all element subcolumns being copies of the single column chosen by scmlat, scmlon.  

Like the Eulerian version, SCAM-SE also has a bit for bit test to validate an exact run through the same physics as the full 3d model.  Because SCAM updates the solution using a slightly different order of operations, the bfb capability is tested by making a special diagnostic run of CAM where the 3d model derives the phys/dyn tendency each time step and then recalculates the prognostic solution using the derived tendencies and SCAM's prognostic equation. This new solution (which is less precise (roundoff) due to the change in order of operations) is substituted for the full 3d solution at each time step of the model run.  The substitution of the roundoff state in the 3d run allows SCAM to reproduce (BFB) each time step using the captured tendencies in the cam iop history file. 

The SCAM-SE vertical advection skips the horizontal step and derives the floating level tendency based on the IOP prescribed vertical velocity. The floating levels are subsequently remapped at the end of the vertically Lagrangian dynamics step.

2024-01-11 15:09 UTC, jedwards4b requested changes
Hi John - thank you for your work on this, it's clear that you've put a lot of time and effort into it.  
There are a lot of changes using user mods or test mods that should be done in config_compsets.xml - I know there are several ways to do this - user mods are the worst in my opinion, please consider changing.    I also strongly feel that this PR should include a change to [shr_scam_mod.F90 ](https://github.com/ESCOMP/CESM_share/blob/main/src/shr_scam_mod.F90#L717) to remove the requirement for MCT.

2024-01-11 15:09 UTC, jedwards4b commented on src/dynamics/se/apply_iop_forcing.F90
> +use pmgrid
Please add only clause.

2024-01-11 16:55 UTC, jtruesdal commented on Externals.cfg
> +repo_url = https://github.com/jtruesdal/CESM_share
i'll double check this and get rid of it.  Thanks.

2024-01-11 17:35 UTC, jedwards4b commented
@cacraigucar I have to disagree,  I think that user mods really obfuscate things - but I have a meeting with John at 2 today to look at this and maybe what we should do is create another branch so that we can compare and contrast the two approaches.

2024-01-12 16:29 UTC, cacraigucar commented
> @cacraigucar I have to disagree, I think that user mods really obfuscate things - but I have a meeting with John at 2 today to look at this and maybe what we should do is create another branch so that we can compare and contrast the two approaches.

I'm getting ready to start reviewing this PR and was curious about any proposed changes that might be made due to your meeting yesterday?   @jedwards4b @jtruesdal

2024-01-12 23:35 UTC, cacraigucar requested changes
Submitting the items I have found so far - have not completed the review by any means

2024-01-12 23:35 UTC, cacraigucar commented on src/control/scamMod.F90
> +      write(6,*)'using column value of f12vmr from boundary data as global volume mixing ratio'
This is obviously really old code.  Need to change `write(6` to use `iulog`.  This pertains throughout this routine

2024-01-12 23:35 UTC, cacraigucar commented on src/control/scamMod.F90
> +   if (status .ne. nf90_noerr) then
Could you update the logical operators from `.ne.` to` /=` throughout this code?

2024-01-16 15:40 UTC, jtruesdal commented on cime_config/usermods_dirs/scam_gateIII/shell_commands
> +if [ `./xmlquery --value CAM_DYCORE` == 'se' ]; then
Agreed. The latest set of mods move this functionality from usermods to new compsets and related config routines.  I'm testing now and will ask for another review when its available.

2024-01-21 20:23 UTC, jtruesdal commented
> > @cacraigucar` I have to disagree, I think that user mods really obfuscate things - but I have a meeting with John at 2 today to look at this and maybe what we should do is create another branch so that we can compare and contrast the two approaches.

> I'm getting ready to start reviewing this PR and was curious about any proposed changes that might be made due to your meeting yesterday? @jedwards4b @jtruesdal

We did meet and as it turns out I already had a mostly complete set of mods for moving to a compset version of the different IOPs. I wanted to see what the effect of pushing the IOP configuration under cime_config would be. So I created a new branch with them to compare to the current way of doing things. 

https://github.com/jtruesdal/CAM-1/compare/b567e51..jtruesdal:CAM-1:scam_dev_exp_w_compsets?expand=1

The mods add a cam6 configuration option for each IOP.  I also added an alias for each IOP although we could keep one main IOP alias and allow users to switch between the various IOPS by specifying the correct longname.  Having the IOP configure options also allow the user to run any IOP case using any of the other configuration options available in the longname.  We no longer need the usermods scam directories and they have been deleted in the branch.  Although if someone wants to add their own IOP then they will most likely do so through the usermods directory, so from the user perspective nothing has changed in that respect.

Whether they should be a configured via compsets is still an open question.  Although they are not configuring for new physics parameterizations, one of the changes being added in this commit is the ability to modify the CLUBB parameterization to be more consistent with the type of forcing represented by the IOP.  After looking at the comparison, they don't seem to overly complicate the xml files and these options make it easier to use the framework default configurations for each IOP via the compset longnames instead of having to individually specify them via usermods. I agree with Jim that this is a better way to setup the standard IOP's while still allowing usermods for user defined IOPs or user_nl_cam to tweak the setup like we do with other compsets.

2024-01-21 20:28 UTC, jtruesdal commented
@jedwards4b wrote:
> I also strongly feel that this PR should include a change to [shr_scam_mod.F90 ](https://github.com/ESCOMP/CESM_share/blob/main/src/shr_scam_mod.F90#L717)to remove the requirement for MCT.

I'm happy to include this change but after looking at the code in question I don't know how to make the proper changes for NUOPC.  Would you be able to help or provide a set of mods to use?  I'm happy to test along with the rest of the PR.

2024-01-22 03:50 UTC, jtruesdal commented on Externals.cfg
> +repo_url = https://github.com/jtruesdal/CESM_share
Tag name should be share1.0.17_scamdev.  I had a few mods for shr_scam_mod that turned up in testing for this PR. If you can help with the mods for getting rid of MCT I'm happy to include them, test and create the PR to CESM_share.  In the meantime I'll fix the tag reference above.

2024-01-22 03:50 UTC, jtruesdal commented on cime_config/usermods_dirs/scam_gateIII/shell_commands
> +if [ `./xmlquery --value CAM_DYCORE` == 'se' ]; then
See conversation below with Cheryl.

2024-01-22 03:50 UTC, jtruesdal commented on src/dynamics/se/apply_iop_forcing.F90
> +use pmgrid
Done.

2024-01-22 03:51 UTC, jtruesdal commented on Externals.cfg
> +branch = cdeps1.0.24_scamdev
I will change these to the official branch names as the PR's for each of these branches goes through.  I think most should be timely enough but land may take longer than we want to wait, in which case I can do without and keep the coldstart option for land.  I will add to a misc PR or create another small one to include the land update when it is approved.

2024-01-22 03:51 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="ne3np4"          >atm/cam/topo/se/ne3np4_gmted2010_modis_bedmachine_nc0540_Laplace1000_noleak_20230717.nc</bnd_topo>
It has the appropriate metadata and has been imported.

2024-01-22 03:51 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<bnd_topo hgrid="ne4np4"          >atm/cam/topo/USGS-gtopo30_ne4np4_16x.c20160612.nc</bnd_topo>
This file is not needed and I've removed it.

2024-01-22 03:52 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<drydep_srf_file hgrid="ne4np4"          >atm/cam/chem/trop_mam/atmsrf_ne4np4_from_0.23x0.31_181018.nc</drydep_srf_file>
Added the metadata to the ne3 datasets and imported. np4 is not needed and was removed.

2024-01-22 03:52 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata  dyn="se1"   hgrid="ne3np4"                scam="1"  >atm/cam/inic/se/CESM2.F2000climo.ne3np4.cam.i.0003-06-01-00000.nc</ncdata>
This file is one of 12 monthly files needed to initialize SCAM-SE.  I did make sure each has proper metadata and was imported into the repository.  The defaults file will also be updated once we make a decision on the best way to initialize the different IOPS (usermods or compset).

2024-01-22 03:52 UTC, jtruesdal commented on src/control/history_scam.F90
> +! !LOCAL VARIABLES:
Added description and removed rest of header.

2024-01-22 03:52 UTC, jtruesdal commented on src/control/history_scam.F90
> +    call add_default ('CLAT1&IC',0,'I')
Done.  Thanks.

2024-01-22 03:53 UTC, jtruesdal commented on src/control/ncdio_atm.F90
> +    integer                   :: j         ! indice
fixed

2024-01-22 03:53 UTC, jtruesdal commented on src/control/ncdio_atm.F90
> +    integer                   :: j         ! indice
Fixed.

2024-01-22 03:53 UTC, jtruesdal commented on src/control/scamMod.F90
> +!jt	use commap,              only: latdeg, clat
Not an issue and removed these comments.

2024-01-22 03:53 UTC, jtruesdal commented on src/control/scamMod.F90
> +      write(6,*)'using column value of f12vmr from boundary data as global volume mixing ratio'
Fixed.

2024-01-22 03:53 UTC, jtruesdal commented on src/control/scamMod.F90
> +   if (status .ne. nf90_noerr) then
Updated to use F90 relational operators throughout the code.

2024-01-24 23:36 UTC, cacraigucar requested changes

2024-01-24 23:36 UTC, cacraigucar commented on src/dynamics/se/se_single_column_mod.F90
> +  if (.not. use_camiop .and. get_nstep() .eq. 0) then
Please use `==` instead of `.eq.`

2024-01-24 23:36 UTC, cacraigucar commented on src/dynamics/se/se_single_column_mod.F90
> +    if (get_nstep() .le. 1) then
Please use `<=` instead of `.le.`

2024-01-24 23:36 UTC, cacraigucar commented on src/dynamics/se/se_single_column_mod.F90
> +    if (get_nstep() .eq. 0) then
Another `.eq.` to update

2024-01-24 23:36 UTC, cacraigucar commented on src/dynamics/se/se_single_column_mod.F90
> +      call mpi_bcast(divq3d,nlev,mpi_real8,mstrid,mpicom,ierr)
The ierr should probably be checked after each of these mpi_bcast calls and the run halting if an error is detected

2024-01-24 23:36 UTC, cacraigucar commented on src/dynamics/se/se_single_column_mod.F90
> +               if (testval .lt. minpoint) then
A couple more `.lt.` which should be replaced with `<`

2024-01-24 23:36 UTC, cacraigucar commented on src/dynamics/eul/iop.F90
> +   ioptop=1
Is this still valid and if so, should it become a namelist?

2024-01-26 21:02 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +               if (testval .lt. minpoint) then
@cacraigucar I'll go through all the routines I touched and make the changes to relational operators.  Is it OK to change those lines which were not part of the original set of mods so as to leave the routine in an updated consistent state?  I will be making a short test as each file is changed to make sure that these mods don't introduce any additional changes.

2024-01-30 22:53 UTC, jtruesdal commented on Externals.cfg
> +repo_url = https://github.com/jtruesdal/CESM_share
@jedwards4b forgot to 'at' you on the previous question.  Repeating here:

>Tag name should be share1.0.17_scamdev. I had a few mods for shr_scam_mod that turned up in testing for this PR. If you can help with the mods for getting rid of MCT I'm happy to include them, test and create the PR to CESM_share. In the meantime I'll fix the tag reference above.

2024-01-30 23:10 UTC, jedwards4b commented on Externals.cfg
> +repo_url = https://github.com/jtruesdal/CESM_share
Sorry I haven't looked into it yet, I'll try to do it tomorrow.

2024-01-31 16:25 UTC, jedwards4b commented
@jtruesdal looking at this this morning, I don't see any tests of scam on the ne grid listed in the [cam/cime_config/testdefs/testlist_cam.xml](https://github.com/jtruesdal/CAM-1/blob/scam_dev_exp/cime_config/testdefs/testlist_cam.xml)  Can you please add at least one test and also tell me what compset and resolution I should try.

2024-01-31 16:51 UTC, jedwards4b commented
I tried test SMS.ne3pg3_ne3pg3_mg37.FSCAM.derecho_intel and ran into missing input data: 
```
Model cam missing file drydep_srf_file = '/glade/campaign/cesm/cesmdata/inputdata/atm/cam/chem/trop_mam/atmsrf_ne3np4.pg3_221214.nc'
Trying to download file: 'atm/cam/chem/trop_mam/atmsrf_ne3np4.pg3_221214.nc' to path '/glade/campaign/cesm/cesmdata/inputdata/atm/cam/chem/trop_mam/atmsrf_ne3np4.pg3_221214.nc' using SVN protocol.
svn export failed with output:  and errput svn: E170000: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/atm/cam/chem/trop_mam/atmsrf_ne3np4.pg3_221214.nc' doesn't exist


```

2024-02-01 13:50 UTC, jedwards4b commented
@jtruesdal I tried to run test SCT_D_Ln7.T42_T42_mg17.QPC6.derecho_intel.cam-scm_prep_c6 and SCT_D_P36_Ln7.T42_T42_mg17.QPC6.derecho_intel.cam-scm_prep_c6 and both fail with an mpi error.   Can you point me to an SCT test that runs on derecho - or izulme.

2024-02-01 15:20 UTC, jedwards4b commented
I also tried these tests on izumi and both fail.  I'm looking into the issue but where are the baselines and what tests have you run?

2024-02-01 18:12 UTC, jtruesdal commented
Thanks Jim.  You can hold for now, I see my SCT test failed also and am looking into it.

2024-02-20 04:24 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +! add (-) global mean total energy difference as heating
fixed.

2024-02-20 04:32 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +    endif
heat_glob is a private module variable and is set before this routine is called.  If this was a problem it would have showed up in the current regression testing as heat_glob is used elsewhere in this routine.

2024-02-20 04:32 UTC, jtruesdal commented on src/infrastructure/phys_grid.F90
> +               if (testpoint .lt. minpoint) then
Done.

2024-02-20 04:33 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +  if (.not. use_camiop .and. get_nstep() .eq. 0) then
.done.

2024-02-20 04:37 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +    if (get_nstep() .le. 1) then
done

2024-02-20 04:37 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +    if (get_nstep() .eq. 0) then
done

2024-02-20 04:37 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +               if (testval .lt. minpoint) then
done

2024-02-20 06:53 UTC, jtruesdal commented
Jim I merged and tested your share changes on Izumi and Derecho. I also corrected the SCAM testing and added new regression tests for SE SCAM.  The code is now up to cam6_3_147.

2024-02-20 06:58 UTC, jtruesdal commented on src/dynamics/eul/iop.F90
> +   ioptop=1
The repository SCAM code does not extrapolate forcing data outside the IOP pressure boundaries, filling those regions with 0's.  I've modified the code to fill these 0 regions with the background state from CAM.  I believe this is the proper behavior and I will remove this flag before committing the code.  For now it allows me to verify BFB results with the previous implementation.

2024-02-20 07:33 UTC, jtruesdal commented
>@jtruesdal looking at this this morning, I don't see any tests of scam on the ne grid listed in the [cam/cime_config/testdefs/testlist_cam.xml](https://github.com/jtruesdal/CAM-1/blob/scam_dev_exp/cime_config/testdefs/testlist_cam.xml) Can you please add at least one test and also tell me what compset and resolution I should try.

The 2 new regression tests are:  
SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC5.derecho_intel.cam-scm_prep
SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6

details:

    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 CREATE_NEWCASE
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 XML
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 SETUP
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 SHAREDLIB_BUILD time=308
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 MODEL_BUILD time=560
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 SUBMIT
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 RUN time=41
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 COMPARE_base_default
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 MEMLEAK insufficient data for memleak test
    PASS SCT_D_Ln7_Vnuopc.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 SHORT_TERM_ARCHIVER

I will remove the CAM5 test once the PR is approved.

2024-02-27 19:52 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +    endif
Regression testing aside I did some tracing and can't see how it could be unassigned.  Do see something I didn't catch?

2024-03-01 22:30 UTC, cacraigucar requested changes
These changes and the few unresolved ones are my final comments.

2024-03-05 20:15 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +! add (-) global mean total energy difference as heating
Reworked the if statement and updated the comments.

2024-03-05 20:15 UTC, jtruesdal commented on src/dynamics/eul/iop.F90
> +   ioptop=1
Thanks.  I will go through these comments before tagging and make sure its removed.  I do appreciate the extra set of eyes on this.

2024-03-05 20:15 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +          go to 1000
Rewrote this original E3SM code minloc intrinsic.  Thanks for the catch.

2024-03-05 20:15 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +          qobs(k)=elem(ie_scm)%state%qdp(i_scm,j_scm,k,1,tl_fqdp)/elem(ie_scm)%state%dp3d(i_scm,j_scm,k,tl_f)
Fixed and checking the rest of my changes for long lines.

2024-03-05 20:15 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata             hgrid="64x128"    nlev="32"       scam_iop="SAS"       >atm/cam/inic/gaus/CESM2.F2000climo.64x128.cam.i.0003-06-01-00000.nc</ncdata>
The IOPs are field programs that took place during specific months of the year.  The initial data files which specify background state should be consistent with the IOP run dates.  I double checked all the dates to make sure they match the base date of the IOP files.

2024-03-05 20:16 UTC, jtruesdal commented
Added the drydep file to the repo via rimport.

2024-03-08 00:09 UTC, cacraigucar requested changes

2024-03-08 00:09 UTC, cacraigucar commented on src/dynamics/eul/iop.F90
> +   ioptop=1
This too will need to be removed before I can give my final approval

2024-04-01 13:14 UTC, nusbaume requested changes
Great work!  I realize it looks like there are a ton of change requests, but most of them should either be trivial, or are just general questions.  Thanks!

2024-04-01 13:14 UTC, nusbaume commented on src/dynamics/se/se_single_column_mod.F90
> +    t_phys_frc(:)   = elem(ie_scm)%derived%fT(i_scm,j_scm,:)
Just double-checking that `t_phys_frc` doesn't need to be divided by `dt` as well?

2024-04-01 13:14 UTC, nusbaume commented on src/dynamics/se/se_single_column_mod.F90
> +      ! Purpose: When running DP-CRM, broadcast relevant logical
Should this say SCAM?

```suggestion
      ! Purpose: When running SCAM, broadcast relevant logical
```

2024-04-01 13:14 UTC, nusbaume commented on src/dynamics/se/se_single_column_mod.F90
> +      !----------------------------------------------------------
I don't think this comment block is correct (?).

2024-04-01 13:14 UTC, nusbaume commented on src/dynamics/se/se_single_column_mod.F90
> +         call endrun('Could not find closest SCM point on input datafile')
I might include the subroutine name in the `endrun` message here so that it is easier to find the source code if needed.

2024-04-11 04:59 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +  'num_a1', 'num_a2', 'num_a3', 'num_a4', 'pom_a1', 'pom_a4', 'so4_a1', 'so4_a2', 'so4_a3', 'soa_a1', 'soa_a2'
These are OK to define for everything but CAM4.  I don't know how to exclude CAM4 other than only defining these defaults for CAM5,6,DEV.

2024-04-19 18:02 UTC, jtruesdal commented on bld/config_files/definition.xml
> +Configure CAM for single column mode and specify an IOP.
Done.

2024-04-19 18:02 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata dyn="se" hgrid="ne3np4"   nlev="26"             ic_ymd="901" >atm/cam/inic/se/cami_0000-01-01_ne3np4_L26_c120525.nc</ncdata>
The naming for the date is consistent with the date of the file that they were directly interpolated from not the date they were created.  The creation date in the metadata is correct though.  I realize the naming is inconsistent with the current guide lines but there is a method to the madness and I would ask that they be allowed to remain as is especially since these files have been committed to the data repository already.

2024-04-19 18:03 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<ncdata             hgrid="ne3np4"    nlev="32"       scam_iop="atex"      >atm/cam/inic/se/CESM2.F2000climo.ne3np4.cam.i.0003-02-01-00000.nc</ncdata>
I've added those comments.  The information came from Andrew Gettleman's SCAM paper.

2024-04-19 18:07 UTC, jtruesdal commented on bld/namelist_files/namelist_defaults_cam.xml
> +<iopfile                                              scam_iop="camfrc"     >atm/cam/scam/iop/ARM97_4scam.nc</iopfile>
Just putting some reasonable defaults in there that the user can modify via usermods_dir.  I put in a comment speaking to that point.

2024-04-19 18:08 UTC, jtruesdal commented on bld/namelist_files/namelist_definition.xml
> +Default:
Done.

2024-04-19 18:10 UTC, jtruesdal commented on cime_config/SystemTests/sct.py
> +            self._case.set_value("CAM_CONFIG_OPTS","{} -scam camfrc ".format(CAM_CONFIG_OPTS))
Done.

2024-04-19 18:11 UTC, jtruesdal commented on cime_config/config_component.xml
> +      <value compset="_CAM.*%SCAMTOGA2">-scam user</value>
Good catch.  Thanks.

2024-04-19 18:12 UTC, jtruesdal commented on cime_config/config_compsets.xml
> +    <lname>2000_CAM60%SCAMCgilss6_CLM50%SP_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV</lname>
I changed it to uppercase.

2024-04-19 18:13 UTC, jtruesdal commented on cime_config/testdefs/testlist_cam.xml
> +    </options>
Done.

2024-04-19 18:13 UTC, jtruesdal commented on cime_config/testdefs/testlist_cam.xml
> +    </options>
Done.

2024-04-19 18:13 UTC, jtruesdal commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FSCAMARM97" grid="T42_T42" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s">
Done.

2024-04-19 18:14 UTC, jtruesdal commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FSCAMARM97" grid="T42_T42" name="SMS_D_Ln9_Vnuopc" testmods="cam/scam_mpace_outfrq9s">
Done.

2024-04-19 18:14 UTC, jtruesdal commented on cime_config/usermods_dirs/scam_mandatory/shell_commands
> +# Only change if CLM_FORCE_COLDSTART exists and dycore is eularian
Changed.

2024-04-19 18:15 UTC, jtruesdal commented on src/control/getinterpnetcdfdata.F90
> +   logical, intent(in)  :: scm_crm_mode  ! extrapolate the end values
Corrected the comment.

2024-04-19 18:18 UTC, jtruesdal commented on src/control/getinterpnetcdfdata.F90
> +   real(r8), intent(in) :: ps            ! dataset pressure levels
Corrected.

2024-04-19 18:19 UTC, jtruesdal commented on src/control/history_scam.F90
> +       call addfld ('LAM&IC',    horiz_only,  'I', ' ','lon for bfb testing', gridname=trim(outgrid))
Historical.  I'd have to look into what the ramifications of changing these would be.

2024-04-19 18:19 UTC, jtruesdal commented on src/control/history_scam.F90
> +       call addfld ('beta',    horiz_only,   'A', 'percent','Mass fixer',gridname=trim(outgrid))
Beta is an energy fixer coefficient and the comment was updated

2024-04-19 18:19 UTC, jtruesdal commented on src/control/history_scam.F90
> +    call addfld ('Ps',      horiz_only,   'A', 'Pa',     'Ps for scam',gridname=trim(outgrid))
Modified as recommended

2024-04-19 18:19 UTC, jtruesdal commented on src/control/history_scam.F90
> +      character(len=100) outgrid
Yes. Changed

2024-04-19 18:20 UTC, jtruesdal commented on src/control/history_scam.F90
> +    character(len=100) outgrid
Yes Changed.

2024-04-19 18:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +public :: plevs0              ! find index in iopboundary data for current time
Corrected.

2024-04-19 18:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +logical, public ::  have_heat_glob         = .false. ! dataset contains shflx
Yes changed as recommended

2024-04-19 18:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +real(r8), public              ::  scm_relax_bot_p       = -1.e36_r8 !  lower bound for scm relaxation
Range for top of model should be 0. While bottom can be huge. Changed

2024-04-19 20:10 UTC, jtruesdal commented on src/control/scamMod.F90
> +logical, public ::  scm_use_obs_qv         = .false. ! Use the SCAM-IOPobserved qv  at each time step instead of forecasting.
Changed to recommended comment

2024-04-19 20:11 UTC, jtruesdal commented on src/control/scamMod.F90
> +#endif
Nope

2024-04-19 20:13 UTC, jtruesdal commented on src/control/scamMod.F90
> +         if (masterproc) write(iulog,*) sub//':ERROR - readiopdata.F:Could not find dimension ID for time/tsec'
Implemented

2024-04-19 20:16 UTC, jtruesdal commented on src/control/scamMod.F90
> +         call endrun
Added.

2024-04-19 20:30 UTC, jtruesdal commented on src/control/scamMod.F90
> +   end if
Your correct and endrun is needed here.  There are only a few IOP variables that should result in an endrun when missing and dimension info is one of them.  Added endrun.

2024-04-19 20:31 UTC, jtruesdal commented on src/control/scamMod.F90
> +   allocate(dplevs(nlev+1))
The handle_ncerr does check the status return of the nf90 call and prints it.

2024-04-19 20:35 UTC, jtruesdal commented on src/control/scamMod.F90
> +   end if
Thanks this should be an endrun.

2024-04-19 22:15 UTC, jtruesdal commented on src/control/scamMod.F90
> +         return
I'll have to test these.  It does look like an error putting return in here as I agree we want the rest of the file to be processed.  All these variables are on the standard IOP which is maybe why it works correctly.

2024-04-19 22:16 UTC, jtruesdal commented on src/control/scamMod.F90
> +      return
This is an error.  There must be a mismatch with the units between the lev dimension and Ps.  I've called endrun and updated the error message.

2024-04-19 22:16 UTC, jtruesdal commented on src/control/scamMod.F90
> +!get global vmrs from camiop file
Yes. Changed

2024-04-19 22:16 UTC, jtruesdal commented on src/control/scamMod.F90
> +         return
Corrected logic and error messages.

2024-04-19 22:17 UTC, jtruesdal commented on src/control/scamMod.F90
> +         return
Corrected logic and error messages.

2024-04-19 22:17 UTC, jtruesdal commented on src/control/scamMod.F90
> +         return
Corrected logic and error messages.

2024-04-19 22:17 UTC, jtruesdal commented on src/control/scamMod.F90
> +   call shr_sys_flush( iulog )
Not that I can tell.  This looks old and probably was needed at sometime in the distant past.  I removed these flushes.

2024-04-19 22:19 UTC, jtruesdal commented on src/control/scamMod.F90
> +   return
Deleted

2024-04-19 22:19 UTC, jtruesdal commented on src/control/scamMod.F90
> +#endif
Nope. Deleted

2024-04-19 22:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +         call endrun(sub//':ERROR - setiopupdate.c:Reached the end of the time varient dataset')
Changed as recommended.

2024-04-19 22:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +   return
Deleted

2024-04-19 22:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +!-----------------------------------------------------------------------
Deleted.

2024-04-19 22:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +  integer k             ! Longitude, level indices
suggestion implemented

2024-04-19 22:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +  return
got rid of it.

2024-04-19 22:20 UTC, jtruesdal commented on src/control/scamMod.F90
> +  !-----------------------------------------------------------------------
Removed

2024-04-19 22:21 UTC, jtruesdal commented on src/control/scamMod.F90
> +  integer     latidx,lonidx,status,i
Updated.

2024-04-19 23:01 UTC, jtruesdal commented on src/control/scamMod.F90
> +      write(iulog,* ) 'ERROR - extractdata.F:Cant get dimension IDs for varid', varid
Made changes as recommended.  Also added endrun since this routine assumes that the variable was found and is returning a start count index.

2024-04-19 23:02 UTC, jtruesdal commented on src/control/scamMod.F90
> +   return
Removed

2024-04-19 23:02 UTC, jtruesdal commented on src/control/scamMod.F90
> +#endif
Nope

2024-04-19 23:02 UTC, jtruesdal commented on src/control/scamMod.F90
> +          write(iulog,*)'ERROR - setiopupdate.F:Cant get variable ID for bdate'
Yes. Added endrun calls with message.

2024-04-19 23:03 UTC, jtruesdal commented on src/control/scamMod.F90
> +       call endrun
done.

2024-04-19 23:05 UTC, jtruesdal commented on src/dynamics/se/advect_tend.F90
> +  ! and writes these to the camiop file
done.

2024-04-19 23:11 UTC, jtruesdal commented on src/dynamics/se/advect_tend.F90
> +      iop_ttendxyz_init = 0._r8
stat and err check done.

2024-04-19 23:11 UTC, jtruesdal commented on src/dynamics/se/advect_tend.F90
> +    ! save inital/calc tendencies on second call to this routine.
fixed

2024-04-19 23:11 UTC, jtruesdal commented on src/dynamics/se/advect_tend.F90
> +      out_ps = 0._r8
Added stat and endrun checks for all the allocates.

2024-04-19 23:12 UTC, jtruesdal commented on src/dynamics/se/apply_iop_forcing.F90
> +  real(r8), intent(in) :: q_phys_frc(plev,pcnst)  ! temperature forcing from physics [K/s]
Changed the comment to read ! Change in q due to physics.

2024-04-19 23:12 UTC, jtruesdal commented on src/dynamics/se/apply_iop_forcing.F90
> +  if ( scm_relaxation.and.scm_relax_linear ) then
Removed.  Thanks.

2024-04-19 23:12 UTC, jtruesdal commented on src/dynamics/se/apply_iop_forcing.F90
> +  !    prepare scm_relax_fincl for comparison in scmforecast.F90
It exists in the Eul dycore.  Removed the comment.

2024-04-19 23:12 UTC, jtruesdal commented on src/dynamics/se/apply_iop_forcing.F90
> +     if( scm_relaxation ) then
Right you are.  Removed the if check and reindented the code.

2024-04-19 23:13 UTC, jtruesdal commented on src/infrastructure/phys_grid.F90
> +      integer(iMap),          pointer     :: grid_map_scm(:,:)
The original phys_decomp works just as you described for the EUL dycore, 2d grid for CAM runs or 1d when run as SCAM where both the physics and dynamics are operating on identical grids.  The E3SM SE SCM design (which we are adopting here) has the SE dycore running on a global coarse ne3 grid while the physics is still run in a column and thus requires two grids to handle the physics and dycore.

2024-04-19 23:14 UTC, jtruesdal commented on src/utils/hybvcoord_mod.F90
> +module hybvcoord_mod
I will need to look into this.

2024-04-19 23:14 UTC, jtruesdal commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +         ! Loop over rsplit vertically lagrangian timesiteps
Done.

2024-04-19 23:15 UTC, jtruesdal commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +  enddo
Indeed.  Done.

2024-04-19 23:16 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +      call outfld('heat_glob',  heat_out(:ncol), pcols, lchnk)
This might be a diagnostic that Peter put in.  I'll check with him to see if it can be removed.

2024-04-19 23:16 UTC, jtruesdal commented on src/control/scamMod.F90
> +use netcdf,         only: NF90_NOERR,NF90_CLOSE,NF90_GET_VAR,NF90_INQUIRE_DIMENSION, &
The vast majority of SCAM has never been updated to use PIO and these changes use the NetCDF interface for consistency.  There is not a good reason to keep using NetCDF although making that happen isn't in the scope of this PR.  Its been on my personal TODO for awhile but I haven't had the time or funding to make it happen yet.

2024-04-19 23:16 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +    t_phys_frc(:)   = elem(ie_scm)%derived%fT(i_scm,j_scm,:)
It is correct.  t_phys_frc is derived from phys_tend$dtdt returned from physics and is already a tendency whereas the quantity carried in derived%fQ is the change in state due to the physics and not already a tendency.

2024-04-19 23:16 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +      ! Purpose: When running DP-CRM, broadcast relevant logical
Yes. Changed as recommended.

2024-04-19 23:17 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +      !----------------------------------------------------------
Corrected the comment.

2024-04-19 23:17 UTC, jtruesdal commented on src/dynamics/se/se_single_column_mod.F90
> +         call endrun('Could not find closest SCM point on input datafile')
Thanks.  I added the subroutine name

2024-04-19 23:18 UTC, jtruesdal commented on bld/build-namelist
> +    if ($cfg->get('scam_iop')) {
Yes.  Done.

2024-04-19 23:21 UTC, jtruesdal commented on cime_config/SystemTests/sct.py
> +            append_to_user_nl_files(caseroot = self._get_caseroot(), component = "cam", contents = "scale_dry_air_mass     = 0.0D0")
I had to put this in specifically to get the tests to pass but can't remember why the defaults were not being applied in this case.  I will double check though.

2024-04-19 23:25 UTC, jtruesdal commented on cime_config/usermods_dirs/scam_camfrc/user_nl_cam
> +scm_relax_tau_top_sec                = 172800.
These lines are here as an example for the user of what a typical set of values for modifying the relaxation algorithm.

2024-04-30 23:57 UTC, jtruesdal commented on src/control/scamMod.F90
> +      return
Removed.

2024-05-15 23:08 UTC, jtruesdal commented on cime_config/SystemTests/sct.py
> +            append_to_user_nl_files(caseroot = self._get_caseroot(), component = "cam", contents = "scale_dry_air_mass     = 0.0D0")
It does need to be specified.  Normally for a 3d run the default should be non-zero but in the special case of the bfb check we need to make a 3d run and the companion scam run both with the scale_dry_airmass set to 0.  The defaults to take care of the scam run but the 3d run needs the default overridden for this test.

2024-05-15 23:09 UTC, jtruesdal commented on cime_config/SystemTests/sct.py
> +            append_to_user_nl_files(caseroot = self._get_caseroot(), component = "cam", contents = "scale_dry_air_mass     = 0.0D0")
Same answer as above.

2024-07-02 14:52 UTC, jtruesdal commented on src/utils/hybvcoord_mod.F90
> +module hybvcoord_mod
There is a circular dependency that I don't see an easy way to fix.  I would like to commit this and will continue to look at this in the next set of SCAM mods.

2024-07-02 14:58 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +      call outfld('heat_glob',  heat_out(:ncol), pcols, lchnk)
This needs to be redefined as a single global value and not written out as a 2d field.  I will update this.

2024-07-02 19:22 UTC, cacraigucar requested changes

2024-07-02 19:22 UTC, cacraigucar commented on src/dynamics/eul/iop.F90
> +   ioptop=1
I believe this still needs to be removed

2024-07-02 19:22 UTC, cacraigucar commented on Externals.cfg
> +branch = cdeps1.0.24_scamdev
I tried to find the .gitmodules file and I am not finding it via this PR.  Did you forget to "git add" it when you removed the Externals.cfg?

2024-07-08 16:24 UTC, jtruesdal commented
@cacraigucar I removed the bfb testing line and updated to cam6_4_006 for diagnostic testing.

2024-07-08 19:41 UTC, cacraigucar commented on Externals.cfg
> +branch = cdeps1.0.24_scamdev
I agree that all the externals you needed to have updated have independently been done in CAM already, so changes for externals are no longer expected.

2024-07-08 19:41 UTC, cacraigucar approved these changes

2024-07-12 04:00 UTC, nusbaume requested changes
Almost there!  Just a few final minor requests and one missed request from last time.

2024-07-12 04:00 UTC, nusbaume commented on src/dynamics/se/advect_tend.F90
> +      if (ierr/=0) call endrun( sub//': not able to allocate ipo_qtendxyz' )
Typo here (`ipo_qtendxyz` -> `iop_qtendxyz`).

2024-07-12 04:00 UTC, nusbaume commented on src/physics/cam/check_energy.F90
> +      call outfld('heat_glob',  heat_out(:ncol), pcols, lchnk)
It looks like this still needs to be updated?

2024-08-06 03:32 UTC, jtruesdal commented on src/physics/cam/check_energy.F90
> +      call outfld('heat_glob',  heat_out(:ncol), pcols, lchnk)
It's turning out to be more difficult to add this back in as a global and will require pretty extensive changes in addition to restructuring due to a circular dependency.  I would ask to leave it as is for this commit.  It's currently consistent with the way global values were treated by SCAM using the EUL dycore. The global value is written at each lat/lon point and the entire surface field is written to the CAM IOP file. (This is why an ncol array is created and written out). The SCAM physgrid definition only contains 1 column and the appropriate global value is read from the user chosen column.

2024-08-06 03:33 UTC, jtruesdal commented on src/control/scamMod.F90
> +  character(len=256) :: dim_name
Added DOI and shr_kind_cl

2024-08-06 03:33 UTC, jtruesdal commented on src/dynamics/se/advect_tend.F90
> +      if (ierr/=0) call endrun( sub//': not able to allocate ipo_qtendxyz' )
corrected typo

2024-08-06 03:35 UTC, jtruesdal commented
It's turning out to be more difficult to write heat_glob as a global and will require pretty extensive changes in addition to restructuring due to a circular dependency. I would ask to leave it as is for this commit. It's currently consistent with the way global values were treated by SCAM using the EUL dycore. The global value is written at each lat/lon point and the entire surface field is written to the CAM IOP file. (This is why an ncol array is created and written out). The SCAM physgrid definition only contains 1 column and the appropriate global value is read from the user chosen column.

2024-08-11 19:46 UTC, nusbaume commented on src/physics/cam/check_energy.F90
> +      call outfld('heat_glob',  heat_out(:ncol), pcols, lchnk)
@jtruesdal Thanks for the explanation!  I am happy to leave this as-is then (at least for now), especially if it is that much effort to implement for arguably minimal gain.

2024-08-11 19:47 UTC, nusbaume approved these changes
Everything looks great to me now.  Thanks @jtruesdal!

2024-08-26 13:47 UTC, jtruesdal commented
> @jtruesdal I tried to run test SCT_D_Ln7.T42_T42_mg17.QPC6.derecho_intel.cam-scm_prep_c6 and SCT_D_P36_Ln7.T42_T42_mg17.QPC6.derecho_intel.cam-scm_prep_c6 and both fail with an mpi error. Can you point me to an SCT test that runs on derecho - or izulme.

@jedwards4b I see that I forgot to address your question about failing SCT tests.  I did correct the error and the tests are running now on both Derecho and Izumi.  The is a baseline difference due to a bug fix for SCAM.  I'm asking for a re-review to clear this issue so I can proceed with the PR.  If you would like to look at the Derecho and Izumi tests they are:
/scratch/cluster/jet/aux_cam_gnu_20240826004033
/scratch/cluster/jet/aux_cam_nag_20240826004050
/glade/derecho/scratch/jet/aux_cam_intel_20240826003035

2024-08-26 14:30 UTC, merged