Update CLUBB and SILHS externals
ESCOMP/CAM pull request #960
Opened 2024-01-12 23:11 UTC by Katetc

New code with some adjustments for the TAUs tuning options. 

Could be a place to address or discuss #953

Possibly another UWM CLUBB branch tag coming in the next week or so, but no changes to CAM code will be required for that, so we should be able to start the code reviews now. This does change answers for all CAM6 and cam_dev compsets. I am building diagnostics for a short comparison run now. I will edit this PR with a link when I'm done.

@bstephens82 would be good to keep abreast here.

Closes #956

2024-01-16 17:45 UTC, bstephens82 commented
Based on the diagnostics, which are very similar before and after, I would guess the differences are due only to order-of-operations changes.  I am checking with @vlarson to make sure that's right.  There are physics changes in the taus code with this new external, but those should not appear in the tests if clubb_l_diag_Lscale_from_tau=F, as it is on the trunk.

2024-01-16 18:20 UTC, vlarson commented
> Based on the diagnostics, which are very similar before and after, I would guess the differences are due only to order-of-operations changes. I am checking with @vlarson to make sure that's right. There are physics changes in the taus code with this new external, but those should not appear in the tests if clubb_l_diag_Lscale_from_tau=F, as it is on the trunk.

Which two CLUBB tags are showing differences?

2024-01-16 18:26 UTC, bstephens82 commented
> > Based on the diagnostics, which are very similar before and after, I would guess the differences are due only to order-of-operations changes. I am checking with @vlarson to make sure that's right. There are physics changes in the taus code with this new external, but those should not appear in the tests if clubb_l_diag_Lscale_from_tau=F, as it is on the trunk.
> 
> Which two CLUBB tags are showing differences?

I believe it's just the previous tag, 

clubb_4ncar_20221129_59cb19f_20230330_branchtag

versus the newer tag from 11-15-23:

clubb_4ncar_20231115_5406350

2024-01-16 18:41 UTC, vlarson commented
> > > Based on the diagnostics, which are very similar before and after, I would guess the differences are due only to order-of-operations changes. I am checking with @vlarson to make sure that's right. There are physics changes in the taus code with this new external, but those should not appear in the tests if clubb_l_diag_Lscale_from_tau=F, as it is on the trunk.
> > 
> > 
> > Which two CLUBB tags are showing differences?
> 
> I believe it's just the previous tag,
> 
> clubb_4ncar_20221129_59cb19f_20230330_branchtag
> 
> versus the newer tag from 11-15-23:
> 
> clubb_4ncar_20231115_5406350

If the comparison is between the newer tag and a tag as old as 2022-11-29, then yes, there are round-off level code changes, such as

https://github.com/larson-group/clubb_release/commit/711714c6821efc75febabf0434b52a814b32a40b

It sounds like Kate's comparison runs are demonstrating that there are no bigger changes than round off.

2024-01-20 16:15 UTC, nusbaume requested changes
Looks good, but I do have some questions and (hopefully minor) change requests.

2024-01-20 16:15 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +      allocate( stats_zt(j)%z( stats_zt(j)%kk ) )
Add `stat` checks here and below?

2024-01-20 16:15 UTC, nusbaume commented on src/physics/cam/clubb_intr.F90
> +
Do these three `addfld` loops also need the `max_fieldname_len` check done for the `stats_zt` and `stats_zm` variables above?

2024-01-22 15:20 UTC, bstephens82 requested changes

2024-01-22 15:20 UTC, bstephens82 commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> -'wpthlp_mfl_max', 'wprtp_mfl_min', 'wprtp_mfl_max', 'Richardson_num', 'shear_sqd',
In the new CLUBB code, Richardson_num has been renamed Ri_zm.  Is there a reason it's not being included here?

2024-01-22 15:20 UTC, bstephens82 commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> -'wpthlp_mfl_max', 'wprtp_mfl_min', 'wprtp_mfl_max', 'Richardson_num', 'shear_sqd'
Ditto.

2024-01-22 15:20 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +                              stats_rad_zt(:), stats_rad_zm(:))
I don't know if you can answer this offhand @Katetc, but I think this is where I ran into issues both after the first timestep (I think) and with restarts (I know).  It seems like in the previous version (I mean prior to this new external), basically the model had to have these "if first call" statements that would prevent it from calling stats_init_zt if not needed.  Are those no longer necessary?  It seems they aren't, but I guess I'm just wondering why?  From what I can tell, stats_init_clubb is inside clubb_ini_cam, which is inside phys_init, which is inside cam_init, which presumably would only be called at the beginning of a run, or maybe at the beginning of a restart run too.  Anyway it gave me problems without that "if first call" stuff, and I'm just curious why you didn't run into that problem, if you have any understanding of that. Thanks!

2024-01-31 20:29 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +                              stats_rad_zt(:), stats_rad_zm(:))
HI Ben, thanks for making a note of this and sticking with the question. I ran the aux_cam suite with the new external and code here and all of the exact restart tests passed base-rest comparisons, so I thought this was fine. However, only one test in the aux_cam suite includes clubb_stat output and that's a SILHS smoke test. When I re-ran that test today as an exact restart, it failed the base-rest comparison. So, without the "if first call" code, all of the cam history can exactly restart, but the clubb stats history cannot. I'll add it back in, and I'd like to add a test to the aux_cam suite that includes an exact restart with clubb_stat history.

2024-01-31 20:31 UTC, bstephens82 commented on src/physics/cam/clubb_intr.F90
> +                              stats_rad_zt(:), stats_rad_zm(:))
Ah, interesting!  That explains why I ran into it right away, since I usually include the clubb stats in my tests.

2024-01-31 20:37 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +                              stats_rad_zt(:), stats_rad_zm(:))
@Katetc - Instead of adding an aux_cam test, could you just add the clubb stats to an already existing test?

2024-03-01 20:54 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_bv_efold                         silhs="1" > 5.0     </clubb_bv_efold>
Agree. Removed.

2024-03-01 20:56 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +    if (ierr /= 0) call endrun(sub//": FATAL: mpi_bcast: clubb_z_displace")
Yep. Added a bunch of mpi_bcast calls below this one

2024-03-01 20:57 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +         allocate(out_radzm(pcols,pverp,stats_rad_zm(1)%num_output_fields))
Added them

2024-03-01 21:01 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +        rtm_integral_vtend(i) = rtm_integral_vtend(i) + ptend_loc%q(i,k,ixq)*state1%pdel(i,k)/gravit
Moved them to after the loop.

2024-03-01 21:05 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +                          'model.in file.'
Updated the error to remove the reference to model.in

2024-03-01 21:06 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +         call endrun ("stats_init_clubb:  number of zt statistical variables exceeds limit")
I'm not exactly sure, but to be safe, I updated all of the errors to set l_error and call endrun

2024-03-01 21:08 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +      allocate( stats_zt(j)%z( stats_zt(j)%kk ) )
Sure, added them.

2024-03-01 21:11 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +
Sure, I added it in

2024-03-01 21:21 UTC, Katetc commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> -'wpthlp_mfl_max', 'wprtp_mfl_min', 'wprtp_mfl_max', 'Richardson_num', 'shear_sqd',
I added it in and it was full of random large numbers that failed the exact restart, so I am going to remove it from this test. Validated by Vince via email.

2024-03-01 21:22 UTC, Katetc commented on cime_config/testdefs/testmods_dirs/cam/silhs/user_nl_cam
> -'wpthlp_mfl_max', 'wprtp_mfl_min', 'wprtp_mfl_max', 'Richardson_num', 'shear_sqd'
Removed Richardson_num and ri_zm to fix exact restart test.

2024-03-01 23:28 UTC, cacraigucar requested changes
Mainly documentation clarifications for the namelists.  Since these go into the CAM namelist web page, they need to be informative for users.

2024-03-01 23:28 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_metadata)
With these threading directives, I'm just confirming that at least one of our tests which run CLUBB turns on OMP threading, so we can make sure it works.  I would assume so.

2024-03-07 19:47 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +                              stats_rad_zt(:), stats_rad_zm(:))
Added them to the mg3 test which is only called twice, as far as I can see, so they are in there now, but not too much.

2024-03-08 00:19 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +       group="clubb_params_nl" valid_values="" >
Updated the description to include:

> Selected option for the two-component normal (double Gaussian) PDF type to use for the w, rt,           
> and theta-l (or w, chi, and eta) portion of CLUBB's multivariate, two-component PDF.                    
> iiPDF_ADG1 = 1 (ADG1 PDF), iiPDF_ADG2 = 2 (ADG2 PDF), iiPDF_3D_Luhar = 3 (3D Luhar PDF),                
> iiPDF_new = 4 (new PDF), iiPDF_TSDADG = 5 (TSDADG PDF), iiPDF_LY93 = 6 (Lewellen and Yoh (1993)),       
> iiPDF_new_hybrid = 7 (new hybrid PDF)

2024-03-08 00:20 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Include the contribution of radiation to thlp2
Yeah, these should have been included in namelist_defaults, so I just updated there. I don't love putting defaults in the definitions file any more because 1, they can be hard to keep up to date and 2, people keep asking me to remove them in reviews. :)

2024-03-08 00:21 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +TKE = 1/2 (u'^2 + v'^2 + w'^2)
Updated the description to:
> Use anisotropic turbulent kinetic energy in the CLUBB higher order closure, i.e. 
> calculate TKE = 1/2 (u'^2 + v'^2 + w'^2). This improves the simulation of complex 
> turbulence but at a greater cost than running without.

2024-03-08 00:22 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +For wind speed nudging.
Updated to
> Turn on (true) or off (false) uv wind speed nudging.

2024-03-08 00:22 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +For rtm nudging
Updated to
> Turn on (true) and off (false) rtm nudging.

2024-03-08 00:24 UTC, Katetc commented on bld/namelist_files/namelist_definition.xml
> +Divides Kh_N2_zm by a stability factor
Updated to
> Whether or not we want CLUBB to apply a stability correction Kh_N2_zm.
It's not a fixed correction, it's an algorithmic adjustment, but I'm not sure how to convey that beyond the above.

2024-03-12 19:21 UTC, adamrher requested changes
Hi Kate. My only comments are on the new CAM namelists. I have a specific question about the ```clubb_l_diffuse_rtm_and_thlm``` namelist below. But for the others, I want to confirm whether any of these are turning on new features that weren't on in the old external, or changing the value of parameters w.r.t the old external).

These are new logical namelists:
```
<clubb_l_calc_thlp2_rad > .true. </clubb_l_calc_thlp2_rad>
<clubb_l_fix_w_chi_eta_correlations > .true. </clubb_l_fix_w_chi_eta_correlations>
<clubb_l_tke_aniso > .true. </clubb_l_tke_aniso>
<clubb_l_upwind_xm_ma > .true. </clubb_l_upwind_xm_ma>
<clubb_l_use_precip_frac > .true. </clubb_l_use_precip_frac>
```
(These are only the new ones that were added and set to .true.. Ignoring the .false. ones).

Here are the other non-logicals:
```
<clubb_bv_efold > 5.0 </clubb_bv_efold>
<clubb_wpxp_Ri_exp                                > 0.5     </clubb_wpxp_Ri_exp>
<clubb_z_displace                                 > 25.0    </clubb_z_displace>
```

2024-03-13 21:00 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_diffuse_rtm_and_thlm                     > .false. </clubb_l_diffuse_rtm_and_thlm>
`l_diffuse_rtm_and_thlm` should be set to false.  It is different than `clubb_l_do_expldiff_rtm_thlm`.

2024-03-13 21:30 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_diffuse_rtm_and_thlm                     > .false. </clubb_l_diffuse_rtm_and_thlm>
Thanks Vince. Can you provide a one sentence description of what it does do, so we can update the namelist_definitions.xml entry?

```
<entry id="clubb_l_diffuse_rtm_and_thlm" type="logical" category="pblrad"
       group="clubb_params_nl" valid_values="" >
Diffuses rtm and thlm
</entry>
```

And here's what the expldiff entry looks like:

```
<entry id="clubb_l_do_expldiff_rtm_thlm" type="logical"  category="pblrad"
       group="clubb_params_nl" valid_values="" >
Explicit diffusion on temperature and moisture by CLUBB, in addition to CLUBB's
normal prognostic equations for rtm and thlm.
</entry>
```

2024-03-14 15:14 UTC, nusbaume approved these changes
All of my concerns have been resolved now.  Thanks!

2024-03-14 18:16 UTC, vlarson commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_diffuse_rtm_and_thlm                     > .false. </clubb_l_diffuse_rtm_and_thlm>
How about "Implicit diffusion on moisture and temperature, implemented within CLUBB's matrix equations for wprtp/rtm and wpthlp/thlm."?

2024-03-14 18:47 UTC, adamrher commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_diffuse_rtm_and_thlm                     > .false. </clubb_l_diffuse_rtm_and_thlm>
That sounds good to me.

2024-03-14 22:48 UTC, cacraigucar reviewed
Still have my question about threading

2024-03-14 22:48 UTC, cacraigucar commented on bld/namelist_files/namelist_definition.xml
> +Include the contribution of radiation to thlp2
Thanks.  I agree that setting them in namelist_defaults is the best way to address this.

2024-03-28 19:18 UTC, Katetc commented on bld/namelist_files/namelist_defaults_cam.xml
> +<clubb_l_diffuse_rtm_and_thlm                     > .false. </clubb_l_diffuse_rtm_and_thlm>
Updated the description of clubb_l_diffuse_rtm_and_thlm to Vince's suggestion

2024-03-28 19:21 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_metadata)
Hi Cheryl, unfortunately I can't find an aux_cam test that includes multiple threads. Chris has confirmed that no alpha tests include threading the the beta tests that do are simple and do not test cam. Running a PET test that uses 2 threads on Derecho causes the current code on cam_development to crash. So, we may need another issue to address threading problems.

2024-03-28 19:44 UTC, Katetc commented
> Hi Kate. My only comments are on the new CAM namelists. I have a specific question about the `clubb_l_diffuse_rtm_and_thlm` namelist below. But for the others, I want to confirm whether any of these are turning on new features that weren't on in the old external, or changing the value of parameters w.r.t the old external).
> 
> These are new logical namelists:
> 
> ```
> <clubb_l_calc_thlp2_rad > .true. </clubb_l_calc_thlp2_rad>
> <clubb_l_fix_w_chi_eta_correlations > .true. </clubb_l_fix_w_chi_eta_correlations>
> <clubb_l_tke_aniso > .true. </clubb_l_tke_aniso>
> <clubb_l_upwind_xm_ma > .true. </clubb_l_upwind_xm_ma>
> <clubb_l_use_precip_frac > .true. </clubb_l_use_precip_frac>
> ```
> 
> (These are only the new ones that were added and set to .true.. Ignoring the .false. ones).
> 
> Here are the other non-logicals:
> 
> ```
> <clubb_bv_efold > 5.0 </clubb_bv_efold>
> <clubb_wpxp_Ri_exp                                > 0.5     </clubb_wpxp_Ri_exp>
> <clubb_z_displace                                 > 25.0    </clubb_z_displace>
> ```

I checked that the logicals were all set to the same values in the previous external. The new non-logicals didn't exist in the previous tag, so there's nothing to compare them too. To see the impacts from this new external, there's comparison diagnostics here: https://webext.cgd.ucar.edu/F2000climo/newCLUBBtesting/larson_tag_20231115.katemerge.011124-1252.F2000dev.f09_f09_mg17_1_2_vs_larson_tag_control.cam6_3_145.011124-1252.F2000dev.f09_f09_mg17_1_2/

2024-03-28 19:51 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_metadata)
I am currently trying an FV threaded test.  Either it will work (and we can test whether these directives are needed and I'll be introducing a regression test in my current PR) or it fails in which case I'll be opening another issue in ESCOMP/CAM.  (The SE dycore appears to be a known failure based on the issue I just opened)

2024-03-29 20:51 UTC, cacraigucar requested changes

2024-03-29 20:51 UTC, cacraigucar commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_metadata)
I ran the ERP_D_Ln9_P64x2.f09_f09_mg17.QSC6.derecho_intel.cam-outfrq9s both with and without these !$omp threadprivate directives.  As I suspected, it appears we do not need these directives.  (The ERP test passed and the h0i and h0a files were identical between the runs with and without them).   I would suggest you remove these directives, unless you know of a reason why you think they should remain.  

Just a reminder to modify the one CAM regression test to turn on the threading.

2024-03-29 23:29 UTC, Katetc commented on src/physics/cam/clubb_intr.F90
> +!$omp threadprivate(stats_metadata)
Thanks so much for your help here, Cheryl! I have removed the threadprivate directives and modified your suggested test to include threading.

2024-03-29 23:58 UTC, bstephens82 commented
> Based on the diagnostics, which are very similar before and after, I would guess the differences are due only to order-of-operations changes.  I am checking with @vlarson to make sure that's right.  There are physics changes in the taus code with this new external, but those should not appear in the tests if clubb_l_diag_Lscale_from_tau=F, as it is on the trunk.

Resolved.

2024-04-02 00:37 UTC, cacraigucar approved these changes

2024-04-12 21:34 UTC, merged