"Science optimize" SE-CSLAM dycore and stabilize WACCM
ESCOMP/CAM pull request #968
Opened 2024-01-30 18:14 UTC by PeterHjortLauritzen

Increase computational throughput of the SE-CSLAM dynamical core by:

 - Reducing se_nsplit to 2 (from 3) in FMT: CSLAM now runs with ~30% longer time-step compared to baseline
 - No double advection of thermodynamic active tracers when using CSLAM. Overwrite GLL values of Q, CLDLIQ,
   etc. every vertical remapping time-step with CSLAM values (interpolated from physics grid to GLL grid)
 - Vertical sponge layer diffusion in physics for WACCM and WACCM-x
 - No increased hyperdiffusion in sponge for FLT and FMT

Provide stable configuration for WACCM with spectral-elements (ne30pg3 and ne16pg3): namelist changes

Resolve qneg issue https://github.com/ESCOMP/CAM/issues/864
Resolve issue https://github.com/ESCOMP/CAM/issues/552 (read in topo file on GLL grid if available)
Resolve issue https://github.com/ESCOMP/CAM/issues/951 (remove namelist defaults for pg4 grids)

2024-02-10 04:32 UTC, nusbaume requested changes
Looks good, but I did have some small suggestions and a few questions.

2024-02-10 04:32 UTC, nusbaume commented on src/dynamics/se/dyn_comp.F90
> +   if (allocated(phis_phys_tmp)) then
It looks like the `phis_phys_tmp` variable is no longer used anymore after the `map_phis_from_physgrid_to_gll` call above.  Maybe it makes sense to simply deallocate the variable right after that call instead of down here?  That way we can also get rid of the `allocated` check being done here (as the variable will always have to be allocated).

2024-02-10 04:32 UTC, nusbaume commented on src/dynamics/se/dyn_grid.F90
>        if (fv_nphys > 0) then
Use `use_cslam` here?

```suggestion
      if (use_cslam) then
```

2024-02-10 04:32 UTC, nusbaume commented on src/physics/cam/vertical_diffusion.F90
> +        write(iulog,*)'vertical diffusion coefficient at interface 6 is increased by 0.1E6 m^2/s2'
I might vote to remove the `^` symbol here since it isn't being used in the denominator.  Plus we can make it better match CCPP unit text:

```suggestion
        write(iulog,*)'Artificial sponge layer vertical diffusion added:'
        write(iulog,*)'vertical diffusion coefficient at interface 1 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 2 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 3 is increased by 0.5E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 4 is increased by 0.1E6 m2 s-2'
     else if (ptop_ref>1e-4_r8) then
        !
        ! WACCM and WACCM-x
        !
        write(iulog,*)'Artificial sponge layer vertical diffusion added:'
        write(iulog,*)'vertical diffusion coefficient at interface 1 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 2 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 3 is increased by 1.5E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 4 is increased by 1.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 5 is increased by 0.5E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 6 is increased by 0.1E6 m2 s-2'
```

2024-02-10 04:32 UTC, nusbaume commented on src/physics/cam/vertical_diffusion.F90
> +     !
I might vote to remove these checks because they don't appear to be doing anything.

2024-02-14 15:44 UTC, nusbaume commented on src/dynamics/se/dycore/global_norms_mod.F90
> +      ! low top (~10 Pa)
@PeterHjortLauritzen it would be good for you to double-check this.  Thanks!

2024-02-15 00:14 UTC, fvitt commented on doc/ChangeLog
> +List all existing files that have been modified, and describe the changes:
Please include the changes you have in cime_config scripts.

2024-02-16 19:53 UTC, fvitt requested changes
Here are some initial comments

2024-02-16 19:53 UTC, fvitt commented on src/dynamics/se/dycore/global_norms_mod.F90
>      end if
This section could be shortened to something like:
```
    if (sponge_del4_lev       <0) sponge_del4_lev        = 1
    if (sponge_del4_nu_fac    <0) sponge_del4_nu_fac     = 1.0_r8
    if (sponge_del4_nu_div_fac<0) sponge_del4_nu_div_fac = 1.0_r8

    if (top_090_140km.or.top_140_600km) then ! defaults for waccm(x)
      if (sponge_del4_lev       <0) sponge_del4_lev        = 20
      if (sponge_del4_nu_fac    <0) sponge_del4_nu_fac     = 5.0_r8
      if (sponge_del4_nu_div_fac<0) sponge_del4_nu_div_fac = 10.0_r8
    end if

    ! set max wind speed for diagnostics
    umax = 120.0_r8
    if (top_042_090km) then
       umax = 240._r8
    else if (top_090_140km) then
       umax = 300._r8
    else if (top_140_600km) then
       umax = 800._r8
    end if

```

2024-02-16 19:53 UTC, fvitt commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +   else
Fix indentation

2024-02-17 20:20 UTC, nusbaume commented on src/dynamics/se/dycore/fvm_mapping.F90
> +   subroutine cslam2gll(elem, fvm, hybrid,nets,nete, tl_f, tl_qdp)
@PeterHjortLauritzen If you can provide me a text description of what this subroutine is doing then I can add it to my code review updates.  Thanks!

2024-02-17 20:22 UTC, nusbaume commented on src/dynamics/se/dycore/fvm_mapping.F90
> +    logical, optional    , intent(in)    :: halo_filled
@PeterHjortLauritzen if you can provide a descripton for what `halo_filled` does then I can add it to the PR.  Thanks!

2024-02-19 17:31 UTC, PeterHjortLauritzen commented on bld/namelist_files/namelist_definition.xml
> +</entry>
There might. Hence I would prefer to keep integer.

2024-02-19 17:45 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/fvm_mapping.F90
> +     allocate(llimiter(nflds))
done

2024-02-19 17:48 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +      ! low top (~10 Pa)
Code correct. Changed comments.

2024-02-19 18:04 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_comp.F90
>           if (fv_nphys == 0) then
sure ... also changed in other places in dyn_comp.F90 for consistency!

2024-02-19 18:07 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_grid.F90
>        if (fv_nphys > 0) then
done

2024-02-19 18:12 UTC, PeterHjortLauritzen commented on src/dynamics/se/dyn_comp.F90
> +   if (allocated(phis_phys_tmp)) then
sure

2024-02-19 18:18 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/fvm_mapping.F90
> +    logical, optional    , intent(in)    :: halo_filled
sure

2024-02-19 18:23 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/fvm_mapping.F90
> +   subroutine cslam2gll(elem, fvm, hybrid,nets,nete, tl_f, tl_qdp)
done

2024-02-19 18:27 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
>      end if
new code adopted. thanks

2024-02-19 18:30 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/prim_driver_mod.F90
> +   else
done

2024-02-19 18:31 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/global_norms_mod.F90
> +    umax = 0.0_r8
done (fixed in Francis's code suggestion)

2024-02-19 18:35 UTC, PeterHjortLauritzen commented on src/physics/cam/vertical_diffusion.F90
> +     !
OK. Removed.

2024-02-19 18:36 UTC, PeterHjortLauritzen commented on doc/ChangeLog
> +List all existing files that have been modified, and describe the changes:
@nusbaume can you do this?

2024-02-19 18:39 UTC, PeterHjortLauritzen commented
@nusbaume and @fvitt: thank you for the code review. I believe I have addressed your comments/concerns.

2024-02-22 22:44 UTC, nusbaume approved these changes
Everything now looks good to me!

2024-02-22 22:44 UTC, nusbaume commented on doc/ChangeLog
> +List all existing files that have been modified, and describe the changes:
The `ChangeLog` should be fully updated now.  Thanks!

2024-02-22 22:59 UTC, fvitt requested changes
Looking good. Just a couple more things.

2024-02-22 22:59 UTC, fvitt commented on src/physics/cam/vertical_diffusion.F90
> +     kvm(:ncol,6) = kvm(:ncol,6)+0.1E6_r8
You have these parameters definded in 2 places.  Here and in the log output in the init routine.  Can these be defined in 1 place, such as parameters global to this module?   If we need to adjust these parameters the changes can be done in 1 place.

2024-02-23 21:17 UTC, PeterHjortLauritzen commented on src/dynamics/se/dycore/fvm_mapping.F90
> +      allocate(llimiter(nflds), stat=ierr)
good catch; 3. Fixed

2024-02-23 23:05 UTC, fvitt requested changes
1 more request

2024-02-23 23:05 UTC, fvitt commented on src/physics/cam/vertical_diffusion.F90
> +     if (maxval(kvm_sponge(:))>0.0_r8) then
Should check if `kvm_sponge` is allocated
```suggestion
     if (allocated(kvm_sponge)) then
```

2024-02-27 15:32 UTC, nusbaume commented on src/physics/cam/vertical_diffusion.F90
> +     if (maxval(kvm_sponge(:))>0.0_r8) then
Good call!  I have added the `allocated` check as well as an `endrun` statement in the off chance the variable is never allocated (as it will fail downstream in that case).

@PeterHjortLauritzen just FYI.

2024-02-27 17:40 UTC, nusbaume commented
@fvitt Sorry, I understand your concern now!  The variable `kvm_sponge` is now only allocated when it is actually being used, with the appropriate `allocated()` checks to make sure it doesn't break something if it hasn't been allocated.

2024-02-27 18:06 UTC, fvitt approved these changes
Looks good to me now.  Thanks.

2024-03-22 21:16 UTC, merged