Update FV3 and FMS externals; Add new FV3 interface external; Now pulling FV3 from GFDL
ESCOMP/CAM pull request #983
Opened 2024-02-29 20:54 UTC by jtruesdal

- Update FV3 to allow syncing FMS version with CESM
 - ditch NCAR fork of FV3 in favor of pulling in library code from GFDL
 - Clean up FV3 makefile

2024-04-12 21:36 UTC, cacraigucar requested changes

2024-04-12 21:36 UTC, cacraigucar commented on doc/ChangeLog
> +	- removed this from CAM and moved new fv3 Makefile to FV3_CAM_INTERFACE external
No need to repeat these deleted files here

2024-04-12 21:36 UTC, cacraigucar commented on doc/ChangeLog
> +	stepon.F90
Please use the full path on each of these files

2024-04-12 21:36 UTC, cacraigucar commented on doc/ChangeLog
> + - Closes issue #950
Could you include the title text for #950 as well, please?

2024-04-14 21:23 UTC, nusbaume requested changes
Great clean-up!  I did have some hopefully minor change requests and a few questions though.

2024-04-14 21:23 UTC, nusbaume commented on cime_config/buildlib
> +                        stat, _, err = run_cmd("{} {} {} {}".format(fmsbuildlib, fmsbuildroot, fmsinstallpath, caseroot), verbose=True)
I would make this an f-string here:

```suggestion
                        stat, _, err = run_cmd(f"{fmsbuildlib} {fmsbuildroot} {fmsinstallpath} {caseroot}", verbose=True)
```

2024-04-14 21:23 UTC, nusbaume commented on cime_config/buildlib
> +                    if not os.path.exists(fmsbuildlib):
Where is `fmsbuildlib` defined?  I can't seem to find that variable anywhere in CAM's `buildlib` script (but maybe I am just not seeing it).

2024-04-14 21:23 UTC, nusbaume commented on cime_config/buildlib
> +                        expect(stat==0, "FMS build Failed {}".format(err))
I think this can be an f-string here:

```suggestion
                        expect(stat==0, f"FMS build Failed {err}")
```

2024-04-14 21:23 UTC, nusbaume commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="gnu" category="aux_cam"/>
Could we also add a `<option name="comment">` tag to this test with a short description of what this test is for?  For example `CAM6-FV3 aquaplanet exact restart test`.

2024-04-14 21:23 UTC, nusbaume commented on doc/ChangeLog
> +  ERP_Ln9.C96_C96_mg17.F2000climo.derecho_intel.cam-outfrq9s_mg3 (Overall: PEND) details:
Just double-checking that this FV3 test is still supposed to be failing?

2024-04-16 16:44 UTC, jtruesdal commented on doc/ChangeLog
> +	- removed this from CAM and moved new fv3 Makefile to FV3_CAM_INTERFACE external
Removed.

2024-04-16 16:44 UTC, jtruesdal commented on doc/ChangeLog
> +	stepon.F90
Added full path and added 2 more files that were removed but were missed here.

2024-04-16 16:44 UTC, jtruesdal commented on doc/ChangeLog
> + - Closes issue #950
Added the title text.

2024-04-16 16:44 UTC, jtruesdal commented on cime_config/buildlib
> +                        stat, _, err = run_cmd("{} {} {} {}".format(fmsbuildlib, fmsbuildroot, fmsinstallpath, caseroot), verbose=True)
Implemented suggested change.

2024-04-16 16:45 UTC, jtruesdal commented on cime_config/buildlib
> +                    if not os.path.exists(fmsbuildlib):
Wow.  Great catch.  I missed an update when getting the code ready for submitting the PR.  fmsbuildlib is now defined and I tested that the routine does build libfms correctly.

2024-04-16 16:45 UTC, jtruesdal commented on cime_config/buildlib
> +                        expect(stat==0, "FMS build Failed {}".format(err))
Added suggested change.

2024-04-16 16:45 UTC, jtruesdal commented on cime_config/testdefs/testlist_cam.xml
> +      <machine name="izumi" compiler="gnu" category="aux_cam"/>
Added comment as recommended.

2024-04-16 16:45 UTC, jtruesdal commented on doc/ChangeLog
> +  ERP_Ln9.C96_C96_mg17.F2000climo.derecho_intel.cam-outfrq9s_mg3 (Overall: PEND) details:
Checked with create_test and this test is passing.  FV3 is now expected to run but  the compare to baseline tests will show failures since it's been broken for previous tags.  These tests will be checked again when I rerun the regression tests before tagging.

2024-04-16 21:53 UTC, cacraigucar approved these changes

2024-04-16 21:53 UTC, nusbaume approved these changes
Looks  good to me now, thanks!

2024-04-17 20:11 UTC, merged