add pointers in cslam for intel performance (and update cime external?)
ESCOMP/CAM pull request #998
Opened 2024-03-18 20:49 UTC by adamrher

Fixes #955 

For the new cesm2.2 tag, we will need to update the cime external as in https://github.com/ESMCI/cime/pull/4559 i/o performance issues with VR grids. Should we update the external in the cam tag?

2024-03-19 16:33 UTC, adamrher commented
Updated cime exterrnal and ran a cslam test case to completion. The cime tag has a weird name ```maint-5.8_5.8.32``` but I think it's the correct tag. Provided it is, I think regressions testing can start.

2024-04-12 21:09 UTC, cacraigucar requested changes
If I have access to your fork, and you are okay with it, I can put in the updated tag when it is made.  I will also need to make a ChangeLog for this commit, and can add it when it is ready.

2024-04-12 21:09 UTC, cacraigucar commented on Externals.cfg
> +tag = maint-5.8_5.8.32
I have requested a tag to be made for the head of this branch.  When it is made, we will use that tag.

2024-04-12 21:09 UTC, cacraigucar commented on src/dynamics/se/dycore/fvm_consistent_se_cslam.F90
> +         !call t_stopf('fvm:swept_flux')
I know you didn't make this change, but I'm wondering why these timers were commented out.  I would suggest it makes sense to uncomment them, so they are available if folks wanted to time these routines.

2024-04-12 21:38 UTC, cacraigucar commented on Externals.cfg
> +tag = maint-5.8_5.8.32
The tag has been made and it is:  5.8.32.10

2024-05-20 22:59 UTC, cacraigucar reviewed
Still need to squash bugs, but the code looks fine

2024-05-20 23:00 UTC, cacraigucar approved these changes

2024-06-17 18:53 UTC, cacraigucar commented
It was decided to not continue supporting the cesm2_2 branch, so this PR is being closed without being implemented.

2024-06-17 18:53 UTC, closed without merging